#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""İdari Dava Türleri — İYUK m.2, m.7, m.10, m.12-13 odaklı 60 soru."""
from topic_pack_builder import write_topic


def R(scenario, focus, correct, bank, why, ref, difficulty="medium"):
    return locals()


WRONG = {
    "tur": [
        "Dava yalnız idarenin cezalandırılmasını amaçlayan bir ceza davası olarak adli yargıda açılabilir",
        "İdari işlemin hukuka uygunluğu incelenmeden yalnız ekonomik yararlılığı hakkında bağlayıcı görüş verilir",
        "Davacıdan menfaat veya hak bağlantısı aranmadan herkes adına soyut norm denetimi yapılması zorunludur",
        "Uyuşmazlık idari nitelikte olsa bile sadece tarafların seçtiği özel hakem kurulu kesin karar verebilir",
        "Mahkeme idari işlemin yerine geçerek aynı konuda yeni bir işlem kurar ve idarenin takdirini doğrudan kullanır",
        "Dava türü ne olursa olsun tek mümkün sonuç yalnız parasal tazminattır; işlemin iptali istenemez",
        "İdari eylem ve işlemlerden doğan uyuşmazlıkların tamamı görev ayrımı yapılmadan tüketici mahkemesinde görülür",
        "İdari sözleşmelerden doğan her uyuşmazlık tahkim şartı bulunup bulunmadığına bakılmadan idari yargıda görülür",
    ],
    "unsur": [
        "İşlemi yapan makamın kamu yararı bakımından daha kârlı bir seçeneği tercih etmemiş olması tek başına bu unsuru sakatlar",
        "İdarenin işlemden sonra bütçe imkânının azalması, kanuni unsurlardan bağımsız olarak işlemi kendiliğinden yok hükmünde kılar",
        "Davacının işlemi beğenmemesi, somut hukuka aykırılık aranmadan bu unsur yönünden iptal için yeterlidir",
        "Mahkemenin idare yerine geçerek yeni gerekçe üretmesi ve işlemi bu gerekçeyle sürdürmesi bu unsurun denetimidir",
        "İşlemin sonuçlarının siyasal bakımdan elverişsiz görülmesi, hukuki ölçüt aranmadan bu unsurun ihlali sayılır",
        "Yetkili makamın işlem yapmış olması hâlinde diğer bütün unsurların kanuna aykırılığı önemini tamamen kaybeder",
        "İşlemin sözlü veya yazılı olmasından bağımsız olarak bütün usul kuralları yalnız tavsiye niteliğindedir",
        "İdari işlemin amacı, sebebi ve konusu arasında hiçbir hukuki bağ kurulamaz; unsurlar ayrı davalarda incelenir",
    ],
    "sonuc": [
        "İptal kararı yalnız davacıya gelecekte uygulanır; işlemin tesis edildiği tarihe ve diğer ilgililere hiçbir etkisi olmaz",
        "Tam yargı davasında zarar ve nedensellik bağı araştırılmaz; idarenin her işleminde otomatik tazminata hükmedilir",
        "İptal davası açılması işlemin yürütmesini kendiliğinden durdurur ve ayrıca karar verilmesine gerek bırakmaz",
        "İptal ve tam yargı talepleri hiçbir koşulda aynı dilekçede ileri sürülemez; kanun bunu mutlak olarak yasaklar",
        "İdari eylemden doğan zarar için idareye ön başvuru yapılmadan her zaman doğrudan tam yargı davası açılması zorunludur",
        "Düzenleyici işlem süresinde dava edilmemişse daha sonra uygulama işlemiyle birlikte hiçbir şekilde ileri sürülemez",
        "Mahkeme iptal davasında hukuka uygunluk yerine yalnız yerindelik incelemesi yaparak en yararlı işlemi seçer",
        "İdari işlemden doğan zarar için önce iptal davası açılması mutlak şarttır; doğrudan tam yargı yolu kapalıdır",
    ],
}


RULES = [
    R("Bir ruhsat iptalinin hukuka aykırı olduğunu ileri süren ve işlemle güncel menfaati zedelenen kişi hangi dava türüne başvurur?", "İdari işlemin hukuka aykırılığı nedeniyle hukuk düzeninden kaldırılmasını amaçlayan dava hangisidir?", "İptal davası", "tur", "İptal davası, menfaati ihlal edilen kişinin idari işlemin hukuka aykırılığı nedeniyle ortadan kaldırılmasını istemesidir.", "2577 sayılı İYUK m.2/1-a", "easy"),
    R("İdari eylem nedeniyle bedensel zarara uğrayan kişinin maddi ve manevi kaybını gidermek için açacağı dava hangisidir?", "Kişisel hakkı doğrudan ihlal edilen kişinin zararının giderilmesini amaçlayan idari dava hangisidir?", "Tam yargı davası", "tur", "İdari eylem veya işlem nedeniyle kişisel hakkı doğrudan ihlal edilen kişi tam yargı davası açabilir.", "2577 sayılı İYUK m.2/1-b", "easy"),
    R("Tahkim yolu öngörülmeyen kamu hizmeti idari sözleşmesinden taraflar arasında uyuşmazlık çıkmıştır. Dava türü nasıl nitelendirilir?", "İYUK m.2'de üçüncü idari dava türü olarak düzenlenen uyuşmazlık hangisidir?", "İdari sözleşmeden doğan dava", "tur", "Kamu hizmetinin yürütülmesi için yapılan idari sözleşmelerden doğan taraf uyuşmazlıkları, tahkim istisnası dışında idari dava türüdür.", "2577 sayılı İYUK m.2/1-c"),
    R("Bir idari işlem davacının yalnız meşru, kişisel ve güncel menfaatini zedelemiştir; doğrudan kişisel hak ihlali kanıtlanamamıştır. Hangi dava uygundur?", "İptal davasında davacı ile işlem arasındaki bağ için aranan temel ölçüt nedir?", "Menfaat ihlali yeterlidir", "tur", "İptal davasında kişisel hakkın doğrudan ihlali değil, meşru ve güncel menfaat ilişkisinin bulunması aranır.", "2577 sayılı İYUK m.2/1-a"),
    R("İdarenin eylemi kişinin malvarlığında doğrudan kayba yol açmıştır. Tam yargı davası ehliyeti bakımından hangi bağ aranır?", "Tam yargı davasını iptal davasından ayıran davacı bağlantısı hangisidir?", "Kişisel hakkın doğrudan ihlali", "tur", "Tam yargı davası, idari eylem veya işlem nedeniyle kişisel hakkı doğrudan ihlal edilenlerce açılır.", "2577 sayılı İYUK m.2/1-b"),
    R("Bir işlemin kanunen başka makama ait olmasına rağmen yetkisiz bir birimce tesis edildiği ileri sürülmektedir. İptal sebebi hangi unsura ilişkindir?", "İşlemi tesis eden makamın kanuni görev alanını ifade eden idari işlem unsuru hangisidir?", "Yetki unsuru", "unsur", "Yetki unsuru, idari işlemi hangi makamın ve hangi görev alanında tesis edebileceğini gösterir.", "2577 sayılı İYUK m.2/1-a", "easy"),
    R("Kanunun zorunlu tuttuğu kurul görüşü alınmadan idari işlem yapılmıştır. Hukuka aykırılık öncelikle hangi unsurdadır?", "İdari işlemin hazırlanması ve açıklanmasında uyulacak usul kurallarını ifade eden unsur hangisidir?", "Şekil unsuru", "unsur", "Zorunlu usul ve biçim kurallarına uyulmaması işlemin şekil unsurunu sakatlar.", "2577 sayılı İYUK m.2/1-a"),
    R("Disiplin cezasına dayanak gösterilen olay gerçekte hiç gerçekleşmemiştir. İptal denetimi hangi unsura yönelir?", "İdareyi işlem yapmaya sevk eden maddi ve hukuki olguları ifade eden unsur hangisidir?", "Sebep unsuru", "unsur", "İdari işlemin sebebi, işlemi doğuran maddi olay ile hukuki dayanağın gerçek ve hukuka uygun olmasını gerektirir.", "2577 sayılı İYUK m.2/1-a"),
    R("Kanunun izin verdiğinden farklı bir hukuki sonuç doğuran idari karar alınmıştır. İptal sebebi hangi unsurla ilgilidir?", "İdari işlemin hukuk âleminde meydana getirdiği sonucu ifade eden unsur hangisidir?", "Konu unsuru", "unsur", "Konu, işlemin doğurduğu hukuki sonuçtur; kanunun öngörmediği sonuç konu yönünden hukuka aykırılık oluşturur.", "2577 sayılı İYUK m.2/1-a"),
    R("Kamu yararı yerine belirli bir kişiye çıkar sağlamak amacıyla yetki kullanılmıştır. Hangi unsur sakatlanmıştır?", "İdari işlemin kamu yararı doğrultusundaki nihai yönelimini ifade eden unsur hangisidir?", "Maksat unsuru", "unsur", "İdari işlemlerde genel amaç kamu yararıdır; yetkinin kişisel çıkar için kullanılması maksat sakatlığıdır.", "2577 sayılı İYUK m.2/1-a"),
    R("Mahkeme, idari işlemin hukuka uygunluğunu denetlemek yerine hangi seçeneğin ekonomik olarak daha yararlı olduğuna karar vermek istemektedir. Bu mümkün müdür?", "İdari yargı yetkisinin sınırlarından biri aşağıdakilerden hangisidir?", "Yerindelik denetimi yapılamaz", "tur", "İdari yargı hukuka uygunluğu denetler; idarenin tercihinin yararlılığına ilişkin yerindelik denetimi yapamaz.", "2577 sayılı İYUK m.2/2"),
    R("Mahkeme iptal ettiği işlemin yerine geçecek yeni ruhsat koşullarını kendisi belirlemek istemektedir. İYUK bakımından sonuç nedir?", "İdari yargı merciinin idari işlem niteliğinde karar vermesine ilişkin kural hangisidir?", "İdari işlem niteliğinde karar veremez", "tur", "Mahkeme hukuka uygunluğu denetler; idare yerine geçerek idari eylem veya işlem niteliğinde karar kuramaz.", "2577 sayılı İYUK m.2/2"),
    R("Kanunun idareye bıraktığı iki hukuka uygun seçenekten hangisinin kullanılacağını mahkeme doğrudan belirlemek istemektedir. Bu yaklaşım nasıldır?", "İdari yargı kararının idarenin takdir yetkisi üzerindeki sınırı hangisidir?", "Takdir yetkisini kaldıracak karar verilemez", "tur", "Yargı, takdirin hukuka uygunluğunu denetleyebilir; fakat idarenin takdir yetkisini tümüyle kaldıracak biçimde karar veremez.", "2577 sayılı İYUK m.2/2"),
    R("Hak ihlaline yol açan idari işleme karşı kişi hem işlemin kaldırılmasını hem zararının giderilmesini istemektedir. Talepler nasıl ileri sürülebilir?", "İdari işlemden doğan iptal ve tam yargı taleplerinin birlikte ileri sürülmesi mümkün müdür?", "İptal ve tam yargı davaları birlikte açılabilir", "sonuc", "İlgili, hak ihlal eden işlem nedeniyle iptal ve tam yargı davalarını birlikte açabilir.", "2577 sayılı İYUK m.12"),
    R("Hak ihlal eden idari işlem nedeniyle kişi zararının giderilmesini istiyor ancak işlemin iptalini talep etmiyor. İYUK m.12 hangi yolu tanır?", "İdari işlemden doğan zarar için önce iptal davası açılması zorunlu mudur?", "Doğrudan tam yargı davası açılabilir", "sonuc", "İYUK m.12, ilgiliye doğrudan tam yargı davası açma seçeneği tanır; önce iptal davası zorunlu değildir.", "2577 sayılı İYUK m.12"),
    R("Kişi önce iptal davası açmış ve karar kendisine tebliğ edilmiştir. İşlemden doğan zarar için hangi imkân korunur?", "Önce iptal davası açan kişinin sonradan tam yargı davası açmasına ilişkin kural hangisidir?", "Kararın tebliğinden sonra süresinde tam yargı davası açabilir", "sonuc", "İptal davasının karara bağlanmasından sonra kararın veya kanun yolu kararının tebliğinden itibaren dava süresi içinde tam yargı davası açılabilir.", "2577 sayılı İYUK m.12"),
    R("İdari işlem uygulanmış ve zarar uygulama tarihinde doğmuştur. Önce iptal davası açan kişi tam yargı talebini hangi olaya bağlayabilir?", "İşlemin icrası nedeniyle doğan zararda sonraki tam yargı davası için süre hangi tarihle ilişkilendirilebilir?", "İcra tarihinden itibaren", "sonuc", "İşlemin icrası nedeniyle zarar doğmuşsa tam yargı davası icra tarihinden başlayarak dava süresi içinde açılabilir.", "2577 sayılı İYUK m.12"),
    R("Belediyenin fiilî çalışması bir taşınmaza zarar vermiş, önceden dava edilebilir yazılı işlem bulunmamaktadır. Dava öncesinde ne yapılır?", "İdari eylemden doğan tam yargı davasında kural olarak zorunlu ilk adım hangisidir?", "İdareye hakların yerine getirilmesi için başvurulur", "sonuc", "İdari eylemden doğan zarar için dava açmadan önce ilgili idareye hakkın yerine getirilmesi amacıyla ön başvuru yapılır.", "2577 sayılı İYUK m.13"),
    R("İdari eylemden zarar gören kişi eylemi ve faili öğrendiği tarihten sonra başvuru yapacaktır. Kanun hangi iki üst sınırı birlikte öngörür?", "İdari eylemden doğan ön başvurunun yapısal süreleri hangileridir?", "Öğrenmeden itibaren bir yıl, eylemden itibaren beş yıl", "sonuc", "İYUK m.13 başvuruyu, eylemin öğrenilmesinden itibaren bir yıl ve her hâlde eylem tarihinden itibaren beş yıl ile sınırlar.", "2577 sayılı İYUK m.13", "hard"),
    R("İdari eylem başvurusuna idare kısmen olumsuz cevap vermiştir. Zarar gören ne yapabilir?", "İdari eylem ön başvurusunun kısmen reddi sonrasında tanınan yol hangisidir?", "Ret kısmı için dava açabilir", "sonuc", "İstek kısmen veya tamamen reddedilirse ret işleminin tebliğinden sonra dava süresi içinde tam yargı davası açılabilir.", "2577 sayılı İYUK m.13"),
    R("İdari eylem nedeniyle yapılan zorunlu ön başvuruya idare süresinde cevap vermemiştir. Bu susma hangi sonucu doğurur?", "İYUK m.13 başvurusunda idarenin sessiz kalması dava yolunu nasıl etkiler?", "İstek reddedilmiş sayılır ve dava yolu açılır", "sonuc", "Kanuni cevap süresinde yanıt verilmemesi zımni ret oluşturur; ilgili dava açma süresi içinde tam yargı davasına başvurabilir.", "2577 sayılı İYUK m.13"),
    R("İlan edilen düzenleyici işlem süresinde dava edilmemiş, daha sonra kişiye bu düzenlemeye dayalı uygulama işlemi yapılmıştır. Hangi yol mümkündür?", "Düzenleyici işlemin uygulanması üzerine dava hakkına ilişkin kural hangisidir?", "Uygulama işlemiyle birlikte düzenleyici işlem de dava edilebilir", "sonuc", "Uygulama üzerine ilgili, düzenleyici işleme, uygulama işlemine veya her ikisine birlikte dava açabilir.", "2577 sayılı İYUK m.7/4"),
    R("Düzenleyici işlem daha önce iptal edilmemiştir; buna dayanan bireysel uygulama işleminde hukuka aykırılık ileri sürülmektedir. Bu durum davayı engeller mi?", "Düzenleyici işlemin iptal edilmemiş olmasının uygulama işlemine etkisi hangisidir?", "Uygulama işleminin iptaline engel olmaz", "sonuc", "Düzenleyici işlemin daha önce iptal edilmemiş olması, ona dayalı uygulama işleminin hukuka aykırılık nedeniyle iptaline engel değildir.", "2577 sayılı İYUK m.7/4"),
    R("İptal davası sonucunda işlem hukuka aykırı bulunarak kaldırılmıştır. Kararın temel işlevi nedir?", "İptal davasının objektif hukuka uygunluk denetimindeki sonucu hangisidir?", "Hukuka aykırı işlemi hukuk düzeninden kaldırmak", "sonuc", "İptal davasının temel işlevi hukuka aykırı idari işlemi hukuk düzeninden çıkarmaktır; tazminat tam yargının konusudur.", "2577 sayılı İYUK m.2/1-a"),
    R("Tam yargı davasında zarar kanıtlanmış ancak idari eylem ile zarar arasında bağ kurulamamıştır. Tazminat için eksik olan unsur hangisidir?", "İdarenin tazmin sorumluluğunda zarar ile idari faaliyet arasında aranan bağ hangisidir?", "Nedensellik bağı", "sonuc", "Tam yargı davasında gerçek zarar yanında zararın idari faaliyetle uygun nedensellik bağı içinde olması gerekir.", "2577 sayılı İYUK m.2/1-b; idari sorumluluğun genel esasları"),
    R("İmtiyaz sözleşmesinde uyuşmazlık için geçerli tahkim yolu açıkça öngörülmüştür. İYUK m.2/1-c kapsamı bakımından sonuç nedir?", "İdari sözleşme davaları bakımından kanunda belirtilen tahkim istisnası hangisidir?", "Uyuşmazlık idari sözleşme davası kapsamı dışında kalır", "tur", "Tahkim yolu öngörülen imtiyaz şartlaşma ve sözleşmelerinden doğan uyuşmazlıklar İYUK m.2/1-c kapsamındaki idari sözleşme davalarından ayrılmıştır.", "2577 sayılı İYUK m.2/1-c", "hard"),
]


def V(correct, distractors, focus, focus_correct, focus_distractors, focus_why,
      focus_ref=None, focus_difficulty=None):
    item = {
        "correct": correct,
        "distractors": distractors,
        "focus": focus,
        "focus_correct": focus_correct,
        "focus_distractors": focus_distractors,
        "focus_why": focus_why,
    }
    if focus_ref:
        item["focus_ref"] = focus_ref
    if focus_difficulty:
        item["focus_difficulty"] = focus_difficulty
    return item


VARIANTS = [
    V(
        "Hukuka aykırı ruhsat işleminin iptali için iptal davası açar",
        [
            "Yalnız uğradığı zararın belirlenmesi için tam yargı davası açar",
            "İdari işlemin ekonomik yararını ölçmek için tespit davası açar",
            "Ruhsat kararını değiştirmesi için doğrudan adli yargıya başvurur",
            "İdarenin cezalandırılması amacıyla kamu davası açılmasını ister",
        ],
        "İptal davasının konusu olabilecek idari işlem bakımından hangi nitelik aranır?",
        "Kesin ve yürütülmesi zorunlu, hukuki sonuç doğuran bir idari işlem olması",
        [
            "İdarenin henüz hiçbir hukuki sonuç doğurmayan hazırlık görüşü olması",
            "Kamu görevlisinin yalnız kişisel kanaatini açıklayan sözlü beyanı olması",
            "Özel kişiler arasındaki borç sözleşmesinin ifasına ilişkin olması",
            "İdarenin işlem niteliği taşımayan ve yalnız fiilî sonuç doğuran her türlü maddi hareketi olması",
        ],
        "İptal davası, idarenin kesin ve yürütülmesi zorunlu hukuki sonuç doğuran işlemlerine yönelir; hazırlık işlemleri veya salt görüş açıklamaları tek başına iptal davasına konu olmaz.",
        "2577 sayılı İYUK m.2/1-a, m.14/3-d, m.15/1-b",
        "medium",
    ),
    V(
        "Zararın giderilmesi için idari yargıda tam yargı davası açar",
        [
            "Eylemin hukuk düzeninden kaldırılması için iptal davası açar",
            "İdare adına yeni bir işlem kurulması için eda davası açar",
            "Yalnız eylemi yapan personel hakkında ceza davası açabilir",
            "Bedensel zarar idari eylemden doğduğu için hiçbir dava açamaz",
        ],
        "Tam yargı davası aşağıdaki idari faaliyetlerden hangilerinden doğabilir?",
        "Kişisel hakkı doğrudan ihlal eden idari işlem veya idari eylemden",
        [
            "Yalnız genel düzenleyici işlemin yayımlanmasından, zarar aranmaksızın",
            "Sadece özel kişiler arasındaki ticari sözleşmenin geçersizliğinden",
            "Yalnız mahkemenin kesinleşmiş kararının hukuka aykırılığından",
            "İdarenin hiçbir etkisinin bulunmadığı tüm toplumsal olaylardan",
        ],
        "İYUK m.2/1-b, kişisel hakkı doğrudan ihlal eden idari işlem ve eylemlerin her ikisini de tam yargı davasının kaynağı olarak kabul eder.",
        "2577 sayılı İYUK m.2/1-b",
        "easy",
    ),
    V(
        "Uyuşmazlık, idari sözleşmeden doğan idari dava niteliğindedir",
        [
            "Uyuşmazlık yalnız sözleşme bedeli nedeniyle vergi davası niteliğindedir",
            "Uyuşmazlık her durumda özel hukuk tüketici davası niteliğindedir",
            "Uyuşmazlık sözleşmeyi yapan idarenin kesin olarak çözeceği bir iştir",
            "Uyuşmazlık geçerli tahkim şartı varmış gibi zorunlu hakemlik konusudur",
        ],
        "İYUK m.2/1-c kapsamındaki idari sözleşme davası için sözleşme ve uyuşmazlık bakımından hangi bağ aranır?",
        "Kamu hizmetinin yürütülmesi için yapılan idari sözleşmenin tarafları arasında çıkması",
        [
            "Herhangi iki özel kişi arasındaki sözleşmeden doğmuş olması",
            "İdari sözleşmeyle ilgisi olmayan üçüncü kişinin soyut görüşüne dayanması",
            "Yalnız sözleşmenin noter tarafından düzenlenmiş bulunması",
            "Kamu hizmetiyle ilgisiz bir mal satışına ilişkin ticari sözleşmenin tarafları arasında doğması",
        ],
        "İYUK m.2/1-c, kamu hizmetlerinden birinin yürütülmesi için yapılan idari sözleşmelerden dolayı taraflar arasında çıkan uyuşmazlıkları kapsar; tahkimli imtiyaz uyuşmazlıkları istisnadır.",
        "2577 sayılı İYUK m.2/1-c",
        "medium",
    ),
    V(
        "Meşru, kişisel ve güncel menfaat bağı bulunduğundan iptal davası açabilir",
        [
            "Doğrudan parasal hakkını kanıtlayamadığından hiçbir idari dava açamaz",
            "Yalnız idarenin cezalandırılması için ceza mahkemesine başvurabilir",
            "İşlemle ilgisi bulunmasa da herkes adına soyut iptal davası açabilir",
            "Menfaat bağı yalnız tam yargı davası için yeterli olduğundan tazminat ister",
        ],
        "İptal davasındaki menfaat ihlali koşulu aşağıdakilerden hangisini ifade eder?",
        "Davacı ile dava konusu işlem arasında meşru, kişisel ve güncel bir ilgi bulunmasını",
        [
            "Davacının mutlaka doğmuş ve miktarı belirli bir parasal alacağını tüm hesap belgeleriyle kanıtlamasını",
            "Her vatandaşın ilgisi olmayan her idari işleme karşı dava açabilmesini",
            "Yalnız taşınmaz mülkiyetinin doğrudan ve tamamen ortadan kalkmasını",
            "İşlemi yapan kamu görevlisiyle davacı arasında sözleşme bulunmasını",
        ],
        "Menfaat ihlali, iptal davasında davacının işlemle meşru, kişisel ve güncel bir bağının bulunmasıdır; tam yargıdaki doğrudan kişisel hak ihlaliyle aynı koşul değildir.",
        "2577 sayılı İYUK m.2/1-a",
        "easy",
    ),
    V(
        "Tam yargı davası için kişisel hakkın doğrudan ihlali aranır",
        [
            "Herhangi bir vatandaşlık ilgisi tam yargı davası için yeterlidir",
            "Yalnız işlemin ekonomik açıdan yararsız görülmesi tazminat için yeterlidir",
            "Zarar bulunmasa da idari eylemin varlığı otomatik tazminat doğurur",
            "Kişisel hak ihlali yerine yalnız genel kamu yararı iddiası aranır",
        ],
        "Bir idari işlemle yalnız genel ve dolaylı biçimde ilgilenen kişi, kişisel hakkının doğrudan ihlalini gösteremiyorsa hangi sonuç doğar?",
        "Bu bağ tek başına tam yargı davasında davacı sıfatı için yeterli değildir",
        [
            "Dolaylı ilgi bulunduğu anda idare otomatik olarak tazminat öder",
            "Kişisel hak ihlali yalnız iptal davasında arandığından tam yargı açılır",
            "İşlemin idari olması doğrudan hak ihlali koşulunu gereksiz kılar",
            "Her vatandaş, kişisel zararını ve doğrudan hak ihlalini göstermeden kamu adına aynı zarar için tam yargı davası açabilir",
        ],
        "Tam yargı davasında genel veya dolaylı ilgi değil, davacının kişisel hakkının idari işlem ya da eylem nedeniyle doğrudan ihlal edilmesi gerekir.",
        "2577 sayılı İYUK m.2/1-b",
        "medium",
    ),
    V(
        "İşlem, işlemi yapan makam yönünden yetki unsurunda sakattır",
        [
            "İşlem yalnız doğurduğu sonuç nedeniyle konu unsurunda sakattır",
            "İşlem yalnız hazırlanış yöntemi nedeniyle şekil unsurunda sakattır",
            "İşlem dayandığı maddi olay nedeniyle sebep unsurunda sakattır",
            "İşlem güdülen nihai amaç nedeniyle maksat unsurunda sakattır",
        ],
        "Yetki unsuru denetlenirken aşağıdakilerden hangisi incelenir?",
        "İşlemi tesis eden makamın konu, yer, zaman ve kişi bakımından yetkili olup olmadığı",
        [
            "İşlemin doğurduğu hukuki sonucun kanunda öngörülüp öngörülmediği",
            "İşleme dayanak maddi olayın gerçekte meydana gelip gelmediği",
            "İdarenin yetkisini kamu yararı yerine kişisel amaçla kullanıp kullanmadığı",
            "Karar öncesinde uyulması zorunlu bütün usul adımlarının ve kurul görüşlerinin tamamlanıp tamamlanmadığı",
        ],
        "Yetki denetimi, idari makamın işlemi konu, yer, zaman ve kişi bakımından tesis etmeye kanunen yetkili olup olmadığını araştırır.",
        "2577 sayılı İYUK m.2/1-a",
        "medium",
    ),
    V(
        "Zorunlu görüşün alınmaması işlemin şekil unsurunu sakatlar",
        [
            "Zorunlu görüşün alınmaması işlemin yalnız konu unsurunu sakatlar",
            "Zorunlu görüşün alınmaması işlemin yalnız maksat unsurunu sakatlar",
            "Zorunlu görüşün alınmaması işlemin yalnız sebep unsurunu sakatlar",
            "Zorunlu görüşün alınmaması hiçbir hukuki sonuç doğurmaz",
        ],
        "Aşağıdakilerden hangisi idari işlemin şekil unsuruna ilişkin bir denetimdir?",
        "Kanunun öngördüğü karar usulüne ve zorunlu imza sürecine uyulup uyulmadığı",
        [
            "İşlemi yapan makamın başka bir kurumun görev alanına girip girmediği",
            "İşleme dayanak gösterilen maddi olayın gerçek olup olmadığı",
            "İşlemin hukuk düzeninde doğurduğu sonucun kanuna uygun olup olmadığı",
            "Yetkinin kamu yararı dışında kişisel amaçla kullanılıp kullanılmadığı",
        ],
        "Şekil unsuru, işlemin hazırlanması, karara bağlanması ve açıklanmasında kanunun zorunlu tuttuğu usul ve biçim kurallarını kapsar.",
        "2577 sayılı İYUK m.2/1-a",
        "easy",
    ),
    V(
        "Gerçekleşmeyen olayın dayanak alınması işlemin sebep unsurunu sakatlar",
        [
            "Gerçekleşmeyen olay işlemin yalnız yetki unsurunu sakatlar",
            "Gerçekleşmeyen olay işlemin yalnız şekil unsurunu sakatlar",
            "Gerçekleşmeyen olay işlemin yalnız konu unsurunu sakatlar",
            "Gerçekleşmeyen olay hukuka uygunluk denetiminde dikkate alınamaz",
        ],
        "İdari işlemin sebep unsuru hangi iki dayanak yönünden incelenir?",
        "İdareyi işlem yapmaya sevk eden maddi olgu ve hukuki dayanak yönünden",
        [
            "Yalnız işlemin ekonomik getirisi ve bütçeye sağlayacağı tasarruf yönünden",
            "Sadece işlemi imzalayan görevlinin kişisel kanaati ve kıdemi yönünden",
            "İşlemin tebliğ edildiği adres ve davacının yerleşim yeri yönünden",
            "Yalnız işlemin gelecekte doğurabileceği siyasi sonuçlar yönünden",
        ],
        "Sebep unsuru, idareyi işlem yapmaya yönelten maddi olayların gerçekliği ile işlemin dayandığı hukuki nedenin geçerliliğini kapsar.",
        "2577 sayılı İYUK m.2/1-a",
        "medium",
    ),
    V(
        "Kanunda bulunmayan sonuç işlemin konu unsurunu hukuka aykırı kılar",
        [
            "Kanunda bulunmayan sonuç yalnız işlemin şekil unsurunu etkiler",
            "Kanunda bulunmayan sonuç yalnız işlemin yetki unsurunu etkiler",
            "Kanunda bulunmayan sonuç mahkemece yeni gerekçeyle tamamlanır",
            "Kanunda bulunmayan sonuç idarenin takdirinde olduğundan denetlenemez",
        ],
        "İdari işlemin konu unsuru aşağıdakilerden hangisini ifade eder?",
        "İşlemin hukuk düzeninde meydana getirdiği hukuki sonucu",
        [
            "İşlemi yapan makamın yer ve zaman bakımından görev alanını",
            "İdareyi işlem tesis etmeye yönelten maddi ve hukuki nedenleri",
            "Kararın alınmasında uyulan yazılı usul ve imza aşamalarını",
            "İşlemle ulaşılmak istenen kamu yararına yönelik nihai amacı",
        ],
        "Konu, idari işlemin hukuk âleminde doğurduğu sonuçtur. İdarenin kanunun izin vermediği bir sonucu kararlaştırması konu yönünden hukuka aykırıdır.",
        "2577 sayılı İYUK m.2/1-a",
        "easy",
    ),
    V(
        "Yetki kişisel çıkar için kullanıldığından maksat unsuru sakatlanır",
        [
            "Yetkili makam işlem yaptığı için bütün unsurlar hukuka uygundur",
            "Kişisel amaç yalnız şekil unsurunu etkiler ve sonucu değiştirmez",
            "Kişisel amaç yalnız konu unsuruna ilişkin teknik bir eksikliktir",
            "İdarenin amacı hiçbir durumda yargısal denetime konu edilemez",
        ],
        "Yetkili makam, biçim ve sebep kurallarına uysa bile yetkiyi kanunun öngördüğü kamu yararı dışında kullanırsa hangi sakatlık doğar?",
        "Yetki saptırması niteliğinde maksat yönünden hukuka aykırılık doğar",
        [
            "Diğer unsurlar uygun olduğu için işlem bütünüyle denetim dışında kalır",
            "Yalnız işlemin yazım biçimine ilişkin önemsiz bir şekil eksikliği doğar",
            "Mahkemenin idare yerine yeni işlem kurmasını gerektiren görev sorunu doğar",
            "Dava yalnız işlemi yapan kamu görevlisinin ceza sorumluluğuna dönüşür",
        ],
        "İdari yetkinin kanundaki amaç ve kamu yararı dışında kullanılması yetki saptırmasıdır ve işlemi maksat unsuru yönünden hukuka aykırı kılar.",
        "2577 sayılı İYUK m.2/1-a",
        "medium",
    ),
    V(
        "Hayır; mahkeme yararlılık tercihi yaparak yerindelik denetimine geçemez",
        [
            "Evet; mahkeme idarenin yerine geçerek ekonomik açıdan en yararlı seçeneği belirler",
            "Evet; mahkeme yalnız davacının tercih ettiği seçeneğin yerindeliğini denetler",
            "Hayır; çünkü idarenin bütün işlemleri hukuka uygunluk denetimi dışındadır",
            "Hayır; yalnız Sayıştay idari işlemlerin hukuka uygunluğunu inceleyebilir",
        ],
        "Yerindelik denetimi yasağı, mahkemenin aşağıdaki incelemelerden hangisini yapmasına engel değildir?",
        "İdari tercihin kanun, kamu yararı ve ölçülülük sınırlarına uygunluğunu incelemesine",
        [
            "İdarenin yerine geçip hizmet politikasını ve bütçe önceliklerini yeniden seçmesine",
            "Kanundaki seçeneklerden hangisinin ekonomik açıdan daha kârlı olduğunu belirlemesine",
            "İdari makam adına yeni bir ruhsat düzenleyerek başvurucuya doğrudan vermesine",
            "İdarenin takdir yetkisini ortadan kaldırıp uygulanacak tek seçeneği belirlemesine",
        ],
        "Yerindelik yasağı hukuka uygunluk denetimini kaldırmaz. Mahkeme takdirin kanuni sınırlar, kamu yararı ve ölçülülük ilkesi içinde kullanılıp kullanılmadığını inceleyebilir.",
        "2577 sayılı İYUK m.2/2; Anayasa m.125",
        "hard",
    ),
    V(
        "Mahkeme idare yerine ruhsat koşulu belirleyen işlem niteliğinde karar veremez",
        [
            "Mahkeme iptal kararının yanında yeni ruhsat koşullarını doğrudan belirlemek zorundadır",
            "Mahkeme davalı idarenin bütün düzenleme yetkisini kendiliğinden devralır",
            "Mahkeme yalnız taraflar anlaşırsa idari makam adına yeni ruhsat düzenleyebilir",
            "Mahkeme hukuka uygunluk incelemeden en yararlı ruhsat koşulunu seçebilir",
        ],
        "İYUK m.2/2'deki idari işlem niteliğinde karar verme yasağına uygun yargısal sonuç hangisidir?",
        "Mahkemenin hukuka aykırı işlemi iptal edip yeni işlemi yetkili idareye bırakması",
        [
            "Mahkemenin iptal ettiği atama yerine kimin atanacağını doğrudan seçmesi",
            "Mahkemenin idare adına ruhsat düzenleyip teknik şartlarını belirlemesi",
            "Mahkemenin kamu hizmetinin nasıl yürütüleceğini ayrıntılı olarak planlaması",
            "Mahkemenin bütçe ödeneğini idari makam yerine başka hizmete aktarması",
        ],
        "Mahkeme işlemi hukuka aykırı bulup iptal edebilir; fakat iptal edilen işlemin yerine geçecek yeni idari işlemi tesis etmek yetkili idarenin görevidir.",
        "2577 sayılı İYUK m.2/2",
        "medium",
    ),
    V(
        "Mahkeme idarenin takdir yetkisini tümüyle ortadan kaldıracak karar veremez",
        [
            "Mahkeme kanundaki seçeneklerden birini idare adına doğrudan kullanmak zorundadır",
            "Mahkeme takdir yetkisi bulunan her işlemde hukuka uygunluk incelemesi yapamaz",
            "Mahkeme idarenin ekonomik tercihini kendi tercihiyle serbestçe değiştirebilir",
            "Mahkeme takdir yetkisini yalnız davacının yazılı izniyle ortadan kaldırabilir",
        ],
        "İdarenin takdir yetkisi bulunması yargısal denetimi bütünüyle ortadan kaldırır mı?",
        "Hayır; takdir yetkisinin hukuki sınırlar içinde kullanılıp kullanılmadığı denetlenir",
        [
            "Evet; takdir yetkisi bulunan işlem hiçbir hukuki ölçüte göre incelenemez",
            "Evet; fakat yalnız işlemi yapan makam denetim yapılmasına izin vermezse",
            "Hayır; mahkeme takdir yetkisini devralarak idare adına yeni karar verir",
            "Hayır; mahkeme yalnız ekonomik yararlılık yönünden yerindelik denetimi yapar",
        ],
        "Takdir yetkisi yargı denetimini kaldırmaz; sebep, amaç, ölçülülük ve kanuni sınırlar yönünden denetlenir. Mahkeme yalnız takdir yetkisini devralamaz veya ortadan kaldıramaz.",
        "2577 sayılı İYUK m.2/2; Anayasa m.125",
        "hard",
    ),
    V(
        "İşleme karşı iptal ve tam yargı taleplerini birlikte ileri sürebilir",
        [
            "Önce yalnız tam yargı davası açıp iptal talebinden kesin olarak vazgeçmek zorundadır",
            "İki talep hiçbir durumda birlikte ileri sürülemediğinden yalnız iptal isteyebilir",
            "Zarar bulunduğunda idari işlemin iptali yerine yalnız ceza davası açabilir",
            "Mahkemeden idare adına yeni işlem tesis etmesini ve tazminata hükmetmesini ister",
        ],
        "İYUK m.12 uyarınca iptal ve tam yargı taleplerinin birlikte açılabilmesinin temel koşulu nedir?",
        "Her iki talebin de hak ihlaline yol açan aynı idari işlemle bağlantılı olması",
        [
            "Taleplerden birinin idari işlemle ilgisiz özel hukuk borcuna dayanması",
            "İptal talebinin başka, tazminat talebinin ilgisiz bir kişiye ait olması",
            "Davacının idari işlemden kaynaklanan hiçbir hak ihlali ileri sürmemesi",
            "Mahkemenin idare adına yeni işlem kurmasının ayrıca istenmiş olması",
        ],
        "İYUK m.12, hakkı ihlal eden aynı idari işlem nedeniyle iptal ve tam yargı davalarının birlikte açılmasına izin verir; ilgisiz talepler bu düzenlemeyle birleşmez.",
        "2577 sayılı İYUK m.12",
        "medium",
    ),
    V(
        "İşlemden doğan zarar için doğrudan tam yargı davası açabilir",
        [
            "Önce iptal davası açmadıkça hiçbir tazminat talebinde bulunamaz",
            "Yalnız işlemi yapan kamu görevlisine karşı adli yargıda dava açabilir",
            "İptal istemediği için zararın idari yargıda giderilmesi mümkün değildir",
            "Tam yargı yerine idari işlemin ekonomik yararını inceleten tespit davası açar",
        ],
        "İdari işlemden doğan tam yargı davası için işlemin daha önce iptal edilmiş olması dava şartı mıdır?",
        "Hayır; İYUK m.12 doğrudan tam yargı davası açılmasına da izin verir",
        [
            "Evet; kesinleşmiş iptal kararı bulunmadıkça tazminat istemi dinlenmez",
            "Evet; ancak davalı idare iptal şartından yazılı olarak vazgeçebilir",
            "Hayır; çünkü idari işlemden doğan zararlar yalnız adli yargıda görülür",
            "Hayır; fakat doğrudan dava yalnız düzenleyici işlemler için mümkündür",
        ],
        "İYUK m.12 seçimlik yollar öngörür: ilgili doğrudan tam yargı davası açabilir, iptal ve tam yargıyı birlikte isteyebilir veya önce iptal sonra tam yargı yolunu kullanabilir.",
        "2577 sayılı İYUK m.12",
        "easy",
    ),
    V(
        "Kararın tebliğinden başlayacak dava süresi içinde tam yargı davası açabilir",
        [
            "İptal davası açtığı için sonradan tazminat isteme hakkı kesin olarak sona erer",
            "Tam yargı davasını süre aranmadan dilediği herhangi bir tarihte açabilir",
            "Yalnız iptal kararını veren hâkimden idare adına ödeme emri düzenlemesini ister",
            "Tazminat talebini yalnız görevli ceza mahkemesinde ileri sürebilir",
        ],
        "İptal davasında kanun yoluna başvurulmuşsa sonraki tam yargı davasının süresi hangi bildirimle ilişkilidir?",
        "Kanun yolu incelemesi sonunda verilen kararın tebliğiyle",
        [
            "İlk derece dava dilekçesinin idareye gönderildiği tarihle",
            "Dava konusu işlemin ilk kez hazırlandığı fakat tebliğ edilmediği tarihle",
            "Kanun yolu başvurusunun yalnız posta idaresine teslim edildiği tarihle",
            "İdari makamın yeni işlem yapmayı planladığını açıkladığı tarihle",
        ],
        "Önce iptal davası açılıp kanun yoluna gidilmişse, sonraki tam yargı davası için dava süresi kanun yolu kararının tebliğinden itibaren değerlendirilir.",
        "2577 sayılı İYUK m.12",
        "medium",
    ),
    V(
        "İşlemin icra tarihinden itibaren dava süresi içinde tam yargı davası açabilir",
        [
            "İcra gerçekleştiğinde tazminat talebi hiçbir süreye tabi olmadan ileri sürülür",
            "İşlemin icrası iptal davasını kendiliğinden tam yargı davasına dönüştürür",
            "Zarar doğsa da yalnız işlemin tesis tarihinden önce tam yargı davası açılabilir",
            "İcra nedeniyle zarar için idari yargıda herhangi bir başvuru yolu bulunmaz",
        ],
        "İşlemin icrası nedeniyle zarar doğduğunda, ilgilinin İYUK m.11 uyarınca idareye başvurma hakkı devam eder mi?",
        "Evet; tam yargı yolunun yanında idareye başvurma hakkı da saklıdır",
        [
            "Hayır; işlemin icrasıyla idari başvuru hakkı kesin olarak sona erer",
            "Hayır; idareye başvuru yalnız dava sonuçlandıktan sonra yapılabilir",
            "Evet; fakat başvuru yalnız adli yargı hâkiminin izniyle yapılabilir",
            "Evet; ancak başvuru tazminat yerine idareye ceza verilmesini amaçlar",
        ],
        "İYUK m.12'nin son cümlesi, işlemin icrası nedeniyle doğan zararlar dâhil bu yollarda ilgilinin m.11 uyarınca idareye başvurma hakkını saklı tutar.",
        "2577 sayılı İYUK m.12 son cümle",
        "hard",
    ),
    V(
        "Dava açmadan önce ilgili idareye hakkın yerine getirilmesi için başvurur",
        [
            "İdari eylemin iptalini istediği dilekçeyi doğrudan ceza mahkemesine verir",
            "Ön başvuru yapmadan her durumda doğrudan tam yargı davası açar",
            "Yalnız eylemi gerçekleştiren personelden sözlü olarak özür dilemesini ister",
            "İdari eylem işlem niteliğinde olmadığı için hiçbir hukuki yola başvuramaz",
        ],
        "İYUK m.13'teki zorunlu ön başvuru hangi zarar kaynağı için öngörülmüştür?",
        "Dava edilebilir bir işleme değil, doğrudan idari eyleme dayanan hak ihlali için",
        [
            "İlan edilmesi gereken bütün düzenleyici işlemlerin doğrudan iptali için",
            "Özel kişiler arasındaki her türlü sözleşme ve haksız fiil uyuşmazlığı için",
            "Kesinleşmiş mahkeme kararının kanun yolunda yeniden incelenmesi için",
            "İdari işlemin yalnız yetki unsuru yönünden hukuka aykırılığı için",
        ],
        "İYUK m.13, doğrudan idari eylemden kaynaklanan hak ihlallerinde dava öncesi idari başvuruyu şart koşar. İdari işlemden doğan talepler m.12 sistemine tabidir.",
        "2577 sayılı İYUK m.12-13",
        "medium",
    ),
    V(
        "İdareye, öğrenmeden itibaren bir yıl ve her hâlde eylemden itibaren beş yıl içinde başvurur",
        [
            "İdareye yalnız eylem tarihinden itibaren otuz gün içinde başvurur",
            "İdareye öğrenme tarihinden bağımsız olarak on yıl içinde başvurur",
            "İdareye süresiz başvurabilir; kanunda herhangi bir üst sınır yoktur",
            "İdareye yalnız zararın miktarı kesinleştikten sonra beş yıl içinde başvurur",
        ],
        "İYUK m.13'teki bir ve beş yıllık süreler öncelikle hangi işlem için öngörülmüştür?",
        "İdari eylemden zarar görenin ilgili idareye yapacağı ön başvuru için",
        [
            "Bölge idare mahkemesine yapılacak olağan istinaf başvurusu için",
            "İptal davasında yürütmenin durdurulması talebinde bulunmak için",
            "Düzenleyici işleme karşı doğrudan açılacak iptal davası için",
            "İdari sözleşmedeki tahkim kararının iptalini istemek için",
        ],
        "Bir ve beş yıllık süreler, idari eylemden doğan zarar için ilgili idareye yapılacak zorunlu ön başvurunun yapısal sınırlarıdır.",
        "2577 sayılı İYUK m.13/1",
        "medium",
    ),
    V(
        "Kısmen reddedilen talep yönünden dava süresi içinde tam yargı davası açabilir",
        [
            "Kısmi ret üzerine bütün hakları sona erdiği için dava açamaz",
            "Yalnız kabul edilen ve ödenen kısım için yeniden iptal davası açar",
            "İdarenin kısmi cevabını beklemeden geçmişe etkili ceza davası açar",
            "Kısmi ret kesin hüküm oluşturduğundan yalnız bireysel başvuru yapabilir",
        ],
        "İdari eylem ön başvurusunun kısmen reddedilmesi hâlinde dava süresi ne zaman işlemeye başlar?",
        "Kısmi ret işleminin ilgiliye tebliğini izleyen günden itibaren",
        [
            "İdari eylemin gerçekleşmesinden önceki takvim yılının başından itibaren",
            "İdarenin kısmen kabul ettiği tutarı bütçesine kaydettiği tarihten itibaren",
            "İlgilinin cevabı sözlü olarak tahmin ettiği tarihten itibaren",
            "Mahkemenin henüz açılmamış dava için tensip zaptı düzenlediği tarihten itibaren",
        ],
        "İYUK m.13 uyarınca istem kısmen veya tamamen reddedilirse, ret işleminin tebliğini izleyen günden itibaren genel dava süresi içinde tam yargı davası açılabilir.",
        "2577 sayılı İYUK m.13/1",
        "medium",
    ),
    V(
        "İdare otuz gün cevap vermezse istek reddedilmiş sayılır ve dava yolu açılır",
        [
            "İdarenin sessizliği başvurunun kabul edildiği ve zararın ödendiği anlamına gelir",
            "Cevap verilmezse dava hakkı herhangi bir karar olmadan kesin olarak sona erer",
            "İdare cevap verinceye kadar hiçbir süre işlemeksizin süresiz beklemek gerekir",
            "Sessizlik yalnız kamu görevlisi hakkında disiplin soruşturması başlatır",
        ],
        "2021 tarihli değişiklikten sonra İYUK m.13 başvurusunda zımni ret süresi kaç gündür?",
        "Başvuru hakkında otuz gün içinde cevap verilmemesiyle zımni ret oluşur",
        [
            "Başvurunun yapıldığı gün cevap verilmemesiyle zımni ret oluşur",
            "Başvuru hakkında yedi gün içinde cevap verilmemesiyle zımni ret oluşur",
            "Başvuru hakkında altmış gün içinde cevap verilmemesiyle zımni ret oluşur",
            "Başvuru hakkında bir yıl içinde cevap verilmemesiyle zımni ret oluşur",
        ],
        "7331 sayılı Kanun, İYUK m.13'teki cevap süresini altmış günden otuz güne indirmiştir. Otuz gün cevap verilmezse istek reddedilmiş sayılır.",
        "2577 sayılı İYUK m.13/1; 7331 sayılı Kanun m.3",
        "easy",
    ),
    V(
        "Düzenleyici işlem, uygulama işlemi veya her ikisi birlikte dava konusu edilebilir",
        [
            "Yalnız düzenleyici işleme karşı dava açılabilir; uygulama işlemi kesinleşir",
            "Yalnız uygulama işlemi dava edilebilir; düzenleyici işleme hiçbir zaman gidilemez",
            "İlan süresi geçtiği için iki işlem de yargı denetimi dışında kalır",
            "Uygulama işlemi düzenleyici işlemi kendiliğinden yürürlükten kaldırır",
        ],
        "İYUK m.7/4 uyarınca düzenleyici işlem ile uygulama işleminin ikisine birden dava açılabilmesi, her durumda aynı dilekçe ve aynı mahkeme anlamına gelir mi?",
        "Hayır; birlikte dava hakkı bulunsa da İYUK m.5 ile görev ve yetki kuralları ayrıca sağlanmalıdır",
        [
            "Evet; iki işlem hangi mahkemelerin görevinde olursa olsun tek dilekçe zorunludur",
            "Evet; uygulama işlemi her zaman düzenleyici işlemi inceleyen Danıştayda görülür",
            "Hayır; çünkü düzenleyici işlem uygulandıktan sonra hiçbir şekilde dava edilemez",
            "Hayır; iki işlemden yalnızca birine karşı dava açılması kanunen zorunludur",
        ],
        "Danıştay uygulamasına göre m.7/4'teki 'her ikisi aleyhine birden' ifadesi otomatik tek dilekçe ve tek görevli mahkeme yaratmaz; İYUK m.5 ile görev ve yetki koşulları ayrıca değerlendirilir.",
        "2577 sayılı İYUK m.5, m.7/4",
        "hard",
    ),
    V(
        "Hayır; düzenleyici işlemin iptal edilmemiş olması uygulama işleminin iptaline engel değildir",
        [
            "Evet; düzenleyici işlem yürürlükteyse uygulama işlemi hiçbir yönden incelenemez",
            "Evet; uygulama işlemi ancak düzenleyici işlem daha önce iptal edilmişse dava edilebilir",
            "Hayır; fakat uygulama işlemi yalnız özel hukuk hakem kurulunda incelenebilir",
            "Hayır; mahkeme uygulama yerine idare adına yeni düzenleyici işlem kurar",
        ],
        "İlanı gereken düzenleyici işleme doğrudan dava açma süresi geçirilmişse, sonradan tesis edilen uygulama işlemi üzerine hangi imkân doğar?",
        "Uygulama üzerine düzenleyici işlem, uygulama işlemi veya ikisi süresinde dava edilebilir",
        [
            "Doğrudan dava süresi geçtiği için düzenleyici işlem hiçbir koşulda ileri sürülemez",
            "Uygulama işlemi düzenleyici işlemi kendiliğinden iptal ettiği için dava açılamaz",
            "Yalnız uygulamayı yapan kamu görevlisi aleyhine ceza davası açılabilir",
            "İki işlem de ancak davalı idare önceden yazılı izin verirse dava edilebilir",
        ],
        "İYUK m.7/4, düzenleyici işlem için ilk ilan süresi geçirilmiş olsa bile onun uygulanması üzerine düzenleyici işlem ve/veya uygulama işlemine süresinde dava açma olanağı tanır.",
        "2577 sayılı İYUK m.7/4",
        "medium",
    ),
    V(
        "İptal kararı hukuka aykırı idari işlemi hukuk düzeninden çıkarır",
        [
            "İptal kararı yalnız işlemi ekonomik açıdan daha yararlı hâle getirir",
            "İptal kararı mahkemenin idare adına yeni işlem kurmasını sağlar",
            "İptal kararı her durumda zarar miktarını belirleyip tazminata hükmeder",
            "İptal kararı yalnız işlemi yapan kamu görevlisine ceza verilmesini sağlar",
        ],
        "İptal davasında işlemin hukuka aykırılığı saptandığında davacının zararının ödenmesine kendiliğinden karar verilir mi?",
        "Hayır; tazminat için tam yargı talebinin usulüne uygun biçimde ileri sürülmesi gerekir",
        [
            "Evet; her iptal kararı zarar bulunup bulunmadığına bakılmaksızın tazminat içerir",
            "Evet; fakat tazminat tutarını mahkeme yerine işlemi yapan kamu görevlisi belirler",
            "Hayır; idari işlemden doğan zararların hiçbir yargı yerinde giderilmesi mümkün değildir",
            "Hayır; tazminat yalnız düzenleyici işlem ilan edilmeden önce talep edilebilir",
        ],
        "İptal davası işlemin hukuka uygunluğuna ve hukuk düzeninden çıkarılmasına; tam yargı ise kişisel hak ihlalinden doğan zararın giderilmesine yönelir. İptal kararı tek başına tazminat hükmü değildir.",
        "2577 sayılı İYUK m.2/1-a-b, m.12",
        "medium",
    ),
    V(
        "Zarar ile idari faaliyet arasında uygun nedensellik bağı bulunmalıdır",
        [
            "İdari faaliyetin varlığı zarar ve bağlantı aranmadan tazminat için yeterlidir",
            "Nedensellik yalnız iptal davasında aranan bir menfaat koşuludur",
            "Zarar başka sebepten doğsa bile idare her durumda tamamını öder",
            "Nedensellik bağı yerine yalnız işlemin ekonomik yararsızlığı kanıtlanır",
        ],
        "Tam yargı davasında tazminata hükmedilebilmesi için nedensellik bağının yanında hangi unsurun da bulunması gerekir?",
        "Gerçekleşmiş, kişisel ve hukuken korunabilir bir zararın bulunması",
        [
            "Davacının işlemle hiçbir ilgisi olmasa da genel bir hoşnutsuzluk duyması",
            "İdari faaliyetin ekonomik açıdan en yararlı seçenek olmadığının ileri sürülmesi",
            "Mahkemenin idare adına yeni bir işlem tesis etmeye hazır olması",
            "Dava konusu faaliyetin mutlaka özel kişiler arasındaki sözleşmeden doğması",
        ],
        "Tam yargıda idarenin sorumluluğu için hukuken korunabilir gerçek bir zarar ve bu zarar ile idari faaliyet arasında uygun nedensellik bağı bulunmalıdır.",
        "2577 sayılı İYUK m.2/1-b; idari sorumluluğun genel ilkeleri",
        "hard",
    ),
    V(
        "Geçerli tahkim kaydı nedeniyle uyuşmazlık İYUK m.2/1-c kapsamı dışındadır",
        [
            "Tahkim kaydına rağmen uyuşmazlık zorunlu olarak idare mahkemesinde görülür",
            "Tahkim kaydı sözleşmeyi kendiliğinden bir vergi uyuşmazlığına dönüştürür",
            "Tahkim kaydı yalnız idarenin tek taraflı onayıyla hukuki sonuç doğurur",
            "Tahkim kaydı taraflar arasındaki uyuşmazlığı tamamen çözümsüz bırakır",
        ],
        "Tahkim yolu öngörülmeyen kamu hizmeti imtiyaz sözleşmesinden taraflar arasında doğan uyuşmazlığın İYUK m.2/1-c karşısındaki niteliği nedir?",
        "İdari sözleşmeden doğan ve idari yargıda görülebilen dava türüdür",
        [
            "Geçerli tahkim şartı varmış gibi yalnız hakem kurulunda görülebilir",
            "Kamu hizmetiyle ilgili olsa da yalnız tüketici mahkemesinde görülür",
            "Taraflardan biri idare olduğu için hiçbir yargı yerinde görülemez",
            "Uyuşmazlık otomatik olarak ceza davasına dönüşür ve savcılıkça görülür",
        ],
        "İYUK m.2/1-c, tahkim yolu öngörülen imtiyaz uyuşmazlıklarını dışarıda bırakır; tahkim yolu öngörülmeyen kamu hizmeti imtiyaz sözleşmesi uyuşmazlığı idari dava türüdür.",
        "2577 sayılı İYUK m.2/1-c",
        "medium",
    ),
]

assert len(VARIANTS) == len(RULES) == 26
for rule, variant in zip(RULES, VARIANTS):
    rule.update(variant)


PREMISES = [
    {"stem": "İdari dava türleri bakımından hangileri doğrudur?\n\nI. İptal davası idari işlemin hukuka aykırılığına yönelir\n\nII. Tam yargı davası kişisel hak ihlalinin giderilmesini amaçlar\n\nIII. Tahkim istisnası dışındaki idari sözleşme uyuşmazlıkları İYUK'ta sayılmıştır", "correct": "I, II ve III", "why": "Üç ifade de İYUK m.2'de düzenlenen idari dava türlerini doğru açıklar.", "ref": "2577 sayılı İYUK m.2"},
    {"stem": "İptal davası bakımından hangileri doğrudur?\n\nI. Menfaat ihlali aranır\n\nII. Yalnız idari işlemlere yönelir\n\nIII. Tek amacı parasal zararı hesaplamaktır", "correct": "I ve II", "why": "İptal davasında menfaat ihlali ve dava konusu yapılabilir idari işlem aranır; parasal zararın giderimi tam yargı davasının işlevidir.", "ref": "2577 sayılı İYUK m.2/1-a"},
    {"stem": "Tam yargı davası bakımından hangileri doğrudur?\n\nI. İdari eylemden doğabilir\n\nII. İdari işlemden doğabilir\n\nIII. Kişisel hakkın doğrudan ihlali aranır", "correct": "I, II ve III", "why": "Tam yargı davası idari eylem veya işlemden doğabilir ve kişisel hakkı doğrudan ihlal edilenlerce açılır.", "ref": "2577 sayılı İYUK m.2/1-b"},
    {"stem": "İptal sebepleri bakımından hangileri doğrudur?\n\nI. Yetkisiz makamın işlem yapması yetki unsuruyla ilgilidir\n\nII. Zorunlu usulün atlanması maksat unsuruyla ilgilidir\n\nIII. Kamu yararı dışındaki amaç maksat unsuruyla ilgilidir", "correct": "I ve III", "why": "Yetkisiz makam yetki, kamu yararı dışındaki amaç maksat unsurunu sakatlar. Zorunlu usulün atlanması maksat değil şekil unsuruyla ilgilidir.", "ref": "2577 sayılı İYUK m.2/1-a"},
    {"stem": "İdari yargı yetkisinin sınırları bakımından hangileri doğrudur?\n\nI. Hukuka uygunluk denetimi yapılır\n\nII. Yerindelik denetimi yapılamaz\n\nIII. Mahkeme idare yerine geçerek yeni işlem kurabilir", "correct": "I ve II", "why": "İdari yargı hukuka uygunluğu denetler; yerindelik denetimi yapamaz ve idare yerine geçerek işlem kuramaz.", "ref": "2577 sayılı İYUK m.2/2"},
    {"stem": "İYUK m.12 uyarınca hangileri mümkündür?\n\nI. Doğrudan tam yargı davası açmak\n\nII. İptal ve tam yargı davalarını birlikte açmak\n\nIII. Mahkemeden idare yerine yeni bir işlem tesis etmesini istemek", "correct": "I ve II", "why": "Doğrudan tam yargı davası ile iptal ve tam yargı davalarının birlikte açılması mümkündür. Mahkeme idare yerine geçerek yeni işlem tesis edemez.", "ref": "2577 sayılı İYUK m.2/2, m.12"},
    {"stem": "İdari eylemden doğan tam yargı davası bakımından hangileri doğrudur?\n\nI. Kural olarak önce idareye başvuru yapılır\n\nII. Öğrenmeden itibaren bir yıllık başvuru süresi vardır\n\nIII. Başvuruda hiçbir nihai üst süre bulunmaz", "correct": "I ve II", "why": "İdari eylemde ön başvuru zorunludur ve öğrenmeden itibaren bir yıllık süre uygulanır. Ayrıca eylem tarihinden itibaren beş yıllık nihai üst sınır vardır.", "ref": "2577 sayılı İYUK m.13/1"},
    {"stem": "Düzenleyici işlemin uygulanması üzerine hangileri doğrudur?\n\nI. Uygulama işlemine dava açılabilir\n\nII. Düzenleyici işleme hiçbir zaman dava açılamaz\n\nIII. Uygulama ve düzenleyici işlem birlikte dava konusu edilebilir", "correct": "I ve III", "why": "Uygulama işlemi tek başına veya düzenleyici işlemle birlikte dava edilebilir; düzenleyici işleme başvuru yolu uygulamayla yeniden açılabilir.", "ref": "2577 sayılı İYUK m.7/4"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="idari_yargilama_hukuku", topic_id="idari_dava_turleri",
        label="İdari Dava Türleri", slug="idari_dava_turleri", prefix="kh-iy-dava",
        seed=20261002, legislation_version="2577 sayılı İYUK (17.07.2026)",
        rules=RULES, premises=PREMISES, wrong_banks=WRONG,
    )
