#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Vergi Hukukunun Temel İlkeleri, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Vergi düzenlemesi, kamu gücünün keyfî kullanımını önleyen açık kurallar ve etkili yargı denetimi içermektedir. Bu yaklaşım öncelikle hangi anayasal niteliği somutlaştırır?",
        "Hukuki güvenlik, belirlilik ve yargı denetimi hangi anayasal devlet niteliğinin gerekleridir?",
        "Hukuk devleti",
        "Hukuk devleti",
        ["Üniter devlet", "Seçim devleti", "İktisadi devlet", "Merkezî devlet"],
        ["Üniter devlet", "Salt çoğunluk devleti", "Sınırsız idare devleti", "Kamu işletmesi devleti"],
        "İdarenin ve kanun koyucunun hukukla bağlı olması, öngörülebilir kurallar ve yargısal denetim hukuk devletinin vergilendirmeye yansımasıdır.",
        "Belirlilik ve hukuki güvenlik, Anayasa m. 2'deki hukuk devleti ilkesinin temel unsurlarıdır.",
        "2709 sayılı Anayasa m. 2; AYM K.2024/94",
        "medium",
    ),
    r(
        "Vergisel bakımdan aynı durumda bulunan iki mükellefe, nesnel bir neden olmadan farklı oran uygulanmıştır. Öncelikle hangi ilke ihlal edilmiş olabilir?",
        "Vergilendirmede eşitlik ilkesi, karşılaştırılabilir durumda bulunan mükellefler bakımından neyi gerektirir?",
        "Kanun önünde eşitlik",
        "Aynı hukuki ölçünün uygulanmasını",
        ["Vergi mahremiyeti", "Dönemsellik", "Tahsililik", "Yerellik"],
        ["Her mükellefe farklı oran belirlenmesini", "Verginin yalnız şirketlerden alınmasını", "Bütün istisnaların kaldırılmasını", "Her verginin aynı tutarda olmasını"],
        "Benzer durumda olanlara haklı ve nesnel neden olmadan farklı muamele yapılması kanun önünde eşitlik sorununa yol açar.",
        "Eşitlik mutlak aynı tutarı değil, karşılaştırılabilir durumdaki kişilere nesnel neden yoksa aynı hukuki ölçünün uygulanmasını gerektirir.",
        "2709 sayılı Anayasa m. 10 ve 73",
        "medium",
    ),
    r(
        "Vergi borcu nedeniyle mülkiyete yapılan müdahale kanuni dayanağa sahip değildir. Bu müdahale hangi temel hakkın güvenceleriyle doğrudan çatışır?",
        "Mülkiyet hakkı Anayasa'ya göre hangi amaçla ve hangi araçla sınırlanabilir?",
        "Mülkiyet hakkı",
        "Kamu yararı amacıyla ve kanunla",
        ["Seçme hakkı", "Yerleşme hakkı", "Dernek kurma hakkı", "Toplantı hakkı"],
        ["İdarenin takdiriyle ve gerekçesiz", "Özel sözleşmeyle ve süresiz", "Sözlü emirle ve kişisel yarar için", "Genelgeyle ve sınırsız biçimde"],
        "Vergi, kişinin mal varlığına müdahale oluşturduğundan kanuni temel bulunmaması mülkiyet hakkının kanunilik güvencesini ihlal edebilir.",
        "Anayasa m. 35, mülkiyet hakkının ancak kamu yararı amacıyla ve kanunla sınırlandırılabileceğini öngörür.",
        "2709 sayılı Anayasa m. 35",
        "medium",
    ),
    r(
        "Mükellefin vergi tarhına karşı bağımsız mahkeme önünde iddia ve savunmalarını sunması engellenmiştir. Hangi anayasal güvence gündemdedir?",
        "Vergi uyuşmazlığında yargı mercileri önünde iddia ve savunma imkânı hangi hakla ilişkilidir?",
        "Hak arama hürriyeti",
        "Adil yargılanma hakkı",
        ["Konut dokunulmazlığı", "Seçme hakkı", "Toplantı hakkı", "Çalışma hakkı"],
        ["Yerleşme hürriyeti", "Basın hürriyeti", "Bilim ve sanat hürriyeti", "Sözleşme hürriyeti"],
        "Vergi işlemine karşı mahkemede iddia ve savunma sunabilmek hak arama hürriyeti ve adil yargılanma güvencesi kapsamındadır.",
        "Anayasa m. 36, herkesin meşru yollarla yargı mercileri önünde iddia ve savunma hakkını korur.",
        "2709 sayılı Anayasa m. 36",
        "easy",
    ),
    r(
        "Aynı gelir düzeyine sahip kişilerden biri, mali gücünü aşan ölçüde daha ağır vergilendirilmiştir. Anayasa m. 73'teki hangi ölçüt önem kazanır?",
        "Anayasa'ya göre vergi ödevinin kişisel yükünü belirleyen temel ölçü hangisidir?",
        "Mali güce göre vergilendirme",
        "Mali güç",
        ["İdarenin personel sayısı", "Mükellefin siyasi tercihi", "Vergi dairesinin fiziksel büyüklüğü", "Beyanname sayısının çokluğu"],
        ["Yaşanılan ilçenin yüzölçümü", "Vergi memurunun kıdemi", "Mükellefin oy tercihi", "Vergi dairesinin bütçesi"],
        "Anayasa herkesin kamu giderlerine mali gücüne göre katılmasını ister; benzer gelir düzeyindeki kişilerin yükü bu ölçüyle açıklanmalıdır.",
        "Vergi ödevinin anayasal kişisel ölçütü mali güçtür.",
        "2709 sayılı Anayasa m. 73/1",
        "easy",
    ),
    r(
        "Vergi yükünün toplum kesimleri arasında adaletli ve dengeli dağılması hedeflenmektedir. Anayasa bunu nasıl nitelendirir?",
        "Vergi yükünün adaletli ve dengeli dağılımı hangi politikanın sosyal amacıdır?",
        "Maliye politikasının sosyal amacı",
        "Maliye politikası",
        ["Para politikasının teknik amacı", "Dış ticaret politikasının tek amacı", "İmar politikasının yerel amacı", "Nüfus politikasının idarî amacı"],
        ["Para politikası", "İmar politikası", "Ulaştırma politikası", "Dış ticaret politikası"],
        "Anayasa m. 73, vergi yükünün adaletli ve dengeli dağılımını maliye politikasının sosyal amacı olarak belirler.",
        "Adaletli ve dengeli dağılım, maliye politikasına yüklenen anayasal sosyal amaçtır.",
        "2709 sayılı Anayasa m. 73/2",
        "easy",
    ),
    r(
        "Bir kamu kurumu yalnız yönetmelikle yeni bir mali yükümlülük getirmiştir. Kanunda bu yükümlülüğün dayanağı yoktur. Düzenleme hangi ilkeye aykırıdır?",
        "Verginin kanuniliği ilkesi hangi işlemlerin kanunla yapılmasını gerektirir?",
        "Verginin kanuniliği",
        "Yükümlülüğü koyma, değiştirme ve kaldırma",
        ["Vergi mahremiyeti", "Dönemsellik", "Tahsililik", "Yerellik"],
        ["Yalnız tahsil makbuzunun basılması", "Vergi dairesinin günlük çalışma saatlerinin belirlenmesi", "Personelin görev dağılımı", "Beyanname formunun sayfa düzeni"],
        "Kanuni temel olmadan yönetmelikle yeni vergi, resim, harç veya benzeri mali yükümlülük getirilemez.",
        "Vergi ve benzeri mali yükümlülüklerin konulması, değiştirilmesi ve kaldırılması kanunilik güvencesi altındadır.",
        "2709 sayılı Anayasa m. 73/3",
        "easy",
    ),
    r(
        "Kanun, bir vergi oranı için alt ve üst sınırı göstermeden Cumhurbaşkanına oranı serbestçe belirleme yetkisi vermiştir. Anayasa m. 73/4 bakımından sorun nedir?",
        "Cumhurbaşkanına vergi oranını değiştirme yetkisi hangi anayasal sınırla verilebilir?",
        "Kanuni sınırlar gösterilmemiştir",
        "Kanuni alt ve üst sınırlar içinde",
        ["Yetki yalnız belediyeye verilmiştir", "Vergi tahsil edilmeden ilan edilmiştir", "Beyanname elektronik hazırlanmıştır", "Mükellef gerçek kişidir"],
        ["İdarenin dilediği sınırsız aralıkta", "Yalnız geçmiş dönemlere uygulanmak üzere", "Hiçbir kanuni çerçeve olmaksızın", "Mükellefin sözlü onayıyla"],
        "Cumhurbaşkanına muaflık, istisna, indirim ve oranlarda değişiklik yetkisi ancak kanunun gösterdiği alt ve üst sınırlar içinde verilebilir.",
        "Anayasa, yürütmeye verilebilecek değişiklik yetkisini kanuni alt ve üst sınırlarla bağlı kılar.",
        "2709 sayılı Anayasa m. 73/4",
        "hard",
    ),
    r(
        "Yeni vergi yükümlülüğü, yürürlüğünden önce tamamlanmış işlemlere beklenmedik biçimde uygulanmıştır. Bu durum öncelikle hangi ilkeyle çatışabilir?",
        "Vergi normlarının geçmişte tamamlanmış olaylara beklenmedik biçimde uygulanmaması hangi güvenceyi destekler?",
        "Hukuki güvenlik",
        "Hukuki güvenlik",
        ["Vergi mahremiyeti", "Tahsililik", "Yerinden yönetim", "Dilekçe hakkı"],
        ["Vergi mahremiyeti", "Bütçe birliği", "Yerellik", "Tahsil ekonomisi"],
        "Geçmişte tamamlanmış vergiyi doğuran olaylara sonradan yeni yük getirilmesi kişilerin hukuki sonuçları öngörebilmesini zedeler.",
        "Vergi kurallarının geriye yürütülmemesi, hukuki güvenlik ve öngörülebilirliğin bir görünümüdür.",
        "2709 sayılı Anayasa m. 2 ve 73; AYM K.2003/76",
        "hard",
    ),
    r(
        "Vergi kanunu, matrahın hangi ölçütlerle belirleneceğini idare ve mükellef yönünden anlaşılmaz bırakmıştır. Hangi ilke zedelenmiştir?",
        "Vergi kuralının açık, net, anlaşılır ve nesnel olması hangi ilkenin gereğidir?",
        "Belirlilik ilkesi",
        "Belirlilik ilkesi",
        ["Tahsililik ilkesi", "Yerellik ilkesi", "Dönemsellik ilkesi", "Mahremiyet ilkesi"],
        ["Tahsililik ilkesi", "Bütçe birliği ilkesi", "Yerinden yönetim ilkesi", "İdari vesayet ilkesi"],
        "Matrah ve yükümlülük unsurlarının duraksamaya yer vermeyecek açıklıkta olması belirlilik ve hukuki güvenlik için zorunludur.",
        "Belirlilik, kuralın hem idare hem kişiler için açık, anlaşılır, uygulanabilir ve keyfîliğe karşı koruyucu olmasını gerektirir.",
        "2709 sayılı Anayasa m. 2 ve 73; AYM B.2019/40353",
        "medium",
    ),
    r(
        "Kanuni amaç meşru olsa da vergisel müdahale mükellefe ulaşılmak istenen yararla açıkça orantısız bir külfet yüklemiştir. Hangi denetim ölçütü önemlidir?",
        "Vergisel müdahalede kamu yararı ile kişiye yüklenen külfet arasında adil denge aranması hangi ilkeyle ilişkilidir?",
        "Ölçülülük",
        "Ölçülülük",
        ["Yetki genişliği", "Tahsililik", "Dönemsellik", "Yerellik"],
        ["Tahsil ekonomisi", "İdari vesayet", "Bütçe genelliği", "Yerinden yönetim"],
        "Mülkiyete vergisel müdahale meşru amaca elverişli, gerekli ve kişi üzerinde orantısız yük doğurmayacak ölçüde olmalıdır.",
        "Kamu yararı ile mülkiyet hakkına getirilen külfet arasında adil denge ölçülülük değerlendirmesinin konusudur.",
        "2709 sayılı Anayasa m. 13, 35 ve 73",
        "hard",
    ),
    r(
        "Vergi kanununun sözü açık değildir. Uygulayıcı hükmü hangi unsurları birlikte değerlendirerek yorumlamalıdır?",
        "VUK'a göre vergi kanunları hangi iki yönüyle hüküm ifade eder?",
        "Amaç, kanundaki yer ve diğer maddelerle bağlantı",
        "Lafzı ve ruhu ile",
        ["İdarenin yalnızca günlük tahsilat ihtiyacı", "Sadece mükellefin kişisel tercihi", "Yalnız tahsilat hedefi", "Sadece sektördeki söylenti"],
        ["Yalnız lafzıyla", "Yalnız idari teamülle", "Yalnız mükellef lehine yorumla", "Yalnız tahsilat amacıyla"],
        "Lafız açık değilse hükmün konuluş amacı, kanun yapısındaki yeri ve diğer maddelerle bağlantısı göz önünde tutulur.",
        "Vergi kanunları yalnız sözüyle değil, lafzı ve ruhu birlikte değerlendirilerek uygulanır.",
        "213 sayılı VUK m. 3/A",
        "medium",
    ),
    r(
        "Sözleşmeye satış adı verilmiş, ancak ekonomik ve fiilî gerçek bunun bir hizmet işlemi olduğunu göstermektedir. Vergilemede hangisi esas alınır?",
        "Vergiyi doğuran olay ve ilgili işlemlerin ispatında VUK'un temel yaklaşımı hangisidir?",
        "İşlemin gerçek mahiyeti",
        "Gerçek mahiyet esastır",
        ["Sözleşmenin yalnız başlığı", "Tarafların sonradan seçtiği ad", "Muhasebe fişinin rengi", "İşletmenin ticaret unvanı"],
        ["Yalnız şekli belge adı esastır", "Tarafların vergi dışı amacı esastır", "İdarenin bütçe ihtiyacı esastır", "İşlemin muhasebe kodu tek başına esastır"],
        "Vergilendirmede işlemin taraflarca verilen adı değil, vergiyi doğuran olayın ekonomik ve fiilî gerçekliği esas alınır.",
        "VUK m. 3/B, vergiyi doğuran olay ve işlemlerde gerçek mahiyet ilkesini benimser.",
        "213 sayılı VUK m. 3/B",
        "easy",
    ),
    r(
        "Vergiyi doğuran olayın gerçek mahiyeti yalnız yemin deliliyle kanıtlanmak istenmektedir. VUK bakımından yemin kullanılabilir mi?",
        "Vergiyi doğuran olayın gerçek mahiyeti kural olarak hangi delillerle ispatlanabilir?",
        "Hayır; yemin delil olarak kullanılamaz",
        "Yemin dışındaki delillerle",
        ["Evet; yalnız yemin geçerlidir", "Evet; yemin kesin ve zorunlu delildir", "Hayır; hiçbir delil kullanılamaz", "Evet; yalnız noter huzurundaki yemin geçerlidir"],
        ["Yalnız yazılı sözleşmeyle", "Sadece noter senediyle", "Yalnız tanık anlatımıyla", "Hiçbir delil kullanılmadan"],
        "VUK gerçek mahiyetin ispatında yemin dışındaki her türlü delile izin verir; yemin istisna edilmiştir.",
        "İspat serbestisi vardır; ancak yemin bu serbestinin dışındadır ve tanık delili için ayrıca bağlantı koşulu aranır.",
        "213 sayılı VUK m. 3/B",
        "medium",
    ),
    r(
        "Vergiyi doğuran olayla doğal ve açık bağlantısı bulunmayan kişinin tanıklığına dayanılmıştır. Bu ifade ispat aracı olabilir mi?",
        "Olağan ekonomik ve ticari akışa aykırı bir durum ileri süren taraf bakımından ispat yükü kime aittir?",
        "Hayır; olayla doğal bağlantı gerekir",
        "Olağan dışı durumu ileri süren tarafa",
        ["Evet; her tanık ifadesi yeterlidir", "Evet; yalnız akraba tanıklığı yeterlidir", "Hayır; tanık hiçbir durumda dinlenemez", "Evet; bağlantı yerine yemin aranır"],
        ["Vergi mahkemesinde karşı taraf olan herkese", "Daima vergi dairesine", "Mükellefin bütün çalışanlarına", "İşlemle ilgisiz üçüncü kişiye"],
        "Tanık ifadesinin ispat aracı olabilmesi için vergiyi doğuran olayla doğal ve açık ilgisinin bulunması gerekir.",
        "Normal ve mutat olana aykırı durumu iddia eden taraf, bu olağan dışı iddiasını ispatlar.",
        "213 sayılı VUK m. 3/B",
        "hard",
    ),
    r(
        "Bir birim mükellefi belirlemekte, vergiyi tarh, tahakkuk ve tahsil etmektedir. VUK'a göre bu birim nedir?",
        "Vergi dairesinin VUK'taki temel işlevleri hangileridir?",
        "Vergi dairesi",
        "Tespit, tarh, tahakkuk ve tahsil",
        ["Takdir komisyonu", "Vergi mahkemesi", "Ticaret sicili", "Belediye encümeni"],
        ["Yalnız davaların açılması ve karara bağlanması", "Yalnız kanun yapma ve kaldırma", "Yalnız şirket tescil etme", "Yalnız meslek ruhsatı verme"],
        "Mükellefi tespit eden ve vergiyi tarh, tahakkuk ve tahsil eden idari birim vergi dairesidir.",
        "VUK m. 4 vergi dairesini mükellefi belirleyen, vergiyi tarh, tahakkuk ve tahsil eden daire olarak tanımlar.",
        "213 sayılı VUK m. 4",
        "easy",
    ),
    r(
        "Vergi inceleme elemanı görevinden ayrıldıktan sonra görev sırasında öğrendiği mükellef sırrını açıklamıştır. Mahremiyet yükümlülüğü sona ermiş midir?",
        "Vergi mahremiyeti kapsamındaki bilgiler görevli tarafından kendi veya üçüncü kişinin yararına kullanılabilir mi?",
        "Hayır; görevden sonra da devam eder",
        "Hayır; kullanılması yasaktır",
        ["Evet; görevle birlikte sona erer", "Evet; yalnız bir yıl daha sürer", "Evet; mükellef tanınmıyorsa serbesttir", "Hayır; fakat yalnız basına açıklanabilir"],
        ["Evet; görev süresinde serbesttir", "Evet; yalnız parasal yarar için kullanılabilir", "Evet; üçüncü kişiye devredilebilir", "Hayır; fakat meslektaşla paylaşılması zorunludur"],
        "Vergi mahremiyeti yükümlülüğü görev sona erse de devam eder; görev sırasında öğrenilen sırlar açıklanamaz.",
        "Mükellefe ait gizli bilgiler görevlinin veya üçüncü kişinin yararına kullanılamaz.",
        "213 sayılı VUK m. 5",
        "easy",
    ),
    r(
        "Kamu kurumu, kendi kanuni göreviyle doğrudan ilgili ve sürekli ihtiyaç duyduğu mükellef bilgisini usulüne uygun istemiştir. Bilginin verilmesi her durumda mahremiyet ihlali midir?",
        "Vergi mahremiyeti kapsamında bilgi verilen kamu kurumu hangi ödevi üstlenir?",
        "Hayır; kanuni şartlarda mümkündür",
        "Gizliliği koruyucu tedbirleri alma",
        ["Evet; hiçbir istisna bulunmaz", "Evet; yalnız mahkeme bilgiyi görebilir", "Hayır; bilgi herkese açıklanabilir", "Evet; bilgi talebi suç oluşturur"],
        ["Bilgiyi internetten yayımlama", "Bilgiyi ticari amaçla satma", "Bilgiyi süresiz üçüncü kişiye aktarma", "Bilgiyi isteyen herkesle paylaşma"],
        "Kanuni görevle doğrudan ilgili, zorunlu ve sürekli bilgi paylaşımı şartlar sağlandığında mahremiyet ihlali sayılmaz.",
        "Bilgi verilen kurum mahremiyet yasağına uyar ve bilgilerin korunması için gerekli önlemleri alır.",
        "213 sayılı VUK m. 5",
        "hard",
    ),
    r(
        "Vergi inceleme görevlisi, kanuni temsilcisi olduğu şirkete ait vergi incelemesini yürütmek istemektedir. VUK bakımından mümkün müdür?",
        "Vergi incelemesinde görevli kişi mükellefin vergiye ilişkin özel muhasebe işini ücretsiz yapabilir mi?",
        "Hayır; bu inceleme ve takdir işi yasaktır",
        "Hayır; ücretsiz olsa da yapamaz",
        ["Evet; ücret almaması yeterlidir", "Evet; şirket izin verirse mümkündür", "Evet; yalnız kısa incelemelerde mümkündür", "Hayır; ancak vergi dairesi de inceleyemez"],
        ["Evet; ücret alınmıyorsa serbesttir", "Evet; mesai dışında her zaman mümkündür", "Evet; yalnız beyan döneminde mümkündür", "Hayır; fakat çalışanına yaptırabilir"],
        "Görevli, kanuni temsilcisi veya vekili olduğu kişiye ait vergi inceleme ve takdir işiyle uğraşamaz.",
        "Vergi işleriyle görevli olanların mükellefin vergiye ilişkin özel işlerini ücretsiz dahi olsa yapması yasaktır.",
        "213 sayılı VUK m. 6",
        "medium",
    ),
    r(
        "Bir kişi vergi kanununa göre kendi borcu nedeniyle vergilendirilmekte, başka biri ise bu verginin ödenmesi bakımından vergi dairesine muhatap olmaktadır. İkinci kişi kimdir?",
        "Vergi mükellefi VUK'ta nasıl tanımlanır?",
        "Vergi sorumlusu",
        "Vergi borcu kendisine düşen kişi",
        ["Vergi mükellefi", "Vergi hakimi", "Yoklama memuru", "Bilirkişi"],
        ["Verginin tarh ve tahsilini yapan vergi dairesi", "Herhangi bir kamu görevlisi", "Vergi davasına bakan hâkim", "Mükellefin bütün alacaklıları"],
        "Verginin ödenmesi bakımından alacaklı vergi dairesine karşı muhatap olan kişi vergi sorumlusudur.",
        "Mükellef, vergi kanununa göre vergi borcu kendisine yüklenen gerçek veya tüzel kişidir.",
        "213 sayılı VUK m. 8",
        "easy",
    ),
    r(
        "Satıcı ve alıcı, vergi sorumluluğunun alıcıya ait olmayacağını özel sözleşmeyle kararlaştırmıştır. Kanunda aksi öngörülmüyorsa bu sözleşme vergi dairesini bağlar mı?",
        "Mükellefiyet veya vergi sorumluluğuna ilişkin özel sözleşmelerin idareye etkisi nedir?",
        "Hayır; vergi dairesini bağlamaz",
        "Kanuni istisna yoksa vergi dairesini bağlamaz",
        ["Evet; sözleşme vergi kanununun yerini alır", "Evet; noter onayı varsa vergi kalkar", "Hayır; özel sözleşme bütünüyle geçersizdir", "Evet; yalnız sözlü yapılırsa bağlar"],
        ["Her durumda vergi borcunu kaldırır", "Vergi kanununu kendiliğinden değiştirir", "Yalnız sözlü yapılırsa idareyi bağlar", "Tarafların seçtiği vergi oranını geçerli kılar"],
        "Taraflar arası özel sözleşme kendi aralarında sonuç doğurabilir; ancak kanuni istisna yoksa vergisel muhataplığı idare yönünden değiştirmez.",
        "Vergisel yükümlülük ve sorumluluk kanundan doğar; özel sözleşme vergi dairesini bağlamaz.",
        "213 sayılı VUK m. 8",
        "medium",
    ),
    r(
        "Kanuni işlem ehliyeti bulunmayan küçük adına vergiyi doğuran olay gerçekleşmiştir. Yalnız ehliyetsizlik mükellefiyeti kaldırır mı?",
        "Vergi ehliyeti bakımından VUK'un benimsediği kural hangisidir?",
        "Hayır; kanuni ehliyet şart değildir",
        "Mükellefiyet için kanuni ehliyet aranmaz",
        ["Evet; küçükler hiç mükellef olamaz", "Evet; vergi borcu daima veliye aittir", "Hayır; fakat vergiyi doğuran olay yok sayılır", "Evet; yalnız tüzel kişiler mükellef olabilir"],
        ["Yalnız tam ehliyetliler mükellef olabilir", "Mükellefiyet için erginlik zorunludur", "Vergi sorumluluğu için mahkeme kararı gerekir", "Mükellefiyet yalnız tacir sıfatıyla doğar"],
        "Vergi borcunun doğması medeni hukuktaki işlem ehliyetine bağlı değildir; küçük de mükellef olabilir, ödevleri temsilcisi yerine getirir.",
        "VUK m. 9, mükellefiyet ve vergi sorumluluğu için kanuni ehliyet şartı aramaz.",
        "213 sayılı VUK m. 9",
        "easy",
    ),
    r(
        "Kanunen yasak olan bir faaliyetten gelir elde edilmiş ve vergiyi doğuran olay gerçekleşmiştir. Faaliyetin yasaklığı vergilendirmeyi ortadan kaldırır mı?",
        "Vergiyi doğuran olayın kanunen yasak olması mükellefiyet bakımından hangi sonucu doğurur?",
        "Hayır; mükellefiyet devam eder",
        "Vergi sorumluluğunu kaldırmaz",
        ["Evet; yasak gelir hiçbir zaman vergilenmez", "Evet; yalnız ceza hukuku uygulanır", "Hayır; fakat gelir kendiliğinden istisnadır", "Evet; vergi borcu idareye geçer"],
        ["Vergi borcunu kendiliğinden siler", "Faaliyeti vergi istisnasına dönüştürür", "Vergiyi yalnız mahkeme harcına çevirir", "Vergi sorumlusunu daima beraat ettirir"],
        "Vergi hukuku ekonomik olayı esas alır; faaliyetin başka bir kanunla yasaklanmış olması doğan vergi yükümlülüğünü ortadan kaldırmaz.",
        "Kanunen yasak faaliyet de vergiyi doğuran olay gerçekleşmişse mükellefiyet ve sorumluluğu kaldırmaz.",
        "213 sayılı VUK m. 9",
        "medium",
    ),
    r(
        "Tüzel kişinin vergisel ödevleri yerine getirilmemiş ve vergi şirket varlığından alınamamıştır. Kanuni şartlarda alacak kimin varlığından alınabilir?",
        "Küçük ve kısıtlı mükelleflerin vergisel ödevlerini kim yerine getirir?",
        "Ödevi yerine getirmeyen kanuni temsilcinin varlığından",
        "Kanuni temsilcileri",
        ["Herhangi bir şirket çalışanından", "Şirketin ticari ilişki kurduğu bütün müşterilerinden", "Ticaret sicili memurundan", "Vergi mahkemesi hâkiminden"],
        ["Vergi mahkemesi", "Ticaret sicili", "Bütün mirasçılar", "Vergi dairesi çalışanları"],
        "Kanuni temsilcinin ödev ihlali yüzünden alacak tüzel kişinin varlığından alınamazsa vergi ve bağlı alacaklar temsilcinin varlığından alınabilir.",
        "Küçüklerin ve kısıtlıların vergisel ödevlerini kanuni temsilcileri yerine getirir.",
        "213 sayılı VUK m. 10",
        "hard",
    ),
    r(
        "İşveren ücret ödemesinden kanunen kesmesi gereken vergiyi eksik kesmiştir. Verginin tam kesilip ödenmesinden kim sorumludur?",
        "Vergi kesmek zorunda olanın vergiyi ödemesi, asıl mükellefe rücu hakkını ortadan kaldırır mı?",
        "Vergi kesen işveren",
        "Hayır; rücu hakkı devam eder",
        ["Ücretlinin komşusu", "Vergi mahkemesi", "Ticaret sicili müdürü", "İşverenin müşterisi"],
        ["Evet; rücu her durumda yasaktır", "Evet; vergi borcu da tamamen sona erer", "Hayır; fakat vergi dairesi kapanır", "Evet; yalnız yazılı sözleşmeyle kalkar"],
        "Ödemeden vergi kesmek zorunda olan işveren, verginin tam kesilip ödenmesi ve ilgili ödevlerin yerine getirilmesinden sorumludur.",
        "Vergi kesenin ödediği tutar için asıl mükellefe rücu edebilme hakkı korunur.",
        "213 sayılı VUK m. 11",
        "medium",
    ),
    r(
        "Mükellef ölmüş ve mirası reddetmeyen iki mirasçı bırakmıştır. Vergisel ödevler ve borç sorumluluğu bakımından temel kural nedir?",
        "Mücbir sebep sayılabilecek bir olayın ortak niteliği hangisidir?",
        "Ödevler mirasçılara geçer; borçtan miras payları oranında sorumludurlar",
        "Vergi ödevinin yerine getirilmesini engellemesi",
        ["Bütün borçlar kendiliğinden silinir", "Yalnız en yaşlı mirasçı tüm borcu üstlenir", "Vergi borcu vergi dairesi çalışanına geçer", "Mirasçılar ödevleri devralmaz, borcun tamamından sorumludur"],
        ["Mükellefe sürekli ve olağan bir ticari avantaj sağlaması", "Vergi oranını değiştirmesi", "Yeni bir vergi türü oluşturması", "Beyannameyi gereksiz kılması"],
        "Mirası reddetmemiş mirasçılar ödevleri devralır; her biri vergi borcundan miras hissesi ölçüsünde sorumludur.",
        "Ağır hastalık, afet veya irade dışı kayıp gibi mücbir sebep hâlleri vergi ödevinin yerine getirilmesine engel olacak ağırlıkta olmalıdır.",
        "213 sayılı VUK m. 12-13",
        "medium",
    ),
]


PREMISES = [
    {"stem":"Anayasal vergi ödevi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Vergi kamu giderlerini karşılamak üzere alınır\n\nII. Herkes mali gücüne göre vergi öder\n\nIII. Vergi yükünün adaletli dağılımı maliye politikasının sosyal amacıdır","correct":"I, II ve III","why":"Üç ifade de Anayasa m. 73'ün ilk iki fıkrasındaki mali güç, kamu gideri ve adaletli dağılım ilkelerini yansıtır.","ref":"2709 sayılı Anayasa m. 73/1-2","difficulty":"easy"},
    {"stem":"Verginin kanuniliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yeni mali yükümlülük kanunla konulur\n\nII. Vergi kanunla değiştirilir veya kaldırılır\n\nIII. Cumhurbaşkanına kanuni alt ve üst sınırlar olmadan oran belirleme yetkisi verilebilir","correct":"I ve II","why":"Mali yükümlülüğün konulması, değiştirilmesi ve kaldırılması kanuna tabidir. Cumhurbaşkanına oran yetkisi kanunun gösterdiği alt ve üst sınırlarla verilebilir.","ref":"2709 sayılı Anayasa m. 73/3-4","difficulty":"medium"},
    {"stem":"Hukuki güvenlik bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Vergi kuralı açık ve öngörülebilir olmalıdır\n\nII. İdareye sınırsız takdir bırakılması belirliliği güçlendirir\n\nIII. Geçmişte tamamlanmış olaya beklenmedik yeni yük uygulanması güvenliği zedeleyebilir","correct":"I ve III","why":"Açıklık ve öngörülebilirlik hukuki güvenliği sağlar; sınırsız takdir ve gerçek geriye yürüme bu güvenceyle çatışabilir.","ref":"2709 sayılı Anayasa m. 2 ve 73; AYM K.2024/94","difficulty":"hard"},
    {"stem":"VUK'un yorum ve ispat kuralları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kanunlar lafzı ve ruhuyla hüküm ifade eder\n\nII. Vergilendirmede gerçek mahiyet esastır\n\nIII. Gerçek mahiyet yalnız yeminle ispatlanabilir","correct":"I ve II","why":"Lafız ve ruh birlikte değerlendirilir, gerçek mahiyet esastır. İspatta yemin dışındaki deliller kullanılabilir.","ref":"213 sayılı VUK m. 3","difficulty":"medium"},
    {"stem":"Vergi mahremiyeti bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Görevden ayrılmak mahremiyet yükümlülüğünü sona erdirmez\n\nII. Gizli bilgi görevlinin yararına kullanılamaz\n\nIII. Kanuni şartları taşıyan bazı kamu kurumu paylaşımları ihlal sayılmaz","correct":"I, II ve III","why":"Mahremiyet görev sonrasında sürer, sırların kişisel yarara kullanımı yasaktır ve kanunda açıkça düzenlenen paylaşımlar istisna oluşturabilir.","ref":"213 sayılı VUK m. 5","difficulty":"medium"},
    {"stem":"Mükellef ve sorumlu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mükellef vergi borcu kendisine düşen kişidir\n\nII. Vergi sorumlusu ödeme bakımından vergi dairesine muhataptır\n\nIII. Özel sözleşme her durumda vergi dairesini bağlar","correct":"I ve II","why":"Mükellef ve sorumlu tanımları doğrudur; kanuni istisna yoksa özel sözleşme vergi dairesini bağlamaz.","ref":"213 sayılı VUK m. 8","difficulty":"easy"},
    {"stem":"Vergi ehliyeti bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mükellefiyet için medeni hukuk ehliyeti şart değildir\n\nII. Küçük adına vergiyi doğuran olay gerçekleşebilir\n\nIII. Yasak faaliyetten doğan olay vergisel sorumluluğu her durumda kaldırır","correct":"I ve II","why":"Kanuni ehliyet aranmaksızın mükellefiyet doğabilir. Faaliyetin yasak olması vergi yükümlülüğünü kaldırmaz.","ref":"213 sayılı VUK m. 9","difficulty":"medium"},
    {"stem":"Temsil ve miras bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Küçüğün vergisel ödevini kanuni temsilci yerine getirir\n\nII. Mirasçı vergi borcundan her durumda terekenin tamamı kadar sorumludur\n\nIII. Mirası reddetmeyen mirasçının sorumluluğu miras payı oranındadır","correct":"I ve III","why":"Küçüğün ödevini temsilci yerine getirir; mirasçı ise ölünün vergi borcundan kendi miras hissesi oranında sorumludur.","ref":"213 sayılı VUK m. 10 ve 12","difficulty":"medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="vergi_hukuku",
        topic_id="vergi_hukuku_ilkeleri",
        label="Vergi Hukukunun Temel İlkeleri",
        slug="vergi_hukuku_ilkeleri",
        prefix="topic-vh-ti",
        seed=20260720,
        legislation_version="2709 sayılı Anayasa ve 213 sayılı VUK, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
