#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Ruhsat ve Staj, 3×20."""
from topic_pack_builder import write_topic


SHORT = {
    "Hayır; mesleki disiplin, bilgi, deneyim ve yeterlilik kazandırır": "Hayır; staj adayı mesleğe hazırlar",
    "Meslek etiği ve meslek bilincini yerleştirmek": "Meslek etiği ve bilinç kazanımı",
    "Yabancı dil ve bilgi teknolojileri": "Dil ve bilgi teknolojileri",
    "Genel şartlar ile kanundaki öğrenim şartları": "Genel koşullar ve lisans öğrenimi",
    "Sınav süresi üç yıl olduğundan hakkı sona ermiştir": "Sınav süresi dolmuştur",
    "Sınav sonucu geçersiz olur ve dosya kaldırılır": "Sonuç geçersiz; dosya kaldırılır",
    "Sonraki dönemden başlayarak üç yıl içinde": "İzleyen dönemden itibaren üç yıl",
    "Hayır; staj süresi üç yıldır": "Hayır; staj üç yıldır",
}


def r(s, f, c, d, w, ref, difficulty="medium", fc=None, fd=None, fw=None):
    c = SHORT.get(c, c)
    fc = SHORT.get(fc or c, fc or c)
    return {"scenario": s, "focus": f, "correct": c, "focus_correct": fc,
            "distractors": list(d), "focus_distractors": list(fd or d), "why": w,
            "focus_why": fw or f"Bu kuralın odak sonucu şudur: {w}",
            "ref": ref, "difficulty": difficulty}


RULES = [
    r("Staj programı yalnız işgücü sağlamak amacıyla düzenlenmiştir. Bu yaklaşım yönetmeliğe uygun mudur?", "SMMM stajının temel amacı hangisidir?", "Hayır; mesleki disiplin, bilgi, deneyim ve yeterlilik kazandırır", ["Evet; yalnız ücretsiz işgücü sağlamaktır", "Sadece oda aidatı toplamaktır", "Yalnız vergi incelemesi yaptırmaktır", "Adayı meslekten uzaklaştırmaktır"], "Staj, mesleki disiplin, bilgi, deneyim ve yeterliliğe sahip meslek mensubu yetiştirmeyi amaçlar.", "SMMM Staj Yönetmeliği m. 5/a", "easy", fc="Nitelikli meslek mensubu yetiştirmek"),
    r("Staj programında meslek etiği ve meslek bilincine hiç yer verilmemiştir. Hedefler bakımından eksik olan nedir?", "Stajın hedefleri arasında hangi mesleki değer yer alır?", "Meslek etiği ve meslek bilincini yerleştirmek", ["Adayı ticari rekabete yöneltmek", "Müşteri sırlarını açıklatmak", "Meslek unvanını ruhsatsız kullandırmak", "Denetimsiz büro açtırmak"], "Meslek etiği ve meslek bilincini yerleştirmek stajın açık hedeflerindendir.", "SMMM Staj Yönetmeliği m. 6/a", "easy"),
    r("Adayın programı yabancı dil ve bilgi teknolojilerini bütünüyle dışlamıştır. Yönetmeliğin hedefleriyle uyumlu mudur?", "Staj hedeflerinden biri adaylara hangi çağdaş beceriler için olanak sağlamaktır?", "Yabancı dil ve bilgi teknolojileri", ["Yalnız satış ve pazarlama", "Sadece beden eğitimi", "Ruhsatsız temsil yetkisi", "Ticari sırların paylaşılması"], "Staj, yabancı dil ve bilgi teknolojileri eğitimine olanak sağlamayı hedefler.", "SMMM Staj Yönetmeliği m. 6/c", "easy"),
    r("Lisans öğrenim şartını taşımayan ve 3568 sayılı Kanunun genel şartlarını sağlamayan kişi staja başvurmuştur. Sonuç nedir?", "Staja başlamada hangi temel şart grupları birlikte aranır?", "Genel şartlar ile kanundaki öğrenim şartları", ["Yalnız işverenin sözlü izni", "Sadece oda aidatının ödenmesi", "Herhangi bir lise diploması", "Meslek mensubu akrabaya sahip olmak"], "Aday, Kanunun genel şartlarını ve SMMM için öngörülen öğrenim şartını taşımalıdır.", "SMMM Staj Yönetmeliği m. 7; 3568 sayılı Kanun m. 4 ve 5/A-a", "medium"),
    r("Aday staja giriş sınavından 58 puan almıştır. Başarı eşiği bakımından staja başlayabilir mi?", "Staja giriş sınavında yönetmelikteki asgari başarı puanı kaçtır?", "Hayır; en az 60 puan gerekir", ["Evet; 40 puan yeterlidir", "Evet; puan şartı yoktur", "Yalnız 100 tam puanla başlanır", "Sınava girmeden başlanabilir"], "Staja başlamak için staja giriş sınavından en az 60 puan alınmalıdır.", "SMMM Staj Yönetmeliği m. 7", "easy", fc="En az 60 puan"),
    r("Aday ilk staja giriş sınavı sonucunun ilanından dört yıl sonra aynı sınav hakkını kullanmak istemektedir. Sonuç nedir?", "Aday, ilk sınav sonucunun ilanından itibaren açılacak sınavlara kaç yıllık sürede katılabilir?", "Sınav süresi üç yıl olduğundan hakkı sona ermiştir", ["Sınav hakkı süresizdir", "Beş yıl boyunca uzatılabilir", "Yalnız on yıl sonra sona erer", "Oda başkanı süreyi sınırsız uzatabilir"], "2025 değişikliğiyle sınavlara katılma süresi ilk sonuç ilanından itibaren üç yıldır ve uzatılamaz.", "SMMM Staj Yönetmeliği m. 7", "medium", fc="Üç yıl"),
    r("Staja giriş sınavını kazanan kişi, sonuçtan sonraki staja başlama döneminden itibaren üç yıl içinde başlamamıştır. Sonuç nedir?", "Başarılı sınav sonucuyla staja başlama hakkı hangi sürede kullanılmalıdır?", "Sınav sonucu geçersiz olur ve dosya kaldırılır", ["Hak ömür boyu korunur", "Staj kendiliğinden tamamlanır", "Aday doğrudan ruhsat alır", "Süre yalnız müşteri kararıyla uzar"], "Başarılı aday üç yıl içinde staja başlamazsa sınav sonucu geçersiz sayılır ve dosyası işlemden kaldırılır.", "SMMM Staj Yönetmeliği m. 7", "medium", fc="Sonraki dönemden başlayarak üç yıl içinde"),
    r("SMMM adayı iki yıllık stajın yeterli olduğunu ileri sürmektedir. Güncel süre bakımından doğru mudur?", "SMMM adayları için staj süresi ne kadardır?", "Hayır; staj süresi üç yıldır", ["Evet; süre iki yıldır", "Staj yalnız altı aydır", "Staj süresi beş yıldır", "Staj zorunluluğu yoktur"], "SMMM adayları için güncel staj süresi üç yıldır.", "SMMM Staj Yönetmeliği m. 8", "easy", fc="Üç yıl"),
    r("Aday herhangi bir özel neden bulunmadan stajını sık sık kesintiye uğratmak istemektedir. Genel kural nedir?", "SMMM stajının sürekliliği bakımından temel ilke hangisidir?", "Staj kural olarak kesintisiz yapılır", ["Aday dilediği kadar ara verebilir", "Staj yalnız hafta sonu yapılır", "Kesintiler stajı kendiliğinden bitirir", "Stajın fiilen yapılması gerekmez"], "Staj, yönetmelikteki özel nedenler dışında kesintisiz olarak yapılır.", "SMMM Staj Yönetmeliği m. 8", "easy"),
    r("İşyeri kapanması ve işten çıkma gibi olağan nedenlerle verilen aralar toplamı on dört aya ulaşmıştır. Süre sınırı bakımından sonuç nedir?", "Yönetmelikte sayılan olağan nedenlerle staja toplam ne kadar ara verilebilir?", "Toplam ara bir yılı aşamaz", ["Ara süresi sınırsızdır", "Her olay için üç yıl verilir", "Yalnız bir hafta ara verilebilir", "Ara stajı doğrudan tamamlar"], "İşyeri kapanması, nakil veya işten ayrılma gibi nedenlerle staja toplam en fazla bir yıl ara verilebilir.", "SMMM Staj Yönetmeliği m. 8", "medium", fc="En fazla bir yıl"),
    r("Ağır hastalık nedeniyle staj yapamayan aday, sebep ortadan kalktıktan bir ay sonra bildirim yapmıştır. Süresinde midir?", "Mücbir sebep sona erince aday ne kadar sürede belgeyle bildirim yapmalıdır?", "Hayır; on beş gün içinde bildirmeliydi", ["Evet; bildirim için süre yoktur", "Yalnız beş yıl içinde bildirilir", "Bildirim yalnız sözlü yapılır", "Mücbir sebep hiçbir zaman bildirilmez"], "Mücbir sebep ortadan kalktıktan sonra on beş gün içinde TESMER Şubesine veya odaya belgeli yazılı bildirim yapılır.", "SMMM Staj Yönetmeliği m. 8", "hard", fc="On beş gün içinde"),
    r("Aday yurt dışında çalışmaya başlamış, TESMER'e önceden başvurmamıştır. Usul bakımından eksiklik nedir?", "Yurt dışı eğitim veya çalışma öncesinde hangi işlem gerekir?", "TESMER'e yazılı başvuru ve izin", ["Yalnız müşteriye sözlü bildirim", "Hiçbir başvuru yapmamak", "Sadece vergi dairesinden ruhsat almak", "Oda kaydını kalıcı kapatmak"], "Yurt dışı eğitim veya çalışma öncesinde TESMER'e yazılı başvurulmalı ve izin alınmalıdır.", "SMMM Staj Yönetmeliği m. 8", "medium"),
    r("Aday stajını ruhsatlı bağımsız SMMM'nin yanında yapmaktadır. Yer bakımından uygun mudur?", "SMMM stajı kimlerin yanında veya şirketlerinde yapılabilir?", "Evet; bağımsız SMMM veya YMM yanında yapılabilir", ["Hayır; yalnız ruhsatsız danışmanda yapılır", "Sadece herhangi bir tacirin yanında yapılır", "Yalnız adayın kendi bürosunda yapılır", "Hiçbir meslek mensubu yanında yapılamaz"], "Staj bağımsız çalışan SMMM veya YMM yanında ya da şirketlerinde yapılabilir.", "3568 sayılı Kanun m. 6; SMMM Staj Yönetmeliği m. 9/a", "easy", fc="Bağımsız SMMM veya YMM yanında"),
    r("Aday TESMER kurs ve seminerlerinde sekiz ay geçirmiş ve tamamını stajdan saydırmak istemektedir. Üst sınır nedir?", "TESMER kurs ve seminerlerinde geçen sürenin ne kadarı stajdan sayılabilir?", "En fazla altı ayı stajdan sayılır", ["Sekiz ayın tamamı koşulsuz sayılır", "Hiçbir günü stajdan sayılmaz", "Yalnız üç yılı sayılır", "Süre sınırsız biçimde sayılır"], "TESMER kurs ve seminerlerinde geçen sürenin altı ayı aşmayan kısmı stajdan sayılabilir.", "SMMM Staj Yönetmeliği m. 9/a", "medium", fc="Altı ayı aşmayan kısmı"),
    r("Aday ilgili alanda tezli yüksek lisansını diploma ve teziyle belgelemiştir. Stajdan sayılabilecek süre nedir?", "İlgili alandaki tezli yüksek lisans staj süresinden ne kadar indirilebilir?", "Bir yıl", ["Hiçbir süre", "Üç ay", "On sekiz ay", "Üç yıl"], "İlgili alandaki tezli yüksek lisansın, diploma ve tez ibrazıyla bir yılı stajdan sayılır.", "SMMM Staj Yönetmeliği m. 9/d-2", "hard"),
    r("Aday ilgili alanda tezsiz veya uzaktan yüksek lisans yapmıştır. Stajdan sayılan süre hangisidir?", "Tezsiz ya da uzaktan yüksek lisans için staj mahsubu ne kadardır?", "Altı ay", ["Bir hafta", "Bir yıl", "On sekiz ay", "Üç yıl"], "İlgili alandaki tezsiz veya uzaktan yüksek lisansın altı ayı stajdan sayılır.", "SMMM Staj Yönetmeliği m. 9/d-2", "hard"),
    r("Aday ilgili alandaki doktorasını diploma ve teziyle belgelemiştir. Stajdan sayılabilecek süre nedir?", "İlgili alandaki doktora eğitiminin staj mahsubu ne kadardır?", "On sekiz ay", ["Üç ay", "Altı ay", "Bir yıl", "Üç yıl"], "İlgili alandaki doktora eğitiminin on sekiz ayı, diploma ve tez şartıyla stajdan sayılır.", "SMMM Staj Yönetmeliği m. 9/d-3", "hard"),
    r("Aday staj boyunca TESMER'in zorunlu eğitimine katılmamıştır. Sonuç nedir?", "Zorunlu eğitim programına katılmamanın staja etkisi hangisidir?", "Stajı iptal edilir", ["Stajı kendiliğinden uzatılmadan tamamlanır", "Aday doğrudan ruhsat alır", "Yalnız ücret indirimi uygulanır", "Hiçbir sonuç doğmaz"], "Staj süresince zorunlu eğitime katılmayan adayın stajı iptal edilir.", "SMMM Staj Yönetmeliği m. 10 ve 24/c", "medium"),
    r("Aday staj başvurusunu haziran ayında yapmak istemektedir. Yönetmelikteki dönemlere uygun mudur?", "Staj başvuruları hangi aylarda alınır?", "Hayır; nisan, ağustos ve aralık aylarında", ["Evet; yalnız haziran ayında", "Her gün sınırsız başvuru alınır", "Yalnız ocak ve temmuzda", "Sadece seçim yıllarında"], "Staj başvuruları her yıl nisan, ağustos ve aralık aylarında yapılır.", "SMMM Staj Yönetmeliği m. 11", "medium", fc="Nisan, ağustos ve aralık"),
    r("Aday, aleyhindeki oda kararına tebliğden yirmi gün sonra itiraz etmiştir. Süre bakımından sonuç nedir?", "Aday meslek mensubunun oda kararına Birlik nezdindeki itiraz süresi kaç gündür?", "Süre geçmiştir; itiraz on beş gündür", ["İtiraz süresi bir yıldır", "Süre sınırsızdır", "Yalnız üç gün içinde itiraz edilir", "Oda kararına hiçbir zaman itiraz edilemez"], "Aday, oda kararının tebliğinden itibaren on beş gün içinde Birliğe itiraz edebilir.", "SMMM Staj Yönetmeliği m. 13", "hard", fc="On beş gün"),
    r("Aday stajına mart ayında başlamak istemektedir. Yönetmelikteki başlangıç dönemine uygun mudur?", "Staja hangi aylarda başlanır?", "Hayır; ocak, mayıs veya eylül döneminde başlanır", ["Evet; yalnız mart başlangıç ayıdır", "Sadece haziran ayında başlanır", "Her aday farklı bir yıl seçer", "Başlangıç dönemi bulunmaz"], "Staja her yıl ocak, mayıs ve eylül aylarında başlanır.", "SMMM Staj Yönetmeliği m. 16", "medium", fc="Ocak, mayıs ve eylül"),
    r("Aday bir yılda mazeretsiz üç denetimde staj yerinde bulunamamıştır. Sonuç nedir?", "Bir yılda kaç kez mücbir sebep olmadan staj mahallinde bulunmama iptal nedenidir?", "Stajı iptal edilir", ["Stajı koşulsuz tamamlanır", "Yalnız sözlü teşekkür verilir", "Aday doğrudan SMMM olur", "Hiçbir işlem yapılmaz"], "Bir yılda üç defa mücbir sebep olmaksızın staj mahallinde bulunmayanın stajı iptal edilir.", "SMMM Staj Yönetmeliği m. 16 ve 24/d", "medium", fc="Üç kez"),
    r("Aday, iş yoğunluğu nedeniyle staj süresinin keyfî olarak kısaltılmasını istemektedir. Mümkün müdür?", "Staja devam ve sürenin kısaltılması bakımından temel kural hangisidir?", "Hayır; devam zorunludur ve süre kısaltılamaz", ["Evet; aday dilediği kadar kısaltabilir", "Yalnız müşteri talebiyle staj biter", "Stajın fiilen yapılması gerekmez", "Oda kaydı süre yerine geçer"], "Staja devam zorunludur ve yönetmelikteki mahsup hükümleri dışında staj süresi keyfî kısaltılamaz.", "SMMM Staj Yönetmeliği m. 17", "easy", fc="Devam zorunludur; süre kısaltılamaz"),
    r("Staj programlarının hazırlanması, uygulanması ve denetlenmesi için Birlik bünyesinde hangi merkez kurulur?", "TESMER'in staj sistemindeki temel görevi hangisidir?", "Temel Eğitim ve Staj Merkezi", ["Vergi Denetim Kurulu", "Ticaret Sicili Müdürlüğü", "Kamu Gözetimi Kurumu", "Gelir İdaresi Başkanlığı"], "TÜRMOB, staj programlarını hazırlamak, uygulamak ve denetlemek üzere TESMER'i kurar.", "SMMM Staj Yönetmeliği m. 18", "easy", fc="Programları hazırlamak, uygulamak ve denetlemek"),
    r("Aday ilgili staj döneminin on ikinci gününde fiilen başlamıştır. Süre bakımından uygun mudur?", "Başarılı aday ilgili staj döneminde en geç ne zaman fiilen başlamalıdır?", "Hayır; ilk on gün içinde başlamalıdır", ["Evet; ilk ayın sonu yeterlidir", "Başlangıç için süre yoktur", "Yalnız yıl sonunda başlamalıdır", "Üç yıl sonra başlamalıdır"], "Aday ilgili staj döneminin ilk on günü içinde fiilen staja başlamak zorundadır.", "SMMM Staj Yönetmeliği m. 19", "medium", fc="İlk on gün içinde"),
    r("Aday kendi adına müşterinin defterini tutarak mesleki hizmet sunmak istemektedir. Staj sırasında mümkün müdür?", "Aday meslek mensubu kendi nam ve hesabına meslek mensubunun yapabileceği işleri yapabilir mi?", "Hayır; kendi adına mesleki iş yapamaz", ["Evet; ruhsat almadan sınırsız yapabilir", "Yalnız başka aday adına yapabilir", "Sadece oda dışında serbesttir", "Müşteri isterse unvan kullanabilir"], "Aday kendi nam ve hesabına meslek mensuplarının yapabileceği işleri yapamaz.", "SMMM Staj Yönetmeliği m. 23", "medium"),
]


PREMISES = [
    {"stem":"Stajın amaç ve hedefleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Meslek etiğini yerleştirmek amaçlanır\n\nII. Mesleki bilgi ve uygulama geliştirilir\n\nIII. Ulusal ve uluslararası standartlar etkin kılınır","correct":"I, II ve III","why":"Üç ifade de yönetmelikteki staj hedefleridir.","ref":"SMMM Staj Yönetmeliği m. 5-6","difficulty":"easy"},
    {"stem":"Staja giriş bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Öğrenim şartı aranır\n\nII. Giriş sınavında 50 puan yeterlidir\n\nIII. Başarılı sonuçla staja başlama süresi üç yıldır","correct":"I ve III","why":"Öğrenim şartı ve üç yıllık başlama süresi vardır; sınavda en az 60 puan aranır.","ref":"SMMM Staj Yönetmeliği m. 7","difficulty":"medium"},
    {"stem":"Staj süresi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. SMMM stajı iki yıldır\n\nII. Olağan nedenlerle ara toplamda bir yılı aşamaz\n\nIII. Staj süresi keyfî olarak kısaltılamaz","correct":"II ve III","why":"Staj üç yıldır; olağan ara üst sınırı bir yıl ve keyfî kısaltma yasaktır.","ref":"SMMM Staj Yönetmeliği m. 8 ve 17","difficulty":"medium"},
    {"stem":"Eğitim sürelerinin stajdan sayılması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tezli yüksek lisansın bir yılı sayılabilir\n\nII. İlgili doktoranın yalnız altı ayı sayılır\n\nIII. Tezsiz yüksek lisansın altı ayı sayılabilir","correct":"I ve III","why":"Tezli yüksek lisans için bir yıl, tezsiz için altı ay; doktora için on sekiz ay öngörülür.","ref":"SMMM Staj Yönetmeliği m. 9/d","difficulty":"hard"},
    {"stem":"Stajın yürütülmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Staj ruhsatsız danışman yanında yapılabilir\n\nII. Zorunlu eğitime katılmama iptal nedenidir\n\nIII. Stajın fiilen yapılması gerekmez","correct":"Yalnız II","why":"Staj uygun SMMM veya YMM yanında fiilen yapılır ve zorunlu eğitim aranır; yalnız II doğrudur.","ref":"SMMM Staj Yönetmeliği m. 9-10","difficulty":"medium"},
    {"stem":"Staj dönemleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Başvurular nisan, ağustos ve aralıkta yapılır\n\nII. Başlangıç ocak, mayıs ve eylül dönemlerindedir\n\nIII. Başarılı aday dönemin ilk on gününde fiilen başlar","correct":"I, II ve III","why":"Başvuru, dönem ve fiilî başlangıç kuralları üç ifadede doğru verilmiştir.","ref":"SMMM Staj Yönetmeliği m. 11, 16 ve 19","difficulty":"hard"},
    {"stem":"Adayın yükümlülükleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kendi nam ve hesabına mesleki iş yapamaz\n\nII. Staj yerine devam zorunlu değildir\n\nIII. Mazeretsiz üç yokluk iptal nedenidir","correct":"I ve III","why":"Aday bağımsız mesleki iş yapamaz ve devam zorunludur; üç mazeretsiz yokluk iptal nedenidir.","ref":"SMMM Staj Yönetmeliği m. 16, 17 ve 23","difficulty":"medium"},
    {"stem":"Mücbir sebep ve yurt dışı çalışması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mücbir sebep sona erince otuz günde bildirim yapılır\n\nII. Yurt dışı çalışma öncesi TESMER izni gerekir\n\nIII. Eksik kalan staj süresi tamamlatılır","correct":"II ve III","why":"Bildirim süresi on beş gündür; yurt dışı çalışma için ön izin gerekir ve eksik süre tamamlatılır.","ref":"SMMM Staj Yönetmeliği m. 8","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(lesson_id="meslek_hukuku", topic_id="ruhsat_ve_staj",
                label="Ruhsat ve Staj", slug="ruhsat_ve_staj",
                prefix="topic-mh-rs", seed=170742,
                legislation_version="3568 sayılı Kanun ve SMMM Staj Yönetmeliği, 17.07.2026 yürürlük durumu",
                rules=RULES, premises=PREMISES, wrong_banks={})
