#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Mesleki Sorumluluk, 3×20."""
from topic_pack_builder import write_topic


SHORT = {
    "Mesleki eğitime katılarak bilgisini geliştirmek": "Mesleki eğitimle bilgisini güncellemek",
    "Birlik ve odaların mesleki eğitimleriyle": "Birlik ve oda mesleki eğitimleriyle",
    "Dürüstlük, güvenilirlik ve tarafsızlık": "Dürüstlük ve tarafsızlık",
    "Gerekli mesleki özen ve titizlik": "Mesleki özen ve titizlik",
    "Evet; oda ve Birlik personeline de uygulanır": "Evet; oda ve Birlik personeli de",
    "Hayır; toplum ve Devlete karşı da sorumludur": "Hayır; topluma ve Devlete de",
    "Bilgi paylaşımı ve mesleki dayanışma": "Mesleki bilgi ve dayanışma",
    "İşi kendi sorumluluğunda bağımsız yürütmelidir": "İşi bağımsız ve sorumlu yürütmek",
    "Kendi sorumluluğunda tam bağımsız çalışmak": "İşi bağımsız ve sorumlu yürütmek",
    "Meslek mensubunun hukuki sorumluluğunu": "Hukuki sorumluluk doğurur",
    "Hayır; ceza hükümleri ayrıca uygulanabilir": "Hayır; ceza ayrıca uygulanır",
    "Defter ve belgeleri özenle muhafaza etmek": "Defterleri özenle korumak",
    "Hayır; mesleği yasaklanan kişi çalıştırılamaz": "Hayır; yasaklı kişi çalıştırılamaz",
    "Mesleği yapması yasaklananı çalıştırmamak": "Yasaklı kişiyi çalıştırmamak",
    "Evet; karşılıklı sorumluluklar yazılmalıdır": "Evet; sorumluluklar yazılmalıdır",
    "Bir ay içinde devir-teslim tutanağıyla iade": "Tutanakla bir ay içinde iade",
    "Düzenli dosya ve çalışma kâğıdı tutma": "Düzenli müşteri dosyası tutmak",
    "Çalışma kâğıtları, yazışmalar ve gerekli belgeler": "Çalışma kâğıdı ve gerekli belgeler",
    "İşi yapan meslek mensubuna": "İşi yapan kişiye",
    "İşi yapan meslek mensubuna aittir": "İşi yapan kişiye aittir",
    "Yaptığı tasdikin doğruluğundan": "Tasdik doğruluğundan",
    "Tasdik doğruluğu ve rapor kapsamından": "Tasdik ve rapor kapsamından",
    "Tasdik kapsamıyla sınırlı müşterek ve müteselsil": "Sınırlı müteselsil sorumluluk",
}


def r(s, f, c, d, w, ref, difficulty="medium", fc=None, fd=None):
    c = SHORT.get(c, c)
    fc = SHORT.get(fc or c, fc or c)
    return {"scenario": s, "focus": f, "correct": c, "focus_correct": fc,
            "distractors": list(d), "focus_distractors": list(fd or d), "why": w,
            "focus_why": f"Sorumluluk kuralının sonucu şudur: {w}",
            "ref": ref, "difficulty": difficulty}


RULES = [
    r("Ruhsatlı meslek mensubu, unvanının gerektirdiği güveni zedeleyen biçimde davranmıştır. Hangi genel standardı ihlal etmiştir?", "Meslek unvanı ve yeterlilik ilkesi meslek mensubundan nasıl davranmasını ister?", "Unvanın saygı ve güvenine yakışır davranma", ["Müşteri bilgilerini tanıtımda kullanma", "Meslektaşı hakkında asılsız açıklama yapma", "Ruhsatı başkasına kullandırma", "Mesleki özeni tamamen bırakma"], "Meslek mensubu, mesleki unvanının gerektirdiği saygı ve güvene yakışır biçimde hareket eder.", "Çalışma Usulleri Yönetmeliği m. 4", "easy", fc="Unvana yaraşır saygı ve güveni korumak"),
    r("Meslek mensubu yıllardır hiçbir mesleki eğitim almadan güncelliğini kaybetmiştir. Bilgi sorumluluğu bakımından eksiklik nedir?", "Mesleki bilgi hangi yolla geliştirilir ve bu çalışmaları kim yürütür?", "Mesleki eğitime katılarak bilgisini geliştirmek", ["Yalnız müşteri söylentilerini izlemek", "Teknik standartları dikkate almamak", "Ruhsat bilgisini hiç yenilememek", "Eğitimi yalnız stajyerlere bırakmak"], "Mesleki bilgi, Birlik ve odalarca yürütülen mesleki eğitimlerle geliştirilir.", "Çalışma Usulleri Yönetmeliği m. 5", "easy", fc="Birlik ve odaların mesleki eğitimleriyle"),
    r("SMMM çıkar çatışmasını gizleyerek taraflı bir rapor hazırlamıştır. Hangi sorumluluk standardına aykırıdır?", "Mesleğin temelini oluşturan üç davranış şartı hangileridir?", "Dürüstlük, güvenilirlik ve tarafsızlık", ["Yakınlık, reklam ve ücret", "Ticaret, ortaklık ve rekabet", "Gizleme, taraf tutma ve baskı", "Ruhsatsızlık, sessizlik ve çıkar"], "Dürüstlük, güvenilirlik ve tarafsızlık mesleğin temelidir; çıkar çatışmalarından uzak durulur.", "Çalışma Usulleri Yönetmeliği m. 6", "easy"),
    r("Meslek mensubu işi yetiştirmek için gerekli incelemeleri yapmadan beyanda bulunmuştur. Temel eksiklik nedir?", "Görev yürütülürken hangi mesleki davranış gösterilmelidir?", "Gerekli mesleki özen ve titizlik", ["Müşteriye koşulsuz bağlılık", "Rakip meslektaşı küçültme", "Bilgileri üçüncü kişiye verme", "Sorumluluğu stajyere bırakma"], "Meslek mensubu görevinde gereken mesleki özen ve titizliği göstermekle yükümlüdür.", "Çalışma Usulleri Yönetmeliği m. 6", "easy"),
    r("SMMM faaliyeti sona erdikten sonra eski müşterisinin sırlarını açıklayabileceğini düşünmektedir. Doğru mudur?", "Sır saklama yükümlülüğü mesleki faaliyet sona erince ne olur?", "Hayır; faaliyet sona erse de sürer", ["Evet; bütün bilgiler serbest kalır", "Yalnız bir hafta devam eder", "Sadece ücret ödenirse sürer", "Sorumluluk müşteriye geçer"], "Mesleki faaliyet dolayısıyla öğrenilen bilgi ve sırlar, faaliyet sona erse bile açıklanamaz.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "easy", fc="Faaliyet sonrasında da devam eder"),
    r("Meslek mensubu öğrendiği bilgiyi ihbar ederek muhbirlere tanınan parasal menfaatten yararlanmak istemektedir. Mümkün müdür?", "Mesleki sır nedeniyle muhbirlere tanınan hak ve menfaatlerden yararlanma kuralı nedir?", "Hayır; bu menfaatlerden yararlanamaz", ["Evet; her sır için ödül alabilir", "Yalnız müşteri izni olmadan alabilir", "Sadece oda çalışanları yararlanabilir", "Menfaat almak mesleki zorunluluktur"], "Meslek mensupları ve çalışanları, mesleki sırlarla bağlantılı olarak muhbirlere tanınan hak ve menfaatlerden yararlanamaz.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "medium"),
    r("SMMM, adli yargıya göre suç teşkil eden bir hâli görev sırasında öğrenmiştir. Ne yapmalıdır?", "Sır saklama kuralının suç teşkil eden hâller bakımından getirdiği görev nedir?", "Yetkili mercilere duyurmalıdır", ["Suçu her durumda gizlemelidir", "Bilgiyi yalnız rakibe vermelidir", "Müşteriden menfaat istemelidir", "Dosyayı yok etmelidir"], "Adli yargıya göre suç teşkil eden hâllerin yetkili mercilere duyurulması zorunludur.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "hard"),
    r("Yetkili idari soruşturmada meslek mensubundan görev bilgisi istenmiştir. Sır saklama bu incelemeyi engeller mi?", "Adli veya idari inceleme ve soruşturmaların sır saklama karşısındaki durumu nedir?", "Hayır; inceleme ve soruşturma istisnadır", ["Evet; hiçbir bilgi istenemez", "Yalnız müşteri soruşturması engeller", "Sadece oda başkanı bilgi verebilir", "Bütün incelemeler kendiliğinden sona erer"], "Adli veya idari inceleme ve soruşturmalar sır saklama yasağının dışındadır.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "medium", fc="Sır saklama yasağının dışındadır"),
    r("Meslek mensubu mahkemede usulüne uygun tanıklık yapmıştır. Bu, sır ifşası sayılır mı?", "Kanuna göre tanıklığın sır saklama yükümlülüğü karşısındaki niteliği nedir?", "Hayır; tanıklık sır ifşası sayılmaz", ["Evet; her tanıklık disiplin suçudur", "Yalnız ücretli tanıklık serbesttir", "Tanıklık meslekten çıkarmayı gerektirir", "Mahkeme önünde hiç konuşulamaz"], "Usulüne uygun tanıklık kanunen sırrın ifşası sayılmaz.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "easy"),
    r("Oda çalışanı üye dosyasındaki sırları üçüncü kişiye açıklamıştır. Sır saklama hükümleri ona uygulanır mı?", "Sır saklama kuralları meslek mensupları dışında kimleri de kapsar?", "Evet; oda ve Birlik personeline de uygulanır", ["Hayır; yalnız müşteriyi bağlar", "Sadece vergi müfettişini bağlar", "Yalnız ruhsatsız kişileri kapsar", "Personel bütün bilgileri yayımlayabilir"], "Sır saklama hükümleri meslek mensubu ve çalışanlarının yanında oda ve Birlik personeline de uygulanır.", "3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7", "medium", fc="Oda ve Birlik personelini de"),
    r("SMMM yalnız müşterisine karşı sorumlu olduğunu, toplum ve Devlete karşı görevi bulunmadığını savunmaktadır. Doğru mudur?", "Sosyal sorumluluk standardı meslek mensubunu kime karşı sorumlu tutar?", "Hayır; toplum ve Devlete karşı da sorumludur", ["Evet; yalnız ücret ödeyen müşteriye", "Sadece büro çalışanına", "Yalnız rakip meslektaşa", "Hiç kimseye karşı sorumlu değildir"], "Meslek mensubu mesleği yürütürken toplum ve Devlete karşı sosyal sorumluluk taşır.", "Çalışma Usulleri Yönetmeliği m. 8/a", "easy", fc="Topluma ve Devlete karşı"),
    r("İşletme yöneticisi karar almak için SMMM'den bilgi istemiştir. Meslek mensubunun sorumluluğu nedir?", "İşletme sahip ve yöneticilerine karşı mesleki sorumluluğun özü hangisidir?", "Doğru ve güvenilir bilgi sağlamak", ["Yanıltıcı verileri saklamak", "Kararı baskıyla yönlendirmek", "Bilgiyi rakiplere açıklamak", "İşletmenin yerine ticari karar vermek"], "Meslek mensubu, isabetli karar alınabilmesi için işletme sahip ve yöneticilerine doğru ve güvenilir bilgi sağlar.", "Çalışma Usulleri Yönetmeliği m. 8/b", "easy"),
    r("Bir meslek mensubu, mesleki eğitimde meslektaşından gerekli bilgiyi kasıtlı biçimde saklamıştır. Hangi sorumluluğa aykırıdır?", "Meslektaşlara karşı sorumluluk hangi davranışları gerektirir?", "Bilgi paylaşımı ve mesleki dayanışma", ["Müşteri sırlarını herkese açıklama", "Ücret kırarak iş alma", "Meslektaşı asılsız biçimde suçlama", "Ruhsatı başkasına kullandırma"], "Meslek mensupları mesleki eğitimde bilgi aktarır ve mesleğin gelişmesi için dayanışma kurar.", "Çalışma Usulleri Yönetmeliği m. 8/c", "medium"),
    r("Müşteri SMMM'den bağımsız yargısını bırakıp kendi talimatına göre rapor yazmasını istemiştir. SMMM ne yapmalıdır?", "Mesleki bağımsızlık sorumluluğunun temel kuralı hangisidir?", "İşi kendi sorumluluğunda bağımsız yürütmelidir", ["Yargısını müşteriye devretmelidir", "Raporu incelemeden imzalamalıdır", "Çıkar ilişkisini gizlemelidir", "Mesleki standardı terk etmelidir"], "Meslek mensubu çalışmalarını kendi sorumluluğu altında tam bağımsızlıkla yürütür.", "Çalışma Usulleri Yönetmeliği m. 9", "medium", fc="Kendi sorumluluğunda tam bağımsız çalışmak"),
    r("Meslek mensubu bağımsızlığına gölge düşürecek yakın mali ilişkiye girmiştir. Doğru yaklaşım nedir?", "Bağımsızlıkla bağdaşmayan ilişki ve davranışlar karşısındaki görev nedir?", "Bu ilişki ve davranışlardan kaçınmak", ["İlişkiyi müşteriden saklayıp sürdürmek", "Bağımsızlığı yalnız görünüşte korumak", "Mesleki kararı üçüncü kişiye bırakmak", "Çıkar çatışmasını artırmak"], "Meslek mensubu bağımsızlığına gölge düşürecek ilişki ve davranışlardan kaçınır.", "Çalışma Usulleri Yönetmeliği m. 9", "medium"),
    r("Meslek mensubu verdiği hizmette VUK'taki iştirak, teşvik ve yardım hükümlerine uyan fiile katılmıştır. Hukuki sonuç nedir?", "Vergi Usul Kanunundaki iştirak, teşvik ve yardım niteliğindeki fiiller meslek mensubu için ne doğurur?", "Meslek mensubunun hukuki sorumluluğunu", ["Kendiliğinden sorumsuzluk", "Yalnız ücret indirimi", "Müşterinin ruhsat almasını", "Oda kaydının ödüle çevrilmesini"], "Meslek mensubu, hizmet sırasında VUK'taki iştirak, teşvik ve yardım hükümlerine uyan fiilleri nedeniyle sorumludur.", "Çalışma Usulleri Yönetmeliği m. 21", "hard", fc="Hukuki sorumluluk doğurur"),
    r("Meslek mensubunun fiiline hukuki sorumluluk uygulanmıştır. Kanun ve yönetmelikteki ceza hükümleri artık uygulanamaz mı?", "Hukuki sorumluluk ile mesleki ceza hükümlerinin ilişkisi nedir?", "Hayır; ceza hükümleri ayrıca uygulanabilir", ["Evet; bütün cezalar ortadan kalkar", "Yalnız müşteri karar verir", "Sorumluluk ücret iadesiyle biter", "Ceza ancak ruhsatsız kişiye uygulanır"], "Hukuki sorumluluk, kanun ve yönetmeliklerdeki ceza hükümlerinin ayrıca uygulanmasını engellemez.", "Çalışma Usulleri Yönetmeliği m. 21", "hard", fc="Birbirinden bağımsız uygulanabilirler"),
    r("SMMM tuttuğu defter ve belgeleri korumasız ortamda kaybetmiştir. Bildirim ve muhafaza sorumluluğu bakımından eksiklik nedir?", "SMMM'nin tuttuğu defter ve ilgili belgelere ilişkin yükümlülüğü nedir?", "Defter ve belgeleri özenle muhafaza etmek", ["Belgeleri istediği anda yok etmek", "Defterleri müşteriden gizlemek", "Belgeleri rakibe teslim etmek", "Muhafazayı tamamen stajyere bırakmak"], "SMMM, tuttuğu defterleri ve ilgili belgeleri itinalı biçimde muhafaza etmek zorundadır.", "Çalışma Usulleri Yönetmeliği m. 20", "medium"),
    r("Mesleği yapması yetkili mercilerce yasaklanan kişi SMMM bürosunda mesleki yardımcı olarak çalıştırılmıştır. Mümkün müdür?", "Meslek mensubunun işyerinde çalıştırabileceği kişiler bakımından yasak hangisidir?", "Hayır; mesleği yasaklanan kişi çalıştırılamaz", ["Evet; hiçbir sınırlama yoktur", "Yalnız müşteri onayı yeterlidir", "Sadece ücretsiz çalıştırılabilir", "Yasaklı kişi büroya ortak olabilir"], "Meslek mensubu, mesleği yapması yetkili mercilerce yasaklanan kişiyi yanında çalıştıramaz.", "Çalışma Usulleri Yönetmeliği m. 22", "medium", fc="Mesleği yapması yasaklananı çalıştırmamak"),
    r("Mesleki hizmet sözleşmesinde tarafların sorumluluk ve yükümlülükleri hiç gösterilmemiştir. Asgari içerik bakımından eksik midir?", "Mesleki sözleşmede bulunması gereken asgari unsurlardan biri hangisidir?", "Evet; karşılıklı sorumluluklar yazılmalıdır", ["Hayır; sözleşmede hiçbir bilgi gerekmez", "Yalnız meslektaşın unvanı yeterlidir", "Sadece müşterinin reklamı yazılır", "Ücret ve kapsamın yazılması yasaktır"], "Mesleki hizmet sözleşmesinde tarafların karşılıklı sorumluluk ve yükümlülükleri asgari unsur olarak yer alır.", "Çalışma Usulleri Yönetmeliği m. 25/c", "easy", fc="Tarafların sorumluluk ve yükümlülükleri"),
    r("Sözleşme feshedildiği hâlde müşterinin defter ve belgeleri tutanak olmadan aylarca elde tutulmuştur. Doğru işlem nedir?", "Fesihte alınmış defter ve belgeler hangi usulle geri verilir?", "Bir ay içinde devir-teslim tutanağıyla iade", ["Süresiz olarak büroda tutulur", "Tutanaksız biçimde üçüncü kişiye verilir", "Belgeler doğrudan imha edilir", "Yalnız rakip meslek mensubuna gönderilir"], "Fesihte defter ve belgeler bir ay içinde devir-teslim tutanağı düzenlenerek sahibine geri verilir.", "Çalışma Usulleri Yönetmeliği m. 26", "medium", fc="Devir-teslim tutanağıyla bir ay içinde"),
    r("Müşteri iş bitiminde defterlerini geri almamış; yazılı bildirime rağmen bir ay geçmiştir. Meslek mensubu ne yapmalıdır?", "İş bitiminde alınmayan defter ve belgelerin son teslim yeri neresidir?", "İlgilinin bağlı olduğu vergi dairesine teslim", ["Meslek mensubunun özel arşivine süresiz kaldırma", "Rakip işletmeye teslim", "Belgeleri habersiz imha", "Ticaret odasına satış"], "İş bitiminden sonra yazılı bildirime rağmen bir ayda alınmayan defter ve belgeler ilgilinin vergi dairesine teslim edilir.", "Çalışma Usulleri Yönetmeliği m. 27", "hard", fc="İlgilinin vergi dairesi"),
    r("SMMM müşterisi için çalışma kâğıtlarını ve yazışmaları içeren dosya tutmamıştır. Hangi sorumluluğu ihlal etmiştir?", "Müşteri dosyasında hangi belgelerin düzenli saklanması gerekir?", "Düzenli dosya ve çalışma kâğıdı tutma", ["Müşteri sırrını herkese açıklama", "Belgeleri kayıtsız biçimde yok etme", "Yalnız reklam metni saklama", "Dosyayı rakip işletmeye verme"], "Meslek mensubu her müşteri için çalışma kâğıtları, yazışmalar ve gerekli belgeleri içeren düzenli dosya tutar.", "Çalışma Usulleri Yönetmeliği m. 28", "medium", fc="Çalışma kâğıtları, yazışmalar ve gerekli belgeler"),
    r("Meslek şirketindeki cezai sonuç doğuran işi belirli bir ortak yapmıştır. Cezai sorumluluk kime aittir?", "Ortaklık bürosu veya şirkette işten doğan cezai sorumluluk nasıl belirlenir?", "İşi yapan meslek mensubuna", ["Bütün müşterilere", "Hiç kimseye", "Yalnız oda başkanına", "Her durumda stajyere"], "Meslek şirketinde yapılan işten doğan cezai sorumluluk işi yapan meslek mensubuna aittir.", "Çalışma Usulleri Yönetmeliği m. 30/f", "hard", fc="İşi yapan meslek mensubuna aittir"),
    r("YMM tasdik raporunu yeterli inceleme yapmadan düzenlemiştir. Temel sorumluluğu nedir?", "YMM tasdik faaliyeti bakımından hangi sonuçtan sorumludur?", "Yaptığı tasdikin doğruluğundan", ["Yalnız müşterinin kârından", "Sadece büro kirasından", "Hiçbir mesleki sonuçtan", "Yalnız oda aidatından"], "YMM yaptığı tasdikin doğruluğundan sorumludur ve kapsamını raporda açıkça belirtir.", "3568 sayılı Kanun m. 12; Çalışma Usulleri Yönetmeliği m. 41", "medium", fc="Tasdik doğruluğu ve rapor kapsamından"),
    r("Gerçeğe aykırı YMM tasdiki nedeniyle vergi ziyaı ve ceza doğmuştur. Mali sorumluluk nasıl uygulanır?", "YMM'nin yanlış tasdikten doğan sorumluluğunun sınırı ve biçimi hangisidir?", "Tasdik kapsamıyla sınırlı müşterek ve müteselsil", ["Bütün mükellefler için sınırsız tek başına", "Yalnız ücret iadesiyle sınırlı", "Hiçbir mali sorumluluk olmadan", "Sadece disiplin uyarısı biçiminde"], "YMM tasdik kapsamıyla sınırlı olarak ziyaa uğratılan vergi ve cezalardan mükellefle müştereken ve müteselsilen sorumludur.", "3568 sayılı Kanun m. 12; Çalışma Usulleri Yönetmeliği m. 41", "hard"),
]


PREMISES = [
    {"stem":"Genel mesleki standartlar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Unvanın güvenine yakışır davranılır\n\nII. Mesleki bilgi eğitimle geliştirilir\n\nIII. Çıkar çatışmalarından uzak kalınır","correct":"I, II ve III","why":"Üç ifade de çalışma usullerindeki genel mesleki standartlardandır.","ref":"Çalışma Usulleri Yönetmeliği m. 4-6","difficulty":"easy"},
    {"stem":"Sır saklama sorumluluğu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Faaliyet sona erince de sürer\n\nII. Suç teşkil eden hâl yetkili mercie bildirilir\n\nIII. Tanıklık her durumda sır ifşasıdır","correct":"I ve II","why":"Sır yükümlülüğü sürer ve suç bildirilir; tanıklık sırrın ifşası sayılmaz.","ref":"3568 sayılı Kanun m. 43","difficulty":"medium"},
    {"stem":"Sır saklama hükümlerinin kapsamı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Meslek mensubu yanında çalışanları kapsar\n\nII. Oda ve Birlik personelini kapsar\n\nIII. Adli ve idari soruşturmayı mutlak biçimde engeller","correct":"I ve II","why":"Çalışanlar ile oda ve Birlik personeli kapsamdadır; yetkili soruşturmalar istisnadır.","ref":"3568 sayılı Kanun m. 43; Çalışma Usulleri Yönetmeliği m. 7","difficulty":"medium"},
    {"stem":"Meslek mensubunun muhatapları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Toplum ve Devlete karşı sorumludur\n\nII. İşletme yönetimine yanıltıcı bilgi sağlar\n\nIII. Meslektaşlarıyla mesleki dayanışma kurar","correct":"I ve III","why":"Meslek mensubu topluma karşı sorumludur ve meslektaş dayanışması kurar; işletme yönetimine doğru ve güvenilir bilgi sağlar.","ref":"Çalışma Usulleri Yönetmeliği m. 8","difficulty":"easy"},
    {"stem":"Hukuki sorumluluk bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. VUK'taki iştirak niteliğindeki fiil sorumluluk doğurabilir\n\nII. Ceza hükümleri ayrıca uygulanabilir\n\nIII. Mesleki hizmet hiçbir hukuki sonuç doğurmaz","correct":"I ve II","why":"İştirak, teşvik ve yardım fiilleri sorumluluk doğurur; diğer ceza hükümleri saklıdır.","ref":"Çalışma Usulleri Yönetmeliği m. 21","difficulty":"hard"},
    {"stem":"Defter ve belge sorumluluğu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Belgeler özenle muhafaza edilir\n\nII. Fesihte tutanakla iade edilir\n\nIII. İş bitiminde alınmayan belge hiçbir işlem yapılmadan imha edilir","correct":"I ve II","why":"Muhafaza ve tutanaklı iade gerekir; alınmayan belge vergi dairesine teslim edilir.","ref":"Çalışma Usulleri Yönetmeliği m. 20 ve 26-27","difficulty":"medium"},
    {"stem":"Meslek şirketinde sorumluluk bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Cezai sorumluluk işi yapan meslek mensubuna aittir\n\nII. Şirket biçimi sorumluluğu tamamen kaldırır\n\nIII. Her hata stajyere yüklenir","correct":"Yalnız I","why":"Cezai sorumluluk işi yapana aittir; şirket biçimi sorumluluğu kaldırmaz.","ref":"Çalışma Usulleri Yönetmeliği m. 30/f","difficulty":"hard"},
    {"stem":"YMM tasdik sorumluluğu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. YMM tasdikin doğruluğundan sorumludur\n\nII. Sorumluluk tasdik kapsamıyla sınırlıdır\n\nIII. Vergi ve ceza için müşterek ve müteselsil sorumluluk doğabilir","correct":"I, II ve III","why":"Üç ifade de yanlış tasdikin sorumluluk rejimini doğru açıklar.","ref":"3568 sayılı Kanun m. 12; Çalışma Usulleri Yönetmeliği m. 41","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(lesson_id="meslek_hukuku", topic_id="mesleki_sorumluluk",
                label="Mesleki Sorumluluk", slug="mesleki_sorumluluk",
                prefix="topic-mh-ms", seed=170744,
                legislation_version="3568 sayılı Kanun ve Çalışma Usulleri Yönetmeliği, 17.07.2026 yürürlük durumu",
                rules=RULES, premises=PREMISES, wrong_banks={})
