#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Hile, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Muhasebe çalışanı hesaplamada istemeden hata yapmış; yönetici ise hedef kâra ulaşmak için aynı hesabı bilerek değiştirmiştir. İki yanlışlığı ayıran temel unsur nedir?",
        "BDS 240 bakımından hata ile hileyi ayıran temel ölçüt hangisidir?",
        "Eylemde kasıt bulunup bulunmadığı ölçütü",
        "Yanlışlığa yol açan eylemde kasıt bulunması",
        ["Yanlışlığın yalnız parasal tutarı", "İşlemin hangi hesapta kaydedildiği", "Belgenin elektronik veya fiziki olması", "Yanlışlığın dönem sonunda bulunması"],
        ["Yanlışlığın mutlaka önemlilik sınırını aşması", "İşlemin yalnız yönetimce gerçekleştirilmesi", "Denetçinin yanlışlığı dönem sonunda bulması", "Belgenin dış kaynak yerine iç kaynaklı olması"],
        "Hile kasıtlı aldatma içerir; hata ise kasıt bulunmadan oluşan yanlışlıktır.",
        "Hata-hile ayrımı yanlışlığa neden olan eylemin kasıtlı olup olmadığına dayanır.",
        "BDS 240 par. 2", "easy",
    ),
    r(
        "Yönetim geliri döneminden önce kaydederek performansı yüksek göstermiş; başka bir çalışan işletme nakdini kişisel hesabına aktarmıştır. Bunlar hangi iki hile türüdür?",
        "Denetçiyi ilgilendiren iki kasıtlı yanlışlık türü hangileridir?",
        "Hileli raporlama ve varlık suistimali",
        "Hileli raporlama ve varlık suistimali",
        ["Muhasebe tahmini ve denetim örneklemesi", "Kontrol riski ve tespit edememe riski", "İşletme riski ve likidite riski", "Sınıflandırma hatası ve hesaplama hatası"],
        ["Yalnız hata ve mevzuata aykırılık", "İş hayatı riski ve denetim riski", "Kontrol eksikliği ve bütçe sapması", "Tahmin belirsizliği ve değer düşüklüğü"],
        "Gelirin kasıtlı biçimde yanlış sunulması hileli raporlama; nakdin çalınması varlıkların kötüye kullanılmasıdır.",
        "BDS 240, finansal tablo denetiminde iki temel kasıtlı yanlışlık türünü ele alır.",
        "BDS 240 par. 3", "easy",
    ),
    r(
        "Denetçi karmaşık işlemlerde hile göstergeleri bulmuş ve kanıt toplamıştır. Denetçi ceza hukuku bakımından hilenin kesin oluştuğuna hükmedebilir mi?",
        "Denetçinin hileye ilişkin sonucunun hukuki niteliği aşağıdakilerden hangisidir?",
        "Hayır; denetçi hile hakkında yasal hüküm vermez",
        "Denetçi hilenin varlığına yasal olarak hükmetmez",
        ["Evet; denetçi her hile için kesin ceza hükmü kurar", "Evet; denetçi savcı ve mahkemenin bütün yetkilerini kullanır", "Hayır; denetçi hile göstergelerini hiçbir zaman değerlendiremez", "Evet; yalnız tutar önemliliği aşarsa hukuki hüküm verir"],
        ["Denetçi ceza sorumluluğunu kesin olarak belirler", "Denetçi mahkeme adına bağlayıcı karar verir", "Denetçi yalnız yönetimin hukuki görüşünü tekrarlar", "Denetçi bütün hile iddialarını denetim dışında bırakır"],
        "Denetçi hile riskini ve yanlışlık etkisini değerlendirir; suçun hukuken oluştuğuna ilişkin bağlayıcı hüküm vermez.",
        "BDS 240 kapsamındaki tespit ve şüphe, ceza veya hukuk mahkemesi kararının yerine geçmez.",
        "BDS 240 par. 3", "medium",
    ),
    r(
        "Yönetim hilenin önlenmesi ve tespit edilmesine ilişkin bütün sorumluluğun bağımsız denetçiye ait olduğunu ileri sürmüştür. Bu görüş doğru mudur?",
        "Hilenin önlenmesi ve tespit edilmesine ilişkin esas sorumluluk kimdedir?",
        "Hayır; esas sorumluluk yönetim ve gözetim organındadır",
        "Yönetim ve üst yönetimden sorumlu olanlar",
        ["Evet; denetim sözleşmesiyle bütün sorumluluk denetçiye geçer", "Evet; yalnız iç denetim fonksiyonu hileden sorumludur", "Hayır; sorumluluk yalnız çalışanlara ve üçüncü kişilere aittir", "Evet; dış denetçi işletmenin bütün kontrollerini yönetir"],
        ["Yalnız bağımsız denetçi", "Sadece işletmenin dış hukuk müşaviri", "Yalnız vergi idaresi ve düzenleyici kurum", "Denetim şirketinin kalite gözden geçiren kişisi"],
        "Yönetim dürüstlük kültürü ve kontrolleri kurar; üst yönetimden sorumlu olanlar bu süreci gözetir.",
        "Denetçi makul güvence arar, fakat hilenin önlenmesi ve tespit edilmesindeki esas işletme sorumluluğunu devralmaz.",
        "BDS 240 par. 4", "easy",
    ),
    r(
        "Denetçi, bütün hileleri istisnasız bulacağını ve mutlak güvence vereceğini taahhüt etmiştir. BDS 240'a uygun mudur?",
        "Denetçinin hile kaynaklı önemli yanlışlıklara ilişkin güvence düzeyi nedir?",
        "Hayır; denetçi hile için makul güvence sağlar, garanti vermez",
        "Makul güvence",
        ["Evet; bağımsız denetim mutlak güvence ve garanti sağlar", "Evet; örnekleme kullanılsa da bütün hileler kesin bulunur", "Hayır; denetçi hile konusunda hiçbir güvence elde etmez", "Evet; yalnız yönetim yazılı beyan verirse mutlak güvence oluşur"],
        ["Mutlak güvence", "Sınırlı güvence", "Hiçbir güvence", "Yalnız yönetim güvencesi"],
        "Denetimin yapısal kısıtları nedeniyle bazı önemli yanlışlıkların tespit edilememe riski kaçınılmazdır.",
        "BDS'lere uygun denetçi, hata veya hile kaynaklı önemli yanlışlık bulunmadığına dair makul güvence elde eder.",
        "BDS 240 par. 5", "easy",
    ),
    r(
        "Hile, muvazaalı işlemler ve kasıtlı yanlış beyanlarla gizlenmiştir. Bu durumda hile kaynaklı yanlışlığın tespit riski hataya göre nasıldır?",
        "Hile kaynaklı önemli yanlışlığın hataya göre daha zor tespit edilmesinin başlıca nedeni nedir?",
        "Daha yüksektir",
        "Kasıtlı gizleme ve muvazaalı işlem olasılığı",
        ["Daha düşüktür", "Her zaman aynıdır", "Sıfırdır", "Yalnız tutara bağlıdır"],
        ["Hilenin her zaman küçük tutarlı olması", "Hatanın yalnız dış kişilerce yapılması", "Denetçinin hileyi araştırmasının yasak olması", "Hilenin finansal tabloları hiç etkilememesi"],
        "Kasıtlı gizleme ve muvazaa görünürde ikna edici fakat sahte kanıtlar üretebilir.",
        "Hile, denetçiyi yanıltmaya yönelik plan, muvazaa ve kasıtlı eksik kayıtlar içerebildiği için hatadan daha zor saptanabilir.",
        "BDS 240 par. 6", "medium",
    ),
    r(
        "Aynı hile çalışan yerine üst yönetim tarafından kontroller ihlal edilerek yapılmıştır. Denetçinin tespit edememe riski bakımından hangi durum geçerlidir?",
        "Yönetim hilesinin çalışan hilesine göre tespitinin daha güç olmasının temel nedeni nedir?",
        "Yönetim hilesinin tespit riski daha yüksektir",
        "Yönetimin kayıtları ve kontrolleri aşabilmesi",
        ["Çalışan hilesi her zaman daha yüksek risk taşır", "Yönetim hilesi iç kontroller sayesinde imkânsızdır", "İki hile türü arasında hiçbir risk farkı yoktur", "Yönetim hilesi finansal tablo denetimi dışındadır"],
        ["Yönetimin hiçbir muhasebe kaydına erişememesi", "Çalışanların bütün kontrolleri tek başına tasarlaması", "Denetçinin yönetimle iletişim kurmasının yasak olması", "Yönetim hilesinin yalnız önemsiz tutarlarda yapılması"],
        "Yönetim yetkisi, kontrolleri aşma ve kayıtları doğrudan manipüle etme imkânı sağlayabilir.",
        "Yönetimin konumu, normal kontrolleri ihlal ederek görünürde meşru kayıt ve açıklama üretmesine imkân verebilir.",
        "BDS 240 par. 7", "medium",
    ),
    r(
        "Denetçi geçmiş yıllarda yönetimi dürüst bulduğu için cari denetimde hile ihtimalini göz ardı etmiş ve şüpheciliğini azaltmıştır. Uygun mudur?",
        "Hile bağlamında mesleki şüphecilik ne kadar süre korunur?",
        "Hayır; şüphecilik geçmiş deneyimden bağımsız sürdürülür",
        "Denetim boyunca",
        ["Evet; geçmiş dürüstlük cari dönem hile riskini ortadan kaldırır", "Evet; şüphecilik yalnız müşteri kabulünde uygulanır", "Hayır; yönetimin bütün beyanları peşinen sahte sayılır", "Evet; olumlu görüş verilecekse şüphecilik gerekmez"],
        ["Yalnız denetim sözleşmesi imzalanırken", "Sadece rapor yazımından sonraki dönemde", "Yönetim hileyi kabul edene kadar", "İlk analitik prosedür tamamlanıncaya kadar"],
        "Geçmiş dürüstlük deneyimi cari dönemde hile olasılığını ortadan kaldırmaz.",
        "Denetçi hile kaynaklı önemli yanlışlık bulunabileceği bilinciyle denetim boyunca mesleki şüpheciliğini korur.",
        "BDS 240 par. 13", "easy",
    ),
    r(
        "Denetçi bir belgenin tahrif edilmiş olabileceğini gösteren bulgu elde etmiş, fakat belgeyi gerçek kabul ederek araştırmayı durdurmuştur. Uygun mudur?",
        "Bir belgenin gerçek olmayabileceğini gösteren koşullar ortaya çıkarsa denetçi ne yapar?",
        "Hayır; araştırmalar derinleştirilmelidir",
        "Belgenin gerçekliği için araştırmayı genişletir",
        ["Evet; kayıt ve belgeler hiçbir koşulda sorgulanamaz", "Evet; yönetimin açıklaması sahtecilik şüphesini otomatik giderir", "Hayır; belge incelenmeden doğrudan imha edilmelidir", "Evet; yalnız belgenin tutarı önemliliği aşarsa araştırılır"],
        ["Belgeyi incelemeden doğru kabul eder", "Tahrif şüphesini yalnız gelecek yıl değerlendirir", "Belgeyi yönetim adına yeniden düzenler", "Bütün denetim kanıtlarını çalışma dosyasından çıkarır"],
        "Belgenin gerçekliğini sorgulatan bulgular, ilave araştırma ve kanıt gerektirir.",
        "Denetçi normalde belgeleri gerçek kabul edebilir; tahrif veya sahtecilik göstergesinde araştırmayı genişletir.",
        "BDS 240 par. 14", "medium",
    ),
    r(
        "Yönetim ile üst yönetimden sorumlu olanların aynı hile iddiasına verdikleri yanıtlar birbiriyle çelişmektedir. Denetçi çelişkiyi yok sayabilir mi?",
        "Hile sorgulamalarında alınan yanıtlar tutarsızsa denetçinin karşılığı nedir?",
        "Hayır; tutarsızlık araştırılır",
        "Tutarsızlığı araştırmak",
        ["Evet; yönetimin yanıtı otomatik olarak üstün kabul edilir", "Evet; daha kıdemli kişinin açıklaması kanıtsız seçilir", "Hayır; bütün yanıtlar çalışma dosyasından çıkarılır", "Evet; tutarsızlık yalnız finansal tablo yayımlanınca incelenir"],
        ["Yanıtlardan birini rastgele seçmek", "Yalnız denetim ücretini artırmak", "Çelişkiyi rapordan sonra incelemek", "Bütün sorgulamaları kanıt olarak reddetmek"],
        "Çelişkili yanıtlar yönetim dürüstlüğü ve kanıt güvenilirliği hakkında ilave risk işareti olabilir.",
        "Denetçi yönetim veya üst yönetimden sorumlu olanların tutarsız yanıtlarını araştırır.",
        "BDS 240 par. 15", "easy",
    ),
    r(
        "Denetim ekibi hile müzakeresinde yalnız geçmiş yıl bulgularını konuşmuş, finansal tabloların nerede ve nasıl hileye açık olabileceğini ele almamıştır. Uygun mudur?",
        "Hileye ilişkin ekip müzakeresinde hangi konuya özel önem verilir?",
        "Hayır; hileye açık alanlar ve yöntemler müzakere edilir",
        "Tabloların nerede ve nasıl hileye açık olabileceği",
        ["Evet; müzakere yalnız önceki yıl yanlışlıklarını kapsar", "Evet; yönetimin dürüst olduğuna inanılıyorsa toplantı gerekmez", "Hayır; toplantıya yalnız müşteri yönetimi katılmalıdır", "Evet; hile konusu sadece sorumlu denetçice değerlendirilebilir"],
        ["Denetim ücretinin ekip üyeleri arasında nasıl paylaştırılacağı", "Müşterinin gelecek yıl satış ve kârlılık hedefleri", "Ekip üyelerinin izin ve terfi planlarının hazırlanması", "Finansal tabloların hangi yazı tipiyle yayımlanacağı"],
        "Ekip müzakeresi, farklı deneyimlerden yararlanarak olası hile yöntem ve alanlarını belirlemeyi destekler.",
        "Müzakere, yönetimin dürüstlüğüne ilişkin kanaatten bağımsız olarak tabloların hileye açıklığına odaklanır.",
        "BDS 240 par. 16", "medium",
    ),
    r(
        "Denetçi yönetimden yalnız 'hile var mı?' diye sormuş; yönetimin hile riskini değerlendirme ve bu risklere karşılık verme süreçlerini anlamamıştır. Yeterli midir?",
        "Yönetim sorgulamalarında hileyle ilgili hangi süreç hakkında bilgi edinilir?",
        "Hayır; yönetimin hile risk süreci de sorgulanır",
        "Hile riskini belirleme ve karşılama süreci",
        ["Evet; tek bir genel soru bütün risk değerlendirmesini tamamlar", "Evet; hile risk süreci yalnız iç denetimin konusudur", "Hayır; yönetimden hiçbir hile bilgisi istenemez", "Evet; sadece geçmişte gerçekleşmiş hileler sorgulanır"],
        ["Denetim ücretini belirleme ve faturalama süreci", "Bütçe hazırlama ve satış kotası koyma süreci", "Personel izinlerini ve terfileri planlama süreci", "Finansal tabloları kamuya dağıtma süreci"],
        "Yönetimin değerlendirmesi, bildiği hileler ve çalışanlara iletilen etik tutum denetçinin risk değerlendirmesini besler.",
        "Denetçi yönetimin hile risklerini nasıl belirleyip değerlendirdiğini, bunlara nasıl karşılık verdiğini ve bilgileri nasıl ilettiğini anlar.",
        "BDS 240 par. 17-20", "medium",
    ),
    r(
        "İşletmede iç denetim fonksiyonu vardır; ancak dış denetçi iç denetçilerin hile bilgilerini ve uyguladıkları prosedürleri hiç sorgulamamıştır. Yaklaşım uygun mudur?",
        "İç denetim fonksiyonu bulunan işletmede hile sorgulaması kimlere yöneltilir?",
        "Hayır; uygun iç denetim personeli de sorgulanır",
        "İç denetimdeki uygun personel",
        ["Evet; iç denetimin bilgisi dış denetimle ilgili değildir", "Evet; iç denetim yalnız yönetimden bilgi alabilir", "Hayır; iç denetim bütün dış denetim prosedürlerini yürütmelidir", "Evet; yalnız iç denetim raporunun başlığı okunur"],
        ["Yalnız işletmenin müşterileri", "Sadece denetim şirketinin muhasebecisi", "Yalnız vergi idaresi çalışanları", "Sadece finansal tablo kullanıcıları"],
        "İç denetim, kontrol ve risk süreçlerine ilişkin gerçekleşmiş veya şüphelenilen hile bilgisine sahip olabilir.",
        "Denetçi iç denetimin hile bilgisi ve dönem içindeki hile prosedürleri hakkında uygun kişileri sorgular.",
        "BDS 240 par. 19", "easy",
    ),
    r(
        "Üst yönetimden sorumlu olanlar icrâî görev üstlenmemektedir. Denetçi, yönetimin hile yanıtlarını doğrulamak için bu kişileri sorgulamamıştır. Uygun mudur?",
        "İcrâî görev üstlenmeyen üst yönetimden sorumlu olanların hile sorgulamasındaki işlevi nedir?",
        "Hayır; gözetim ve hile bilgileri hakkında sorgulanmalıdırlar",
        "Yönetim yanıtlarını doğrulayıp gözetimi anlamak",
        ["Evet; bu kişiler hile risk değerlendirmesi dışında tutulur", "Evet; yalnız yönetim kurulu başkanı icrâî ise sorgulanır", "Hayır; denetçi gözetim sorumluluğunu tamamen devralır", "Evet; yalnız denetim raporu yayımlandıktan sonra bilgi istenir"],
        ["Yönetimin yanıtlarını sorgusuz kabul etmek", "Denetim prosedürlerini müşteri adına uygulamak", "Finansal tabloları yönetim yerine hazırlamak", "Hile risklerini çalışma dosyasından çıkarmak"],
        "Bağımsız gözetim organının bilgisi, yönetimin verdiği cevapların doğrulanmasına katkı sağlar.",
        "Denetçi gözetim biçimini anlar ve gerçekleşmiş, şüphelenilen ya da iddia edilen hile bilgisi için bu kişileri sorgular.",
        "BDS 240 par. 21-22", "medium",
    ),
    r(
        "Analitik prosedürlerde hasılat ile nakit tahsilat arasında açıklanamayan olağan dışı ilişki bulunmuştur. Denetçi bunu yalnız bütçe sapması sayıp hile açısından değerlendirmemiştir. Uygun mudur?",
        "Analitik prosedürlerde belirlenen olağan dışı ilişkiler hile bakımından nasıl ele alınır?",
        "Hayır; ilişkinin hile riskine işaret edip etmediği incelenir",
        "Hile riskine işaret edip etmediği",
        ["Evet; analitik sapmalar hile riskiyle hiçbir zaman ilişkili değildir", "Evet; yalnız satış bütçesi revize edilerek sorun çözülür", "Hayır; bütün hasılat işlemleri finansal tablodan çıkarılır", "Evet; yönetim açıklaması test edilmeden yeterli kabul edilir"],
        ["Yalnız denetim ücretine etkisi hesaplanır", "Sapma doğrudan hile kanıtı kabul edilir", "Sadece gelecek dönem bütçesi değiştirilir", "İlişki herhangi bir araştırma yapılmadan yok sayılır"],
        "Beklenmeyen ilişki tek başına hileyi kanıtlamaz, fakat hile riskini gösteren bilgi olabilir.",
        "Hasılat dâhil olağan dışı veya beklenmeyen ilişkiler hile kaynaklı önemli yanlışlık riskine işaret edip etmediği yönünden değerlendirilir.",
        "BDS 240 par. 23", "medium",
    ),
    r(
        "Yönetim üzerinde yüksek kâr hedefi baskısı vardır, görevler ayrılığı zayıftır ve yönetici uygunsuz kaydı 'şirketi kurtarmak' diye gerekçelendirmektedir. Bu unsurlar hangi çerçeveyi gösterir?",
        "Hile riski faktörlerinin yaygın üçlü sınıflaması hangisidir?",
        "Baskı, fırsat ve haklı gösterme",
        "Baskı, fırsat ve haklı gösterme",
        ["Likidite, kârlılık ve borçluluk", "Tamlık, doğruluk ve sınıflandırma", "Planlama, kanıt ve raporlama", "Yapısal risk, kontrol riski ve tespit riski"],
        ["Önemlilik, örnekleme ve raporlama", "Sorgulama, gözlem ve dış teyit", "Varlık, kaynak ve özkaynak", "Bütçeleme, finansman ve yatırım"],
        "Baskı hile motivasyonunu, zayıf kontrol fırsatı ve gerekçelendirme kişinin tutumunu gösterir.",
        "Hile riski faktörleri çoğunlukla teşvik veya baskı, fırsat ve tutum ya da haklı gösterme eksenlerinde değerlendirilir.",
        "BDS 240 par. 12, 25 ve Ek 1", "easy",
    ),
    r(
        "Denetçi hasılatta hile riski bulunmadığını hiçbir gerekçe göstermeden varsaymış ve bu alanı risk değerlendirmesinden çıkarmıştır. Uygun mudur?",
        "Hasılatın finansal tablolara alınmasında hile riski için BDS 240'ın başlangıç yaklaşımı nedir?",
        "Hayır; hasılatta hile riski varsayımıyla başlanır",
        "Hile riski varsayılır; aksi sonuç belgelenir",
        ["Evet; hasılat hiçbir işletmede hile riski taşımaz", "Evet; yalnız nakit satışlar hile açısından değerlendirilir", "Hayır; bütün hasılat işlemleri otomatik hile sayılır", "Evet; yönetim beyanı varsayımı kaldırmak için tek başına yeterlidir"],
        ["Hasılat her durumda hileden bağımsız kabul edilir", "Bütün hasılat işlemleri doğrudan yanlış sayılır", "Varsayım yalnız zarar eden işletmelerde uygulanır", "Varsayım yönetimin sözlü talebiyle kaldırılır"],
        "Standart, hasılatın türü ve ilgili beyanlar bakımından hile riski bulunabileceği varsayımıyla başlanmasını ister.",
        "Varsayım somut koşullarda çürütülebilir; ancak hasılatı hile riski saymama gerekçesi çalışma kâğıtlarında açıklanır.",
        "BDS 240 par. 27 ve 48", "hard",
    ),
    r(
        "Denetçi hile kaynaklı önemli yanlışlık riski belirlemiş, fakat bunu olağan risk kabul ederek ilgili kontrollerin tasarım ve uygulamasını anlamamıştır. Uygun mudur?",
        "Hile kaynaklı önemli yanlışlık riskleri hangi risk sınıfında ele alınır?",
        "Hayır; hile riskleri ciddi risk olarak ele alınır",
        "Ciddi risk",
        ["Evet; hile riskleri her zaman önemsiz kabul edilir", "Evet; yalnız kontrol riski sınıfına alınır", "Hayır; hile riski doğrudan tespit edememe riskidir", "Evet; yönetim kabul etmezse risk çalışma dosyasından çıkarılır"],
        ["Önemsiz risk", "Yalnız iş hayatı riski", "Tespit edememe riski", "Denetim sözleşmesi riski"],
        "Hile riski kasıtlı gizleme ve kontrol ihlali olasılığı nedeniyle ciddi risk kabul edilir.",
        "Belirlenen hile kaynaklı önemli yanlışlık riskleri ciddi risk olarak ele alınır; ilgili kontroller belirlenir, tasarım ve uygulama değerlendirilir.",
        "BDS 240 par. 28", "easy",
    ),
    r(
        "Finansal tablo düzeyinde hile riski yüksektir. Denetçi ekip görevlendirmesini değiştirmemiş ve prosedürlere öngörülemezlik unsuru eklememiştir. Uygun mudur?",
        "Finansal tablo düzeyindeki hile riskine genel karşılıklardan biri hangisidir?",
        "Hayır; personel, gözetim ve prosedürlerin öngörülemezliği riskle uyarlanmalıdır",
        "Prosedürlerin niteliği, zamanlaması ve kapsamında öngörülemezlik kullanmak",
        ["Evet; hile riski ekip ve prosedür planını etkilemez", "Evet; yalnız denetim ücreti artırılarak risk karşılanır", "Hayır; bütün denetim görevleri deneyimsiz personele verilir", "Evet; yönetimin seçtiği prosedürler aynen uygulanır"],
        ["Yönetimin bütün prosedürleri önceden seçmesine izin vermek", "Denetim kanıtını ve örnek hacmini azaltmak", "Bütün testleri her yıl aynı kalem ve tarihte yapmak", "Yalnız finansal tablo yazı tipini değiştirmek"],
        "Hile riskine uygun bilgi ve beceriye sahip personel, güçlü yönlendirme-gözetim ve öngörülemez prosedürler gerekir.",
        "Öngörülemezlik yönetimin veya çalışanların denetim yaklaşımını önceden tahmin edip hileyi gizleme olasılığını azaltır.",
        "BDS 240 par. 29-30", "hard",
    ),
    r(
        "Stok miktarının kasıtlı şişirilmesi riski vardır; denetçi yalnız satış sözleşmelerini inceleyen ve stok beyanına karşılık vermeyen prosedürler seçmiştir. Uygun mudur?",
        "Yönetim beyanı düzeyindeki hile riskine karşı prosedürler nasıl tasarlanır?",
        "Hayır; prosedürün niteliği, zamanlaması ve kapsamı belirlenen riske karşılık vermelidir",
        "Hile riskine uygun nitelik, zamanlama ve kapsamla",
        ["Evet; herhangi bir hesapta uygulanan prosedür bütün riskleri karşılar", "Evet; yalnız yönetim beyanı alınarak stok riski kapatılır", "Hayır; bütün stoklar denetçi tarafından satın alınmalıdır", "Evet; prosedürlerin ilgili yönetim beyanıyla bağlantısı gerekmez"],
        ["Her yıl aynı kalemleri ve aynı tarihleri seçerek", "Yönetimin belirlediği testlerle sınırlı kalarak", "Risk değerlendirmesinden bağımsız sabit liste kullanarak", "Yalnız denetim süresini ve ücretini azaltarak"],
        "Prosedür ile risk arasında bağ kurulmazsa yeterli ve uygun kanıt elde edilemez.",
        "Müteakip prosedürler yönetim beyanı düzeyindeki hile riskine niteliği, zamanlaması ve kapsamıyla açıkça karşılık verir.",
        "BDS 240 par. 31", "hard",
    ),
    r(
        "İşletmede güçlü kontroller vardır. Denetçi bu nedenle yönetimin kontrolleri ihlal etme riskini değerlendirme ve zorunlu prosedürleri uygulama dışı bırakmıştır. Doğru mudur?",
        "Yönetimin kontrolleri ihlal etme riski hangi işletmelerde dikkate alınır?",
        "Hayır; bu risk tüm işletmelerde vardır ve ciddi risk kabul edilir",
        "Tüm işletmelerde",
        ["Evet; güçlü kontrol bulunan işletmede yönetim ihlali imkânsızdır", "Evet; risk yalnız halka açık işletmelerde bulunur", "Hayır; yönetim ihlali yalnız çalışan hilesi olarak değerlendirilir", "Evet; denetçi önceki yıl hile bulmadıysa risk kalkar"],
        ["Yalnız halka açık işletmelerde", "Sadece küçük işletmelerde", "Yalnız zarar eden işletmelerde", "Sadece iç denetimi olmayan işletmelerde"],
        "Yönetimin yetkisi, görünürde etkin kontrolleri aşma imkânı yarattığından risk her işletmede mevcuttur.",
        "Risk düzeyi değişebilse de yönetimin kontrolleri ihlal etme riski tüm işletmelerde hile kaynaklı ciddi risk olarak ele alınır.",
        "BDS 240 par. 32", "easy",
    ),
    r(
        "Dönem sonunda yönetici, geliri artırmak için 800.000 TL alacak ve 800.000 TL satış hesabına dayanağı olmayan yevmiye kaydı yaptırmıştır. Denetçi hangi kaydı öncelikle test etmelidir?",
        "Yönetimin kontrolleri ihlal etme riskine karşı yevmiye kayıtları nasıl seçilir?",
        "800.000 TL alacak / 800.000 TL satış kaydı",
        "Dönem sonu ve olağan dışı kayıtları test etmek",
        ["Dönem başındaki rutin kira tahakkuku", "Banka ekstresiyle mutabık tahsilat kaydı", "Onaylı bordroya dayanan ücret kaydı", "Otomatik amortisman dağıtım kaydı"],
        ["Yalnız yönetimin önceden seçtiği rutin kayıtlar", "Sadece küçük tutarlı otomatik kayıtlar", "Hiçbir yevmiye kaydı test edilmeden yönetim beyanı", "Yalnız önceki dönemin kapanış kayıtları"],
        "Dayanaksız dönem sonu satış kaydı, hasılatı kasıtlı artırma ve yönetim ihlali riskine doğrudan işaret eder.",
        "Denetçi finansal raporlama personelini olağan dışı kayıtlar için sorgular, dönem sonu kayıtlarını seçer ve dönem içi test gereğini ele alır.",
        "BDS 240 par. 33(a)", "hard",
    ),
    r(
        "Yönetimin bütün tahminleri tek tek makul görünmekte, fakat sonuçların tamamı sürekli kârı artıran yöndedir. Denetçi taraflılık olasılığını değerlendirmeli midir?",
        "Yönetim tahminlerinde muhtemel taraflılığı değerlendirmek için hangi geriye dönük çalışma yapılır?",
        "Evet; tahminlerin bütünü ve olası yönetim taraflılığı yeniden değerlendirilir",
        "Önceki yıl önemli tahminlerine ait yargı ve varsayımları geriye dönük incelemek",
        ["Hayır; tek tek makul tahminler topluca hiçbir zaman taraflı olamaz", "Evet; ancak yalnız tahminler kârı azaltıyorsa taraflılık vardır", "Hayır; muhasebe tahminleri hile risk değerlendirmesi dışındadır", "Evet; yalnız yönetim taraflılığı yazılı olarak kabul ederse"],
        ["Yalnız cari yıl bütçesini gelecek yıl satışlarıyla karşılaştırmak", "Denetim ücretinin önceki yıla göre değişimini incelemek", "Bütün tahminleri yönetimin seçtiği tek varsayımla yenilemek", "Sadece tahmin notlarının sayfa sayısını karşılaştırmak"],
        "Aynı yönlü tahmin sonuçları, münferit tahminler makul olsa da sistematik yönetim taraflılığı göstergesi olabilir.",
        "Denetçi önceki yıl tahminlerinin sonuçlarını ve kullanılan yargı-varsayımları geriye dönük inceleyerek taraflılık göstergesi arar.",
        "BDS 240 par. 33(b)", "hard",
    ),
    r(
        "İşletme, olağan faaliyetleriyle ilgisiz bir şirkete dönem sonunda ekonomik gerekçesi açıklanamayan büyük ödeme yapmıştır. Denetçi neyi değerlendirmelidir?",
        "Olağan iş akışı dışındaki önemli işlemde iş mantığının bulunmaması neye işaret edebilir?",
        "İşlemin hileyi gizleyip gizlemediğini",
        "Hileli raporlama veya varlıkların kötüye kullanımını gizleme amacına",
        ["Yalnız ödemenin vergi matrahına etkisini", "Sadece işlemin sözleşmede yer alıp almadığını", "Yalnız banka komisyonunun doğru hesaplanmasını", "Sadece yönetimin işlemi bütçeye eklemesini"],
        ["İşlemin her durumda ticari olarak başarılı olduğuna", "Denetim riskinin otomatik olarak sıfırlandığına", "Yönetimin bütün kontrolleri etkin uyguladığına", "İşlemin finansal tabloları hiç etkilemediğine"],
        "Olağan dışı işlemde ekonomik gerekçenin bulunmaması işlemin gerçek amacının gizlendiğini gösterebilir.",
        "İş mantığından yoksun olağan dışı işlem hileli raporlama veya varlık kötüye kullanımını gizleme amacı taşıyabilir.",
        "BDS 240 par. 33(c)", "hard",
    ),
    r(
        "Denetçi küçük tutarlı bir yanlışlığın yönetimce kasıtlı yapıldığına ilişkin kanıt bulmuş ve bunu münferit, önemsiz bir olay sayarak başka etki değerlendirmemiştir. Uygun mudur?",
        "Belirlenen yanlışlık hile göstergesi taşıyorsa denetçi hangi yaklaşımı benimser?",
        "Hayır; hilenin münferit olma ihtimali düşük görülerek etkiler yeniden değerlendirilir",
        "Yönetim beyanları ve denetimin diğer aşamalarına etkisini yeniden değerlendirmek",
        ["Evet; önemlilik altındaki kasıtlı yanlışlık daima yok sayılır", "Evet; yalnız yanlışlık düzeltilirse hile değerlendirmesi sona erer", "Hayır; denetçi hukuki cezayı kendisi belirlemelidir", "Evet; hile göstergesi yalnız raporda açıklanıp prosedürler değiştirilmez"],
        ["Yanlışlığı tutar küçük olduğu için çalışma dosyasından çıkarmak", "Yalnız denetim ücretini artırıp riskleri değiştirmemek", "Yönetimin sözlü açıklamasını kesin kanıt saymak", "Hile göstergesini bir sonraki denetime ertelemek"],
        "Kasıt, yanlışlığın tutarından bağımsız biçimde yönetim dürüstlüğü ve diğer kanıtların güvenilirliğini etkileyebilir.",
        "Hile göstergesi varsa olayın münferit olma olasılığı düşük kabul edilir; riskler, kanıt ve yönetim beyanları yeniden değerlendirilir.",
        "BDS 240 par. 35-38", "hard",
    ),
    r(
        "Denetçi yönetimin dâhil olduğundan şüphelendiği hileyi yalnız ilgili yöneticiye bildirmiş, üst yönetimden sorumlu olanlarla iletişim kurmamış ve yazılı beyan almamıştır. Uygun mudur?",
        "Yönetimin dâhil olduğu hile şüphesinde temel iletişim muhatabı kimdir?",
        "Hayır; üst yönetimden sorumlu olanlara zamanında bildirim ve uygun beyan gerekir",
        "Üst yönetimden sorumlu olanlar",
        ["Evet; şüphe yalnız hileye dâhil yöneticiyle paylaşılır", "Evet; iletişim ancak denetçi raporu yayımlandıktan sonra yapılır", "Hayır; denetçi bütün soruşturmayı tek başına yürütür", "Evet; yönetim yazılı beyanı hile konusunda hiçbir zaman istenmez"],
        ["Yalnız hile şüphesi bulunan yönetici", "Sadece işletmenin müşterileri", "Yalnız denetim ekibinin stajyer üyeleri", "Sadece finansal tablo kullanıcıları"],
        "Yönetim hilesi şüphesinin aynı yönetim kademesinde bırakılması gözetim ve uygun karşılık verilmesini engelleyebilir.",
        "Yönetimin dâhil olduğu hile üst yönetimden sorumlu olanlara zamanında bildirilir; ayrıca BDS 240 kapsamındaki yazılı beyan ve dış raporlama sorumlulukları değerlendirilir.",
        "BDS 240 par. 40-44", "hard",
    ),
]


PREMISES = [
    {"stem":"Hilenin ayırt edici özellikleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hile kasıtlı eylem içerir\n\nII. Hileli finansal raporlama denetçiyi ilgilendiren türlerden biridir\n\nIII. Varlıkların kötüye kullanılması denetçiyi ilgilendiren türlerden biridir","correct":"I, II ve III","why":"Üç ifade de BDS 240'ın hile tanımı ve ele aldığı kasıtlı yanlışlık türleriyle uyumludur.","ref":"BDS 240 par. 2-3 ve 12","difficulty":"easy"},
    {"stem":"Yönetimin kontrolleri ihlal etmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Risk bütün işletmelerde vardır\n\nII. Yevmiye kayıtları ve düzeltmeler test edilir\n\nIII. Tahminlerde yönetim taraflılığı değerlendirilir","correct":"I, II ve III","why":"BDS 240 yönetim ihlali riskini tüm işletmelerde ciddi risk sayar ve belirtilen zorunlu prosedürleri ister.","ref":"BDS 240 par. 32-33","difficulty":"hard"},
    {"stem":"Hile riskine ilişkin sorumluluklar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hileyi önleme sorumluluğu yalnız dış denetçidedir\n\nII. Esas sorumluluk yönetim ve üst yönetimden sorumlu olanlardadır\n\nIII. Denetçi makul güvence elde etmeye çalışır","correct":"II ve III","why":"Esas işletme sorumluluğu yönetim ve gözetim organındadır; denetçi önemli yanlışlıklara ilişkin makul güvence arar.","ref":"BDS 240 par. 4-5","difficulty":"easy"},
    {"stem":"Mesleki şüphecilik bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Geçmiş dürüstlük deneyimi şüpheciliği ortadan kaldırmaz\n\nII. Tahrif şüphesi doğarsa araştırma derinleştirilir\n\nIII. Tutarsız sorgulama yanıtları yok sayılır","correct":"I ve II","why":"Şüphecilik denetim boyunca sürer; belge ve yanıt tutarsızlıkları araştırılır. III yanlıştır.","ref":"BDS 240 par. 13-15","difficulty":"medium"},
    {"stem":"Hasılatta hile riski bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hasılatta hile riski varsayımıyla başlanır\n\nII. Varsayımın geçersiz olduğu sonucuna varılırsa gerekçe belgelenir\n\nIII. Bütün hasılat işlemleri otomatik olarak hiledir","correct":"I ve II","why":"Hasılatta hile riski varsayılır; somut koşullarda çürütülürse gerekçe belgelenir. Varsayım her işlemin hile olduğu anlamına gelmez.","ref":"BDS 240 par. 27 ve 48","difficulty":"hard"},
    {"stem":"Hile riski faktörleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hile riski faktörü hilenin kesin kanıtıdır\n\nII. Teşvik veya baskı bir faktördür\n\nIII. Hile yapma fırsatı bir faktördür","correct":"II ve III","why":"Risk faktörleri kesin hile kanıtı değildir; baskı veya teşvik ile fırsat hile riskine işaret edebilir.","ref":"BDS 240 par. 12 ve 25","difficulty":"medium"},
    {"stem":"Hile göstergesi bulunan yanlışlık bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tutar küçük olsa da yönetim dürüstlüğünü etkileyebilir\n\nII. Hile göstergesi her durumda tutar nedeniyle yok sayılır\n\nIII. Önceki kanıtların güvenilirliği yeniden değerlendirilebilir","correct":"I ve III","why":"Kasıt nitel önem taşır; yönetim beyanları, riskler ve önceki kanıtların güvenilirliği yeniden ele alınabilir.","ref":"BDS 240 par. 36-38","difficulty":"hard"},
    {"stem":"Hile iletişimi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yönetimin dâhil olduğu hile üst yönetimden sorumlu olanlara bildirilir\n\nII. Yetkili kuruma raporlama için mevzuat ve etik hükümler değerlendirilir\n\nIII. Hileye ilişkin yazılı beyan hiçbir zaman alınmaz","correct":"I ve II","why":"İç iletişim ve dış raporlama sorumlulukları değerlendirilir; BDS 240 ayrıca hile konusunda yazılı beyan alınmasını ister.","ref":"BDS 240 par. 40-44","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="hile",
        label="Hile", slug="hile", prefix="topic-hile",
        seed=2026071751,
        legislation_version="KGK TDS 2026 Seti; BDS 240, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
