#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Mükellef Ödevleri, 3×20."""
from topic_pack_builder import write_topic


def r(
    scenario,
    focus,
    correct,
    focus_correct,
    distractors,
    focus_distractors,
    why,
    focus_why,
    ref,
    difficulty="medium",
):
    return {
        "scenario": scenario,
        "focus": focus,
        "correct": correct,
        "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why,
        "focus_why": focus_why,
        "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Vergiye tabi ticari faaliyete başlayan gerçek kişi, işe başlamayı hangi makama bildirmekle yükümlüdür?",
        "Aşağıdakilerden hangisi işe başlamayı bildirmekle yükümlü olanlar arasında yer alır?",
        "İlgili vergi dairesine",
        "Serbest meslek erbabı",
        ["Ticaret mahkemesine", "Sosyal Güvenlik Kurumuna", "Belediye encümenine", "Türkiye İstatistik Kurumuna"],
        ["Yalnız ücret geliri elde eden çalışan", "Vergiden muaf tüketici", "Apartman yöneticisi", "Kamu hizmetinden yararlanan kişi"],
        "Vergiye tabi ticaret ve sanat erbabı işe başlamayı ilgili vergi dairesine bildirir.",
        "VUK, serbest meslek erbabını işe başlamayı bildirmekle yükümlü kişiler arasında açıkça sayar.",
        "213 sayılı VUK m. 153",
        "easy",
    ),
    r(
        "Kurumlar vergisi mükellefi bir anonim şirket tescil başvurusunu yapmış, ticaret sicili müdürlüğü başvuru evrakını vergi dairesine iletmiştir. İşe başlama bildirimi bakımından sonuç nedir?",
        "Tescil için başvuran kurumlar vergisi mükellefinin evrakı ticaret sicili müdürlüğünce vergi dairesine iletildiğinde hangi yükümlülük yerine getirilmiş sayılır?",
        "İşe başlama bildirimi yapılmış sayılır",
        "İşe başlamayı bildirme yükümlülüğü",
        ["Şirketin bütün vergi borçları ödenmiş sayılır", "Defter tasdiki kendiliğinden tamamlanmış sayılır", "İlk beyanname verilmiş kabul edilir", "Vergi incelemesi yapılmış kabul edilir"],
        ["Defter ve belgeleri beş yıl saklama yükümlülüğü", "Fatura düzenleme yükümlülüğü", "Vergi borcunu ödeme yükümlülüğü", "Beyannameyi süresinde verme yükümlülüğü"],
        "Ticaret sicili müdürlüğünün başvuru evrakını vergi dairesine aktarması, bu kurumlar vergisi mükellefi yönünden işe başlama bildirimini karşılar.",
        "Kanundaki aktarım yalnız işe başlama bildiriminin yerine geçer; beyan, ödeme veya belge düzeni ödevlerini ortadan kaldırmaz.",
        "213 sayılı VUK m. 153",
        "medium",
    ),
    r(
        "Bir tacir dükkân kiralamış ve içeride tadilat yaptırmaktadır; henüz ticari faaliyete geçmemiş ve sicile kaydolmamıştır. VUK bakımından yalnız bu durum neyi gösterir?",
        "Tüccar bakımından aşağıdakilerden hangisi işe başlamanın belirtisidir?",
        "İşe başlama sayılmaz",
        "Ticaret siciline kaydolmak",
        ["İşe başlama kesinleşmiştir", "İşi bırakma gerçekleşmiştir", "Özel hesap dönemi başlamıştır", "Mükellefiyet muaflığa dönüşmüştür"],
        ["İş yeri için kira görüşmesi yapmak", "Henüz kullanılmayan dükkânı kiralamak", "Boş dükkânda tadilat yaptırmak", "Ticari faaliyete geçmeden tabela sipariş etmek"],
        "Bir yerin yalnız tutulması veya içinde tertibat ve tesisat yapılması, fiilen ticari ya da sınai faaliyete geçilmedikçe iş yeri açıldığını göstermez.",
        "İş yeri açılmamış olsa bile ticaret siciline veya mesleki teşekküle kaydolmak tüccar için işe başlama belirtisidir.",
        "213 sayılı VUK m. 154",
        "medium",
    ),
    r(
        "Bir mali müşavir henüz müşteri kabul etmemiş ancak serbest çalışmak amacıyla meslek kuruluşuna kaydolmuştur. VUK bakımından bu kayıt nasıl değerlendirilir?",
        "Serbest meslek erbabı bakımından aşağıdakilerden hangisi işe başlamanın göstergelerinden biri değildir?",
        "İşe başlama belirtisidir",
        "Yalnız mesleki yayın satın almak",
        ["İşi bırakma bildirimi sayılır", "Defter tutma muafiyeti sağlar", "Vergi borcunu sona erdirir", "Özel hesap dönemi talebi sayılır"],
        ["Mesleki faaliyet için özel iş yeri açmak", "Çalışılan yere mesleki tabela asmak", "Sürekli mesleki faaliyet ilanı vermek", "Serbest çalışmak için meslek kuruluşuna kaydolmak"],
        "Serbest olarak faaliyette bulunmak üzere mesleki teşekküle kaydolmak, VUK'ta işe başlama göstergesi olarak sayılmıştır.",
        "Mesleki yayın edinmek tek başına fiilî veya kurumsal bir serbest meslek faaliyeti göstergesi değildir.",
        "213 sayılı VUK m. 155",
        "easy",
    ),
    r(
        "Bir işletme, satışa hazır mallarını ticari faaliyetinde kullandığı ayrı bir depoda tutmaktadır. Bu depo VUK'taki iş yeri tanımına girer mi?",
        "VUK'a göre iş yeri tanımının belirleyici ölçütü hangisidir?",
        "Evet; ticari faaliyette kullanılan yer iş yeridir",
        "Faaliyete tahsis edilmesi veya faaliyette kullanılması",
        ["Hayır; yalnız merkez mağaza iş yeri olabilir", "Hayır; depolar iş yeri sayılmaz", "Evet; fakat yalnız depo tapuluysa iş yeridir", "Evet; ancak müşteriye satış yapılıyorsa iş yeridir"],
        ["Yerin mutlaka mükellefe ait olması", "Yalnız müşterilerin girebildiği bir yer olması", "Belediye sınırları içinde bulunması", "Her durumda ayrı bir tüzel kişiliğe sahip olması"],
        "Depo, ticari faaliyetin yürütülmesinde kullanılan yerlerden biri olduğundan iş yeri kapsamındadır.",
        "Mülkiyet veya müşteriye açıklık değil, yerin ticari, sınai, zirai ya da mesleki faaliyete tahsis edilmesi veya kullanılması belirleyicidir.",
        "213 sayılı VUK m. 156",
        "easy",
    ),
    r(
        "Mükellef aynı işletmeye bağlı üç şubeden birini kapatmıştır. VUK bakımından hangi değişikliği bildirmelidir?",
        "Aşağıdaki değişikliklerden hangisi vergi dairesine bildirilmesi gereken iş değişikliklerindendir?",
        "İş yeri sayısındaki azalışı",
        "Yeni bir vergiye tabi olmayı gerektiren değişiklik",
        ["Ortakların kişisel telefon değişikliğini", "Çalışanın yıllık izin tarihini", "Tedarikçinin banka hesabını", "Müşterinin teslimat tercihini"],
        ["Ofis mobilyalarının yerini değiştirmek", "Aynı iş yerinde vardiya çizelgesini yenilemek", "Çalışanların öğle arasını değiştirmek", "Müşterilere uygulanan ticari indirimi yenilemek"],
        "Aynı teşebbüse bağlı iş yerlerinin sayısındaki artış ve azalışlar vergi dairesine bildirilir.",
        "Yeni bir vergiye tabi olmayı, mükellefiyet şeklini değiştirmeyi veya muaflığa geçmeyi gerektiren iş değişiklikleri bildirim konusudur.",
        "213 sayılı VUK m. 157-159",
        "medium",
    ),
    r(
        "Bir tacir faaliyetini iki ay süreyle durdurmuş, sonra aynı faaliyete devam etmiştir. Bu geçici ara VUK bakımından işi bırakma sayılır mı?",
        "VUK'a göre işi bırakmanın gerçekleşmesi için hangi durum gerekir?",
        "Hayır; geçici durdurma işi bırakma değildir",
        "Vergiye tabi işlemlerin tamamen sona ermesi",
        ["Evet; bir günlük ara dahi işi bırakmadır", "Evet; iş yeri kapısı kapanınca iş biter", "Hayır; işi bırakma hiçbir zaman mümkün değildir", "Evet; stok sayımı yapılınca iş sona erer"],
        ["İşlerin mevsim nedeniyle geçici olarak durması", "İş yerinin kısa süreli tadilata alınması", "Çalışanların topluca yıllık izin kullanması", "Satışların bir dönem için yavaşlaması"],
        "İşi bırakma, vergiye tabi işlemlerin tamamen durup sona ermesini gerektirir; geçici durma yeterli değildir.",
        "Faaliyetin geçici biçimde kesilmesi değil, vergiye tabi işlemlerin tamamen sona ermesi işi bırakmayı oluşturur.",
        "213 sayılı VUK m. 160-161",
        "easy",
    ),
    r(
        "Gerçek kişi mükellef ticari faaliyetine 3 Mart'ta başlamıştır. İşe başlama bildirimi için VUK'taki süre nasıl belirlenir?",
        "İşi bırakma ve değişiklik bildirimleri, bildirilecek olayın gerçekleşmesinden itibaren hangi sürede yapılır?",
        "On gün içinde",
        "Bir ay içinde",
        ["Aynı gün içinde", "Yedi gün içinde", "Bir ay içinde", "Üç ay içinde"],
        ["On gün içinde", "Kırk beş gün içinde", "İki ay içinde", "Hesap dönemi sonunda"],
        "Gerçek kişilerin işe başlama bildirimi, işe başlama tarihinden itibaren on gün içinde yapılır.",
        "Şirketlerin işe başlama dışındaki bildirimleri ile işi bırakma ve değişiklik bildirimlerinin genel süresi olaydan itibaren bir aydır.",
        "213 sayılı VUK m. 168",
        "medium",
    ),
    r(
        "Mükellef yazılı değişiklik bildirimini süresi içinde taahhütlü postaya vermiş, evrak vergi dairesine süre geçtikten sonra ulaşmıştır. Bildirim tarihi hangisidir?",
        "Defter tutmak zorunda olmayan, okuma ve yazma bilmeyen mükellefin bildirimi hangi şekilde alınabilir?",
        "Taahhütlü postaya verildiği tarih",
        "Tutanakla tespit edilen sözlü bildirimle",
        ["Vergi dairesine ulaştığı tarih", "Memurun evrakı kaydettiği tarih", "Mükellefin telefon ettiği tarih", "Takip eden hesap döneminin ilk günü"],
        ["Bildirim yükümlülüğü tamamen kalkar", "Yalnız noter aracılığıyla bildirim yapabilir", "Sadece yakın akrabasının sözlü beyanı yeterlidir", "Her durumda elektronik imza kullanmak zorundadır"],
        "Taahhütlü postayla gönderilen yazılı bildirimin postaya verildiği tarih, vergi dairesine verilme tarihi yerine geçer.",
        "Bildirimler kural olarak yazılıdır; defter tutmak zorunda olmayan okuma yazma bilmeyenlerin sözlü bildirimi tutanakla tespit edilebilir.",
        "213 sayılı VUK m. 169-170",
        "medium",
    ),
    r(
        "Bir işletmenin tuttuğu defterler, işletmenin vergiyle ilgili faaliyet sonucunu belirlemeye elverişli değildir. Bu durum VUK'taki defter tutma amaçlarıyla uyumlu mudur?",
        "Aşağıdakilerden hangisi VUK'ta defter tutmanın amaçlarından biridir?",
        "Hayır; faaliyet sonucu belirlenebilmelidir",
        "Vergiyle ilgili işlemleri açıkça göstermek",
        ["Evet; defterlerin vergiyle ilgisi bulunmaz", "Evet; yalnız kasa bakiyesi yeterlidir", "Hayır; defter yalnız üçüncü kişiyi izlemek içindir", "Evet; yalnız ortakların kararları kaydedilir"],
        ["Mükellefin özel hayatını ayrıntılı izlemek", "İşletmenin reklam stratejisini belirlemek", "Personelin izin tercihlerini sıralamak", "Rakip işletmelerin fiyatlarını denetlemek"],
        "Defterler; servet, sermaye ve hesap durumunun yanında vergiyle ilgili faaliyet ve hesap sonuçlarını belirlemeye elverişli tutulmalıdır.",
        "Vergiyle ilgili işlemleri göstermek ve mükellefin vergisel durumunu hesap üzerinden denetleyebilmek defter tutmanın temel amaçlarındandır.",
        "213 sayılı VUK m. 171",
        "easy",
    ),
    r(
        "Gelir vergisinden muaf bir esnaf, yalnız bu muaf faaliyet yönünden VUK'a göre defter tutmak zorunda mıdır?",
        "Aşağıdakilerden hangisi VUK'ta kural olarak defter tutmakla yükümlü olanlar arasında sayılır?",
        "Hayır; defter tutma istisnası uygulanır",
        "Serbest meslek erbabı",
        ["Evet; bütün gerçek kişiler defter tutar", "Evet; yalnız bilanço esasına göre tutar", "Hayır; hiçbir esnaf defter tutmaz", "Evet; yalnız envanter defteri tutar"],
        ["Nihai tüketiciler", "Yalnız ücret geliri elde edenler", "Vergiden muaf esnaf", "Kamu hizmetinden yararlananlar"],
        "Gelir vergisinden muaf esnaf, muaf olduğu faaliyet bakımından VUK'taki defter tutma mecburiyetinin istisnaları arasındadır.",
        "Serbest meslek erbabı VUK m. 172'de defter tutacak kişiler arasında açıkça sayılmıştır.",
        "213 sayılı VUK m. 172-173",
        "easy",
    ),
    r(
        "Yeni işe başlayan işletme takvim yılının son üç ayında faaliyet göstermiştir. Bu üç aylık süre hesap dönemi sayılır mı?",
        "Takvim yılı faaliyet yapısına uygun olmayan bir mükellef için on iki aylık özel hesap dönemini kim belirleyebilir?",
        "Evet; üç aylık süre de hesap dönemidir",
        "Hazine ve Maliye Bakanlığı",
        ["Hayır; en az altı ay faaliyet gerekir", "Hayır; ilk yıl kayıt tutulmaz", "Evet; ancak vergi doğmaz", "Hayır; sonraki yılla birleştirilir"],
        ["Mükellefin kendisi", "Ticaret sicili müdürlüğü", "Belediye başkanlığı", "Vergi mahkemesi"],
        "Yeniden işe başlama veya işi bırakma hâlinde hesap dönemi içindeki bir yıldan kısa faaliyet süresi de hesap dönemi sayılır.",
        "Başvuru üzerine on iki aylık özel hesap dönemini belirleme yetkisi Hazine ve Maliye Bakanlığına aittir.",
        "213 sayılı VUK m. 174",
        "medium",
    ),
    r(
        "Birinci sınıf tüccar, VUK'a göre hangi esasa göre defter tutar?",
        "İkinci sınıf tüccarların tabi olduğu defter tutma esası hangisidir?",
        "Bilanço esası",
        "İşletme hesabı esası",
        ["İşletme hesabı esası", "Serbest meslek esası", "Basit kayıt esası", "Yalnız belge saklama esası"],
        ["Bilanço esası", "Serbest meslek kazanç esası", "Yalnız envanter esası", "Kayıtsız beyan esası"],
        "VUK, tüccarları defter tutma bakımından iki sınıfa ayırır; birinci sınıf bilanço esasına göre defter tutar.",
        "İkinci sınıf tüccarlar işletme hesabı esasına göre defter tutar.",
        "213 sayılı VUK m. 176",
        "easy",
    ),
    r(
        "Bir ticaret şirketi, iş hacmi hadlerine bakılmaksızın VUK bakımından hangi tüccar sınıfında yer alır?",
        "İkinci sınıf bir tüccar kendi isteğiyle bilanço esasına göre defter tutabilir mi?",
        "Birinci sınıf tüccar",
        "Evet; isteğe bağlı olarak seçebilir",
        ["İkinci sınıf tüccar", "Defter tutmayan mükellef", "Basit usulde çiftçi", "Yalnız serbest meslek erbabı"],
        ["Hayır; seçim hakkı bulunmaz", "Evet; yalnız mahkeme kararıyla seçebilir", "Hayır; önce mükellefiyetini sona erdirmelidir", "Evet; fakat defter tutmadan bilanço düzenler"],
        "Adi şirketlerin özel durumu dışında ticaret şirketleri, VUK'ta birinci sınıf tüccarlar arasında sayılır.",
        "İkinci sınıf tüccarlar isterlerse bilanço esasına göre defter tutmayı seçebilirler.",
        "213 sayılı VUK m. 177-181",
        "medium",
    ),
    r(
        "Bilanço esasına göre defter tutan bir tüccarın yalnız işletme hesabı defteri tutması yeterli midir?",
        "Aşağıdakilerden hangisi bilanço esasında tutulması gereken defterlerden biridir?",
        "Hayır; üç bilanço defteri birlikte tutulur",
        "Defterikebir",
        ["Evet; başka defter gerekmez", "Evet; yalnız kasa defteri eklenir", "Hayır; sadece serbest meslek defteri tutulur", "Evet; yalnız perakende satış defteri yeterlidir"],
        ["İşletme hesabı defteri", "Serbest meslek kazanç defteri", "Çiftçi işletme defteri", "Günlük müşteri listesi"],
        "Bilanço esasında yevmiye defteri, defterikebir ve envanter defteri birlikte tutulur.",
        "Defterikebir bilanço esasındaki üç temel defterden biridir; işletme hesabı defteri ikinci sınıf tüccarlara özgüdür.",
        "213 sayılı VUK m. 182-193",
        "easy",
    ),
    r(
        "İşletme yurt içindeki müşteri adına yabancı para üzerinden fatura düzenlemiş, faturada Türk parası karşılığını göstermemiştir. Genel kurala uygun mudur?",
        "VUK'a göre defterlerde başka dilde kayda hangi şartla yer verilebilir?",
        "Hayır; Türk parası karşılığı da gösterilmelidir",
        "Türkçe kayıtların da bulunması şartıyla",
        ["Evet; yabancı para tek başına her zaman yeterlidir", "Evet; yalnız fatura tarihi yazılması yeterlidir", "Hayır; yabancı para hiçbir belgede kullanılamaz", "Evet; müşteri gerçek kişiyse karşılık aranmaz"],
        ["Vergi dairesinden her kayıt için izin alınmasıyla", "Yalnız yabancı ortak bulunmasıyla", "Defterlerin yurt dışında saklanmasıyla", "Türkçe hiçbir kayıt bulunmaması şartıyla"],
        "Yurt içindeki müşteri adına yabancı parayla belge düzenlenebilir; ancak genel kural olarak Türk parası karşılığının da gösterilmesi gerekir.",
        "Defter ve kayıtlar Türkçe tutulur; Türkçe kayıtlar bulunmak kaydıyla başka dilde kayda da yer verilebilir.",
        "213 sayılı VUK m. 215",
        "medium",
    ),
    r(
        "Yevmiye defterindeki yanlış kayıt silinerek okunamaz hâle getirilmiştir. VUK kayıt düzenine uygun mudur?",
        "Yevmiye defteri maddelerindeki yanlışlar hangi yöntemle düzeltilir?",
        "Hayır; kayıt okunamaz hâle getirilemez",
        "Muhasebe kurallarına göre düzeltme kaydıyla",
        ["Evet; bütün yanlışlar tamamen silinir", "Evet; sayfa koparılırsa işlem tamamlanır", "Hayır; hiçbir yanlış düzeltilemez", "Evet; yalnız kurşun kalemle kapatılır"],
        ["Yanlış kaydı kazıyarak yok etmekle", "Defter sayfasını koparmakla", "Rakamın üzerini okunmayacak biçimde boyamakla", "Boş satıra açıklamasız yeni tutar yazmakla"],
        "Deftere geçirilen kayıt kazınamaz, silinemez veya okunamaz hâle getirilemez; hata kanundaki yöntemle düzeltilir.",
        "Yevmiye defterindeki yanlışlar muhasebe kurallarına uygun düzeltme kaydıyla giderilir.",
        "213 sayılı VUK m. 217",
        "easy",
    ),
    r(
        "Ciltli defterde kullanılmayan bir sayfa ciltten koparılmıştır. VUK bakımından bu işlem yapılabilir mi?",
        "Defterde kayıtlar arasında kalan kullanılmamış satırlar nasıl işlem görmelidir?",
        "Hayır; ciltli defterin sayfası koparılamaz",
        "Çizilerek boş bırakılmalıdır",
        ["Evet; boş sayfa her zaman koparılabilir", "Evet; yalnız yıl sonunda koparılabilir", "Hayır; sayfa tamamen karalanmalıdır", "Evet; noter sonradan onaylarsa mümkündür"],
        ["Hiçbir işaret konmadan atlanmalıdır", "Sayfa koparılarak kaldırılmalıdır", "Sonraki kayıt üzerine yazılmalıdır", "Yalnız tarih atılarak kullanılmalıdır"],
        "Ciltli defter sayfaları ciltten koparılamaz; tasdikli hareketli yaprakların da sırası bozulamaz ve yapraklar yırtılamaz.",
        "Kayıt için ayrılmış satırlar atlanamaz; boş kalacak satırlar çizilerek kapatılmalıdır.",
        "213 sayılı VUK m. 218",
        "easy",
    ),
    r(
        "İşletme olağan işlemlerini hiçbir özel belge sistemine dayanmadan on iki gün sonra deftere kaydetmiştir. Genel kayıt süresine uygun mudur?",
        "Yetkili amirlerin imza veya parafını taşıyan muhasebe fişlerine zamanında işlenen işlemler esas defterlere en geç ne zaman aktarılmalıdır?",
        "Hayır; on günlük üst sınır aşılmıştır",
        "Kırk beş gün içinde",
        ["Evet; genel süre otuz gündür", "Evet; hesap dönemi sonuna kadar yazılabilir", "Hayır; bütün kayıtlar aynı dakika yapılmalıdır", "Evet; yalnız fatura varsa süre aranmaz"],
        ["On gün içinde", "Bir ay içinde", "Üç ay içinde", "Hesap dönemi sonunda"],
        "İşlemler, muhasebe düzenini bozmayacak sürede ve genel olarak en çok on günlük gecikmeyle kaydedilmelidir.",
        "Mazbut muhasebe fişi, primanota veya bordroya zamanında işlenen işlemler esas defterlere en geç kırk beş gün içinde aktarılmalıdır.",
        "213 sayılı VUK m. 219",
        "medium",
    ),
    r(
        "Öteden beri işe devam eden ve takvim yılı hesap dönemini kullanan mükellef, gelecek yıl kullanacağı tasdike tabi defteri hangi zamanda tasdik ettirmelidir?",
        "Yıl içinde tasdike tabi defteri dolan mükellef, yeni defteri ne zaman tasdik ettirmelidir?",
        "Kullanım yılından önceki son ayda",
        "Yeni defteri kullanmaya başlamadan önce",
        ["Kullanılacağı yılın üçüncü ayında", "Hesap dönemi sona erdikten sonra", "İlk vergi incelemesi başladığında", "Defter tamamen dolduktan bir ay sonra"],
        ["Kullanmaya başladıktan on gün sonra", "Hesap dönemi kapandıktan sonra", "İlk beyanname verilirken", "Takip eden takvim yılının sonunda"],
        "Öteden beri faaliyette olanlar tasdike tabi defterlerini kullanılacağı yıldan önce gelen son ayda tasdik ettirir.",
        "Yıl içinde yeni tasdike tabi defter kullanma zorunluluğu doğarsa tasdik, kullanımdan önce yapılır.",
        "213 sayılı VUK m. 220-221",
        "medium",
    ),
    r(
        "İşletme, üçüncü kişiyle yaptığı mal alımına ilişkin kaydı hiçbir belgeye dayandırmamıştır. Kanunda özel istisna yoksa bu kayıt düzeni uygun mudur?",
        "VUK'a göre zorunlu bilgileri taşımayan bir belge vergi kanunları bakımından nasıl kabul edilir?",
        "Hayır; işlem belgelendirilmelidir",
        "Hiç düzenlenmemiş sayılır",
        ["Evet; sözlü açıklama her zaman yeterlidir", "Evet; yalnız tutarın küçük olması yeterlidir", "Hayır; bütün kayıtlar noter senedine dayanmalıdır", "Evet; dönem sonunda toplu kayıt yapılabilir"],
        ["Eksiksiz fatura sayılır", "Yalnız geç düzenlenmiş kabul edilir", "Kendiliğinden gider pusulasına dönüşür", "Vergi incelemesinde kesin delil sayılır"],
        "Kanunda aksine hüküm olmadıkça üçüncü kişilerle ilişki ve işlemlere ait kayıtların ispat edici belgeye dayanması gerekir.",
        "Kanunen zorunlu bilgileri taşımayan belge, elektronik belge dâhil, vergi kanunları bakımından hiç düzenlenmemiş sayılır.",
        "213 sayılı VUK m. 227",
        "medium",
    ),
    r(
        "Satıcı, yaptığı hizmet karşılığında müşterinin borçlandığı tutarı gösteren ticari belge düzenlemiştir. Bu belge hangisidir?",
        "Aşağıdakilerden hangisi faturada bulunması gereken bilgilerden biridir?",
        "Fatura",
        "Malın veya işin türü, miktarı, fiyatı ve tutarı",
        ["Gider pusulası", "Müstahsil makbuzu", "Serbest meslek makbuzu", "Yoklama fişi"],
        ["Müşterinin medeni hâli", "Çalışanların yıllık izin tarihleri", "Ortakların kişisel harcamaları", "Satıcının meslek odasındaki oy tercihi"],
        "Fatura, satılan mal veya yapılan iş karşılığında müşterinin borçlandığı meblağı göstermek üzere satıcı veya işi yapan tüccarca verilen belgedir.",
        "Malın veya işin türü, miktarı, fiyatı ve tutarı faturanın zorunlu içerikleri arasındadır.",
        "213 sayılı VUK m. 229-230",
        "easy",
    ),
    r(
        "Hizmet 1 Nisan'da tamamlanmış, fatura 10 Nisan'da düzenlenmiştir. Bakanlıkça daha kısa bir süre belirlenmediği varsayımında sonuç nedir?",
        "Genel kurala göre fatura, malın tesliminden veya hizmetin yapılmasından itibaren azami hangi sürede düzenlenir?",
        "Geç düzenlendiği için hiç düzenlenmemiş sayılır",
        "Yedi gün içinde",
        ["Fatura süresinde düzenlenmiştir", "Fatura yalnız bir gün gecikmiş sayılır fakat geçerlidir", "Fatura kendiliğinden irsaliye sayılır", "Fatura hesap dönemi sonunda düzenlenmiş sayılır"],
        ["Aynı gün içinde", "On gün içinde", "Bir ay içinde", "Kırk beş gün içinde"],
        "Teslim veya hizmet tarihinden itibaren genel yedi günlük süre aşılmıştır; bu sürede düzenlenmeyen fatura hiç düzenlenmemiş sayılır.",
        "Genel azami süre yedi gündür; Hazine ve Maliye Bakanlığı belirli işlemler için bu süreyi kısaltabilir veya anlık düzenleme zorunluluğu getirebilir.",
        "213 sayılı VUK m. 231/5",
        "medium",
    ),
    r(
        "Birinci sınıf tüccar, belge düzenleme yükümlülüğü bulunmayan kişiden işletmesi için kullanılmış masa satın almıştır. Satın alma hangi belgeyle tevsik edilir?",
        "Fatura düzenlenmesi gerekmeyen bir perakende satışın bedeli aşağıdakilerden hangisiyle belgelendirilebilir?",
        "Gider pusulasıyla",
        "Perakende satış fişiyle",
        ["Serbest meslek makbuzuyla", "Müstahsil makbuzuyla", "Yolcu listesiyle", "Tahakkuk fişiyle"],
        ["Yoklama fişiyle", "Vergi inceleme tutanağıyla", "Tahakkuk fişiyle", "Uzlaşma tutanağıyla"],
        "Belge düzenleme zorunluluğu bulunmayan kişiden alınan mal için alıcı tüccar gider pusulası düzenler ve satana imzalatır.",
        "Fatura verme zorunluluğu olmayan perakende satışlar perakende satış fişi, kasa kaydı veya giriş ve yolcu taşıma biletiyle tevsik edilebilir.",
        "213 sayılı VUK m. 233-234",
        "medium",
    ),
    r(
        "Tüccar, gerçek usulde vergilendirilmeyen çiftçiden ürün satın almış ve bedeli ödemiştir. Hangi belge düzenlenmelidir?",
        "Serbest meslek erbabı mesleki faaliyetine ilişkin tahsilat yaptığında hangi belgeyi düzenleyip müşterisine verir?",
        "Müstahsil makbuzu",
        "Serbest meslek makbuzu",
        ["Gider pusulası", "Perakende satış fişi", "Ücret bordrosu", "Yoklama fişi"],
        ["Müstahsil makbuzu", "Gider pusulası", "Perakende satış fişi", "Tahakkuk fişi"],
        "Gerçek usulde vergiye tabi olmayan çiftçiden mal alımında alıcı, bedelin ödenmesi sırasında iki nüsha müstahsil makbuzu düzenler.",
        "Serbest meslek erbabı mesleki faaliyetiyle ilgili her tahsilat için iki nüsha serbest meslek makbuzu düzenler ve birini müşteriye verir.",
        "213 sayılı VUK m. 235-237",
        "easy",
    ),
    r(
        "2022 yılına ilişkin defter ve belgeler için beş yıllık muhafaza süresi hangi tarihten itibaren işlemeye başlar?",
        "Elektronik kayıtlara erişmek için kullanılan şifreler, yetkili makamın talebi üzerine ibraz yükümlülüğü kapsamında mıdır?",
        "2023 takvim yılının başından itibaren",
        "Evet; erişim bilgi ve şifreleri de ibraz edilir",
        ["2022 yılının başından itibaren", "2022 hesap döneminin ortasından itibaren", "2024 takvim yılının başından itibaren", "Vergi incelemesinin başladığı tarihten itibaren"],
        ["Hayır; yalnız basılı defterler ibraz edilir", "Hayır; elektronik kayıtlar muhafaza edilmez", "Evet; fakat yalnız mükellefin isteğiyle açıklanır", "Hayır; sadece cihazın kendisi gösterilir"],
        "Defter ve belgeler, ilgili oldukları yılı izleyen takvim yılının başından itibaren beş yıl saklanır.",
        "İbraz ödevi elektronik ortamdaki kayıtlarla birlikte bu kayıtlara erişmek veya onları okunabilir hâle getirmek için gereken bilgi ve şifreleri de kapsar.",
        "213 sayılı VUK m. 253-256",
        "medium",
    ),
]


PREMISES = [
    {
        "stem": "İşe başlama ve iş yeri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ticaret siciline kaydolmak tüccar için işe başlama göstergesi olabilir\n\nII. Yalnız dükkân kiralayıp tadilat yaptırmak her durumda işe başlama sayılır\n\nIII. Ticari faaliyette kullanılan depo iş yeri sayılabilir",
        "correct": "I ve III",
        "why": "Sicile kayıt işe başlama göstergesidir ve faaliyette kullanılan depo iş yeri olabilir; yalnız kiralama veya tadilat fiilî açılışı göstermez.",
        "ref": "213 sayılı VUK m. 154 ve 156",
        "difficulty": "medium",
    },
    {
        "stem": "Bildirimler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gerçek kişinin işe başlama bildirimi on gün içinde yapılır\n\nII. İşi bırakma ve değişiklik bildirimlerinin genel süresi bir aydır\n\nIII. Taahhütlü postada postaya veriliş tarihi bildirim tarihi sayılır",
        "correct": "I, II ve III",
        "why": "Üç ifade de VUK'un bildirim süresi ve taahhütlü postaya ilişkin hükümleriyle uyumludur.",
        "ref": "213 sayılı VUK m. 168 ve 170",
        "difficulty": "medium",
    },
    {
        "stem": "Defter tutma esasları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Birinci sınıf tüccarlar bilanço esasına tabidir\n\nII. İkinci sınıf tüccarlar işletme hesabı esasına tabidir\n\nIII. İkinci sınıf tüccar isterse bilanço esasını seçebilir",
        "correct": "I, II ve III",
        "why": "VUK'taki iki sınıf ayrımı ve ikinci sınıf tüccara tanınan ihtiyari bilanço esası seçimi bu üç sonucu doğurur.",
        "ref": "213 sayılı VUK m. 176 ve 181",
        "difficulty": "medium",
    },
    {
        "stem": "Kayıt düzeni bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yevmiye defterindeki yanlış kayıt kazınarak yok edilebilir\n\nII. Boş bırakılan kayıt satırları çizilmelidir\n\nIII. Ciltli defter sayfaları ciltten koparılamaz",
        "correct": "II ve III",
        "why": "Kayıt okunamaz hâle getirilemez; boş satırlar çizilir ve ciltli defter sayfaları koparılamaz.",
        "ref": "213 sayılı VUK m. 217-218",
        "difficulty": "medium",
    },
    {
        "stem": "Kayıt zamanı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Olağan kayıtlar genel olarak on günden fazla geciktirilemez\n\nII. Mazbut muhasebe fişlerine dayanan kayıtlar esas deftere en geç kırk beş günde aktarılır\n\nIII. Serbest meslek kazanç defterine işlemler hesap dönemi sonunda topluca yazılır",
        "correct": "I ve II",
        "why": "Genel üst sınır on gün, usulüne uygun muhasebe fişi sisteminde esas deftere aktarım üst sınırı kırk beş gündür; serbest meslek kazanç defteri günü gününe tutulur.",
        "ref": "213 sayılı VUK m. 219",
        "difficulty": "hard",
    },
    {
        "stem": "Fatura düzeni bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Fatura müşterinin borçlandığı tutarı gösteren ticari belgedir\n\nII. Genel düzenleme süresi teslim veya hizmetten itibaren yedi gündür\n\nIII. Zorunlu bilgileri taşımayan fatura yalnız geç düzenlenmiş sayılır",
        "correct": "I ve II",
        "why": "Faturanın tanımı ve genel yedi günlük süre doğrudur. Zorunlu bilgileri taşımayan belge yalnız gecikmiş kabul edilmez; vergi kanunları bakımından hiç düzenlenmemiş sayılır.",
        "ref": "213 sayılı VUK m. 227 ve 229-231",
        "difficulty": "hard",
    },
    {
        "stem": "Belge türleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Belge düzenleme zorunluluğu olmayan kişiden mal alan tüccar gider pusulası düzenleyebilir\n\nII. Gerçek usulde vergilendirilmeyen çiftçiden ürün alımında serbest meslek makbuzu kullanılır\n\nIII. Serbest meslek tahsilatı için serbest meslek makbuzu düzenlenir",
        "correct": "I ve III",
        "why": "Gider pusulası ve serbest meslek makbuzuna ilişkin ifadeler doğrudur. Gerçek usulde vergilendirilmeyen çiftçiden ürün alımında serbest meslek makbuzu değil, müstahsil makbuzu kullanılır.",
        "ref": "213 sayılı VUK m. 234-237",
        "difficulty": "hard",
    },
    {
        "stem": "Muhafaza ve ibraz bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Beş yıllık muhafaza süresi ilgili yılı izleyen takvim yılından başlar\n\nII. Elektronik kayıtlar ibraz kapsamı dışındadır\n\nIII. Kayıtları okunabilir kılmak için gerekli şifreler de ibraz edilir",
        "correct": "I ve III",
        "why": "Muhafaza süresi izleyen takvim yılı başlar; elektronik kayıtlar ile erişim için gereken bilgi ve şifreler ibraz kapsamındadır.",
        "ref": "213 sayılı VUK m. 253-256",
        "difficulty": "medium",
    },
]


if __name__ == "__main__":
    write_topic(
        lesson_id="vergi_usul_kanunu",
        topic_id="mukellef_odevleri",
        label="Mükellef Ödevleri",
        slug="mukellef_odevleri",
        prefix="topic-vuk-mo",
        seed=20260718,
        legislation_version="213 sayılı Vergi Usul Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
