#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Denetim Kanıtı, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Denetçi yalnız işletmenin muhasebe defterlerini kanıt saymış, diğer kaynaklardan edindiği bilgileri denetim kanıtı dışında bırakmıştır. Yaklaşım doğru mudur?",
        "BDS 500'e göre denetim kanıtı aşağıdakilerden hangisidir?",
        "Hayır; muhasebe dışı kaynaklardan alınan bilgiler de kanıttır",
        "Denetçi görüşünün dayandığı sonuçlara ulaşmakta kullanılan bilgiler",
        ["Evet; yalnız defteri kebir ve yevmiye kayıtları kanıt sayılır", "Evet; üçüncü kişilerden alınan bilgiler denetimde kullanılamaz", "Hayır; muhasebe kayıtları hiçbir zaman denetim kanıtı değildir", "Evet; yalnız yönetimin yazılı beyanları kanıt niteliğindedir"],
        ["Yönetimin gelecek dönem için hazırladığı ticari bütçe ve hedefler", "Denetim şirketinin ücret ve personel planlamasında kullandığı veriler", "İşletmenin yalnız vergi matrahını hesaplamak için ürettiği kayıtlar", "Finansal tabloları hazırlayan yönetimin kişisel kanaatleri"],
        "Denetim kanıtı, muhasebe kayıtlarındaki bilgilerle sınırlı değildir; diğer iç ve dış kaynakları da kapsar.",
        "Kanıt, denetçinin görüşüne dayanak olan sonuçlara ulaşırken kullandığı bilgilerin bütünüdür.",
        "BDS 500 par. 1 ve 5", "easy",
    ),
    r(
        "Denetçi çok sayıda belge toplamış ancak belgeler ilgili yönetim beyanıyla ilişkili değildir ve kaynakları güvenilir değildir. Yalnız belge sayısı yeterli midir?",
        "Denetim kanıtında yeterlilik ve uygunluk sırasıyla neyi ifade eder?",
        "Hayır; kanıt miktarı kalite eksikliğini tek başına gidermez",
        "Kanıtın miktarı ile ihtiyaca uygunluk ve güvenilirliği",
        ["Evet; belge sayısı arttıkça kanıtın kalitesi otomatik yükselir", "Evet; ilgisiz belgeler örnek hacmi büyükse uygun kanıt olur", "Hayır; yalnız işletme dışındaki bütün belgeler reddedilmelidir", "Evet; güvenilirlik yalnız denetim raporu yazılırken değerlendirilir"],
        ["Denetim maliyeti ile işletmenin finansal performansını", "Yanlışlığın tutarı ile yönetimin düzeltme niyetini", "Çalışma süresi ile denetim ekibinin kıdem dağılımını", "Örnekleme aralığı ile rapor tarihinin yakınlığını"],
        "Çok sayıdaki düşük kaliteli kanıt, uygun kanıt eksikliğini zorunlu olarak telafi etmez.",
        "Yeterlilik miktar; uygunluk ise kanıtın sonuçları destekleme açısından ilgisi ve güvenilirliğidir.",
        "BDS 500 par. 5-6", "easy",
    ),
    r(
        "Önemli yanlışlık riski yükselmiş, fakat denetçi daha az ve daha düşük kaliteli kanıt toplamayı planlamıştır. Bu plan uygun mudur?",
        "İhtiyaç duyulan denetim kanıtı miktarını başlıca hangi iki unsur etkiler?",
        "Hayır; yüksek risk daha çok ve daha ikna edici kanıt gerektirir",
        "Risk değerlendirmesi ile mevcut kanıtın kalite düzeyi",
        ["Evet; risk yükseldikçe prosedür sayısı azaltılır", "Evet; düşük kaliteli kanıt büyük örnekle her durumda yeterlidir", "Hayır; yalnız denetim ücreti artırılarak risk karşılanır", "Evet; yönetim yazılı beyan verirse diğer kanıtlar kaldırılır"],
        ["Denetim ücretinin tutarı ve sözleşmenin imza tarihi", "İşletmenin çalışan sayısı ve ortakların oy oranı", "Finansal tabloların sayfa sayısı ve dipnot uzunluğu", "Denetim ekibinin izin planı ve raporun biçimi"],
        "Yüksek risk daha ikna edici kanıt gerektirir; kalite arttıkça ihtiyaç duyulan miktar bazı koşullarda azalabilir.",
        "Kanıt miktarı, önemli yanlışlık riski değerlendirmesinden ve mevcut kanıtın kalitesinden etkilenir.",
        "BDS 500 par. 5-6; BDS 330 par. 7", "medium",
    ),
    r(
        "Alacak bakiyesinin varlığına ilişkin kanıt olarak yalnız stok sayım tutanağı kullanılmıştır. Tutanak güvenilir olsa bile bu beyan için uygun mudur?",
        "Denetim kanıtının ihtiyaca uygunluğu esas olarak hangi ilişkiyi ifade eder?",
        "Hayır; kanıt ilgili amacı ve yönetim beyanını desteklemelidir",
        "Kanıtın test edilen amaç ve beyanla bağlantısını",
        ["Evet; güvenilir her belge bütün yönetim beyanlarını destekler", "Evet; işletme içinde üretilen her tutanak alacağı doğrular", "Hayır; yalnız banka dekontları stok mevcudiyetini kanıtlar", "Evet; kanıtın hangi hesapla ilgili olduğu önem taşımaz"],
        ["Kanıtın hazırlanma maliyeti ile denetim ücretinin oranını", "Belgenin sayfa sayısı ile arşivde tutulma süresini", "İşletmenin bütçe hedefi ile gerçekleşen satış farkını", "Denetim ekibinin kıdemi ile çalışma saatlerini"],
        "Güvenilir bir bilgi dahi yanlış beyanı test ediyorsa denetim amacı açısından ilgili değildir.",
        "İhtiyaca uygunluk, kanıtın test edilen amaç ve yönetim beyanını destekleme ya da çürütme bağlantısıdır.",
        "BDS 500 par. 5 ve A27-A30", "medium",
    ),
    r(
        "Müşteriden bağımsız bankanın doğrudan denetçiye gönderdiği yazılı teyit ile yönetimin sözlü açıklaması çelişmektedir. Genel olarak hangisi daha güvenilirdir?",
        "Denetim kanıtının güvenilirliğiyle ilgili genel kural aşağıdakilerden hangisidir?",
        "Bankanın denetçiye doğrudan ilettiği yazılı teyit",
        "Bağımsız dış kaynak kanıtı genellikle daha güvenilirdir",
        ["Yönetimin denetçiye verdiği sözlü açıklama", "İşletmenin teyitten sonra hazırladığı iç not", "Kaynağı bilinmeyen elektronik tablo çıktısı", "Müşteri temsilcisinin imzasız e-posta özeti"],
        ["İşletme içinden alınan sözlü bilgi her zaman dış belgeden üstündür", "Kanıtın kaynağı ve elde edilme koşulları güvenilirliği etkilemez", "Elektronik kanıt hiçbir koşulda güvenilir kabul edilemez", "Yönetimin hazırladığı bütün belgeler dış teyit sayılır"],
        "Bağımsız kaynaktan doğrudan gelen yazılı teyit, koşullar uygun olduğunda iç sözlü açıklamadan daha güvenilirdir.",
        "Güvenilirlik kaynağa, niteliğe ve elde edilme koşullarına bağlıdır; dış bağımsız kaynak çoğu durumda güvenceyi artırır.",
        "BDS 500 par. A31; BDS 505 par. 2", "easy",
    ),
    r(
        "Denetçi depo sayımını bizzat gözlemlemiş; başka bir çalışan ise aynı olayı sonradan sözlü olarak aktarmıştır. Diğer koşullar eşitse hangi kanıt daha güvenilirdir?",
        "Doğrudan denetçi tarafından elde edilen kanıtın güvenilirliği için hangi genelleme yapılabilir?",
        "Denetçinin doğrudan gözlemi",
        "Doğrudan kanıt, dolaylı kanıttan genellikle daha güvenilirdir",
        ["Çalışanın olaydan sonra verdiği sözlü özet", "Yönetimin olaya ilişkin hazırladığı imzasız not", "Depo sorumlusunun tahmine dayalı açıklaması", "Kaynağı belirlenmeyen sayım çizelgesi"],
        ["Dolaylı bilgi her zaman doğrudan gözlemden daha güvenilirdir", "Denetçinin doğrudan elde ettiği kanıt ayrıca değerlendirilmez", "Sözlü açıklama her durumda yazılı kanıttan daha üstündür", "Kanıtın elde edilme biçimi güvenilirliği hiçbir zaman etkilemez"],
        "Doğrudan gözlem, olayın başkasınca aktarılmasına kıyasla bilgi zincirindeki bozulma riskini azaltır.",
        "Genel olarak denetçinin doğrudan elde ettiği kanıt, dolaylı veya çıkarım yoluyla elde edilenden daha güvenilirdir.",
        "BDS 500 par. A31", "easy",
    ),
    r(
        "Aynı konuda yetkili bir kaynaktan alınan imzalı sözleşme ile yalnız hatırlamaya dayanan sözlü açıklama bulunmaktadır. Diğer koşullar eşitse hangisi daha güvenilirdir?",
        "Kanıtın biçimi bakımından güvenilirliği artıran genel özellik hangisidir?",
        "İmzalı sözleşme",
        "Fiziki ya da elektronik belge olması",
        ["Hatırlamaya dayanan sözlü açıklama", "Kaynağı belirtilmeyen toplantı notu", "İşletme çalışanının tahmini", "Sonradan oluşturulan imzasız özet"],
        ["Yalnız sözlü olarak aktarılması", "Hiçbir kayıt izi bırakmaması", "Kaynağının belirlenememesi", "Denetim tamamlandıktan sonra hazırlanması"],
        "Belge niteliğindeki kanıt, salt sözlü açıklamaya göre genellikle daha güvenilir bir kayıt izi sağlar.",
        "Kanıtın fiziki, elektronik veya başka ortamda belge biçiminde olması güvenilirliği çoğu durumda artırır.",
        "BDS 500 par. A31", "easy",
    ),
    r(
        "Denetçi, işletmenin hazırladığı satış raporunu testte kullanmış; raporun tamlığını, doğruluğunu ve ayrıntı düzeyini değerlendirmemiştir. Uygun mudur?",
        "İşletme tarafından oluşturulan bilgi denetim kanıtı olarak kullanılacaksa denetçi neyi değerlendirir?",
        "Hayır; bilginin doğruluk, tamlık ve ayrıntısı değerlendirilir",
        "Doğruluk, tamlık, açıklık ve yeterli ayrıntı",
        ["Evet; işletmenin ürettiği her rapor otomatik güvenilirdir", "Evet; yalnız raporun toplam tutarı önemlidir", "Hayır; işletme içi bilgi hiçbir denetimde kullanılamaz", "Evet; yönetimin imzası bütün veri testlerinin yerini alır"],
        ["Yalnız raporun yazı tipi ve sayfa düzeni", "Sadece hazırlayan çalışanın kıdem ve ücret bilgisi", "Raporun denetim ücretini azaltıp azaltmadığı", "Yönetimin raporu kamuya açıklama niyeti"],
        "Eksik veya hatalı kaynak veri, onun üzerine kurulan denetim prosedürünün sonucunu geçersiz kılabilir.",
        "Denetçi işletme üretimi bilginin doğruluk ve tamlığına kanıt elde eder; ayrıca amaç için açık ve ayrıntılı olup olmadığını değerlendirir.",
        "BDS 500 par. 9", "medium",
    ),
    r(
        "Yönetim, karmaşık değerleme için kullandığı uzmanın çalışmasını sunmuştur. Denetçi uzmanı ve çalışmasını değerlendirmeden sonucu kanıt kabul edebilir mi?",
        "Yönetimin faydalandığı uzmanın çalışması kullanılırken hangi üç alan ele alınır?",
        "Hayır; uzman ve çalışmasının uygunluğu değerlendirilir",
        "Uzmanın yetkinliği, tarafsızlığı ve çalışmanın uygunluğu",
        ["Evet; uzman unvanı bütün değerlendirmelerin yerini alır", "Evet; yönetim ücret ödediyse çalışma otomatik güvenilirdir", "Hayır; uzman çalışması hiçbir zaman denetim kanıtı olamaz", "Evet; yalnız değerleme sonucu yönetim beklentisine uyuyorsa yeterlidir"],
        ["Uzmanın reklam bütçesi, müşteri sayısı ve ofis büyüklüğü", "Çalışmanın sayfa sayısı, yazı tipi ve teslim zamanı", "Yönetimin uzman ücretini hangi hesapta izlediği", "Denetim ekibinin uzmanla aynı şehirde bulunması"],
        "Uzmanın unvanı tek başına çalışmanın tarafsız ve ilgili yönetim beyanı için uygun olduğunu göstermez.",
        "Denetçi uzmanın yetkinlik, kabiliyet ve tarafsızlığını; çalışmayı ve kanıt olarak uygunluğunu gerekli ölçüde değerlendirir.",
        "BDS 500 par. 8", "hard",
    ),
    r(
        "Denetçi bir hesap için yalnız kolay ulaşılabilen kalemleri seçmiş, seçimin prosedür amacına ulaşmada etkin olup olmadığını değerlendirmemiştir. Uygun mudur?",
        "Kontrol ve detay testlerinde kalem seçiminin temel ölçütü nedir?",
        "Hayır; kalem seçimi prosedür amacına uygun olmalıdır",
        "İlgili prosedürün amacına ulaşmada etkili olması",
        ["Evet; en kolay kalemleri seçmek her durumda yeterlidir", "Evet; yalnız en küçük tutarlı kalemler test edilmelidir", "Hayır; bütün denetimlerde her kalem zorunlu incelenir", "Evet; yönetimin seçtiği örnek denetçi için bağlayıcıdır"],
        ["Denetim ücretini mümkün olan en düşük düzeye indirmesi", "Yönetimin test sonucunu önceden kabul etmiş olması", "Örneklerin yalnız dönem başındaki işlemlerden oluşması", "Kalemlerin denetim ekibince hızlı bulunabilmesi"],
        "Kolaylık, seçimin ilgili riske ve yönetim beyanına uygun denetim kanıtı sağlamasını garanti etmez.",
        "Denetçi bütün kalemleri inceleme, belirli kalemleri seçme veya örnekleme yöntemlerinden amaca etkili olanı seçer.",
        "BDS 500 par. 10 ve A53-A57", "medium",
    ),
    r(
        "Banka teyidi ile muhasebe kayıtları arasında önemli tutarsızlık vardır; denetçi iki kanıttan istediğini seçip diğerini yok saymıştır. Uygun mudur?",
        "Kanıtlar arasında tutarsızlık veya güvenilirlik şüphesi varsa denetçi ne yapar?",
        "Hayır; tutarsızlığı çözmek için ek prosedür uygulanır",
        "Sorunu çözen ek prosedürler ve diğer etkilerin değerlendirilmesi",
        ["Evet; yönetimin tercih ettiği kanıt doğrudan kabul edilir", "Evet; daha düşük tutarı gösteren kanıt her zaman doğrudur", "Hayır; iki kanıt da incelemeden dosyadan çıkarılmalıdır", "Evet; tutarsızlık yalnız rapor yayımlandıktan sonra araştırılır"],
        ["Kanıtlardan birini gerekçe göstermeden çalışma dosyasından çıkarır", "Yalnız denetim ücretini artırıp mevcut kanıtla görüş verir", "Tutarsızlığı yönetimin sözlü beyanıyla otomatik çözer", "Bütün finansal tabloları test etmeden doğru kabul eder"],
        "Tutarsızlık, risk değerlendirmesini ve diğer kanıtların güvenilirliğini etkileyebileceği için araştırılmalıdır.",
        "Denetçi sorunu çözmek üzere prosedürleri değiştirir veya genişletir ve sorunun denetimin diğer yönlerine etkisini değerlendirir.",
        "BDS 500 par. 11", "hard",
    ),
    r(
        "Denetçi bir faturayı okuyarak sözleşme koşullarıyla karşılaştırmıştır. Bu işlem hangi kanıt elde etme prosedürüdür?",
        "Kayıt ve belgelerin iç veya dış ortamda incelenmesi hangi prosedürdür?",
        "Tetkik",
        "Tetkik",
        ["Gözlem", "Sorgulama", "Yeniden hesaplama", "Yeniden uygulama"],
        ["Gözlem", "Dış teyit", "Analitik prosedür", "Yeniden uygulama"],
        "Belge ve kayıtların incelenmesi tetkik prosedürüdür.",
        "Tetkik; fiziki, elektronik veya başka ortamda bulunan iç ya da dış kayıt ve belgelerin incelenmesidir.",
        "BDS 500 par. A14-A18", "easy",
    ),
    r(
        "Denetçi, işletme personelinin stok sayım prosedürünü uygulamasını izlemektedir. Hangi prosedürü kullanmaktadır?",
        "Gözlem prosedürünün başlıca yapısal sınırlılığı nedir?",
        "Gözlem",
        "Gözlem anıyla sınırlı olup süreci etkileyebilmesi",
        ["Yeniden hesaplama", "Dış teyit", "Tetkik", "Analitik prosedür"],
        ["Hiçbir zaman denetim kanıtı sağlamaması", "Yalnız işletme dışı belgelerde uygulanabilmesi", "Her durumda bütün dönemi eksiksiz kapsaması", "Sadece yönetimin yazılı izniyle yapılabilmesi"],
        "Bir süreç başkalarınca uygulanırken izleniyorsa gözlem yapılır.",
        "Gözlem belirli bir zamandaki uygulamayı gösterir; ayrıca gözlenen kişinin davranışı gözlem nedeniyle değişebilir.",
        "BDS 500 par. A17", "medium",
    ),
    r(
        "Denetçi alacak bakiyesi için müşterinin borçlusundan doğrudan yazılı yanıt almıştır. Hangi prosedür uygulanmıştır?",
        "Dış teyit hangi kanıt elde etme biçimidir?",
        "Dış teyit",
        "Üçüncü kişiden doğrudan gelen yazılı yanıt",
        ["Yeniden uygulama", "Gözlem", "Sorgulama", "Yeniden hesaplama"],
        ["Yönetimin üçüncü kişi adına hazırladığı sözlü açıklama", "İşletmenin kendi kayıtlarından çıkardığı hesap özeti", "Denetçinin işletme içi raporu yeniden toplaması", "Müşteri çalışanının imzasız toplantı notu"],
        "Üçüncü kişinin doğrudan denetçiye verdiği yazılı yanıt dış teyit kanıtıdır.",
        "Dış teyit, teyit eden üçüncü kişiden denetçiye doğrudan gelen yazılı yanıttır.",
        "BDS 505 par. 5-6", "easy",
    ),
    r(
        "Denetçi amortisman tablosundaki matematiksel işlemleri yeniden yapmıştır. Hangi prosedür söz konusudur?",
        "Belge veya kayıtların matematiksel doğruluğunun kontrolü hangi prosedürdür?",
        "Yeniden hesaplama",
        "Yeniden hesaplama",
        ["Yeniden uygulama", "Gözlem", "Sorgulama", "Dış teyit"],
        ["Analitik prosedür", "Tetkik", "Gözlem", "Sorgulama"],
        "Matematiksel doğruluğun bağımsız kontrolü yeniden hesaplamadır.",
        "Yeniden hesaplama manuel veya elektronik olarak kayıtların matematiksel doğruluğunu kontrol eder.",
        "BDS 500 par. A19", "easy",
    ),
    r(
        "Denetçi işletmenin yaşlandırma kontrolünü bağımsız biçimde baştan uygulayarak aynı sonucu elde etmiştir. Hangi prosedürdür?",
        "İşletmenin iç kontrolünün parçası olan bir prosedürün denetçice bağımsız yürütülmesi nedir?",
        "Yeniden uygulama",
        "Yeniden uygulama",
        ["Yeniden hesaplama", "Sorgulama", "Gözlem", "Dış teyit"],
        ["Tetkik", "Analitik prosedür", "Dış teyit", "Gözlem"],
        "İşletme kontrolünün denetçi tarafından bağımsız biçimde yürütülmesi yeniden uygulamadır.",
        "Yeniden uygulama, işletmenin iç kontrolünün parçası olarak uygulanan prosedürün denetçice bağımsız gerçekleştirilmesidir.",
        "BDS 500 par. A20", "easy",
    ),
    r(
        "Denetçi brüt kâr oranını önceki dönem ve sektör verileriyle karşılaştırıp beklenmedik sapmayı araştırmıştır. Hangi prosedürdür?",
        "Finansal ve finansal olmayan veriler arasındaki makul ilişkilerin incelenmesi hangi prosedürdür?",
        "Analitik prosedür",
        "Analitik prosedür",
        ["Yeniden uygulama", "Tetkik", "Dış teyit", "Gözlem"],
        ["Yeniden hesaplama", "Sorgulama", "Gözlem", "Dış teyit"],
        "Oran ve eğilimlerin beklentilerle karşılaştırılması analitik prosedürdür.",
        "Analitik prosedürler veriler arasındaki makul ilişkileri ve belirlenen sapmaları inceler.",
        "BDS 500 par. A21; BDS 520", "easy",
    ),
    r(
        "Denetçi yalnız satış müdürüne sözlü soru sormuş ve önemli alacak bakiyesinin varlığı için başka kanıt toplamamıştır. Sorgulama tek başına yeterli midir?",
        "Sorgulama yoluyla elde edilen yanıtların temel kullanım biçimi nedir?",
        "Hayır; sorgulama çoğu zaman başka kanıtlarla desteklenir",
        "Diğer prosedürleri yönlendirmek ve kanıtları desteklemek",
        ["Evet; yönetici açıklaması dış teyidin yerini her zaman alır", "Evet; sözlü yanıt bütün hesap bakiyelerini kesin doğrular", "Hayır; sorgulama hiçbir zaman denetim kanıtı sağlamaz", "Evet; yalnız yanıt çalışma kâğıdına yazılırsa yeterlidir"],
        ["Bütün diğer denetim prosedürlerini ortadan kaldırmak", "Yönetimin finansal tablo sorumluluğunu denetçiye devretmek", "Denetim riskini hiçbir ek kanıt olmadan sıfırlamak", "Yalnız denetim ücretinin uygunluğunu doğrulamak"],
        "Sorgulama kanıt sağlayabilir; ancak önemli bir bakiyenin varlığı gibi konularda çoğunlukla tek başına yeterli değildir.",
        "Yanıtlar yeni bilgiler sağlayabilir ve diğer kanıtları destekleyebilir; gerektiğinde başka prosedürlerle doğrulanır.",
        "BDS 500 par. A22-A25", "medium",
    ),
    r(
        "Stoklar finansal tablolar için önemlidir ve fiziki sayım yapılmaktadır. Denetçi mümkün olduğu hâlde sayıma katılmamıştır. BDS 501'e uygun mudur?",
        "Önemli stokların fiziki sayımına katılım sırasında denetçinin temel işleri nelerdir?",
        "Hayır; mümkün olan hâllerde fiziki sayıma katılım gerekir",
        "Talimatlar, gözlem, stok tetkiki ve test sayımları",
        ["Evet; yönetimin sayım tutanağı tek başına her zaman yeterlidir", "Evet; yalnız stok değerleme yöntemini incelemek yeterlidir", "Hayır; denetçi bütün stokları bizzat saymak zorundadır", "Evet; sayım katılımı yalnız önemsiz stoklar için zorunludur"],
        ["Yalnız stok maliyetini yeniden hesaplamak ve satış fiyatını belirlemek", "İşletme adına sayımı yönetmek ve çalışanlara görev dağıtmak", "Sadece depo kirasını ve sigorta poliçesini incelemek", "Stok kayıtlarını hazırlayıp yönetim adına onaylamak"],
        "Önemli stoklarda sayım katılımı mevcudiyet ve durum hakkında doğrudan kanıt sağlar.",
        "Katılım, yönetim talimatlarının değerlendirilmesini, prosedürlerin gözlemini, stok tetkikini ve test sayımlarını içerir.",
        "BDS 501 par. 4", "medium",
    ),
    r(
        "Fiziki stok sayımı bilanço tarihinden bir ay önce yapılmıştır. Denetçi ara tarihteki sayıma katılıp aradaki değişiklikleri test etmemiştir. Yeterli midir?",
        "Öngörülemeyen nedenle sayım gününe katılamayan denetçinin ilk karşılığı nedir?",
        "Hayır; iki tarih arasındaki stok değişiklikleri test edilir",
        "Başka tarihte sayım yapıp veya gözlemleyip aradaki işlemleri test etmek",
        ["Evet; ara tarih sayımı dönem sonu stokunu otomatik doğrular", "Evet; yalnız yönetimin değişiklik olmadığı beyanı yeterlidir", "Hayır; bilanço tarihinden farklı sayım hiçbir zaman kullanılamaz", "Evet; aradaki satışlar yalnız vergi denetiminin konusudur"],
        ["Sayım prosedürünü hiçbir alternatif uygulamadan kaldırmak", "Yönetimin stok tutarını doğrudan doğru kabul etmek", "Yalnız denetim ücretini artırıp sayımı sonraki yıla bırakmak", "Stok kalemlerini finansal tablolardan kendiliğinden çıkarmak"],
        "Farklı tarihteki sayım ile raporlama tarihi arasındaki hareketler dönem sonu mevcudiyetini etkiler.",
        "Öngörülemeyen katılamama durumunda başka tarihte sayım yapılır veya gözlemlenir ve iki tarih arasındaki işlemler test edilir.",
        "BDS 501 par. 5-6", "hard",
    ),
    r(
        "İşletmeye ait önemli stoklar bağımsız lojistik şirketinin deposundadır. Denetçi yalnız yönetimin iç listesini kanıt kabul etmiştir. Uygun mudur?",
        "Üçüncü tarafın emanetindeki önemli stok için hangi kanıt yolları kullanılabilir?",
        "Hayır; üçüncü taraftan teyit veya uygun tetkik ve diğer prosedürler gerekir",
        "Üçüncü taraf teyidi ve koşullara uygun tetkik veya diğer denetim prosedürleri",
        ["Evet; işletmenin iç listesi üçüncü taraf stokunu kesin doğrular", "Evet; stok işletme dışında olduğundan denetim kapsamına girmez", "Hayır; denetçi lojistik şirketinin yönetimini devralmalıdır", "Evet; yalnız depo kira sözleşmesini görmek her durumda yeterlidir"],
        ["Yalnız işletmenin satış bütçesini ve fiyat listesini incelemek", "Stok tutarını hiçbir kanıt olmadan yönetim beyanından almak", "Depo çalışanlarının ücret bordrolarını yeniden hesaplamak", "Üçüncü tarafın bütün finansal tablolarını denetlemek"],
        "İşletme dışındaki önemli stokun miktarı ve durumu bağımsız teyit veya uygun başka prosedürlerle desteklenir.",
        "Denetçi üçüncü taraftan miktar ve durum teyidi isteyebilir; şartlara göre tetkik veya diğer prosedürleri de uygular.",
        "BDS 501 par. 8", "hard",
    ),
    r(
        "İşletmenin önemli bir davası vardır. Denetçi yönetimi ve işletme avukatını sorgulamadan yalnız muhasebe kayıtlarını incelemiştir. Yeterli midir?",
        "Dava ve iddiaların tamlığına ilişkin prosedürler arasında hangisi yer alır?",
        "Hayır; yönetim ve hukuk müşaviri sorgulanır, dış iletişim kurulur",
        "İç sorgulama ve dış hukuk müşaviriyle iletişim",
        ["Evet; kayda alınmayan dava denetçinin sorumluluğunda değildir", "Evet; yalnız dava gideri hesabını görmek bütün davaları doğrular", "Hayır; denetçi davanın hukuki sonucuna kendisi karar vermelidir", "Evet; yönetim dava olmadığını sözlü söylerse başka prosedür gerekmez"],
        ["Yalnız satış sözleşmelerinin ve reklam giderlerinin incelenmesi", "Denetim ücretinin hukuk müşavirince onaylanması", "Bütün dava dosyalarının finansal tablolardan çıkarılması", "İşletme avukatının denetim ekibine ortak edilmesi"],
        "Dava ve iddiaların eksik kaydedilme riski farklı bilgi kaynaklarının kullanılmasını gerektirir.",
        "Denetçi yönetimi ve uygun hukuk müşavirini sorgular, ilgili kurul tutanakları ve hukuk giderlerini inceler; gerekli hâlde dış hukuk müşaviriyle doğrudan iletişim kurar.",
        "BDS 501 par. 9-12", "hard",
    ),
    r(
        "Yönetim teyit edilecek tarafı seçmiş, talebi kendi e-posta adresinden göndermiş ve yanıtı düzenleyerek denetçiye iletmiştir. Dış teyit prosedürü uygun mudur?",
        "Dış teyit talepleri üzerinde kontrolü kim kurar ve sürdürür?",
        "Hayır; talep ve yanıt süreci denetçinin kontrolünde olmalıdır",
        "Denetçi",
        ["Evet; teyit sürecini bütünüyle yönetim yürütmelidir", "Evet; yanıt müşteri aracılığıyla gelirse daha güvenilirdir", "Hayır; teyit talebini yalnız teyit eden taraf tasarlamalıdır", "Evet; yönetimin düzenlediği her yanıt doğrudan dış kanıttır"],
        ["İşletme yönetimi", "Teyit edilen üçüncü taraf", "İç denetim fonksiyonu", "Finansal tablo kullanıcıları"],
        "Yönetimin araya girmesi yanıtın bütünlüğünü ve bağımsızlığını zedeler.",
        "Denetçi teyit edilecek bilgiyi ve tarafı seçer, talebi tasarlar, gönderir ve yanıtın doğrudan kendisine gelmesini sağlar.",
        "BDS 505 par. 7", "medium",
    ),
    r(
        "Teyit edilen tarafın mutabık olsa da olmasa da doğrudan denetçiye yanıt vermesi istenmiştir. Bu hangi teyit türüdür?",
        "Olumsuz teyit talebinde teyit eden taraf ne zaman yanıt verir?",
        "Olumlu teyit talebi",
        "Yalnız talepteki bilgilerle mutabık olmadığında",
        ["Olumsuz teyit talebi", "Yanıt verilmeyen teyit", "Teyit istisnası", "Yönetim beyanı"],
        ["Her durumda mutabık olup olmadığını bildirirken", "Yalnız denetçi ikinci kez talep gönderdiğinde", "Yönetim doğrudan kendisine yanıt istediğinde", "Teyit bakiyesi finansal tablolardan çıkarıldığında"],
        "Olumlu teyitte üçüncü kişiden her durumda doğrudan yanıt beklenir.",
        "Olumsuz teyitte taraf yalnız talep edilen bilgilerle mutabık değilse doğrudan denetçiye yanıt verir.",
        "BDS 505 par. 6", "easy",
    ),
    r(
        "Yönetim banka teyidi gönderilmesine izin vermemiştir. Denetçi gerekçeyi araştırmadan ve alternatif prosedür uygulamadan bakiyeyi doğru kabul etmiştir. Uygun mudur?",
        "Olumlu teyit talebine yanıt verilmemesi durumunda denetçinin temel karşılığı nedir?",
        "Hayır; gerekçe, risk ve alternatif prosedürler değerlendirilir",
        "İhtiyaca uygun ve güvenilir kanıt sağlayacak alternatif denetim prosedürleri uygulamak",
        ["Evet; yönetimin izin vermemesi bakiyeyi doğrular", "Evet; teyit yanıtı alınmayınca hesap otomatik doğru sayılır", "Hayır; hiçbir inceleme yapmadan doğrudan olumlu görüş verilir", "Evet; yalnız teyit talebini çalışma dosyasına koymak yeterlidir"],
        ["Yanıt alınmayan bakiyeyi doğrudan finansal tablolardan silmek", "Yönetimin sözlü açıklamasını tek başına kesin kanıt kabul etmek", "Teyit prosedürünü bir sonraki hesap dönemine ertelemek", "Yalnız denetim ücretini artırarak kanıt eksikliğini gidermek"],
        "Yönetimin engeli hile dâhil riskleri etkileyebilir; gerekçeler ve alternatif kanıt yolları değerlendirilir.",
        "Yanıt verilmeyen olumlu teyit için denetçi alternatif prosedürlerle ilgili ve güvenilir kanıt elde etmeye çalışır.",
        "BDS 505 par. 8-12", "hard",
    ),
    r(
        "Yönetim bütün sorumluluklarını yerine getirdiğine dair yazılı beyan vermiştir. Denetçi bu beyanı diğer bütün kanıtların yerine kullanabilir mi?",
        "Yazılı beyanların tarihi denetçi raporu tarihiyle nasıl ilişkilidir?",
        "Hayır; yazılı beyan tek başına ele aldığı konuda yeterli ve uygun kanıt sağlamaz",
        "Rapor tarihinden sonra olamaz ve rapor tarihine mümkün olan en yakın tarih olur",
        ["Evet; güvenilir yazılı beyan bütün prosedürlerin yerini alır", "Evet; yönetim imzaladığında dış teyit ve detay testleri kaldırılır", "Hayır; yazılı beyan hiçbir zaman denetim kanıtı değildir", "Evet; beyan yalnız sözlü açıklamaları desteklemek için kullanılır"],
        ["Her durumda rapor tarihinden sonra düzenlenir", "Yalnız finansal tablolar yayımlandıktan sonra alınır", "Önceki yıl rapor tarihli beyan süresiz kullanılabilir", "Tarihsiz hazırlanması beyanın güvenilirliğini artırır"],
        "Yazılı beyan gerekli bir kanıttır; ancak diğer uygun kanıtların niteliğini veya kapsamını ortadan kaldırmaz.",
        "Beyan rapor tarihinden sonraya bırakılamaz; rapora mümkün olan en yakın tarihi taşır ve ilgili tüm dönemleri kapsar.",
        "BDS 580 par. 3-4 ve 14", "hard",
    ),
]


PREMISES = [
    {"stem":"Denetim kanıtının niteliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yeterlilik kanıt miktarının ölçütüdür\n\nII. Uygunluk kanıt kalitesinin ölçütüdür\n\nIII. Uygunluk ihtiyaca uygunluk ve güvenilirliği içerir","correct":"I, II ve III","why":"Üç ifade de BDS 500'deki yeterlilik ve uygunluk tanımlarına uygundur.","ref":"BDS 500 par. 5","difficulty":"easy"},
    {"stem":"Kanıt güvenilirliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bağımsız dış kaynak kanıtı genellikle daha güvenilirdir\n\nII. Doğrudan elde edilen kanıt genellikle daha güvenilirdir\n\nIII. Belge şeklindeki kanıt genellikle daha güvenilirdir","correct":"I, II ve III","why":"Kaynak, elde edilme biçimi ve belgelendirme güvenilirliğe ilişkin genel değerlendirmelerdir.","ref":"BDS 500 par. A31","difficulty":"easy"},
    {"stem":"İşletme tarafından üretilen bilgi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yönetim imzası doğruluk testini gereksiz kılar\n\nII. Bilginin doğruluğu ve tamlığı değerlendirilir\n\nIII. Bilginin amaç için yeterince açık ve ayrıntılı olup olmadığı değerlendirilir","correct":"II ve III","why":"Yönetim imzası tek başına yeterli değildir; doğruluk, tamlık, açıklık ve ayrıntı değerlendirilir.","ref":"BDS 500 par. 9","difficulty":"medium"},
    {"stem":"Fiziki stok sayımı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yönetim talimatları değerlendirilir\n\nII. Sayım prosedürlerinin uygulanması gözlemlenir\n\nIII. Denetçi hiçbir test sayımı yapmaz","correct":"I ve II","why":"Denetçi talimatları değerlendirir, uygulamayı gözlemler, stokları tetkik eder ve test sayımları yapar; III yanlıştır.","ref":"BDS 501 par. 4","difficulty":"medium"},
    {"stem":"Dış teyitler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Talep süreci üzerinde kontrol denetçidedir\n\nII. Yanıt doğrudan denetçiye yöneltilir\n\nIII. Yönetim yanıtı düzenleyip denetçiye iletmelidir","correct":"I ve II","why":"Denetçi talep sürecinin kontrolünü korur ve yanıtın doğrudan kendisine gelmesini sağlar; yönetim aracılığı güvenilirliği zedeler.","ref":"BDS 505 par. 6-7","difficulty":"medium"},
    {"stem":"Yazılı beyanlar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yazılı beyan tek başına her konuda yeterli ve uygun kanıttır\n\nII. Yazılı beyan denetim kanıtıdır\n\nIII. Diğer denetim kanıtlarının yerini otomatik almaz","correct":"II ve III","why":"Yazılı beyan kanıttır; ancak ele aldığı konuda tek başına yeterli ve uygun kanıt değildir.","ref":"BDS 580 par. 3-4","difficulty":"medium"},
    {"stem":"Kanıt tutarsızlığı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tutarsızlığı çözmek için prosedür değiştirilebilir\n\nII. Güvenilirlik şüphesinde ilave prosedür uygulanabilir\n\nIII. Sorunun denetimin diğer yönlerine etkisi dikkate alınmaz","correct":"I ve II","why":"Prosedürler değiştirilir veya genişletilir ve sorunun diğer denetim alanlarına etkisi de değerlendirilir; III yanlıştır.","ref":"BDS 500 par. 11","difficulty":"hard"},
    {"stem":"Stok sayımına katılım bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Öngörülemeyen katılamama hâlinde başka tarihte sayım gözlenebilir\n\nII. Alternatif prosedürle kanıt alınamasa da görüş etkilenmez\n\nIII. Üçüncü taraftaki önemli stok için teyit istenebilir","correct":"I ve III","why":"Başka tarihte sayım ve aradaki işlemler test edilebilir; üçüncü taraf teyidi mümkündür. Kanıt alınamazsa görüş etkilenebilir.","ref":"BDS 501 par. 6-8","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="denetim_kaniti",
        label="Denetim Kanıtı", slug="denetim_kaniti", prefix="topic-dk",
        seed=2026071750,
        legislation_version="KGK TDS 2026 Seti; BDS 500, 501, 505, 520 ve 580, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
