#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Hukuk — Tacir ve Yükümlülükleri konu havuzu (3×20).

Dayanak, 17.07.2026 tarihinde mevzuat.gov.tr'den alınan güncel 6102 sayılı
Türk Ticaret Kanunu metninin 18–23. maddeleridir. Paket, Ticari İşletme konu
havuzundaki tacir sıfatının kazanılması sorularını tekrar etmez; tacir olmanın
sonuçları ile ticari satışın özel hükümlerine odaklanır.
"""
from topic_pack_builder import write_topic


RULES = [
    {
        "scenario": "Gerçek kişi tacir A'nın ticari işletmesiyle ilgisi bulunmayan özel bir borcu ödenmemiştir. A, borcun adi nitelikte olduğunu ileri sürerek hakkında iflas yoluna başvurulamayacağını savunmaktadır. Bu savunma nasıl değerlendirilmelidir?",
        "focus": "Bir tacirin işletme faaliyeti dışında doğan borcu nedeniyle iflas yoluyla takip edilmesi istenmiştir. Tacir olmanın genel sonuçları bakımından hangi sonuca ulaşılır?",
        "correct": "Tacir, ticari olup olmadığına bakılmaksızın her türlü borcu için iflasa tabidir",
        "distractors": [
            "Tacir yalnız ticari işletmesinden doğan ve senede bağlanan borçları için iflasa tabidir",
            "Tacirin özel borçları bakımından yalnız haciz yoluna başvurulabilir, iflas yolu kapalıdır",
            "Tacir ancak borcun iki taraf için de ticari iş sayılması hâlinde iflasa tabi tutulabilir",
            "Tacirin iflasa tabi olması için borcun ticaret siciline ayrıca kaydedilmiş olması gerekir",
        ],
        "focus_distractors": [
            "İflas yolu yalnız tacirin işletme hesabına kaydettiği borçlar için kullanılabilir",
            "Borç adi ise tacir sıfatı iflas bakımından hiçbir sonuç doğurmaz",
            "İflas yolu için alacaklının da tacir sıfatını taşıması zorunludur",
            "Tacirin özel borçlarında iflas ancak kendisinin yazılı kabulüyle mümkündür",
        ],
        "why": "TTK m.18/1, taciri her türlü borcu için iflasa tabi tutar. Borcun ticari işletmeyle ilgili olmaması bu sonucu kaldırmaz; savunma bu nedenle yerinde değildir.",
        "focus_why": "İflasa tabi olma, tacir sıfatına bağlanan genel bir sonuçtur. TTK m.18/1 ticari ve adi borç ayrımı yapmadan tacirin her türlü borcunu kapsar.",
        "ref": "6102 sayılı TTK m.18/1",
        "difficulty": "medium",
    },
    {
        "scenario": "Bir tacir ticari faaliyetini fiilen sürdürmesine rağmen ticaret unvanı seçmemiş, işletmesini ticaret siciline tescil ettirmemiş ve tutulması gereken ticari defterleri de tutmamıştır. TTK m.18 bakımından hangisi doğrudur?",
        "focus": "Tacir olmanın kanunda açıkça sayılan genel yükümlülükleri birlikte değerlendirildiğinde aşağıdaki yükümlülük gruplarından hangisi doğrudur?",
        "correct": "Ticaret unvanı seçmek, işletmeyi tescil ettirmek ve gerekli ticari defterleri tutmak",
        "distractors": [
            "İşletme adı seçmek, bütün sözleşmeleri noterde yapmak ve her alacağı senede bağlamak",
            "Marka tescil ettirmek, anonim şirkete dönüşmek ve bağımsız denetçi atamak",
            "Esnaf siciline kaydolmak, her işlemi ilan etmek ve bütün ödemeleri bankadan yapmak",
            "Odaya kaydolmak, sermaye artırmak ve her yıl ticaret unvanını yenilemek",
        ],
        "focus_distractors": [
            "Marka tescili yaptırmak, şirket kurmak ve bütün işlemleri yazılı şekle bağlamak",
            "Esnaf odasına kaydolmak, işletme adı kullanmak ve her faturayı sicilde ilan etmek",
            "Sermaye taahhüdünde bulunmak, bağımsız denetime girmek ve pay senedi çıkarmak",
            "Bütün borçları teminatlandırmak, banka hesabı açmak ve elektronik tebligat adresi edinmek",
        ],
        "why": "TTK m.18/1 tacire kanuna uygun ticaret unvanı seçme, ticari işletmesini ticaret siciline tescil ettirme ve Kanuna göre gerekli ticari defterleri tutma yükümlülüklerini birlikte yükler.",
        "focus_why": "Kanunda tacir için açıkça sayılan üçlü; ticaret unvanı, ticaret siciline tescil ve ticari defterlerdir. Marka tescili veya şirket türü seçimi bu hükümdeki genel zorunluluklardan değildir.",
        "ref": "6102 sayılı TTK m.18/1",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacir B, uzmanlık alanı dışında yaptığı ticari bir sözleşmede yeterli araştırma yapmadığını, bu nedenle sözleşmenin doğuracağı riski öngöremediğini ileri sürmektedir. Basiretli hareket yükümlülüğü bakımından hangisi doğrudur?",
        "focus": "Bir tacirin piyasa koşullarını ve sözleşme risklerini değerlendirirken yalnız kendi kişisel bilgi ve deneyim düzeyini ölçü alması, TTK'daki davranış standardı bakımından nasıl değerlendirilir?",
        "correct": "Tacirden, ticari faaliyetlerinde tedbirli ve öngörülü davranması beklenir",
        "distractors": [
            "Tacirin yalnız dürüst davranması yeterlidir; mesleki özen ve öngörü ayrıca aranmaz",
            "Tacirin sorumluluğu kendi kişisel bilgi düzeyiyle sınırlıdır; nesnel bir ölçü uygulanmaz",
            "Basiret yükümlülüğü yalnız bankalar ve sermaye şirketleri için geçerli özel bir ilkedir",
            "Tacir sözleşme riskini bilmediğini açıkladığında basiret yükümlülüğünden tamamen kurtulur",
        ],
        "focus_distractors": [
            "Kişisel deneyim her durumda tek ölçüdür; tacirden piyasa araştırması yapması beklenemez",
            "Davranış standardı yalnız karşı tarafın da tacir olması hâlinde uygulanabilir",
            "Basiret ölçüsü yalnız defter tutma ve sicile tescil işlemleriyle sınırlı olarak uygulanır",
            "Tacirin iyi niyetli olması, öngörülebilir riskleri araştırmamasını her durumda haklı kılar",
        ],
        "why": "TTK m.18/2 uyarınca tacir, ticaretine ait bütün faaliyetlerinde basiretli bir iş adamı gibi hareket etmelidir. Kişisel bilgisizlik, nesnel nitelikteki özen ve öngörü beklentisini ortadan kaldırmaz.",
        "focus_why": "Basiret ölçüsü tacirin yalnız öznel yeteneklerine göre belirlenmez. Aynı faaliyet alanındaki tedbirli ve öngörülü bir tacirden beklenen davranış esas alınır.",
        "ref": "6102 sayılı TTK m.18/2",
        "difficulty": "medium",
    },
    {
        "scenario": "İki tacir arasındaki ticari sözleşmede borçlu temerrüde düşmüştür. Alacaklı, temerrüt ihtarını güvenli elektronik imza kullanarak kayıtlı elektronik posta sistemi üzerinden göndermiştir. Şekil bakımından hangisi doğrudur?",
        "focus": "Tacirler arasında diğer tarafı temerrüde düşürmeye ilişkin bir ihtar için TTK m.18/3'te öngörülen yöntemlerden biri aşağıdakilerden hangisidir?",
        "correct": "Güvenli elektronik imzalı kayıtlı elektronik posta sistemi",
        "distractors": [
            "Göndereni doğrulamayan sıradan elektronik posta mesajı",
            "Sosyal medya hesabından gönderilen doğrudan mesaj",
            "Telefon görüşmesinde yapılan ve kayda alınmayan sözlü bildirim",
            "Teslim kaydı bulunmayan isimsiz kısa mesaj bildirimi",
        ],
        "focus_distractors": [
            "Güvenli elektronik imza içermeyen olağan e-posta iletisi",
            "Taraflardan birinin internet sitesinde yayımladığı duyuru",
            "İçeriği sonradan yazıya geçirilmeyen telefon görüşmesi",
            "Alıcının hesabına gönderilen açıklamasız banka havalesi",
        ],
        "why": "TTK m.18/3; noter, taahhütlü mektup, telgraf ve güvenli elektronik imzalı kayıtlı elektronik posta sistemini sayar. Olaydaki KEP bildirimi bu yöntemlerden biridir.",
        "focus_why": "Temerrüt, fesih ve dönmeye ilişkin tacirler arası bildirimlerde güvenli elektronik imza kullanılarak KEP üzerinden gönderim Kanunda açıkça yer alan yöntemlerdendir.",
        "ref": "6102 sayılı TTK m.18/3",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacirler arasındaki bir sözleşmenin feshedileceğini bildirmek isteyen taraf, bildirimi taahhütlü mektupla göndermiştir. Muhatap, yalnız noter bildiriminin geçerli olacağını ileri sürmektedir. Hangisi doğrudur?",
        "focus": "Tacirler arasında sözleşmeden dönmeye ilişkin ihtar bakımından aşağıdaki gönderim yöntemlerinden hangisi TTK m.18/3'te açıkça sayılmıştır?",
        "correct": "Taahhütlü mektup Kanunda sayılan bildirim yöntemlerinden biridir",
        "distractors": [
            "Fesih bildirimi yalnız noter aracılığıyla yapılabilir; diğer yöntemlerin tamamı geçersizdir",
            "Fesih bildirimi yalnız ticaret sicili gazetesinde ilan edilerek yapılabilir",
            "Taahhütlü mektup sadece fatura itirazlarında kullanılabilir, fesihte kullanılamaz",
            "Tacirler arasındaki fesih bildirimi herhangi bir biçime ihtiyaç olmadan yalnız sözlü yapılır",
        ],
        "focus_distractors": [
            "Alındı bilgisi bulunmayan olağan elektronik posta mesajı",
            "Şirketin herkese açık sosyal medya hesabındaki paylaşım",
            "Tutanağa bağlanmamış yüz yüze sözlü açıklama",
            "Muhatabın görüp görmediği belirlenemeyen kısa mesaj",
        ],
        "why": "TTK m.18/3'te noter yanında taahhütlü mektup, telgraf ve güvenli elektronik imzalı KEP de sayılmıştır. Muhatabın yöntemi yalnız notere indirgeyen itirazı doğru değildir.",
        "focus_why": "Sözleşmeden dönme bildirimi bakımından taahhütlü mektup, Kanunun açıkça belirttiği yöntemler arasındadır; sıradan dijital veya sözlü bildirimler maddede sayılmaz.",
        "ref": "6102 sayılı TTK m.18/3",
        "difficulty": "medium",
    },
    {
        "scenario": "Bir tacir borçlandığı sırada işlemin işletmesiyle ilgili olup olmadığına dair hiçbir açıklama yapmamıştır. İşlemin niteliği de ticari sayılmasına elverişlidir. Borcun niteliği bakımından hangisi doğrudur?",
        "focus": "Tacirin borçları hakkında TTK m.19/1'de kabul edilen temel karine aşağıdakilerden hangisidir?",
        "correct": "Tacirin üstlendiği borcun ticari nitelikte olması kanuni asıldır",
        "distractors": [
            "Tacirin her borcu aksi kararlaştırılamayan şekilde adi sayılır",
            "Borcun ticari sayılması için mutlaka senede bağlanması gerekir",
            "Borcun niteliğini yalnız alacaklının tacir olup olmaması belirler",
            "Borcun ticari olması için ticaret sicilinde ayrıca ilan edilmesi gerekir",
        ],
        "focus_distractors": [
            "Tacirin yalnız vergi kayıtlarına işlediği borçları ticari sayılır",
            "Tacirin bütün borçları herhangi bir istisna olmaksızın adi borçtur",
            "Borcun ticari niteliği ancak iki tarafın yazılı kabulüyle doğar",
            "Tacir borcunun niteliği yalnız ödeme günündeki kullanım amacına göre belirlenir",
        ],
        "why": "TTK m.19/1'e göre bir tacirin borçlarının ticari olması asıldır. Somut olayda gerçek kişi tacire tanınan istisnaları gösterecek bir açıklama veya elverişsizlik de bulunmamaktadır.",
        "focus_why": "Kanun tacir borçları için ticari iş karinesi kurar. Gerçek kişi tacirin işlem anındaki açık bildirimi veya işin niteliğinin elverişsizliği bu karinenin istisnalarıdır.",
        "ref": "6102 sayılı TTK m.19/1",
        "difficulty": "easy",
    },
    {
        "scenario": "Gerçek kişi tacir D, evinde kişisel kullanım için satın aldığı mobilyanın ticari işletmesiyle ilgili olmadığını sözleşme kurulurken satıcıya açıkça bildirmiştir. Borcun niteliği bakımından hangisi doğrudur?",
        "focus": "Gerçek kişi tacirin yaptığı bir işlemin ticari iş karinesinin dışında kalabilmesi için TTK m.19/1'de öngörülen yollardan biri hangisidir?",
        "correct": "İşlem anında işletmeyle ilgisizliğin diğer tarafa açıkça bildirilmesi",
        "distractors": [
            "Ödeme gününden sonra borcun kişisel amaçla kullanıldığının tek taraflı olarak açıklanması",
            "İşlemin üzerinden sekiz gün geçtikten sonra ticari nitelikten vazgeçildiğinin bildirilmesi",
            "Borcun ticari defterlere kaydedilmemesinin tek başına adi borç sonucu doğurması",
            "Karşı tarafın tacir olmamasının her durumda borcu kendiliğinden adi hâle getirmesi",
        ],
        "focus_distractors": [
            "Tacirin ödeme tarihinden sonra işletme bağlantısını sözlü olarak reddetmesi",
            "İşlemin ticari deftere kaydedilmemesi ve faturanın daha sonra iade edilmesi",
            "Karşı tarafın tacir olmadığına dair sicilden belge getirerek işlemi iptal etmesi",
            "Sözleşme ifa edildikten sonra ticari iş karinesinden tek taraflı olarak vazgeçmesi",
        ],
        "why": "Gerçek kişi tacir, işlemi yaptığı anda bunun ticari işletmesiyle ilgili olmadığını karşı tarafa açıkça bildirirse borç adi sayılır. Sonradan yapılan tek taraflı açıklama aynı sonucu doğurmaz.",
        "focus_why": "TTK m.19/1'deki ilk istisna, gerçek kişi tacirin işlem anındaki açık bildirimidir. Bildirimin zamanı ve karşı tarafa yöneltilmiş olması belirleyicidir.",
        "ref": "6102 sayılı TTK m.19/1",
        "difficulty": "medium",
    },
    {
        "scenario": "Gerçek kişi tacir E, çocuğunun düğününde kullanılması amacıyla kişisel bir hizmet satın almış; işlem sırasında ayrıca açıklama yapmamıştır. İşin ticari sayılmasına durumun elverişli olmadığı açıktır. Hangisi doğrudur?",
        "focus": "Gerçek kişi tacirin işlem anında özel amaç açıklaması yapmadığı bir durumda, işin niteliği ticari sayılmaya elverişli değilse borcun niteliği nasıl belirlenir?",
        "correct": "İşin ticari sayılmasına durum elverişli olmadığından borç adi sayılabilir",
        "distractors": [
            "Tacir sıfatı nedeniyle kişisel amaçlı her borç zorunlu olarak ticari sayılır",
            "Borç ancak karşı taraf da tacirse adi nitelik kazanabilir",
            "Açık bildirim bulunmadığında işin niteliği hiçbir şekilde dikkate alınamaz",
            "Borcun adi sayılması için tacirin ticaret sicilinden kaydını sildirmesi gerekir",
        ],
        "focus_distractors": [
            "İşin niteliğine bakılmaksızın tacirin bütün borçları kesin olarak ticari kalır",
            "Borcun adi sayılması için her durumda noter aracılığıyla önceden bildirim gerekir",
            "Karşı taraf tacir değilse bütün sözleşmeler kendiliğinden geçersiz hâle gelir",
            "İşlem ancak ticari deftere kaydedilmezse adi borç niteliğine dönüşebilir",
        ],
        "why": "TTK m.19/1 gerçek kişi tacir için iki ayrı istisna tanır. Açık bildirim bulunmasa bile işin ticari sayılmasına durum elverişli değilse borç adi sayılır.",
        "focus_why": "İşlemin niteliğinin ticari sayılmaya elverişli olmaması, işlem anındaki açık bildirimden bağımsız ikinci istisnadır. Bu nedenle kişisel nitelik somut olayda dikkate alınır.",
        "ref": "6102 sayılı TTK m.19/1",
        "difficulty": "medium",
    },
    {
        "scenario": "Bir sözleşme, taraflardan yalnız satıcı tacirin ticari işletmesiyle ilgilidir; alıcı için ticari nitelik taşımamaktadır. Kanunda aksine özel bir hüküm de yoktur. Sözleşmenin niteliği bakımından hangisi doğrudur?",
        "focus": "Taraflardan yalnız biri için ticari iş niteliğinde olan sözleşmeler hakkında TTK m.19/2'nin getirdiği kural aşağıdakilerden hangisidir?",
        "correct": "Sözleşme, kanunda aksine hüküm yoksa diğer taraf için de ticari iş sayılır",
        "distractors": [
            "Sözleşme iki taraf bakımından da kendiliğinden adi iş sayılır",
            "Sözleşmenin ticari niteliği yalnız tacir olan tarafla sınırlı kalır",
            "Diğer taraf noter önünde kabul etmedikçe sözleşme geçersiz olur",
            "Sözleşme ancak ticaret sicilinde ilan edilirse diğer taraf için ticari sayılır",
        ],
        "focus_distractors": [
            "Sözleşme her iki taraf bakımından da zorunlu olarak tüketici işlemi sayılır",
            "Ticari nitelik yalnız tacir taraf için sonuç doğurur ve karşı tarafa geçmez",
            "Diğer tarafın tacir olmaması sözleşmenin hukuki sonuçlarını ortadan kaldırır",
            "Ticari sayılma için tarafların sonradan ayrı bir yazılı anlaşma yapması zorunludur",
        ],
        "why": "TTK m.19/2 uyarınca taraflardan yalnız biri için ticari iş niteliğindeki sözleşme, Kanunda aksine hüküm bulunmadıkça diğeri için de ticari iş sayılır.",
        "focus_why": "Hüküm sözleşmelerde ticari niteliği kural olarak karşı tarafa da genişletir. Ancak Kanunda aksine özel düzenleme varsa bu genel kural uygulanmaz.",
        "ref": "6102 sayılı TTK m.19/2",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacir F, ticari işletmesiyle ilgili olarak tacir olmayan bir kişiye danışmanlık hizmeti vermiş; taraflar ücret miktarını önceden kararlaştırmamıştır. F'nin ücret istemi bakımından hangisi doğrudur?",
        "focus": "Bir tacirin ticari işletmesiyle ilgili olarak gördüğü iş veya hizmet karşılığında ücret isteyebilmesi için hizmetten yararlanan kişinin de tacir olması gerekir mi?",
        "correct": "Tacir, hizmet verdiği kişi tacir olmasa da uygun bir ücret isteyebilir",
        "distractors": [
            "Ücret ancak karşı taraf da tacirse ve miktar sicilde ilan edilmişse istenebilir",
            "Önceden yazılı ücret anlaşması yoksa tacir hiçbir karşılık talep edemez",
            "Tacir olmayan kişiye verilen hizmetler kanunen her durumda karşılıksız sayılır",
            "Ücret hakkı yalnız mal satışında doğar; iş veya hizmet görme hâlinde doğmaz",
        ],
        "focus_distractors": [
            "Karşı tarafın tacir sıfatı taşıması ücret hakkının zorunlu koşuludur",
            "Ücret hakkı yalnız taraflar noter önünde miktarı belirlemişse doğabilir",
            "Hizmetten yararlanan tüketici ise tacirin ücret istemesi tümüyle yasaktır",
            "Tacir yalnız masraflarını geri isteyebilir, yaptığı hizmet için ücret isteyemez",
        ],
        "why": "TTK m.20, tacirin ticari işletmesiyle ilgili iş veya hizmeti tacir olan ya da olmayan bir kişiye görmesi hâlinde uygun ücret isteyebileceğini düzenler.",
        "focus_why": "Ücret isteme hakkı bakımından muhatabın tacir olması aranmaz. Belirleyici olan, tacirin gördüğü iş veya hizmetin kendi ticari işletmesiyle ilgili olmasıdır.",
        "ref": "6102 sayılı TTK m.20",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacir G, müşterisinin işi için kendi kaynaklarından avans vermiş ve zorunlu gider yapmıştır. Taraflar faiz başlangıcını ayrıca kararlaştırmamıştır. Kanuni faiz hakkı bakımından hangisi doğrudur?",
        "focus": "Tacirin ticari işletmesiyle ilgili iş nedeniyle verdiği avanslar ve yaptığı giderler için faiz hakkı hangi andan itibaren doğar?",
        "correct": "Tacir, avans ve giderler için ödeme tarihinden itibaren faize hak kazanır",
        "distractors": [
            "Faiz ancak müşteriye noter ihtarı gönderildiği tarihten itibaren işlemeye başlar",
            "Faiz yalnız dava açıldığı tarihten itibaren ve mahkeme kararıyla doğar",
            "Avans ve giderler için taraflar anlaşmadıkça hiçbir zaman faiz istenemez",
            "Faiz hakkı işin tamamlanmasından sekiz gün sonra kendiliğinden başlar",
        ],
        "focus_distractors": [
            "İş veya hizmetin tamamen bitirilip faturanın kesildiği tarihten itibaren",
            "Borçluya yapılan ilk yazılı başvurudan otuz gün sonra",
            "Alacak hakkında dava açılıp tensip tutanağı düzenlendiği tarihten itibaren",
            "Tarafların daha sonra faiz konusunda yazılı anlaşmaya vardığı tarihten itibaren",
        ],
        "why": "TTK m.20 tacire, verdiği avanslar ve yaptığı giderler için ödeme tarihinden itibaren faiz hakkı tanır. Ayrıca temerrüt ihtarı veya dava şartı aranmaz.",
        "focus_why": "Kanuni başlangıç anı, tacirin avansı verdiği veya gideri ödediği tarihtir. Faiz hakkı işin tamamlanmasına ya da sonradan yapılacak ihtara ertelenmez.",
        "ref": "6102 sayılı TTK m.20",
        "difficulty": "medium",
    },
    {
        "scenario": "Tacir H, ticari işletmesi kapsamında bir alıcıya mal satmıştır. Alıcı kendisine fatura verilmesini talep etmektedir. Taraflar sözleşmede fatura düzenlenmeyeceğini kararlaştırdıklarını ileri sürmektedir. TTK m.21 bakımından hangisi doğrudur?",
        "focus": "Ticari işletmesi bağlamında mal satan, mal üreten, iş gören veya menfaat sağlayan tacirden diğer tarafın isteyebileceği belge hangisidir?",
        "correct": "Diğer taraf, tacirden kendisine bir fatura verilmesini isteyebilir",
        "distractors": [
            "Diğer taraf yalnız ticaret sicili tasdiknamesi verilmesini isteyebilir",
            "Fatura isteme hakkı yalnız alıcının da tacir olması hâlinde doğar",
            "Fatura talebi ancak mal tesliminden önce noter aracılığıyla yapılabilir",
            "Tacir satış yaptıktan sonra hiçbir belge verme yükümlülüğü altında değildir",
        ],
        "focus_distractors": [
            "Yalnız işletmenin son üç yıllık ticari defterlerinin onaylı örneğini",
            "Her işlem için ticaret sicili müdürlüğünce düzenlenen faaliyet belgesini",
            "Sadece sözleşmenin noter tarafından onaylanmış tam metnini",
            "Tacirin bütün banka hareketlerini içeren hesap dökümünü",
        ],
        "why": "TTK m.21/1, ticari işletmesi bağlamında mal satan veya üreten, iş gören ya da menfaat sağlayan tacirden diğer tarafın fatura isteyebilmesini düzenler.",
        "focus_why": "Kanunun bu işlem türleri için tanıdığı belge talebi faturadır. Talep sahibinin ayrıca tacir olması veya faturanın sicilde düzenlenmesi koşulu yoktur.",
        "ref": "6102 sayılı TTK m.21/1",
        "difficulty": "easy",
    },
    {
        "scenario": "Bir müşteri, tacire yaptığı ödemenin faturada gösterilmesini istemiştir. Tacir, faturada yalnız mal veya hizmet bedelinin yer alabileceğini savunmaktadır. Bu savunma nasıl değerlendirilir?",
        "focus": "Ticari işletme bağlamındaki işlem bedeli daha önce ödenmişse, faturayı talep eden taraf TTK m.21/1 uyarınca ayrıca ne isteyebilir?",
        "correct": "Bedelin ödenmiş olduğunun faturada gösterilmesini isteyebilir",
        "distractors": [
            "Ödeme bilgisi yalnız ticari defterde tutulur ve faturada hiçbir zaman gösterilemez",
            "Ödeme ancak ticaret sicili müdürlüğünün ayrı belgesiyle kanıtlanabilir",
            "Fatura düzenlendiğinde daha önce yapılmış ödeme kendiliğinden geçersiz olur",
            "Bedelin ödendiği yalnız mahkeme kararı alınırsa faturaya yazılabilir",
        ],
        "focus_distractors": [
            "Tacirin bütün alacaklılarının isimlerinin faturaya eklenmesini isteyebilir",
            "İşletmenin yıllık bilançosunun fatura eki yapılmasını isteyebilir",
            "Ödemenin ticaret sicili gazetesinde ilan edilmesini isteyebilir",
            "Tacirin kişisel malvarlığının faturada açıklanmasını isteyebilir",
        ],
        "why": "TTK m.21/1'e göre diğer taraf fatura isteyebileceği gibi, bedel ödenmişse bunun faturada gösterilmesini de talep edebilir. Tacirin savunması hükme uygun değildir.",
        "focus_why": "Kanun, ödeme yapılmış olduğunun faturada belirtilmesini isteme hakkını açıkça tanır. Bu kayıt ödeme durumunu faturanın içeriğinde görünür kılar.",
        "ref": "6102 sayılı TTK m.21/1",
        "difficulty": "easy",
    },
    {
        "scenario": "Alıcı 3 Mart'ta aldığı faturanın içeriğine 12 Mart'ta ilk kez itiraz etmiştir. Arada süreyi durduran özel bir durum bulunmamaktadır. TTK m.21/2 bakımından hangisi doğrudur?",
        "focus": "Bir faturayı alan kişi, faturanın içeriğine ilişkin kanuni karinenin doğmasını önlemek için faturayı aldığı tarihten itibaren kaç gün içinde itiraz etmelidir?",
        "correct": "Faturanın alındığı tarihten itibaren sekiz gün içinde itiraz edilmelidir",
        "distractors": [
            "Faturanın düzenlendiği tarihten itibaren iki gün içinde itiraz edilmelidir",
            "Faturanın alındığı tarihten itibaren on beş gün içinde itiraz edilmelidir",
            "Ödeme vadesinden itibaren otuz gün içinde itiraz edilmelidir",
            "Fatura içeriğine ilişkin itiraz için herhangi bir süre öngörülmemiştir",
        ],
        "focus_distractors": [
            "Faturanın düzenlenmesini izleyen iki gün içinde",
            "Faturada yazılı ödeme vadesinden itibaren yedi gün içinde",
            "Faturanın muhasebe kayıtlarına işlendiği tarihten itibaren on beş gün içinde",
            "Malın yeniden satıldığı tarihten itibaren otuz gün içinde",
        ],
        "why": "TTK m.21/2'de itiraz süresi faturanın alındığı tarihten itibaren sekiz gündür. Dokuzuncu günde yapılan itiraz, süresinde itiraz edilmemesine bağlanan karineyi önlemez.",
        "focus_why": "Fatura içeriğine itiraz için ölçü düzenleme veya vade tarihi değil, faturanın alındığı tarihtir. Bu tarihten başlayan kanuni süre sekiz gündür.",
        "ref": "6102 sayılı TTK m.21/2",
        "difficulty": "medium",
    },
    {
        "scenario": "Bir kişi aldığı faturanın içeriğine sekiz gün içinde itiraz etmemiştir. Daha sonra faturadaki miktarı hiç kabul etmediğini ileri sürmektedir. TTK m.21/2'nin doğrudan sonucu hangisidir?",
        "focus": "Fatura alıcısının sekiz günlük süre içinde faturanın içeriğine itiraz etmemesine Kanun hangi sonucu bağlamıştır?",
        "correct": "Süresinde itiraz etmeyen fatura alıcısı, faturanın içeriğini kabul etmiş sayılır",
        "distractors": [
            "Fatura kendiliğinden hükümsüz hâle gelir ve yeniden düzenlenmesi gerekir",
            "Fatura içeriği yalnız satıcı yönünden bağlayıcı olur, alıcıyı hiç etkilemez",
            "Borç derhâl sona erer ve faturada yazılı bedel ödenmiş kabul edilir",
            "Fatura ticaret siciline tescil edilmiş bir mahkeme kararı niteliği kazanır",
        ],
        "focus_distractors": [
            "Fatura iptal edilmiş ve taraflar arasındaki sözleşme sona ermiş sayılır",
            "Faturada yazılı bedel kendiliğinden tahsil edilmiş kabul edilir",
            "Alıcı faturayı düzenleyen tacirin ortağı hâline gelmiş sayılır",
            "Fatura hiçbir delil değeri taşımayan sıradan bir yazıya dönüşür",
        ],
        "why": "TTK m.21/2, faturayı alan kişinin sekiz gün içinde içeriğe itiraz etmemesi hâlinde bu içeriği kabul etmiş sayılacağını düzenler. Hüküm ödeme yapılmış sayılması sonucunu doğurmaz.",
        "focus_why": "Süresinde itiraz etmemenin kanuni sonucu fatura içeriğinin kabul edilmiş sayılmasıdır. Bu sonuç, borcun ifa edildiği veya faturanın ilam olduğu anlamına gelmez.",
        "ref": "6102 sayılı TTK m.21/2",
        "difficulty": "easy",
    },
    {
        "scenario": "Taraflar telefon görüşmesinde sözleşmenin temel şartlarını kararlaştırmıştır. Taraflardan biri, görüşmede yapılan açıklamaları doğrulayan yazıyı diğerine göndermiştir. Bu yazı TTK m.21/3 bakımından nasıl nitelendirilir?",
        "focus": "Telefonla veya sözlü olarak kurulan sözleşme ve yapılan açıklamaların içeriğini sonradan doğrulayan yazının ticaret hukukundaki adı nedir?",
        "correct": "Önceki sözleşme veya açıklamaları doğrulayan teyit mektubudur",
        "distractors": [
            "Ticari işletmenin kuruluşunu gösteren ticaret sicili tasdiknamesidir",
            "Borcun ödendiğini kesin olarak gösteren kıymetli evrak niteliğinde makbuzdur",
            "Tarafların ortak şirket kurduğunu gösteren kuruluş sözleşmesidir",
            "Yalnız malın ayıplı olduğunu bildirmeye yarayan ayıp ihbarıdır",
        ],
        "focus_distractors": [
            "Ticaret unvanının tescil edildiğini gösteren sicil ilanıdır",
            "Alacağın devrini sağlayan kambiyo senedi niteliğinde belgedir",
            "İşletmenin kapanışını bildiren terkin beyannamesidir",
            "Yalnız ödenmiş bedeli gösteren perakende satış makbuzudur",
        ],
        "why": "TTK m.21/3, telefon, iletişim veya bilişim aracı ya da sözlü şekilde kurulan sözleşme ve açıklamaların içeriğini doğrulayan yazıyı teyit mektubu olarak düzenler.",
        "focus_why": "Teyit mektubu, önceden kurulan sözleşmenin veya yapılan açıklamaların içeriğini sonradan doğrulamaya yarar; yeni bir ticari işletme kuran sicil belgesi değildir.",
        "ref": "6102 sayılı TTK m.21/3",
        "difficulty": "easy",
    },
    {
        "scenario": "Teyit mektubunu 5 Nisan'da alan taraf, mektuptaki içeriğin telefon görüşmesine uymadığını 14 Nisan'da bildirmiştir. Süreyi etkileyen başka bir durum yoktur. Kanuni sonuç bakımından hangisi doğrudur?",
        "focus": "Teyit mektubunu alan kişinin, mektubun sözleşme veya açıklamalara uygun sayılmasını önlemek için kaç gün içinde itiraz etmesi gerekir?",
        "correct": "Teyit mektubunun alınmasından itibaren sekiz gün içinde itiraz edilmelidir",
        "distractors": [
            "Telefon görüşmesinin yapıldığı tarihten itibaren iki gün içinde itiraz edilmelidir",
            "Teyit mektubunun yazıldığı tarihten itibaren on beş gün içinde itiraz edilmelidir",
            "Sözleşmenin ifa tarihinden itibaren otuz gün içinde itiraz edilmelidir",
            "Teyit mektubuna itiraz için Kanunda herhangi bir süre bulunmamaktadır",
        ],
        "focus_distractors": [
            "Sözlü açıklamanın yapıldığı tarihten itibaren iki gün içinde",
            "Mektubun gönderildiği tarihten itibaren yedi gün içinde",
            "Sözleşme bedelinin ödendiği tarihten itibaren on beş gün içinde",
            "Taraflardan birinin dava açtığı tarihten itibaren otuz gün içinde",
        ],
        "why": "TTK m.21/3'te teyit mektubuna itiraz süresi alındığı tarihten itibaren sekiz gündür. Olayda dokuzuncu günde bildirilen itiraz kanuni süreden sonradır.",
        "focus_why": "Teyit mektubunda da fatura gibi sekiz günlük süre vardır ve başlangıç mektubun alındığı tarihtir. Süresinde itiraz, uygunluk karinesinin doğmasını önler.",
        "ref": "6102 sayılı TTK m.21/3",
        "difficulty": "medium",
    },
    {
        "scenario": "Teyit mektubunu alan kişi, aldığı tarihten itibaren sekiz gün içinde herhangi bir itirazda bulunmamıştır. TTK m.21/3 uyarınca doğrudan hangi sonuç ortaya çıkar?",
        "focus": "Teyit mektubuna kanuni süresinde itiraz edilmemesinin sonucu aşağıdakilerden hangisidir?",
        "correct": "Mektubun önceki sözleşme veya açıklamalara uygun olduğu kabul edilmiş sayılır",
        "distractors": [
            "Taraflar arasındaki sözleşme kendiliğinden sona ermiş ve hükümsüz sayılır",
            "Mektupta belirtilen bütün borçlar ödenmiş ve ibra edilmiş kabul edilir",
            "Mektup mahkeme ilamı niteliği kazanır ve doğrudan icraya konulabilir",
            "Mektubu gönderen taraf tacir sıfatını kaybetmiş kabul edilir",
        ],
        "focus_distractors": [
            "Mektup iptal edilir ve önceki sözlü açıklamaların tamamı yok sayılır",
            "Sözleşmenin bütün edimleri kendiliğinden ifa edilmiş kabul edilir",
            "Mektup yalnız göndereni bağlar ve alıcı bakımından hiçbir sonuç doğurmaz",
            "Tarafların ticari işletmeleri tek bir işletme hâlinde birleşmiş sayılır",
        ],
        "why": "Sekiz gün içinde itiraz edilmezse, TTK m.21/3 gereğince teyit mektubunun yapılan sözleşmeye veya açıklamalara uygun olduğu kabul edilmiş sayılır.",
        "focus_why": "Kanuni sonuç mektubun önceki mutabakata uygunluğunun kabul edilmiş sayılmasıdır. Bu, borcun ödendiği veya belgenin ilam niteliği kazandığı anlamına gelmez.",
        "ref": "6102 sayılı TTK m.21/3",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacir sıfatını taşıyan borçlu, ticari sözleşmede kararlaştırılan cezanın aşırı olduğunu ileri sürerek yalnız bu gerekçeyle mahkemeden indirim istemiştir. TTK m.22 bakımından hangisi doğrudur?",
        "focus": "Tacir sıfatını haiz borçlunun, Kanunda belirtilen hâllerde aşırı sözleşme cezasına dayanarak mahkemeden indirim istemesi bakımından hangi kural uygulanır?",
        "correct": "Tacir borçlu, aşırılık gerekçesiyle sözleşme cezasında indirim isteyemez",
        "distractors": [
            "Tacir borçlu, cezanın tamamını her durumda tek taraflı iradesiyle kaldırabilir",
            "Tacir borçlu, hiçbir gerekçe göstermeden cezanın yarıya indirilmesini isteyebilir",
            "Sözleşme cezası tacirler bakımından kanunen geçersiz olduğu için uygulanamaz",
            "Ceza ancak alacaklının da tacir olmaması hâlinde mahkemece artırılabilir",
        ],
        "focus_distractors": [
            "Mahkeme tacirin talebi üzerine cezanın tamamını zorunlu olarak kaldırır",
            "Tacir borçlu her durumda cezanın kanuni yarısına indirilmesini isteyebilir",
            "Sözleşme cezası tacir borçlu yönünden baştan itibaren hükümsüzdür",
            "İndirim yasağı yalnız borçlunun tacir olmadığını ispatlaması hâlinde uygulanır",
        ],
        "why": "TTK m.22, tacir sıfatını haiz borçlunun belirtilen TBK hükümlerindeki hâllerde aşırı ücret veya ceza iddiasıyla sözleşme cezasının indirilmesini isteyemeyeceğini düzenler.",
        "focus_why": "Tacire özgü sonuç, salt aşırılık iddiasına dayanan indirim talebinin kapalı olmasıdır. Hüküm sözleşme cezasını kendiliğinden geçersiz kılmaz.",
        "ref": "6102 sayılı TTK m.22",
        "difficulty": "medium",
    },
    {
        "scenario": "İki tacir arasındaki mal satımında uyuşmazlık çıkmıştır. TTK m.23'teki özel düzenlemelerin dışında kalan bir konu için hangi hükümlere başvurulacağı tartışılmaktadır. Hangisi doğrudur?",
        "focus": "Tacirler arasındaki satış ve mal değişimlerinde TTK m.23'ün özel hükümleri saklı kalmak üzere kural olarak hangi kanunun ilgili hükümleri uygulanır?",
        "correct": "Türk Borçlar Kanununun satış ve mal değişimi hükümleri uygulanır",
        "distractors": [
            "Yalnız Vergi Usul Kanununun belge düzenine ilişkin hükümleri uygulanır",
            "Yalnız İcra ve İflas Kanununun iflas yoluna ilişkin hükümleri uygulanır",
            "Yalnız Sermaye Piyasası Kanununun halka arza ilişkin hükümleri uygulanır",
            "Yalnız İş Kanununun ücret ve çalışma süresine ilişkin hükümleri uygulanır",
        ],
        "focus_distractors": [
            "Vergi Usul Kanununun tarh ve tahakkuka ilişkin hükümleri",
            "İcra ve İflas Kanununun konkordatoya ilişkin hükümleri",
            "Sermaye Piyasası Kanununun ihraç hükümleri",
            "İş Kanununun iş sözleşmesi ve çalışma koşullarına ilişkin hükümleri",
        ],
        "why": "TTK m.23/1, maddede yer alan özel hükümler saklı kalmak üzere tacirler arasındaki satış ve mal değişimlerinde TBK'nın satış ve mal değişimi hükümlerine gönderme yapar.",
        "focus_why": "Ticari satışa özgü TTK hükümleri öncelikle uygulanır; bunların dışında kalan alanlarda TBK'nın satış ve mal değişimi sözleşmesi düzeni devreye girer.",
        "ref": "6102 sayılı TTK m.23/1",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacirler arasındaki satış sözleşmesi niteliği gereği kısım kısım ifa edilebilir durumdadır. Satıcı yalnız son partiyi teslim etmemiş, bu eksiklik sözleşmenin genel amacını etkilememiştir. Alıcının hakları bakımından hangisi doğrudur?",
        "focus": "Kısım kısım yerine getirilmesi mümkün ticari satışta yalnız bir bölüm teslim edilmemiş ve sözleşmenin amacı zayıflamamışsa alıcı kural olarak haklarını hangi kısım için kullanabilir?",
        "correct": "Alıcı haklarını kural olarak yalnız teslim edilmeyen kısım için kullanabilir",
        "distractors": [
            "Alıcı hiçbir hak kullanamaz ve eksik teslimi kesin olarak kabul etmiş sayılır",
            "Alıcı her durumda sözleşmenin tamamını geçmişe etkili olarak hükümsüz kılabilir",
            "Alıcı yalnız teslim edilmiş kısımları satıcıya bedelsiz bırakmak zorundadır",
            "Alıcı haklarını ancak ticaret sicilinden önceden izin alarak kullanabilir",
        ],
        "focus_distractors": [
            "Alıcı bütün sözleşmeyi her durumda ve gerekçe göstermeden feshedebilir",
            "Alıcı teslim edilmeyen kısım yönünden hiçbir talepte bulunamaz",
            "Alıcı yalnız daha önce teslim edilmiş kısımlar hakkında hak kullanabilir",
            "Alıcı haklarını kullanmak için satıcının yazılı onayını almak zorundadır",
        ],
        "why": "TTK m.23/1-a uyarınca kısmi ifa mümkünse ve yalnız bir kısım yerine getirilmemişse alıcı kural olarak haklarını teslim edilmemiş kısım hakkında kullanır.",
        "focus_why": "Sözleşmenin beklenen yararı veya amacı etkilenmiyorsa eksiklik bütün sözleşmeye yayılmaz. Kanuni temel sonuç, hakların teslim edilmeyen kısma yönelmesidir.",
        "ref": "6102 sayılı TTK m.23/1-a",
        "difficulty": "medium",
    },
    {
        "scenario": "Kısım kısım ifa edilen ticari satışta teslim edilmeyen parça yüzünden bütün üretim hattı çalışamaz hâle gelmiş ve sözleşmeden beklenen yarar ortadan kalkmıştır. Alıcının sözleşmeyi feshetmesi bakımından hangisi doğrudur?",
        "focus": "Ticari satışta bir kısmın teslim edilmemesi nedeniyle sözleşmeden beklenen yararın elde edilmesi imkânı ortadan kalkıyorsa alıcı hangi imkâna sahip olabilir?",
        "correct": "Sözleşmeden beklenen yarar ortadan kalktığı için alıcı sözleşmeyi feshedebilir",
        "distractors": [
            "Alıcı yalnız teslim edilmeyen parçanın faturasına itiraz edebilir, fesih hakkı doğmaz",
            "Alıcı her durumda kalan teslimleri beklemek zorundadır ve başka hak kullanamaz",
            "Alıcı ancak satıcı iflas ettikten sonra sözleşmenin tamamını feshedebilir",
            "Alıcının fesih hakkı için eksik parçanın bedelinin toplam bedelden fazla olması gerekir",
        ],
        "focus_distractors": [
            "Alıcı eksik kısmın sözleşmenin amacına etkisine bakılmaksızın beklemek zorundadır",
            "Alıcı yalnız teslim edilmiş malları bedelsiz edinme hakkına sahip olur",
            "Alıcı sözleşmeyi ancak satıcının yazılı kabulüyle sona erdirebilir",
            "Alıcı eksik teslim nedeniyle yalnız ticaret siciline şikâyette bulunabilir",
        ],
        "why": "TTK m.23/1-a, teslim edilmeyen kısım yüzünden beklenen yararın veya izlenen amacın ortadan kalkması ya da zayıflaması hâlinde alıcıya sözleşmeyi feshetme imkânı tanır.",
        "focus_why": "Kısmi eksiklik bütün sözleşmenin ekonomik amacını bozuyorsa haklar yalnız eksik kısımla sınırlanmaz. Alıcı Kanunda belirtilen durumda sözleşmeyi feshedebilir.",
        "ref": "6102 sayılı TTK m.23/1-a",
        "difficulty": "hard",
    },
    {
        "scenario": "Tacirler arasındaki satışta alıcı teslim almada temerrüde düşmüştür. Satıcı malın satılarak elden çıkarılmasını istemektedir. TTK m.23/1-b uyarınca satıcının başvuracağı yol hangisidir?",
        "focus": "Ticari satışta alıcı mütemerrit olduğunda satıcı, malın satışı konusunda öncelikle kimden izin isteyebilir?",
        "correct": "Satıcı malın satışına izin verilmesini görevli mahkemeden isteyebilir",
        "distractors": [
            "Satıcı hiçbir izne gerek olmadan malı dilediği kişiye bağışlamak zorundadır",
            "Satıcı yalnız ticaret sicili müdürlüğünden satış ruhsatı isteyebilir",
            "Satıcı malı imha etmek için vergi dairesinden karar almak zorundadır",
            "Satıcı yalnız alıcının noter onayıyla malı yeniden satışa çıkarabilir",
        ],
        "focus_distractors": [
            "Yalnız alıcının bağlı bulunduğu meslek odasından",
            "Sadece ticaret sicili müdürlüğünden",
            "Doğrudan vergi dairesi başkanlığından",
            "Satıcının kendi muhasebecisinden",
        ],
        "why": "TTK m.23/1-b, alıcının temerrüdü hâlinde satıcının malın satışına izin verilmesini mahkemeden isteyebileceğini düzenler.",
        "focus_why": "Satış izni konusunda yetkili merci mahkemedir. Mahkeme açık artırma veya yetkilendirilen kişi aracılığıyla satış yöntemlerinden birine karar verebilir.",
        "ref": "6102 sayılı TTK m.23/1-b",
        "difficulty": "medium",
    },
    {
        "scenario": "Alıcının temerrüdü üzerine mahkeme malın satışına izin vermiştir. Satış giderleri düşüldükten sonra para artmış; satıcının takas edebileceği bir alacağı da bulunmamaktadır. Artan tutar için hangisi yapılmalıdır?",
        "focus": "Alıcının temerrüdü nedeniyle satılan maldan, satış giderleri çıkarıldıktan sonra artan para satıcının takas hakkı saklı kalmak üzere nereye bırakılır?",
        "correct": "Satış fazlası alıcı adına bankaya, banka yoksa notere bırakılıp alıcıya hemen bildirilir",
        "distractors": [
            "Artan paranın tamamı satıcının ek kazancı sayılarak kendisine bırakılır",
            "Artan para ticaret sicili müdürlüğünün bütçesine kesin gelir kaydedilir",
            "Artan para herhangi bir bildirim yapılmadan satış görevlisine ücret olarak verilir",
            "Artan para alıcı adına vergi dairesine süresiz teminat olarak yatırılır",
        ],
        "focus_distractors": [
            "Satıcının serbestçe kullanacağı kişisel hesabına kesin olarak aktarılır",
            "Ticaret sicili müdürlüğüne gelir kaydedilir ve alıcıya bildirilmez",
            "Satışı yapan kişinin ücreti olarak kendisine bırakılır",
            "Alıcının meslek odasına aidat karşılığı teslim edilir",
        ],
        "why": "TTK m.23/1-b gereğince giderlerden sonra artan para, satıcının takas hakkı saklı olmak üzere alıcı adına bankaya; banka yoksa notere bırakılır ve durum hemen alıcıya ihbar edilir.",
        "focus_why": "Satış fazlası satıcının kazancı değildir. Kanun bu tutarın alıcı adına güvenli bir yere bırakılmasını ve alıcının gecikmeden haberdar edilmesini öngörür.",
        "ref": "6102 sayılı TTK m.23/1-b",
        "difficulty": "hard",
    },
    {
        "scenario": "Tacirler arasındaki satışta malın ayıbı teslim anında açıkça görülmektedir. Alıcı, ayıba ilişkin haklarını korumak istemektedir. Satıcıya ihbar süresi bakımından hangisi doğrudur?",
        "focus": "Ticari satışta malın ayıplı olduğu teslim sırasında açıkça belli ise alıcı durumu satıcıya hangi süre içinde ihbar etmelidir?",
        "correct": "Alıcı açıkça belli ayıbı iki gün içinde satıcıya bildirmelidir",
        "distractors": [
            "Alıcı açıkça belli ayıp için sekiz gün içinde yalnız mahkemeye başvurmalıdır",
            "Alıcı açık ayıbı otuz gün içinde ticaret siciline tescil ettirmelidir",
            "Alıcının açıkça belli ayıp için satıcıya bildirim yapmasına gerek yoktur",
            "Alıcı açık ayıbı ancak ödeme vadesinde noter aracılığıyla bildirebilir",
        ],
        "focus_distractors": [
            "Teslimden itibaren sekiz gün içinde yalnız ticaret siciline",
            "Ödeme gününden itibaren on beş gün içinde mahkemeye",
            "Sözleşme tarihinden itibaren otuz gün içinde meslek odasına",
            "Herhangi bir süreye bağlı olmadan yalnız vergi dairesine",
        ],
        "why": "TTK m.23/1-c uyarınca teslim sırasında açıkça belli olan ayıp, alıcı tarafından iki gün içinde satıcıya ihbar edilmelidir.",
        "focus_why": "Açık ayıp teslim anında fark edilebilir niteliktedir ve buna özgü kısa ihbar süresi iki gündür. Sekiz günlük inceleme süresi açıkça belli olmayan ayıplara ilişkindir.",
        "ref": "6102 sayılı TTK m.23/1-c",
        "difficulty": "easy",
    },
    {
        "scenario": "Tacirler arasındaki satışta ayıp teslim sırasında açıkça belli değildir; olağan bir incelemeyle ortaya çıkabilecek niteliktedir. Alıcının yükümlülüğü bakımından hangisi doğrudur?",
        "focus": "Ticari satışta teslim sırasında açıkça belli olmayan ancak incelemeyle ortaya çıkabilecek ayıp bakımından alıcı ne yapmalıdır?",
        "correct": "Alıcı sekiz günde malı inceleyip ayıp çıkarsa bu sürede satıcıya bildirmelidir",
        "distractors": [
            "Alıcı malı incelemeden iki yıl bekleyebilir ve sonra yalnız sicile bildirim yapabilir",
            "Alıcı inceleme yapmasa da bütün ayıpları süresiz olarak ileri sürebilir",
            "Alıcı yalnız faturaya itiraz ederek ayıp ihbarı yükümlülüğünü yerine getirmiş olur",
            "Alıcı ayıbı ancak bağımsız denetçi raporuyla ve otuz gün içinde bildirebilir",
        ],
        "focus_distractors": [
            "Malı incelemeden ödeme vadesine kadar beklemeli ve yalnız faturayı iade etmelidir",
            "İki gün içinde doğrudan ticaret siciline tescil başvurusu yapmalıdır",
            "Otuz gün içinde meslek odasından ayıp belgesi alarak satıcıya göndermelidir",
            "Herhangi bir inceleme veya ihbar yükümlülüğü olmadan süresiz bekleyebilir",
        ],
        "why": "TTK m.23/1-c, açıkça belli olmayan ayıpta alıcıya teslimden itibaren sekiz gün içinde inceleme veya incelettirme ve ayıp çıkarsa bu süre içinde satıcıya ihbar yükümlülüğü getirir.",
        "focus_why": "Olağan incelemeyle ortaya çıkabilecek gizli olmayan ayıp için hem inceleme hem ihbar sekiz günlük ticari süre içinde yerine getirilmelidir.",
        "ref": "6102 sayılı TTK m.23/1-c",
        "difficulty": "medium",
    },
]


PREMISES = [
    {
        "stem": "Tacir olmanın genel sonuçlarıyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tacir her türlü borcu için iflasa tabidir.\n\nII. Tacir ticaretine ait faaliyetlerinde basiretli bir iş insanı gibi davranmalıdır.\n\nIII. Tacir kanuna uygun ticaret unvanı seçmekle yükümlüdür.",
        "correct": "I, II ve III",
        "why": "TTK m.18/1 tacirin her türlü borcu için iflasa tabi olmasını ve ticaret unvanı seçmesini; m.18/2 ise ticaretine ait faaliyetlerde basiretli davranmasını düzenler. Üç ifade de doğrudur.",
        "ref": "6102 sayılı TTK m.18/1-2",
        "difficulty": "medium",
    },
    {
        "stem": "Tacirler arasında TTK m.18/3 kapsamındaki bildirim yöntemleriyle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Noter aracılığıyla bildirim yapılabilir.\n\nII. Taahhütlü mektup kullanılabilir.\n\nIII. Güvenli elektronik imza içermeyen sıradan e-posta maddede açıkça sayılmıştır.",
        "correct": "I ve II",
        "why": "Noter ve taahhütlü mektup m.18/3'te sayılır. Elektronik yöntem olarak ise sıradan e-posta değil, güvenli elektronik imza kullanılarak kayıtlı elektronik posta sistemi belirtilmiştir.",
        "ref": "6102 sayılı TTK m.18/3",
        "difficulty": "medium",
    },
    {
        "stem": "Ticari iş karinesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tacirin borçlarının ticari olması asıldır.\n\nII. Gerçek kişi tacirin işlem anındaki açık bildirimi borcun adi sayılmasına yol açabilir.\n\nIII. İşin ticari sayılmasına durumun elverişli olmaması gerçek kişi tacir bakımından dikkate alınır.",
        "correct": "I, II ve III",
        "why": "TTK m.19/1 ticari iş karinesini ve gerçek kişi tacir için iki istisnayı birlikte düzenler: işlem anındaki açık bildirim ile işin ticari sayılmasına durumun elverişli olmaması.",
        "ref": "6102 sayılı TTK m.19/1",
        "difficulty": "hard",
    },
    {
        "stem": "Tacirin ücret ve faiz isteme hakkıyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İş veya hizmet tacirin ticari işletmesiyle ilgili olmalıdır.\n\nII. Hizmetten yararlananın mutlaka tacir olması gerekir.\n\nIII. Tacir, yaptığı giderler için ödeme tarihinden itibaren faiz isteyebilir.",
        "correct": "I ve III",
        "why": "TTK m.20'de işin tacirin ticari işletmesiyle ilgili olması aranır ve gider için ödeme tarihinden itibaren faiz tanınır. Muhatap tacir olan veya olmayan kişi olabilir; II yanlıştır.",
        "ref": "6102 sayılı TTK m.20",
        "difficulty": "medium",
    },
    {
        "stem": "Fatura ve teyit mektubuyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Fatura içeriğine itiraz süresi faturanın alınmasından itibaren sekiz gündür.\n\nII. Teyit mektubuna itiraz süresi mektubun alınmasından itibaren sekiz gündür.\n\nIII. Her iki belgeye süresinde itiraz edilmemesi borcun ödendiği anlamına gelir.",
        "correct": "I ve II",
        "why": "TTK m.21/2-3 her iki belge için de alınma tarihinden başlayan sekiz günlük itiraz süresi öngörür. Sessizlik içerik veya uygunluk karinesi doğurur; borcun ödendiği sonucunu doğurmaz.",
        "ref": "6102 sayılı TTK m.21/2-3",
        "difficulty": "medium",
    },
    {
        "stem": "Tacir borçlunun sözleşme cezası karşısındaki durumuyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. TTK m.22'de belirtilen hâllerde yalnız aşırılık iddiasıyla indirim isteyemez.\n\nII. Hüküm, sözleşme cezasını tacir bakımından baştan itibaren geçersiz kılar.\n\nIII. Tacir, cezanın yarıya indirilmesini gerekçesiz biçimde talep edebilir.",
        "correct": "Yalnız I",
        "why": "TTK m.22'nin sonucu, tacir borçlunun belirtilen hâllerde salt aşırılık iddiasıyla indirim isteyememesidir. Ceza kendiliğinden geçersiz olmaz ve gerekçesiz yarı indirim hakkı doğmaz.",
        "ref": "6102 sayılı TTK m.22",
        "difficulty": "medium",
    },
    {
        "stem": "Tacirler arasındaki kısmi teslimli satışla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kısmi ifa mümkünse haklar kural olarak teslim edilmeyen kısım için kullanılır.\n\nII. Eksiklik sözleşmenin amacını ortadan kaldırırsa alıcı fesih imkânına sahip olabilir.\n\nIII. Her kısmi eksiklikte bütün sözleşme kendiliğinden hükümsüz olur.",
        "correct": "I ve II",
        "why": "TTK m.23/1-a hakları kural olarak teslim edilmeyen kısımla sınırlar; ancak beklenen yarar veya amaç ortadan kalkar ya da zayıflarsa feshe izin verir. Otomatik hükümsüzlük yoktur.",
        "ref": "6102 sayılı TTK m.23/1-a",
        "difficulty": "hard",
    },
    {
        "stem": "Ticari satışta ayıp ihbarıyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Teslimde açıkça belli ayıp sekiz gün içinde ihbar edilmelidir.\n\nII. Açıkça belli olmayan ayıpta sekiz gün içinde inceleme yükümlülüğü vardır.\n\nIII. İncelemede ayıp çıkarsa hakları korumak için aynı süre içinde satıcıya ihbar gerekir.",
        "correct": "II ve III",
        "why": "Açıkça belli olmayan ayıpta sekiz günlük inceleme ve aynı süre içinde ihbar yükümlülüğü bulunduğundan II ve III doğrudur. Açıkça belli ayıp için süre sekiz değil iki gündür; I yanlıştır.",
        "ref": "6102 sayılı TTK m.23/1-c",
        "difficulty": "hard",
    },
]


# Bu builder bütün çeldiricileri kural düzeyinde tanımlar; ortak banka kullanılmaz.
WRONG_BANKS = {"unused": ["a", "b", "c", "d", "e", "f"]}


if __name__ == "__main__":
    write_topic(
        lesson_id="ticaret_hukuku",
        topic_id="tacir_yukumluluklari",
        label="Tacir ve Yükümlülükleri",
        slug="tacir_yukumluluklari",
        prefix="kh-tacir-yuk",
        seed=20260721,
        legislation_version="6102 sayılı TTK — 17.07.2026 güncel metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks=WRONG_BANKS,
    )
