#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""İdari Yargıda Görev ve Yetki — 60 özgün konu havuzu sorusu."""
from topic_pack_builder import write_topic


def R(scenario, focus, correct, bank, why, ref, difficulty="medium"):
    return locals()


WRONG = {
    "merci": [
        "Uyuşmazlığın niteliğine bakılmaksızın bütün idari davaları ilk derece mahkemesi olarak Danıştay çözer",
        "İlk derece idari uyuşmazlıkların tamamı doğrudan bölge idare mahkemesinin tek hâkimince karara bağlanır",
        "Vergi, resim ve harç uyuşmazlıklarında görevli yargı yeri kural olarak genel görevli asliye hukuk mahkemesidir",
        "İdare mahkemeleri yalnız istinaf incelemesi yapar; iptal ve tam yargı davalarında ilk derece görevi bulunmaz",
        "Bölge idare mahkemesi yalnız danışma görüşü verir; istinaf başvurusu hakkında bağlayıcı karar veremez",
        "Tahkim yolu öngörülmeyen idari sözleşme uyuşmazlıkları her durumda iş mahkemesinin görev alanına girer",
        "Danıştayın temyiz görevi yerindelik denetimini de kapsar ve idarenin takdir yetkisini yeniden kullanmasına imkân verir",
        "Bir davanın vergi mahkemesinde görülmesi için taraflardan ikisinin de tacir ve uyuşmazlığın özel hukuk sözleşmesine dayalı olması gerekir",
    ],
    "yetki": [
        "Yetkili mahkeme her durumda davacının yerleşim yerindeki idare mahkemesidir; özel yetki kuralları uygulanmaz",
        "İdari davalarda yetki yalnız tarafların yapacağı sözleşmeyle belirlenir ve mahkemece kendiliğinden incelenemez",
        "Yetkili mahkeme idari işlemin uygulandığı her yerde seçimlik olarak belirlenir; işlemi yapan merciin yeri önem taşımaz",
        "Kamu görevlisine ilişkin bütün davalarda yetkili yer, görev yeriyle bağlantı aranmaksızın Ankara idare mahkemeleridir",
        "Taşınmazla ilgili idari davada taşınmazın bulunduğu yer yerine yalnız işlemi tebliğ eden birimin bulunduğu yer esas alınır",
        "Vergi uyuşmazlığında yetki, tarhiyatı yapan daireden bağımsız olarak mükellefin dilediği vergi mahkemesine aittir",
        "Tam yargı davasında zarar veya eylem yeri dikkate alınmaz; yalnız davalı idarenin merkezindeki mahkeme yetkilidir",
        "Yetki kamu düzeninden olmadığından davalı ilk itirazda bulunmazsa yetkisizlik hiçbir aşamada değerlendirilemez",
    ],
    "uyusmazlik": [
        "Aynı yargı çevresindeki idare ve vergi mahkemeleri arasındaki görev uyuşmazlığını ilk derece hukuk mahkemesi kesin çözer",
        "Mahkemeler arasındaki yetki tereddüdünde taraflar ortak bir mahkeme seçmedikçe dava kendiliğinden sona erer",
        "Bağlantı yalnız tarafların ve taleplerin tamamen aynı olması hâlinde kabul edilir; hukuki sebep ortaklığı yeterli değildir",
        "Görevsizlik kararı verildiğinde dosya hiçbir koşulda görevli idari yargı yerine gönderilemez ve yeniden dava açılamaz",
        "Merci tayini kararı yalnız tavsiye niteliğindedir; belirlenen mahkeme görevsizlik kararı vermekte serbesttir",
        "Farklı bölge idare mahkemesi çevrelerindeki yetki uyuşmazlığını uyuşmazlığa taraf belediye meclisi karara bağlar",
        "Bir davadaki hükmün diğer davayı etkilemesi bağlantı oluşturmaz; mutlaka dava konularının kelimesi kelimesine aynı olması gerekir",
        "Mahkeme görev ve yetkiyi yalnız tarafların açık talebi üzerine inceler; dosya üzerinden kendiliğinden inceleme yapamaz",
    ],
}


RULES = [
    R("Bir idare mahkemesi kararına karşı olağan istinaf başvurusu yapılmıştır. Başvuruyu hangi merci inceler?", "Bölge idare mahkemesinin temel yargısal görevi aşağıdakilerden hangisidir?", "İstinaf başvurusunu bölge idare mahkemesi inceler", "merci", "Bölge idare mahkemeleri, yargı çevrelerindeki idare ve vergi mahkemesi kararlarına yönelik istinaf başvurularını karara bağlar.", "2576 sayılı Kanun m.3/A", "easy"),
    R("Bir uyuşmazlık vergi mahkemesinin veya Danıştayın ilk derece görevi kapsamında değildir ve idari işlemin iptali istenmektedir. Görevli mahkeme hangisidir?", "İdare mahkemelerinin genel ilk derece görevi bakımından doğru ifade hangisidir?", "İdare mahkemesi görevlidir", "merci", "İdare mahkemeleri; vergi mahkemesi ve Danıştayın ilk derece görevine girenler dışındaki iptal ve tam yargı davalarını çözer.", "2576 sayılı Kanun m.5", "easy"),
    R("Belediyeye ait bir harcın tarhı ve cezasına karşı dava açılacaktır. Uyuşmazlık hangi ilk derece mahkemesinin görevine girer?", "Vergi mahkemelerinin görev alanını doğru gösteren seçenek hangisidir?", "Vergi mahkemesi görevlidir", "merci", "Vergi, resim, harç ve benzeri mali yükümler ile bunların zam ve cezalarına ilişkin davalar vergi mahkemesinde görülür.", "2576 sayılı Kanun m.6", "easy"),
    R("Bir bakanlığın ülke çapında uygulanacak düzenleyici işlemine karşı iptal davası açılacaktır. İlk derece mahkemesi hangisidir?", "Danıştayın ilk derece görevlerinden biri aşağıdakilerden hangisidir?", "Dava ilk derece olarak Danıştayda görülür", "merci", "Bakanlıkların ülke çapında uygulanacak düzenleyici işlemlerine karşı davalar Danıştayda ilk derece olarak görülür.", "2575 sayılı Danıştay Kanunu m.24/1-c"),
    R("Bir Cumhurbaşkanı kararının iptali istenmektedir. Davanın ilk derece yargı yeri nasıl belirlenir?", "Cumhurbaşkanı kararlarına karşı açılan idari davalarda görevli ilk derece mercii hangisidir?", "İlk derece görevi Danıştaya aittir", "merci", "Cumhurbaşkanı kararlarına karşı iptal ve tam yargı davaları Danıştayın ilk derece görevleri arasındadır.", "2575 sayılı Danıştay Kanunu m.24/1-a"),
    R("Dava konusu işlem birden çok idare mahkemesinin yetki alanına girmektedir. İlk derece görevi hangi mercidedir?", "Birden çok idare veya vergi mahkemesinin yetki alanına giren işlerde görevli ilk derece mercii hangisidir?", "İlk derece incelemesini Danıştay yapar", "merci", "Birden çok idare veya vergi mahkemesinin yetki alanına giren işler Danıştayda ilk derece olarak görülür.", "2575 sayılı Danıştay Kanunu m.24/1-e", "hard"),
    R("Tahkim yolu öngörülmeyen bir kamu hizmeti imtiyaz sözleşmesinden idari uyuşmazlık doğmuştur. Yargılamayı hangi merci yapar?", "Tahkimsiz kamu hizmeti imtiyaz sözleşmelerinden doğan idari davalarda görevli merci hangisidir?", "Dava Danıştayda görülür", "merci", "Tahkim yolu öngörülmeyen kamu hizmeti imtiyaz şartlaşma ve sözleşmelerinden doğan idari davalar Danıştayın ilk derece görevindedir.", "2575 sayılı Danıştay Kanunu m.24"),
    R("İdare mahkemesi görevsizlik kararıyla dosyayı aynı yargı çevresindeki vergi mahkemesine göndermiş; vergi mahkemesi de kendisini görevsiz görmüştür. Uyuşmazlığı kim çözer?", "Aynı yargı çevresindeki idare ve vergi mahkemeleri arasındaki görev ve yetki uyuşmazlığını hangi merci çözer?", "İlgili bölge idare mahkemesi çözer", "uyusmazlik", "Dosyanın gönderildiği mahkeme de kendisini görevsiz görür ve iki mahkeme aynı bölge idare mahkemesinin yargı çevresinde bulunursa uyuşmazlığı o bölge idare mahkemesi kesin olarak çözer.", "2576 sayılı Kanun m.3/A-b; 2577 sayılı İYUK m.43/1-b"),
    R("Kanunda özel bir yetki kuralı bulunmayan idari işleme karşı dava açılacaktır. İşlemi yapan merci Konya'dadır. Yetkili yer neresidir?", "İYUK'taki genel yetki kuralı aşağıdakilerden hangisidir?", "İşlemi yapan merciin bulunduğu yer mahkemesi", "yetki", "Özel yetki kuralı yoksa yetkili idare mahkemesi, dava konusu işlemi veya sözleşmeyi yapan idari merciin bulunduğu yerdedir.", "2577 sayılı İYUK m.32", "easy"),
    R("İdari sözleşmeyi yapan idari merci İzmir'dedir ve özel kanunda farklı yetki belirlenmemiştir. Dava nerede açılır?", "İdari sözleşmeden doğan davada özel hüküm yoksa genel yetki hangi bağlantıya dayanır?", "Sözleşmeyi yapan merciin bulunduğu yere", "yetki", "İYUK m.32, işlem yanında idari sözleşmeyi yapan merciin bulunduğu yeri de genel yetki ölçütü kabul eder.", "2577 sayılı İYUK m.32"),
    R("Kamu görevlisinin Ankara'dan Bursa'ya nakline karşı dava açılacaktır. Yetkili mahkeme nasıl belirlenir?", "Atama ve nakil davalarında kamu görevlisine tanınan yetki seçeneği hangisidir?", "Yeni veya eski görev yeri mahkemesi", "yetki", "Atama ve nakille ilgili davalar yeni veya eski görev yeri idare mahkemesinde açılabilir.", "2577 sayılı İYUK m.33/1"),
    R("Görevine son verilen kamu görevlisi son olarak Eskişehir'de çalışmıştır. Özel hüküm yoksa yetkili mahkeme neresidir?", "Göreve son verme ve emeklilik işlemlerinde yetkili idare mahkemesi hangi yere göre belirlenir?", "Son görev yerindeki idare mahkemesi", "yetki", "Göreve son verme, emekli etme ve görevden uzaklaştırma davalarında son görev yeri mahkemesi yetkilidir.", "2577 sayılı İYUK m.33/2"),
    R("Görevle ilişiği kesilmeyen memura verilen disiplin cezası dava konusu yapılacaktır. Yetkili mahkeme hangisidir?", "Görevle ilişiği kesmeyen disiplin cezasına karşı davada yetki hangi yere aittir?", "Görevli bulunduğu yer idare mahkemesine", "yetki", "Görevle ilişiği kesmeyen disiplin cezalarında ilgilinin görevli bulunduğu yer idare mahkemesi yetkilidir.", "2577 sayılı İYUK m.33/3"),
    R("Bir taşınmaza ilişkin imar planı uygulaması dava konusu edilmiştir. Yetkili idare mahkemesi nerededir?", "İmar ve kamulaştırma gibi taşınmaz uyuşmazlıklarında özel yetki kuralı hangisidir?", "Taşınmazın bulunduğu yer mahkemesi", "yetki", "Taşınmaz mevzuatının uygulanmasından doğan idari davalarda taşınmazın bulunduğu yer idare mahkemesi yetkilidir.", "2577 sayılı İYUK m.34"),
    R("İdarece el konulan belirli bir taşınır mal hakkında idari dava açılacaktır. Özel yetki kuralı hangi yeri gösterir?", "Taşınır mallara ilişkin idari davalarda yetki hangi bağlantıya göre belirlenir?", "Taşınırın bulunduğu yer mahkemesine göre", "yetki", "Taşınır mallara ilişkin davalarda taşınırın bulunduğu yer idare mahkemesi yetkilidir.", "2577 sayılı İYUK m.35"),
    R("Belediyenin Antalya'da yürüttüğü yol bakım hizmetinden zarar doğmuş ve zararı doğuran ayrı bir idari işlem bulunmamıştır. Tam yargı davası nerede açılır?", "İdari eylemden doğan tam yargı davasında yetki için esas alınan yer hangisidir?", "Eylemin yapıldığı yer mahkemesi", "yetki", "Zarar bir hizmetin yürütülüşünden veya idari eylemden doğmuşsa hizmetin görüldüğü ya da eylemin yapıldığı yerdeki idare mahkemesi yetkilidir.", "2577 sayılı İYUK m.36/b"),
    R("Tam yargı davasında İYUK m.36'nın zarar doğuran uyuşmazlık ve eylem yeri ölçütleri uygulanamamaktadır. Sıradaki ölçüt nedir?", "Tam yargı davalarında diğer özel bağlantılar yoksa yetki hangi yere geçer?", "Davacının ikametgâhındaki mahkemeye", "yetki", "İdari sözleşme dışındaki tam yargı davalarında önceki özel ölçütler uygulanamazsa davacının ikametgâhı esas alınır.", "2577 sayılı İYUK m.36/c", "hard"),
    R("Bir vergi dairesinin yaptığı tarhiyat ve kestiği ceza dava konusu edilmiştir. Yetkili vergi mahkemesi nasıl belirlenir?", "Tarh ve ceza uyuşmazlığında vergi mahkemesinin yetkisi hangi dairenin yerine bağlanmıştır?", "Tarhı yapan ve cezayı kesen dairenin yerine", "yetki", "Vergi uyuşmazlığında tarh ve tahakkuk ettiren ya da ceza kesen dairenin bulunduğu yer vergi mahkemesi yetkilidir.", "2577 sayılı İYUK m.37/a"),
    R("6183 sayılı Kanun uyarınca düzenlenen ödeme emrine karşı dava açılacaktır. Yetkili vergi mahkemesi nerededir?", "Ödeme emri uyuşmazlığında özel yetkiyi belirleyen idari birim hangisidir?", "Ödeme emrini düzenleyen dairenin bulunduğu yer", "yetki", "Amme alacağının takibindeki ödeme emri uyuşmazlığında emri düzenleyen dairenin bulunduğu yerdeki vergi mahkemesi yetkilidir.", "2577 sayılı İYUK m.37/c"),
    R("Aynı hukuki sebepten doğan iki idari dava farklı tarihlerde açılmıştır. İYUK bakımından bu ilişki nasıl nitelendirilir?", "İYUK'a göre bağlantılı davayı belirleyen ölçüt hangisidir?", "Davalar arasında bağlantı vardır", "uyusmazlik", "Aynı maddi veya hukuki sebepten doğan davalar, açılış tarihleri farklı olsa da İYUK anlamında bağlantılıdır.", "2577 sayılı İYUK m.38/1"),
    R("Aynı mahkemedeki iki dava arasında bağlantı bulunduğu düşünülmektedir. Mahkeme taraf talebi olmadan bağlantıyı değerlendirebilir mi?", "Bağlantının tespitinde mahkemenin kendiliğinden hareket yetkisi var mıdır?", "Mahkeme bağlantıya resen karar verebilir", "uyusmazlik", "Bağlantının varlığına taraf istemi üzerine veya doğrudan doğruya mahkemece karar verilebilir.", "2577 sayılı İYUK m.38/2"),
    R("İki mahkeme aynı davaya bakmaya kendisini yetkili saymıştır ve aynı bölge idare mahkemesi çevresindedir. Merci tayinini kim yapar?", "Aynı yargı çevresindeki olumlu yetki uyuşmazlığında merci tayini kime aittir?", "O yargı çevresindeki bölge idare mahkemesine", "uyusmazlik", "Aynı yargı çevresindeki mahkemeler için merci tayini o bölge idare mahkemesince yapılır.", "2577 sayılı İYUK m.44/1-a"),
    R("Farklı bölge idare mahkemelerinin yargı çevrelerindeki iki mahkeme aynı davaya bakmaya kendisini yetkili saymıştır. Merci tayini nereye aittir?", "Aynı bölge idare mahkemesi çevresi dışında kalan merci tayininde görevli üst merci hangisidir?", "Danıştaya", "uyusmazlik", "Aynı yargı çevresi dışında kalan merci tayini hâllerinde görevli ve yetkili mahkemeyi Danıştay belirler.", "2577 sayılı İYUK m.44/1-b"),
    R("Adli yargıda açılan dava görev yönünden reddedilmiş ve uyuşmazlık idari yargının görevine girmektedir. Başvuru tarihinin korunması için ne yapılır?", "Adli yargının görevsizlik kararından sonra idari yargıya başvuru bakımından temel kural hangisidir?", "Kesinleşmeden sonra otuz gün içinde dava açılır", "uyusmazlik", "Görevsizlik kararının kesinleşmesini izleyen günden başlayarak otuz gün içinde görevli idari mahkemede dava açılabilir; ilk başvuru tarihi korunur.", "2577 sayılı İYUK m.9"),
    R("İdari yargı mahkemesi görev alanı dışında kalan davayı ilk incelemede saptamıştır. Görev kamu düzenine ilişkin olduğundan nasıl hareket eder?", "İdari yargıda görev incelemesinin niteliğini doğru açıklayan ifade hangisidir?", "Görev hususu resen incelenir", "uyusmazlik", "Görev ve yetki, ilk incelemede mahkemece kendiliğinden değerlendirilen usul koşullarıdır.", "2577 sayılı İYUK m.14-15"),
    R("Yetkili mahkeme davaya bakmaya hukuki engel bulunduğunu bildirmiştir. Davanın görülebilmesi için hangi kurum işletilir?", "Mahkemenin davaya bakmasına fiili veya hukuki engel çıktığında başvurulan çözüm hangisidir?", "Merci tayini yapılır", "uyusmazlik", "Yetkili mahkemenin davaya bakmasına fiili veya hukuki engel çıkarsa dosya görevli üst mercie merci tayini için gönderilir.", "2577 sayılı İYUK m.44"),
]


def V(correct, distractors, focus, focus_correct, focus_distractors, focus_why,
      focus_ref=None, focus_difficulty=None):
    """Bir kuralın iki sorusunu içerik ve çeldirici bakımından ayırır."""
    item = {
        "correct": correct,
        "distractors": distractors,
        "focus": focus,
        "focus_correct": focus_correct,
        "focus_distractors": focus_distractors,
        "focus_why": focus_why,
    }
    if focus_ref:
        item["focus_ref"] = focus_ref
    if focus_difficulty:
        item["focus_difficulty"] = focus_difficulty
    return item


VARIANTS = [
    V(
        "Başvuruyu, mahkemenin yargı çevresindeki bölge idare mahkemesi inceler",
        [
            "Başvuruyu ilk derece kararını veren idare mahkemesi yeniden inceler",
            "Başvuruyu görevli Danıştay dava dairesi doğrudan istinafen inceler",
            "Başvuruyu mahkemenin bulunduğu yerdeki asliye hukuk mahkemesi inceler",
            "Başvuruyu Hâkimler ve Savcılar Kurulunun ilgili dairesi, idari yargı hâkimlerinden oluşan kuruluyla inceler",
        ],
        "Bölge idare mahkemesinin olağan istinaf görevi hangi kararlar üzerinde doğar?",
        "Yargı çevresindeki idare ve vergi mahkemelerinin istinafa açık kararları üzerinde",
        [
            "Yalnız Danıştay İdari Dava Daireleri Kurulunun kesin kararları üzerinde",
            "Yargıtay dairelerinin idari sözleşmelere ilişkin bütün kararları üzerinde",
            "Uyuşmazlık Mahkemesinin görev uyuşmazlığına ilişkin kararları üzerinde",
            "Sayıştayın bütün denetim raporları ve görüş yazılarındaki hukuki uyuşmazlıklar üzerinde",
        ],
        "Bölge idare mahkemesi, kendi yargı çevresindeki idare ve vergi mahkemelerinin kanunen istinafa açık kararlarını inceler; yüksek mahkeme veya denetim organı kararlarını istinafen denetlemez.",
        "2576 sayılı Kanun m.3/A; 2577 sayılı İYUK m.45",
        "easy",
    ),
    V(
        "Kanunda başka bir idari yargı merciine verilmemişse idare mahkemesi görevlidir",
        [
            "İptal istemi bulunduğu için vergi mahkemesi her durumda görevlidir",
            "İdari işlem uyuşmazlıklarının tamamında Danıştay ilk derece mahkemesidir",
            "Uyuşmazlığı bölge idare mahkemesi doğrudan ilk derece sıfatıyla çözer",
            "İşlemi yapan idare, davaya bakacak yargı merciini kendi teşkilatındaki bir kurul aracılığıyla belirler",
        ],
        "İdare mahkemesinin genel görevli sayılması aşağıdaki sınırlamalardan hangisini içerir?",
        "Danıştayın ve vergi mahkemelerinin ilk derece görevine giren davalar kapsam dışındadır",
        [
            "Yalnız gerçek kişilerin açtığı davalar idare mahkemesinin kapsamı dışındadır",
            "İptal davalarının tamamı doğrudan bölge idare mahkemesinde görülür",
            "Tam yargı davaları uyuşmazlığın türüne bakılmadan adli yargıda görülür",
            "İdare mahkemesi yalnız kanun yolu incelemesi yapan ve ilk derece uyuşmazlığını hiçbir zaman çözemeyen bir üst mahkemedir",
        ],
        "2576 sayılı Kanun m.5, idare mahkemesini Danıştayın ve vergi mahkemelerinin ilk derece görevleri dışında kalan iptal, tam yargı ve idari sözleşme davalarında genel görevli kılar.",
        "2576 sayılı Kanun m.5",
        "easy",
    ),
    V(
        "Uyuşmazlık görevli vergi mahkemesinde görülür",
        [
            "Uyuşmazlık genel görevli asliye hukuk mahkemesinde görülür",
            "Uyuşmazlık doğrudan Danıştayda ilk derece olarak görülür",
            "Uyuşmazlık bölge idare mahkemesinde ilk derece olarak görülür",
            "Uyuşmazlık yalnız belediye encümenince kesin olarak çözülür",
        ],
        "Vergi mahkemesinin görev alanı 6183 sayılı Kanun uygulaması bakımından nasıl sınırlandırılmıştır?",
        "Vergi mahkemesinin görevindeki mali yükümlere ilişkin 6183 uygulaması da kapsamdadır",
        [
            "6183 sayılı Kanuna dayanan bütün özel hukuk alacakları görev alanındadır",
            "6183 uygulaması yalnız borçlunun seçtiği hukuk mahkemesinde incelenir",
            "Amme alacağının türü ne olursa olsun Danıştay ilk derece görevlisidir",
            "6183 uygulaması, uyuşmazlığın dayandığı mali yükümün türüne bakılmaksızın vergi mahkemesinin görev alanından bütünüyle çıkarılmıştır",
        ],
        "2576 sayılı Kanun m.6, maddede sayılan vergi, resim, harç ve benzeri mali yükümlere ilişkin 6183 sayılı Kanun uygulamasından doğan davaları vergi mahkemesine verir.",
        "2576 sayılı Kanun m.6",
        "medium",
    ),
    V(
        "Dava ilk derece mahkemesi sıfatıyla Danıştayda görülür",
        [
            "Dava düzenleyici işlemi yayımlayan bakanlık bünyesinde karara bağlanır",
            "Dava her durumda davacının yerleşim yerindeki idare mahkemesinde görülür",
            "Dava doğrudan bölge idare mahkemesinin tek hâkimince görülür",
            "Dava görevli asliye hukuk mahkemesinde ilk derece olarak görülür",
        ],
        "Bir bakanlığın yalnızca tek bir ilde uygulanan bireysel işlemine karşı açılan dava, sırf işlemi bakanlık yaptığı için doğrudan Danıştayda mı görülür?",
        "Hayır; özel bir görev kuralı yoksa dava genel görevli idare mahkemesinde görülür",
        [
            "Evet; bakanlıkların bütün bireysel işlemleri Danıştayın ilk derece görevindedir",
            "Evet; ancak davacının yerleşim yeri Ankara dışında bulunuyorsa görev değişir",
            "Hayır; bu tür uyuşmazlıklarda görevli merci daima vergi mahkemesidir",
            "Hayır; bakanlık işlemlerine karşı yalnız Anayasa Mahkemesine başvurulabilir",
        ],
        "Danıştay Kanunu m.24/1-c için işlemin bakanlığa ait olması tek başına yetmez; düzenleyici işlemin ülke çapında uygulanacak nitelikte olması gerekir. Aksi durumda başka özel kural yoksa idare mahkemesi genel görevlidir.",
        "2575 sayılı Danıştay Kanunu m.24/1-c; 2576 sayılı Kanun m.5",
        "hard",
    ),
    V(
        "Dava ilk derece mahkemesi olarak Danıştayda açılır",
        [
            "Dava Cumhurbaşkanlığı İdari İşler Başkanlığında kesin karara bağlanır",
            "Dava davacının seçtiği herhangi bir bölge idare mahkemesinde açılır",
            "Dava görevli sulh hukuk mahkemesinde ilk derece olarak açılır",
            "Dava yalnız işlemi uygulayan yerel idare mahkemesinde açılabilir",
        ],
        "Cumhurbaşkanı kararından doğrudan zarar gördüğünü ileri süren kişinin açacağı tam yargı davasında ilk derece görevi kime aittir?",
        "Tam yargı davasını da ilk derece mahkemesi olarak Danıştay görür",
        [
            "Tam yargı istemini yalnız Uyuşmazlık Mahkemesi karara bağlar",
            "Zarar istemi bulunduğundan dava zorunlu olarak adli yargıda görülür",
            "Tam yargı davasını bölge idare mahkemesi doğrudan ilk derece görür",
            "İptal istenmediği için başvuru yargısal inceleme dışında kalır",
        ],
        "2575 sayılı Kanun m.24/1-a, Cumhurbaşkanı kararlarına karşı açılacak iptal davalarıyla birlikte bunlardan doğan tam yargı davalarını da Danıştayın ilk derece görevine verir.",
        "2575 sayılı Danıştay Kanunu m.24/1-a",
        "medium",
    ),
    V(
        "Dava konusu işi ilk derece mahkemesi sıfatıyla Danıştay inceler",
        [
            "Her mahkeme işlemin kendi çevresindeki bölümünü ayrı ayrı inceler",
            "Davacı yetki alanlarından birindeki mahkemeyi kesin olarak seçer",
            "Bölge idare mahkemelerinden biri kura yoluyla ilk derece görevlendirilir",
            "Uyuşmazlık idari yargı dışında kaldığı için adli yargıda görülür",
        ],
        "Danıştay Kanunu m.24'teki birden çok yetki alanı kuralının uygulanması için aşağıdakilerden hangisi aranır?",
        "Dava konusu işin birden çok idare veya vergi mahkemesinin yetki alanına girmesi",
        [
            "Aynı işlemin yalnız bir mahkemenin çevresinde birden çok kişiyi etkilemesi",
            "Davacıların farklı illerde oturmasına rağmen işlemin tek yerde yapılması",
            "Dava dilekçesinde birbirinden bağımsız birden çok talebin yazılması",
            "İlk derece mahkemesinin kararına karşı istinaf yolunun açık bulunması",
        ],
        "Özel görev kuralı, etkilenen kişi veya talep sayısına değil, dava konusu işin birden çok idare veya vergi mahkemesinin yetki alanına girmesine bağlanmıştır.",
        "2575 sayılı Danıştay Kanunu m.24/1-e",
        "hard",
    ),
    V(
        "İdari dava ilk derece mahkemesi olarak Danıştayda görülür",
        [
            "Uyuşmazlık sözleşmenin tarafı idare tarafından kesin olarak çözülür",
            "Dava kamu hizmetinin yürütüldüğü yerdeki iş mahkemesinde görülür",
            "Uyuşmazlık her durumda görevli tüketici mahkemesine gönderilir",
            "Dava bölge idare mahkemesinde doğrudan ilk derece olarak görülür",
        ],
        "Kamu hizmeti imtiyaz sözleşmesinden doğan uyuşmazlığın Danıştayın ilk derece görevine girmesinde belirleyici sözleşme özelliği hangisidir?",
        "İmtiyaz şartlaşma veya sözleşmesinde tahkim yolunun öngörülmemiş olması",
        [
            "Sözleşmenin bedelinin idarenin tek taraflı kararıyla belirlenmiş olması",
            "Sözleşmenin taraflarından birinin yabancı sermayeli şirket olması",
            "Kamu hizmetinin yalnızca bir belediyenin sınırları içinde yürütülmesi",
            "Sözleşmenin noter huzurunda düzenlenmiş ve tescil edilmiş olması",
        ],
        "Danıştayın bu özel ilk derece görevi tahkim yolu öngörülmeyen kamu hizmeti imtiyaz şartlaşma ve sözleşmelerine ilişkindir; tahkim kaydı kanundaki açık istisnadır.",
        "2575 sayılı Danıştay Kanunu m.24/1",
        "medium",
    ),
    V(
        "Uyuşmazlığı aynı yargı çevresindeki bölge idare mahkemesi çözer",
        [
            "Uyuşmazlığı ilk görevsizlik kararını veren mahkeme tek başına çözer",
            "Uyuşmazlığı görevli asliye hukuk mahkemesi kesin olarak çözer",
            "Uyuşmazlığı her durumda Danıştay İdari Dava Daireleri Kurulu çözer",
            "Uyuşmazlığı tarafların ortaklaşa seçeceği hakem heyeti çözer",
        ],
        "İYUK m.43 uyarınca bölge idare mahkemesinin kendi çevresindeki görev veya yetki uyuşmazlığı hakkında verdiği kararın niteliği nedir?",
        "Karar kesindir ve ilgili ilk derece mahkemeleri bu belirlemeye uyar",
        [
            "Karar yalnız tavsiye niteliğindedir ve mahkemeleri bağlamaz",
            "Karar kendiliğinden temyize tabidir ve kesinleşmeden uygulanamaz",
            "Karar ancak tarafların yazılı kabulüyle hukuki sonuç doğurur",
            "Karar idari makamın onayından sonra kesinlik kazanabilir",
        ],
        "İYUK m.43/3, görev ve yetki uyuşmazlıklarında bölge idare mahkemesi ile Danıştayın verdiği kararları kesin sayar; dosyanın gönderildiği mahkeme bu belirlemeyi yeniden tartışamaz.",
        "2577 sayılı İYUK m.43/3",
        "medium",
    ),
    V(
        "Yetkili yer, işlemi yapan idari merciin bulunduğu yerdir",
        [
            "Yetkili yer her durumda davacının yerleşim yeridir",
            "Yetkili yer işlemin tebliğ edildiği herhangi bir yerdir",
            "Yetkili yer davalı idarenin sonradan seçtiği yerdir",
            "Yetkili yer bölge idare mahkemesinin merkezidir",
        ],
        "İYUK m.32'deki genel yetki kuralı hangi durumda devreye girer?",
        "İYUK'ta veya özel kanunda uyuşmazlığa özgü başka bir yetki kuralı yoksa",
        [
            "Davacı özel yetki kuralını kullanmak istemediğini dilekçesinde bildirirse",
            "Davalı idare ilk savunmasında genel yetkili mahkemeyi açıkça kabul ederse",
            "Uyuşmazlık taşınmaz, kamu görevlisi veya vergi işlemine ilişkin olsa bile",
            "Taraflar dava açıldıktan sonra başka bir mahkeme üzerinde anlaşırsa",
        ],
        "Genel yetki, kanunda uyuşmazlığa özgü bir yetkili mahkeme gösterilmediğinde uygulanır; kamu görevlisi, taşınmaz veya vergi uyuşmazlığı gibi özel hükümler önceliklidir.",
        "2577 sayılı İYUK m.32/1",
        "easy",
    ),
    V(
        "Dava, sözleşmeyi yapan idari merciin bulunduğu yerde açılır",
        [
            "Dava yalnız sözleşmenin imzalandığı noterlik yerinde açılır",
            "Dava davacının dilediği herhangi bir idare mahkemesinde açılır",
            "Dava sözleşme bedelini ödeyen banka şubesinin yerinde açılır",
            "Dava zorunlu olarak kamu hizmetinin görüldüğü yerde açılır",
        ],
        "İdari sözleşmenin tarafları, kanunun gösterdiği yetkili idare mahkemesini yaptıkları anlaşmayla değiştirebilir mi?",
        "Hayır; idari yargıda yetki kamu düzenindendir ve anlaşmayla değiştirilemez",
        [
            "Evet; sözleşmeye yazılan her yetki şartı idari mahkemeyi bağlar",
            "Evet; fakat yalnız davacı kamu tüzel kişisi olduğunda değiştirilebilir",
            "Hayır; çünkü idari sözleşmelerden doğan hiçbir dava idari yargıda görülmez",
            "Hayır; yetkili yeri yalnız bölge adliye mahkemesi sonradan belirleyebilir",
        ],
        "İYUK m.32/2 uyarınca yetki kamu düzenindendir. Bu nedenle tarafların idari sözleşmeye koyduğu bir yetki kaydı kanundaki görevli ve yetkili idari yargı yerini değiştiremez.",
        "2577 sayılı İYUK m.32/2",
        "medium",
    ),
    V(
        "Dava Ankara veya Bursa idare mahkemelerinden birinde açılabilir",
        [
            "Dava yalnız eski görev yeri olan Ankara'da açılabilir",
            "Dava yalnız yeni görev yeri olan Bursa'da açılabilir",
            "Dava yalnız kamu kurumunun merkezinin bulunduğu yerde açılabilir",
            "Dava görev yerleri dışında davacının ikametgâhında açılabilir",
        ],
        "Atama ve nakil işlemlerine karşı davalarda İYUK m.33/1'in tanıdığı seçimlik yetki nasıl kullanılır?",
        "Kamu görevlisi yeni veya eski görev yeri idare mahkemelerinden birine başvurabilir",
        [
            "Kamu görevlisi yalnız işlemi tebliğ aldığı yer mahkemesine başvurabilir",
            "Yetkili mahkemeyi davalı idare dava açıldıktan sonra tek taraflı seçer",
            "Atama davaları görev yeriyle bağlantı aranmadan yalnız Ankara'da açılır",
            "Yeni ve eski görev yeri mahkemelerinin ikisinde aynı anda dava açılması gerekir",
        ],
        "Atama ve nakil davalarında yeni görev yeri ile eski görev yeri mahkemeleri seçimlik yetkilidir; düzenleme kamu görevlisini yalnız yeni görev yerine bağlı bırakmaz.",
        "2577 sayılı İYUK m.33/1",
        "easy",
    ),
    V(
        "Yetkili yer, kamu görevlisinin son görev yaptığı Eskişehir'dir",
        [
            "Yetkili yer her durumda kamu kurumunun Ankara'daki merkezidir",
            "Yetkili yer kamu görevlisinin dava günündeki ikametgâhıdır",
            "Yetkili yer işlemin elektronik ortamda tebliğ edildiği yerdir",
            "Yetkili yer bölge idare mahkemesinin bulunduğu herhangi bir ildir",
        ],
        "Aşağıdaki işlemlerden hangisi İYUK m.33/2'deki son görev yeri ölçütüne tabidir?",
        "Kamu görevlisinin emekli edilmesine ilişkin işlem",
        [
            "Kamu görevlisinin devam eden görevinde aldığı aylık miktarı",
            "Adayın kamu görevine ilk kez alınmak için girdiği merkezi sınav",
            "Memurun görevle ilişkisini kesmeyen uyarma disiplin cezası",
            "Kurumun bütün çalışanlarına yönelik genel düzenleyici işlemi",
        ],
        "İYUK m.33/2; göreve son verme, emekli etme ve görevden uzaklaştırma işlemlerinde kamu görevlisinin son görev yaptığı yerdeki idare mahkemesini yetkili kılar.",
        "2577 sayılı İYUK m.33/2",
        "medium",
    ),
    V(
        "Dava, memurun görevli bulunduğu yer idare mahkemesinde açılır",
        [
            "Dava yalnız disiplin amirinin kişisel yerleşim yerinde açılır",
            "Dava memurun dilediği herhangi bir idare mahkemesinde açılır",
            "Dava zorunlu olarak kurumun Ankara'daki merkezinde açılır",
            "Dava görevli sulh ceza hâkimliğinde açılır",
        ],
        "Kamu görevlisinin özlük ve parasal haklarına ilişkin uyuşmazlıkta özel yetki hangi yere bağlanmıştır?",
        "İlgilinin görevli bulunduğu yerdeki idare mahkemesine",
        [
            "Maaş ödemesini yapan bankanın genel müdürlük merkezine",
            "Kamu görevlisinin nüfusa kayıtlı olduğu yerdeki mahkemeye",
            "Uyuşmazlık tutarına göre seçilecek herhangi bir vergi mahkemesine",
            "İşlemi imzalayan amirin dava tarihindeki görev yerine",
        ],
        "İYUK m.33/3, görevle ilişiği kesmeyen disiplin cezalarının yanında ilerleme, yükselme, sicil, intibak ve diğer özlük ve parasal hak davalarında ilgilinin görevli bulunduğu yeri esas alır.",
        "2577 sayılı İYUK m.33/3",
        "medium",
    ),
    V(
        "Yetkili mahkeme taşınmazın bulunduğu yerdeki idare mahkemesidir",
        [
            "Yetkili mahkeme taşınmaz malikinin dilediği yerdeki idare mahkemesidir",
            "Yetkili mahkeme imar planını ilan eden gazetenin basıldığı yerdedir",
            "Yetkili mahkeme taşınmazın tapuya ilk kaydedildiği yerdeki hukuk mahkemesidir",
            "Yetkili mahkeme belediye başkanının yerleşim yerindeki mahkemedir",
        ],
        "İYUK m.34'teki taşınmazın bulunduğu yer kuralı aşağıdaki uyuşmazlıklardan hangisini de kapsar?",
        "Taşınmaz mevzuatının uygulanmasından doğan kamulaştırma işlemini",
        [
            "Taşınmaz malikinin satıcıyla yaptığı özel hukuk satış sözleşmesini",
            "Kiracının başka bir kiracıyla yaptığı taşınır eşya devir sözleşmesini",
            "Şirket ortağının pay devrine ilişkin ticari nitelikteki alacak davasını",
            "İşçinin taşınmazda çalışmasından doğan bireysel işçilik alacağını",
        ],
        "İYUK m.34; imar, kamulaştırma ve benzeri taşınmaz mevzuatının uygulanmasından doğan idari davalarda taşınmazın bulunduğu yer mahkemesini özel yetkili kılar.",
        "2577 sayılı İYUK m.34",
        "medium",
    ),
    V(
        "Dava, taşınır malın bulunduğu yerdeki idare mahkemesinde açılır",
        [
            "Dava yalnız taşınır malikinin nüfusa kayıtlı olduğu yerde açılır",
            "Dava el koyma tutanağını düzenleyen görevlinin ikametgâhında açılır",
            "Dava zorunlu olarak idarenin Ankara'daki merkezinde açılır",
            "Dava taşınırın satın alındığı yerdeki tüketici mahkemesinde açılır",
        ],
        "Taşınır mala ilişkin idari davada, mal dava açılmadan önce başka bir yere götürülmüşse İYUK m.35'in temel bağlantı noktası hangisidir?",
        "Uyuşmazlığa konu taşınır malın bulunduğu yer",
        [
            "Taşınır malın üretildiği fabrikanın ticaret sicili yeri",
            "Davacının taşınırı satın aldığı satıcının yerleşim yeri",
            "Taşıma işini yapan şirketin merkezinin bulunduğu yer",
            "Taşınırın bedelinin ödendiği banka şubesinin bulunduğu yer",
        ],
        "İYUK m.35, taşınır mallara ilişkin idari davalarda işlemi yapan idarenin merkezi veya davacının ikametgâhı yerine taşınırın bulunduğu yeri esas alır.",
        "2577 sayılı İYUK m.35",
        "easy",
    ),
    V(
        "Dava, hizmetin görüldüğü Antalya'daki idare mahkemesinde açılır",
        [
            "Dava yalnız davacının doğum yerindeki idare mahkemesinde açılır",
            "Dava zararın tutarına göre seçilecek herhangi bir vergi mahkemesinde açılır",
            "Dava idarenin merkezinin bulunduğu yerdeki hukuk mahkemesinde açılır",
            "Dava hizmeti yürüten personelin yerleşim yerindeki mahkemede açılır",
        ],
        "İdari sözleşme dışındaki tam yargı davalarında İYUK m.36'nın ilk sıradaki yetki ölçütü hangisidir?",
        "Zararı doğuran idari uyuşmazlığı çözmeye yetkili idare mahkemesi",
        [
            "Davacının dava tarihindeki yerleşim yerinde bulunan vergi mahkemesi",
            "Davalı idarenin bütçesini onaylayan makamın bulunduğu yerdeki mahkeme",
            "Zarar miktarına göre bölge idare mahkemesince sonradan seçilen mahkeme",
            "Dava dilekçesinin ilk teslim edildiği adli yargı mahkemesi",
        ],
        "İYUK m.36, ölçütleri sıralı kurar: önce zararı doğuran idari uyuşmazlığı çözmeye yetkili mahkeme; bu bağ yoksa hizmet veya eylem yeri, son olarak davacının ikametgâhı değerlendirilir.",
        "2577 sayılı İYUK m.36/a",
        "hard",
    ),
    V(
        "Dava, davacının ikametgâhının bulunduğu yer idare mahkemesinde açılır",
        [
            "Dava doğrudan Danıştayda ilk derece mahkemesi sıfatıyla açılır",
            "Dava davalı idarenin seçtiği herhangi bir idare mahkemesinde açılır",
            "Dava zararın ödendiği banka şubesinin bulunduğu yerde açılır",
            "Dava yalnız olayın öğrenildiği yerdeki hukuk mahkemesinde açılır",
        ],
        "İYUK m.36/c'deki davacının ikametgâhı ölçütü ne zaman uygulanır?",
        "Maddenin önceki sıralarında yer alan uyuşmazlık ve eylem bağlantıları uygulanamıyorsa",
        [
            "Davacı bu yeri diğer kanuni yetki ölçütlerinden daha elverişli görüyorsa",
            "Davalı idare cevap dilekçesinde ikametgâh mahkemesine açıkça onay verirse",
            "Tam yargı istemi bir idari sözleşmeden doğmuş ve tahkim kaydı içeriyorsa",
            "Zararı doğuran idari uyuşmazlığı çözecek mahkeme açıkça belirlenebiliyorsa",
        ],
        "Davacının ikametgâhı, idari sözleşme dışındaki tam yargı davalarında m.36/a ve m.36/b bağlantılarının uygulanamadığı diğer hâller için son sıradaki ölçüttür.",
        "2577 sayılı İYUK m.36/c",
        "hard",
    ),
    V(
        "Yetkili yer, tarhı yapan ve cezayı kesen vergi dairesinin bulunduğu yerdir",
        [
            "Yetkili yer yalnız mükellefin kanuni temsilcisinin ikametgâhıdır",
            "Yetkili yer vergi borcunun ödendiği banka şubesinin bulunduğu yerdir",
            "Yetkili yer davacının seçeceği herhangi bir idare mahkemesidir",
            "Yetkili yer her durumda Gelir İdaresi Başkanlığının bulunduğu Ankara'dır",
        ],
        "İYUK m.37/a'ya göre vergi uyuşmazlığında yetkiyi belirleyen işlemler hangi seçenekte birlikte verilmiştir?",
        "Vergiyi tarh ve tahakkuk ettiren veya zam ve cezayı kesen dairenin işlemleri",
        [
            "Vergi beyannamesini hazırlayan meslek mensubunun bütün özel işlemleri",
            "Mükellefin mal aldığı satıcının ve ödeme yaptığı bankanın işlemleri",
            "Vergi mahkemesi başkanlığının ve bölge idare mahkemesinin işlemleri",
            "Vergi incelemesine tanık olan kişilerin ikametgâh işlemleri",
        ],
        "Tarh, tahakkuk, zam ve ceza uyuşmazlıklarında yetkili vergi mahkemesi, bu işlemleri yapan dairenin bulunduğu yere göre belirlenir.",
        "2577 sayılı İYUK m.37/a",
        "medium",
    ),
    V(
        "Yetkili yer, ödeme emrini düzenleyen dairenin bulunduğu yerdir",
        [
            "Yetkili yer borçlunun seçtiği herhangi bir vergi mahkemesidir",
            "Yetkili yer ödeme emrini tebliğ eden posta merkezinin bulunduğu yerdir",
            "Yetkili yer amme alacağının ödendiği banka şubesinin bulunduğu yerdir",
            "Yetkili yer her durumda ilk tarhiyatı yapan dairenin bulunduğu yerdir",
        ],
        "Ödeme emrine karşı davada yetki belirlenirken tarhiyatı yapan daire ile ödeme emrini düzenleyen daire farklıysa hangisi esas alınır?",
        "Ödeme emrini düzenleyen dairenin bulunduğu yer esas alınır",
        [
            "İlk tarhiyatı yapan dairenin bulunduğu yer zorunlu olarak esas alınır",
            "Borçlunun dava gününde seçtiği herhangi bir yer esas alınır",
            "Ödeme emrini fiilen teslim eden görevlinin bulunduğu yer esas alınır",
            "Amme alacağını bütçesine kaydeden bakanlığın merkezi esas alınır",
        ],
        "İYUK m.37/c, 6183 sayılı Kanunun uygulanmasında ödeme emrini düzenleyen daireyi özel bağlantı noktası yapar; ilk tarhiyatı yapan daire farklı olsa da sonuç değişmez.",
        "2577 sayılı İYUK m.37/c",
        "medium",
    ),
    V(
        "Davalar arasında İYUK m.38 uyarınca hukuki bağlantı bulunur",
        [
            "Davalar yalnız tarafları farklı olduğu için bağlantısızdır",
            "Davalar ancak talep sonuçları tamamen aynıysa bağlantılı sayılır",
            "Davalar arasında ilişki kurulması idari yargıda mümkün değildir",
            "Davalar bağlantılı olsa bile mutlaka ayrı yargı kollarında görülür",
        ],
        "Ayrı hukuki sebeplere dayanan iki davadan biri hakkında verilecek hüküm diğerinin sonucunu etkiliyorsa İYUK m.38 bakımından sonuç nedir?",
        "Hükümlerin birbirini etkilemesi tek başına bağlantı ölçütlerinden biridir",
        [
            "Hukuki sebepler farklı olduğu için bağlantı hiçbir durumda kurulamaz",
            "Bağlantı için iki davanın taraflarının ve taleplerinin aynı olması zorunludur",
            "Bağlantı yalnız ilk davanın kesinleşmesinden sonra değerlendirilebilir",
            "İki dava farklı tarihlerde açılmışsa aralarında bağlantı kurulamaz",
        ],
        "İYUK m.38/1 alternatif ölçütler getirir: aynı maddi veya hukuki sebep yeterli olduğu gibi bir davadaki hükmün diğerini etkilemesi de bağlantı kurar.",
        "2577 sayılı İYUK m.38/1",
        "medium",
    ),
    V(
        "Evet; mahkeme bağlantının varlığına doğrudan doğruya karar verebilir",
        [
            "Hayır; iki tarafın birlikte yazılı başvurusu bulunmadıkça inceleyemez",
            "Hayır; bağlantı konusunda yalnız Danıştay Başsavcısı karar verebilir",
            "Evet; ancak davalardan ikisi de kesin hükme bağlandıktan sonra inceleyebilir",
            "Evet; fakat karar verebilmesi için idari makamın önceden izin vermesi gerekir",
        ],
        "Bağlantılı davalardan biri ilk derece mahkemesi olarak Danıştayda bulunuyorsa dosyalar bakımından hangi usul uygulanır?",
        "Bağlantılı dava dosyaları Danıştaya gönderilir",
        [
            "Danıştaydaki dava görevli idare mahkemesine geri gönderilir",
            "Her dava bulunduğu mahkemede tamamen bağımsız biçimde sürdürülür",
            "Dosyaların tamamı ilgili bölge idare mahkemesine istinafen gönderilir",
            "Bağlantı kararı kendiliğinden bütün davaların açılmamış sayılmasına yol açar",
        ],
        "İYUK m.38/3 uyarınca bağlantılı davalardan biri Danıştayda bulunuyorsa dava dosyası Danıştaya gönderilir; bu kural bağlantının hangi üst merci tarafından ele alınacağını belirler.",
        "2577 sayılı İYUK m.38/3",
        "hard",
    ),
    V(
        "Merci tayinini aynı yargı çevresindeki bölge idare mahkemesi yapar",
        [
            "Merci tayinini ilk davanın açıldığı mahkeme tek başına yapar",
            "Merci tayinini görevli bölge adliye mahkemesi yapar",
            "Merci tayinini tarafların seçeceği özel hakem heyeti yapar",
            "Merci tayinini uyuşmazlığa taraf idari makam yapar",
        ],
        "Aynı bölge idare mahkemesinin yargı çevresindeki iki idare mahkemesinin sınırlarının belirlenmesinde tereddüt çıkarsa merci tayini kime aittir?",
        "O yargı çevresindeki bölge idare mahkemesine aittir",
        [
            "Tereddüt yaşayan iki mahkemenin ortaklaşa seçeceği hukuk mahkemesine aittir",
            "İşlemi yapan idari makamın merkez teşkilatındaki kurula aittir",
            "Her durumda doğrudan Anayasa Mahkemesi Genel Kuruluna aittir",
            "Davacının yerleşim yerindeki bölge adliye mahkemesine aittir",
        ],
        "İYUK m.44/1-a, yalnız olumlu yetki uyuşmazlığını değil, aynı yargı çevresindeki mahkemelerin çevre sınırlarında tereddüt edilmesini de o bölge idare mahkemesine götürür.",
        "2577 sayılı İYUK m.44/1-a",
        "medium",
    ),
    V(
        "Farklı yargı çevrelerini ilgilendiren merci tayinini Danıştay yapar",
        [
            "Merci tayinini davalı idarenin merkezindeki bölge idare mahkemesi yapar",
            "Merci tayinini ilk başvurulan mahkeme tek başına kesinleştirir",
            "Merci tayinini görevli bölge adliye mahkemesi hukuk dairesi yapar",
            "Merci tayinini tarafların ortaklaşa seçtiği idari makam yapar",
        ],
        "Danıştayın veya bölge idare mahkemesinin İYUK m.44 uyarınca verdiği merci tayini kararının niteliği nedir?",
        "Karar kesindir; görevli ve yetkili mahkeme bu kararla belirlenir",
        [
            "Karar bir danışma görüşüdür ve ilk derece mahkemesini bağlamaz",
            "Karar ancak tarafların ayrıca kabul etmesiyle uygulanabilir hâle gelir",
            "Karar zorunlu olarak bölge adliye mahkemesinde istinaf edilebilir",
            "Karar idari makamın onay vermesine kadar hiçbir sonuç doğurmaz",
        ],
        "İYUK m.44/2-3 uyarınca üst merci görevli ve yetkili mahkemeyi belirler ve bu konuda verdiği karar kesindir.",
        "2577 sayılı İYUK m.44/2-3",
        "medium",
    ),
    V(
        "Görevsizlik kararının kesinleşmesini izleyen günden itibaren otuz gün içinde idari dava açılır",
        [
            "Görevsizlik kararı verildiği gün içinde aynı adli mahkemeye yeniden başvurulur",
            "Kararın kesinleşmesinden itibaren yedi gün içinde Danıştaya temyiz başvurusu yapılır",
            "Herhangi bir süre aranmadan istenilen tarihte bölge idare mahkemesine başvurulur",
            "İdari yargıya geçiş mümkün olmadığından yalnız tazminat için adli yargıya başvurulur",
        ],
        "Adli yargı yerinin görevsizlik kararından sonra İYUK m.9'daki sürede idari yargıya başvurulmasının ilk başvuru tarihi üzerindeki sonucu nedir?",
        "Adli yargı yerine yapılan ilk başvuru tarihi idari yargı başvurusu için de korunur",
        [
            "İdari yargıya başvuru günü her durumda ilk ve tek başvuru tarihi sayılır",
            "İlk başvuru yalnız davalı idarenin yazılı kabulü bulunursa korunur",
            "Tarih koruması yalnız görevsizlik kararı kesinleşmeden dava açılırsa uygulanır",
            "İlk başvuru tarihi yerine ödeme emrinin düzenlendiği tarih esas alınır",
        ],
        "İYUK m.9, adli yargıdaki görevsizlik kararından sonra öngörülen sürede görevli idari yargı yerine başvurulduğunda ilk başvuru tarihini korur.",
        "2577 sayılı İYUK m.9",
        "medium",
    ),
    V(
        "Mahkeme görev ve yetki konularını ilk incelemede kendiliğinden değerlendirir",
        [
            "Mahkeme görev ve yetkiyi yalnız davalının ilk itirazı üzerine değerlendirir",
            "Mahkeme görevi incelemeden doğrudan uyuşmazlığın esasını karara bağlar",
            "Mahkeme görev konusunu davalı idarenin takdirine bırakır",
            "Mahkeme görev alanı dışındaki davayı bölge adliye mahkemesine istinafen gönderir",
        ],
        "İdari yargının görev alanındaki bir dava görevli veya yetkili olmayan idare mahkemesinde açılmışsa ilk inceleme sonunda hangi karar verilir?",
        "Dava görev veya yetki yönünden reddedilir ve dosya görevli, yetkili mahkemeye gönderilir",
        [
            "Dava her durumda esastan reddedilir ve dosya idari makama iade edilir",
            "Dava açılmamış sayılır ve bütün başvuru hakları kendiliğinden sona erer",
            "Mahkeme yetkisizliği dikkate almadan yalnız taraf delillerini değerlendirir",
            "Dosya görevli mahkeme belirlenmeden doğrudan adli yargıya gönderilir",
        ],
        "İYUK m.14/3-a görev ve yetkiyi ilk inceleme konusu yapar. Uyuşmazlık idari yargının görevinde olup yanlış idari mahkemede açılmışsa m.15/1-a uyarınca ret kararıyla dosya görevli ve yetkili mahkemeye gönderilir.",
        "2577 sayılı İYUK m.14/3-a, m.15/1-a",
        "hard",
    ),
    V(
        "Dosya, görevli üst mercie merci tayini için gönderilir",
        [
            "Dava hukuki engel ortadan kalkıncaya kadar süresiz biçimde işlemden kaldırılır",
            "Taraflar yeni bir mahkemede aynı davayı yeniden açmak zorunda bırakılır",
            "Dava görevli olmayan bir adli yargı mahkemesine kendiliğinden aktarılır",
            "Engelin varlığı davanın herhangi bir karar verilmeden sona ermesini sağlar",
        ],
        "Yetkili mahkemenin davaya bakmasına fiilî veya hukukî engel çıktığında merci tayini isteminde kimler bulunabilir?",
        "Taraflar veya mahkemeler merci tayini isteminde bulunabilir",
        [
            "Yalnız davalı idarenin en üst amiri istemde bulunabilir",
            "Yalnız Adalet Bakanlığı resen merci tayini isteyebilir",
            "Sadece davacı ile davalının birlikte imzaladığı istem geçerlidir",
            "Hiç kimse istemde bulunamaz; dosya kendiliğinden kesinleşir",
        ],
        "İYUK m.44/1, fiilî veya hukukî engel dâhil merci tayini hâllerinde dosyanın tarafların ya da mahkemelerin istemi üzerine yetkili üst mercie gönderilmesini öngörür.",
        "2577 sayılı İYUK m.44/1",
        "medium",
    ),
]

assert len(VARIANTS) == len(RULES) == 26
for rule, variant in zip(RULES, VARIANTS):
    rule.update(variant)


PREMISES = [
    {"stem": "İdari yargı mercileri hakkında hangileri doğrudur?\n\nI. Bölge idare mahkemesi istinaf başvurularını inceler\n\nII. Vergi mahkemesi vergi cezalarına ilişkin davaları çözer\n\nIII. İdare mahkemesi kanundaki sınırlar içinde genel görevli ilk derece mahkemesidir", "correct": "I, II ve III", "why": "Üç ifade de idari yargı düzenindeki temel görev paylaşımını doğru gösterir.", "ref": "2575 m.24; 2576 m.3/A, m.5-6"},
    {"stem": "İYUK'taki yetki kuralları bakımından hangileri doğrudur?\n\nI. Yetki kamu düzenindendir\n\nII. Özel hüküm yoksa işlemi yapan merciin yeri esas alınır\n\nIII. Taraflar anlaşarak kanuni yetkiyi her durumda değiştirebilir", "correct": "I ve II", "why": "İdari yargıda yetki kamu düzenindendir ve özel hüküm yoksa işlemi yapan merciin bulunduğu yer esas alınır; taraf anlaşması kanuni yetkiyi değiştiremez.", "ref": "2577 sayılı İYUK m.32"},
    {"stem": "Kamu görevlilerine ilişkin yetki bakımından hangileri doğrudur?\n\nI. Nakil davası yeni veya eski görev yerinde açılabilir\n\nII. Göreve son verme davasında son görev yeri esas alınır\n\nIII. Görevle ilişiği kesmeyen disiplin cezasında görevli bulunulan yer esas alınır", "correct": "I, II ve III", "why": "Üç ifade de kamu görevlileri için İYUK m.33'te öngörülen özel yetki kurallarını yansıtır.", "ref": "2577 sayılı İYUK m.33"},
    {"stem": "Özel yetki kuralları hakkında hangileri doğrudur?\n\nI. İmar davasında taşınmazın bulunduğu yer esastır\n\nII. Taşınır mal davasında davacının yerleşim yeri zorunludur\n\nIII. Ödeme emrinde emri düzenleyen dairenin yeri esastır", "correct": "I ve III", "why": "Taşınmazın bulunduğu yer ve ödeme emrini düzenleyen dairenin bulunduğu yer özel yetkidir. Taşınırda ise malın bulunduğu yer esas alınır.", "ref": "2577 sayılı İYUK m.34-35, m.37"},
    {"stem": "Bağlantılı davalar bakımından hangileri doğrudur?\n\nI. Aynı maddi sebepten doğma bağlantı oluşturabilir\n\nII. Bir davadaki hükmün diğerini etkilemesi bağlantı oluşturabilir\n\nIII. Bağlantıya yalnız tarafların ortak talebiyle karar verilebilir", "correct": "I ve II", "why": "Aynı maddi veya hukuki sebep ya da hükümlerin birbirini etkilemesi bağlantı ölçütüdür. Mahkeme resen de karar verebilir.", "ref": "2577 sayılı İYUK m.38"},
    {"stem": "Merci tayini hakkında hangileri doğrudur?\n\nI. Aynı yargı çevresindeki uyuşmazlıkta bölge idare mahkemesi yetkilidir\n\nII. Diğer hâllerde Danıştay yetkilidir\n\nIII. Merci tayini kararı yalnız tavsiye niteliğindedir", "correct": "I ve II", "why": "İYUK m.44, aynı yargı çevresinde bölge idare mahkemesini, diğer hâllerde Danıştayı yetkilendirir; verilen karar kesindir, tavsiye değildir.", "ref": "2577 sayılı İYUK m.44"},
    {"stem": "Danıştayın ilk derece görevi bakımından hangileri doğrudur?\n\nI. Cumhurbaşkanı kararlarına karşı davalar kapsamdadır\n\nII. Ülke çapında uygulanacak bakanlık düzenleyici işlemleri kapsamdadır\n\nIII. Her belediye encümeni kararı doğrudan Danıştayda dava edilir", "correct": "I ve II", "why": "Cumhurbaşkanı kararları ve ülke çapındaki bakanlık düzenleyici işlemleri Danıştayın ilk derece görevindedir; belediye encümeni kararları için böyle genel bir kural yoktur.", "ref": "2575 sayılı Danıştay Kanunu m.24"},
    {"stem": "İdari yargıda görev bakımından hangileri doğrudur?\n\nI. İdare mahkemeleri kanunda belirtilen kapsamda genel görevli ilk derece mahkemeleridir\n\nII. Vergi mahkemeleri özel hukuk sözleşmelerinden doğan bütün alacak davalarını çözer\n\nIII. Bölge idare mahkemesi olağan olarak istinaf incelemesi yapar", "correct": "I ve III", "why": "İdare mahkemeleri kanundaki sınırlar içinde genel görevli ilk derece mahkemesi, bölge idare mahkemesi ise olağan istinaf merciidir. Özel hukuk sözleşmelerinden doğan bütün alacak davaları vergi mahkemesinin görevine girmez.", "ref": "2576 sayılı Kanun m.3/A, m.5-6"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="idari_yargilama_hukuku", topic_id="idari_yargi_gorev_yetki",
        label="İdari Yargıda Görev ve Yetki", slug="idari_yargi_gorev_yetki",
        prefix="kh-iy-gorev", seed=20261001, legislation_version="2575, 2576 ve 2577 sayılı Kanunlar (17.07.2026)",
        rules=RULES, premises=PREMISES, wrong_banks=WRONG,
    )
