#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Kurumlar Vergisi Mükellefiyeti, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Bir incelemede sermaye şirketi, kooperatif, iktisadi kamu kuruluşu, vakıf iktisadi işletmesi ve iş ortaklığı karşılaştırılmıştır. Ortak özellikleri hangisidir?",
        "KVK'da kurumlar vergisi mükellefleri kaç ana grupta sayılmıştır?",
        "Kurumlar vergisi mükellefi olabilmeleri",
        "Beş ana grupta",
        ["Yalnız gelir vergisi mükellefi olmaları", "Tamamının gerçek kişi olması", "Yalnız yerel vergi ödemeleri", "Vergiden koşulsuz muaf olmaları"],
        ["İki ana grupta", "Üç ana grupta", "Yedi ana grupta", "Dokuz ana grupta"],
        "Sayılan beş kurum türünün kazançları KVK m. 1 uyarınca kurumlar vergisine tabidir.",
        "KVK sermaye şirketi, kooperatif, iktisadi kamu kuruluşu, dernek-vakıf iktisadi işletmesi ve iş ortaklığını sayar.",
        "5520 sayılı KVK m. 1",
        "easy",
    ),
    r(
        "Türkiye'de kurulmuş anonim şirketin kurumlar vergisi karşısındaki statüsü hangisidir?",
        "Anonim, limited ve sermayesi paylara bölünmüş komandit şirketler KVK'da hangi gruptadır?",
        "Sermaye şirketi",
        "Sermaye şirketleri",
        ["Şahıs ortaklığı", "İktisadi kamu kuruluşu", "İş ortaklığı", "Dernek iktisadi işletmesi"],
        ["Kooperatifler", "İktisadi kamu kuruluşları", "İş ortaklıkları", "Adi ortaklıklar"],
        "Anonim şirket KVK kapsamında sermaye şirketi ve kurumlar vergisi mükellefidir.",
        "KVK m. 2 anonim, limited ve sermayesi paylara bölünmüş komandit şirketleri sermaye şirketi sayar.",
        "5520 sayılı KVK m. 1-2",
        "easy",
    ),
    r(
        "SPK'nın düzenleme ve denetimine tabi bir yatırım fonu tüzel kişiliği bulunmadığını ileri sürmüştür. KVK uygulamasındaki niteliği hangisidir?",
        "SPK düzenleme ve denetimine tabi fonlar KVK bakımından nasıl değerlendirilir?",
        "Sermaye şirketi sayılır",
        "Sermaye şirketi sayılır",
        ["Kurumlar vergisi kapsamı dışındadır", "Adi ortaklık sayılır", "Yalnız gelir vergisine tabidir", "İktisadi kamu kuruluşudur"],
        ["Gerçek kişi sayılır", "Kooperatif sayılır", "İş ortaklığı sayılır", "Dernek iktisadi işletmesi sayılır"],
        "SPK denetimine tabi fonlar, KVK uygulamasında sermaye şirketi sayılır.",
        "Fonun özel hukuk niteliği, KVK'nın onu sermaye şirketi sayan açık hükmünü değiştirmez.",
        "5520 sayılı KVK m. 2/1",
        "medium",
    ),
    r(
        "1163 sayılı Kanuna göre kurulmuş bir kooperatif, özel bir muafiyet koşulu ileri sürmemektedir. Mükellef grubu hangisidir?",
        "Kooperatifler KVK'nın mükellef sınıflandırmasında hangi konumdadır?",
        "Kooperatif mükellef grubunda",
        "Ayrı bir kurumlar vergisi mükellef grubudur",
        ["Gerçek kişi gelir vergisi grubunda", "İş ortaklığı grubunda", "Dernek iktisadi işletmesi grubunda", "Sermaye şirketi grubunda"],
        ["Her durumda vergi dışındadır", "Yalnız ortakları vergilenir", "Adi ortaklık sayılır", "Yalnız belediye vergisine tabidir"],
        "Kooperatifler KVK m. 1'de ayrı kurumlar vergisi mükellef grubu olarak sayılır.",
        "Kooperatifin kanuni tanımı ve varsa muafiyet şartları ayrı; temel mükellef grubu kooperatiflerdir.",
        "5520 sayılı KVK m. 1-b ve 2/2",
        "easy",
    ),
    r(
        "Belediyeye bağlı, devamlı ticari faaliyeti bulunan ve sermaye şirketi olmayan işletme hangi kurum türüne girer?",
        "Kamu idaresine ait veya bağlı devamlı ticari, sınai ya da zirai işletme KVK'da nasıl adlandırılır?",
        "İktisadi kamu kuruluşu",
        "İktisadi kamu kuruluşu",
        ["Sermaye şirketi", "Adi ortaklık", "İş ortaklığı", "Dernek iktisadi işletmesi"],
        ["Kooperatif", "Sermaye şirketi", "Gerçek kişi işletmesi", "Münferit mükellef"],
        "Kamu idaresine ait veya bağlı devamlı ticari, sınai veya zirai işletme iktisadi kamu kuruluşudur.",
        "Devlet, belediye ve diğer kamu kuruluşlarına bağlı bu işletmeler KVK m. 2/3 kapsamındadır.",
        "5520 sayılı KVK m. 2/3",
        "easy",
    ),
    r(
        "Bir vakfa bağlı işletme devamlı olarak mal satmaktadır. Vakıf kârı sosyal amacına ayırmaktadır. Kurumlar vergisi mükellefi olan yapı hangisidir?",
        "Dernek veya vakfa bağlı devamlı ticari, sınai veya zirai işletme KVK'da nasıl adlandırılır?",
        "Vakfa ait iktisadi işletme",
        "Dernek veya vakfa ait iktisadi işletme",
        ["Vakfın bütün mal varlığı", "Vakıf yöneticileri", "Mal satın alan tüketiciler", "Bağış yapan gerçek kişiler"],
        ["Sermaye şirketi", "İktisadi kamu kuruluşu", "Kooperatif", "Adi ortaklık"],
        "Mükellef vakfın kendisi değil, ona ait veya bağlı devamlı iktisadi işletmedir.",
        "Dernek veya vakfa bağlı devamlı ticari, sınai ya da zirai işletmeler kurumlar vergisi mükellefidir.",
        "5520 sayılı KVK m. 1-ç ve 2/5",
        "easy",
    ),
    r(
        "Bir sendikaya ait devamlı ticari işletmenin KVK statüsü belirlenmektedir. Sendika hangi yapı gibi kabul edilir?",
        "KVK uygulamasında sendikalar ve cemaatler sırasıyla hangi yapılara benzetilir?",
        "Dernek",
        "Dernek ve vakıf",
        ["Kooperatif", "Sermaye şirketi", "İş ortaklığı", "Kamu kuruluşu"],
        ["Kooperatif ve şirket", "Şirket ve kooperatif", "Kamu kurumu ve şirket", "Gerçek kişi ve ortaklık"],
        "KVK uygulamasında sendikalar dernek sayılır; sendikaya bağlı iktisadi işletme buna göre değerlendirilir.",
        "Kanun sendikayı dernek, cemaati vakıf kabul eder.",
        "5520 sayılı KVK m. 2/5",
        "medium",
    ),
    r(
        "Derneğe ait devamlı işletme kâr amacı gütmeden ve yalnız maliyeti karşılayan bedelle hizmet sunmaktadır. Bu durum mükellefiyeti kaldırır mı?",
        "Dernek-vakıf iktisadi işletmesinin kazanç amacı gütmemesi mükellefiyeti nasıl etkiler?",
        "Hayır; mükellefiyet devam eder",
        "Mükellefiyeti etkilemez",
        ["Evet; her durumda mükellefiyet biter", "Yalnız ortakları vergilenir", "İşletme ücret mükellefi olur", "Kurum gelir vergisine geçer"],
        ["İşletmeyi koşulsuz muaf yapar", "Kurumlar vergisini gelir vergisine çevirir", "Yalnız belediye vergisi doğurur", "İşletmeyi gerçek kişi sayar"],
        "Kazanç amacı bulunmaması veya maliyet bedeliyle çalışılması iktisadi işletmenin mükellefiyetini ortadan kaldırmaz.",
        "KVK m. 2/6 iktisadi faaliyetin devamlılığını esas alır; kâr amacı şart değildir.",
        "5520 sayılı KVK m. 2/6",
        "medium",
    ),
    r(
        "Vakıf iktisadi işletmesinin ayrı tüzel kişiliği ve ayrılmış sermayesi yoktur. Devamlı ticari faaliyeti vardır. Mükellefiyet sonucu hangisidir?",
        "İktisadi işletmenin tüzel kişiliği veya ayrı sermayesi bulunmaması kurumlar vergisini nasıl etkiler?",
        "Mükellefiyeti ortadan kaldırmaz",
        "Mükellefiyeti etkilemez",
        ["İşletmeyi vergi dışına çıkarır", "Yalnız vakfı gelir vergisine tabi tutar", "İşletmeyi ücretli sayar", "Faaliyeti bağış kabul eder"],
        ["Her durumda muafiyet doğurur", "Yalnız ortakları vergilendirir", "KDV mükellefiyetini kurumlar vergisine çevirir", "İşletmeyi kooperatif yapar"],
        "Tüzel kişilik, bağımsız muhasebe, ayrılmış sermaye veya işyeri bulunmaması mükellefiyeti etkilemez.",
        "İktisadi işletmenin mükellefiyeti hukuki biçimden çok devamlı iktisadi faaliyete bağlanmıştır.",
        "5520 sayılı KVK m. 2/6",
        "hard",
    ),
    r(
        "Kamuya ait iktisadi işletme dönem sonunda kâr etmemiş ve gelirini kuruluş amacına ayırmıştır. Kurumlar vergisi mükellefiyeti bakımından sonuç hangisidir?",
        "İktisadi kamu kuruluşunun kâr etmemesi veya kârı kuruluş amacına ayırması hangi sonucu doğurur?",
        "Mükellefiyet niteliğini değiştirmez",
        "İktisadi niteliği değiştirmez",
        ["Kurumlar vergisi kapsamını kendiliğinden kaldırır", "Kuruluşu gerçek kişi yapar", "İşletmeyi ücret mükellefi sayar", "Faaliyeti servet transferine dönüştürür"],
        ["Koşulsuz muafiyet sağlar", "İşletmeyi adi ortaklık yapar", "Sermaye şirketine dönüştürür", "Yalnız KDV mükellefi yapar"],
        "Kâr edilmemesi veya kârın kuruluş amacına ayrılması iktisadi kuruluşun mükellef niteliğini değiştirmez.",
        "Vergiye tabi iktisadi işletme olma ölçütü, fiili ve devamlı iktisadi faaliyettir.",
        "5520 sayılı KVK m. 2/6",
        "medium",
    ),
    r(
        "İki şirket belli bir inşaat işini birlikte yapıp kazancı paylaşmak üzere ortaklık kurmuş ve bu şekilde mükellefiyet istemiştir. Yapı hangisidir?",
        "Belli bir işi ortaklaşa yüklenip kazancı paylaşmak için kurulan ve bu statüde mükellefiyet talep eden yapı hangisidir?",
        "İş ortaklığı",
        "İş ortaklığı",
        ["Adi bağış topluluğu", "Kooperatif", "İktisadi kamu kuruluşu", "Dernek iktisadi işletmesi"],
        ["Sermaye şirketi", "Kollektif şirket", "Vakıf", "Münferit mükellef"],
        "Belli işin ortaklaşa yapılması ve kazancın paylaşılması için kurulan, mükellefiyet talep eden ortaklık iş ortaklığıdır.",
        "KVK iş ortaklığını belli bir iş ve kazanç paylaşımı amacı ile mükellefiyet talebine bağlar.",
        "5520 sayılı KVK m. 2/7",
        "easy",
    ),
    r(
        "Belli iş için kurulan iş ortaklığının tüzel kişiliği bulunmamaktadır. Bu eksiklik kurumlar vergisi mükellefiyetini etkiler mi?",
        "İş ortaklığının tüzel kişiliğinin bulunmaması KVK'daki statüsünü nasıl etkiler?",
        "Hayır; mükellefiyeti etkilemez",
        "Mükellefiyeti etkilemez",
        ["Evet; her durumda kapsam dışı kalır", "Yalnız ortaklar ücretli sayılır", "Ortaklık vakfa dönüşür", "Yalnız gelir vergisi doğar"],
        ["İş ortaklığını gerçek kişi yapar", "Koşulsuz muafiyet sağlar", "Ortaklığı kooperatif yapar", "Mükellefiyeti belediyeye aktarır"],
        "İş ortaklığında tüzel kişilik bulunmaması kurumlar vergisi mükellefiyetini engellemez.",
        "KVK iş ortaklığı statüsünü tüzel kişiliğe değil, ortak iş ve mükellefiyet talebi koşullarına bağlar.",
        "5520 sayılı KVK m. 2/7",
        "medium",
    ),
    r(
        "İki gerçek kişi sürekli işlerini adi ortaklıkta yürütmektedir; KVK anlamında iş ortaklığı mükellefiyeti talep edilmemiştir. Kurumlar vergisi mükellefi hangisidir?",
        "Adi ortaklık KVK m. 2/7'deki iş ortaklığı statüsünü seçmedikçe kurumlar vergisi bakımından genel sonuç hangisidir?",
        "Ortaklık değil, gerçek kişi ortaklar",
        "Kazanç ortaklar düzeyinde vergilenir",
        ["Adi ortaklığın tüzel kişiliği", "Yalnız müşteriler", "Ticaret sicili müdürlüğü", "Ortaklığın çalışanları"],
        ["Adi ortaklık sermaye şirketi sayılır", "Ortaklık koşulsuz muaftır", "Kazanç belediyede vergilenir", "Yalnız işveren stopajı doğar"],
        "Adi ortaklık kural olarak ayrı kurumlar vergisi mükellefi değildir; kazanç ortakların paylarına göre vergilenir.",
        "İş ortaklığı statüsü ayrı koşul ve talebe bağlıdır; her adi ortaklık kendiliğinden kurumlar vergisi mükellefi olmaz.",
        "5520 sayılı KVK m. 1-2; 193 sayılı GVK",
        "hard",
    ),
    r(
        "Bir dernek bağış ve aidat geliri elde etmekte, fakat devamlı iktisadi işletmesi bulunmamaktadır. KVK bakımından doğrudan mükellef olan hangisidir?",
        "Dernek veya vakıf ile bunlara ait iktisadi işletme arasındaki mükellefiyet ayrımı hangisidir?",
        "Derneğin kendisi kurumlar vergisi mükellefi değildir",
        "Mükellef olan iktisadi işletmedir",
        ["Bağış yapan her gerçek kişi mükelleftir", "Dernek her durumda sermaye şirketidir", "Yönetim kurulu üyeleri kurum mükellefidir", "Aidat ödeyenler iş ortaklığıdır"],
        ["Dernek her gelir için kurum mükellefidir", "Vakıf yöneticileri sermaye şirketidir", "Bağışçılar kurumlar vergisi öder", "Dernek çalışanları iş ortaklığıdır"],
        "KVK dernek veya vakfı değil, ona ait veya bağlı iktisadi işletmeyi kurumlar vergisi mükellefi sayar.",
        "İktisadi işletme bulunmuyorsa dernek veya vakfın sırf varlığı kurumlar vergisi mükellefiyeti doğurmaz.",
        "5520 sayılı KVK m. 1-ç ve 2/5",
        "medium",
    ),
    r(
        "Bir kurumun kanuni merkezi Türkiye dışında, iş merkezi Türkiye'dedir. KVK'ya göre mükellefiyet türü hangisidir?",
        "Kanuni merkez veya iş merkezinden yalnız birinin Türkiye'de bulunması hangi mükellefiyeti doğurur?",
        "Tam mükellefiyet",
        "Tam mükellefiyet",
        ["Dar mükellefiyet", "Mükellefiyetsizlik", "Yalnız stopaj sorumluluğu", "Münferit mükellefiyet"],
        ["Dar mükellefiyet", "Vergiden koşulsuz muafiyet", "Yalnız KDV mükellefiyeti", "Geçici mükellefiyet"],
        "Kanuni veya iş merkezinden birinin Türkiye'de bulunması tam mükellefiyet için yeterlidir.",
        "KVK tam mükellefiyeti iki merkezden birinin Türkiye'de olmasına bağlar.",
        "5520 sayılı KVK m. 3/1",
        "easy",
    ),
    r(
        "Kanuni merkezi Türkiye'de bulunan kurum yurt içinde ve dışında kazanç elde etmiştir. Tam mükellefiyetin kapsamı hangisidir?",
        "Tam mükellef kurum hangi coğrafi kapsamdaki kazançları üzerinden vergilendirilir?",
        "Yurt içi ve yurt dışı kazançların tamamı",
        "Dünya çapındaki kazançlarının tamamı",
        ["Yalnız Türkiye'deki ticari kazanç", "Yalnız yurt dışı faiz geliri", "Sadece dağıtılan kâr payı", "Yalnız merkezdeki kira geliri"],
        ["Yalnız Türkiye'deki kazançları", "Yalnız yabancı ülkedeki kazançları", "Sadece ücret gelirleri", "Sadece taşınmaz satışları"],
        "Tam mükellef kurum Türkiye içinde ve dışında elde ettiği kazançların tamamı üzerinden vergilendirilir.",
        "Tam mükellefiyet dünya geliri ilkesine dayanır.",
        "5520 sayılı KVK m. 3/1",
        "easy",
    ),
    r(
        "Yabancı kurumun hem kanuni hem iş merkezi Türkiye dışındadır. Türkiye'de kaynaklanan kazancı vardır. Mükellefiyet türü hangisidir?",
        "Kanuni ve iş merkezlerinin her ikisi de Türkiye dışında olan kurum KVK'da hangi mükellefiyet türündedir?",
        "Dar mükellefiyet",
        "Dar mükellefiyet",
        ["Tam mükellefiyet", "Mükellefiyetsizlik", "Yalnız vergi sorumluluğu", "Geçici mükellefiyet"],
        ["Tam mükellefiyet", "Koşulsuz muafiyet", "Yalnız gelir vergisi mükellefiyeti", "Yerel mükellefiyet"],
        "Kanuni ve iş merkezlerinin ikisi de Türkiye'de olmayan kurum dar mükelleftir.",
        "Dar mükellefiyet için iki merkezin de Türkiye dışında bulunması gerekir.",
        "5520 sayılı KVK m. 3/2",
        "easy",
    ),
    r(
        "Dar mükellef kurum hem Türkiye'de hem yabancı ülkede kazanç elde etmiştir. Türkiye'deki kurumlar vergisinin kapsamı hangisidir?",
        "Dar mükellef kurum Türkiye'de hangi kazançlar üzerinden vergilendirilir?",
        "Yalnız Türkiye'de elde edilen kazançlar",
        "Türkiye kaynaklı kazançlar",
        ["Dünya çapındaki kazançların tamamı", "Yalnız yabancı ülkedeki kazançlar", "Sadece dağıtılmayan kârlar", "Ortakların kişisel gelirleri"],
        ["Yurt dışı kazançlarının tamamı", "Ortaklarının ücret gelirleri", "Dünya gelirinin tamamı", "Yalnız ödenmiş sermayesi"],
        "Dar mükellef yalnız Türkiye'de elde ettiği kazançları üzerinden kurumlar vergisine tabidir.",
        "Dar mükellefiyetin coğrafi kapsamı Türkiye kaynaklı kazançlarla sınırlıdır.",
        "5520 sayılı KVK m. 3/2",
        "easy",
    ),
    r(
        "Şirket sözleşmesinde kayıtlı merkez Ankara, fiili yönetim merkezi Berlin'dir. Ankara'daki merkez hangi kavramdır?",
        "Vergiye tabi kurumun kuruluş belgesinde veya ana sözleşmesinde gösterilen merkez nasıl adlandırılır?",
        "Kanuni merkez",
        "Kanuni merkez",
        ["İş merkezi", "Daimi temsilci", "Vergi dairesi", "Şube merkezi"],
        ["İş merkezi", "Fiili yönetim yeri", "Daimi temsilcilik", "Tahsil merkezi"],
        "Kuruluş kanunu, statü veya sözleşmede gösterilen merkez kanuni merkezdir.",
        "Kanuni merkez belgesel ve hukuki merkezdir; fiili yönetimden ayrılır.",
        "5520 sayılı KVK m. 3/5",
        "easy",
    ),
    r(
        "Şirketin önemli iş kararları ve günlük yönetimi fiilen İstanbul'da toplanmaktadır. İstanbul'daki merkez hangi kavramdır?",
        "İş bakımından işlemlerin fiilen toplandığı ve yönetildiği yer nasıl adlandırılır?",
        "İş merkezi",
        "İş merkezi",
        ["Kanuni merkez", "Ticaret sicili", "Vergi mahkemesi", "Şube adresi"],
        ["Kanuni merkez", "Daimi temsilci", "Tahsil dairesi", "Münferit işyeri"],
        "İşlemlerin fiilen toplandığı ve yönetildiği yer iş merkezidir.",
        "İş merkezi fiili yönetim ölçütüne dayanır.",
        "5520 sayılı KVK m. 3/6",
        "easy",
    ),
    r(
        "Dar mükellef yabancı kurum Türkiye'deki işyeri üzerinden ticari faaliyet yürütmüş ve kazanç elde etmiştir. Bu kazanç hangi kapsamdadır?",
        "Türkiye'de işyeri veya daimi temsilci aracılığıyla yürütülen işten doğan kazanç dar mükellefte nasıl sınıflandırılır?",
        "Türkiye'de elde edilen ticari kazanç",
        "Dar mükellef kurum kazancı",
        ["Yalnız yabancı ülke kazancı", "Vergiden koşulsuz istisna", "Ortağın kişisel ücreti", "Türkiye dışı kira geliri"],
        ["Tam mükellefin dünya geliri", "Gerçek kişinin ücreti", "Vergi dışı sermaye aktarımı", "Yalnız yabancı kaynaklı kazanç"],
        "Türkiye'deki işyeri veya daimi temsilciyle yapılan işten elde edilen ticari kazanç dar mükellefin Türkiye kazancıdır.",
        "KVK m. 3/3-a bu işyeri ve temsilci bağlantısını Türkiye'de kazanç elde etme ölçütü sayar.",
        "5520 sayılı KVK m. 3/3-a",
        "medium",
    ),
    r(
        "Yabancı kurum Türkiye'den yalnız ihraç edilmek üzere mal satın almış, malları Türkiye'de satmadan yurt dışına göndermiştir. Kazanç Türkiye'de elde edilmiş sayılır mı?",
        "Dar mükellef kurumun ihraç amacıyla Türkiye'den aldığı malı burada satmadan yurt dışına göndermesi hangi sonucu doğurur?",
        "Hayır; Türkiye'de elde edilmiş sayılmaz",
        "Türkiye'de ticari kazanç sayılmaz",
        ["Evet; her satın alma Türkiye kazancıdır", "Evet; mal Türkiye'de bulunduğu için", "Yalnız ücret geliri sayılır", "Kurum tam mükellef olur"],
        ["Her durumda Türkiye kazancıdır", "Kurumun iş merkezini Türkiye'ye taşır", "Yalnız KDV mükellefiyeti tam mükellef yapar", "Ortakları gelir vergisine geçirir"],
        "İhraç edilmek üzere Türkiye'de alınıp burada satılmadan gönderilen mallardan doğan kazanç Türkiye'de elde edilmiş sayılmaz.",
        "KVK dar mükellefin salt ihracat amaçlı alımını Türkiye ticari kazancı dışında tutar.",
        "5520 sayılı KVK m. 3/3-a",
        "hard",
    ),
    r(
        "Dar mükellef yabancı kurum Türkiye'deki zirai işletmesinden kazanç elde etmiştir. Bu kazanç kurumlar vergisine tabi midir?",
        "Türkiye'de bulunan zirai işletmeden elde edilen kazanç dar mükellef kurum kazancına girer mi?",
        "Evet; Türkiye kazancıdır",
        "Evet; dar mükellef kurum kazancıdır",
        ["Hayır; yalnız ticari kazanç kapsamdadır", "Hayır; zirai kazanç her durumda vergisizdir", "Yalnız ortakların ücretidir", "Kurum tam mükellef sayılır"],
        ["Hayır; yalnız yabancı ülkede vergilenir", "Hayır; gelir vergisi ücreti sayılır", "Yalnız KDV matrahına girer", "Kurumun kanuni merkezini değiştirir"],
        "Türkiye'deki zirai işletmeden elde edilen kazanç dar mükellefin Türkiye'de elde edilen kurum kazancına dâhildir.",
        "KVK m. 3/3-b Türkiye'deki zirai işletme kazancını açıkça kapsar.",
        "5520 sayılı KVK m. 3/3-b",
        "medium",
    ),
    r(
        "Dar mükellef yabancı kurum Türkiye'deki taşınmazını kiraya vermiştir. Kira geliri kurumlar vergisi kapsamında mıdır?",
        "Türkiye'deki taşınır, taşınmaz ve hakların kiralanmasından elde edilen irat dar mükellefte hangi kapsamdadır?",
        "Türkiye'de elde edilen kurum kazancı",
        "Dar mükellef kurum kazancı",
        ["Yalnız yabancı ülke geliri", "Vergiden koşulsuz muaf gelir", "Ortağın kişisel geliri", "Türkiye dışı ücret"],
        ["Tam mükellefin dünya geliri", "Vergi dışı sermaye aktarımı", "Yalnız gerçek kişi geliri", "Kurumun ödenmiş sermayesi"],
        "Türkiye'deki taşınır, taşınmaz veya hakkın kiralanmasından elde edilen irat dar mükellef kurum kazancına girer.",
        "KVK m. 3/3-ç Türkiye'deki kira iratlarını dar mükellefiyet kapsamına alır.",
        "5520 sayılı KVK m. 3/3-ç",
        "medium",
    ),
    r(
        "Dar mükellef kurumun Türkiye'de elde ettiği menkul sermaye iradı ve diğer kazancı bulunmaktadır. Bu unsurlar kurum kazancına girer mi?",
        "Türkiye'de elde edilen menkul sermaye iradı ile diğer kazanç ve iratlar dar mükellefte nasıl değerlendirilir?",
        "Evet; kurum kazancına dâhildir",
        "Dar mükellef kurum kazancına dâhildir",
        ["Hayır; yalnız ücret sayılır", "Hayır; kurumlar vergisinden koşulsuz muaftır", "Yalnız ortakların geliridir", "Kurum tam mükellefe dönüşür"],
        ["Türkiye kapsamı dışında kalır", "Yalnız gelir vergisi mükellefine aittir", "Ödenmiş sermaye sayılır", "Vergi dışı bağış kabul edilir"],
        "Türkiye'de elde edilen menkul sermaye iratları ile diğer kazanç ve iratlar dar mükellef kurum kazancına girer.",
        "KVK m. 3/3, Türkiye kaynaklı gelir unsurlarını kurum kazancı kapsamında toplar.",
        "5520 sayılı KVK m. 3/3-d ve e",
        "medium",
    ),
    r(
        "Dar mükellef kurumun kazancının Türkiye'de elde edilip edilmediği ve daimi temsilci bağlantısı belirlenecektir. Tamamlayıcı olarak hangi kanun hükümleri uygulanır?",
        "Dar mükellef kurum kazancında Türkiye'de elde etme ve daimi temsilci konularında hangi kanuna başvurulur?",
        "Gelir Vergisi Kanunu",
        "Gelir Vergisi Kanununun ilgili hükümleri",
        ["Emlak Vergisi Kanunu", "Damga Vergisi Kanunu", "Harçlar Kanunu", "Motorlu Taşıtlar Vergisi Kanunu"],
        ["Yalnız Türk Ticaret Kanunu", "Yalnız Belediye Kanunu", "Yalnız Kooperatifler Kanunu", "Yalnız İş Kanunu"],
        "KVK m. 3/4, Türkiye'de elde etme ve daimi temsilci konularında GVK'nın ilgili hükümlerine gönderme yapar.",
        "Kurumlar vergisindeki dar mükellefiyet bağlantıları GVK'nın kaynak ve temsilci kurallarıyla tamamlanır.",
        "5520 sayılı KVK m. 3/4; 193 sayılı GVK m. 7-8",
        "hard",
    ),
]


PREMISES = [
    {"stem":"Kurumlar vergisi mükellef grupları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Sermaye şirketleri mükelleftir\n\nII. Kooperatifler mükellef grubudur\n\nIII. İş ortaklıkları mükellef olabilir","correct":"I, II ve III","why":"Üç kurum türü de KVK m. 1'de sayılan mükellef gruplarındandır.","ref":"5520 sayılı KVK m. 1","difficulty":"easy"},
    {"stem":"Dernek ve vakıf iktisadi işletmeleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Devamlı iktisadi faaliyet mükellefiyet doğurabilir\n\nII. Kâr amacı bulunmaması mükellefiyeti kaldırmaz\n\nIII. Derneğin her faaliyeti kendiliğinden iktisadi işletmedir","correct":"I ve II","why":"Devamlı ticari, sınai veya zirai işletme mükelleftir; kâr amacı şart değildir, fakat derneğin her faaliyeti iktisadi işletme sayılmaz.","ref":"5520 sayılı KVK m. 2/5-6","difficulty":"medium"},
    {"stem":"İş ortaklığı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Belli bir işin ortaklaşa yapılması amaçlanır\n\nII. Tüzel kişilik zorunludur\n\nIII. Bu statüde mükellefiyet tesisi talep edilir","correct":"I ve III","why":"İş ortaklığı belli iş ve kazanç paylaşımına dayanır; tüzel kişilik şart değildir, mükellefiyet talebi aranır.","ref":"5520 sayılı KVK m. 2/7","difficulty":"medium"},
    {"stem":"Tam ve dar mükellefiyet bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Her iki merkezi yurt dışında olan kurum tam mükelleftir\n\nII. Merkezlerden biri Türkiye'de olan kurum tam mükelleftir\n\nIII. Her iki merkezi yurt dışında olan kurum Türkiye kazançları için dar mükelleftir","correct":"II ve III","why":"Kanuni veya iş merkezinden biri Türkiye'deyse tam; ikisi de dışarıdaysa Türkiye kazançları için dar mükellefiyet doğar.","ref":"5520 sayılı KVK m. 3/1-2","difficulty":"easy"},
    {"stem":"Merkez kavramları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kanuni merkez kuruluş belgesinde gösterilen merkezdir\n\nII. İş merkezi faaliyetlerin fiilen yönetildiği merkezdir\n\nIII. İş merkezi her durumda ticaret sicilindeki adrestir","correct":"I ve II","why":"Kanuni merkez hukuki belgeye, iş merkezi fiili yönetim yerine dayanır.","ref":"5520 sayılı KVK m. 3/5-6","difficulty":"medium"},
    {"stem":"Dar mükellef kurum kazancı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Türkiye işyerinden elde edilen ticari kazancı kapsar\n\nII. Türkiye'deki zirai işletme kazancını kapsar\n\nIII. Türkiye'deki mal ve hakların kira iradını kapsar","correct":"I, II ve III","why":"Üç gelir de KVK m. 3/3'te Türkiye'de elde edilen dar mükellef kurum kazancı içinde sayılır.","ref":"5520 sayılı KVK m. 3/3","difficulty":"medium"},
    {"stem":"İktisadi kuruluşlarda mükellefiyet bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kâr edilmemesi mükellefiyeti tek başına kaldırmaz\n\nII. Tüzel kişilik yokluğu mükellefiyeti zorunlu olarak kaldırır\n\nIII. Maliyeti karşılayan bedelle çalışmak iktisadi niteliği ortadan kaldırmaz","correct":"I ve III","why":"Kâr amacı, tüzel kişilik ve yüksek fiyat şart değildir; devamlı iktisadi faaliyet belirleyicidir.","ref":"5520 sayılı KVK m. 2/6","difficulty":"hard"},
    {"stem":"Dar mükellefiyetin kapsamı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dar mükellef dünya kazancının tamamından vergilenir\n\nII. Yalnız Türkiye'de elde edilen kazançları kapsar\n\nIII. Türkiye'de elde etme ölçütlerinde GVK hükümleri tamamlayıcıdır","correct":"II ve III","why":"Dar mükellefiyet Türkiye kaynaklı kazançlarla sınırlıdır ve elde etme ölçütlerinde GVK'ya başvurulur.","ref":"5520 sayılı KVK m. 3/2-4","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="kurumlar_vergisi",
        topic_id="kurumlar_mukellefiyeti",
        label="Kurumlar Vergisi Mükellefiyeti",
        slug="kurumlar_mukellefiyeti",
        prefix="topic-kv-km",
        seed=170730,
        legislation_version="5520 sayılı Kurumlar Vergisi Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
