#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Risk Değerlendirme, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Denetçi, işletmenin finansal tablolarındaki hata veya hile kaynaklı önemli yanlışlık risklerini belirlemeden standart bir prosedür listesi uygulamıştır. BDS 315'in amacıyla uyumlu mudur?",
        "BDS 315 uyarınca risk belirleme ve değerlendirmenin temel amacı nedir?",
        "Hayır; riskler sonraki denetim işlerine dayanak olacak şekilde belirlenmelidir",
        "Risklere karşı yapılacak işlerin tasarlanmasına ve uygulanmasına dayanak oluşturmak",
        ["Evet; bütün işletmelerde sektör ve işlem farklılıklarına bakılmadan aynı prosedür listesi yeterlidir", "Evet; risk değerlendirmesi yalnız rapor tarihinden sonra, bütün prosedürler tamamlanınca yapılır", "Hayır; denetçi yalnız işletmenin ticari risklerini belirler", "Evet; yönetim risk bulunmadığını bildirirse çalışma tamamlanır"],
        ["Yönetimin bütün iş hayatı risklerini belirlemek ve ticari sonuçlarını güvence altına almak", "Denetim riskini hiçbir kanıt toplamadan sıfırlamak ve standart olumlu görüşü seçmek", "Finansal tabloları işletme adına yeniden hazırlamak", "Yalnız denetim ücretinin uygunluğunu değerlendirmek"],
        "BDS 315, önemli yanlışlık risklerinin belirlenmesini ve değerlendirilmesini müteakip denetim işlerinin temeli olarak düzenler.",
        "Risk değerlendirmesi, finansal tablo ve yönetim beyanı düzeyindeki risklere uygun karşılıkların tasarlanmasını sağlar.",
        "BDS 315 par. 1 ve 11", "easy",
    ),
    r(
        "Denetçi planlama aşamasında yaptığı risk değerlendirmesini dönem boyunca değişmez kabul etmiş, yeni işlemleri ve kanıtları dikkate almamıştır. Yaklaşım doğru mudur?",
        "BDS 315'e göre denetçinin risk belirleme ve değerlendirme süreci nasıl bir süreçtir?",
        "Hayır; risk değerlendirmesi yinelenen ve dinamik bir süreçtir",
        "Yinelenen ve dinamik bir süreçtir",
        ["Evet; ilk planlama yapıldıktan sonra riskler değiştirilemez", "Evet; yalnız yönetim isterse değerlendirme yenilenir", "Hayır; bütün denetim prosedürleri dönem sonunda seçilir", "Evet; önceki yıl değerlendirmesi süresiz kullanılabilir"],
        ["Bir kez uygulanan ve değiştirilemeyen bir süreçtir", "Yalnız denetim raporundan sonra yürütülen bir süreçtir", "Sadece işletme yönetiminin gerçekleştirdiği bir süreçtir", "Finansal tablo kalemlerinden bağımsız sabit bir süreçtir"],
        "Denetim ilerledikçe edinilen bilgiler risklerin yeniden ele alınmasını gerektirebilir.",
        "BDS 315 risk değerlendirmesini, denetim boyunca yeni kanıtlarla güncellenebilen yinelenen ve dinamik bir süreç olarak tanımlar.",
        "BDS 315 par. 7 ve 37", "easy",
    ),
    r(
        "Zayıf üst yönetim gözetimi çok sayıda hesap ve yönetim beyanını etkileyebilecek niteliktedir. Bu risk öncelikle hangi düzeyde değerlendirilir?",
        "Önemli yanlışlık riskleri BDS 315 uyarınca hangi iki düzeyde belirlenir?",
        "Finansal tablo düzeyinde",
        "Finansal tablo düzeyi ve yönetim beyanı düzeyi",
        ["Yalnız belirli hesap bakiyesi düzeyinde", "Sadece tek bir işlem belgesi düzeyinde", "Denetim şirketinin ücret düzeyinde", "İşletmenin vergi matrahı düzeyinde"],
        ["İşletme bütçesi ve denetim ücreti düzeylerinde", "Yönetim kurulu ve denetim ekibi düzeylerinde", "Sektör ortalaması ve vergi oranı düzeylerinde", "Nakit akışı ve kâr dağıtımı düzeylerinde"],
        "Bir bütün olarak tablolara yaygın biçimde etki eden riskler finansal tablo düzeyinde ele alınır.",
        "Riskler finansal tabloların geneli ile işlem sınıfı, hesap bakiyesi ve açıklamalara ilişkin yönetim beyanı düzeylerinde belirlenir.",
        "BDS 315 par. 2, 28 ve 30", "easy",
    ),
    r(
        "Bir stok kalemi, ilgili kontroller dikkate alınmadan önce karmaşık değerleme nedeniyle yanlışlığa açıktır. Bu açıklık hangi risk bileşenidir?",
        "Yönetim beyanı düzeyindeki önemli yanlışlık riski hangi iki bileşenden oluşur?",
        "Yapısal risk",
        "Yapısal risk ve kontrol riski",
        ["Kontrol riski", "Tespit edememe riski", "Örnekleme dışı risk", "Denetim sözleşmesi riski"],
        ["Tespit edememe riski ve örnekleme riski", "İş hayatı riski ve likidite riski", "Denetim riski ve müşteri kabul riski", "Piyasa riski ve kredi riski"],
        "Yapısal risk, kontroller dikkate alınmadan önce bir yönetim beyanının yanlışlığa açıklığıdır.",
        "Yönetim beyanı düzeyindeki önemli yanlışlık riski yapısal risk ile kontrol riskinin bileşimidir.",
        "BDS 315 par. 4 ve 12", "easy",
    ),
    r(
        "Denetçi yalnız yönetim kurulunu sorgulamış; analitik prosedür, gözlem veya tetkik uygulamamıştır. Risk değerlendirme prosedürleri tamamlanmış sayılır mı?",
        "BDS 315'te sayılan risk değerlendirme prosedürleri hangileridir?",
        "Hayır; sorgulama yanında analitik prosedür, gözlem ve tetkik gerekir",
        "Sorgulama, analitik prosedürler, gözlem ve tetkik",
        ["Evet; yönetimin sorgulanması tek başına her durumda yeterlidir", "Evet; risk değerlendirmesi yalnız dış teyitten oluşur", "Hayır; sadece ayrıntılı maddi doğrulama testi yapılmalıdır", "Evet; önceki yıl dosyasının okunması bütün prosedürlerin yerini alır"],
        ["Yalnız dış teyit, yeniden hesaplama ve fiziki sayım", "Sadece yönetim beyanı, hukuki mektup ve raporlama", "Detay testleri, örnekleme ve denetçi raporu", "Bütçeleme, finansman ve faaliyet analizi"],
        "Risk değerlendirmesi tek bir sorgulamaya indirgenemez; standart farklı bilgi kaynaklarını birlikte kullanır.",
        "BDS 315 sorgulama, analitik prosedürler ile gözlem ve tetkiki zorunlu prosedür grupları olarak sayar.",
        "BDS 315 par. 13-14", "medium",
    ),
    r(
        "Denetçi risk değerlendirme prosedürlerini yalnız yönetimin açıklamalarını doğrulayacak kanıtları arayacak biçimde tasarlamış, çelişkili kanıtları dışlamıştır. Uygun mudur?",
        "Risk değerlendirme prosedürlerinin kanıt seçimi bakımından temel tasarım ilkesi nedir?",
        "Hayır; doğrulayıcı ve çelişkili kanıtlar tarafsız biçimde değerlendirilmelidir",
        "Doğrulayıcı kanıta yönelip çelişkili kanıtı dışlamayacak şekilde tasarlanması",
        ["Evet; yönetimin açıklamasını doğrulayan kanıtlar diğer kaynaklara bakılmadan öncelikli kabul edilir", "Evet; çelişkili kanıtlar yalnız denetçi raporu yayımlandıktan sonra ayrıca değerlendirilir", "Hayır; yönetimin bütün açıklamaları peşinen yanlış sayılmalıdır", "Evet; kanıt seçimini yalnız işletmenin iç denetimi yapar"],
        ["Yalnız işletme dışından elde edilen kanıtları kabul edip işletme içindeki bütün bilgileri dışlamak", "Bütün yönetim beyanlarını kanıt aramadan reddedip sadece önceki denetim dosyasına dayanmak", "Sadece önceki yıl denetim dosyasındaki kanıtlara dayanılması", "Kanıtların maliyetine göre doğru veya yanlış kabul edilmesi"],
        "Taraflı kanıt seçimi risklerin eksik veya yanlış değerlendirilmesine yol açar.",
        "Denetçi, doğrulayıcı kanıt elde etme veya çelişkili kanıtı dışlama eğilimi göstermeyecek tarafsız bir tasarım kullanır.",
        "BDS 315 par. 13", "medium",
    ),
    r(
        "Denetçi önceki yıl edindiği işletme bilgisini, cari yılda büyük sistem değişikliği olmasına rağmen güncelliğini sorgulamadan kullanmıştır. Doğru mudur?",
        "Önceki denetimlerden elde edilen bilgiler cari risk değerlendirmesinde hangi koşulla kullanılabilir?",
        "Hayır; bilginin cari dönem için ihtiyaca uygunluğu ve güvenilirliği değerlendirilmelidir",
        "Cari denetim için hâlen ihtiyaca uygun ve güvenilir olduğunun değerlendirilmesiyle",
        ["Evet; önceki denetimde edinilen bilgiler işletmedeki önemli değişikliklerden bağımsız olarak süresiz geçerli sayılır", "Evet; büyük sistem değişikliği eski bilginin cari dönem için uygunluk ve güvenilirliğini kendiliğinden artırır", "Hayır; önceki dönem bilgileri hiçbir koşulda kullanılamaz", "Evet; yönetim değişikliği olmadıkça değerlendirme yapılmaz"],
        ["Önceki yıl olumlu görüş verilmiş ve aynı yönetim görevde kalmışsa bilginin doğrudan kullanılmasıyla", "Yönetimin sözlü olarak hiçbir değişiklik olmadığını açıklaması ve yeni kanıtın aranmamasıyla", "Denetim ücretinin önceki yılla aynı kalmasıyla", "Bilginin yalnız elektronik dosyada saklanmış olmasıyla"],
        "Önceki deneyim yararlı olabilir; ancak değişiklikler bilginin cari dönem uygunluğunu ve güvenilirliğini etkiler.",
        "Denetçi geçmiş bilgiyi kullanmadan önce cari denetim açısından hâlen ihtiyaca uygun ve güvenilir olup olmadığını değerlendirir.",
        "BDS 315 par. 15-16", "medium",
    ),
    r(
        "Sorumlu denetçi ekipte risk müzakeresi yapmamış, üyeleri işletmenin önemli yanlışlığa açıklığı konusunda bilgilendirmemiştir. BDS 315'e uygun mudur?",
        "Denetim ekibi içindeki risk müzakeresinin ana konuları nelerdir?",
        "Hayır; kilit üyelerle risk müzakeresi yapılmalıdır",
        "Raporlama çerçevesinin uygulanması ve finansal tabloların yanlışlığa açıklığı",
        ["Evet; risk müzakeresi yalnız iç denetim fonksiyonunun görevidir", "Evet; ekip üyeleri sadece kendi test sonuçlarını bilmelidir", "Hayır; bütün çalışanların müşteriyle birlikte toplantı yapması gerekir", "Evet; sorumlu denetçinin tek başına değerlendirmesi her zaman yeterlidir"],
        ["Denetim ücretinin dağılımı ve personelin izin planı", "Müşterinin gelecek dönem satış hedefleri ve reklam bütçesi", "Vergi oranları ile işletmenin finansman maliyeti", "Ekip üyelerinin bireysel performans ve terfi kararları"],
        "Ekip müzakeresi farklı deneyimlerden yararlanarak önemli yanlışlık risklerinin tutarlı değerlendirilmesini destekler.",
        "Kilit üyeler çerçevenin işletmeye uygulanmasını ve tabloların hata veya hile kaynaklı yanlışlığa açıklığını müzakere eder.",
        "BDS 315 par. 17-18", "medium",
    ),
    r(
        "İşletme yeni bir sektöre girmiş ve iş modelini dijital platforma taşımıştır. Denetçi yalnız geçmiş finansal oranlara bakarak çevreyi tanıdığını kabul edebilir mi?",
        "İşletme ve çevresi hakkında kanaat edinilirken hangi hususlar birlikte ele alınır?",
        "Hayır; iş modeli, sektör, mevzuat ve performans ölçümleri de anlaşılmalıdır",
        "İş modeli, sektör ve diğer dış etkenler ile performans ölçümleri",
        ["Evet; geçmiş finansal oranlar yeni sektör ve iş modeli değişikliklerinden bağımsız olarak bütün riskleri açıklar", "Evet; yeni sektöre giriş yalnız yönetimin ticari kararını ilgilendirdiğinden finansal raporlama riskini etkilemez", "Hayır; denetçi yalnız vergi mevzuatını incelemelidir", "Evet; bilgi teknolojisi kullanımı risk değerlendirmesinin dışındadır"],
        ["Sadece denetim ücreti, ekip büyüklüğü, planlanan çalışma süresi ve önceki yıl bütçesi", "Yalnız vergi matrahı, kâr dağıtımı, ortak sayısı ve işletmenin geçmiş yıl satış kotası", "Müşterinin reklam bütçesi, satış kotası ve fiyat listesi", "Denetim şirketinin ortaklık yapısı ve personel politikası"],
        "İş modelindeki ve dış çevredeki değişiklikler yönetim beyanlarının yanlışlığa açıklığını etkileyebilir.",
        "Denetçi organizasyon ve iş modeli, sektör ve mevzuat etkenleri ile iç ve dış performans ölçümleri hakkında kanaat edinir.",
        "BDS 315 par. 19", "medium",
    ),
    r(
        "Yönetim, geçerli finansal raporlama çerçevesiyle çelişen yeni bir muhasebe politikası seçmiştir. Denetçi risk değerlendirmesinde bu seçimi değerlendirmeli midir?",
        "Denetçi işletmenin muhasebe politikalarını hangi ölçüte göre değerlendirir?",
        "Evet; politikanın uygunluğu ve raporlama çerçevesiyle tutarlılığı değerlendirilir",
        "Uygunluk ve geçerli finansal raporlama çerçevesiyle tutarlılık",
        ["Hayır; muhasebe politikalarının seçimi yalnız yönetimin takdirindedir ve çerçeveyle tutarlılık denetim kapsamı dışındadır", "Evet; ancak yalnız politika kârı azaltıyorsa değerlendirilir", "Hayır; denetçi sadece vergi uygulamalarına uygunluğu inceler", "Evet; fakat önceki yılda kullanılan her politika otomatik uygundur"],
        ["Yalnız işletmenin vergi yükünü azaltıp azaltmadığı ve yönetimin bu sonucu uygun bulup bulmadığı", "Sadece sektör ortalamasındaki kârlılığı sağlayıp sağlamadığı", "Denetim ücretini ve çalışma süresini etkileyip etkilemediği", "Yönetim kurulunun oybirliğiyle kabul edip etmediği"],
        "Politika seçimi ve değişiklik nedenleri, finansal tablo yanlışlık risklerinin anlaşılmasında önemlidir.",
        "BDS 315 politikanın uygunluğunun ve geçerli çerçeveyle tutarlılığının değerlendirilmesini ister.",
        "BDS 315 par. 19-20", "medium",
    ),
    r(
        "Denetçi iç kontrolü yalnız onay kontrollerinden ibaret saymış; kontrol çevresi, risk değerlendirme, izleme ve bilgi sistemini kapsam dışında bırakmıştır. Doğru mudur?",
        "BDS 315'e göre iç kontrol sisteminin birbiriyle ilişkili bileşen sayısı kaçtır?",
        "Hayır; iç kontrol sistemi birbiriyle ilişkili beş bileşenden oluşur",
        "Beş bileşen",
        ["Evet; kontrol faaliyetleri iç kontrolün tek bileşenidir", "Evet; bilgi sistemi finansal raporlamadan bağımsızdır", "Hayır; iç kontrol yalnız iç denetim ve dış denetimden oluşur", "Evet; risk değerlendirme yalnız denetçinin sorumluluğudur"],
        ["İki bileşen", "Üç bileşen", "Dört bileşen", "Yedi bileşen"],
        "Tek tek kontroller, işletmenin daha geniş iç kontrol sistemi içinde değerlendirilir.",
        "Sistem; kontrol çevresi, işletmenin risk değerlendirme ve izleme süreçleri, bilgi sistemi ve iletişim ile kontrol faaliyetlerinden oluşur.",
        "BDS 315 par. 12", "easy",
    ),
    r(
        "Yönetim etik ihlallerini görmezden geliyor, yetki ve sorumlulukları belirsiz bırakıyor ve çalışanları hesap verebilir tutmuyorsa öncelikle hangi bileşen zayıftır?",
        "Kontrol çevresinin iç kontrol sistemi bakımından temel işlevi nedir?",
        "Kontrol çevresi",
        "Diğer iç kontrol bileşenleri için uygun bir zemin oluşturmak",
        ["Bilgi sistemi ve iletişim", "Kontrol faaliyetleri", "İzleme süreci", "İşletmenin risk değerlendirme süreci"],
        ["Bütün maddi doğrulama prosedürlerini ortadan kaldırmak", "Finansal tabloları denetçi adına hazırlamak", "Yalnız bilgi teknolojisi erişimlerini yönetmek", "İşletmenin ticari hedeflerini garanti etmek"],
        "Etik kültür, gözetim, yetki, yetkinlik ve hesap verebilirlik kontrol çevresinin temel unsurlarıdır.",
        "Kontrol çevresi diğer bileşenlerin etkin işleyebileceği kurumsal zemini oluşturur; eksiklikleri diğer bileşenleri zayıflatabilir.",
        "BDS 315 par. 21", "medium",
    ),
    r(
        "İşletmenin süreci finansal raporlama risklerini belirliyor ancak gerçekleşme ihtimali ve ciddiyetini değerlendirmeden hiçbir karşılık geliştirmiyor. Süreç yeterli midir?",
        "İşletmenin risk değerlendirme süreci hangi üç faaliyeti kapsar?",
        "Hayır; risklerin ciddiyeti değerlendirilmeli ve riskler ele alınmalıdır",
        "Riskleri belirlemek, ciddiyetlerini değerlendirmek ve ele almak",
        ["Evet; risklerin yalnız adlandırılması yeterlidir, gerçekleşme ihtimali ve ciddiyet için başka değerlendirme gerekmez", "Evet; ciddiyet yalnız denetçi raporunda değerlendirilir", "Hayır; işletme bütün riskleri sigorta şirketine devretmelidir", "Evet; finansal raporlama riskleri yalnız dönem sonunda ele alınır"],
        ["Denetim ücretini belirlemek, müşteri bütçesine göre faturalamak ve rapor tarihinden önce tahsil etmek", "Bütçeyi hazırlamak, onaylamak ve kamuya açıklamak", "Yönetim beyanını almak, arşivlemek ve imha etmek", "Denetçi seçmek, sözleşme yapmak ve rapor yayımlamak"],
        "Uygun bir işletme risk süreci yalnız risk listesinden değil, ciddiyet değerlendirmesi ve karşılıktan oluşur.",
        "Süreç finansal raporlamayla ilgili iş hayatı risklerini belirler, ihtimal dâhil ciddiyetini değerlendirir ve ele alır.",
        "BDS 315 par. 22", "medium",
    ),
    r(
        "Denetçi, yönetimin belirlemesi beklenen önemli bir finansal raporlama riskini yönetimin atladığını bulmuştur. Bu bulguyu yalnız kendi prosedürlerine ekleyip işletmenin sürecini değerlendirmemiştir. Uygun mudur?",
        "Yönetimin belirlemesi beklenen bir riskin işletme sürecince atlanması denetçiyi hangi değerlendirmeye yöneltir?",
        "Hayır; riskin neden atlandığı ve işletme sürecine etkisi anlaşılmalıdır",
        "Atlanma nedeninin ve işletmenin risk değerlendirme sürecine etkisinin değerlendirilmesine",
        ["Evet; atlanan riskin işletmenin süreciyle hiçbir ilgisi yoktur ve yalnız denetçinin prosedür planını etkiler", "Evet; denetçi riski bulduğunda yönetimin süreci otomatik yeterlidir", "Hayır; bütün iç kontrol sistemi derhâl kaldırılmalıdır", "Evet; yalnız denetim ücretinin artırılması yeterlidir"],
        ["Denetim sözleşmesinin gerekçe araştırılmadan otomatik sona erdirilmesine ve bütün risklerin yönetime bırakılmasına", "Yönetimin bütün finansal tabloları denetçiye hazırlatmasına", "Yalnız ilgili hesap bakiyesinin finansal tablolardan çıkarılmasına", "İşletmenin ticari stratejisinin denetçi tarafından değiştirilmesine"],
        "Beklenen bir riskin atlanması, işletmenin risk değerlendirme sürecinde eksiklik bulunabileceğine işaret eder.",
        "Denetçi atlanma nedenini anlar ve bu durumun işletme risk sürecinin uygunluğuna ilişkin değerlendirmesini nasıl etkilediğini ele alır.",
        "BDS 315 par. 23", "hard",
    ),
    r(
        "İşletme kontrollerin etkinliğini izliyor ancak izleme raporlarında kullanılan verilerin güvenilirliğini hiç değerlendirmiyor. Denetçi bunu dikkate almalı mıdır?",
        "İç kontrol sistemini izleme süreci hakkında kanaat edinilirken hangi bilgi özelliği ayrıca anlaşılır?",
        "Evet; izleme bilgilerinin güvenilirliğine ilişkin yönetim dayanağı anlaşılmalıdır",
        "İzlemede kullanılan bilgi kaynakları ve bu bilgilerin güvenilirliğinin dayanağı",
        ["Hayır; izleme raporunda yer alan her veri, kaynağı ve hazırlanma biçimi değerlendirilmeden otomatik güvenilir kabul edilir", "Evet; yalnız rapor elektronik değilse değerlendirilir", "Hayır; izleme süreci bağımsız denetim kapsamı dışındadır", "Evet; fakat sadece iç denetim fonksiyonu yoksa önemlidir"],
        ["Denetim ücretinin hangi bütçeden ödendiği ve izleme raporunun yönetimce hangi tarihte imzalandığı", "Yönetimin raporu kaç sayfada hazırladığı", "İzleme sonuçlarının yalnız vergi idaresine sunulması", "Denetim ekibinin çalışma saatlerinin dağılımı"],
        "Güvenilir olmayan izleme verisi, kontrollerin etkinliği hakkında yanlış sonuç doğurabilir.",
        "Denetçi sürekli ve ayrı değerlendirmeler yanında izleme bilgi kaynaklarını ve yönetimin güvenilirlik dayanağını anlar.",
        "BDS 315 par. 24", "medium",
    ),
    r(
        "İşlemler bir uygulamada başlatılıp başka bir sistemde defteri kebire aktarılmaktadır; denetçi bu veri akışını anlamadan riskleri değerlendirmiştir. Yaklaşım doğru mudur?",
        "Bilgi sistemi hakkında kanaat edinmenin merkezinde hangi süreç yer alır?",
        "Hayır; işlemlerin başlatılmasından raporlanmasına kadar bilgi akışı anlaşılmalıdır",
        "İşlemlerin başlatılması, kaydedilmesi, işlenmesi ve raporlanmasındaki bilgi akışı",
        ["Evet; yalnız dönem sonu toplam bakiyelerinin incelenmesi, işlemlerin bütün sistemlerdeki veri akışını anlamak için yeterlidir", "Evet; otomatik sistemlerde bilgi akışı yanlışlık riski taşımaz", "Hayır; denetçi bütün bilgi sistemini kendisi yeniden kurmalıdır", "Evet; veri akışını yalnız işletmenin yazılım tedarikçisi değerlendirir"],
        ["Yalnız denetim raporunun hazırlanması, imzalanması, yayımlanması ve kullanıcılarla paylaşılması süreci", "İşletmenin satış bütçesini hazırlama ve onaylama süreci", "Denetim ücretinin tahakkuk ve tahsilat süreci", "Çalışanların işe alınması ve izin planlama süreci"],
        "Bilginin sistemler arasında nasıl aktığı anlaşılmadan tamlık, doğruluk ve geçerlilik riskleri uygun biçimde belirlenemez.",
        "Denetçi işlem ve olayların başlatılmasından finansal tablolarda raporlanmasına kadar bilgi işleme faaliyetlerini ve iletişimi anlar.",
        "BDS 315 par. 25", "hard",
    ),
    r(
        "İşletme standart olmayan dönem sonu yevmiye kayıtları kullanmaktadır. Denetçi bu kayıtlar üzerindeki kontrolleri kontrol faaliyetleri kapsamında belirlemeli midir?",
        "BDS 315 uyarınca kontrol faaliyetleri bileşeninde özellikle belirlenen kontrol gruplarından biri hangisidir?",
        "Evet; standart olmayan yevmiye kayıtları üzerindeki kontroller belirlenir",
        "Ciddi riskleri ve standart olmayan yevmiye kayıtlarını ele alan kontroller",
        ["Hayır; yevmiye kayıtları yalnız muhasebe standardının konusudur", "Evet; ancak yalnız kayıt tutarı önemliliğin altında ise", "Hayır; dönem sonu kontrolleri risk değerlendirmesine dâhil değildir", "Evet; fakat kontrolün tasarımı ve uygulanması değerlendirilmez"],
        ["Yalnız bordro izinleri ve personel devam kontrolleri", "Sadece bütçe sapmalarını açıklayan yönetim raporları", "Denetim ücretinin tahsilatını sağlayan mali kontroller", "İşletmenin pazarlama kampanyalarını onaylayan kontroller"],
        "Standart olmayan yevmiye kayıtları olağan süreçlerin dışında yanlışlık veya yönetimin kontrolleri aşma riski taşıyabilir.",
        "Kontrol faaliyetlerinde ciddi riskleri, yevmiye kayıtlarını ve denetçinin güvenmeyi planladığı kontrolleri ele alan kontroller belirlenir.",
        "BDS 315 par. 26(a)", "hard",
    ),
    r(
        "Denetçi bir kontrolün politika belgesinde yer aldığını görmüş ve personelin kontrolü uygulayıp uygulamadığını araştırmadan etkin işlediği sonucuna varmıştır. Doğru mudur?",
        "Bir kontrolün tasarımının değerlendirilmesi ve uygulanıp uygulanmadığının belirlenmesi neyi tek başına kanıtlamaz?",
        "Hayır; tasarım değerlendirilmeli ve sorgulama dışında prosedürlerle uygulama belirlenmelidir",
        "Kontrolün dönem boyunca işleyiş etkinliğini",
        ["Evet; yazılı politika kontrolün etkin işlediğini kesin kanıtlar", "Evet; yönetimin sözlü beyanı bütün diğer prosedürlerin yerini alır", "Hayır; denetçi kontrolü işletme adına uygulamalıdır", "Evet; tasarım iyi ise kontrolün uygulanması önem taşımaz"],
        ["Kontrolün belirli riski ele almak üzere tasarlanmış olduğunu", "Kontrolün işletme tarafından uygulamaya konulmuş olduğunu", "Kontrolün hangi yönetim beyanıyla ilişkili olduğunu", "Kontrolün manuel veya otomatik nitelik taşıdığını"],
        "Yazılı tasarım ile fiilî uygulama farklı olabilir; sorgulama tek başına uygulamayı belirlemek için yeterli değildir.",
        "Tasarım ve uygulamanın anlaşılması risk değerlendirmesidir; dönem boyunca işleyiş etkinliği ayrıca kontrol testiyle kanıtlanır.",
        "BDS 315 par. 26(c); BDS 330 par. 8-10", "hard",
    ),
    r(
        "Finansal raporlama uygulamasına yetkisiz erişim ve kontrolsüz program değişikliği riski vardır. Denetçi yalnız tek bir otomatik kontrolü inceleyip BT süreçlerini kapsam dışında bırakabilir mi?",
        "Genel BT kontrollerinin temel amacı aşağıdakilerden hangisidir?",
        "Hayır; BT riskleri ve bunları ele alan genel BT kontrolleri belirlenmelidir",
        "BT çevresinin doğru çalışmasını ve bilgi bütünlüğünü sürekli desteklemek",
        ["Evet; otomatik kontroller genel BT kontrollerinden bağımsızdır ve erişim ile program değişikliği risklerinden etkilenmez", "Evet; yetkisiz erişim yalnız işletmenin güvenlik konusudur", "Hayır; denetçi tüm yazılımların kaynak kodunu yeniden yazmalıdır", "Evet; program değişiklikleri finansal raporlama riskini etkilemez"],
        ["Yalnız bilgisayar donanımının satın alma maliyetini azaltmak ve yazılım lisanslarının süresini uzatmak", "Finansal tabloları denetçi müdahalesi olmadan hazırlamak", "İşletmenin bütün manuel kontrollerini ortadan kaldırmak", "Sadece çalışanların internet kullanım süresini sınırlamak"],
        "BT uygulamasının güvenilirliği, erişim, değişiklik ve operasyon süreçlerindeki genel kontrollerden etkilenir.",
        "Genel BT kontrolleri bilgi işleme kontrollerinin işleyişini, BT çevresinin sürekliliğini ve bilginin tamlık, doğruluk ve geçerliliğini destekler.",
        "BDS 315 par. 12 ve 26(b)", "hard",
    ),
    r(
        "Yeni ve karmaşık bir değerleme modeli yüksek tahmin belirsizliği ve yönetim taraflılığına açıktır. Bu özellikler risk değerlendirmesinde hangi kavramla ele alınır?",
        "BDS 315'te sayılan yapısal risk faktörleri arasında hangileri yer alır?",
        "Yapısal risk faktörleri",
        "Karmaşıklık, subjektiflik, değişiklik, belirsizlik ve taraflılığa açıklık",
        ["Kontrol testlerinin zamanlaması", "Denetim ücretinin büyüklüğü", "Örnekleme aralığı", "Müşteri kabul prosedürü"],
        ["Likidite, kârlılık, borçlanma, yatırım ve temettü politikası", "Planlama, bütçeleme, raporlama, arşiv ve faturalama", "Sorgulama, teyit, yeniden hesaplama, gözlem ve tetkik", "Tamlık, doğruluk, sınıflandırma, sunum ve dipnot sayısı"],
        "Bu özellikler kontrollerden önce yönetim beyanının yanlışlığa olan açıklığını artırır.",
        "Yapısal risk faktörleri karmaşıklık, subjektiflik, değişiklik, belirsizlik ve yönetim taraflılığı veya diğer hile faktörleri nedeniyle açıklığı içerir.",
        "BDS 315 par. 12 ve Ek 2", "medium",
    ),
    r(
        "Denetçi yapısal riski yalnız olası yanlışlığın tutarına göre değerlendirmiş, yanlışlığın gerçekleşme ihtimalini dikkate almamıştır. Uygun mudur?",
        "Yönetim beyanı düzeyinde yapısal risk değerlendirilirken hangi iki unsur birlikte ele alınır?",
        "Hayır; yanlışlık ihtimali ile muhtemel yanlışlığın büyüklüğü birlikte değerlendirilir",
        "Yanlışlığın oluşma ihtimali ve oluşursa muhtemel büyüklüğü",
        ["Evet; yalnız parasal büyüklük yapısal riski belirler ve yanlışlığın oluşma ihtimali değerlendirme dışında bırakılır", "Evet; gerçekleşme ihtimali sadece kontrol riskinde kullanılır", "Hayır; yapısal risk yalnız denetim ücretine göre belirlenir", "Evet; nitel faktörler hiçbir risk değerlendirmesinde dikkate alınmaz"],
        ["Denetim ücretinin toplam tutarı ile sözleşmenin geçerli olduğu hesap döneminin uzunluğu", "Kontrol sayısı ile denetim ekibinin büyüklüğü", "İşletmenin satış hacmi ile çalışan sayısı", "Örnek hacmi ile örnekleme aralığı"],
        "Yalnız tutara bakmak düşük olasılıklı büyük yanlışlıkları veya yüksek olasılıklı önemli yanlışlıkları yanlış sınıflandırabilir.",
        "Yapısal risk, yanlışlık ihtimali ile yanlışlık oluştuğunda muhtemel büyüklüğün bileşimi üzerinden değerlendirilir.",
        "BDS 315 par. 31", "medium",
    ),
    r(
        "Bir satış hesabının var olma beyanında belirlenmiş önemli yanlışlık riski bulunmakta, ancak tamlık beyanında böyle bir risk bulunmamaktadır. Hangi beyan ilgilidir?",
        "Kritik önem taşıyan işlem sınıfı, hesap bakiyesi veya açıklama neyi ifade eder?",
        "Var olma beyanı",
        "Bir veya daha fazla ilgili yönetim beyanı bulunan kalemi",
        ["Tamlık beyanı", "Bütün beyanlar otomatik olarak", "Hiçbir yönetim beyanı", "Yalnız sunum beyanı"],
        ["Yalnız tutarı genel önemliliği aşan her kalemi", "Denetçinin test uygulamadığı bütün küçük kalemleri", "Yönetimin finansal tablolardan çıkardığı her kalemi", "Sadece önceki yılda yanlışlık bulunan hesapları"],
        "İlgili yönetim beyanı, kontroller dikkate alınmadan önce belirlenmiş önemli yanlışlık riski bulunan beyandır.",
        "Bir ya da daha fazla ilgili yönetim beyanı bulunan işlem sınıfı, hesap bakiyesi veya açıklama kritik önem taşır.",
        "BDS 315 par. 12 ve 29", "medium",
    ),
    r(
        "Yönetimin dürüstlüğüne ilişkin ciddi şüpheler çok sayıda hesap ve açıklamayı etkileyebilecek niteliktedir. Denetçi yalnız tek bir hesap riskini artırmakla yetinebilir mi?",
        "Finansal tablo düzeyindeki önemli yanlışlık risklerinin ayırt edici özelliği nedir?",
        "Hayır; yaygın etki finansal tablo düzeyinde değerlendirilmelidir",
        "Tabloların bütünüyle yaygın biçimde ilgili olup çok sayıda beyanı etkileyebilmesi",
        ["Evet; her risk yalnız tek bir hesapla ilişkilendirilebilir", "Evet; yönetimin dürüstlüğü risk değerlendirmesini etkilemez", "Hayır; bütün hesap bakiyeleri finansal tablolardan çıkarılmalıdır", "Evet; risk yalnız denetçi raporunun biçimini etkiler"],
        ["Yalnız tek bir faturanın matematiksel doğruluğunu etkilemesi", "Sadece vergi matrahında küçük bir fark yaratması", "Denetim ücretinin tahsil edilebilirliğini azaltması", "Bir kontrolün belirli günde uygulanmamasından ibaret olması"],
        "Yönetim dürüstlüğü gibi yaygın koşullar birden çok yönetim beyanının risk değerlendirmesini etkiler.",
        "Finansal tablo düzeyi riskleri tabloların bütünüyle yaygın biçimde ilgilidir ve çok sayıda beyanı etkileyebilir.",
        "BDS 315 par. 4 ve 30", "hard",
    ),
    r(
        "Bir riskte yanlışlık ihtimali ve muhtemel büyüklük, yapısal risk aralığının üst sınırına yakındır. Denetçi bu riski hangi sınıfta değerlendirmeyi düşünmelidir?",
        "Ciddi risk kavramı BDS 315'e göre hangi durumu ifade eder?",
        "Ciddi risk",
        "Yapısal risk aralığının üst sınırına yakın veya diğer BDS'lerce ciddi sayılan risk",
        ["Önemsiz risk", "Yalnız kontrol riski", "Tespit edememe riski", "Denetim sözleşmesi riski"],
        ["Yalnız tutarı önemlilik altında kalan her yanlışlık riski", "Kontrollerle tamamen ortadan kalktığı varsayılan her risk", "Denetim ekibinin daha önce hiç karşılaşmadığı her işlem", "Sadece işletmenin ticari hedeflerini etkileyen faaliyet riski"],
        "Yapısal risk faktörlerinin ihtimal ve büyüklük birleşimini güçlü biçimde etkilediği risk ciddi risk olabilir.",
        "Ciddi risk, yapısal risk aralığının üst sınırına yakın değerlendirilen veya diğer BDS hükümlerince ciddi sayılması gereken risktir.",
        "BDS 315 par. 12 ve 32", "hard",
    ),
    r(
        "Tamamen otomatik satış sisteminde işlemler dışında bağımsız belge oluşmamakta ve maddi doğrulama prosedürleri tek başına yeterli kanıt sağlayamamaktadır. Denetçi ne yapmalıdır?",
        "BDS 330 uyarınca kontrol testleri hangi durumlarda zorunlu hâle gelir?",
        "İlgili kontrolleri belirleyip işleyiş etkinliklerini test etmelidir",
        "Kontrollere güven planlandığında veya maddi doğrulama tek başına yeterli olmadığında",
        ["Yalnız yönetimin sözlü beyanını yeterli kanıt saymalıdır", "Sistemi test etmeden bütün satışları doğru kabul etmelidir", "Maddi doğrulama kanıt sağlamasa da prosedürleri azaltmalıdır", "Kontrol riskini değerlendirmeden olumlu görüş vermelidir"],
        ["Denetim ücreti önceki yıldan daha düşük belirlendiğinde", "Yönetim kontrol testlerini gerekli görmediğini açıkladığında", "İşletmenin satışları bütçe hedefinin altında kaldığında", "Yalnız finansal tablolar erken hazırlandığında"],
        "Maddi doğrulamanın tek başına kanıt sağlayamadığı risklerde ilgili kontroller anlaşılır ve işleyiş etkinliği test edilir.",
        "Kontrol testleri, denetçi kontrollere güvenecekse veya maddi doğrulama tek başına yeterli ve uygun kanıt sağlayamıyorsa uygulanır.",
        "BDS 315 par. 33-34; BDS 330 par. 8", "hard",
    ),
    r(
        "Denetçi ilk risk değerlendirmesiyle tutarsız yeni ve güvenilir bilgi elde etmiş, ancak planlanan prosedürleri değiştirmemiştir. Uygun mudur?",
        "BDS 330 uyarınca risk düzeyi yükseldikçe denetçinin elde edeceği kanıtın niteliği nasıl değişir?",
        "Hayır; risk belirleme veya değerlendirmesi revize edilmelidir",
        "Daha fazla ikna edici denetim kanıtı elde edilir",
        ["Evet; ilk risk değerlendirmesi denetim boyunca değiştirilemez", "Evet; yeni bilgi yalnız gelecek yıl denetiminde kullanılır", "Hayır; bütün denetim çalışması kanıt incelenmeden iptal edilir", "Evet; plan değişikliği için yalnız müşteri onayı yeterlidir"],
        ["Kanıt miktarı ve güvenilirliği azaltılır", "Yalnız yönetimin sözlü açıklamasıyla yetinilir", "Maddi doğrulama prosedürleri tamamen kaldırılır", "Risk ile kanıtın ikna ediciliği arasında bağ kurulmaz"],
        "İlk dayanakla tutarsız yeni bilgi risklerin ve bunlara karşılık veren prosedürlerin yeniden ele alınmasını gerektirir.",
        "Değerlendirilen risk yükseldikçe denetçi o riske karşı daha ikna edici kanıt elde eder.",
        "BDS 315 par. 35 ve 37; BDS 330 par. 6-7", "hard",
    ),
]


PREMISES = [
    {"stem":"Risk değerlendirme prosedürleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İşletmedeki uygun kişiler sorgulanır\n\nII. Analitik prosedürler uygulanır\n\nIII. Gözlem ve tetkik yapılır","correct":"I, II ve III","why":"BDS 315 risk değerlendirme prosedürlerini sorgulama, analitik prosedürler ile gözlem ve tetkik olarak sayar.","ref":"BDS 315 par. 14","difficulty":"easy"},
    {"stem":"İç kontrol sisteminin bileşenleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kontrol çevresi bir bileşendir\n\nII. Bilgi sistemi ve iletişim bir bileşendir\n\nIII. Kontrol faaliyetleri bir bileşendir","correct":"I, II ve III","why":"Üçü de BDS 315'te tanımlanan beş iç kontrol bileşeni arasındadır.","ref":"BDS 315 par. 12","difficulty":"easy"},
    {"stem":"Önceki dönem bilgilerinin kullanılması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Önceki bilgi her durumda süresiz geçerlidir\n\nII. Cari dönem için ihtiyaca uygunluğu değerlendirilir\n\nIII. Cari dönem için güvenilirliği değerlendirilir","correct":"II ve III","why":"Geçmiş bilgi otomatik geçerli sayılmaz; cari denetim açısından uygunluk ve güvenilirlik yeniden değerlendirilir.","ref":"BDS 315 par. 16","difficulty":"medium"},
    {"stem":"Yapısal riskin değerlendirilmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yanlışlık ihtimali dikkate alınır\n\nII. Muhtemel yanlışlığın büyüklüğü dikkate alınır\n\nIII. İlgili kontroller yapısal risk belirlenmeden önce etkin kabul edilir","correct":"I ve II","why":"Yapısal risk ihtimal ve büyüklük üzerinden, ilgili kontroller dikkate alınmadan değerlendirilir.","ref":"BDS 315 par. 31","difficulty":"medium"},
    {"stem":"Kontrol faaliyetleri hakkında kanaat edinilmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ciddi riskleri ele alan kontroller belirlenir\n\nII. Standart olmayan yevmiye kayıtları üzerindeki kontroller belirlenir\n\nIII. Tasarım görülünce işleyiş etkinliği otomatik kanıtlanmış sayılır","correct":"I ve II","why":"İlgili kontroller belirlenir; tasarım ve uygulama hakkındaki kanaat dönem boyunca işleyiş etkinliğinin testi değildir.","ref":"BDS 315 par. 26","difficulty":"hard"},
    {"stem":"Önemli yanlışlık risklerinin düzeyleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Riskler yalnız işletme bütçesi düzeyinde belirlenir\n\nII. Finansal tablo düzeyinde risk belirlenebilir\n\nIII. Yönetim beyanı düzeyinde risk belirlenebilir","correct":"II ve III","why":"BDS 315 riskleri finansal tablo ve yönetim beyanı düzeylerinde belirler; bütçe düzeyi ayrı bir risk düzeyi değildir.","ref":"BDS 315 par. 28","difficulty":"easy"},
    {"stem":"Risk değerlendirmesinin güncellenmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İlk değerlendirmeyle tutarsız yeni bilgi risk değerlendirmesini değiştirebilir\n\nII. İlk plan hiçbir koşulda değiştirilemez\n\nIII. Risk düzeyi yükseldikçe daha ikna edici kanıt gerekir","correct":"I ve III","why":"Yeni bilgi risk değerlendirmesini revize ettirebilir ve yüksek risk daha ikna edici kanıt gerektirir; II yanlıştır.","ref":"BDS 315 par. 37; BDS 330 par. 7","difficulty":"hard"},
    {"stem":"Kontrol testleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Denetçi kontrollere güvenmeyi planlıyorsa kontrol testi uygulanır\n\nII. Maddi doğrulama tek başına yeterli kanıt sağlamıyorsa kontrol testi uygulanır\n\nIII. Yanlışlık bulunmaması kontrolün etkinliğini tek başına kanıtlar","correct":"I ve II","why":"İlk iki durum kontrol testini gerektirir; maddi doğrulamada yanlışlık bulunmaması kontrol etkinliği kanıtı değildir.","ref":"BDS 330 par. 8 ve 16","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="risk_degerlendirme",
        label="Risk Değerlendirme", slug="risk_degerlendirme", prefix="topic-rd",
        seed=2026071749,
        legislation_version="KGK TDS 2026 Seti; BDS 315 ve BDS 330, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
