#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Kurum Kazancı, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Bir kurumun hesap dönemindeki tüm gelir unsurları ve giderleri dikkate alınarak vergiye esas net kazanç belirlenmiştir. Vergi hangi kazanç üzerinden hesaplanır?",
        "Kurumlar vergisinin hesaplanmasına esas kazanç hangisidir?",
        "Safi kurum kazancı",
        "Safi kurum kazancı",
        ["Brüt satış hasılatı", "Dağıtılan kâr payı", "Ödenmiş sermaye", "Dönem sonu kasa bakiyesi"],
        ["Ticari alacak toplamı", "Yalnız dağıtılmış kâr", "Öz sermayenin tamamı", "Brüt satış tutarı"],
        "Kurumlar vergisi bir hesap döneminde elde edilen safi kurum kazancı üzerinden hesaplanır.",
        "Verginin matrahına hareket noktası brüt hasılat veya sermaye değil, safi kurum kazancıdır.",
        "5520 sayılı KVK m. 6/1",
        "easy",
    ),
    r(
        "Kurumun safi kazancı belirlenirken ticari faaliyet giderleri ve hasılatı değerlendirilecektir. Hangi kanunun ticari kazanç hükümleri uygulanır?",
        "Safi kurum kazancının tespitinde temel alınan gelir vergisi hükümleri hangileridir?",
        "Gelir Vergisi Kanunu",
        "Ticari kazanç hükümleri",
        ["Emlak Vergisi Kanunu", "Damga Vergisi Kanunu", "Harçlar Kanunu", "Motorlu Taşıtlar Vergisi Kanunu"],
        ["Ücret hükümleri", "Gayrimenkul iradı hükümleri", "Menkul sermaye hükümleri", "Arızi kazanç hükümleri"],
        "KVK m. 6, safi kurum kazancının tespitinde GVK'nın ticari kazanç hükümlerini esas alır.",
        "Kurum kazancı farklı gelir unsurlarından oluşabilse de safi kazanç ticari kazanç hükümlerine göre belirlenir.",
        "5520 sayılı KVK m. 6/2",
        "easy",
    ),
    r(
        "Şirketin muhasebe kayıtlarında oluşan dönem kârına vergi mevzuatının kabul etmediği gider ve istisna düzeltmeleri uygulanacaktır. Muhasebe kârı hangi kavramdır?",
        "Ticari bilanço kârı ile mali kâr arasındaki temel fark hangisidir?",
        "Ticari bilanço kârı",
        "Vergisel matrah düzeltmeleri",
        ["Kurumlar vergisi matrahı", "Dağıtılabilir net kâr", "Ödenmiş sermaye", "Geçmiş yıl zararı"],
        ["Beyannamenin elektronik verilmesi", "Şirketin ortak sayısı", "Sermayenin nakit konulması", "Hesap döneminin adı"],
        "Muhasebe standartları ve kayıtlar sonucu bulunan dönem kârı ticari bilanço kârıdır; vergi düzeltmeleri sonrası mali kâra ulaşılır.",
        "Mali kâr, ticari bilanço kârının vergi kanunlarındaki kabul edilmeyen gider, istisna ve indirimlerle düzeltilmiş hâlidir.",
        "5520 sayılı KVK m. 6, 8, 10 ve 11; 193 sayılı GVK m. 38-41",
        "medium",
    ),
    r(
        "Muhasebe kârı içinde gider yazılmış bir kalem KVK'ya göre indirilememektedir. Mali kâra geçişte işlem hangisidir?",
        "Kanunen kabul edilmeyen gider ticari bilanço kârından mali kâra geçişte nasıl düzeltilir?",
        "Ticari kâra eklenir",
        "Matraha eklenir",
        ["Ticari kârdan yeniden indirilir", "İştirak kazancı sayılır", "Geçmiş yıl zararına aktarılır", "Ödenmiş sermayeye eklenir"],
        ["İstisna olarak düşülür", "Dağıtılan kâra eklenir", "Sermaye hesabına kaydedilir", "Beyan dışı bırakılır"],
        "Muhasebede gider olan ancak vergi hukukunda indirilemeyen tutar, mali kâra ulaşırken ticari kâra eklenir.",
        "KKEG'nin matraha eklenmesi, muhasebe kârını vergiye tabi mali kâra dönüştüren olumlu düzeltmedir.",
        "5520 sayılı KVK m. 11; 193 sayılı GVK m. 41",
        "easy",
    ),
    r(
        "Muhasebe kârına dâhil bir kazanç KVK m. 5 uyarınca kurumlar vergisinden istisnadır. Mali kâra geçişte işlem hangisidir?",
        "Ticari bilanço kârına dâhil kurumlar vergisi istisnası matrah hesabında nasıl düzeltilir?",
        "Ticari kârdan indirilir",
        "Matrahtan indirilir",
        ["Kanunen kabul edilmeyen gider olarak eklenir", "Ödenmiş sermayeye aktarılır", "Vergi cezasına dönüştürülür", "Geçmiş yıl zararına eklenir"],
        ["KKEG olarak kâra eklenir", "Yedek akçe sayılır", "Brüt satışa eklenir", "Örtülü sermaye kabul edilir"],
        "Ticari kâr içinde bulunan istisna kazanç, vergi matrahına alınmaması için mali kâr hesabında indirilir.",
        "İstisna kazanç muhasebe kârında yer alsa da kurumlar vergisi matrahından düşülür.",
        "5520 sayılı KVK m. 5 ve 6",
        "easy",
    ),
    r(
        "Vergiye tabi bir gelir muhasebe kayıtlarına ve ticari kâra alınmamıştır. Mali kâra geçişte nasıl işlem yapılır?",
        "Kayıt dışı kalmış vergiye tabi gelir kurumlar vergisi matrahına nasıl yansır?",
        "Ticari kâra eklenir",
        "Matraha eklenir",
        ["İstisna olarak indirilir", "KKEG sayılarak giderleştirilir", "Sermaye hesabında bırakılır", "Beyan dışı tutulur"],
        ["İndirim olarak düşülür", "Geçmiş yıl zararı yapılır", "Yalnız yedek akçeye alınır", "Vergi cezası olarak kaydedilir"],
        "Vergiye tabi olduğu hâlde ticari kâra girmeyen gelir, mali kâra ulaşırken matraha eklenmelidir.",
        "Mali kâr, kayıt dışı bırakılan vergiye tabi gelirleri de kapsamalıdır.",
        "5520 sayılı KVK m. 6; 213 sayılı VUK m. 30",
        "medium",
    ),
    r(
        "Kurum, yeni pay ve borçlanma aracı ihracı için doğrudan gider yapmıştır. KVK'ya göre bu giderin niteliği hangisidir?",
        "Menkul kıymet ihraç giderleri kurum kazancının tespitinde nasıl değerlendirilir?",
        "İndirilebilir kurum gideri",
        "Hasılattan indirilebilir",
        ["Kanunen kabul edilmeyen gider", "Dağıtılmış kâr payı", "Örtülü sermaye faizi", "Yedek akçe"],
        ["Matraha eklenir", "Kâr payı sayılır", "Ödenmiş sermaye sayılır", "Vergi cezasına dönüşür"],
        "KVK m. 8 menkul kıymet ihraç giderlerini ticari kazanç giderlerine ek olarak indirilebilir sayar.",
        "Menkul kıymet ihraç giderleri kurum kazancından indirilebilir.",
        "5520 sayılı KVK m. 8/1-a",
        "easy",
    ),
    r(
        "Yeni kurulan kurum, kuruluş ve örgütlenme sürecine ait giderleri kazançtan indirmek istemektedir. KVK'daki kural hangisidir?",
        "Kuruluş ve örgütlenme giderleri kurum kazancının tespitinde hangi gruptadır?",
        "İndirilebilir",
        "İndirilebilir gider",
        ["Her durumda KKEG'dir", "Dağıtılmış kâr payıdır", "Vergi cezasıdır", "Örtülü sermayedir"],
        ["Kanunen kabul edilmeyen gider", "İştirak kazancı istisnası", "Ödenmiş sermaye", "Geçmiş yıl zararı"],
        "KVK m. 8 kuruluş ve örgütlenme giderlerinin hasılattan indirilebilmesine izin verir.",
        "Kuruluş ve örgütlenme gideri KVK'da ayrıca sayılan indirilebilir kurum giderlerindendir.",
        "5520 sayılı KVK m. 8/1-b",
        "easy",
    ),
    r(
        "Kurum, genel kurul toplantısı ile kanuna uygun birleşme ve tasfiye işlemleri için gider yapmıştır. Bu giderler nasıl değerlendirilir?",
        "Genel kurul, birleşme, devir, bölünme, fesih ve tasfiye giderleri KVK'ya göre hangi niteliktedir?",
        "Hasılattan indirilebilir",
        "İndirilebilir gider",
        ["Yedek akçeye eklenir", "Örtülü kazanç sayılır", "Vergi cezası kabul edilir", "İştirak kazancı yapılır"],
        ["Kanunen kabul edilmeyen gider", "Öz sermaye faizi", "Dağıtılmış kâr payı", "Vergiden istisna gelir"],
        "Kanunda sayılan genel kurul ve yeniden yapılanma giderleri kurum kazancından indirilebilir.",
        "Bu işlemlere ait giderler KVK m. 8'de ayrıca indirilebilecek giderler arasındadır.",
        "5520 sayılı KVK m. 8/1-c",
        "medium",
    ),
    r(
        "Sermayesi paylara bölünmüş komandit şirkette komandite ortağa kâr payı ödenmiştir. Kurum kazancı açısından sonuç hangisidir?",
        "Sermayesi paylara bölünmüş komandit şirkette komandite ortağın kâr payı nasıl değerlendirilir?",
        "İndirilebilir kurum gideri",
        "İndirilebilir gider",
        ["Her durumda KKEG sayılır", "Örtülü sermaye faizi sayılır", "Yedek akçeye eklenir", "Vergi cezası sayılır"],
        ["İştirak kazancı istisnasıdır", "Ödenmiş sermayeye eklenir", "Kurumlar vergisi sayılır", "Transfer fiyatlandırması cezasıdır"],
        "KVK m. 8, komandite ortağın kâr payını kurum kazancından indirilebilir gider sayar.",
        "Komandite ortağın kâr payı bu kurum türü için KVK'da özel indirim olarak düzenlenmiştir.",
        "5520 sayılı KVK m. 8/1-ç",
        "hard",
    ),
    r(
        "Tam mükellef kurum, başka bir tam mükellef kurumun sermayesine katılımından kâr payı elde etmiştir. Genel kural olarak hangi düzenleme gündemdedir?",
        "Yurt içi iştirak kazançları istisnasının temel amacı hangisidir?",
        "İştirak istisnası",
        "Mükerrer kurum vergisini önlemek",
        ["Örtülü sermaye düzeltmesi", "Zarar mahsubu", "Emisyon primi gideri", "Vergi cezası indirimi"],
        ["Her kâr payını gider yazmak", "Kurum sermayesini azaltmak", "Vergi cezalarını silmek", "Yurt içi satışları KDV'den çıkarmak"],
        "Tam mükellef kurumdan elde edilen iştirak kazancı, kanundaki şartlarla kurumlar vergisinden istisnadır.",
        "İştirak kazançları istisnası, dağıtılan kazancın iştirak edilen ve iştirak eden kurumda tekrar vergilenmesini önler.",
        "5520 sayılı KVK m. 5/1-a",
        "medium",
    ),
    r(
        "Kurum geçmiş yıl zararını cari dönem kazancından indirmek istemektedir. Zarar beyannamelerde ayrı gösterilmiş ve süre aşılmamıştır. En fazla taşıma süresi hangisidir?",
        "Geçmiş yıl zararının kurum kazancından indirilebilmesi için temel süre koşulu hangisidir?",
        "Beş yıldan fazla taşınmaması",
        "Beş yıllık taşıma sınırı",
        ["Süresiz taşınabilmesi", "Yalnız aynı ayda kullanılması", "On yıl geriye götürülmesi", "Ortakların ücretinden düşülmesi"],
        ["Zararın süresiz devri", "Yalnız bir ay içinde kullanılması", "Sermayeye eklenmesi", "Dağıtılan kârdan düşülmesi"],
        "Geçmiş yıl zararları, beyannamelerde ayrı gösterilmek ve beş yıldan fazla taşınmamak şartıyla indirilebilir.",
        "KVK m. 9 zarar mahsubunu beş yıllık ileri taşıma süresiyle sınırlar.",
        "5520 sayılı KVK m. 9/1-a",
        "medium",
    ),
    r(
        "Kurum geçmiş yıl zararlarını beyannamede tek toplam tutar hâlinde göstermiş, yıllarını ayırmamıştır. Mahsup koşulu bakımından eksik olan nedir?",
        "Geçmiş yıl zararlarının mahsubunda beyannamede aranan gösterim biçimi hangisidir?",
        "Yılların ayrı gösterilmesi",
        "Yılların ayrı gösterimi",
        ["Zararın ortaklara fatura edilmesi", "Tamamının sermayeye eklenmesi", "Yalnız dipnotta belirtilmesi", "Vergi dairesine sözlü bildirim"],
        ["Tek toplam tutar yazılması", "Ortaklara paylaştırılması", "Yalnız bilançoda saklanması", "Beyanname dışında tutulması"],
        "Zarar mahsubu için geçmiş yıl zararlarının kurumlar vergisi beyannamesinde yıllar itibarıyla ayrı ayrı gösterilmesi gerekir.",
        "Yıllar itibarıyla ayrı gösterim, beş yıllık sürenin ve mahsup sırasının izlenmesini sağlar.",
        "5520 sayılı KVK m. 9/1",
        "hard",
    ),
    r(
        "Kurum KVK m. 10 kapsamındaki bir indirimi doğrudan muhasebe gideri yazmak yerine beyannamede gösterecektir. Temel koşul hangisidir?",
        "KVK m. 10'daki diğer indirimler matrah hesabında nerede gösterilir?",
        "Beyanname üzerinde ayrıca gösterilmesi",
        "Kurumlar vergisi beyannamesinde",
        ["Yalnız ticaret sicilinde gösterilmesi", "Ortakların ücret bordrosuna eklenmesi", "Kasa hesabından doğrudan düşülmesi", "Münferit beyannameye aktarılması"],
        ["Yalnız KDV beyannamesinde", "Ortakların gelir beyannamesinde", "Emlak vergisi bildiriminde", "Muhtasar beyannamede"],
        "KVK m. 10 indirimleri kurumlar vergisi beyannamesi üzerinde ayrıca gösterilerek kurum kazancından sırasıyla indirilir.",
        "Diğer indirimlerin uygulanma yeri yıllık kurumlar vergisi beyannamesidir.",
        "5520 sayılı KVK m. 10/1",
        "medium",
    ),
    r(
        "Kurum kendi öz sermayesi üzerinden ortaklarına faiz hesaplayıp gider yazmıştır. Vergisel sonuç hangisidir?",
        "Öz sermaye üzerinden ödenen veya hesaplanan faiz kurum kazancında nasıl değerlendirilir?",
        "Kanunen kabul edilmeyen gider",
        "İndirilemez",
        ["İndirilebilir finansman gideri", "İştirak kazancı istisnası", "Geçmiş yıl zararı", "Kuruluş gideri"],
        ["Hasılattan indirilir", "İhraç gideri sayılır", "Zarar mahsubu yapılır", "İstisna kazanç kabul edilir"],
        "Öz sermaye üzerinden hesaplanan faiz KVK m. 11 uyarınca kurum kazancından indirilemez.",
        "Kurumun kendi sermayesine yürüttüğü faiz vergi matrahında KKEG niteliğindedir.",
        "5520 sayılı KVK m. 11/1-a",
        "easy",
    ),
    r(
        "Ortakla ilişkili kişiden alınan borcun örtülü sermaye sayılan kısmına faiz ve kur farkı hesaplanmıştır. Bu giderlerin durumu hangisidir?",
        "Örtülü sermaye üzerinden hesaplanan faiz, kur farkı ve benzeri giderler matrahta nasıl işlem görür?",
        "Kurum kazancından indirilemez",
        "Kanunen kabul edilmeyen giderdir",
        ["Genel finansman gideri olarak indirilir", "İştirak kazancı istisnasıdır", "Kuruluş gideri sayılır", "Geçmiş yıl zararıdır"],
        ["Tamamı hasılattan indirilir", "Menkul kıymet ihraç gideridir", "Sponsorluk indirimi sayılır", "Kurumlar vergisinden mahsup edilir"],
        "Örtülü sermaye üzerinden ödenen faiz, kur farkı ve benzeri giderler kurum kazancından indirilemez.",
        "KVK m. 11, örtülü sermaye maliyetlerini KKEG olarak matraha ekletir.",
        "5520 sayılı KVK m. 11/1-b ve 12",
        "medium",
    ),
    r(
        "Kurum, ilişkili kişiye emsallere uygun olmayan bedelle mal satarak kazancı ilişkili kişiye aktarmıştır. Aktarılan kazanç nasıl değerlendirilir?",
        "Transfer fiyatlandırması yoluyla örtülü dağıtılan kazancın kurum matrahındaki sonucu hangisidir?",
        "Kurum kazancından indirilemez",
        "Kanunen kabul edilmeyen indirimdir",
        ["İştirak kazancı istisnası olur", "Geçmiş yıl zararı sayılır", "Kuruluş gideri kabul edilir", "Sermaye artırımı sayılır"],
        ["Hasılattan serbestçe düşülür", "İhraç gideri kabul edilir", "Vergiden istisna kazançtır", "Sponsorluk indirimi olur"],
        "Emsallere aykırı ilişkili kişi işlemiyle örtülü dağıtılan kazanç vergi matrahından indirilemez.",
        "Transfer fiyatlandırması yoluyla örtülü kazanç dağıtımı KVK m. 11'de kabul edilmeyen indirimdir.",
        "5520 sayılı KVK m. 11/1-c ve 13",
        "medium",
    ),
    r(
        "Kurum safi kârından yasal yedek akçe ayırmış ve gider kaydetmiştir. Kurum kazancı açısından sonuç hangisidir?",
        "Kurumun ayırdığı yedek akçeler vergi matrahında nasıl değerlendirilir?",
        "Kurum kazancından indirilemez",
        "Kanunen kabul edilmeyen giderdir",
        ["Genel gider olarak indirilir", "İştirak kazancı istisnasıdır", "Geçmiş yıl zararı sayılır", "Kuruluş gideridir"],
        ["Hasılattan her durumda düşülür", "Menkul kıymet ihraç gideridir", "Vergi kredisi sayılır", "Sermaye zararı olarak taşınır"],
        "Her ne adla ayrılırsa ayrılsın yedek akçeler kurum kazancından indirilemez.",
        "Yedek akçe kârın dağıtım biçimidir; vergi matrahında gider değildir.",
        "5520 sayılı KVK m. 11/1-ç",
        "easy",
    ),
    r(
        "Kurum, hesaplanan kurumlar vergisi ile vergi ve para cezalarını gider yazmıştır. Mali kâra geçişte işlem hangisidir?",
        "Kurumlar vergisi, vergi cezaları ve para cezaları kurum kazancında nasıl değerlendirilir?",
        "Ticari kâra eklenir",
        "Kurum kazancından indirilemez",
        ["İstisna olarak indirilir", "Geçmiş yıl zararı sayılır", "Kuruluş gideri kabul edilir", "İştirak kazancı yapılır"],
        ["Hasılattan genel gider olarak düşülür", "Sermaye artırımı sayılır", "İhraç gideri kabul edilir", "Vergi kredisine dönüşür"],
        "Kurumlar vergisi ile kanundaki ceza ve fer'iler gider yazılmışsa KKEG olarak ticari kâra eklenir.",
        "Bu vergiler ve cezalar KVK m. 11 uyarınca kurum kazancından indirilemez.",
        "5520 sayılı KVK m. 11/1-d",
        "easy",
    ),
    r(
        "Kurum, esas faaliyetiyle ilgisiz özel uçağın gider ve amortismanını kurum kazancından indirmiştir. Vergisel sonuç hangisidir?",
        "Esas faaliyetle ilgisiz yat, tekne, uçak ve helikopter giderleri matrahta nasıl değerlendirilir?",
        "Kurum kazancından indirilemez",
        "Kanunen kabul edilmeyen giderdir",
        ["Genel gider olarak tamamen indirilir", "Kuruluş gideri sayılır", "İştirak kazancı istisnasıdır", "Geçmiş yıl zararıdır"],
        ["Hasılattan serbestçe indirilir", "Menkul kıymet ihraç gideridir", "Sponsorluk indirimi sayılır", "Vergi mahsubuna konu olur"],
        "İşletmenin esas faaliyet konusu ile ilgili olmayan hava ve deniz taşıtlarının gider ve amortismanı indirilemez.",
        "KVK m. 11 bu özel taşıt giderlerini KKEG olarak düzenler.",
        "5520 sayılı KVK m. 11/1-f",
        "medium",
    ),
    r(
        "Kurum, ortağından aldığı ve işletmede kullandığı borcun hesap dönemi içinde öz sermayenin üç katını aşan kısmını belirlemiştir. Bu kısım nedir?",
        "Örtülü sermaye hesabında öz sermaye karşılaştırması hangi döneme ait öz sermayeyle yapılır?",
        "Örtülü sermaye",
        "Dönem başı öz sermayesiyle",
        ["Ödenmiş sermaye indirimi", "İştirak kazancı", "Geçmiş yıl zararı", "Kuruluş gideri"],
        ["Dönem sonu satış hasılatıyla", "Ortakların kişisel servetiyle", "Dağıtılan kâr payıyla", "Kurumun piyasa değeriyle"],
        "Ortak veya ilişkili kişiden sağlanıp kullanılan borcun öz sermayenin üç katını aşan kısmı örtülü sermayedir.",
        "Örtülü sermaye karşılaştırmasında VUK'a göre tespit edilmiş hesap dönemi başı öz sermayesi esas alınır.",
        "5520 sayılı KVK m. 12/1 ve 3-b",
        "hard",
    ),
    r(
        "Kurum ilişkili kişiden aldığı mal için bağımsız taraflar arasında oluşacak bedelden farklı fiyat uygulamıştır. Hangi ilke test edilir?",
        "Emsallere uygunluk ilkesi ilişkili kişi işlemindeki fiyatı neyle karşılaştırır?",
        "Emsallere uygunluk ilkesi",
        "Bağımsız işlem fiyatıyla",
        ["Vergi mahremiyeti ilkesi", "Tahakkuk esası", "Dönemsellik ilkesi", "İştirak istisnası"],
        ["Kurumun ödenmiş sermayesiyle", "Ortağın kişisel geliriyle", "Geçmiş yıl zararıyla", "Vergi cezası tutarıyla"],
        "İlişkili kişi işlem bedeli, aralarında ilişki bulunmayan taraflar arasında oluşacak bedele uygun olmalıdır.",
        "Emsallere uygunluk ilkesi, kontrollü işlem fiyatını bağımsız taraf koşullarıyla karşılaştırır.",
        "5520 sayılı KVK m. 13/1 ve 3",
        "medium",
    ),
    r(
        "Kurum ilişkili kişisiyle yaptığı kiralama işleminde emsallere aykırı bedel kullanmıştır. Transfer fiyatlandırması kapsamına girer mi?",
        "Transfer fiyatlandırmasında mal veya hizmet alım satımı sayılan işlemler arasında hangisi de bulunur?",
        "Evet; kiralama işlemleri kapsamdadır",
        "Kiralama işlemleri",
        ["Hayır; yalnız mal satışı kapsamdadır", "Hayır; kira her durumda istisnadır", "Yalnız bağımsız kişi kirası kapsamdadır", "Sadece bedelsiz işlemler kapsamdadır"],
        ["Yalnız vergi cezası ödemeleri", "Ortağın kişisel tüketimi", "Beyanname verilmesi", "Sermaye tescili"],
        "Kiralama ve kiraya verme işlemleri transfer fiyatlandırmasında mal veya hizmet alım satımı kapsamında değerlendirilir.",
        "KVK m. 13 kontrollü kira işlemlerini de emsallere uygunluk denetimine tabi tutar.",
        "5520 sayılı KVK m. 13/1",
        "medium",
    ),
    r(
        "Transfer fiyatlandırması yoluyla örtülü dağıtılan kazanç için hesap dönemi sonu itibarıyla ikinci düzeltme yapılacaktır. Dağıtılan tutar ne sayılır?",
        "Örtülü dağıtılan kazanç gelir ve kurumlar vergisi uygulamasında hangi niteliği kazanır?",
        "Dağıtılmış kâr payı",
        "Dağıtılmış kâr payı",
        ["Kuruluş gideri", "Geçmiş yıl zararı", "Menkul kıymet ihraç gideri", "Yedek akçe indirimi"],
        ["İştirak maliyeti", "Ödenmiş sermaye", "Vergi cezası", "Genel yönetim gideri"],
        "Örtülü dağıtılan kazanç, hesap dönemi sonu itibarıyla dağıtılmış kâr payı; dar mükellefte ana merkeze aktarılan tutar sayılır.",
        "İkincil düzeltme, örtülü kazancı kâr payı niteliğine dönüştürür.",
        "5520 sayılı KVK m. 13/6",
        "hard",
    ),
    r(
        "Kurumun ortakları şirket zararını kapatmak üzere TTK m. 376 kararı kapsamında karşılıksız tutar aktarmıştır. Bu tutar kurum kazancında nasıl değerlendirilir?",
        "Sermayenin tamamlanması kararıyla ortakların zarar kapatma ödemesi KVK'ya göre hangi sonucu doğurur?",
        "Kurum kazancına alınmaz",
        "Kurum kazancında dikkate alınmaz",
        ["Vergiye tabi hasılat sayılır", "Dağıtılmış kâr payı sayılır", "Örtülü sermaye faizi sayılır", "Menkul sermaye iradı olur"],
        ["Ticari satış geliri sayılır", "Transfer fiyatlandırması kazancı olur", "Kurumlar vergisi cezasına dönüşür", "İştirak kazancı istisnası sayılır"],
        "TTK m. 376 kapsamında zarar nedeniyle karşılıksız kalan kısmı kapatmak için ortakların aktardığı tutar kurum kazancında dikkate alınmaz.",
        "Bu zarar tamamlama ödemesi KVK m. 6/3 uyarınca vergiye tabi kurum kazancı değildir.",
        "5520 sayılı KVK m. 6/3; 6102 sayılı TTK m. 376",
        "hard",
    ),
    r(
        "Kurum ticari bilanço zararına rağmen vergiye göre kabul edilmeyen giderleri eklediğinde pozitif mali kâra ulaşmıştır. Kurumlar vergisi açısından sonuç hangisidir?",
        "Ticari zarar bulunması kurumlar vergisi matrahının da mutlaka zarar olmasını gerektirir mi?",
        "Mali kâr üzerinden vergi doğabilir",
        "Hayır; düzeltmeler mali kâr yaratabilir",
        ["Ticari zarar varsa vergi asla doğmaz", "KKEG'ler ticari zarardan indirilmeye devam eder", "Yalnız dağıtılan kâr vergilenir", "Vergi matrahı öz sermayeye eşit olur"],
        ["Evet; iki sonuç her zaman aynıdır", "Evet; KKEG'ler matrahı azaltır", "Evet; istisnalar matraha eklenir", "Hayır; yalnız sermaye vergilenir"],
        "KKEG ve diğer olumlu düzeltmeler ticari zararı aşarsa mali kâr ve kurumlar vergisi matrahı oluşabilir.",
        "Muhasebe sonucu ile vergi matrahı farklı kurallara tabi olduğundan ticari zarar mali zararı zorunlu kılmaz.",
        "5520 sayılı KVK m. 6 ve 11",
        "hard",
    ),
]


PREMISES = [
    {"stem":"Ticari bilanço kârından mali kâra geçiş bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KKEG ticari kâra eklenir\n\nII. İstisna kazanç matrahtan indirilir\n\nIII. Vergiye tabi kayıt dışı gelir matraha eklenir","correct":"I, II ve III","why":"Üç işlem de ticari muhasebe sonucunu vergi mevzuatına göre mali kâra dönüştüren düzeltmelerdir.","ref":"5520 sayılı KVK m. 5, 6 ve 11","difficulty":"medium"},
    {"stem":"Kurum kazancından indirilebilen giderler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Menkul kıymet ihraç gideri indirilebilir\n\nII. Kuruluş ve örgütlenme gideri indirilebilir\n\nIII. Hesaplanan kurumlar vergisi indirilebilir","correct":"I ve II","why":"İhraç ile kuruluş giderleri m. 8 kapsamında indirilebilir; kurumlar vergisi m. 11 uyarınca indirilemez.","ref":"5520 sayılı KVK m. 8 ve 11","difficulty":"easy"},
    {"stem":"Kabul edilmeyen indirimler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Öz sermaye faizi indirilemez\n\nII. Her genel kurul gideri indirilemez\n\nIII. Yedek akçe kurum kazancından indirilemez","correct":"I ve III","why":"Öz sermaye faizi ve yedek akçe KKEG'dir; genel kurul gideri m. 8 kapsamında indirilebilir.","ref":"5520 sayılı KVK m. 8/1-c ve 11/1-a, ç","difficulty":"medium"},
    {"stem":"Örtülü sermaye bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Her üçüncü kişi borcu örtülü sermayedir\n\nII. Ortak veya ilişkili kişiden sağlanan belirli borçlar kapsama girebilir\n\nIII. Karşılaştırmada hesap dönemi başı öz sermayesi esas alınır","correct":"II ve III","why":"Örtülü sermaye ortak veya ilişkili kişi borçlarına ilişkin koşullara bağlıdır ve dönem başı öz sermayeyle karşılaştırılır.","ref":"5520 sayılı KVK m. 12","difficulty":"hard"},
    {"stem":"Geçmiş yıl zararı mahsubu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Zararlar yıllar itibarıyla ayrı gösterilir\n\nII. Beş yıldan fazla taşınamaz\n\nIII. Süre ve beyan koşulu olmadan sınırsız indirilebilir","correct":"I ve II","why":"Mahsup için zararların ayrı gösterilmesi ve beş yıllık taşıma sınırına uyulması gerekir.","ref":"5520 sayılı KVK m. 9","difficulty":"medium"},
    {"stem":"Transfer fiyatlandırması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İlişkili kişi işlemlerinde emsallere uygunluk aranır\n\nII. Kiralama işlemleri de kapsama girebilir\n\nIII. Örtülü dağıtılan kazanç kâr payı sayılabilir","correct":"I, II ve III","why":"Üç ifade de KVK m. 13'ün işlem kapsamı, emsal ilkesi ve ikincil düzeltme hükümlerine uygundur.","ref":"5520 sayılı KVK m. 13","difficulty":"hard"},
    {"stem":"Mali kâr düzeltmeleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gider yazılan vergi cezası matraha eklenir\n\nII. İştirak kazancı istisnası KKEG olarak eklenir\n\nIII. Vergiden istisna kazanç ticari kârdan indirilebilir","correct":"I ve III","why":"Vergi cezası KKEG olarak eklenir; istisna kazanç matrahtan indirilir.","ref":"5520 sayılı KVK m. 5 ve 11/1-d","difficulty":"medium"},
    {"stem":"Kurum kazancının yapısı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kurumlar vergisi yalnız dağıtılan kârdan alınır\n\nII. Safi kurum kazancında GVK'nın ticari kazanç hükümleri uygulanır\n\nIII. Ticari zarar bulunmasına rağmen vergi düzeltmeleri mali kâr doğurabilir","correct":"II ve III","why":"Vergi safi kurum kazancından alınır; ticari kazanç hükümleri ve vergi düzeltmeleri nedeniyle muhasebe sonucu ile mali sonuç ayrışabilir.","ref":"5520 sayılı KVK m. 6 ve 11","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="kurumlar_vergisi",
        topic_id="kurum_kazanci",
        label="Kurum Kazancı",
        slug="kurum_kazanci",
        prefix="topic-kv-kk",
        seed=170729,
        legislation_version="5520 sayılı Kurumlar Vergisi Kanunu ve ilgili GVK/VUK hükümleri, 17.07.2026 tarihinde yürürlükteki metinler",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
