#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Disiplin, 3×20 güncel özgün soru."""
from topic_pack_builder import write_topic


DISTRACTOR_EXPANSIONS = {
    "Uyarma": "Uyarma cezası verilmesi",
    "Kınama": "Kınama cezası verilmesi",
    "Geçici alıkoyma": "Geçici faaliyet yasağı uygulanması",
    "Meslekten çıkarma": "Meslekten çıkarma cezası verilmesi",
    "Yeminli sıfatını kaldırma": "Yeminli sıfatının kaldırılması",
    "Yalnız uyarma": "Yalnız uyarma cezası verilmesi",
    "Yalnız kınama": "Yalnız kınama cezası verilmesi",
    "Yalnız yeni bir uyarma": "Yalnız yeni bir uyarma cezası verilmesi",
    "Yalnız yeni kınama": "Yalnız yeni bir kınama cezası verilmesi",
    "Yalnız sözlü uyarı": "Yalnız sözlü uyarıyla yetinilmesi",
    "Yalnız sözlü tavsiye": "Yalnız sözlü tavsiyeyle yetinilmesi",
    "Ceza verilmemesi": "Herhangi bir disiplin cezası verilmemesi",
}


def r(s, f, c, d, w, ref, difficulty="medium", *, fc=None, fd=None, fw=None, fr=None):
    """Bir kazanımın olay ve doğrudan bilgi varyantlarını tanımlar."""
    return {
        "scenario": s,
        "focus": f,
        "correct": c,
        "focus_correct": fc or c,
        "distractors": [DISTRACTOR_EXPANSIONS.get(x, x) for x in d],
        "focus_distractors": [DISTRACTOR_EXPANSIONS.get(x, x) for x in (fd or d)],
        "why": w,
        "focus_why": fw or f"Bu doğrudan soruda belirleyici kural şudur: {w}",
        "ref": ref,
        "focus_ref": fr or ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Oda, staj yapan aday meslek mensubunun Disiplin Yönetmeliği dışında kaldığını ileri sürmüştür. Bu görüş doğru mudur?",
        "Disiplin Yönetmeliğinin kişi bakımından kapsamı hangisidir?",
        "Hayır; disiplin esasları adaya da uygulanır",
        ["Evet; yalnız ruhsatlı YMM'ye uygulanır", "Evet; adaylar her koşulda tamamen kapsam dışıdır", "Yalnız müşterilere uygulanır", "Sadece oda çalışanlarına uygulanır"],
        "Yönetmelik, meslek mensupları yanında aday meslek mensuplarını da disiplin esaslarına tabi tutar.",
        "Disiplin Yönetmeliği m. 1 ve 10",
        "easy",
        fc="Meslek ve aday meslek mensupları",
        fd=["Yalnız oda personeli", "Sadece YMM müşterileri", "Yalnız kamu görevlileri", "Sadece emekli meslek mensupları ve müşterileri"],
    ),
    r(
        "Bir dosya, şikâyetin odaya ulaşmasından disiplin kuruluna sevk edilmesine kadar ilerlemiştir. Bu aşama nasıl adlandırılır?",
        "Disiplin kovuşturması hangi zaman aralığını ifade eder?",
        "Disiplin soruşturması",
        ["Disiplin kovuşturması", "İdari yargılama", "Ceza infazı", "Mesleki staj"],
        "Soruşturma, ihbar veya istemin odaya ulaşmasından dosyanın disiplin kuruluna sevkine kadar olan aşamadır.",
        "Disiplin Yönetmeliği m. 3",
        "easy",
        fc="Kurula intikalden kararın kesinleşmesine kadar",
        fd=["Şikâyetten yönetim kuruluna sevke kadar", "Yalnız ceza davası açılıncaya kadar", "Ruhsat başvurusundan mesleki stajın sonuna kadar", "Kesinleşmeden cezanın silinmesine kadar"],
        fw="Kovuşturma, dosyanın disiplin kuruluna intikalinden disiplin kurulu kararının kesinleşmesine kadar sürer.",
    ),
    r(
        "Kurul, Yönetmelikte bulunmayan 'iki ay ruhsat askıya alma' adlı yeni bir ceza uygulamak istemektedir. Mümkün müdür?",
        "Yönetmelikte meslek mensupları için kaç temel disiplin cezası türü sayılmıştır?",
        "Hayır; Yönetmelikteki cezalarla sınırlıdır",
        ["Evet; kurul her olayda sınırsız yeni ceza koyabilir", "Evet; müşteri istediği cezayı belirler", "Yalnız para cezası uygulanabilir", "Ceza türünü vergi dairesi seçer"],
        "Ceza türleri uyarma, kınama, geçici alıkoyma, yeminli sıfatını kaldırma ve meslekten çıkarmadır.",
        "Disiplin Yönetmeliği m. 4",
        "easy",
        fc="Beş temel ceza türü",
        fd=["İki temel ceza türü", "Üç temel ceza türü", "Altı temel ceza türü", "Yedi temel ceza türü"],
    ),
    r(
        "Meslek mensubuna, mesleğin yürütülmesinde daha dikkatli davranması gerektiği yazıyla bildirilmiştir. Uygulanan ceza hangisidir?",
        "Kınama cezası neyi ifade eder?",
        "Uyarma",
        ["Kınama", "Geçici alıkoyma", "Meslekten çıkarma", "Yeminli sıfatını kaldırma"],
        "Uyarma, mesleğin yürütülmesinde daha dikkatli davranılması gerektiğinin yazılı bildirimidir.",
        "Disiplin Yönetmeliği m. 4/a",
        "easy",
        fc="Kusurlu olduğunun yazıyla bildirilmesi",
        fd=["Dikkatli olma gereğinin sözlü söylenmesi", "Ruhsatın bir daha verilmemesi", "Mührün denetimsiz bırakılması", "Yalnız aidat borcunun tahsili"],
        fw="Kınama, görev ve davranışlarda kusurlu olunduğunun yazıyla bildirilmesidir.",
        fr="Disiplin Yönetmeliği m. 4/b",
    ),
    r(
        "Kurul, olağan geçici alıkoyma cezasını dört ay olarak belirlemiştir. Süre yönünden doğru mudur?",
        "Geçici olarak mesleki faaliyetten alıkoyma cezasının olağan süre aralığı nedir?",
        "Hayır; alt sınır altı aydır",
        ["Evet; alt sınır bir aydır", "Evet; süre tamamen sınırsızdır", "Hayır; ceza daima beş yıldır", "Hayır; yalnız on yıl olabilir"],
        "Her bir eylem için geçici alıkoyma cezası altı aydan az, bir yıldan fazla olamaz.",
        "Disiplin Yönetmeliği m. 4/c ve 7",
        "medium",
        fc="Altı ay ile bir yıl arasında",
        fd=["Bir ay ile üç ay arasında", "İki yıl ile beş yıl arasında", "Yalnız süresiz olarak", "Tam olarak on beş gün"],
    ),
    r(
        "YMM'nin yeminli sıfatı kaldırılmış, ancak mührü kendisinde bırakılmıştır. İşlem eksiksiz midir?",
        "Meslekten çıkarma cezasının temel sonucu nedir?",
        "Hayır; mühür de geri alınmalıdır",
        ["Evet; mühür hiçbir zaman geri alınmaz", "Evet; yalnız müşteri listesi değişir", "Hayır; sadece aidat artırılmalıdır", "Hayır; staj yeniden başlatılmalıdır"],
        "Yeminli sıfatının kaldırılması, YMM sıfatının kaldırılmasıyla birlikte mührün geri alınmasını gerektirir.",
        "Disiplin Yönetmeliği m. 4/d",
        "medium",
        fc="Ruhsatı geri alıp mesleği sürekli yasaklama",
        fd=["Yalnız dikkatli olma yazısı gönderilmesi", "En çok bir yıllık geçici mesleki faaliyet yasağı", "YMM mührünün yenisiyle değiştirilmesi", "Aidat borcunun takside bağlanması"],
        fw="Meslekten çıkarma, ruhsatın geri alınarak mesleğin yeniden yürütülmesine izin verilmemesidir.",
        fr="Disiplin Yönetmeliği m. 4/e",
    ),
    r(
        "Sözleşmesi sona eren müşterinin defter ve belgeleri, odaya bildirilen haklı bir teslim engeli olmadan 45 gün tutulmuştur. Hangi ceza gündeme gelir?",
        "Fesih sonrası müşteri defter ve belgeleri kural olarak kaç gün içinde tutanakla teslim edilmelidir?",
        "Uyarma cezası",
        ["Doğrudan meslekten çıkarma", "Yeminli sıfatını kaldırma", "Üç yıl geçici alıkoyma", "Hiçbir disiplin sonucu doğmaz"],
        "Haklı teslim engelinin odaya bildirildiği durum hariç, defter ve belgelerin 30 gün içinde tutanakla teslim edilmemesi uyarma nedenidir.",
        "Disiplin Yönetmeliği m. 5/a",
        "medium",
        fc="Otuz gün içinde",
        fd=["Yedi gün içinde", "Altmış gün içinde", "Bir yıl içinde", "Süre aranmaksızın"],
    ),
    r(
        "Oda aidat borcu en az iki kez yazıyla istenmiş, meslek mensubu haklı neden göstermeden ödememiştir. Hangi yaptırım söz konusudur?",
        "Adres değişikliğinin süresinde bildirilmemesi hangi ceza grubunda sayılmıştır?",
        "Uyarma cezası",
        ["Meslekten çıkarma", "Yeminli sıfatını kaldırma", "Üç yıl alıkoyma", "Adli para cezası"],
        "En az iki yazılı isteme rağmen haklı neden olmadan aidat ödememek ve adres değişikliğini süresinde bildirmemek uyarma nedenlerindendir.",
        "Disiplin Yönetmeliği m. 5/h-i",
        "easy",
        fc="Uyarma cezası",
        fd=["Doğrudan meslekten çıkarma", "Yeminli sıfatını kaldırma", "Süresiz faaliyet yasağı", "Hapis cezası"],
    ),
    r(
        "Meslek mensubu üç yıllık dönemde, ilk iki ceza kesinleşip bildirildikten sonra üçüncü kez uyarma gerektiren eylem işlemiştir. Sonuç nedir?",
        "Yürürlükteki 2026 kuralına göre üç yıllık dönemde üçüncü uyarma eylemi hangi cezayı gerektirir?",
        "Kınama cezası",
        ["Yalnız yeni bir uyarma", "Doğrudan meslekten çıkarma", "Yeminli sıfatını kaldırma", "Ceza verilmemesi"],
        "Koşulları oluştuğunda üç yıllık dönemde üçüncü uyarma eylemi kınama nedenidir.",
        "Disiplin Yönetmeliği m. 6/a ve 11",
        "hard",
    ),
    r(
        "Meslek mensubu yazılı hizmet sözleşmesi yapmadan iş kabul etmiş ve sözleşmeyi e‑Birlik'e de girmemiştir. Hangi ceza gündeme gelir?",
        "Mesleki hizmet sözleşmesini Birliğin belirlediği sürede e‑Birlik'e girmemek hangi ceza nedenidir?",
        "Kınama cezası",
        ["Yalnız sözlü hatırlatma", "Meslekten çıkarma", "Yeminli sıfatını kaldırma", "Beş yıl alıkoyma"],
        "Yazılı hizmet sözleşmesiz iş kabulü ve sözleşmenin süresinde e‑Birlik'e girilmemesi kınama nedenidir.",
        "Disiplin Yönetmeliği m. 6/d",
        "medium",
    ),
    r(
        "Meslek mensubu reklam yasağına aykırı tanıtım yapmıştır. Yönetmelikteki karşılığı hangisidir?",
        "2026 yılı asgari ücret tarifesinin altında iş kabul edilmesi hangi disiplin cezası nedenidir?",
        "Kınama cezası",
        ["Uyarı gerektirmeyen davranış", "Doğrudan meslekten çıkarma", "Yeminli sıfatını kaldırma", "Sadece vergi cezası"],
        "Reklam yasağına uymamak ve asgari tarifenin altında iş kabul etmek kınama nedenleri arasındadır.",
        "Disiplin Yönetmeliği m. 6/f-g",
        "medium",
        fc="Kınama cezası",
        fd=["Doğrudan meslekten çıkarma", "Yalnız sözlü tavsiye", "Üç yıl faaliyet yasağı", "Mührün yenilenmesi"],
    ),
    r(
        "Meslek mensubu üç yıllık dönemde, önceki iki ceza kesinleşip bildirildikten sonra üçüncü kez kınama gerektiren eylem işlemiştir. Sonuç nedir?",
        "Üç yıllık dönemde üçüncü kınama eylemi hangi ceza düzeyine yükselir?",
        "Geçici mesleki faaliyetten alıkoyma",
        ["Yalnız uyarma", "Yalnız yeni kınama", "Yeminli sıfatını kaldırma", "Ceza verilmemesi"],
        "Koşulları oluştuğunda üç yıllık dönemde üçüncü kınama eylemi geçici alıkoyma nedenidir.",
        "Disiplin Yönetmeliği m. 7/a ve 11",
        "hard",
    ),
    r(
        "Meslek mensubunun ticari faaliyet yasağına aykırı davrandığı saptanmıştır. Hangi ceza türü gündeme gelir?",
        "Meslek mensubu olmayan kişiyle mevzuata aykırı iş birliği yapılmasının disiplin karşılığı nedir?",
        "Geçici mesleki faaliyetten alıkoyma",
        ["Yalnız uyarma", "Kınama ile sınırlı sonuç", "Yeminli sıfatını kaldırma", "Hiçbir disiplin sonucu yoktur"],
        "Ticari faaliyet yasağının ihlali ve yetkisiz kişilerle aykırı iş birliği geçici alıkoyma nedenlerindendir.",
        "Disiplin Yönetmeliği m. 7/c ve 7/e",
        "medium",
        fc="Geçici mesleki faaliyetten alıkoyma",
        fd=["Yalnız sözlü uyarı", "Aidatın artırılması", "Meslekten kendiliğinden ayrılma", "Ceza verilmemesi"],
    ),
    r(
        "YMM'nin tasdik yetkisini mükerreren ve kasten gerçeğe aykırı kullandığı mahkeme kararıyla kesinleşmiştir. Hangi ceza uygulanır?",
        "Yeminli sıfatını kaldırma için kasıt ve tekrar yanında hangi güvence aranır?",
        "Yeminli sıfatını kaldırma",
        ["Yalnız uyarma", "Yalnız kınama", "Altı aylık staj", "Ceza verilmemesi"],
        "Mükerrer kasıtlı tasdik aykırılığının mahkeme kararıyla kesinleşmesi yeminli sıfatının kaldırılmasını gerektirir.",
        "Disiplin Yönetmeliği m. 8",
        "hard",
        fc="Mahkeme kararının kesinleşmesi",
        fd=["Müşterinin sözlü kanaati", "Oda personelinin tahmini", "Yeni staj başvurusu", "Aidat ödeme makbuzunun düzenlenmesi"],
    ),
    r(
        "Meslek mensubunun kasten vergi zıyaına sebep olduğu yalnız bir ihbarla ileri sürülmüş, kesinleşmiş mahkeme kararı yoktur. Hemen meslekten çıkarılabilir mi?",
        "Kasten vergi zıyaına sebep olma hangi koşulla meslekten çıkarma nedenidir?",
        "Hayır; mahkeme kararıyla kesinleşmelidir",
        ["Evet; isimsiz ihbar tek başına yeterlidir", "Evet; müşteri kanaati kesin delildir", "Evet; oda aidat borcu yeterlidir", "Hayır; bu fiile hiçbir ceza verilemez"],
        "Kasten vergi zıyaına sebebiyet verme, mahkeme kararıyla kesinleştiğinde meslekten çıkarma nedenidir.",
        "Disiplin Yönetmeliği m. 9/c",
        "hard",
        fc="Mahkeme kararıyla kesinleştiğinde",
        fd=["Sözlü söylenti duyulduğunda", "Müşteri tek başına yazılı olarak istediğinde", "Aidat geciktiğinde", "Staj süresi dolduğunda"],
    ),
    r(
        "Meslek mensubu ruhsatını başka kişiye kullandırmış ve kendi adına müşteri kabul etmesine izin vermiştir. Hangi ceza gündeme gelir?",
        "Başka meslek mensubunun ad ve unvanıyla beyanname düzenleyip imzalamak hangi ceza nedenidir?",
        "Meslekten çıkarma",
        ["Yalnız uyarma", "Yalnız kınama", "Aidat artırımı", "Ceza verilmemesi"],
        "Ruhsatı başkasına kullandırmak ve başka meslek mensubunun adıyla beyanname düzenlemek meslekten çıkarma nedenidir.",
        "Disiplin Yönetmeliği m. 9/d-e",
        "hard",
    ),
    r(
        "Kurul, gerekçesini kararında açıklayarak olayın özellikleri nedeniyle bir derece hafif ceza seçmiştir. Takdir yetkisi var mıdır?",
        "Bir derece hafif ceza takdiriyle ortadan kaldırılamayan ceza hangisidir?",
        "Evet; gerekçeli bir derece hafif ceza seçebilir",
        ["Hayır; hiçbir takdir yetkisi yoktur", "Evet; gerekçe göstermesi gerekmez", "Yalnız müşteri ceza derecesini seçer", "Sadece mahkeme yeni ceza koyabilir"],
        "Disiplin kurulu gerekçeli olarak bir derece ağır veya hafif ceza seçebilir; uyarma hafifletilerek ortadan kaldırılamaz.",
        "Disiplin Yönetmeliği m. 11",
        "medium",
        fc="Uyarma cezası",
        fd=["Kınama cezası", "Geçici alıkoyma cezası", "Yeminli sıfatını kaldırma", "Meslekten çıkarma cezası"],
    ),
    r(
        "Kesinleşen disiplin cezası oda disiplin kurulu sekreterince uygulanmaya başlanmıştır. Yetkili makam bakımından doğru mudur?",
        "Oda disiplin kurulu kararının onaylı örneği kaç gün içinde Birlik Disiplin Kurulu Başkanlığına gönderilir?",
        "Hayır; oda yönetim kurulu başkanlığı uygular",
        ["Evet; yalnız kurul sekreteri uygular", "Evet; müşteri cezanın infazını yapar", "Hayır; vergi mahkemesi uygular", "Hayır; staj komisyonu uygular"],
        "Kesinleşen cezayı ilgili oda yönetim kurulu başkanlığı uygular; karar örneği 30 gün içinde Birliğe gönderilir.",
        "Disiplin Yönetmeliği m. 12",
        "medium",
        fc="Otuz gün içinde",
        fd=["Yedi gün içinde", "Doksan gün içinde", "Bir yıl içinde", "Süre bulunmaksızın"],
    ),
    r(
        "Kesinleşen kınama cezası diğer bütün kurumlara duyurulup Resmî Gazete'de ilan edilmek istenmektedir. Güncel kurala uygun mudur?",
        "Güncel düzenlemede hangi cezalar Resmî Gazete'de ilan edilir?",
        "Hayır; kınama bu ilan kapsamının dışındadır",
        ["Evet; bütün cezalar ilan edilir", "Evet; yalnız kınama ilan edilir", "Hayır; hiçbir ceza ilan edilmez", "Hayır; sadece uyarma ilan edilir"],
        "Uyarma ve kınama dışındaki cezalar ilgili kurumlara duyurulur; geçici alıkoyma, yeminli sıfatını kaldırma ve meslekten çıkarma Resmî Gazete'de ilan edilir.",
        "Disiplin Yönetmeliği m. 12 (14.01.2026 değişikliği işlenmiş)",
        "hard",
        fc="Geçici alıkoyma, yeminli sıfatını kaldırma ve çıkarma",
        fd=["Uyarma, kınama ve geçici alıkoyma cezaları", "Yalnız uyarma ve kınama cezaları", "Bütün disiplin cezaları birlikte", "Hiçbir disiplin cezası ilan edilmez"],
    ),
    r(
        "Disiplin fiilinin üzerinden altı yıl geçmiş, fiil suç oluşturmuyor ve süresinde odaya giren şikâyetle zamanaşımı durmamıştır. Soruşturma yapılabilir mi?",
        "Meslekten ayrılıp oda kaydını sildirmek önceki mesleki fiiller için disiplin işlemini engeller mi?",
        "Hayır; olağan zamanaşımı beş yıldır",
        ["Evet; olağan süre on yıldır", "Evet; hiçbir zamanaşımı yoktur", "Evet; süre yalnız bir aydır", "Hayır; olağan süre altı aydır"],
        "Olağan süre fiilden itibaren beş yıldır; suç için daha uzun süre varsa o uygulanır ve meslekten ayrılma işlemi engellemez.",
        "Disiplin Yönetmeliği m. 14",
        "hard",
        fc="Hayır; önceki fiiller için işlem yapılabilir",
        fd=["Evet; oda kaydı silinince dosya zorunlu kapanır", "Evet; yalnız müşteri isterse kapanır", "Evet; bütün kanıtlar yok sayılır", "Hayır; fakat ceza verilmesi yasaktır"],
    ),
    r(
        "Meslek mensubu hakkında kovuşturma gerekip gerekmediğini anlamak için oda disiplin kurulu doğrudan soruşturma başlatmıştır. Yetki düzeni doğru mudur?",
        "Disiplin soruşturması açılması ve kovuşturmaya geçilip geçilmeyeceği kararını hangi organ verir?",
        "Hayır; soruşturmayı yönetim kurulu yaptırır",
        ["Evet; müşteri tek başına başlatır", "Evet; staj komisyonu karar verir", "Hayır; yalnız vergi mahkemesi başlatır", "Hayır; noter kurulu başlatır"],
        "Soruşturmayı oda yönetim kurulu yaptırır ve kovuşturma açılıp açılmayacağına yine yönetim kurulu karar verir.",
        "Disiplin Yönetmeliği m. 15 ve 19-20",
        "medium",
        fc="İlgili oda yönetim kurulu",
        fd=["Müşteri kabul komisyonu", "Vergi dairesi müdürlüğü", "Staj değerlendirme kurulu", "Ticaret sicili müdürlüğü"],
    ),
    r(
        "Kimlik, adres ve imza içermeyen şikâyet dilekçesi odaya ulaşmıştır. Oda hiçbir belirti de görmemiştir. Dilekçenin durumu nedir?",
        "İsimsiz ihbar işleme konulmasa bile oda yönetim kurulunun kendiliğinden soruşturma yetkisi var mıdır?",
        "Kimliksiz ve imzasız ihbar işleme konulmaz",
        ["Her durumda doğrudan ceza verilir", "Dilekçe mahkeme kararı sayılır", "Yalnız imza eksikliği önemsizdir", "Şikâyet kesin hüküm oluşturur"],
        "Kimlik, adres ve imzasız ihbar işleme konulmaz; ancak oda gerekli görürse konu hakkında resen soruşturma yapabilir.",
        "Disiplin Yönetmeliği m. 17",
        "medium",
        fc="Evet; gerekli görürse resen soruşturur",
        fd=["Hayır; hiçbir koşulda inceleyemez", "Yalnız müşteri izin verirse soruşturur", "Sadece noter kararıyla soruşturur", "Yalnız stajyerler karar verebilir"],
    ),
    r(
        "Soruşturmacı, bilgi istem yazısında konuyu açıkça belirtmiş fakat meslek mensubuna yalnız beş gün vermiştir. Süre uygun mudur?",
        "Oda yönetim kurulu soruşturmayı ihbar, şikâyet veya istem tarihinden itibaren en geç ne kadar sürede sonuçlandırır?",
        "Hayır; asgari bilgi süresi on beş gündür",
        ["Evet; bir gün bile yeterlidir", "Evet; süre verilmesi yasaktır", "Hayır; süre en az bir yıldır", "Hayır; süre tam otuz gündür"],
        "Soruşturmada bilgi için en az 15 gün verilir; yönetim kurulu soruşturmayı en geç altı ayda sonuçlandırır.",
        "Disiplin Yönetmeliği m. 19",
        "hard",
        fc="Altı ay içinde",
        fd=["On beş gün içinde", "İki yıl içinde", "Beş yıl içinde", "Süresiz olarak"],
    ),
    r(
        "Disiplin kurulu, meslek mensubunun savunmasını almadan ceza vermiştir. Bildirimle en az 15 günlük savunma süresi de tanınmamıştır. Karar usule uygun mudur?",
        "Mali tatil döneminde savunma istenmesi ve duruşma yapılması mümkün müdür?",
        "Hayır; savunma alınmadan ceza verilemez",
        ["Evet; savunma hiçbir zaman aranmaz", "Evet; müşteri beyanı savunmanın yerini alır", "Evet; yalnız kınamada savunma gerekir", "Hayır; ama savunma süresi en çok üç gündür"],
        "Savunma alınmadan ceza verilemez; süre en az 15 gündür ve mali tatilde savunma istenemez, duruşma yapılamaz.",
        "Disiplin Yönetmeliği m. 23",
        "hard",
        fc="Hayır; ikisi de mali tatilde yapılamaz",
        fd=["Evet; ikisi de zorunlu yapılır", "Yalnız duruşma zorunludur", "Yalnız savunma bir günde alınır", "Evet; müşteri isterse yapılır"],
    ),
    r(
        "Oda disiplin kurulu kararını bildirimden 25 gün sonra doğrudan Birlik Disiplin Kuruluna götüren meslek mensubunun itirazı, oda aracılığı kullanılmadığı için reddedilmiştir. Doğru mudur?",
        "14 Ocak 2026 değişikliği sonrasında posta ile itirazda hangi tarih itiraz tarihi sayılır?",
        "Hayır; otuz günde doğrudan başvuru mümkündür",
        ["Evet; yalnız oda aracılığı mümkündür", "Evet; süre yalnız yedi gündür", "Hayır; itiraz doğrudan mahkemeye yapılır", "Hayır; itiraz süresi bir yıldır"],
        "Karara 30 gün içinde oda aracılığıyla veya doğrudan Birlik Disiplin Kuruluna itiraz edilebilir.",
        "Disiplin Yönetmeliği m. 28 (14.01.2026 değişikliği)",
        "hard",
        fc="Dilekçenin kurum evrakına girdiği tarih",
        fd=["Dilekçenin postaya verildiği tarih", "Kararın yazıldığı ilk tarih", "Oda genel kurulunun toplantı tarihi", "Meslek mensubunun ruhsat tarihi"],
        fw="Güncel kurala göre posta itirazında dilekçenin kurum evrakına girdiği tarih esas alınır; Birlik elektronik başvuru altyapısı kurabilir.",
    ),
    r(
        "Meslek mensubunun odaya bildirdiği adrese ulaşılamamış; oda yalnız internet sitesine ilan koyarak bildirimi tamamlanmış saymıştır. Güncel usule uygun mudur?",
        "Ulaşılamayan ilgili için e‑Birlik bildiriminden sonraki yedi gün içinde hangi işlem yapılır?",
        "Hayır; e‑Birlik ve ilan tahtası gerekir",
        ["Evet; internet ilanı tek başına yeterlidir", "Evet; hiçbir bildirim gerekmez", "Hayır; yalnız müşteriye mesaj atılır", "Hayır; sadece vergi dairesine yazılır"],
        "Adresine ulaşılamayan ilgiliye e‑Birlik üzerinden bildirim gönderilir; ardından ilan tahtası ve bekleme süreleri uygulanır.",
        "Disiplin Yönetmeliği m. 34 (14.01.2026 değişikliği)",
        "hard",
        fc="İlan tahtasına beş iş günlük duyuru asılır",
        fd=["İnternet sitesinde süresiz ilan yayımlanır", "Müşterinin bürosuna mühür bırakılır", "Vergi mahkemesinde dava açılır", "Ruhsat kendiliğinden iptal edilir"],
    ),
]


PREMISES = [
    {
        "stem": "Disiplin cezalarının tanımları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Uyarma, daha dikkatli davranma gereğinin yazılı bildirimidir\n\nII. Kınama, kusurlu olunduğunun yazılı bildirimidir\n\nIII. Meslekten çıkarma, ruhsatın geri alınarak mesleğe yeniden izin verilmemesidir",
        "correct": "I, II ve III",
        "why": "Üç ifade de Yönetmelikteki ceza tanımlarını doğru yansıtır.",
        "ref": "Disiplin Yönetmeliği m. 4",
        "difficulty": "easy",
    },
    {
        "stem": "Disiplin cezası türleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Geçici alıkoymanın olağan alt sınırı altı aydır\n\nII. Kınama, mührün sürekli geri alınmasıdır\n\nIII. Yeminli sıfatını kaldırmada YMM mührü geri alınır",
        "correct": "I ve III",
        "why": "Geçici alıkoyma en az altı aydır ve yeminli sıfatı kaldırılınca mühür geri alınır; kınamanın tanımı farklıdır.",
        "ref": "Disiplin Yönetmeliği m. 4",
        "difficulty": "medium",
    },
    {
        "stem": "Tekerrür hükümleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Üç yıllık dönemde üçüncü uyarma eylemi kınamaya yol açabilir\n\nII. Üç yıllık dönemde üçüncü kınama eylemi geçici alıkoymaya yol açabilir\n\nIII. İlk iki cezanın kesinleşip ilgiliye bildirilmiş olması aranır",
        "correct": "I, II ve III",
        "why": "Üç ifade de Yönetmeliğin tekerrür için aradığı koşullara uygundur.",
        "ref": "Disiplin Yönetmeliği m. 6/a, 7/a ve 11",
        "difficulty": "hard",
    },
    {
        "stem": "Disiplin kovuşturmasında savunma bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Savunma alınmadan ceza verilemez\n\nII. Savunma için en az on beş gün verilir\n\nIII. Mali tatilde savunma istenmesi zorunludur",
        "correct": "I ve II",
        "why": "Savunma zorunlu ve asgari süre 15 gündür; mali tatilde savunma istenemez.",
        "ref": "Disiplin Yönetmeliği m. 23",
        "difficulty": "medium",
    },
    {
        "stem": "Oda Disiplin Kurulu kararına itiraz bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bildirimden itibaren otuz günlük süre vardır\n\nII. Posta itirazında kurum evrakına giriş tarihi esas alınır\n\nIII. İtiraz yalnız ilgili oda aracılığıyla yapılabilir",
        "correct": "I ve II",
        "why": "Süre 30 gündür ve posta itirazında evraka giriş tarihi esastır; doğrudan Birliğe de başvurulabilir.",
        "ref": "Disiplin Yönetmeliği m. 28 (14.01.2026 değişikliği)",
        "difficulty": "hard",
    },
    {
        "stem": "Güncel bildirim usulü bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bildirilen KEP adresine tebligat yazılı tebligat yerine geçmez\n\nII. Adrese ulaşılamazsa e‑Birlik ve ilan tahtası zinciri uygulanır\n\nIII. Odanın internet sitesindeki tek ilan her durumda yeterli değildir",
        "correct": "II ve III",
        "why": "KEP adresine yapılan tebligat yazılı tebligat yerine geçer; e‑Birlik ve ilan tahtası uygulanır, tek internet ilanı yeterli değildir.",
        "ref": "Disiplin Yönetmeliği m. 34 (14.01.2026 değişikliği)",
        "difficulty": "hard",
    },
    {
        "stem": "Disiplin soruşturması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Olağan zamanaşımı fiilden itibaren beş yıldır\n\nII. Meslekten ayrılma önceki fiiller için soruşturmayı engeller\n\nIII. Meslek mensubunun ölümü halinde açık süreç sonlandırılır",
        "correct": "I ve III",
        "why": "Olağan süre beş yıldır ve ölüm halinde süreç sonlandırılır; meslekten ayrılma önceki fiiller için engel değildir.",
        "ref": "Disiplin Yönetmeliği m. 14",
        "difficulty": "medium",
    },
    {
        "stem": "Disiplin cezalarının uygulanması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kesinleşen cezayı ilgili oda yönetim kurulu başkanlığı uygular\n\nII. Uyarma ve kınama Resmî Gazete'de ilan edilir\n\nIII. İnternet ilanı tek başına cezanın kesinleşme koşulu değildir",
        "correct": "I ve III",
        "why": "Uygulama oda yönetim kurulu başkanlığınındır; uyarma ve kınama Resmî Gazete ilan grubunda değildir, internet ilanı kesinleşme koşulu olmaz.",
        "ref": "Disiplin Yönetmeliği m. 12 ve 29",
        "difficulty": "hard",
    },
]


if __name__ == "__main__":
    write_topic(
        lesson_id="meslek_hukuku",
        topic_id="disiplin",
        label="Disiplin",
        slug="disiplin",
        prefix="topic-mh-di",
        seed=170747,
        legislation_version="14.01.2026 tarihli ve 33137 sayılı RG değişiklikleri işlenmiş yürürlükteki Disiplin Yönetmeliği",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
