#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Oda ve TÜRMOB, 3×20."""
from topic_pack_builder import write_topic


SHORT = {
    "En az 250 meslek mensubu": "En az 250 kayıtlı meslek mensubu",
    "TÜRMOB": "Meslek Odaları Birliği",
    "TÜRMOB'un": "Odalar Birliğinin",
    "Tüzel kişiliğe sahip kamu kurumu niteliğinde meslek kuruluşu": "Kamu kurumu niteliğinde oda",
    "Kamu kurumu niteliğinde meslek kuruluşu": "Kamu kurumu niteliğinde oda",
    "Hayır; kuruluş amaçları dışında çalışamaz": "Hayır; amaçlarıyla sınırlıdır",
    "Hayır; en az 100 yazılı başvuru gerekir": "Hayır; 100 başvuru gerekir",
    "En az 100 meslek mensubunun başvurusu": "En az 100 yazılı başvuru",
    "Kuruluşun Bakanlığa bildirilmesiyle": "Bakanlığa kuruluş bildirimiyle",
    "Hayır; oda üyesi olmadan faaliyet yapılamaz": "Hayır; faaliyet için oda üyeliği gerekir",
    "Evet; aidat ve eğitim gelirleri oda geliridir": "Evet; aidat ve eğitim oda geliridir",
    "Giriş ücreti, aidat ve mesleki eğitim geliri": "Giriş, aidat ve eğitim gelirleri",
    "Genel, yönetim, disiplin ve denetleme kurulları": "Dört temel meslek kurulu",
    "Kayıtlı bütün üyelerden oluşan en yüksek organdır": "Kayıtlı üyelerin en yüksek organı",
    "Oda Genel Kurulunun tasdiki": "Odanın Genel Kurul organı",
    "Hayır; resmî internet sitesinde ilan gerekir": "Hayır; internet ilanı gerekir",
    "Oda Yönetim Kurulunun soruşturma açma kararı": "Oda Yönetim Kurulunun kararı",
    "Türkiye SMMM ve YMM Odaları Birliği": "Meslek Odaları Birliği",
    "Hayır; kamu kurumu niteliğinde tüzel kişidir": "Hayır; kamu meslek tüzel kişisidir",
    "Kamu kurumu niteliğinde tüzel kişi; merkezi Ankara": "Kamu meslek tüzel kişisi; Ankara",
    "Odaların seçtiği temsilcilerden": "Oda temsilcilerinden",
    "Hayır; görüşmeye katılamaz": "Hayır; ilgili işe katılamaz",
    "İşlem ve hesapları denetleyip Genel Kurula rapor vermek": "Oda hesabını denetleyip raporlamak",
}


def r(s, f, c, d, w, ref, difficulty="medium", fc=None, fd=None):
    c = SHORT.get(c, c)
    fc = SHORT.get(fc or c, fc or c)
    return {"scenario": s, "focus": f, "correct": c, "focus_correct": fc,
            "distractors": list(d), "focus_distractors": list(fd or d), "why": w,
            "focus_why": f"Kurumsal yapının odak sonucu şudur: {w}",
            "ref": ref, "difficulty": difficulty}


RULES = [
    r("SMMM ve YMM'ler tek bir yerel odada birlikte örgütlenmek istemektedir. Kanuni yapı buna uygun mudur?", "SMMM ve YMM odalarının kuruluş biçimi hangisidir?", "Hayır; SMMM ve YMM odaları ayrı kurulur", ["Evet; her ilde zorunlu tek karma oda vardır", "Yalnız SMMM odası kurulabilir", "YMM'ler hiçbir odaya bağlı değildir", "Odalar yalnız ticaret şirketidir"], "Kanun, SMMM odaları ile YMM odalarının ayrı ayrı kurulmasını öngörür.", "3568 sayılı Kanun m. 14", "easy", fc="İki meslek grubu için ayrı odalar"),
    r("Bir meslek odası, tüzel kişiliği bulunmayan özel dernek olduğunu ileri sürmektedir. Hukuki niteliği nedir?", "3568 sayılı Kanuna göre meslek odalarının statüsü hangisidir?", "Tüzel kişiliğe sahip kamu kurumu niteliğinde meslek kuruluşu", ["Kâr amaçlı anonim şirket", "Tüzel kişiliksiz gönüllü topluluk", "Siyasi parti yan kuruluşu", "Yalnız geçici danışma kurulu"], "Odalar tüzel kişiliğe sahip, kamu kurumu niteliğinde meslek kuruluşlarıdır.", "3568 sayılı Kanun m. 14", "easy", fc="Kamu kurumu niteliğinde meslek kuruluşu"),
    r("Oda, meslekle ilgisiz ticari faaliyeti sürekli yürütmektedir. Amaç sınırı bakımından mümkün müdür?", "Odaların faaliyet alanı hangi sınırla bağlıdır?", "Hayır; kuruluş amaçları dışında çalışamaz", ["Evet; her ticari işi yapabilir", "Yalnız siyasi parti faaliyeti yapar", "Amaç sınırlaması bulunmaz", "Müşterilerin şirketlerini yönetir"], "Odalar, mesleki ihtiyaç, gelişim, dürüstlük, güven, disiplin ve ahlak amaçları dışında faaliyette bulunamaz.", "3568 sayılı Kanun m. 14", "medium", fc="Kanundaki kuruluş amaçlarıyla"),
    r("Bir il merkezinde aynı meslek grubundan 250 meslek mensubu bulunmaktadır. Oda kuruluş sayısı bakımından temel eşik sağlanmış mıdır?", "İl merkezi veya uygun ilçede oda kurulması için temel meslek mensubu sayısı kaçtır?", "Evet; 250 kişilik eşik sağlanmıştır", ["Hayır; mutlaka 2.500 kişi gerekir", "Yalnız on kişi yeterlidir", "Sayı şartı hiçbir zaman aranmaz", "Oda ancak tek meslek mensubuyla kurulur"], "Kanun, bölgesinde kendi meslek grubundan en az 250 kişi bulunan il merkezinde oda kurulmasını öngörür.", "3568 sayılı Kanun m. 15", "medium", fc="En az 250 meslek mensubu"),
    r("Büyükşehir dışındaki bir ilçede 250 meslek mensubu vardır ancak yazılı kuruluş başvurusu yapanların sayısı 90'dır. İlçe odası kurulabilir mi?", "İlçede oda kuruluşunda sayı eşiğine ek hangi yazılı başvuru şartı aranır?", "Hayır; en az 100 yazılı başvuru gerekir", ["Evet; tek başvuru yeterlidir", "Yazılı başvuru tamamen yasaktır", "Yalnız belediye başkanı başvurur", "Başvuru sayısı 10'u aşamaz"], "İlçede oda kurulması için genel sayı eşiği yanında en az 100 meslek mensubunun yazılı başvurusu gerekir.", "3568 sayılı Kanun m. 15", "hard", fc="En az 100 meslek mensubunun başvurusu"),
    r("Yeterli meslek mensubu bulunmadığı için oda kurulamayan yerin hangi odaya bağlanacağı tartışılmaktadır. Karar mercii kimdir?", "Oda kurulamayan yerlerin en yakın odaya bağlanmasına veya bölge odası kurulmasına kim karar verir?", "TÜRMOB", ["Herhangi bir müşteri", "Ticaret şirketi yönetimi", "Stajyerler kurulu", "Yalnız noterler birliği"], "Yeterli sayı bulunmayan yerin en yakın odaya bağlanmasına veya bölge odası kurulmasına Birlik karar verir.", "3568 sayılı Kanun m. 15", "medium"),
    r("Yeni oda kuruluşunu Birlik Yönetim Kurulu aracılığıyla Maliye Bakanlığına bildirmiştir. Ne zaman tüzel kişilik kazanır?", "Odanın tüzel kişilik kazanması hangi işleme bağlanmıştır?", "Kuruluşun Bakanlığa bildirilmesiyle", ["İlk müşterinin ücret ödemesiyle", "Ticari satış yapılmasıyla", "Siyasi parti onayıyla", "Staj sınavı düzenlenmesiyle"], "Oda, kuruluşunu Birlik Yönetim Kurulu aracılığıyla Maliye Bakanlığına bildirmekle tüzel kişilik kazanır.", "3568 sayılı Kanun m. 15", "medium"),
    r("Ruhsatlı meslek mensubu hiçbir odaya üye olmadan bağımsız faaliyet yürütmek istemektedir. Mümkün müdür?", "Oda üyeliğinin mesleki faaliyet bakımından etkisi nedir?", "Hayır; oda üyesi olmadan faaliyet yapılamaz", ["Evet; ruhsat dışında hiçbir kayıt gerekmez", "Yalnız müşterinin izni yeterlidir", "Oda üyeliği sadece stajyere gerekir", "Üyelik yerine ticaret sicili yeterlidir"], "Odaya üye olmayan meslek mensubu mesleki faaliyette bulunamaz.", "3568 sayılı Kanun m. 15", "easy", fc="Mesleki faaliyetin zorunlu koşuludur"),
    r("Odanın gelirleri arasında yıllık üye aidatı ve mesleki eğitim kurs ücretleri bulunmaktadır. Kanuna uygun mudur?", "Odanın kanuni gelir kaynaklarından biri hangisidir?", "Evet; aidat ve eğitim gelirleri oda geliridir", ["Hayır; odanın hiçbir geliri olamaz", "Yalnız siyasi bağış kabul edilir", "Sadece ticari satış geliri olabilir", "Müşteri vergileri doğrudan odaya aittir"], "Giriş ücreti, yıllık aidat, bağışlar ve mesleki eğitim-kurs gelirleri oda gelirleri arasındadır.", "3568 sayılı Kanun m. 16", "easy", fc="Giriş ücreti, aidat ve mesleki eğitim geliri"),
    r("Oda, yalnız yönetim kurulundan oluştuğunu ve başka organa ihtiyaç bulunmadığını ileri sürmektedir. Kanuni organlar hangileridir?", "Odanın dört temel organı hangileridir?", "Genel, yönetim, disiplin ve denetleme kurulları", ["Yalnız başkan ve müşteri kurulu", "Vergi, ticaret ve noter kurulları", "Stajyer, işveren ve banka kurulları", "Sadece yönetim kurulu"], "Oda organları Genel Kurul, Yönetim Kurulu, Disiplin Kurulu ve Denetleme Kuruludur.", "3568 sayılı Kanun m. 17", "easy"),
    r("Odaya kayıtlı üyelerin yalnız küçük bir kısmının oluşturduğu kurulun en yüksek organ olduğu savunulmuştur. Doğrusu nedir?", "Oda Genel Kurulu kimlerden oluşur ve kurumsal konumu nedir?", "Kayıtlı bütün üyelerden oluşan en yüksek organdır", ["Yalnız oda çalışanlarından oluşur", "Sadece müşterilerin temsilcisidir", "Vergi dairesinin alt birimidir", "Tüzel kişiliği olmayan geçici komisyondur"], "Oda Genel Kurulu, odaya kayıtlı bütün meslek mensuplarının katılımıyla oluşan en yüksek organdır.", "3568 sayılı Kanun m. 18", "easy", fc="Kayıtlı tüm meslek mensuplarından"),
    r("Oda yönetim, disiplin ve denetleme kurulu üyeleri ile Birlik temsilcileri seçilecektir. Seçim yetkisi kimdedir?", "Odanın kurullarını ve Birlik temsilcilerini seçen organ hangisidir?", "Oda Genel Kurulu", ["Herhangi bir müşteri kurulu", "Vergi dairesi müdürlüğü", "Ticaret sicili memurluğu", "Stajyer aday komisyonu"], "Oda Genel Kurulu yönetim, disiplin ve denetleme kurullarını ve Birlik temsilcilerini seçer.", "3568 sayılı Kanun m. 19", "medium"),
    r("Oda bütçesi ve kesin hesabı yönetimce hazırlanmış, fakat Genel Kurul onayına sunulmamıştır. Eksiklik nedir?", "Oda bütçesi ile kesin hesaplarını tasdik eden organ hangisidir?", "Oda Genel Kurulunun tasdiki", ["Müşterilerin oybirliği", "Stajyerlerin yazılı izni", "Ticaret sicilinin tescili", "Herhangi bir banka müdürü"], "Bütçe ve kesin hesapları tasdik etmek Oda Genel Kurulunun görevidir.", "3568 sayılı Kanun m. 19/f", "medium", fc="Oda Genel Kurulu"),
    r("Olağan Oda Genel Kurulu 2026 yılında yıllık toplantı yapmak istemektedir. Kanundaki dönem nedir?", "Olağan Oda Genel Kurulu hangi sıklık ve ayda toplanır?", "Üç yılda bir mayıs ayında", ["Her ay ocak ayında", "Beş yılda bir aralık ayında", "Her hafta cuma günü", "Toplantı dönemi bulunmaz"], "Oda Genel Kurulu üç yılda bir mayıs ayı içinde bütçe, gündem ve seçimler için toplanır.", "3568 sayılı Kanun m. 20", "medium"),
    r("2025 sonrası Oda Genel Kurulu duyurusu yalnız kapalı mektupla yapılmış, resmî internet sitesinde yayımlanmamıştır. Usule uygun mudur?", "Güncel kurala göre Oda Genel Kurulu bilgileri nasıl ilan edilir?", "Hayır; resmî internet sitesinde ilan gerekir", ["Evet; hiçbir ilan gerekmez", "Yalnız müşteriye sözlü bildirilir", "Sadece gazete ilanı zorunludur", "İlanı stajyer yapar"], "2025 değişikliğiyle toplantı bilgileri, ilk toplantıdan en az on gün önceden toplantı tarihine kadar odanın resmî internet sitesinde ilan edilir.", "3568 sayılı Kanun m. 20 (30.03.2025 değişikliği)", "hard", fc="Odanın resmî internet sitesinde"),
    r("Oda Yönetim Kurulunun hukuki temsil yetkisi konusunda uyuşmazlık çıkmıştır. Odayı kim temsil eder?", "Odanın hukuki temsilcisi kimdir?", "Oda Yönetim Kurulu Başkanı", ["Herhangi bir müşteri", "Disiplin şikâyetçisi", "Stajyer temsilcisi", "Vergi dairesi memuru"], "Odanın hukuki temsilcisi Oda Yönetim Kurulu Başkanıdır.", "3568 sayılı Kanun m. 21", "easy"),
    r("Oda Yönetim Kurulu bütçe teklifini hazırlamamış ve Genel Kurula sunmamıştır. Hangi görev ihlal edilmiştir?", "Oda bütçe teklifini düzenleyip Genel Kurul onayına sunmak kimin görevidir?", "Oda Yönetim Kurulunun", ["Müşteri danışma kurulunun", "Ticaret sicili müdürlüğünün", "Yalnız stajyerlerin", "Vergi mahkemesinin"], "Bütçe teklifini düzenlemek ve Genel Kurula sunmak Oda Yönetim Kurulunun görevidir.", "3568 sayılı Kanun m. 23/a", "medium"),
    r("Oda Yönetim Kurulu üyesi kendisini doğrudan ilgilendiren işin görüşülmesine katılmıştır. Usule uygun mudur?", "Yönetim Kurulu üyesi ilgili olduğu işin görüşülmesine katılabilir mi?", "Hayır; görüşmeye katılamaz", ["Evet; tek başına karar verir", "Yalnız müşteri isterse katılır", "İlgili işte iki oy kullanır", "Çıkar çatışması önem taşımaz"], "Başkan ve yönetim kurulu üyeleri ilgili oldukları işlerin görüşülmesine katılamaz.", "3568 sayılı Kanun m. 24", "medium"),
    r("Oda Disiplin Kurulu, Yönetim Kurulunun soruşturma açma kararı olmadan üyeye ceza vermiştir. Görev düzeni bakımından eksiklik nedir?", "Oda Disiplin Kurulu soruşturma görevini hangi karar üzerine yürütür?", "Oda Yönetim Kurulunun soruşturma açma kararı", ["Herhangi bir müşterinin sözlü talebi", "Stajyerin tek taraflı kararı", "Ticaret sicilinin izin belgesi", "Vergi dairesinin aidat yazısı"], "Oda Disiplin Kurulu, Oda Yönetim Kurulunun disiplin soruşturması açma kararı üzerine soruşturma yapar ve karar verir.", "3568 sayılı Kanun m. 26", "hard", fc="Oda Yönetim Kurulu kararı üzerine"),
    r("Odanın mali işlem ve hesaplarını inceleyip Genel Kurula rapor sunacak organ hangisidir?", "Oda Denetleme Kurulunun temel görevi nedir?", "Oda Denetleme Kurulu", ["Müşteri kabul komisyonu", "Stajyer yoklama kurulu", "Ticaret sicili heyeti", "Vergi uzlaşma komisyonu"], "Denetleme Kurulu odanın işlem ve hesaplarını denetleyerek Genel Kurula rapor verir.", "3568 sayılı Kanun m. 27", "easy", fc="İşlem ve hesapları denetleyip Genel Kurula rapor vermek"),
    r("SMMM ve YMM odalarının katıldığı üst meslek kuruluşunun kısa adı nedir?", "Kanundaki Birlik hangi kuruluşu ifade eder?", "TÜRMOB", ["TESMER", "KGK", "SPK", "BDDK"], "Bütün SMMM ve YMM odalarının katıldığı üst kuruluş Türkiye SMMM ve YMM Odaları Birliği, kısa adıyla TÜRMOB'dur.", "3568 sayılı Kanun m. 1 ve 28", "easy", fc="Türkiye SMMM ve YMM Odaları Birliği"),
    r("TÜRMOB'un özel bir ticaret şirketi olduğu ve tüzel kişiliği bulunmadığı ileri sürülmüştür. Doğru mudur?", "TÜRMOB'un hukuki statüsü ve merkezi hangisidir?", "Hayır; kamu kurumu niteliğinde tüzel kişidir", ["Evet; kâr amaçlı anonim şirkettir", "Yalnız geçici bir komisyondur", "Tüzel kişiliksiz müşteri birliğidir", "Siyasi partinin alt kuruluşudur"], "TÜRMOB tüzel kişiliğe sahip kamu kurumu niteliğinde meslek kuruluşudur; merkezi Ankara'dadır.", "3568 sayılı Kanun m. 28", "easy", fc="Kamu kurumu niteliğinde tüzel kişi; merkezi Ankara"),
    r("Odalar arasında mesleki anlaşmazlık çıkmış ve bağlayıcı çözüm istenmiştir. Yetkili üst kuruluş hangisidir?", "Odalar arasındaki mesleki anlaşmazlıkları kesin çözen ve zorunlu meslek kurallarını belirleyen kimdir?", "TÜRMOB", ["Herhangi bir müşteri", "Ticaret şirketi genel kurulu", "Stajyerler komisyonu", "Noterler birliği"], "Odalar arası mesleki anlaşmazlıkları kesin çözmek ve uyulması zorunlu meslek kurallarını belirlemek Birliğin görevidir.", "3568 sayılı Kanun m. 29/d", "medium", fc="Türkiye SMMM ve YMM Odaları Birliği"),
    r("Mesleğe ilişkin yönetmelik taslağının hangi kuruluşça hazırlanacağı tartışılmaktadır. Kanuni görev kime aittir?", "3568 sayılı Kanuna göre çıkarılacak yönetmelikleri hazırlamak kimin görevidir?", "TÜRMOB'un", ["Her müşterinin ayrı ayrı", "Ticaret sicili memurunun", "Stajyer adayların", "Bankalar birliğinin"], "Kanuna göre çıkarılacak yönetmelikleri hazırlamak TÜRMOB'un görevleri arasındadır.", "3568 sayılı Kanun m. 29/e", "medium", fc="TÜRMOB"),
    r("Birliğin yalnız Yönetim Kurulundan oluştuğu ileri sürülmüştür. Birliğin organları hangileridir?", "TÜRMOB'un dört kanuni organı hangisidir?", "Genel, yönetim, disiplin ve denetleme kurulları", ["Yalnız müşteri ve stajyer kurulları", "Vergi, banka ve noter kurulları", "Sadece yönetim ve reklam kurulu", "Ticaret sicili ile uzlaşma kurulu"], "Birlik organları Genel Kurul, Yönetim Kurulu, Disiplin Kurulu ve Denetleme Kuruludur.", "3568 sayılı Kanun m. 31", "easy"),
    r("Birlik Genel Kurulunun doğrudan bütün meslek mensuplarından oluştuğu savunulmuştur. Doğru yapı nedir?", "TÜRMOB Genel Kurulu kimlerden meydana gelir?", "Odaların seçtiği temsilcilerden", ["Yalnız müşterilerden", "Bütün vergi müfettişlerinden", "Stajyerlerin tamamından", "Ticaret sicili memurlarından"], "Birlik Genel Kurulu, odaların kendi üyeleri arasından seçtikleri temsilcilerden oluşur.", "3568 sayılı Kanun m. 32", "medium"),
]


PREMISES = [
    {"stem":"Odaların niteliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. SMMM ve YMM odaları ayrı kurulur\n\nII. Odalar kâr amaçlı özel şirkettir\n\nIII. Odalar kuruluş amaçları dışında faaliyette bulunamaz","correct":"I ve III","why":"Odalar ayrı, kamu kurumu niteliğinde ve kuruluş amaçlarıyla sınırlı meslek kuruluşlarıdır.","ref":"3568 sayılı Kanun m. 14","difficulty":"easy"},
    {"stem":"Oda kuruluşu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Temel sayı eşiği 250 meslek mensubudur\n\nII. Üyelik olmadan mesleki faaliyet yapılamaz\n\nIII. Oda Bakanlığa bildirimle tüzel kişilik kazanır","correct":"I, II ve III","why":"Üç ifade de oda kuruluşu ve üyelik hükümlerine uygundur.","ref":"3568 sayılı Kanun m. 15","difficulty":"medium"},
    {"stem":"Oda organları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Genel Kurul en yüksek organdır\n\nII. Yönetim Kurulu odayı Başkan aracılığıyla temsil eder\n\nIII. Denetleme Kurulu oda hesaplarını denetler","correct":"I, II ve III","why":"Üç ifade oda organlarının yapı ve görevlerini doğru açıklar.","ref":"3568 sayılı Kanun m. 17-27","difficulty":"medium"},
    {"stem":"Oda Genel Kurulu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bütçe ve kesin hesabı tasdik etmez\n\nII. Oda kurullarını seçer\n\nIII. Olağan toplantı üç yılda bir mayısta yapılır","correct":"II ve III","why":"Genel Kurul kurulları seçer, üç yılda bir mayısta toplanır ve bütçeyi de tasdik eder.","ref":"3568 sayılı Kanun m. 19-20","difficulty":"medium"},
    {"stem":"TÜRMOB'un niteliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bütün SMMM ve YMM odalarının üst kuruluşudur\n\nII. Merkezi İstanbul'dadır\n\nIII. Kâr amaçlı özel şirket değildir","correct":"I ve III","why":"TÜRMOB kamu kurumu niteliğindeki üst kuruluştur ve merkezi Ankara'dadır.","ref":"3568 sayılı Kanun m. 28","difficulty":"easy"},
    {"stem":"TÜRMOB'un görevleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mesleğin gelişmesi için çalışma yapmaz\n\nII. Odalar arası anlaşmazlıkları kesin çözer\n\nIII. Kanuna göre çıkarılacak yönetmelikleri hazırlar","correct":"II ve III","why":"Birlik mesleği geliştirir, anlaşmazlıkları çözer ve yönetmelikleri hazırlar.","ref":"3568 sayılı Kanun m. 29","difficulty":"medium"},
    {"stem":"TÜRMOB organları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Genel Kurul vardır\n\nII. Disiplin Kurulu yoktur\n\nIII. Denetleme Kurulu vardır","correct":"I ve III","why":"Birliğin Genel, Yönetim, Disiplin ve Denetleme Kurulları bulunur.","ref":"3568 sayılı Kanun m. 31","difficulty":"medium"},
    {"stem":"Birlik Genel Kurulu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Oda temsilcilerinden oluşur\n\nII. Birlik kurullarını seçer\n\nIII. Zorunlu mesleki karar alamaz","correct":"I ve II","why":"Birlik Genel Kurulu temsilcilerden oluşur, kurulları seçer ve zorunlu mesleki karar alabilir.","ref":"3568 sayılı Kanun m. 32-33","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(lesson_id="meslek_hukuku", topic_id="oda_ve_turmob",
                label="Oda ve TÜRMOB", slug="oda_ve_turmob",
                prefix="topic-mh-ot", seed=170746,
                legislation_version="3568 sayılı Kanun, 30.03.2025 değişikliği işlenmiş 17.07.2026 metni",
                rules=RULES, premises=PREMISES, wrong_banks={})
