#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Finansal Tablolar ve Analizi — Finansal Tablolar, 3×20.

17.07.2026 itibarıyla erken uygulama varsayılmadığında TMS 1 yürürlüktedir.
TFRS 18, 01.01.2027 ve sonrasında başlayan dönemlerde zorunlu olacaktır.
"""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, distractors, why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus, "correct": correct,
        "distractors": distractors,
        "focus_distractors": distractors[2:] + distractors[:2],
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Yatırımcılar işletmeye kaynak sağlama kararında işletmenin varlıkları, yükümlülükleri, özkaynakları, gelir ve giderleri hakkında bilgi istemektedir. Genel amaçlı finansal tabloların temel işlevi nedir?",
        "Genel amaçlı finansal raporlar belirli bir yatırımcının özel talebine göre mi hazırlanır?",
        "Ekonomik kararlar için yararlı finansal bilgi sağlamak",
        ["Yalnız vergi matrahını kesin biçimde hesaplamak", "Her yatırımcıya gelecekteki getiriyi garanti etmek", "Sadece işletme yöneticilerinin ücretini belirlemek", "Bütün varlıkları zorunlu olarak tasfiye değerine çevirmek"],
        "Genel amaçlı finansal tablolar, mevcut ve potansiyel yatırımcılar, borç verenler ve diğer kreditörlerin kaynak sağlama kararlarında yararlı bilgi sunar.",
        "Raporlar ortak bilgi ihtiyacına yöneliktir; tek bir kullanıcının bütün özel bilgi talebini karşılamak için tasarlanmaz.",
        "Finansal Raporlamaya İlişkin Kavramsal Çerçeve, 1.2-1.10", "easy",
    ),
    r(
        "17.07.2026 tarihinde TFRS 18'i erken uygulamayan bir işletme, yalnız finansal durum tablosu ile kâr veya zarar tablosunu tam set olarak sunmuştur. Set tamam mıdır?",
        "17.07.2026 itibarıyla TMS 1 uyarınca tam finansal tablo setinde hangileri birlikte yer alır?",
        "Hayır; nakit akış, özkaynak değişim ve dipnotlar gerekir",
        ["Evet; iki temel tablo tam set için her durumda yeterlidir", "Hayır; fakat tam set yalnız vergi beyannamesinden oluşur", "Evet; dipnotlar ve diğer tablolar finansal rapor sayılmaz", "Hayır; tam set yalnız yönetim kurulu faaliyet raporudur"],
        "TMS 1'e göre tam set; finansal durum, kâr veya zarar ve diğer kapsamlı gelir, özkaynak değişim ve nakit akış tabloları ile dipnot ve karşılaştırmalı bilgileri içerir.",
        "Dipnotlar ve diğer temel tablolar isteğe bağlı ek değildir; tam setin ayrılmaz parçalarıdır.",
        "TMS 1 Finansal Tabloların Sunuluşu, par. 10", "easy",
    ),
    r(
        "İşletme 2026 döneminde TFRS 18'i erken uygulamamıştır. Sunum esasları için TMS 1 yerine zorunlu olarak TFRS 18'i kullandığını belirtmiştir. Bu yaklaşım doğru mudur?",
        "TFRS 18'in zorunlu yürürlük tarihi ile TMS 1 arasındaki geçiş nasıl belirlenmiştir?",
        "Hayır; 2027'de zorunludur, erken uygulama açıklanır",
        ["Evet; TFRS 18 bütün işletmeler için 2024'te zorunlu olmuştur", "Hayır; TFRS 18 hiçbir tarihte yürürlüğe girmeyecektir", "Evet; TMS 1 yalnız vergi mükellefi olmayanlara uygulanır", "Hayır; TFRS 18 sadece nakit akış tablosunu kaldırmıştır"],
        "TFRS 18, 1 Ocak 2027 veya sonrasında başlayan yıllık dönemlerde zorunludur; erken uygulamaya izin verilir ve erken uygulama açıklanır.",
        "TFRS 18 yürürlüğe girdiğinde TMS 1'in yerini alacaktır. 2026 için erken uygulama belirtilmedikçe TMS 1 esas alınır.",
        "TFRS 18 Ek C, par. C1; KGK 2026 TFRS seti", "medium",
    ),
    r(
        "İşletme bir varlığı normal faaliyet döngüsünde satmayı beklemekte, ancak satışın raporlama tarihinden on dört ay sonra gerçekleşeceğini öngörmektedir. Sınıflandırma nedir?",
        "Normal faaliyet döngüsü içinde satılması, tüketilmesi veya paraya çevrilmesi beklenen bir varlık nasıl sınıflandırılır?",
        "Dönen varlık olarak sınıflandırılır",
        ["Duran varlık olarak sınıflandırılması zorunludur", "Özkaynak hesabında izlenir", "Koşullu yükümlülük olarak açıklanır", "Finansal tablo dışında bırakılır"],
        "Normal faaliyet döngüsünde gerçekleşmesi beklenen varlık, on iki ayı aşsa bile dönen varlık ölçütünü karşılar.",
        "Dönen varlık için normal faaliyet döngüsü, alım satım amacı, on iki ay içinde gerçekleşme veya nakit ve nakit benzeri olma ölçütlerinden biri yeterlidir.",
        "TMS 1, par. 66 ve 68", "medium",
    ),
    r(
        "İşletmenin raporlama tarihinden sonraki sekiz ay içinde ödenecek ticari borcu vardır. Normal faaliyet döngüsü de içinde olan bu borç nasıl sınıflandırılır?",
        "Raporlama tarihinden sonraki on iki ay içinde ödenmesi gereken bir yükümlülüğün genel sınıfı nedir?",
        "Kısa vadeli yükümlülük olarak sunulur",
        ["Uzun vadeli bir varlık olarak finansal durum tablosunda sunulur", "Özkaynakta yedek olarak gösterilir", "Gelir tablosunda hasılat sayılır", "Nakit akışından tamamen çıkarılır"],
        "Normal faaliyet döngüsünde ödenecek veya on iki ay içinde vadesi gelecek borç kısa vadeli yükümlülüktür.",
        "Yükümlülüğün kısa vadeli sayılması için TMS 1'deki ölçütlerden birinin karşılanması yeterlidir.",
        "TMS 1, par. 69-76", "easy",
    ),
    r(
        "İşletmenin raporlama tarihinde bir borcun ödemesini en az on iki ay erteleme hakkı bulunmamaktadır. Yönetim daha sonra refinansman anlaşması yapmıştır. Raporlama tarihindeki sınıflandırma nedir?",
        "Borcu uzun vadeli sınıflandırmada raporlama tarihinde erteleme hakkının önemi nedir?",
        "Raporlama tarihinde hak yoksa borç kısa vadeli sınıflandırılır",
        ["Sonraki her anlaşma borcu geriye dönük olarak uzun vadeli yapar", "Yönetimin sözlü niyeti tek başına uzun vadeli sınıflandırır", "Borç tutarı büyükse otomatik olarak özkaynağa dönüşür", "Bütün finansman borçları vadesine bakılmadan duran varlıktır"],
        "Sınıflandırma raporlama tarihinde mevcut hak ve koşullara dayanır. Sonraki refinansman, koşulları varsa raporlama döneminden sonraki olay olarak açıklanabilir.",
        "Ödemeyi en az on iki ay erteleme hakkı raporlama tarihinde var olmalıdır; yalnız sonraki niyet veya anlaşma sınıflandırmayı geriye dönük değiştirmez.",
        "TMS 1, par. 72A-76ZA; TMS 10", "hard",
    ),
    r(
        "İşletme aynı tarafla olan ticari alacak ve borcunu, bir TFRS izin vermediği hâlde net tutarda göstermiştir. Sunum uygun mudur?",
        "Finansal tablolarda varlık ve yükümlülüklerin veya gelir ve giderlerin mahsup edilmesinde genel kural nedir?",
        "Hayır; TFRS izin vermedikçe mahsup edilmez",
        ["Evet; yönetim isterse bütün kalemler netleştirilebilir", "Evet; aynı para birimindeki her kalem zorunlu mahsup edilir", "Hayır; ancak bütün varlıklar gelir tablosuna aktarılır", "Evet; dipnot varsa mahsup yasağı kendiliğinden kalkar"],
        "TMS 1, başka bir TFRS zorunlu kılmadıkça veya izin vermedikçe varlık-yükümlülük ve gelir-gider mahsubuna izin vermez.",
        "Brüt sunum finansal büyüklükleri görünür kılar; mahsup ancak ilgili standardın koşullarıyla yapılabilir.",
        "TMS 1, par. 32-35", "medium",
    ),
    r(
        "İşletme cari dönem tutarlarını sunmuş, ancak önceki döneme ait karşılaştırmalı rakamları gerekçe göstermeden çıkarmıştır. TMS 1'e uygun mudur?",
        "Asgari karşılaştırmalı bilgi bakımından finansal tablolar hangi dönemi de içerir?",
        "Hayır; önceki döneme ait karşılaştırmalı bilgi de sunulur",
        ["Evet; her finansal tablo yalnız cari dönemi içerir", "Hayır; yalnız on yıl önceki bilgiler sunulur", "Evet; karşılaştırma sadece vergi beyannamesinde gerekir", "Hayır; ancak önceki dönem tutarları sıfır yazılır"],
        "TMS 1, cari dönemin finansal tablolarındaki tüm tutarlar için önceki döneme ilişkin karşılaştırmalı bilgi sunulmasını ister.",
        "Karşılaştırmalı bilgi, değişimin görülmesini sağlar; açıklayıcı anlatım da cari dönemi anlamak için ilgiliyse karşılaştırmalı sunulur.",
        "TMS 1, par. 38-44", "easy",
    ),
    r(
        "İşletme hiçbir değişiklik veya daha güvenilir sunum gerekçesi bulunmadan finansal tablo kalemlerinin sınıflamasını her yıl değiştirmektedir. Bu uygulama uygun mudur?",
        "Sunum ve sınıflandırmanın dönemler arasında tutarlılığı hangi durumlarda değiştirilebilir?",
        "Hayır; haklı değişiklik yoksa sunum tutarlı sürdürülür",
        ["Evet; sınıflama her dönem rastgele değiştirilebilir", "Hayır; finansal tablo biçimi hiçbir zaman değiştirilemez", "Evet; yalnız kâr düştüğünde bütün sınıflar değiştirilir", "Hayır; tutarlılık yalnız nakit akış tablosunda aranır"],
        "TMS 1, önemli faaliyet değişikliği veya bir TFRS'nin gerektirmesi gibi daha uygun sunum gerekçesi olmadıkça sınıflandırmanın korunmasını ister.",
        "Tutarlılık karşılaştırılabilirliği destekler; değişiklik yapılırsa karşılaştırmalı bilgiler de uygulanabilir olduğu ölçüde yeniden sınıflandırılır ve açıklanır.",
        "TMS 1, par. 45-46", "medium",
    ),
    r(
        "İşletme çok sayıda önemsiz kalemi ayrı satırlarda göstererek önemli bilgiyi görünmez hâle getirmiştir. Sunum ilkesi bakımından sorun nedir?",
        "Önemlilik ve birleştirme ilkesi finansal tablo kalemlerine nasıl uygulanır?",
        "Önemli kalemler ayrı; önemsiz benzer kalemler toplu sunulur",
        ["Bütün kalemler tutarına bakılmadan tek satırda birleştirilir", "Her küçük işlem mutlaka ayrı bir temel tablo olur", "Önemlilik yalnız vergi cezası tutarıyla belirlenir", "Dipnotlar önemli bilgiyi gizlemek için kullanılır"],
        "TMS 1'e göre önemli sınıflar ayrı sunulur; farklı nitelik veya işleve sahip kalemler önemsiz olmadıkça ayrı gösterilir.",
        "Aşırı ayrıştırma da aşırı birleştirme de yararlı bilgiyi örtebilir. Önemlilik tutar ve niteliğe göre değerlendirilir.",
        "TMS 1, par. 29-31; Kavramsal Çerçeve", "medium",
    ),
    r(
        "Yönetim işletmeyi tasfiye etmeye karar vermiş ve gerçekçi başka seçeneği kalmamıştır; yine de tabloları işletmenin sürekliliği esasına göre hazırlamıştır. Doğru mudur?",
        "İşletmenin sürekliliğine ilişkin önemli belirsizlik bulunduğunda hangi açıklama gerekir?",
        "Hayır; uygun başka esas kullanılır ve durum açıklanır",
        ["Evet; süreklilik her durumda değiştirilemez varsayımdır", "Hayır; fakat finansal tablolar tamamen yok edilir", "Evet; tasfiye kararı yalnız nakit akışını etkiler", "Hayır; bütün borçlar otomatik olarak gelire çevrilir"],
        "Yönetim tasfiye veya faaliyeti durdurma niyetinde ya da başka gerçekçi seçeneği yoksa süreklilik esası uygun değildir; kullanılan esas ve neden açıklanır.",
        "Sürekliliğe ciddi şüphe doğuran önemli belirsizlikler varsa bunlar dipnotlarda açıkça belirtilir.",
        "TMS 1, par. 25-26", "hard",
    ),
    r(
        "İşletme malı vadeli satmış ve bedeli sonraki dönemde tahsil edecektir. Nakit akış tablosu dışındaki finansal tablolarda gelir hangi esasa göre muhasebeleştirilir?",
        "TMS 1 uyarınca nakit akış tablosu dışındaki tablolar hangi muhasebe esasına göre hazırlanır?",
        "Tahakkukla ilgili dönemde muhasebeleştirilir",
        ["Yalnız nakit tahsil edildiğinde muhasebeleştirilir", "Sadece vergi incelemesi başlayınca kaydedilir", "Müşteri isterse özkaynakta gösterilir", "Hiçbir dönemde finansal tablolara alınmaz"],
        "Tahakkuk esasında işlemler nakit hareketinden bağımsız olarak tanım ve muhasebeleştirme ölçütleri karşılandığında ilgili döneme alınır.",
        "Nakit akış tablosu nakit esaslı akışları sınıflandırır; diğer temel tablolar tahakkuk esasına dayanır.",
        "TMS 1, par. 27-28", "easy",
    ),
    r(
        "İşletme TFRS'lerin tüm hükümlerine uymadığı hâlde dipnotta 'tam uyum' beyanı vermiştir. Bu beyan yapılabilir mi?",
        "TFRS'lere açık ve koşulsuz uyum beyanı hangi şartla dipnotlarda yer alabilir?",
        "Hayır; bütün TFRS hükümlerine uyum sağlanmalıdır",
        ["Evet; tek bir standarda uyum tam uyum beyanına yeterlidir", "Evet; yönetimin iyi niyeti bütün eksikleri giderir", "Hayır; hiçbir işletme TFRS uyum beyanı veremez", "Evet; yalnız bilanço denkse tam uyum oluşur"],
        "TMS 1, finansal tablolar bütün TFRS hükümlerine uyduğunda açık ve koşulsuz uyum beyanı yapılmasına izin verir.",
        "Uygun olmayan muhasebe politikaları dipnot açıklamasıyla veya gerekçeyle düzelmiş sayılmaz.",
        "TMS 1, par. 15-18", "medium",
    ),
    r(
        "İşletme yeniden değerleme artışını doğrudan dönem kârına eklemiş, ilgili TFRS ise kalemin diğer kapsamlı gelirde sunulmasını istemektedir. Sunum doğru mudur?",
        "Kâr veya zarar ile diğer kapsamlı gelir arasındaki sınıflandırma neye göre yapılır?",
        "Hayır; ilgili TFRS hangi bölümde sunulacağını belirler",
        ["Evet; bütün gelirler her durumda yalnız dönem kârıdır", "Hayır; diğer kapsamlı gelir finansal tablo dışında kalır", "Evet; yönetim istediği kalemi özkaynak dışına çıkarır", "Hayır; yeniden değerleme her durumda nakit girişidir"],
        "Gelir ve giderler, bir TFRS aksini gerektirmedikçe kâr veya zararda; ilgili standardın belirlediği kalemler diğer kapsamlı gelirde muhasebeleştirilir.",
        "Diğer kapsamlı gelir, dönem kârından ayrı sunulan belirli gelir ve gider unsurlarını ve bunların yeniden sınıflandırma düzeltmelerini içerir.",
        "TMS 1, par. 81A-105", "medium",
    ),
    r(
        "Ortakların sermaye katkısı, işletmenin dönem içindeki gelirleriyle birlikte net dönem kârına yazılmıştır. Kavramsal olarak doğru mudur?",
        "Özkaynak katılımcılarının katkıları ve dağıtımlar gelir veya gider tanımına girer mi?",
        "Hayır; sahiplerle işlemler dönem kârı değildir",
        ["Evet; her sermaye katkısı faaliyet hasılatıdır", "Evet; kâr dağıtımı işletmenin satış gideridir", "Hayır; ancak katkı mutlaka finansman geliri sayılır", "Evet; ortak işlemleri yalnız nakit akışında yasaktır"],
        "Gelir ve gider tanımları özkaynak talep hakkı sahiplerinin katkıları ve onlara yapılan dağıtımlar dışındaki değişimleri kapsar.",
        "Ortaklarla sahip sıfatıyla yapılan işlemler özkaynak değişim tablosunda gösterilir; işletmenin performans kârı değildir.",
        "Kavramsal Çerçeve, 4.68-4.72; TMS 1", "easy",
    ),
    r(
        "Dönem başı özkaynak 1.000 bin TL, net kâr 180 bin TL, diğer kapsamlı gelir 40 bin TL, sermaye artışı 100 bin TL ve kâr dağıtımı 70 bin TL'dir. Dönem sonu özkaynak kaç bin TL'dir?",
        "Özkaynak değişim tablosu hangi değişimleri ayrı biçimde açıklar?",
        "1.250 bin TL",
        ["1.050 bin TL", "1.110 bin TL", "1.290 bin TL", "1.390 bin TL"],
        "Dönem sonu özkaynak = 1.000 + 180 + 40 + 100 − 70 = 1.250 bin TL'dir.",
        "Tablo; toplam kapsamlı gelir, sahiplerle yapılan katkı ve dağıtımlar ile her özkaynak bileşeninin dönem başı-sonu mutabakatını gösterir.",
        "TMS 1, par. 106-110", "medium",
    ),
    r(
        "Finansal durum tablosundaki tek bir tutarın hangi muhasebe politikasıyla ölçüldüğü anlaşılamamaktadır. Bu bilgi nerede açıklanmalıdır?",
        "Dipnotların finansal tablo setindeki temel işlevi nedir?",
        "Politika ve gerekli açıklamalar dipnotlarda sunulur",
        ["Bütün ölçüm bilgileri yalnız vergi beyannamesinde sunulur", "Dipnotlar sadece yönetimin reklâm metninden oluşur", "Dipnotlar temel tablolarla bağlantı kurmadan hazırlanır", "Muhasebe politikalarının açıklanması TFRS'de yasaktır"],
        "Dipnotlar hazırlama esası, önemli muhasebe politikaları ve TFRS'lerin istediği ya da tabloların anlaşılması için gerekli diğer bilgileri açıklar.",
        "Dipnotlar sistematik sunulur ve ilgili temel tablo kalemleriyle çapraz bağlantı kurar.",
        "TMS 1, par. 112-138", "easy",
    ),
    r(
        "İşletme önemli bir muhasebe politikasını geriye dönük uygulamış ve önceki dönem başı finansal durumunu önemli ölçüde etkilemiştir. Ek hangi tablo gerekir?",
        "Üçüncü finansal durum tablosu hangi tarihe ilişkin sunulur?",
        "Karşılaştırmalı dönemin başına ait bilanço",
        ["Cari dönemin ortasına ait tahmini gelir tablosu", "Sonraki on yılın bütçelenmiş nakit akış tablosu", "Yalnız vergi idaresine sunulan gizli bilanço", "İşletmenin kuruluş gününe ait değişmez tablo"],
        "Önemli geriye dönük politika uygulaması, düzeltme veya sınıflama varsa önceki karşılaştırmalı dönemin başına ait üçüncü finansal durum tablosu sunulur.",
        "Örneğin 31.12.2026 ve 31.12.2025 tablolarına ek üçüncü tablo 01.01.2025 tarihine ilişkindir.",
        "TMS 1, par. 40A-40D", "hard",
    ),
    r(
        "İşletmenin geçmiş olay sonucu kontrol ettiği ve ekonomik fayda üretme potansiyeli taşıyan mevcut ekonomik kaynağı vardır. Bu unsur nedir?",
        "Kavramsal Çerçeveye göre varlık tanımının üç temel unsuru hangileridir?",
        "Geçmiş olaydan doğan kontrollü ekonomik kaynak: varlık",
        ["Yükümlülüktür; yalnız gelecekteki satış niyeti yeterlidir", "Gelirdir; nakit tahsilatı yapılması zorunludur", "Giderdir; özkaynağı artırma potansiyeli taşır", "Özkaynaktır; bütün borçlardan önce gelen taleptir"],
        "Varlık, geçmişteki olaylar sonucunda işletme tarafından kontrol edilen mevcut ekonomik kaynaktır.",
        "Ekonomik kaynak fayda üretme potansiyeline sahip bir haktır; kesin nakit girişi varlık tanımının zorunlu unsuru değildir.",
        "Finansal Raporlamaya İlişkin Kavramsal Çerçeve, 4.3-4.25", "easy",
    ),
    r(
        "İşletmenin geçmiş olaydan doğan, ekonomik kaynak devretmesini gerektiren mevcut bir mükellefiyeti vardır. Hangi unsur tanımlanmıştır?",
        "Yükümlülük tanımında işletmenin kaçınma imkânı ve kaynak devri nasıl değerlendirilir?",
        "Ekonomik kaynak devri gerektiren mevcut borç: yükümlülük",
        ["Varlıktır; işletmenin kontrol ettiği bütün hakları gösterir", "Gelirdir; ortak katkısını artıran her değişimdir", "Özkaynaktır; varlıklardan borçların çıkarılmasıdır", "Giderdir; yalnız nakit ödeme yapıldığında doğar"],
        "Yükümlülük, geçmiş olaylar sonucu ekonomik kaynak devretme mükellefiyeti olan mevcut borçtur.",
        "İşletmenin kaynak devrinden kaçınmak için uygulanabilir bir imkânı yoksa mevcut mükellefiyet bulunabilir.",
        "Kavramsal Çerçeve, 4.26-4.47", "easy",
    ),
    r(
        "İşletmenin toplam varlıkları 2.700 bin TL, toplam yükümlülükleri 1.650 bin TL'dir. Özkaynak kaç bin TL'dir?",
        "Kavramsal Çerçevede özkaynak nasıl tanımlanır?",
        "1.050 bin TL",
        ["1.650 bin TL", "2.700 bin TL", "4.350 bin TL", "445,5 bin TL"],
        "Özkaynak = Varlıklar − Yükümlülükler = 2.700 − 1.650 = 1.050 bin TL'dir.",
        "Özkaynak, işletmenin tüm yükümlülükleri düşüldükten sonra varlıkları üzerindeki kalıntı payıdır.",
        "Kavramsal Çerçeve, 4.63", "easy",
    ),
    r(
        "İşletmenin özkaynak talep hakkı sahiplerinin katkısı dışında varlıkları artmış ve bunun sonucunda özkaynak artmıştır. Kavramsal unsur nedir?",
        "Gelir ile gider tanımlarında ortaklarla sahip sıfatıyla yapılan işlemler neden dışlanır?",
        "Gelirdir; ortak katkısı dışındaki özkaynak artışıdır",
        ["Giderdir; her varlık artışı özkaynağı azaltır", "Yükümlülüktür; bütün artışlar geri ödeme gerektirir", "Özkaynak katkısıdır; kaynağı ne olursa olsun hasılat sayılmaz", "Nakit akışıdır; tahakkukla ilgisi bulunmaz"],
        "Gelir, özkaynak sahiplerinin katkıları dışındaki varlık artışı veya yükümlülük azalışından kaynaklanan özkaynak artışıdır.",
        "Ortak katkı ve dağıtımları işletmenin performansından değil, sahiplerle yapılan sermaye işlemlerinden doğar.",
        "Kavramsal Çerçeve, 4.68-4.72", "medium",
    ),
    r(
        "Karar verecek yatırımcı için bir bilgi gelecekteki sonuçları tahmin etmeye veya önceki değerlendirmeleri doğrulamaya yardımcı olmaktadır. Hangi temel nitelik söz konusudur?",
        "İhtiyaca uygun finansal bilginin tahmin ve doğrulama değerleri arasındaki ilişki nedir?",
        "İhtiyaca uygunluktur; karar değeri taşır",
        ["Anlaşılmazlıktır; bilgi kullanıcıdan gizlenir", "Taraflılıktır; belirli sonucu zorunlu kılar", "Zamansızlıktır; karar sonrasında sunulur", "Tutarsızlıktır; dönemler arası karşılaştırmayı önler"],
        "İhtiyaca uygun bilgi kullanıcı kararında fark yaratabilir ve tahmin değeri, doğrulama değeri veya her ikisini taşır.",
        "Tahmin ve doğrulama değeri birbirine bağlıdır; önceki tahminlerin sonucu sonraki tahminlerin girdisi olabilir.",
        "Kavramsal Çerçeve, 2.6-2.11", "easy",
    ),
    r(
        "Raporlanan açıklama tam, tarafsız ve hatasız bir sürecin ürünü olacak biçimde hazırlanmıştır. Hangi temel nitelik hedeflenmiştir?",
        "Gerçeğe uygun sunumun üç özelliği nelerdir?",
        "Gerçeğe uygun sunum; tamlık, tarafsızlık ve hatasızlık",
        ["İhtiyaca uygunluk; yalnız kârı artırma ve gizlilik", "Karşılaştırılabilirlik; sadece aynı tutarları tekrarlama", "Anlaşılabilirlik; karmaşık bilgiyi rapordan çıkarma", "Zamanında sunum; doğrulamadan önce yayımlama"],
        "Gerçeğe uygun sunum, ekonomik olayın özünü tam, tarafsız ve hatasız biçimde yansıtmayı amaçlar.",
        "Hatasızlık her bakımdan kusursuz sonuç garantisi değil, açıklama ve tahmin sürecinde hata bulunmaması anlamındadır.",
        "Kavramsal Çerçeve, 2.12-2.22", "medium",
    ),
    r(
        "İşletme müşterilerden nakit tahsilatını, yeni makine alımını ve banka kredisi tahsilini aynı faaliyet grubunda göstermiştir. TMS 7'ye uygun sınıflama nedir?",
        "Nakit akış tablosunun üç temel faaliyet sınıfı hangileridir?",
        "Sırasıyla esas, yatırım ve finansmandır",
        ["Üçü de esas faaliyet nakit akışıdır", "Üçü de yatırım faaliyeti nakit akışıdır", "Üçü de finansman faaliyeti nakit akışıdır", "Hiçbiri nakit akış tablosunda gösterilmez"],
        "Müşteri tahsilatı ana hasılat faaliyetinden, makine alımı uzun vadeli varlık ediniminden, kredi tahsili finansman yapısından kaynaklanır.",
        "TMS 7 dönemin nakit akışlarını esas, yatırım ve finansman faaliyetlerine ayırır.",
        "TMS 7 Nakit Akış Tablosu, par. 10-17", "easy",
    ),
    r(
        "İşletme vadesine dört ay kalan ve değer değişim riski önemli olan bir yatırımı nakit benzeri saymıştır. Sınıflandırma doğru mudur?",
        "Bir yatırımın nakit benzeri sayılması için hangi özellikleri taşıması gerekir?",
        "Hayır; likit ve değer değişim riski önemsiz olmalıdır",
        ["Evet; bütün finansal yatırımlar nakit benzeridir", "Hayır; nakit benzeri yalnız fiziki stoklardan oluşur", "Evet; vade ve değer riski sınıflamayı etkilemez", "Hayır; banka hesapları nakit tanımına hiçbir zaman girmez"],
        "Nakit benzerleri kısa vadeli nakit taahhütlerini karşılamak için tutulan, kolayca belirli nakde çevrilen ve değer değişim riski önemsiz yatırımlardır; edinimden itibaren üç ay veya daha kısa vade örnektir.",
        "Yatırım amacıyla tutulan araçlar kural olarak nakit benzeri değildir; likidite ve değer riski birlikte değerlendirilir.",
        "TMS 7, par. 6-9", "medium",
    ),
]


PREMISES = [
    {"stem": "Tam finansal tablo seti bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Finansal durum tablosu sette yer alır\n\nII. Nakit akış tablosu sette yer alır\n\nIII. Dipnotlar setin parçasıdır", "correct": "I, II ve III", "why": "TMS 1 uyarınca finansal durum ve nakit akış tabloları ile dipnotlar tam setin parçalarıdır.", "ref": "TMS 1, par. 10", "difficulty": "easy"},
    {"stem": "Finansal tablo sunumu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Karşılaştırmalı bilgi sunulur\n\nII. Sunum sınıflaması kural olarak tutarlı sürdürülür\n\nIII. Önemli kalemler ayrı sunulur", "correct": "I, II ve III", "why": "Karşılaştırma, tutarlılık ve önemli kalemlerin ayrı sunumu TMS 1'in temel sunum ilkeleridir.", "ref": "TMS 1, par. 29-46", "difficulty": "medium"},
    {"stem": "Dönen varlık sınıflaması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Normal faaliyet döngüsünde satılması beklenen varlık dönen olabilir\n\nII. Alım satım amacıyla tutulan varlık dönen olabilir\n\nIII. Bütün nakitler kullanımı kısıtlı olsa da dönen sayılır", "correct": "I ve II", "why": "Faaliyet döngüsü ve alım satım amacı dönen varlık ölçütleridir. En az on iki ay kullanımı kısıtlı nakit dönen sayılmayabileceğinden III yanlıştır.", "ref": "TMS 1, par. 66", "difficulty": "medium"},
    {"stem": "Genel sunum ilkeleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. TFRS izin vermedikçe mahsup yapılmaz\n\nII. İşletmenin sürekliliği hiçbir koşulda sorgulanamaz\n\nIII. Nakit akış tablosu dışındaki tablolar tahakkuk esasına dayanır", "correct": "I ve III", "why": "Mahsup yasağı ve tahakkuk esası geçerlidir. Süreklilik yönetimce değerlendirilir; uygun değilse başka esas kullanılır, bu nedenle II yanlıştır.", "ref": "TMS 1, par. 25-35", "difficulty": "medium"},
    {"stem": "Kavramsal Çerçeveye göre aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Özkaynak bütün yükümlülüklerden önce gelen sabit bir borçtur\n\nII. Varlık geçmiş olay sonucu kontrol edilen mevcut ekonomik kaynaktır\n\nIII. Yükümlülük ekonomik kaynak devretme mükellefiyetidir", "correct": "II ve III", "why": "Varlık ve yükümlülük ifadeleri doğrudur. Özkaynak yükümlülüklerden sonraki kalıntı pay olduğundan I yanlıştır.", "ref": "Kavramsal Çerçeve, Bölüm 4", "difficulty": "easy"},
    {"stem": "Yararlı finansal bilginin nitelikleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İhtiyaca uygunluk temel niteliktir\n\nII. Gerçeğe uygun sunum yalnız destekleyici niteliktir\n\nIII. Karşılaştırılabilirlik destekleyici niteliktir", "correct": "I ve III", "why": "İhtiyaca uygunluk ve gerçeğe uygun sunum temel, karşılaştırılabilirlik destekleyici niteliktir. Bu nedenle II yanlıştır.", "ref": "Kavramsal Çerçeve, Bölüm 2", "difficulty": "medium"},
    {"stem": "Nakit akış tablosu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Müşteriden tahsilat genellikle esas faaliyettir\n\nII. Maddi duran varlık alımı genellikle yatırım faaliyetidir\n\nIII. Banka kredisi tahsili esas faaliyet olarak sınıflandırılır", "correct": "I ve II", "why": "Müşteri tahsilatı esas, duran varlık alımı yatırım faaliyetidir. Kredi tahsili finansman faaliyeti olduğundan III yanlıştır.", "ref": "TMS 7, par. 10-17", "difficulty": "easy"},
    {"stem": "TFRS 18 geçişi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. TFRS 18 bütün işletmeler için 2026'da zorunludur\n\nII. Erken uygulamaya izin verilir\n\nIII. 2026'da erken uygulama yoksa TMS 1 esas alınır", "correct": "II ve III", "why": "TFRS 18, 2027'de zorunlu olur; erken uygulanabilir. 2026'da erken uygulama belirtilmedikçe TMS 1 geçerlidir; I yanlıştır.", "ref": "TFRS 18 Ek C, par. C1", "difficulty": "medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="mali_tablolar_analizi",
        topic_id="finansal_tablolar",
        label="Finansal Tablolar",
        slug="finansal_tablolar",
        prefix="topic-fnt",
        seed=2026071742,
        legislation_version=(
            "KGK 2026 TFRS seti; TMS 1, TMS 7 ve Finansal Raporlamaya İlişkin "
            "Kavramsal Çerçeve; TFRS 18 geçiş hükümleri (17.07.2026 kontrolü)"
        ),
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
