#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Türk Vergi Sisteminin Yapısı, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Bir sınıflandırmada gelir ve kurumlar vergisi ilk; KDV ve ÖTV ikinci; emlak ve motorlu taşıtlar vergisi üçüncü grupta toplanmıştır. Grupların sırası hangisidir?",
        "Vergiler, üzerine konuldukları ekonomik kaynak bakımından hangi üç ana grupta incelenir?",
        "Gelir, harcama ve servet vergileri",
        "Gelir, harcama ve servet vergileri",
        ["Servet, nüfus ve meslek vergileri", "Harcama, ceza ve ruhsat vergileri", "Gelir, ücret ve belediye vergileri", "Kazanç, belge ve yargı vergileri"],
        ["Merkez, taşra ve belediye vergileri", "Beyan, tarh ve tahsil vergileri", "Gerçek, tüzel ve ortaklık vergileri", "Sürekli, geçici ve ceza vergileri"],
        "Gelir ve kurumlar vergileri geliri; KDV ve ÖTV harcamayı; emlak ve motorlu taşıtlar vergileri serveti vergilendirir.",
        "Ekonomik konuya göre temel ayrım gelir, harcama ve servet vergileridir.",
        "193 sayılı GVK m. 1; 5520 sayılı KVK m. 1 ve 6; 3065 sayılı KDVK m. 1; 1319 sayılı EVK m. 1 ve 12",
        "easy",
    ),
    r(
        "Vergiyi kanunen ödeyen kişinin yükü fiyat yoluyla başka kişiye aktarması kolaydır. Bu vergi hangi gruba daha yakındır?",
        "Dolaylı ve dolaysız vergi ayrımında temel ekonomik ölçüt hangisidir?",
        "Yükü yansıtılabilen dolaylı vergi",
        "Vergi yükünün yansıtılabilmesi",
        ["Dolaysız vergi", "Servet üzerinden vergi", "Şahsî gelir vergisi", "Yerel yönetim vergisi"],
        ["Beyannamenin elektronik verilmesi", "Verginin merkezden tahsil edilmesi", "Mükellefin tüzel kişi olması", "Tarh işleminin yazılı yapılması"],
        "Dolaylı vergilerde kanuni mükellef ile ekonomik yükü taşıyan kişi çoğu kez ayrılır; yük fiyat aracılığıyla yansıtılabilir.",
        "Bu ayrım, kanuni ödeme ödevinden çok vergi yükünün başkasına aktarılabilme özelliğine dayanır.",
        "3065 sayılı KDVK m. 8, 20 ve 29; Türk Vergi Sistemi — vergi yansıması",
        "easy",
    ),
    r(
        "Bir gerçek kişinin yıllık geliri, kişisel durumu da dikkate alınarak vergilendirilmektedir. Verginin yapısal niteliği hangisidir?",
        "Gelir vergisi ekonomik kaynak ve yansıma bakımından nasıl sınıflandırılır?",
        "Şahsî ve dolaysız gelir vergisi",
        "Gelir üzerinden alınan dolaysız vergi",
        ["Objektif ve dolaylı harcama vergisi", "Servet transferinden alınan vergi", "Belge üzerinden alınan işlem vergisi", "Tüketimden alınan özel vergi"],
        ["Harcama üzerinden alınan dolaylı vergi", "Servet üzerinden alınan yerel vergi", "İşlem üzerinden alınan belge vergisi", "Mal üzerinden alınan özel tüketim vergisi"],
        "GVK gerçek kişilerin gelirini vergilendirir; gelir vergisi dolaysız ve kişisel nitelikli bir gelir vergisidir.",
        "Gelir vergisinin konusu gerçek kişinin geliridir ve yük kural olarak gelir sahibi üzerinde kalır.",
        "193 sayılı GVK m. 1-2; Türk Vergi Sistemi — dolaysız vergiler",
        "easy",
    ),
    r(
        "Bir sermaye şirketinin safi kurum kazancı üzerinden vergi hesaplanmıştır. Bu vergi hangi sınıfta yer alır?",
        "Kurumlar vergisinin konusu ve ekonomik sınıfı hangisidir?",
        "Dolaysız gelir vergisi",
        "Kurum kazancından alınan dolaysız vergi",
        ["Dolaylı tüketim vergisi", "Servet transferi vergisi", "Belge ve işlem vergisi", "Yerel emlak vergisi"],
        ["Teslim üzerinden alınan dolaylı vergi", "Taşıt üzerinden alınan servet vergisi", "Kâğıt üzerinden alınan işlem vergisi", "İntikal üzerinden alınan servet vergisi"],
        "Kurumlar vergisi, kanundaki kurumların safi kurum kazancı üzerinden alınan dolaysız bir gelir vergisidir.",
        "Verginin konusu kurum kazancıdır; bu nedenle gelir vergileri grubunda ve dolaysız vergiler arasında yer alır.",
        "5520 sayılı KVK m. 1 ve 6",
        "easy",
    ),
    r(
        "Bir işletme satışında KDV hesaplayıp alışlarında yüklendiği KDV'yi indirerek kalan tutarı beyan etmiştir. Ekonomik yük olağan olarak kimde kalır?",
        "KDV'nin Türk vergi sistemindeki yapısal niteliği hangisidir?",
        "Ekonomik yük nihai tüketicide",
        "Genel ve dolaylı tüketim vergisi",
        ["Satıcının çalışanlarında", "Vergi dairesi personelinde", "Malı üreten ilk işletmede", "İndirimi yapan mali müşavirde"],
        ["Şahsî ve dolaysız gelir vergisi", "Yerel ve dolaysız servet vergisi", "Miras üzerinden alınan intikal vergisi", "Yalnız belgelerden alınan işlem vergisi"],
        "KDV zincir içinde hesaplanıp indirilir; olağan yansıma sonucunda ekonomik yük nihai tüketici üzerinde kalır.",
        "KDV geniş işlem alanına uygulanan, indirim mekanizmalı genel bir dolaylı tüketim vergisidir.",
        "3065 sayılı KDVK m. 1, 8, 20 ve 29",
        "medium",
    ),
    r(
        "Kanuna ekli listede yer alan bir mal, kanunda belirlenen aşamada bir defaya mahsus vergilendirilmiştir. Söz konusu vergi hangisidir?",
        "Özel tüketim vergisini KDV'den ayıran temel yapısal özellik hangisidir?",
        "Özel tüketim vergisi",
        "Listeli mallarda bir defalık uygulanması",
        ["Katma değer vergisi", "Gelir vergisi", "Emlak vergisi", "Veraset ve intikal vergisi"],
        ["Her mal ve hizmette çok aşamalı uygulanması", "Gerçek kişinin yıllık gelirini vergilemesi", "Bina ve arazi değerini vergilemesi", "Miras yoluyla intikali vergilemesi"],
        "ÖTV, kanuna ekli listelerdeki belirli malları kanunda gösterilen aşamada bir defaya mahsus vergilendirir.",
        "ÖTV seçilmiş listeli mallara bir kez uygulanırken KDV genel olarak teslim ve hizmet zincirinde çok aşamalıdır.",
        "4760 sayılı ÖTVK m. 1 ve 3",
        "easy",
    ),
    r(
        "Taraflar, kanuna ekli tabloda yer alan bir sözleşmeyi imzalamıştır. Vergi, sözleşmenin kâğıt niteliği üzerinden doğmuştur. Hangi yapıya örnektir?",
        "Damga vergisi ekonomik sınıflandırmada en çok hangi gruba yakındır?",
        "Belge ve işlem vergisi",
        "Dolaylı işlem vergisi",
        ["Şahsî gelir vergisi", "Dönemsel servet vergisi", "Özel tüketim vergisi", "Kurum kazancı vergisi"],
        ["Dolaysız gelir vergisi", "Dolaysız servet vergisi", "Kurum kazancı vergisi", "Miras intikali vergisi"],
        "Damga vergisi, kanundaki kâğıtları hukuki işlemi belgelemesi nedeniyle vergilendiren bir işlem vergisidir.",
        "Damga vergisi gelir veya servetin kendisini değil, kanundaki kâğıda bağlanan işlemi vergilendirdiği için dolaylı işlem vergileri içinde değerlendirilir.",
        "488 sayılı Damga Vergisi Kanunu m. 1 ve 3",
        "medium",
    ),
    r(
        "Bir banka, kendi lehine aldığı para nedeniyle banka ve sigorta muameleleri vergisi hesaplamıştır. Bu vergi hangi ekonomik gruptadır?",
        "Banka ve sigorta muameleleri vergisinin konusu esas olarak nedir?",
        "Dolaylı işlem vergisi",
        "İşlem nedeniyle lehe alınan para",
        ["Dolaysız gelir vergileri", "Dönemsel servet vergileri", "Miras ve intikal vergileri", "Yerel emlak vergileri"],
        ["Bankanın yıllık safi kurum kazancı", "Banka binasının vergi değeri", "Ortakların miras yoluyla edindiği pay", "Çalışanların yıllık ücret geliri"],
        "BSMV, banka ve sigorta işlemleri dolayısıyla lehe alınan parayı konu alan dolaylı bir işlem vergisidir.",
        "Verginin konusu kurum kazancının tamamı değil, kanunda belirtilen işlemler nedeniyle lehe alınan paradır.",
        "6802 sayılı Gider Vergileri Kanunu m. 28 ve 30",
        "hard",
    ),
    r(
        "Bir kişi malik olduğu bina nedeniyle belediyeye vergi ödemektedir. Bu verginin ekonomik sınıfı hangisidir?",
        "Emlak vergisi hangi servet unsurunu konu edinir?",
        "Dolaysız servet vergisi",
        "Türkiye'deki bina ve araziler",
        ["Dolaylı tüketim vergisi", "Şahsî gelir vergisi", "Belge ve işlem vergisi", "Servet transferi vergisi"],
        ["Gerçek kişilerin yıllık gelirleri", "Mal teslimi ve hizmet ifaları", "İmzalanan bütün özel belgeler", "Yalnız miras yoluyla geçen mallar"],
        "Emlak vergisi bina ve arazi biçimindeki servet unsurlarını doğrudan vergilendirir.",
        "Emlak Vergisi Kanunu Türkiye'deki bina ve arazileri verginin konusuna alır.",
        "1319 sayılı EVK m. 1-3 ve 12-13",
        "easy",
    ),
    r(
        "Trafik siciline kayıtlı bir otomobil nedeniyle aracın kayıtlı sahibi vergi ödemektedir. Bu verginin yapısal niteliği hangisidir?",
        "Motorlu taşıtlar vergisinde mükellefiyet hangi hukuki bağa dayanır?",
        "Dolaysız servet vergisi",
        "İlgili sicilde adına kayıtlı olmaya",
        ["Dolaylı genel tüketim vergisi", "Şahsî kazanç vergisi", "Belge üzerinden alınan vergi", "Servet intikali vergisi"],
        ["Taşıt yakıtının her ay tüketilmesine", "Aracın yalnız ticari kazanç sağlamasına", "Taşıt için sözleşme imzalanmasına", "Aracın miras dışında edinilememesine"],
        "MTV, kayıt ve tescil edilmiş motorlu taşıt sahipliğini esas alan dolaysız bir servet vergisidir.",
        "Mükellef, trafik veya ilgili sicilde adına motorlu taşıt kayıt ve tescil edilmiş kişidir.",
        "197 sayılı MTVK m. 1 ve 3",
        "easy",
    ),
    r(
        "Bir kişi miras yoluyla karşılıksız mal edinmiştir. Bu edinim hangi ekonomik vergi grubuna girer?",
        "Veraset ve intikal vergisi hangi servet hareketini vergilendirir?",
        "Karşılıksız intikal vergisi",
        "Karşılıksız mal ve hak intikalini",
        ["Genel tüketim vergisi", "Dolaysız gelir vergisi", "Belge ve işlem vergisi", "Dönemsel taşıt vergisi"],
        ["Mal ve hizmetlerin bedelli teslimini", "Kurumların yıllık safi kazancını", "Binaların her yıl elde tutulmasını", "Bankaların lehe aldığı parayı"],
        "Veraset ve intikal vergisi, servetin miras veya diğer karşılıksız yollarla el değiştirmesini vergilendirir.",
        "Kanun, Türkiye'deki malların veraset yoluyla veya herhangi bir biçimde karşılıksız intikalini konu edinir.",
        "7338 sayılı VİVK m. 1 ve 5",
        "easy",
    ),
    r(
        "Aynı malın üretimden perakendeye uzanan zincirinde KDV her aşamada indirimli biçimde, ÖTV ise kanundaki aşamada bir kez uygulanmıştır. Doğru karşılaştırma hangisidir?",
        "KDV ile ÖTV'nin aşama yapısı arasındaki fark hangisidir?",
        "KDV çok aşamalı, ÖTV tek aşamalıdır",
        "KDV çok aşamalı, ÖTV tek aşamalıdır",
        ["Her ikisi yalnız son satışta alınır", "KDV tek, ÖTV çok aşamalıdır", "Her ikisi yalnız üretimde alınır", "Aşama bakımından tamamen aynıdır"],
        ["KDV bir defalık; ÖTV her aşamada indirimlidir", "Her ikisi gelir üzerinden hesaplanır", "Her ikisi yalnız bina sahipliğinde doğar", "ÖTV her işlemde genel olarak uygulanır"],
        "KDV teslim-hizmet zincirinde indirim mekanizmasıyla çok aşamalı; ÖTV listeli malda kanuni aşamada bir defalıktır.",
        "KDV genel ve çok aşamalı, ÖTV seçici ve bir defalık tüketim vergisidir.",
        "3065 sayılı KDVK m. 1 ve 29; 4760 sayılı ÖTVK m. 1 ve 3",
        "medium",
    ),
    r(
        "Aşağıdaki vergi çiftlerinden hangisinde iki vergi de kural olarak dolaysızdır?",
        "Dolaysız vergi örneklerini birlikte gösteren seçenek hangisidir?",
        "Gelir vergisi ve kurumlar vergisi",
        "Emlak ve motorlu taşıtlar vergisi",
        ["KDV ile özel tüketim vergisi", "Damga vergisi ve katma değer vergisi", "Banka muameleleri vergisi ve özel tüketim vergisi", "Katma değer vergisi ve emlak vergisi"],
        ["Katma değer vergisi ve damga vergisi", "Özel tüketim vergisi ve banka muameleleri vergisi", "Gelir vergisi ve katma değer vergisi", "Kurumlar vergisi ve özel tüketim vergisi"],
        "Gelir ve kurumlar vergileri, vergi yükünün kural olarak mükellef üzerinde kaldığı dolaysız gelir vergileridir.",
        "Emlak ve motorlu taşıtlar vergileri servet unsurunu doğrudan vergilendiren dolaysız vergilerdir.",
        "193 sayılı GVK m. 1; 5520 sayılı KVK m. 1; 1319 sayılı EVK; 197 sayılı MTVK",
        "easy",
    ),
    r(
        "Aşağıdaki vergi çiftlerinden hangisinde iki vergi de kural olarak dolaylı tüketim veya işlem vergisidir?",
        "Dolaylı vergi örneklerini birlikte gösteren seçenek hangisidir?",
        "KDV ve özel tüketim vergisi",
        "Damga vergisi ve banka muameleleri vergisi",
        ["Gelir vergisi ve kurumlar vergisi", "Emlak vergisi ve motorlu taşıtlar vergisi", "Gelir vergisi ve emlak vergisi", "Kurumlar vergisi ve veraset vergisi"],
        ["Gelir vergisi ve kurumlar vergisi", "Emlak vergisi ve motorlu taşıtlar vergisi", "Veraset vergisi ve gelir vergisi", "Kurumlar vergisi ve emlak vergisi"],
        "KDV ve ÖTV, fiyat mekanizmasıyla yansıtılabilen dolaylı tüketim vergileridir.",
        "Damga vergisi ile BSMV, gelir veya servetin kendisi yerine işlem üzerinden alınan dolaylı vergilerdir.",
        "3065 sayılı KDVK; 4760 sayılı ÖTVK; 488 sayılı DVK; 6802 sayılı Gider Vergileri Kanunu",
        "easy",
    ),
    r(
        "Satıcı KDV'yi beyan edip vergi dairesine ödemiş; bedel içindeki vergi yükünü alıcı taşımıştır. Satıcının ve alıcının sıfatları sırasıyla hangisidir?",
        "Dolaylı vergide kanuni mükellef ile ekonomik yüklenici neden ayrılabilir?",
        "Kanuni mükellef ve ekonomik yüklenici",
        "Vergi fiyat yoluyla yansıtılabildiği için",
        ["Ekonomik yüklenici ve vergi sorumlusu", "Vergi sorumlusu ve kanuni mükellef", "Nihai tüketici ve vergi dairesi", "Dar mükellef ve tam mükellef"],
        ["Beyanname yalnız kâğıtla verildiği için", "Her mükellef tüzel kişi olduğu için", "Vergi mutlaka belediyece alındığı için", "Matrah yalnız fiziksel miktar olduğu için"],
        "KDV'de teslimi yapan kanuni mükelleftir; fiyat içindeki ekonomik yük olağan olarak alıcıya ve sonunda nihai tüketiciye yansır.",
        "Fiyata eklenebilen dolaylı vergide ödeme ödevi ile ekonomik yük farklı kişilerde kalabilir.",
        "3065 sayılı KDVK m. 8, 20 ve 29; Türk Vergi Sistemi — kanuni ve ekonomik mükellef",
        "medium",
    ),
    r(
        "İşveren, çalışanın ücretinden gelir vergisi kesip vergi dairesine yatırmıştır. Bu tahsil yöntemi gelir vergisini dolaylı vergiye dönüştürür mü?",
        "Gelir vergisinin tevkifat yoluyla alınması verginin ekonomik sınıfını nasıl etkiler?",
        "Hayır; gelir vergisi dolaysız kalır",
        "Tevkifat dolaysız niteliği değiştirmez",
        ["Evet; her kesinti dolaylı vergidir", "Evet; ücret artık tüketim sayılır", "Hayır; vergi servet vergisine dönüşür", "Evet; işveren nihai tüketici olur"],
        ["Vergiyi dolaylı tüketim vergisine çevirir", "Vergiyi servet transferi vergisine çevirir", "Vergiyi yerel emlak vergisine çevirir", "Verginin konusunu belge işlemi yapar"],
        "Tevkifat bir tahsil tekniğidir; verginin konusu ücret geliri, ekonomik yüklenicisi ücretli olduğundan gelir vergisi dolaysız kalır.",
        "Verginin kaynakta kesilmesi, gelir üzerinden alınan dolaysız vergi olma niteliğini değiştirmez.",
        "193 sayılı GVK m. 61 ve 94",
        "medium",
    ),
    r(
        "Vergi hesabında mükellefin medeni durumu, kişisel giderleri veya özel koşulları değil yalnız işlem esas alınmıştır. Bu vergi hangi niteliğe daha yakındır?",
        "Objektif vergi ile şahsî vergi arasındaki temel ayrım hangisidir?",
        "Objektif vergi",
        "Kişisel koşulların dikkate alınması",
        ["Şahsî vergi", "Servet transferi vergisi", "Artan oranlı gelir vergisi", "Dolaysız kurumlar vergisi"],
        ["Verginin elektronik beyan edilmesi", "Verginin merkezî idarece alınması", "Mükellefin gerçek kişi olması", "Verginin bir kanuna dayanması"],
        "İşlemi kişisel koşullardan bağımsız vergilendiren KDV ve benzeri vergiler objektif vergi niteliğindedir.",
        "Şahsî vergiler ödeme gücüne ilişkin kişisel unsurları, objektif vergiler ise esas olarak vergi konusu işlemi dikkate alır.",
        "193 sayılı GVK; 3065 sayılı KDVK; Türk Vergi Sistemi — şahsî ve objektif vergiler",
        "medium",
    ),
    r(
        "2026 yılında sayısal yüzdeler dikkate alınmadan, gerçek kişinin gelirinde matrah yükseldikçe sonraki dilimlerde vergi yüzdesi de yükselmektedir. Yapı hangisidir?",
        "2026 yılında sayısal yüzdeler dikkate alınmadan, Gelir Vergisi Kanunu'ndaki yükselen dilimli tarifenin yapısal niteliği hangisidir?",
        "Artan oranlı tarife",
        "Yükselen dilimli vergi tarifesi",
        ["Tek oranlı tarife", "Azalan oranlı tarife", "Sabit tutarlı tarife", "Yalnız nispi olmayan tarife"],
        ["Her gelir düzeyinde azalan tarife", "Yalnız sabit tutarlı tarife", "Matrahtan bağımsız tek maktu tarife", "Vergisiz ve dilimsiz tarife"],
        "GVK m. 103 tarifesi dilimlidir; matrah üst dilimlere çıktıkça o dilime uygulanan oran yükselir.",
        "Gelir vergisi tarifesi, matrah dilimleri için yükselen oranlar öngördüğünden artan oranlıdır.",
        "193 sayılı GVK m. 103",
        "easy",
    ),
    r(
        "Bir vergi, matrahın parasal değerine yüzde uygulanarak hesaplanmaktadır. Bu hesaplama tekniği hangisidir?",
        "Spesifik vergi ile ad valorem vergi arasındaki ölçü farkı hangisidir?",
        "Ad valorem vergileme",
        "Değer ile fiziksel ölçü ayrımı",
        ["Spesifik vergileme", "Maktu ceza uygulaması", "Kaynakta kesinti yöntemi", "Servet transferi yöntemi"],
        ["Merkezî idare ile belediye ayrımı", "Gerçek kişi ile kurum ayrımı", "Beyan ile tahsil zamanı ayrımı", "Dolaysız ile şahsî vergi ayrımı"],
        "Parasal değere oran uygulanması değer esaslı, diğer adıyla ad valorem vergilemedir.",
        "Ad valorem vergi değere; spesifik vergi ağırlık, hacim, adet veya teknik ölçü gibi fiziksel birime dayanır.",
        "4760 sayılı ÖTVK m. 11-12; 197 sayılı MTVK m. 5-6; Türk Vergi Sistemi — matrah türleri",
        "medium",
    ),
    r(
        "Bir belediye sınırları içindeki bina için emlak vergisini tarh etmektedir. Bu vergi idari yapı bakımından nasıl nitelendirilir?",
        "Emlak vergisini merkezî vergilerden ayıran idari özellik hangisidir?",
        "Yerel yönetim vergisi",
        "Belediyece tarh ve tahsil edilmesi",
        ["Merkezî gelir vergisi", "Genel tüketim vergisi", "Gümrük vergisi", "Kurum kazancı vergisi"],
        ["Yalnız kurum kazancına dayanması", "Her aşamada indirimli uygulanması", "Miras intikalini konu alması", "Banka işlemlerinden alınması"],
        "Emlak vergisi bina ve arazi için ilgili belediyece tarh ve tahsil edilen yerel bir servet vergisidir.",
        "Emlak vergisinin uygulanması ve geliri belediye yapısıyla bağlantılıdır; bu yönüyle merkezî idare vergilerinden ayrılır.",
        "1319 sayılı EVK m. 11, 21 ve 37",
        "medium",
    ),
    r(
        "Bir verginin konusu mal teslimi, matrahı ise bu teslimin karşılığını oluşturan bedeldir. Konu ile matrah arasındaki doğru ilişki hangisidir?",
        "Verginin konusu ile matrahı yapısal olarak nasıl ayrılır?",
        "Konu işlem, matrah hesaplama ölçüsüdür",
        "Konu ekonomik unsur, matrah ölçüdür",
        ["Konu ve matrah her durumda aynı kavramdır", "Konu oranı, matrah mükellefi gösterir", "Konu tahsili, matrah tebliği gösterir", "Konu cezayı, matrah süreyi gösterir"],
        ["Konu vergi oranı, matrah ödeme süresidir", "Konu beyanname, matrah vergi dairesidir", "Konu tahsil yöntemi, matrah mükelleftir", "Konu yaptırım, matrah dava süresidir"],
        "KDV'de teslim veya hizmet verginin konusunu, bunların bedeli ise verginin hesaplanacağı matrahı oluşturur.",
        "Verginin konusu neyin vergilendirildiğini, matrah ise verginin hangi değer veya miktar üzerinden hesaplanacağını gösterir.",
        "3065 sayılı KDVK m. 1 ve 20; Türk Vergi Sistemi — konu ve matrah",
        "easy",
    ),
    r(
        "KDV bütün teslim ve hizmet zincirine genel olarak uygulanırken ÖTV yalnız kanun ekindeki malları hedeflemektedir. Bu fark nasıl ifade edilir?",
        "Genel tüketim vergisi ile seçici tüketim vergisinin tipik örnekleri sırasıyla hangileridir?",
        "KDV genel, ÖTV seçici tüketim vergisidir",
        "KDV ile özel tüketim vergisi",
        ["KDV seçici, ÖTV genel tüketim vergisidir", "Her ikisi yalnız gelir üzerinden alınır", "Her ikisi servetin elde tutulmasını vergiler", "KDV ve ÖTV yalnız belge üzerinden alınır"],
        ["Gelir ve kurumlar vergileri", "Emlak vergisi ve motorlu taşıtlar vergisi", "Damga vergisi ve veraset vergisi", "Kurumlar vergisi ve emlak vergisi"],
        "KDV geniş teslim ve hizmet alanını kapsayan genel; ÖTV ise listeli malları hedefleyen seçici tüketim vergisidir.",
        "Genel tüketim vergisinin temel örneği KDV, seçici tüketim vergisinin temel örneği ÖTV'dir.",
        "3065 sayılı KDVK m. 1; 4760 sayılı ÖTVK m. 1",
        "easy",
    ),
    r(
        "Bir bina elde tutulduğu için her dönem emlak vergisine, miras yoluyla yeni sahibine geçtiği için ayrıca veraset ve intikal vergisine konu olmuştur. Vergiler sırasıyla neyi ölçer?",
        "Servet vergilerinde sahiplik vergisi ile transfer vergisi ayrımına örnek hangisidir?",
        "Servet sahipliği ve servet transferi",
        "Emlak vergisi ve veraset ve intikal vergisi",
        ["Gelir elde etme ve tüketim harcaması", "Belge düzenleme ve banka işlemi", "Mal teslimi ve hizmet ifası", "Kurum kazancı ve ücret geliri"],
        ["KDV ve özel tüketim vergisi", "Gelir vergisi ve kurumlar vergisi", "Damga vergisi ve banka muameleleri vergisi", "Kurumlar vergisi ve motorlu taşıtlar vergisi"],
        "Emlak vergisi mevcut servet unsurunun sahipliğini; veraset ve intikal vergisi servetin karşılıksız el değiştirmesini vergilendirir.",
        "Emlak vergisi servet sahipliğine, veraset ve intikal vergisi servet transferine örnektir.",
        "1319 sayılı EVK m. 1-3; 7338 sayılı VİVK m. 1 ve 5",
        "medium",
    ),
    r(
        "KDV mükellefi, satışları üzerinden hesapladığı vergiden faaliyetle ilgili alışlarında yüklendiği vergiyi indirmiştir. Bu mekanizmanın yapısal işlevi hangisidir?",
        "KDV'de indirim mekanizması verginin hangi niteliğini gerçekleştirir?",
        "Yalnız eklenen değeri vergilemek",
        "Zincirdeki mükerrer vergi yükünü önlemek",
        ["Kurum kazancını tamamen vergiden çıkarmak", "Bina sahipliğini tüketim saymak", "Miras intikalini vergisiz bırakmak", "Gelir vergisini servet vergisine çevirmek"],
        ["Vergiyi tek aşamalı ÖTV'ye dönüştürmek", "Mükellefin yıllık gelirini hesaplamak", "Taşıt sahipliğini vergilendirmek", "Belge imzalanmasını verginin konusu yapmak"],
        "Hesaplanan KDV'den indirilebilir yüklenilen KDV'nin düşülmesi, zincirin her aşamasında yalnız eklenen değerin yüklenmesini sağlar.",
        "İndirim mekanizması, önceki aşamada ödenen verginin yeniden yük oluşturmasını önleyerek KDV'nin katma değer niteliğini korur.",
        "3065 sayılı KDVK m. 29 ve 34",
        "medium",
    ),
    r(
        "Kurum, mal satışında KDV ve dönem sonunda safi kazancı üzerinden kurumlar vergisi ödemiştir. Vergilerin ekonomik kaynakları sırasıyla hangisidir?",
        "Aynı işletmenin KDV ve kurumlar vergisi mükellefi olması hangi yapısal gerçeği gösterir?",
        "Harcama ve gelir",
        "Farklı konuların ayrı vergiler doğurabilmesini",
        ["Servet ve servet transferi", "Gelir ve servet", "Belge ve servet", "Harcama ve miras"],
        ["Her mükellefin yalnız tek vergi ödeyebilmesini", "KDV ile kurumlar vergisinin aynı matraha dayanmasını", "Dolaylı vergilerin kazanç üzerinden alınmasını", "Kurumlar vergisinin tüketiciye ait olmasını"],
        "KDV mal veya hizmete yönelik harcamayı, kurumlar vergisi kurumun safi kazancını konu edinir.",
        "Bir kişi farklı vergilerin konusuna giren ayrı olaylar gerçekleştirdiğinde hem dolaylı hem dolaysız verginin mükellefi olabilir.",
        "3065 sayılı KDVK m. 1 ve 8; 5520 sayılı KVK m. 1 ve 6",
        "medium",
    ),
    r(
        "Bir vergi oranı değiştirilmemiş, ancak fiyat artışı nedeniyle değer esaslı matrah büyümüş ve ödenecek vergi artmıştır. Bu durum hangi matrah yapısına uygundur?",
        "Değer esaslı vergide nominal matrah artışının vergi tutarına etkisi genel olarak nasıldır?",
        "Ad valorem matrah yapısı",
        "Vergi tutarını aynı yönde artırır",
        ["Yalnız fiziksel ölçülü yapı", "Sabit maktu vergi yapısı", "Kaynakta kesinti yapısı", "Servet transferi yapısı"],
        ["Vergi tutarını kendiliğinden sıfırlar", "Vergiyi dolaysız hâle getirir", "Mükellefiyeti sona erdirir", "Vergiyi maktu cezaya dönüştürür"],
        "Değere oran uygulanan ad valorem vergide parasal matrah büyürse oran aynı kalsa da vergi tutarı artar.",
        "Değer esaslı matrah büyüdüğünde sabit oranla hesaplanan vergi de aynı yönde değişir.",
        "3065 sayılı KDVK m. 20; 4760 sayılı ÖTVK m. 11-12; Türk Vergi Sistemi — ad valorem vergiler",
        "medium",
    ),
]


PREMISES = [
    {"stem":"Ekonomik konuya göre sınıflandırma bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gelir vergisi gelir üzerinden alınır\n\nII. KDV harcama üzerinden alınır\n\nIII. Emlak vergisi servet üzerinden alınır","correct":"I, II ve III","why":"Gelir vergisi geliri, KDV harcamayı ve emlak vergisi serveti konu edinir.","ref":"193 sayılı GVK m. 1; 3065 sayılı KDVK m. 1; 1319 sayılı EVK m. 1 ve 12","difficulty":"easy"},
    {"stem":"Dolaylı ve dolaysız vergiler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dolaylı vergide yük fiyat yoluyla yansıtılabilir\n\nII. Dolaysız vergide yük kural olarak mükellefte kalır\n\nIII. Tahsilin kesintiyle yapılması vergiyi her durumda dolaylı kılar","correct":"I ve II","why":"İlk iki ifade ekonomik yansıma ayrımını açıklar; kesinti yalnız bir tahsil tekniğidir.","ref":"193 sayılı GVK m. 94; 3065 sayılı KDVK m. 8, 20 ve 29","difficulty":"medium"},
    {"stem":"KDV ve ÖTV bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KDV genel ve çok aşamalı bir tüketim vergisidir\n\nII. ÖTV her mal ve hizmete her aşamada uygulanır\n\nIII. ÖTV kanundaki listeli mallarda bir defaya mahsus uygulanır","correct":"I ve III","why":"KDV genel ve çok aşamalıdır; ÖTV ise listeli malları kanuni aşamada bir defa vergilendirir.","ref":"3065 sayılı KDVK m. 1 ve 29; 4760 sayılı ÖTVK m. 1 ve 3","difficulty":"medium"},
    {"stem":"Servet vergileri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KDV servetin elde tutulmasını vergilendirir\n\nII. Emlak vergisi bina ve araziyi konu edinir\n\nIII. Veraset ve intikal vergisi karşılıksız servet transferini vergilendirir","correct":"II ve III","why":"Emlak vergisi servet sahipliğini, veraset ve intikal vergisi karşılıksız transferi vergilendirir; KDV harcama vergisidir.","ref":"1319 sayılı EVK m. 1 ve 12; 7338 sayılı VİVK m. 1","difficulty":"easy"},
    {"stem":"Kanuni ve ekonomik mükellef ayrımı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KDV'de teslimi yapan kanuni mükelleftir\n\nII. Ekonomik yük olağan olarak nihai tüketiciye yansır\n\nIII. Kanuni mükellef her durumda ekonomik yükü de taşır","correct":"I ve II","why":"KDV'yi teslimi yapan beyan eder; fiyat mekanizması ekonomik yükü nihai tüketiciye taşıyabilir.","ref":"3065 sayılı KDVK m. 8, 20 ve 29","difficulty":"medium"},
    {"stem":"Türk vergi sisteminin yapısı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gelir ve kurumlar vergileri dolaysızdır\n\nII. KDV ve ÖTV dolaylıdır\n\nIII. Emlak ve motorlu taşıtlar vergileri servet vergileridir","correct":"I, II ve III","why":"Üç ifade de vergilerin ekonomik konu ve yansıma ölçütlerine göre yerleşik sınıflandırmasına uygundur.","ref":"193 sayılı GVK; 5520 sayılı KVK; 3065 sayılı KDVK; 4760 sayılı ÖTVK; 1319 sayılı EVK; 197 sayılı MTVK","difficulty":"easy"},
    {"stem":"2026 yılında sayısal yüzdeler dikkate alınmadan tarife ve matrah yapısı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gelir vergisi yükselen dilimli tarifeye sahiptir\n\nII. Ad valorem vergi yalnız fiziksel miktara dayanır\n\nIII. Spesifik vergi adet, ağırlık veya teknik ölçüye dayanabilir","correct":"I ve III","why":"GVK tarifesi artan oranlıdır; ad valorem değer, spesifik vergi fiziksel ölçü esaslıdır.","ref":"193 sayılı GVK m. 103; 4760 sayılı ÖTVK m. 11-12; 197 sayılı MTVK m. 5-6","difficulty":"hard"},
    {"stem":"Verginin konusu ve matrahı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Matrah hangi ekonomik unsurun vergilendirildiğini gösterir\n\nII. Konu verginin yöneldiği ekonomik unsur veya işlemdir\n\nIII. Matrah verginin hesaplanacağı değer veya miktardır","correct":"II ve III","why":"Konu neyin vergilendirildiğini, matrah ise bu konuya ilişkin hesaplama ölçüsünü gösterir.","ref":"3065 sayılı KDVK m. 1 ve 20; Türk Vergi Sistemi — konu ve matrah","difficulty":"medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="turk_vergi_sistemi",
        topic_id="vergi_sistemi_yapisi",
        label="Vergi Sisteminin Yapısı",
        slug="vergi_sistemi_yapisi",
        prefix="topic-tvs-vsy",
        seed=170726,
        legislation_version="193 sayılı GVK, 5520 sayılı KVK, 3065 sayılı KDVK, 4760 sayılı ÖTVK, 1319 sayılı EVK, 197 sayılı MTVK, 7338 sayılı VİVK, 488 sayılı DVK ve 6802 sayılı Gider Vergileri Kanunu; 17.07.2026 tarihinde yürürlükteki metinler",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
