#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Mesleki Etik, 3×20."""
from topic_pack_builder import write_topic


SHORT = {
    "Mesleki yeterlilik ve özen": "Yeterlilik ve özen",
    "Yeniden değerlendirme tehdidi": "Yeniden değerlendirme",
    "Tehdit kaldırılır veya kabul edilebilir düzeye indirilir": "Tehdit azaltılır veya kaldırılır",
    "Raporu dikkate almamalı ve ilişkilendirilmemelidir": "Raporla ilişki kurmamalıdır",
    "Baskının etkisini önlemeli ve karardan ödün vermemelidir": "Baskıya direnip tarafsız kalmalıdır",
    "Ulusal ve uluslararası gelişmeleri sürekli izlemek": "Mesleki gelişmeleri sürekli izlemek",
}


def r(s, f, c, d, w, ref, difficulty="medium", fc=None, fd=None):
    c = SHORT.get(c, c)
    fc = SHORT.get(fc or c, fc or c)
    d = [x.replace("Yalnız ücret tarifesi konusudur", "Yalnız müşteri tercihidir")
         .replace("Ücret tarifesini ortadan kaldırmak", "Mesleki standardı kaldırmak") for x in d]
    fd = [x.replace("Yalnız ücret tarifesi konusudur", "Yalnız müşteri tercihidir")
          .replace("Ücret tarifesini ortadan kaldırmak", "Mesleki standardı kaldırmak")
          for x in (fd or d)]
    return {"scenario": s, "focus": f, "correct": c, "focus_correct": fc,
            "distractors": list(d), "focus_distractors": list(fd), "why": w,
            "focus_why": f"Etik değerlendirmede ulaşılan sonuç şudur: {w}",
            "ref": ref, "difficulty": difficulty}


RULES = [
    r("Meslek mensubu müşteriye sunduğu bilgide doğru sözlü ve açık davranmıştır. Hangi temel ilkeye uymuştur?", "Mesleki ve iş ilişkilerinde doğruluk, güvenilirlik ve açık sözlülük hangi ilkedir?", "Dürüstlük", ["Yakınlık", "Yıldırma", "Kişisel çıkar", "Yeniden değerlendirme"], "Dürüstlük, mesleki ilişkilerde doğru, güvenilir, adil ve açık sözlü olmayı gerektirir.", "Etik Yönetmeliği Birinci Kısım m. 1/a ve 6", "easy"),
    r("Üçüncü kişinin baskısına rağmen mesleki kararından ödün vermeyen SMMM hangi ilkeyi korumuştur?", "Yanlılık, çıkar çatışması ve uygunsuz baskının mesleki kararı etkilememesi hangi ilkedir?", "Tarafsızlık", ["Gizlilik", "Reklam", "Kişisel çıkar", "Şarta bağlı ücret"], "Tarafsızlık, önyargı, çıkar çatışması ve uygunsuz baskı nedeniyle mesleki karardan ödün vermemektir.", "Etik Yönetmeliği Birinci Kısım m. 1/b ve 8", "easy"),
    r("SMMM hizmeti teknik standartlara uygun, dikkatli ve zamanında tamamlamıştır. Hangi temel ilkeye uygun davranmıştır?", "Gerekli bilgi-beceri düzeyiyle teknik standartlara uygun özenli çalışma hangi ilkedir?", "Mesleki yeterlilik ve özen", ["Yakınlık tehdidi", "Kişisel çıkar tehdidi", "Taraf tutma tehdidi", "Yıldırma tehdidi"], "Mesleki yeterlilik ve özen, yeterli bilgi-beceriyle standartlara uygun, dikkatli ve gayretli hizmet sunmayı gerektirir.", "Etik Yönetmeliği Birinci Kısım m. 1/c ve 10", "easy"),
    r("Meslek mensubu müşteriden öğrendiği bilgiyi izinsiz üçüncü kişiye açıklamamış ve kendi yararına kullanmamıştır. Hangi ilke uygulanmıştır?", "Mesleki ilişkide edinilen bilgiyi yetkisiz açıklamama ve çıkar için kullanmama yükümlülüğü hangisidir?", "Gizlilik", ["Taraf tutma", "Mesleki atama", "Şarta bağlı ücret", "Yeniden değerlendirme"], "Gizlilik, mesleki bilgiyi yetkisiz açıklamamayı ve kişisel ya da üçüncü kişi çıkarı için kullanmamayı kapsar.", "Etik Yönetmeliği Birinci Kısım m. 1/ç ve 12", "easy"),
    r("Meslek mensubu kanunlara uymuş ve mesleğin itibarını zedeleyecek davranıştan kaçınmıştır. Hangi ilkeyi gözetmiştir?", "Mevzuata uyma ve mesleğin itibarını koruma yükümlülüğü hangi temel ilkedir?", "Mesleki davranış", ["Kişisel çıkar", "Yakınlık", "Yeniden değerlendirme", "Taraf tutma"], "Mesleki davranış ilkesi, mevzuata uymayı ve mesleğin itibarını zedeleyen davranışlardan kaçınmayı gerektirir.", "Etik Yönetmeliği Birinci Kısım m. 1/d ve 16", "easy"),
    r("SMMM'nin müşteri şirketinde önemli finansal yatırımı bulunması kararlarını etkileyebilecektir. Bu durum hangi tehdittir?", "Meslek mensubunun veya yakın ailesinin mali çıkarından doğan etik tehdit hangisidir?", "Kişisel çıkar tehdidi", ["Yeniden değerlendirme tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"], "Meslek mensubunun veya yakın ailesinin finansal ya da diğer çıkarları kişisel çıkar tehdidi yaratır.", "Etik Yönetmeliği Birinci Kısım m. 3/a", "easy"),
    r("Meslek mensubu daha önce kendi hazırladığı hesaplamayı sonradan denetlemektedir. Hangi tehdit ortaya çıkar?", "Önceki kararın o karardan sorumlu kişi tarafından yeniden incelenmesi hangi tehdit türüdür?", "Yeniden değerlendirme tehdidi", ["Kişisel çıkar tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"], "Kişinin daha önce sorumlu olduğu kararı yeniden değerlendirmesi yeniden değerlendirme tehdididir.", "Etik Yönetmeliği Birinci Kısım m. 3/b", "medium"),
    r("Meslek mensubu müşterisinin görüşünü tarafsızlığını tehlikeye atacak ölçüde savunmaktadır. Tehdit türü nedir?", "Bir durum veya fikri tarafsızlığı bozacak noktaya taşıma hangi tehdidi oluşturur?", "Taraf tutma tehdidi", ["Kişisel çıkar tehdidi", "Yeniden değerlendirme tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"], "Müşterinin görüşünü tarafsızlığı zedeleyecek ölçüde savunmak taraf tutma tehdidi yaratır.", "Etik Yönetmeliği Birinci Kısım m. 3/c", "medium"),
    r("Müşteri yöneticisiyle uzun ve yakın ilişki kuran SMMM, onun çıkarlarına uygun karar vermeye başlamıştır. Tehdit hangisidir?", "Üçüncü kişilerle yakın ilişki nedeniyle onların çıkarına davranma riski hangi tehdittir?", "Yakınlık tehdidi", ["Kişisel çıkar tehdidi", "Yeniden değerlendirme tehdidi", "Taraf tutma tehdidi", "Yıldırma tehdidi"], "Yakın ilişki nedeniyle üçüncü kişinin çıkarına davranma riski yakınlık tehdididir.", "Etik Yönetmeliği Birinci Kısım m. 3/ç", "medium"),
    r("İşveren, istenen muhasebe kaydı yapılmazsa SMMM'yi işten çıkaracağını söylemiştir. Bu hangi tehdittir?", "Gerçek veya hissedilen tehdit nedeniyle tarafsızlıktan kaçınmaya zorlanma hangi sınıftadır?", "Yıldırma tehdidi", ["Kişisel çıkar tehdidi", "Yeniden değerlendirme tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi"], "İşten çıkarma gibi baskılar, meslek mensubunu tarafsızlıktan uzaklaştırabilecek yıldırma tehdididir.", "Etik Yönetmeliği Birinci Kısım m. 3/d", "medium"),
    r("Etik tehdit önemsiz değildir. Meslek mensubu hiçbir önlem almadan işe devam etmek istemektedir. Doğru yaklaşım nedir?", "Kavramsal çerçevede önemli bir tehdit saptandığında hangi işlem yapılır?", "Tehdit kaldırılır veya kabul edilebilir düzeye indirilir", ["Tehdit görmezden gelinir", "Müşteriden saklanır", "Her durumda meslek unvanı bırakılır", "Yalnız ücret artırılır"], "Önemsiz olmayan tehditler uygun önlemlerle ortadan kaldırılmalı veya kabul edilebilir düzeye indirilmelidir.", "Etik Yönetmeliği Birinci Kısım m. 2", "medium", fc="Uygun etik önlemler uygulanır"),
    r("Etik tehdide karşı mesleğe giriş, sürekli eğitim ve disiplin düzeni uygulanmaktadır. Bunlar hangi önlem grubudur?", "Tehdit önlemleri yönetmelikte hangi iki ana kaynaktan doğar?", "Mevzuatla oluşturulan önlemler", ["Müşteri sırrını açıklayan işlemler", "Reklam ve tanıtım faaliyetleri", "Kişisel çıkarı artıran işlemler", "Şarta bağlı ücret düzenleri"], "Mesleğe giriş, eğitim, standart, izleme ve disiplin prosedürleri mevzuatla oluşturulan önlemlerdir.", "Etik Yönetmeliği Birinci Kısım m. 4", "medium", fc="Mevzuat ve iş çevresi önlemleri", fd=["Yalnız müşteri ve rakip önlemleri", "Sadece ücret ve reklam önlemleri", "Yalnız kişisel çıkar düzenleri", "Hiçbir kurumsal önlem kaynağı yoktur"]),
    r("SMMM önemli hata içerdiğini bildiği bir rapora adını bağlamak istemektedir. Dürüstlük ilkesi bakımından ne yapmalıdır?", "Yanıltıcı veya önemli hata içeren bilgiyle hazırlanmış rapor karşısında doğru tutum nedir?", "Raporu dikkate almamalı ve ilişkilendirilmemelidir", ["Hatasını bilerek raporu onaylamalıdır", "Yanıltıcı bilgiyi müşteriden saklamalıdır", "Raporu reklama dönüştürmelidir", "Hatanın devamını teşvik etmelidir"], "Meslek mensubu önemli hata, yanıltıcı ya da gizlenmiş ifade içerdiğini düşündüğü bilgi veya raporla ilişkilendirilmemelidir.", "Etik Yönetmeliği Birinci Kısım m. 7", "medium", fc="Yanıltıcı raporla ilişki kurmamak"),
    r("Müşterinin baskısı SMMM'nin mesleki yargısını etkileyebilecek düzeydedir. Tarafsızlığı korumak için ne yapmalıdır?", "Tarafsızlığı etkileyebilecek ortam ve ilişkiler karşısındaki temel tutum nedir?", "Baskının etkisini önlemeli ve karardan ödün vermemelidir", ["Baskıya koşulsuz uymalıdır", "Mesleki yargıyı müşteriye devretmelidir", "Yanlılığı mesleki kural saymalıdır", "Çıkar çatışmasını gizlemelidir"], "Meslek mensubu tarafsızlığını etkileyen baskı ve ilişkilerden kaçınmalı, mesleki kararından ödün vermemelidir.", "Etik Yönetmeliği Birinci Kısım m. 8-9", "medium", fc="Tarafsızlığı bozan ortamdan kaçınmak"),
    r("Meslek mensubu güncel teknik gelişmeleri izlemeyi yıllar önce bırakmıştır. Yeterlilik ilkesi bakımından eksiklik nedir?", "Mesleki yeterliliğin korunması hangi sürekli faaliyeti gerektirir?", "Ulusal ve uluslararası gelişmeleri sürekli izlemek", ["Yalnız ilk ruhsat bilgisini kullanmak", "Mesleki eğitimi tamamen bırakmak", "Teknik standartları dikkate almamak", "Yalnız müşterinin bilgisini esas almak"], "Yeterliliğin korunması, mesleki gelişmelerin sürekli izlenmesini ve anlaşılmasını gerektirir.", "Etik Yönetmeliği Birinci Kısım m. 11/1-b", "medium", fc="Mesleki gelişmeleri izlemek"),
    r("Aday mesleğe giriş şartlarını tamamlayarak gerekli bilgi ve beceriyi kazanmıştır. Bu yeterliliğin hangi aşamasıdır?", "Mesleki yeterliliğin iki aşaması hangileridir?", "Mesleki yeterliliğin elde edilmesi", ["Yeterliliğin gizlenmesi", "Yakınlık tehdidinin büyütülmesi", "Yıldırma tehdidinin kabulü", "Mesleki davranıştan vazgeçilmesi"], "Mesleğe giriş şartlarının sağlanması yeterliliğin elde edilmesi aşamasıdır.", "Etik Yönetmeliği Birinci Kısım m. 11/1-a", "easy", fc="Yeterliliğin elde edilmesi ve korunması", fd=["Yeterliliğin saklanması ve bırakılması", "Tehdidin kurulması ve büyütülmesi", "Reklamın yapılması ve yinelenmesi", "Sırrın öğrenilmesi ve açıklanması"]),
    r("SMMM, kendi otoritesi altındaki çalışanları eğitimsiz ve gözetimsiz bırakmıştır. Özen ilkesi bakımından doğru mudur?", "Meslek mensubunun otoritesi altındaki çalışanlara ilişkin özen yükümlülüğü nedir?", "Hayır; uygun eğitim ve gözetim sağlamalıdır", ["Evet; hiçbir sorumluluğu yoktur", "Yalnız ücret ödemesi yeterlidir", "Çalışanların eğitimi yasaktır", "Gözetim yalnız müşteriye aittir"], "Meslek mensubu, otoritesi altındaki çalışanların uygun eğitim almasını ve gözetim altında tutulmasını sağlar.", "Etik Yönetmeliği Birinci Kısım m. 11/3", "medium", fc="Eğitim almalarını ve gözetilmelerini sağlamak"),
    r("Müşteri, mesleki bilginin üçüncü kişiye açıklanmasına geçerli biçimde izin vermemiştir ve yasal görev de yoktur. SMMM açıklayabilir mi?", "Gizli bilginin üçüncü kişiye açıklanabilmesi için hangi temel dayanak aranır?", "Hayır; yetki veya yasal-mesleki görev gerekir", ["Evet; her bilgi serbestçe açıklanır", "Yalnız kişisel çıkar yeterlidir", "Rakibin talebi açıklama için yeterlidir", "Reklam amacı her zaman haklıdır"], "Gizli bilgi ancak yetki, izin veya yasal ya da mesleki açıklama görevi bulunduğunda paylaşılabilir.", "Etik Yönetmeliği Birinci Kısım m. 12 ve 14", "medium", fc="Yetki, izin veya açıklama görevi"),
    r("SMMM müşteri bilgisini kendi yatırım kararında kullanarak kazanç sağlamıştır. Gizlilik ilkesi bakımından sonuç nedir?", "Mesleki ilişkide edinilen gizli bilgi kişisel veya üçüncü kişi çıkarına kullanılabilir mi?", "Gizliliğin ihlalidir", ["Tarafsızlığın zorunlu sonucudur", "Mesleki reklam hakkıdır", "Her durumda serbest kullanımdır", "Yalnız ücret tarifesi konusudur"], "Gizli bilginin kişisel veya üçüncü kişi çıkarı için kullanılması yasaktır.", "Etik Yönetmeliği Birinci Kısım m. 12/b", "easy", fc="Hayır; çıkar için kullanılamaz"),
    r("Müşteriyle sözleşme sona erdikten sonra SMMM sır saklama yükümlülüğünün de bittiğini ileri sürmüştür. Doğru mudur?", "Gizlilik sorumluluğu müşteri veya işveren ilişkisi sona erince ne olur?", "Hayır; gizlilik ilişkiden sonra da sürer", ["Evet; bütün sırlar serbest kalır", "Yalnız bir gün daha sürer", "Sadece ücret ödenirse devam eder", "Yükümlülük müşteriye geçer"], "Gizlilik sorumluluğu müşteri veya işverenle ilişki sona erdikten sonra da devam eder.", "Etik Yönetmeliği Birinci Kısım m. 13", "easy", fc="İlişki sona erse de devam eder"),
    r("Kanuni soruşturma kapsamında yetkili kamu otoritesi mesleki bilgi istemiştir. Gizlilik ilkesi açıklamayı mutlak biçimde engeller mi?", "Yasal süreçte kanıt sağlama veya kanuna aykırılığı yetkili makama bildirme gizlilik bakımından nasıl değerlendirilir?", "Hayır; kanuni açıklama görevi uygulanabilir", ["Evet; hiçbir kanuni istisna yoktur", "Bilgi yalnız rakibe verilebilir", "Açıklama sadece reklam için yapılır", "Yetkili makamın talebi önemsizdir"], "Kanun gereği belge sağlama veya aykırılığı yetkili otoriteye bildirme, gizliliğin izin verdiği açıklama hâllerindendir.", "Etik Yönetmeliği Birinci Kısım m. 14", "hard", fc="Kanuni veya mesleki açıklama kapsamındadır"),
    r("SMMM gizli bilgiyi açıklamadan önce bilginin doğrulanmış olup olmadığını ve kime verileceğini değerlendirmiştir. Doğru yaklaşım mıdır?", "Gizli bilgiyi açıklama kararında hangi unsurlar dikkate alınır?", "Evet; doğruluk, tarafların çıkarı, alıcı ve yöntem değerlendirilir", ["Hayır; hiçbir unsur değerlendirilmez", "Yalnız reklam değeri dikkate alınır", "Sadece ücret tutarı önemlidir", "Bilginin alıcısı hiçbir zaman araştırılmaz"], "Açıklama kararında tarafların çıkarları, bilginin uygun ve doğrulanmış oluşu ile doğru alıcı ve yöntem değerlendirilir.", "Etik Yönetmeliği Birinci Kısım m. 15", "hard", fc="Çıkarlar, doğruluk, alıcı ve açıklama yöntemi"),
    r("Meslek mensubu tanıtımında iş tecrübesini abartmış ve başka SMMM'yi küçültücü karşılaştırma yapmıştır. Etik sonuç nedir?", "Mesleki tanıtımda hangi davranıştan kaçınılmalıdır?", "Mesleki davranış ilkesine aykırıdır", ["Zorunlu etik uygulamadır", "Gizlilik önlemidir", "Tarafsızlığı güçlendiren yöntemdir", "Mesleki yeterlilik belgesidir"], "Tanıtım dürüst olmalı; abartılı iddia, doğrulanmamış karşılaştırma ve küçültücü atıf içermemelidir.", "Etik Yönetmeliği Birinci Kısım m. 16-17", "medium", fc="Abartı ve küçültücü karşılaştırma"),
    r("Yeni müşterinin yasa dışı faaliyet ve tartışmalı raporlama geçmişi vardır. Tehditler kabul edilebilir düzeye indirilemiyorsa ne yapılmalıdır?", "Yeni müşteri kabulünde önemli etik tehdit giderilemiyorsa temel sonuç nedir?", "Müşteri kabul edilmemelidir", ["Müşteri koşulsuz kabul edilmelidir", "Tehditler dosyadan silinmelidir", "Yasa dışı faaliyet görmezden gelinmelidir", "Yalnız ücret artırılmalıdır"], "Müşteri kabulünden önce etik tehdit araştırılır; kabul edilebilir düzeye indirilemeyen tehdit varsa müşteri reddedilir.", "Etik Yönetmeliği İkinci Kısım m. 33", "hard"),
    r("Başka meslek mensubunun yerine geçmesi istenen SMMM, mevcut meslek mensubuyla iletişim kurmadan işi almıştır. Etik açıdan eksiklik nedir?", "Mesleki atama değişikliğinde mevcut meslek mensubuyla iletişimin amacı nedir?", "Değişime ilişkin gerçekleri ve tehditleri öğrenmek", ["Müşterinin sırlarını yayımlamak", "Rakibi küçültücü reklam yapmak", "Ücret tarifesini ortadan kaldırmak", "Hizmeti kanıtsız kabul etmek"], "Mevcut meslek mensubuyla, müşterinin izni veya yasal dayanak çerçevesinde iletişim kurularak değişimin gerçekleri ve tehditleri değerlendirilir.", "Etik Yönetmeliği İkinci Kısım m. 35", "hard", fc="İş kabulünün uygunluğunu değerlendirmek"),
    r("SMMM çıkar çatışması içindeki iki müşteriye hizmet verirken taraflara bilgi verip onaylarını almış ve ayrı ekipler kurmuştur. Bunlar ne niteliğindedir?", "Çıkar çatışmasında bilgi verme, onay alma ve ayrı ekip kullanma ne sağlar?", "Etik tehdidi azaltan önlemlerdir", ["Gizliliği kaldıran sınırsız izinlerdir", "Meslek unvanını sona erdiren işlemlerdir", "Çatışmayı artıran reklam yöntemleridir", "Sözleşmeyi kendiliğinden hükümsüz kılar"], "Bilgilendirme-onay, ayrı ekipler ve bilgi engelleri çıkar çatışması tehditlerini azaltan önlemlerdir.", "Etik Yönetmeliği İkinci Kısım m. 36-38", "hard"),
]


PREMISES = [
    {"stem":"Temel etik ilkeler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dürüstlük doğru ve güvenilir davranmayı gerektirir\n\nII. Tarafsızlık uygunsuz baskıya karşı mesleki kararı korur\n\nIII. Mesleki davranış mesleğin itibarını gözetir","correct":"I, II ve III","why":"Üç ifade de zorunlu temel etik ilkelerin kapsamını doğru açıklar.","ref":"Etik Yönetmeliği Birinci Kısım m. 1","difficulty":"easy"},
    {"stem":"Etik tehditler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Finansal çıkar kişisel çıkar tehdidi doğurabilir\n\nII. Kendi kararını yeniden inceleme yeniden değerlendirme tehdididir\n\nIII. Yakın ilişki her durumda tarafsızlığı güçlendirir","correct":"I ve II","why":"Finansal çıkar ve kendi kararını inceleme ilgili tehditleri doğurur; yakınlık tarafsızlığı tehdit edebilir.","ref":"Etik Yönetmeliği Birinci Kısım m. 3","difficulty":"medium"},
    {"stem":"Kavramsal çerçeve bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tehditler belirlenir ve değerlendirilir\n\nII. Önemli tehdit için uygun önlem alınır\n\nIII. Tehdit giderilemiyorsa işe her koşulda devam edilir","correct":"I ve II","why":"Tehdit belirlenip değerlendirilir ve önlem alınır; giderilemiyorsa hizmet azaltılabilir veya sona erdirilebilir.","ref":"Etik Yönetmeliği Birinci Kısım m. 2-4","difficulty":"medium"},
    {"stem":"Mesleki yeterlilik ve özen bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yeterlilik yalnız ruhsat tarihinde önemlidir\n\nII. Mesleki gelişmeler sürekli izlenir\n\nIII. Otorite altındaki çalışanlar eğitilir ve gözetilir","correct":"II ve III","why":"Yeterlilik korunmalı, gelişmeler izlenmeli ve çalışanlar eğitilip gözetilmelidir.","ref":"Etik Yönetmeliği Birinci Kısım m. 10-11","difficulty":"medium"},
    {"stem":"Gizlilik ilkesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gizli bilgi kişisel çıkar için kullanılamaz\n\nII. İlişki sona erince gizlilik devam eder\n\nIII. Kanuni açıklama görevi hiçbir zaman uygulanamaz","correct":"I ve II","why":"Gizli bilgi çıkar için kullanılamaz ve yükümlülük sürer; kanuni açıklama hâlleri mümkündür.","ref":"Etik Yönetmeliği Birinci Kısım m. 12-14","difficulty":"medium"},
    {"stem":"Mesleki davranış bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mevzuata uyulur\n\nII. Mesleğin itibarı korunur\n\nIII. Tanıtımda abartılı ve küçültücü iddialardan kaçınılır","correct":"I, II ve III","why":"Üç davranış da mesleki davranış ilkesinin gereğidir.","ref":"Etik Yönetmeliği Birinci Kısım m. 16-17","difficulty":"easy"},
    {"stem":"Müşteri kabulü ve atama değişikliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yeni müşterinin etik tehditleri araştırılır\n\nII. Mevcut meslek mensubuyla uygun iletişim kurulabilir\n\nIII. Giderilemeyen önemli tehditler görmezden gelinir","correct":"I ve II","why":"Kabulden önce araştırma ve uygun iletişim gerekir; önemli tehdit giderilemiyorsa iş kabul edilmez.","ref":"Etik Yönetmeliği İkinci Kısım m. 33-35","difficulty":"hard"},
    {"stem":"Çıkar çatışması önlemleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İlgili taraflardan durum gizlenir\n\nII. Tarafların onayı alınabilir\n\nIII. Farklı sözleşme ekipleri kullanılabilir","correct":"II ve III","why":"Çatışma gizlenmez; bilgilendirme ve onay ile ayrı ekipler uygun önlemlerdir.","ref":"Etik Yönetmeliği İkinci Kısım m. 36-38","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(lesson_id="meslek_hukuku", topic_id="mesleki_etik",
                label="Mesleki Etik", slug="mesleki_etik",
                prefix="topic-mh-me", seed=170743,
                legislation_version="Mesleki Etik İlkeler Yönetmeliği, 17.07.2026 yürürlük durumu",
                rules=RULES, premises=PREMISES, wrong_banks={})
