#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Finansal Tablolar ve Analizi — Dikey Analiz, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario,
        "focus": focus,
        "correct": correct,
        "focus_correct": focus_correct,
        "distractors": distractors,
        "focus_distractors": focus_distractors,
        "why": why,
        "focus_why": focus_why,
        "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Analist, tek döneme ait bilançodaki her kalemi toplam varlığa oranlayarak ortak büyüklükte yüzdeler elde etmektedir. Hangi teknik uygulanmaktadır?",
        "Dikey analizin temel inceleme konusu aşağıdakilerden hangisidir?",
        "Dikey yani yüzde yöntemiyle analiz",
        "Bir tablodaki kalemlerin seçilen bütün içindeki yapısal payı",
        ["Karşılaştırmalı tabloların dönemsel değişim analizi", "Trend yüzdeleri yöntemi", "Finansal oran analizi", "Nakit akışlarının zaman analizi"],
        ["Aynı kalemin iki dönem arasındaki tutar ve yüzde değişim hızı", "Baz yıla göre uzun dönemli endeks seyri", "Birbiriyle ilişkili iki kalemin bölümü", "Gelecek dönemin bütçelenmiş nakit dengesi"],
        "Kalemlerin aynı tablodaki bir bütüne oranlanması dikey analizdir; bu tablolar ortak büyüklüklü tablolar olarak da adlandırılır.",
        "Dikey analiz, dönemler arası tutar değişiminden önce tek tablonun bileşimini görünür kılar.",
        "Finansal tablo analizi - dikey analiz", "easy",
    ),
    r(
        "Bir işletmenin varlık yapısı yalnız 2026 bilançosu üzerinden yüzde dağılımıyla incelenmiştir. Bu çalışma zaman boyutu bakımından nasıl sınıflandırılır?",
        "Tek dönemin iç yapısını esas alan dikey analiz hangi analiz türüne örnektir?",
        "Statik analiz",
        "Statik analizdir",
        ["Dinamik analiz", "Trend analizi", "Fon akım analizi", "Karşılaştırmalı analiz"],
        ["Birden çok dönemi zorunlu kılan dinamik analizdir", "Yalnız baz yıl seçilince trend analizidir", "Her durumda oran analizine dönüşür", "Nakit girişlerini izleyen akım analizidir"],
        "Tek dönem verisiyle mali yapının bileşimini ölçmek statik analiz niteliğindedir.",
        "Dikey yüzdeler farklı dönemlerde ayrıca karşılaştırılabilir; ancak tek dönem uygulamasının kendisi statiktir.",
        "Finansal tablo analizi - statik ve dinamik analiz", "easy",
    ),
    r(
        "Bilançoda kasa kaleminin dikey yüzdesi hesaplanacaktır. Genel toplam yaklaşımında payda hangi büyüklüktür?",
        "Bilançoda genel toplam üzerinden dikey analiz yapılırken yüzde yüz kabul edilen büyüklük hangisidir?",
        "Toplam varlık tutarı",
        "Toplam varlık veya ona eşit toplam kaynak tutarı",
        ["Net satışlar", "Dönemin vergi sonrası net kâr tutarı", "Dönen varlıklar", "Özkaynaklar"],
        ["Net satışlar ile brüt kâr toplamı", "Yalnız özkaynakların toplamı", "Dönen ve duran varlıkların dönem sonu aritmetik ortalaması", "Dönem kârından verginin düşülmüş tutarı"],
        "Bilançonun genel dikey analizinde her varlık kalemi toplam varlığa oranlanır.",
        "Bilanço eşitliği nedeniyle toplam varlık ve toplam kaynak aynı genel toplamı ifade eder ve %100'dür.",
        "Finansal tablo analizi - bilanço dikey yüzdesi", "easy",
    ),
    r(
        "Gelir tablosunda satışların maliyetinin dikey yüzdesi hesaplanacaktır. Payda hangi kalemdir?",
        "Gelir tablosu ortak büyüklüklü biçime çevrilirken kural olarak %100 kabul edilen tutar nedir?",
        "Net satışlar",
        "Net satışlar tutarıdır",
        ["Toplam varlıklar", "Brüt satış kârı", "Faaliyet kârı", "Dönem net kârı"],
        ["Satışların maliyeti tutarıdır", "Brüt satışların iadeler düşülmemiş tutarıdır", "Toplam kaynaklar tutarıdır", "Dönem kârı ve vergi gideri toplamıdır"],
        "Gelir tablosu kalemleri, faaliyet hacmini temsil eden net satışlara oranlanır.",
        "Net satışların dikey yüzdesi %100 kabul edilir; gider ve kâr kalemleri bu baza göre gösterilir.",
        "Finansal tablo analizi - gelir tablosu dikey yüzdesi", "easy",
    ),
    r(
        "Analist stokların hem toplam varlık içindeki hem de dönen varlık grubu içindeki payını raporlamıştır. Bu iki yüzdenin farklı olması hata mıdır?",
        "Grup toplamına göre hesaplanan dikey yüzde yorumlanırken hangi bilgi mutlaka belirtilmelidir?",
        "Hayır; iki oran farklı bazlara dayanan ayrı yapı bilgileri verir",
        "Paydanın grup toplamı mı genel toplam mı olduğu",
        ["Evet; her finansal tabloda bütün kalemler yalnız genel toplam tutarına oranlanmalıdır", "Evet; stoklar yalnız net satışlara oranlanabilir", "Hayır; iki sonuç doğrudan toplanarak kullanılır", "Evet; grup toplamı hiçbir analizde baz olamaz"],
        ["İlgili kalemin önceki döneme göre mutlak ve yüzde değişimi", "Baz yılın trend endeksi", "Soruya ait cevap anahtarı", "Gelecek dönemin satış tahmini"],
        "Genel toplam yüzdesi yapının bütündeki, grup yüzdesi ise ilgili alt gruptaki ağırlığını gösterir.",
        "Payda açıklanmazsa aynı kaleme ait farklı yüzdelerin ekonomik anlamı karışır.",
        "Finansal tablo analizi - grup ve genel toplam yüzdeleri", "medium",
    ),
    r(
        "Büyüklükleri çok farklı iki işletmenin bilanço kalemleri dikey yüzdelere çevrilerek karşılaştırılmıştır. Bu yaklaşımın başlıca yararı nedir?",
        "Ortak büyüklüklü tablolar işletmeler arası karşılaştırmayı hangi yolla kolaylaştırır?",
        "Ölçek farkını azaltarak finansal yapıların kıyaslanabilmesi",
        "Yapısal ağırlıkları ortak yüzde tabanında göstermesi",
        ["Her iki işletmenin bütün finansal tablo tutarlarını aynı nominal değere eşitlemesi", "Gelecek dönem kârını kesin olarak hesaplaması", "Muhasebe politikası farklarını kendiliğinden yok etmesi", "Nakit yaratmayan işlemleri tablodan çıkarması"],
        ["Bütün kalemleri aynı parasal tutara dönüştürmesi", "Ekonomik koşul farklarını tamamen ortadan kaldırması", "Kredi riskini tek başına ölçmesi", "Her işletmenin net kârını %100 kabul etmesi"],
        "Yüzdeler ölçeği standardize eder; böylece farklı büyüklükteki işletmelerin varlık, kaynak ve sonuç yapıları kıyaslanabilir.",
        "Standardizasyon yapısal karşılaştırmayı kolaylaştırır, fakat işletmelerin ekonomik koşullarını eşitlemez.",
        "Finansal tablo analizi - ortak büyüklüklü tablolar", "medium",
    ),
    r(
        "Stokların toplam varlık payı %18'den %31'e çıkmıştır. Analist yalnız bu artıştan işletmenin kesin olarak daha kârlı olduğu sonucunu çıkarmıştır. Değerlendirme doğru mudur?",
        "Bir dikey yüzde değişiminin sağlıklı yorumlanması için aşağıdakilerden hangisi gerekir?",
        "Hayır; neden, sektör ve ilişkili kalemler birlikte incelenmelidir",
        "Tutar, dönem koşulları ve ilişkili kalemlerle birlikte yorumlama",
        ["Evet; stok payındaki her artış, diğer koşullardan bağımsız olarak kesin bir kârlılık artışı gösterir", "Hayır; stoklar dikey analizde gösterilemez", "Evet; yüzde değişimi tek başına nakit artışını kanıtlar", "Hayır; dikey yüzdeler yalnız vergi amacıyla kullanılır"],
        ["Yalnız en yüksek yüzdeye sahip kalemi olumlu sonuç sayarak diğer verileri incelememe", "Bütün işletmeler için tek ideal yüzde belirleme", "Kalemlerin parasal tutarlarını göz ardı etme", "Payda değişse bile aynı sonucu kabul etme"],
        "Yüksek stok payı büyüme hazırlığı da, yavaş devir veya değer düşüklüğü riski de gösterebilir; tek başına hüküm kurdurmaz.",
        "Dikey analiz yapıyı gösterir; neden ve performans yorumu ek kanıtlarla desteklenmelidir.",
        "Finansal tablo analizi - dikey yüzde yorumu", "hard",
    ),
    r(
        "İki işletmenin dikey yüzdeleri karşılaştırılmış, ancak biri kiraladığı varlıkları farklı muhasebe politikasıyla sınıflandırmıştır. Yüzdeler tek başına yeterli midir?",
        "Dikey analiz, muhasebe politikası ve sınıflama farkları bakımından hangi sınıra sahiptir?",
        "Hayır; karşılaştırılabilirlik farkları ayrıca incelenmelidir",
        "Yüzdeler temel muhasebe farklılıklarını gidermez",
        ["Evet; yüzdeler bütün politika farklarını otomatik düzeltir", "Hayır; dikey analiz yalnız aynı işletmeye uygulanabilir", "Evet; sınıflama farkları yalnız nakit tablosunu etkiler", "Hayır; karşılaştırmada bütün kalemler sıfırlanmalıdır"],
        ["Yüzdeler her türlü ölçüm farkını ortadan kaldırır", "Politika farkları yalnız önceki dönem tutarına eklenir", "Farklı sınıflamalar finansal yapıyı etkilemez", "Her karşılaştırmada net satışlar toplam varlığa eşitlenir"],
        "Ortak yüzde tabanı ölçek sorununu azaltır; ölçüm ve sınıflama farklılıklarını ortadan kaldırmaz.",
        "Karşılaştırmanın anlamlı olması için politika, kapsam ve sınıflama temelleri uyumlu olmalıdır.",
        "TMS 1 karşılaştırılabilirlik; finansal tablo analizi", "hard",
    ),
    r(
        "Gelir tablosunda faaliyet zararı net satışlara oranlanmıştır. Elde edilen yüzde negatif çıkmıştır. Bu sonuç nasıl ele alınır?",
        "Dikey analizde negatif bir gider, zarar veya indirim kalemi için doğru yaklaşım hangisidir?",
        "İşaret korunarak negatif dikey yüzde raporlanır",
        "Kalemin ekonomik yönünü gösteren işareti korunur",
        ["Sonuç her durumda pozitif değere çevrilir", "Kalem analiz dışında bırakılır", "Payda dönem net zararı yapılır", "Yüzde zorunlu olarak sıfır yazılır"],
        ["Mutlak değer alınarak işaret bilgisi gizlenir", "Kalem net satışlarla toplanıp yeniden hesaplanır", "Negatif kalem otomatik olarak özkaynağa aktarılır", "Yalnız önceki dönem yüzdesi kullanılır"],
        "Negatif sonuç ekonomik niteliğin parçasıdır; mutlak değere çevirmek tablonun anlamını bozar.",
        "Dikey yüzdede işaret, kalemin bütüne katkı yönünü veya azalış niteliğini gösterir.",
        "Finansal tablo analizi - işaretli dikey yüzdeler", "medium",
    ),
    r(
        "Bir kalemin 2025 ve 2026 dikey yüzdeleri arasındaki fark hesaplanmıştır. Bu fark neyi gösterir?",
        "Dikey yüzde iki dönem için ayrı ayrı hesaplandıktan sonra yüzdelerin karşılaştırılması hangi bilgiyi sağlar?",
        "Yapısal ağırlığın değişimini, yüzde puan olarak",
        "Yapısal payın zaman içindeki yönünü ve büyüklüğünü",
        ["Kalemin parasal tutarındaki dönemsel yüzde değişimini", "Baz yıl trend endeksini", "Kalemin devir hızını", "Nakit akışının bugünkü değerini"],
        ["Tutarın önceki döneme göre mutlak ve yüzdesel değişimini gösterir", "İki kalemin birbirine oranını", "Gelecek dönemin kesin bakiyesini", "Yalnız fiyat düzeyindeki değişimi"],
        "İki dikey yüzdenin farkı yüzde puandır; tutar artış oranıyla aynı kavram değildir.",
        "Ayrı dönemlerin ortak büyüklüklü tabloları, bileşimin dönem içinde nasıl değiştiğini gösterir.",
        "Finansal tablo analizi - dikey yüzde karşılaştırması", "medium",
    ),
]


CALCS = [
    r(
        "Toplam varlıkları 2.400 bin TL olan işletmenin dönen varlıkları 960 bin TL'dir. Dönen varlıkların dikey yüzdesi kaçtır?",
        "Dönen varlıkların toplam varlık içindeki payı %40 ve tutarı 960 bin TL ise toplam varlık kaç bin TL'dir?",
        "%40", "2.400 bin TL",
        ["%25", "%60", "%96", "%140"], ["384 bin TL", "1.440 bin TL", "3.360 bin TL", "4.800 bin TL"],
        "Dönen varlık payı 960 / 2.400 × 100 = %40'tır.",
        "Toplam varlık 960 / 0,40 = 2.400 bin TL olarak bulunur.",
        "Finansal tablo analizi - bilanço dikey yüzdesi", "easy",
    ),
    r(
        "Stoklar 360 bin TL, toplam varlıklar 1.800 bin TL'dir. Stokların genel toplam içindeki payı kaçtır?",
        "Toplam varlıkları 1.800 bin TL olan işletmede stokların dikey yüzdesi %20 ise stok tutarı kaç bin TL'dir?",
        "%20", "360 bin TL",
        ["%5", "%18", "%80", "%500"], ["90 bin TL", "180 bin TL", "900 bin TL", "3.600 bin TL"],
        "Stokların dikey yüzdesi 360 / 1.800 × 100 = %20'dir.",
        "Stok tutarı 1.800 × 0,20 = 360 bin TL'dir.",
        "Finansal tablo analizi - varlık yapısı", "easy",
    ),
    r(
        "Toplam varlık 1.500 bin TL, nakit ve nakit benzerleri 225 bin TL'dir. Nakit payı yüzde kaçtır?",
        "Nakit payı %15, toplam varlık 1.500 bin TL ve stoklar 300 bin TL ise nakit ile stokların toplam varlık içindeki birleşik payı kaçtır?",
        "%15", "%35",
        ["%6,67", "%22,5", "%85", "%150"], ["%15", "%20", "%30", "%45"],
        "Nakit payı 225 / 1.500 × 100 = %15'tir.",
        "Nakit 225 bin TL, stok 300 bin TL'dir; toplam 525 / 1.500 = %35 paya sahiptir.",
        "Finansal tablo analizi - varlık bileşimi", "medium",
    ),
    r(
        "Toplam kaynakları 3.000 bin TL olan işletmenin toplam yabancı kaynakları 1.950 bin TL'dir. Yabancı kaynak payı kaçtır?",
        "Toplam kaynakların %65'i yabancı kaynak ise özkaynak payı yüzde kaçtır?",
        "%65", "%35",
        ["%35", "%53,85", "%95", "%153,85"], ["%25", "%45", "%65", "%165"],
        "Yabancı kaynak payı 1.950 / 3.000 × 100 = %65'tir.",
        "Kaynaklar toplamı %100 olduğundan özkaynak payı %100 − %65 = %35'tir.",
        "Finansal tablo analizi - kaynak yapısı", "easy",
    ),
    r(
        "Özkaynaklar 840 bin TL, toplam kaynaklar 2.400 bin TL'dir. Özkaynakların dikey yüzdesi kaçtır?",
        "Özkaynak payı %35 ve toplam kaynak 2.400 bin TL ise yabancı kaynak tutarı kaç bin TL'dir?",
        "%35", "1.560 bin TL",
        ["%28,57", "%65", "%84", "%285,71"], ["840 bin TL", "1.200 bin TL", "2.040 bin TL", "3.240 bin TL"],
        "Özkaynak payı 840 / 2.400 × 100 = %35'tir.",
        "Yabancı kaynak payı %65, tutarı 2.400 × 0,65 = 1.560 bin TL'dir.",
        "Finansal tablo analizi - özkaynak payı", "medium",
    ),
    r(
        "Net satışlar 5.000 bin TL, satışların maliyeti 3.200 bin TL'dir. Satışların maliyetinin dikey yüzdesi kaçtır?",
        "Satışların maliyeti net satışların %64'ü ve net satışlar 5.000 bin TL ise brüt kâr kaç bin TL'dir?",
        "%64", "1.800 bin TL",
        ["%36", "%56,25", "%68", "%156,25"], ["1.200 bin TL", "2.800 bin TL", "3.200 bin TL", "8.200 bin TL"],
        "Satışların maliyeti payı 3.200 / 5.000 × 100 = %64'tür.",
        "Brüt kâr marjı %36'dır; 5.000 × 0,36 = 1.800 bin TL brüt kâr bulunur.",
        "Finansal tablo analizi - gelir tablosu dikey analizi", "medium",
    ),
    r(
        "Net satışları 4.000 bin TL olan işletmede faaliyet giderleri 720 bin TL'dir. Giderlerin net satışlara oranı kaçtır?",
        "Brüt kâr marjı %38, faaliyet giderlerinin satışlara oranı %18 ise diğer gelir ve giderler yokken faaliyet kâr marjı kaçtır?",
        "%18", "%20",
        ["%5,56", "%22", "%72", "%180"], ["%18", "%38", "%56", "%211,11"],
        "Faaliyet gideri dikey yüzdesi 720 / 4.000 × 100 = %18'dir.",
        "Faaliyet kâr marjı %38 − %18 = %20'dir.",
        "Finansal tablo analizi - faaliyet giderleri", "medium",
    ),
    r(
        "Net dönem kârı 450 bin TL, net satışlar 6.000 bin TL'dir. Net kârın dikey yüzdesi kaçtır?",
        "Net kârın satışlara oranı %7,5 ve net satışlar 6.000 bin TL ise net dönem kârı kaç bin TL'dir?",
        "%7,5", "450 bin TL",
        ["%6,67", "%13,33", "%75", "%133,33"], ["45 bin TL", "80 bin TL", "800 bin TL", "4.500 bin TL"],
        "Net kâr payı 450 / 6.000 × 100 = %7,5'tir.",
        "Net dönem kârı 6.000 × 0,075 = 450 bin TL'dir.",
        "Finansal tablo analizi - net kâr marjı", "easy",
    ),
    r(
        "Ticari alacaklar 630 bin TL, dönen varlıklar 1.800 bin TL ve toplam varlıklar 3.500 bin TL'dir. Alacakların dönen varlık grubu içindeki payı kaçtır?",
        "Ticari alacakların dönen varlık grubu içindeki payı %35, genel toplam içindeki payı %18 ise dönen varlıkların toplam varlık payı yaklaşık kaçtır?",
        "%35", "%51,43",
        ["%18", "%28,57", "%50", "%194,44"], ["%6,3", "%35", "%53", "%194,44"],
        "Grup yüzdesi 630 / 1.800 × 100 = %35'tir.",
        "Alacak tutarı her iki payın payıdır; dönen varlık payı %18 / %35 = yaklaşık %51,43'tür.",
        "Finansal tablo analizi - grup yüzdesi", "hard",
    ),
    r(
        "Maddi duran varlıklar 1.620 bin TL, toplam varlıklar 2.700 bin TL'dir. Maddi duran varlıkların payı kaçtır?",
        "Maddi duran varlık payı %60 olan 2.700 bin TL toplam varlıklı işletmede diğer varlıkların tutarı kaç bin TL'dir?",
        "%60", "1.080 bin TL",
        ["%40", "%62,5", "%162", "%166,67"], ["720 bin TL", "1.620 bin TL", "2.100 bin TL", "4.320 bin TL"],
        "Maddi duran varlık payı 1.620 / 2.700 × 100 = %60'tır.",
        "Diğer varlık payı %40 olduğundan tutar 2.700 × 0,40 = 1.080 bin TL'dir.",
        "Finansal tablo analizi - duran varlık yapısı", "medium",
    ),
    r(
        "Kısa vadeli yabancı kaynaklar 900 bin TL, toplam kaynaklar 2.500 bin TL'dir. Kısa vadeli borç payı kaçtır?",
        "Kısa vadeli borç payı %36, uzun vadeli borç payı %24 olan işletmede özkaynak payı yüzde kaçtır?",
        "%36", "%40",
        ["%27,78", "%64", "%90", "%277,78"], ["%24", "%36", "%60", "%76"],
        "Kısa vadeli borçların dikey yüzdesi 900 / 2.500 × 100 = %36'dır.",
        "Toplam borç payı %60 olduğuna göre kalan %40 özkaynak payıdır.",
        "Finansal tablo analizi - kaynakların vade yapısı", "medium",
    ),
    r(
        "Net satışlar 8.000 bin TL, brüt kâr 2.800 bin TL'dir. Brüt kârın dikey yüzdesi kaçtır?",
        "Brüt kâr marjı %35 ise satışların maliyetinin net satışlara oranı kaçtır?",
        "%35", "%65",
        ["%28,57", "%53,85", "%65", "%285,71"], ["%35", "%53,85", "%135", "%185,71"],
        "Brüt kârın dikey yüzdesi 2.800 / 8.000 × 100 = %35'tir.",
        "Net satışlar %100 olduğundan satışların maliyeti payı %100 − %35 = %65'tir.",
        "Finansal tablo analizi - brüt kâr yapısı", "easy",
    ),
    r(
        "Net satışlar 10.000 bin TL, faaliyet kârı 1.400 bin TL'dir. Faaliyet kârının dikey yüzdesi kaçtır?",
        "Faaliyet kâr marjı %14, finansman gideri payı %5 ve başka sonuç kalemi yoksa vergi öncesi kâr marjı kaçtır?",
        "%14", "%9",
        ["%7,14", "%10", "%86", "%140"], ["%5", "%14", "%19", "%71,43"],
        "Faaliyet kâr payı 1.400 / 10.000 × 100 = %14'tür.",
        "Finansman gideri faaliyet sonucundan düşüldüğünde vergi öncesi kâr marjı %14 − %5 = %9'dur.",
        "Finansal tablo analizi - faaliyet sonucu", "medium",
    ),
    r(
        "A işletmesinde stok 400 bin TL ve toplam varlık 2.000 bin TL; B işletmesinde stok 600 bin TL ve toplam varlık 4.000 bin TL'dir. Hangi işletmenin stok payı daha yüksektir?",
        "A işletmesinin stok payı %20, B işletmesinin %15'tir. B'nin toplam varlığı 4.000 bin TL olduğuna göre stok tutarı A'nın 400 bin TL stokundan kaç bin TL fazladır?",
        "A işletmesinin; stok payı %20'dir", "200 bin TL",
        ["B işletmesinin; stok payı %30'dur", "B işletmesinin; stok payı %15'tir", "İki işletmenin de stok payı %20'dir", "Tutarlar farklı olduğu için oran hesaplanamaz"], ["100 bin TL", "400 bin TL", "600 bin TL", "1.000 bin TL"],
        "A'nın stok payı %20, B'nin %15'tir; mutlak stok tutarı yüksek olsa da B'nin yapısal payı daha düşüktür.",
        "B'nin stoku 4.000 × 0,15 = 600 bin TL'dir; A'dan 200 bin TL fazladır.",
        "Finansal tablo analizi - işletmeler arası dikey analiz", "hard",
    ),
    r(
        "Toplam varlıklar 5.000 bin TL, dönen varlıklar 2.000 bin TL ve stoklar 500 bin TL'dir. Stokların hem toplam varlık hem dönen varlık içindeki payları sırasıyla kaçtır?",
        "Stokların dönen varlık içindeki payı %25, toplam varlık içindeki payı %10 ise dönen varlıkların toplam varlık içindeki payı kaçtır?",
        "%10 ve %25", "%40",
        ["%25 ve %10", "%10 ve %40", "%25 ve %40", "%40 ve %25"], ["%2,5", "%15", "%25", "%250"],
        "Stokların genel payı 500 / 5.000 = %10, grup payı 500 / 2.000 = %25'tir.",
        "Stok paylarının oranı %10 / %25 = %40 olup dönen varlıkların genel toplam payını verir.",
        "Finansal tablo analizi - genel ve grup toplamı", "hard",
    ),
    r(
        "Ticari alacakların toplam varlık payı 2025'te %12, 2026'da %17 olmuştur. Yapısal değişim kaç yüzde puandır?",
        "Alacak payı 5 yüzde puan artarak %17'ye çıkmış ve 2026 toplam varlıkları 4.000 bin TL olmuştur. 2026 ticari alacak tutarı kaç bin TL'dir?",
        "5 yüzde puan artış", "680 bin TL",
        ["%5 oranında azalış", "%29,41 oranında artış", "12 yüzde puan artış", "17 yüzde puan artış"], ["200 bin TL", "480 bin TL", "588 bin TL", "800 bin TL"],
        "Yapısal paydaki değişim %17 − %12 = 5 yüzde puandır; bu ifade yüzde değişim oranından farklıdır.",
        "2026 alacak tutarı 4.000 × 0,17 = 680 bin TL'dir.",
        "Finansal tablo analizi - yapısal pay değişimi", "hard",
    ),
]

RULES.extend(CALCS)


PREMISES = [
    {"stem":"Dikey analiz tekniği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kalemlerin aynı tablodaki bir bütüne oranını gösterir\n\nII. Ortak büyüklüklü tablo üretir\n\nIII. Tek dönem için uygulanabilir","correct":"I, II ve III","why":"Dikey analiz üç özelliği de taşır: yapısal payları ortak bir yüzde tabanında gösterir ve tek döneme uygulanabilir.","ref":"Finansal tablo analizi - dikey analiz","difficulty":"easy"},
    {"stem":"Dikey analiz bazları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bilançoda genel toplam olarak toplam varlık kullanılır\n\nII. Gelir tablosunda net satışlar kullanılır\n\nIII. Baz kabul edilen tutar %100'dür","correct":"I, II ve III","why":"Bilanço ve gelir tablosu için belirtilen bazlar %100 kabul edilir; ilgili kalemler bu tutara oranlanır.","ref":"Finansal tablo analizi - dikey analiz bazları","difficulty":"easy"},
    {"stem":"Dikey yüzde yorumu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yüzde tek başına kârlılığın nedenini kanıtlamaz\n\nII. İlişkili kalemlerle birlikte değerlendirme yapılır\n\nIII. En yüksek pay her durumda en olumlu sonucu gösterir","correct":"I ve II","why":"Yapısal payın anlamı ilişkili veriler ve koşullarla kurulur; yüksek payın her durumda olumlu sayılması mümkün değildir.","ref":"Finansal tablo analizi - yorum","difficulty":"medium"},
    {"stem":"Ortak büyüklüklü tablolar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Her işletmenin mutlak tutarını eşitler\n\nII. Ölçek farkının karşılaştırmaya etkisini azaltır\n\nIII. Finansal yapıların karşılaştırılmasını kolaylaştırır","correct":"II ve III","why":"Yüzdeler yapısal kıyası kolaylaştırır, ancak işletmelerin gerçek tutarlarını eşitlemez.","ref":"Finansal tablo analizi - ortak büyüklüklü tablolar","difficulty":"medium"},
    {"stem":"Grup yüzdeleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kalem ilgili grup toplamına oranlanabilir\n\nII. Kullanılan paydanın açıklanmasına gerek yoktur\n\nIII. Grup yüzdesi genel toplam yüzdesinden farklı bir yapı bilgisi verir","correct":"I ve III","why":"Grup ve genel toplam yüzdeleri farklı paydalar kullanır; bu nedenle bazın açıklanması gerekir ve II yanlıştır.","ref":"Finansal tablo analizi - grup yüzdeleri","difficulty":"medium"},
    {"stem":"Dikey analizin sınırlılıkları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yüzdeye çevirme muhasebe politikası farklarını yok eder\n\nII. Sektör koşulları yorumda dikkate alınmalıdır\n\nIII. Sınıflama farklılıkları karşılaştırmayı etkileyebilir","correct":"II ve III","why":"Politika ve sınıflama farkları yüzdelerle kendiliğinden giderilmez; sektör bağlamı da yoruma dahildir.","ref":"TMS 1 karşılaştırılabilirlik; finansal tablo analizi","difficulty":"hard"},
    {"stem":"Dikey yüzde hesapları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kalem tutarı baz toplama bölünür\n\nII. Negatif kalemin işareti korunur\n\nIII. Bilançoda her kalem net satışlara oranlanır","correct":"I ve II","why":"Formül kalem/baz toplamdır ve ekonomik işaret korunur; bilançonun genel bazı net satışlar değil toplam varlıktır.","ref":"Finansal tablo analizi - dikey yüzde hesabı","difficulty":"medium"},
    {"stem":"Dönemler arası dikey yüzde karşılaştırması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İki dikey yüzdenin farkı yüzde puanla ifade edilebilir\n\nII. Yüzde puan farkı tutarın yüzde değişimiyle her zaman aynıdır\n\nIII. Karşılaştırma finansal yapıdaki ağırlık değişimini gösterir","correct":"I ve III","why":"Dikey pay farkı yapısal ağırlık değişimidir; tutarın önceki döneme göre değişim oranıyla aynı değildir.","ref":"Finansal tablo analizi - yapısal pay değişimi","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="mali_tablolar_analizi",
        topic_id="dikey_analiz",
        label="Dikey Analiz",
        slug="dikey_analiz",
        prefix="topic-dya",
        seed=2026071744,
        legislation_version="SMMM Finansal Tablolar ve Analizi müfredatı; dikey (yüzde) analiz (17.07.2026 kontrolü)",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
