#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Gelir Unsurları, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Bir gerçek kişi yıl içinde ticari kazanç, ücret ve mevduat faizi elde etmiştir. Bu gelirlerin GVK'daki ortak özelliği hangisidir?",
        "GVK'ya göre gelire giren kazanç ve iratlar kaç ana unsurda toplanır?",
        "Kanunda sayılan gelir unsurları olmaları",
        "Yedi gelir unsurunda",
        ["Tamamının ücret sayılması", "Yalnız servet transferi olmaları", "Kurum kazancı niteliği taşımaları", "Vergi dışı tahsilat sayılmaları"],
        ["Üç gelir unsurunda", "Dört gelir unsurunda", "Beş gelir unsurunda", "Dokuz gelir unsurunda"],
        "Ticari kazanç, ücret ve menkul sermaye iradı GVK m. 2'de sayılan yedi gelir unsurundandır.",
        "GVK m. 2, gelire giren kazanç ve iratları yedi unsur hâlinde sayar.",
        "193 sayılı GVK m. 2",
        "easy",
    ),
    r(
        "Bir gerçek kişi sürekli biçimde mal alıp satmakta ve bu faaliyetten kazanç sağlamaktadır. Gelir unsuru hangisidir?",
        "Her türlü ticari ve sınai faaliyetten doğan kazanç GVK'da nasıl adlandırılır?",
        "Ticari kazanç",
        "Ticari kazanç",
        ["Zirai kazanç", "Serbest meslek kazancı", "Gayrimenkul sermaye iradı", "Arızi kazanç"],
        ["Ücret", "Menkul sermaye iradı", "Zirai kazanç", "Değer artışı kazancı"],
        "Devamlılık gösteren mal alım satımı ticari faaliyet niteliğindedir ve kazancı ticari kazançtır.",
        "GVK, her türlü ticari ve sınai faaliyetten doğan kazancı ticari kazanç sayar.",
        "193 sayılı GVK m. 37",
        "easy",
    ),
    r(
        "Bir kişi gayrimenkulleri devamlı olarak satın alıp satmayı meslek hâline getirmiştir. Bu faaliyetin kazancı hangisidir?",
        "Gayrimenkul alım, satım ve inşa işleriyle devamlı uğraşan kişinin kazancı hangi unsurdur?",
        "Ticari kazanç",
        "Ticari kazanç",
        ["Gayrimenkul sermaye iradı", "Değer artışı kazancı", "Serbest meslek kazancı", "Menkul sermaye iradı"],
        ["Gayrimenkul sermaye iradı", "Arızi kazanç", "Ücret", "Zirai kazanç"],
        "Gayrimenkul alım satımının devamlı faaliyet olarak yürütülmesi ticari kazanç doğurur.",
        "GVK m. 37, gayrimenkul alım, satım ve inşa işleriyle devamlı uğraşanların kazancını ticari sayar.",
        "193 sayılı GVK m. 37/4",
        "medium",
    ),
    r(
        "Bir kollektif şirket ortağı, şirket kârından pay almıştır. Gerçek kişi ortağın bu payı hangi gelir unsurudur?",
        "Kollektif ortakların ortaklık kârından aldıkları pay GVK bakımından nasıl nitelendirilir?",
        "Şahsi ticari kazanç",
        "Şahsi ticari kazanç",
        ["Ücret geliri", "Gayrimenkul sermaye iradı", "Arızi kazanç", "Zirai kazanç"],
        ["Menkul sermaye iradı", "Serbest meslek kazancı", "Değer artışı kazancı", "Ücret"],
        "Kollektif şirket ortaklarının ortaklık kârından aldığı paylar şahsi ticari kazanç hükmündedir.",
        "GVK, kollektif ortakların kâr payını gerçek kişi ortak yönünden şahsi ticari kazanç sayar.",
        "193 sayılı GVK m. 37",
        "medium",
    ),
    r(
        "Çiftçi, arazisinde yetiştirdiği ürünleri satarak kazanç elde etmiştir. Gelir unsuru hangisidir?",
        "Arazide ekim, dikim, bakım ve yetiştirme yoluyla ürün elde edilmesinden doğan kazanç hangisidir?",
        "Zirai kazanç",
        "Zirai kazanç",
        ["Ticari kazanç", "Ücret", "Menkul sermaye iradı", "Gayrimenkul sermaye iradı"],
        ["Serbest meslek kazancı", "Ticari kazanç", "Arızi kazanç", "Değer artışı kazancı"],
        "Zirai faaliyetten doğan ürün satış kazancı zirai kazançtır.",
        "Bitki ve hayvan ürünlerinin yetiştirilmesi ve elde edilmesi zirai faaliyet kapsamındadır.",
        "193 sayılı GVK m. 52",
        "easy",
    ),
    r(
        "Çiftçi, kendisine ait tarım makinesini başka çiftçilerin üretim işlerinde çalıştırmıştır. Bu gelir hangi faaliyete bağlıdır?",
        "Çiftçiye ait tarım makinesinin başka çiftçilerin üretiminde çalıştırılması hangi faaliyet sayılır?",
        "Zirai faaliyet",
        "Zirai faaliyet",
        ["Serbest meslek faaliyeti", "Ücret ilişkisi", "Gayrimenkul kiralaması", "Menkul sermaye yatırımı"],
        ["Ticari aracılık", "Bağımlı çalışma", "Menkul sermaye işletimi", "Arızi serbest meslek"],
        "Çiftçiye ait tarım makine ve aletlerinin diğer çiftçilerin zirai üretiminde çalıştırılması zirai faaliyettir.",
        "GVK m. 52, çiftçinin kendi tarım makinesini başka çiftçinin üretiminde çalıştırmasını zirai faaliyet sayar.",
        "193 sayılı GVK m. 52",
        "medium",
    ),
    r(
        "Çiftçi yalnız kendi ürettiği zeytinleri, sınai işletme boyutuna ulaşmayan tesisinde zeytinyağına dönüştürmüştür. Kazancın niteliği hangisidir?",
        "Zirai ürünü değerlendirmek için üretime bağlı ve sınai ölçekte olmayan işleme faaliyeti hangi kapsamda kalır?",
        "Zirai kazanç",
        "Zirai faaliyet",
        ["Serbest meslek kazancı", "Ücret", "Menkul sermaye iradı", "Gayrimenkul sermaye iradı"],
        ["Bağımsız ticari aracılık", "Ücret ilişkisi", "Servet değer artışı", "Menkul sermaye yatırımı"],
        "Kendi ürününü, zirai üretime bağlı ve sınai işletme genişliğine varmadan işlemek zirai faaliyetin devamıdır.",
        "Ürünün değerlendirilmesine yönelik bağlı işleme, kanundaki koşullarla zirai faaliyet sayılır.",
        "193 sayılı GVK m. 52",
        "hard",
    ),
    r(
        "Bir çalışan, işverene tabi ve belirli işyerine bağlı olarak hizmeti karşılığında ödeme almıştır. Gelir unsuru hangisidir?",
        "İşverene tabi, belirli işyerine bağlı çalışma karşılığındaki ödeme GVK'da nasıl adlandırılır?",
        "Ücret",
        "Ücret",
        ["Serbest meslek kazancı", "Ticari kazanç", "Menkul sermaye iradı", "Arızi kazanç"],
        ["Gayrimenkul sermaye iradı", "Zirai kazanç", "Değer artışı kazancı", "Ticari kazanç"],
        "İşverene tabi, işyerine bağlı çalışma karşılığı para veya ayınla sağlanan menfaat ücrettir.",
        "Bağımlılık, işyerine bağlılık ve hizmet karşılığı menfaat ücretin temel unsurlarıdır.",
        "193 sayılı GVK m. 61",
        "easy",
    ),
    r(
        "Çalışana aylığının yanında kasa tazminatı ve prim ödenmiştir. Bu ek ödemelerin gelir türü hangisidir?",
        "Ödemenin tazminat, ödenek, zam veya prim adı taşıması ücret niteliğini nasıl etkiler?",
        "Ücret",
        "Ücret niteliğini değiştirmez",
        ["Gayrimenkul sermaye iradı", "Menkul sermaye iradı", "Değer artışı kazancı", "Zirai kazanç"],
        ["Ödemeyi ticari kazanca dönüştürür", "Ödemeyi servet transferi yapar", "Ödemeyi kira geliri saydırır", "Ödemeyi zirai kazanç yapar"],
        "Hizmet ilişkisi kapsamında ödenen prim ve tazminatlar farklı ad taşısa da ücret sayılır.",
        "GVK m. 61, ücretin ödenek, tazminat, zam veya başka adla ödenmesinin niteliği değiştirmeyeceğini belirtir.",
        "193 sayılı GVK m. 61",
        "easy",
    ),
    r(
        "Bir anonim şirketin yönetim kurulu üyesine görevi nedeniyle ödeme yapılmıştır. Bu ödeme hangi gelir unsurudur?",
        "Yönetim ve denetim kurulu üyelerine bu sıfatları dolayısıyla yapılan ödemeler hangi gelir sayılır?",
        "Ücret",
        "Ücret",
        ["Menkul sermaye iradı", "Ticari kazanç", "Serbest meslek kazancı", "Değer artışı kazancı"],
        ["Kâr payı niteliğinde menkul sermaye iradı", "Gayrimenkul sermaye iradı", "Zirai kazanç", "Arızi ticari kazanç"],
        "Yönetim kurulu üyesine görevi nedeniyle yapılan ödeme GVK'da ücret sayılan ödemelerdendir.",
        "Kurul üyelerine bu sıfatları nedeniyle sağlanan para, ayın ve menfaatler ücret kapsamındadır.",
        "193 sayılı GVK m. 61/4",
        "medium",
    ),
    r(
        "Mali müşavir, işverene bağlı olmadan kendi nam ve hesabına mesleki bilgisiyle sürekli hizmet sunmaktadır. Gelir unsuru hangisidir?",
        "Sermayeden çok kişisel çalışmaya ve mesleki bilgiye dayanan bağımsız faaliyetin kazancı hangisidir?",
        "Serbest meslek kazancı",
        "Serbest meslek kazancı",
        ["Ücret", "Ticari kazanç", "Menkul sermaye iradı", "Gayrimenkul sermaye iradı"],
        ["Zirai kazanç", "Ücret", "Değer artışı kazancı", "Arızi kazanç"],
        "Bağımsız yürütülen ve kişisel emek ile mesleki bilgiye dayanan mali müşavirlik serbest meslek faaliyetidir.",
        "Sermayeden çok kişisel çalışmaya, bilimsel veya mesleki bilgiye dayanan bağımsız faaliyet serbest meslektir.",
        "193 sayılı GVK m. 65",
        "easy",
    ),
    r(
        "Bir mühendis, serbest meslek faaliyetini sürekli meslek hâlinde yürütmektedir. GVK bakımından sıfatı hangisidir?",
        "Serbest meslek faaliyetini mutat meslek hâlinde yapan kişi nasıl adlandırılır?",
        "Serbest meslek erbabı",
        "Serbest meslek erbabı",
        ["Ücretli hizmet erbabı", "Zirai işletme sahibi", "Menkul sermaye sahibi", "Gayrimenkul kiralayan"],
        ["Ticari temsilci", "Vergi sorumlusu", "Nihai tüketici", "Arızi kazanç sahibi"],
        "Serbest meslek faaliyetini devamlı ve mutat meslek hâlinde yapan kişi serbest meslek erbabıdır.",
        "Mutat biçimde serbest meslek faaliyeti yürütenler serbest meslek erbabı sayılır.",
        "193 sayılı GVK m. 66",
        "easy",
    ),
    r(
        "Bir avukat, mesleğini yalnız bir defa ve arızi olarak bağımsız biçimde icra etmiştir. Gelir hangi gruba girer?",
        "Mutat olmaksızın arızi yapılan serbest meslek faaliyetinden doğan kazanç hangi unsurda izlenir?",
        "Arızi kazanç",
        "Diğer kazanç ve irat",
        ["Sürekli serbest meslek kazancı", "Ücret", "Gayrimenkul sermaye iradı", "Zirai kazanç"],
        ["Menkul sermaye iradı", "Ticari kazanç", "Ücret", "Gayrimenkul sermaye iradı"],
        "Arızi olarak yapılan serbest meslek faaliyetinden doğan kazanç GVK m. 82 kapsamında arızi kazançtır.",
        "Devamlılık taşımayan serbest meslek faaliyeti, diğer kazanç ve iratlar içindeki arızi kazanç hükümlerine girer.",
        "193 sayılı GVK m. 80 ve 82/4",
        "hard",
    ),
    r(
        "Bir uzman, işverenin emir ve organizasyonuna bağlı çalışırken diğeri kendi müşteri ve çalışma düzenini belirlemektedir. İkinci kişinin geliri hangisidir?",
        "Ücret ile serbest meslek kazancını ayırmada belirleyici ölçüt hangisidir?",
        "Serbest meslek kazancı",
        "İşverene bağımlılık veya mesleki bağımsızlık",
        ["Ücret", "Zirai kazanç", "Gayrimenkul sermaye iradı", "Menkul sermaye iradı"],
        ["Ödemenin yalnız bankadan yapılması", "Mükellefin gerçek kişi olması", "Hizmetin aynı şehirde verilmesi", "Takvim yılının sona ermesi"],
        "Kendi nam ve hesabına, işverene bağlı olmadan sunulan uzmanlık hizmeti serbest meslek kazancı doğurur.",
        "İşverene tabi olma ücretin; bağımsız ve mesleki bilgiye dayalı çalışma serbest mesleğin ayırıcı yönüdür.",
        "193 sayılı GVK m. 61 ve 65",
        "medium",
    ),
    r(
        "Bir gerçek kişi kendisine ait işyerini kiraya vermiş ve kira bedeli elde etmiştir. Gelir unsuru hangisidir?",
        "GVK m. 70'te sayılan bina ve arazilerin kiraya verilmesinden doğan gelir hangisidir?",
        "Gayrimenkul sermaye iradı",
        "Gayrimenkul sermaye iradı",
        ["Menkul sermaye iradı", "Ücret", "Ticari kazanç", "Değer artışı kazancı"],
        ["Serbest meslek kazancı", "Zirai kazanç", "Arızi kazanç", "Ücret"],
        "Bina kiralamasından elde edilen bedel gayrimenkul sermaye iradıdır.",
        "GVK m. 70'te sayılan mal ve hakların kiraya verilmesinden elde edilen gelir gayrimenkul sermaye iradıdır.",
        "193 sayılı GVK m. 70",
        "easy",
    ),
    r(
        "Bir kişi sahibi olduğu markanın kullanım hakkını başka bir işletmeye kiralamıştır. Kira geliri hangi unsurdur?",
        "Marka ve benzeri sınai hakların kiraya verilmesinden doğan gelir hangi unsurda yer alır?",
        "Gayrimenkul sermaye iradı",
        "Gayrimenkul sermaye iradı",
        ["Menkul sermaye iradı", "Ücret", "Zirai kazanç", "Arızi kazanç"],
        ["Serbest meslek kazancı", "Ticari kazanç", "Ücret", "Değer artışı kazancı"],
        "GVK m. 70'te sayılan marka gibi hakların kiralanmasından doğan gelir gayrimenkul sermaye iradıdır.",
        "Gayrimenkul sermaye iradı yalnız taşınmazı değil, m. 70'te sayılan bazı hakların kiralanmasını da kapsar.",
        "193 sayılı GVK m. 70/5",
        "medium",
    ),
    r(
        "Bir işletmenin aktifine kayıtlı bina kiraya verilmiştir. Kira geliri işletmenin ticari faaliyetine bağlıdır. Hangi kazancın tespitinde dikkate alınır?",
        "Kiraya verilen mal veya hak ticari işletmeye dâhilse kira geliri hangi unsur içinde değerlendirilir?",
        "Ticari kazanç",
        "Ticari kazanç",
        ["Gayrimenkul sermaye iradı", "Menkul sermaye iradı", "Ücret", "Arızi kazanç"],
        ["Değer artışı kazancı", "Zirai kazanç", "Ücret", "Serbest meslek kazancı"],
        "Ticari işletmeye dâhil mal ve hakların kira gelirleri ayrı GMSİ değil, ticari kazancın tespitinde dikkate alınır.",
        "Mal veya hak ticari işletmeye dâhilse ondan elde edilen kira ticari kazanca bağlanır.",
        "193 sayılı GVK m. 70",
        "hard",
    ),
    r(
        "Bir gerçek kişi bankadaki mevduatı nedeniyle faiz geliri elde etmiştir. Gelir unsuru hangisidir?",
        "Sahibinin faaliyeti dışında nakdi sermayeden doğan faiz ve kâr payı türü gelirler hangi unsurdur?",
        "Menkul sermaye iradı",
        "Menkul sermaye iradı",
        ["Gayrimenkul sermaye iradı", "Ücret", "Zirai kazanç", "Arızi kazanç"],
        ["Serbest meslek kazancı", "Ticari kazanç", "Değer artışı kazancı", "Ücret"],
        "Mevduat faizi nakdi sermayeden doğduğu için menkul sermaye iradıdır.",
        "Ticari, zirai veya mesleki faaliyete bağlı olmayan nakdi sermaye gelirleri menkul sermaye iradıdır.",
        "193 sayılı GVK m. 75",
        "easy",
    ),
    r(
        "Gerçek kişi, ortak olduğu anonim şirketten kâr payı almıştır. Bu gelir hangi unsurdur?",
        "Hisse senedi ve iştirak hisselerinden doğan kâr payları hangi gelir unsuruna girer?",
        "Menkul sermaye iradı",
        "Menkul sermaye iradı",
        ["Ticari kazanç", "Ücret", "Gayrimenkul sermaye iradı", "Arızi kazanç"],
        ["Zirai kazanç", "Serbest meslek kazancı", "Değer artışı kazancı", "Ücret"],
        "Gerçek kişinin sermaye payı nedeniyle aldığı kâr payı menkul sermaye iradıdır.",
        "Hisse senedi ve iştirak hissesi kâr payları GVK m. 75'te menkul sermaye iradı sayılır.",
        "193 sayılı GVK m. 75/1-2",
        "easy",
    ),
    r(
        "Bir gerçek kişi tahvil faizini tahsil etmiştir. Tahvil ticari işletmesine bağlı değildir. Gelir unsuru hangisidir?",
        "Tahvil ve Hazine bonosu faizleri GVK'da hangi gelir unsuru içinde sayılır?",
        "Menkul sermaye iradı",
        "Menkul sermaye iradı",
        ["Değer artışı kazancı", "Ticari kazanç", "Ücret", "Gayrimenkul sermaye iradı"],
        ["Serbest meslek kazancı", "Zirai kazanç", "Arızi kazanç", "Ücret"],
        "Ticari faaliyete bağlı olmayan tahvil faizi menkul sermaye iradıdır.",
        "Tahvil ve Hazine bonosu faizleri GVK m. 75'te menkul sermaye iradı olarak sayılır.",
        "193 sayılı GVK m. 75/5",
        "easy",
    ),
    r(
        "Ticari işletmenin aktifindeki mevduattan faiz doğmuştur. Faiz işletmenin ticari faaliyetine bağlıdır. Hangi gelir unsurunda dikkate alınır?",
        "Menkul sermaye geliri ticari faaliyete bağlıysa hangi kazancın tespitine girer?",
        "Ticari kazanç",
        "Ticari kazanç",
        ["Menkul sermaye iradı", "Gayrimenkul sermaye iradı", "Ücret", "Arızi kazanç"],
        ["Zirai kazanç", "Değer artışı kazancı", "Serbest meslek kazancı", "Ücret"],
        "Sermaye geliri ticari işletmeye bağlı olduğunda ayrı MSI olarak değil ticari kazanç içinde dikkate alınır.",
        "GVK m. 75, sermaye gelirinin ticari faaliyete bağlı olması hâlinde ticari kazanç hükümlerini korur.",
        "193 sayılı GVK m. 75",
        "hard",
    ),
    r(
        "Bir gerçek kişi sahip olduğu tahvili ana para bedeli üzerinden satmıştır. Satışta alınan ana para hangi nedenle faiz geliri sayılmaz?",
        "Menkul kıymetin satış veya itfa karşılığında alınan ana para bedeli kural olarak hangi gelir değildir?",
        "Sermayenin kendisi olduğu için",
        "Menkul sermaye iradı",
        ["Ücret ödemesi olduğu için", "Zirai ürün bedeli olduğu için", "Kira tahsilatı olduğu için", "Mesleki hizmet bedeli olduğu için"],
        ["Gayrimenkul sermaye iradı", "Ücret", "Zirai kazanç", "Serbest meslek kazancı"],
        "Menkul kıymetin satış veya itfasında geri alınan sermaye, sermayenin getirisi olan irattan ayrılır.",
        "GVK m. 76, menkul kıymetin satış ve itfa bedellerini menkul sermaye iradı saymaz; varsa kazanç başka hükümlere göre değerlendirilir.",
        "193 sayılı GVK m. 76",
        "hard",
    ),
    r(
        "Bir gerçek kişi, gelir unsurlarının önceki altı grubuna girmeyen değer artışı ve arızi kazanç elde etmiştir. Bunlar hangi ana gruptadır?",
        "Diğer kazanç ve iratlar GVK'da hangi iki alt gruptan oluşur?",
        "Diğer kazanç ve iratlar",
        "Değer artışı kazançları ve arızi kazançlar",
        ["Yalnız ticari kazançlar", "Ücretler ve zirai kazançlar", "Kira ve faiz gelirleri", "Kurum kazançları"],
        ["Ücretler ve ticari kazançlar", "Zirai ve mesleki kazançlar", "Menkul ve gayrimenkul iratları", "Kurum ve ortaklık kazançları"],
        "Değer artışı ve arızi kazançlar, GVK'daki diğer kazanç ve iratlar grubunu oluşturur.",
        "GVK m. 80, diğer kazanç ve iratları değer artışı kazançları ile arızi kazançlar olarak ikiye ayırır.",
        "193 sayılı GVK m. 80",
        "easy",
    ),
    r(
        "Bir kişi bedel karşılığında edindiği taşınmazı iktisap tarihinden başlayarak beş yıl içinde satıp kazanç sağlamıştır. Faaliyet devamlı değildir. Gelir türü hangisidir?",
        "GVK'daki koşullarla belirli mal ve hakların elden çıkarılmasından doğan kazanç hangi gruptadır?",
        "Değer artışı kazancı",
        "Değer artışı kazancı",
        ["Gayrimenkul sermaye iradı", "Ticari kazanç", "Ücret", "Menkul sermaye iradı"],
        ["Arızi serbest meslek kazancı", "Zirai kazanç", "Ücret", "Gayrimenkul sermaye iradı"],
        "Devamlı ticari faaliyet oluşturmayan ve m. 80'deki koşulları taşıyan taşınmaz elden çıkarma kazancı değer artışı kazancıdır.",
        "GVK mükerrer m. 80'de sayılan mal ve hakların elden çıkarılmasından doğan kazançlar değer artışı kazancıdır.",
        "193 sayılı GVK mükerrer m. 80/6",
        "hard",
    ),
    r(
        "Bir kişi ticari bir işi devamlılık göstermeden yalnız bir kez yapmış ve kazanç sağlamıştır. Gelir unsuru hangisidir?",
        "Devamlılık taşımayan ticari veya mesleki faaliyetten doğan kazanç hangi grupta değerlendirilir?",
        "Arızi kazanç",
        "Arızi kazanç",
        ["Sürekli ticari kazanç", "Ücret", "Menkul sermaye iradı", "Gayrimenkul sermaye iradı"],
        ["Zirai kazanç", "Sürekli serbest meslek kazancı", "Ücret", "Değer artışı kazancı"],
        "Devamlılık göstermeyen ve bir defaya özgü ticari işlemden doğan kazanç arızi kazançtır.",
        "Arızi olarak yapılan ticari veya serbest meslek faaliyetlerinden doğan kazanç m. 82 kapsamındadır.",
        "193 sayılı GVK m. 82/1 ve 4",
        "medium",
    ),
    r(
        "Bir çalışan işverene bağlı hizmetinden ücret, ayrıca kişisel mevduatından faiz almıştır. Gelir unsurları sırasıyla hangileridir?",
        "Emek ilişkisine bağlı ödeme ile bağımsız nakdi sermaye getirisi sırasıyla hangi unsurlardır?",
        "Ücret ve menkul sermaye iradı",
        "Ücret ve menkul sermaye iradı",
        ["Ticari kazanç ve ücret", "Zirai kazanç ve kira geliri", "Serbest meslek kazancı ve ücret", "Arızi kazanç ve ticari kazanç"],
        ["Ticari kazanç ve zirai kazanç", "Gayrimenkul iradı ve ücret", "Serbest meslek kazancı ve kira", "Değer artışı ve ticari kazanç"],
        "İşverene bağlı hizmet ödemesi ücret; kişisel mevduat faizi menkul sermaye iradıdır.",
        "Bağımlı emeğin karşılığı ücret, faaliyete bağlı olmayan nakdi sermaye getirisi menkul sermaye iradıdır.",
        "193 sayılı GVK m. 61 ve 75",
        "medium",
    ),
]


PREMISES = [
    {"stem":"GVK'daki gelir unsurları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ticari kazanç bir gelir unsurudur\n\nII. Ücret bir gelir unsurudur\n\nIII. Menkul sermaye iradı bir gelir unsurudur","correct":"I, II ve III","why":"Üç unsur da GVK m. 2'de sayılan yedi gelir unsurundandır.","ref":"193 sayılı GVK m. 2","difficulty":"easy"},
    {"stem":"Ticari ve zirai kazanç ayrımı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Devamlı mal alım satımı ticari kazanç doğurabilir\n\nII. Bitki yetiştirilmesinden doğan kazanç zirai kazançtır\n\nIII. Her kira geliri zorunlu olarak ticari kazançtır","correct":"I ve II","why":"Devamlı ticari faaliyet ticari, yetiştirme faaliyeti zirai kazançtır; kira geliri koşula göre GMSİ olabilir.","ref":"193 sayılı GVK m. 37, 52 ve 70","difficulty":"medium"},
    {"stem":"Ücret ve serbest meslek kazancı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İşverene tabi çalışma ücret doğurur\n\nII. Her bağımsız mesleki faaliyet ücret sayılır\n\nIII. Kendi nam ve hesabına mesleki faaliyet serbest meslek kazancı doğurur","correct":"I ve III","why":"Bağımlı çalışma ücret, bağımsız ve mesleki bilgiye dayalı çalışma serbest meslek kazancıdır.","ref":"193 sayılı GVK m. 61 ve 65","difficulty":"medium"},
    {"stem":"Sermaye iratları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bina kirası menkul sermaye iradıdır\n\nII. Mevduat faizi menkul sermaye iradıdır\n\nIII. Bina kirası gayrimenkul sermaye iradıdır","correct":"II ve III","why":"Mevduat faizi MSI, bina kirası GMSİ'dir.","ref":"193 sayılı GVK m. 70 ve 75","difficulty":"easy"},
    {"stem":"Faaliyete bağlı gelirler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İşletme aktifindeki mevduat faizi ticari kazanca dâhil olabilir\n\nII. İşletmeye dâhil binanın kirası ticari kazanca bağlanabilir\n\nIII. Faaliyete bağlı her gelir ayrı menkul sermaye iradı sayılır","correct":"I ve II","why":"Ticari faaliyete bağlı sermaye ve kira gelirleri ticari kazancın tespitinde dikkate alınır.","ref":"193 sayılı GVK m. 70 ve 75","difficulty":"hard"},
    {"stem":"Diğer kazanç ve iratlar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Değer artışı kazançlarını kapsar\n\nII. Arızi kazançları kapsar\n\nIII. GVK'daki yedi gelir unsurundan biridir","correct":"I, II ve III","why":"Diğer kazanç ve iratlar, değer artışı ile arızi kazançlardan oluşan yedinci gelir unsurudur.","ref":"193 sayılı GVK m. 2 ve 80","difficulty":"easy"},
    {"stem":"Arızi kazanç bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Devamlılık göstermeyen ticari faaliyet arızi kazanç doğurabilir\n\nII. Mutat serbest meslek faaliyeti her durumda arızi kazançtır\n\nIII. Arızi serbest meslek faaliyeti diğer kazanç ve iratlarda yer alır","correct":"I ve III","why":"Devamlı olmayan ticari veya mesleki faaliyet arızi olabilir; mutat faaliyet serbest meslek kazancıdır.","ref":"193 sayılı GVK m. 65-66 ve 82","difficulty":"medium"},
    {"stem":"Gelir unsurlarının sınırları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Her taşınmaz satışı gayrimenkul sermaye iradıdır\n\nII. Sürekli taşınmaz alım satımı ticari kazanç doğurabilir\n\nIII. Koşulları taşıyan arızi taşınmaz satışı değer artışı kazancı olabilir","correct":"II ve III","why":"Kira GMSİ'dir; sürekli alım satım ticari, m. 80 koşullarındaki arızi satış değer artışı kazancı olabilir.","ref":"193 sayılı GVK m. 37, 70 ve mükerrer m. 80","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="gelir_vergisi",
        topic_id="gelir_unsurlari",
        label="Gelir Unsurları",
        slug="gelir_unsurlari",
        prefix="topic-gv-gu",
        seed=170727,
        legislation_version="193 sayılı Gelir Vergisi Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
