#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Bağımsızlık ve Etik, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Denetçi, müşteri yönetiminin çıkarı ile kamu yararı çatıştığında yalnız müşterinin talimatına göre davranmıştır. Etik Kuralların denetçiye yüklediği temel yönelimle uyumlu mudur?",
        "Denetçilik mesleğinin ayırt edici özelliklerinden biri aşağıdakilerden hangisidir?",
        "Hayır; denetçi kamu yararına uygun davranma sorumluluğu taşır",
        "Kamu yararına uygun davranma sorumluluğu",
        ["Evet; denetçi yalnız ücret ödeyen müşterinin çıkarını gözetir", "Evet; kamu yararı yalnız düzenleyici kurumun görevidir", "Hayır; denetçi hiçbir müşteri talebini dikkate alamaz", "Evet; sözleşme etik ilkelerin üzerinde yer alır"],
        ["Müşteri çıkarını bütün kullanıcıların üzerinde tutmak", "Her durumda yönetimin ticari kararlarını onaylamak", "Denetim sonucunu ücret düzeyine göre değiştirmek", "Yalnız vergi idaresine karşı sorumlu olmak"],
        "Denetçi müşteri adına hizmet verse de mesleğin kamu yararı sorumluluğunu gözetir.",
        "Kamu yararı, temel etik ilkelerin ve bağımsızlık standartlarının uygulanmasının ana gerekçesidir.",
        "Etik Kurallar Bölüm 100 par. 100.1-100.6", "easy",
    ),
    r(
        "Bir denetçi dürüstlük ve tarafsızlığa uymış, fakat mesleki yeterlik, sır saklama ve mesleğe uygun davranış ilkelerini uygulamamıştır. Temel etik ilkelere tam uyum var mıdır?",
        "Bağımsız Denetçiler İçin Etik Kurallarda yer alan beş temel ilke hangileridir?",
        "Hayır; beş temel ilkenin tamamına uyulmalıdır",
        "Dürüstlük, tarafsızlık, mesleki yeterlik ve özen, sır saklama, mesleğe uygun davranış",
        ["Evet; dürüstlük diğer ilkelerin yerine geçer", "Evet; yalnız bağımsızlık ilkesi bağlayıcıdır", "Hayır; etik ilkeler sadece denetim şirketine uygulanır", "Evet; müşteri onayı eksik ilkeleri giderir"],
        ["Bağımsızlık, müşteri sadakati, ticari yeterlik, ücret gizliliği ve kâr odaklı mesleki davranış", "Tarafsızlık, rekabetçi ücret, hızlı raporlama, sınırsız reklam ve yönetim talimatına uyum", "Dürüstlük, vergi tasarrufu, satış, tahsilat ve kâr", "Bağımsızlık, yönetim, bütçeleme, yatırım ve finansman"],
        "Temel ilkeler ayrı yükümlülüklerdir; biri diğerlerinin ihlalini telafi etmez.",
        "Etik Kurallar beş ilkeyi birlikte denetçiden beklenen standart davranış olarak tanımlar.",
        "Etik Kurallar Bölüm 110", "easy",
    ),
    r(
        "Denetçi, müşteri kabulünü sağlamak için bildiği önemli bir bilgiyi yanıltıcı rapora eklememiştir. Hangi temel ilke ihlal edilmiştir?",
        "Dürüstlük ilkesi denetçiden hangi davranışı bekler?",
        "Dürüstlük",
        "Mesleki ilişkilerinde açık sözlü ve doğru olmak",
        ["Tarafsızlık", "Sır saklama", "Mesleki yeterlik", "Mesleğe uygun davranış"],
        ["Müşterinin bütün açıklamalarını sorgusuz kabul etmek", "Her bilgiyi kamuya açıklamak", "Denetim ücretini rakiplere göre belirlemek", "Yönetimin ticari hedefini üstlenmek"],
        "Yanlış veya yanıltıcı bilgiyle bilerek ilişkilendirilmek dürüstlük ilkesiyle bağdaşmaz.",
        "Dürüstlük; doğruluk ve açık sözlülük gerektirir, fakat sır saklama yükümlülüğünü ortadan kaldırmaz.",
        "Etik Kurallar Bölüm 111", "easy",
    ),
    r(
        "Denetim yöneticisi, yakın arkadaşının hazırladığı muhasebe tahminini kanıta aykırı olmasına rağmen eleştirmemiştir. Hangi ilke öncelikle tehdit altındadır?",
        "Tarafsızlık ilkesi aşağıdakilerden hangisini gerektirir?",
        "Tarafsızlık",
        "Önyargı, çıkar çatışması veya başkalarının etkisiyle mesleki muhakemeden ödün vermemek",
        ["Dürüstlük", "Sır saklama", "Mesleki yeterlik", "Mesleğe uygun davranış"],
        ["Bütün müşteri görüşlerini reddedip yalnız denetim şirketi yönetiminin değerlendirmesini benimsemek", "Yalnız dış kanıta dayanıp işletme içinden elde edilen bütün kanıtları geçersiz saymak", "Her çıkar çatışmasını gizli tutup mesleki kararı müşterinin yazılı talimatına göre oluşturmak", "Mesleki muhakemeyi yönetimin talimatına bırakmak"],
        "Yakınlık ilişkisi denetçinin tarafsız muhakemesini zedeleyebilir.",
        "Tarafsızlık, mesleki veya ticari kararın uygunsuz etkiler altında kalmamasını gerektirir.",
        "Etik Kurallar Bölüm 112", "medium",
    ),
    r(
        "Denetçi, yeni bir finansal raporlama standardını öğrenmeden karmaşık denetimi yürütmüş ve gerekli özeni göstermemiştir. Hangi temel ilke ihlal edilmiştir?",
        "Mesleki yeterlik ve özen ilkesi hangi iki yükümlülüğü birlikte içerir?",
        "Mesleki yeterlik ve özen",
        "Mesleki bilgi ve beceriyi güncel tutmak, hizmeti standartlara göre özenle yürütmek",
        ["Dürüstlük ve sır saklama ilkeleri", "Mesleki bağımsızlık yükümlülüğü", "Sır saklama yükümlülüğü", "Mesleğe uygun davranış ilkesi"],
        ["Yalnız denetim ücretini düşük tutmak, süreyi kısaltmak ve müşteri talimatlarını önceliklendirmek", "Mesleki bilgi güncelliğini müşteriye bırakmak ve bütün teknik görevleri deneyimsiz personele devretmek", "Bütün karmaşık konularda danışmayı reddedip önceki yıl uygulamasını aynen sürdürmek", "Hizmeti yalnız bütçe ve müşteri memnuniyeti ölçütlerine göre hızla tamamlamak"],
        "Güncel teknik bilgi olmadan ve gerekli dikkat gösterilmeden çalışma yeterlik ve özen ilkesini ihlal eder.",
        "İlke, yeterli mesleki bilgi düzeyini korumayı ve geçerli teknik-mesleki standartlara uygun titiz hizmeti birlikte arar.",
        "Etik Kurallar Bölüm 113", "easy",
    ),
    r(
        "Denetçi, eski müşteriye ait gizli ticari bilgiyi kişisel yatırım kararında kullanmıştır. Bilgiyi üçüncü kişiye açıklamamış olması ihlali ortadan kaldırır mı?",
        "Sır saklama ilkesi yalnız bilginin açıklanmasını mı yasaklar?",
        "Hayır; gizli bilginin kişisel çıkar için kullanılması da yasaktır",
        "Hayır; açıklama yanında kişisel veya üçüncü kişi yararına kullanım da yasaktır",
        ["Evet; bilgi üçüncü kişiye aktarılmadığı sürece denetçinin kişisel yatırımında kullanılması serbesttir", "Evet; denetim sözleşmesi sona erdiğinde eski müşteriye ilişkin bütün gizlilik yükümlülükleri biter", "Hayır; bütün müşteri bilgileri kamuya ve düzenleyici kurumlara kendiliğinden açıklanmalıdır", "Evet; yalnız yazılı belgeler gizlidir ve sözlü bilgiler serbestçe kullanılabilir"],
        ["Evet; yalnız kamuya açıklama yasaktır, denetçinin kişisel yatırımında kullanması her durumda serbesttir", "Evet; müşteri ilişkisi sona erince çalışanlar ve üçüncü kişiler arasında kullanım sınırsız hâle gelir", "Hayır; denetçi gizli bilgiyi mevzuatın izin verdiği mesleki görevlerde dahi hiçbir zaman kullanamaz", "Evet; ekonomik değeri olan bilgi ticari nitelik taşıdığı için sır saklama kapsamına girmez"],
        "Gizli bilgiden denetçinin veya üçüncü kişilerin yararına faydalanmak sır saklama ilkesine aykırıdır.",
        "Gizlilik görevi müşteri ilişkisi sona erdikten sonra da sürer; mevzuat veya mesleki hak-görev istisnaları ayrıca değerlendirilir.",
        "Etik Kurallar Bölüm 114", "medium",
    ),
    r(
        "Denetçi, mesleği itibarsızlaştıracağını bildiği yanıltıcı reklam kullanmıştır. Hangi temel ilke doğrudan ihlal edilmiştir?",
        "Mesleğe uygun davranış ilkesi denetçiden ne ister?",
        "Mesleğe uygun davranış",
        "Mevzuata uymak ve mesleğin itibarını zedeleyecek davranışlardan kaçınmak",
        ["Mesleki yeterlik ve özen ilkesi", "Mesleki bağımsızlık yükümlülüğü", "Sır saklama yükümlülüğü", "Tarafsızlık ilkesi"],
        ["Rakipleri küçümseyen ve sunulabilecek hizmetlerin sonucunu kesin biçimde garanti eden reklamları kullanmak", "Müşteri çıkarını korumak için mevzuatı göz ardı edip yanıltıcı mesleki beyanlarda bulunmak", "Mesleki hizmetlerin sonuçlarını müşterinin ticari hedeflerine göre garanti etmek", "Denetim kanıtını reklam amacıyla kamuya açık biçimde yayımlamak"],
        "Yanıltıcı veya mesleği itibarsızlaştıran davranış mesleğe uygun davranış ilkesiyle bağdaşmaz.",
        "İlke, ilgili mevzuata uymayı ve makul üçüncü kişinin mesleği olumsuz değerlendirmesine yol açacak davranışlardan kaçınmayı gerektirir.",
        "Etik Kurallar Bölüm 115", "easy",
    ),
    r(
        "Denetçi, bir çıkar ilişkisinin temel ilkelere tehdit oluşturabileceğini fark etmiş; ancak tehdidi değerlendirmeden hizmete devam etmiştir. Kavramsal çerçeve uygulanmış mıdır?",
        "Etik Kuralların kavramsal çerçevesindeki üç aşama hangileridir?",
        "Hayır; tehdit belirlenmeli, değerlendirilmeli ve ele alınmalıdır",
        "Tehditleri belirlemek, değerlendirmek ve ele almak",
        ["Evet; tehdidi fark etmek yeterlidir ve önem değerlendirmesi yapılmadan hizmet aynen sürdürülebilir", "Evet; değerlendirme yalnız rapor tarihinden sonra müşteri yönetimi talep ederse yapılır", "Hayır; belirlenen her tehditte denetim şirketi bütün mesleki faaliyetlerini kalıcı olarak bırakır", "Evet; müşteri tehdidi yazılı olarak kabul ederse herhangi bir karşılık uygulanmadan işlem tamamlanır"],
        ["Ücreti belirlemek, müşteriden yazılı onay almak ve rapor tarihinden sonra tahsil etmek", "Tehdidi yalnız dosyada açıklamak, müşteri talimatına uymak ve çalışmayı değiştirmeden sürdürmek", "Planlamak, bütçelemek ve sonuçları müşteri yönetiminin beklentisine göre raporlamak", "İspatlamak, cezalandırmak ve bütün mesleki ilişkiyi kamuya açıklamak"],
        "Kavramsal çerçeve tehdit farkındalığını, kabul edilebilir düzey değerlendirmesini ve uygun karşılığı birlikte gerektirir.",
        "Kurallar her olayı listeleyemediği için denetçi mesleki muhakemeyle üç aşamalı yaklaşımı uygular.",
        "Etik Kurallar Bölüm 120 par. 120.3-120.10", "easy",
    ),
    r(
        "Denetçi, bir tehdidin kabul edilebilir düzeyde olduğunu yalnız kendi bakış açısıyla değerlendirmiştir. Etik Kurallardaki nesnel test hangisidir?",
        "Makul ve bilgi sahibi üçüncü taraf testi hangi soruya cevap arar?",
        "Makul ve bilgi sahibi üçüncü taraf testi",
        "Aynı olgu ve koşulları değerlendiren üçüncü tarafın temel ilkelere uyulduğu sonucuna varıp varmayacağı",
        ["Yönetimin ticari başarı ve ücret ödeme kapasitesi testi", "Müşterinin hizmetten memnuniyetini ve sözleşmeyi yenileme niyetini ölçen ticari ilişki testi", "Denetim ücretinin rakiplerin fiyat politikasına uygunluğunu ölçen yeterlilik testi", "Düzenleyicinin olası ceza tutarı ile müşteri kârlılığını karşılaştıran maliyet testi"],
        ["Müşteri yönetiminin denetim ücretini uygun bulup sözleşmeyi yenilemeye karar verip vermeyeceği ve hizmetten memnun kalıp kalmayacağı", "Denetim ücretinin rakiplere uygun olup olmadığı ve müşteri bütçesini aşıp aşmayacağı", "Düzenleyici kurumun her olguyu ayrıca inceleyip ceza ihtimalini yüksek görüp görmeyeceği ve sonucu kamuya açıklayıp açıklamayacağı", "Tehdidin kamuya açıklanmasının müşteri ve denetim şirketi için reklam değeri taşıyıp taşımayacağı"],
        "Tehdit değerlendirmesi yalnız denetçinin öznel kanaatine bırakılamaz.",
        "Test, ilgili tüm olguları bilen makul üçüncü kişinin denetçinin temel ilkelere uyduğu sonucuna varıp varmayacağını sorgular.",
        "Etik Kurallar Bölüm 120 par. 120.5", "medium",
    ),
    r(
        "Bir tehdit; kişisel çıkar, kendi kendini denetleme, taraf tutma, yakınlık veya yıldırma başlıklarından biriyle ilişkilendirilememiştir. Denetçi tehdidi yok sayabilir mi?",
        "Etik Kurallarda temel ilkelere uyumu engelleyen beş tehdit sınıfı hangileridir?",
        "Hayır; sınıflar örnekleyicidir ve tehdit yine değerlendirilir",
        "Kişisel çıkar, kendi kendini denetleme, taraf tutma, yakınlık ve yıldırma",
        ["Evet; yalnız adı açıkça sayılan tehditler dikkate alınır ve başka nitelikteki riskler yok sayılır", "Evet; sınıflandırılamayan riskler müşteri yönetiminin yazılı onayıyla etik tehdit olmaktan çıkar", "Hayır; sınıflanamayan her durum ayrıca değerlendirilmeden otomatik olarak meslek suçu sayılır", "Evet; beş sınıf yalnız finansal kuruluş denetimlerine ve halka açık işletmelere uygulanır"],
        ["Kârlılık, likidite, borçlanma, vergi planlaması ve yatırım getirisini artırma tehdidi", "Planlama, bütçeleme, kanıt toplama, örnekleme ve denetim raporunu zamanında tamamlama tehdidi", "Dürüstlük, gizlilik, kalite yönetimi, ücret tahsilatı ve mesleki rekabet tehdidi", "Hata, hile, mevzuata aykırılık, işletmenin sürekliliği ve ilişkili taraf tehdidi"],
        "Beş sınıf tehditleri analiz etmeyi kolaylaştırır, fakat karşılaşılabilecek durumların tamamını tüketici biçimde listelemez.",
        "Bir durum birden çok tehdit yaratabilir; denetçi her tehdidi olgu ve koşullarıyla değerlendirir.",
        "Etik Kurallar Bölüm 120 par. 120.6", "medium",
    ),
    r(
        "Denetim ekibi üyesinin müşteride önemli doğrudan finansal çıkarı vardır. Bu çıkarın muhakemeyi uygunsuz etkileme ihtimali hangi tehdittir?",
        "Denetçinin finansal veya başka bir çıkarının muhakemesini uygunsuz etkilemesi hangi tehdit sınıfıdır?",
        "Kişisel çıkar tehdidi",
        "Kişisel çıkar tehdidi",
        ["Kendi kendini denetleme tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"],
        ["Kendi kendini denetleme", "Taraf tutma", "Yakınlık", "Yıldırma"],
        "Müşterideki finansal çıkar, denetçinin sonuçtan ekonomik olarak etkilenmesine yol açar.",
        "Kişisel çıkar tehdidi, mali veya başka bir menfaatin muhakeme ya da davranışı uygunsuz etkilemesi riskidir.",
        "Etik Kurallar Bölüm 120 par. 120.6 U3(a)", "easy",
    ),
    r(
        "Denetim şirketi müşterinin değerleme modelini tasarlamış, aynı modelin finansal tablo sonucunu daha sonra denetlemiştir. Hangi tehdit doğar?",
        "Önceki bir muhakeme veya hizmet sonucunun aynı denetçi tarafından değerlendirilmesi hangi tehdit sınıfıdır?",
        "Kendi kendini denetleme tehdidi",
        "Kendi kendini denetleme tehdidi",
        ["Kişisel çıkar tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"],
        ["Kişisel çıkar", "Taraf tutma", "Yakınlık", "Yıldırma"],
        "Denetçi kendi ürettiği sonuç veya muhakemeyi nesnel biçimde yeniden değerlendiremeyebilir.",
        "Tehdit, daha önce yapılan işin mevcut mesleki faaliyet kapsamında güvenilir biçimde değerlendirilememesi riskidir.",
        "Etik Kurallar Bölüm 120 par. 120.6 U3(b)", "easy",
    ),
    r(
        "Denetçi müşteri adına bir hukuki uyuşmazlıkta finansal pozisyonu savunmuş, ardından aynı hususu bağımsız denetimde değerlendirmiştir. Hangi tehdit oluşur?",
        "Müşterinin görüşünü, denetçinin tarafsızlığını zedeleyecek ölçüde desteklemesi hangi tehdit sınıfıdır?",
        "Taraf tutma tehdidi",
        "Taraf tutma tehdidi",
        ["Kişisel çıkar tehdidi", "Kendi kendini denetleme tehdidi", "Yakınlık tehdidi", "Yıldırma tehdidi"],
        ["Kişisel çıkar", "Kendi kendini denetleme", "Yakınlık", "Yıldırma"],
        "Müşterinin pozisyonunu savunmak denetçiyi aynı konu hakkında tarafsız değerlendirme yapamayacak konuma getirebilir.",
        "Taraf tutma tehdidi, müşterinin görüşünün denetçi tarafından tarafsızlıktan ödün verecek biçimde desteklenmesidir.",
        "Etik Kurallar Bölüm 120 par. 120.6 U3(c)", "easy",
    ),
    r(
        "Aynı sorumlu denetçi uzun yıllar boyunca müşteri yönetimiyle çok yakın ilişki kurmuş ve açıklamaları aşırı hoşgörüyle kabul etmeye başlamıştır. Hangi tehdit öne çıkar?",
        "Uzun veya yakın ilişki nedeniyle denetçinin müşteri çıkarlarına aşırı yakınlık duyması hangi tehdittir?",
        "Yakınlık tehdidi",
        "Yakınlık tehdidi",
        ["Kişisel çıkar tehdidi", "Kendi kendini denetleme tehdidi", "Taraf tutma tehdidi", "Yıldırma tehdidi"],
        ["Kişisel çıkar", "Kendi kendini denetleme", "Taraf tutma", "Yıldırma"],
        "Uzun ilişki denetçinin yönetim açıklamalarına gereğinden fazla güvenmesine yol açabilir.",
        "Yakınlık tehdidi, uzun ya da yakın ilişki sonucu denetçinin müşteri çıkarlarına fazla yakınlık veya hoşgörü duymasıdır.",
        "Etik Kurallar Bölüm 120 par. 120.6 U3(ç)", "easy",
    ),
    r(
        "Müşteri yönetimi, istenen görüş verilmezse denetim şirketini görevden alma tehdidinde bulunmuştur. Hangi tehdit söz konusudur?",
        "Gerçek veya hissedilen baskı nedeniyle denetçinin tarafsız davranmasının engellenmesi hangi tehdittir?",
        "Yıldırma tehdidi",
        "Yıldırma tehdidi",
        ["Kişisel çıkar tehdidi", "Kendi kendini denetleme tehdidi", "Taraf tutma tehdidi", "Yakınlık tehdidi"],
        ["Kişisel çıkar", "Kendi kendini denetleme", "Taraf tutma", "Yakınlık"],
        "Görevden alma baskısı denetçinin mesleki muhakemesinden ödün vermesine yol açabilir.",
        "Yıldırma tehdidi, denetçinin gerçek veya hissedilen baskı yüzünden tarafsız davranmasının engellenmesidir.",
        "Etik Kurallar Bölüm 120 par. 120.6 U3(d)", "easy",
    ),
    r(
        "Denetçi bir tehdidin kabul edilebilir düzeyde olmadığını belirlemiş, fakat hiçbir önlem almadan çalışmaya devam etmiştir. Etik Kurallara uygun mudur?",
        "Kabul edilebilir düzeyde olmayan tehdit hangi yollarla ele alınır?",
        "Hayır; tehdit uygun bir karşılıkla ele alınmalıdır",
        "Kaynağı ortadan kaldırmak, önlem uygulamak veya faaliyeti reddetmek ya da sona erdirmek",
        ["Evet; tehdidin yalnız belgelenmesi yeterlidir", "Evet; müşteri tehdidi biliyorsa sorun kalmaz", "Hayır; her tehditte meslekten tamamen ayrılmak gerekir", "Evet; tehdit rapor tarihinden sonra ele alınır"],
        ["Yalnız denetim ücretini artırmak ve tehdidi çalışma kâğıdında açıklayarak faaliyeti aynen sürdürmek", "Tehdidi müşteri yönetimine bildirip sözlü onay aldıktan sonra herhangi bir önlem uygulamadan çalışmak", "Kanıt düzeyini azaltıp denetim süresini kısaltarak tehdidin görünürlüğünü düşürmek", "Tehdidi yalnız kalite dosyasına kaydedip kaynağını ve etkisini değerlendirmemek"],
        "Denetçi tehdidi ortadan kaldırır, kabul edilebilir düzeye indiren önlemler uygular veya ilgili faaliyeti reddeder/sona erdirir.",
        "Uygun karşılık tehdidin kaynağına, önemine ve mevcut önlemlerin etkinliğine göre seçilir.",
        "Etik Kurallar Bölüm 120 par. 120.10-120.11", "medium",
    ),
    r(
        "Bir işlem bağımsız bir kanaat oluşturmayı fiilen etkilememiştir; ancak makul üçüncü taraf denetçinin tarafsızlığından kuşku duyacaktır. Bağımsızlık korunmuş mudur?",
        "Bağımsızlık standartları hangi iki boyutu birlikte kapsar?",
        "Hayır; şekilde bağımsızlık da korunmalıdır",
        "Esasta bağımsızlık ve şekilde bağımsızlık",
        ["Evet; yalnız denetçinin kendi kanaati önemlidir", "Evet; görünüş hiçbir zaman dikkate alınmaz", "Hayır; yalnız mali bağımsızlık aranır", "Evet; müşteri ilişkiyi açıklarsa tehdit biter"],
        ["Finansal bağımsızlık ve hukuki bağımsızlık", "Yönetim bağımsızlığı ve bütçe bağımsızlığı", "Teknik bağımsızlık ve ücret bağımsızlığı", "İç bağımsızlık ve vergi bağımsızlığı"],
        "Bağımsızlığın fiilen korunması kadar dışarıdan makul algının korunması da güvence değerini etkiler.",
        "Etik Kurallar bağımsızlığı esasta ve şekilde bağımsızlık boyutlarıyla tanımlar.",
        "Etik Kurallar Kısım 4A par. 400.5", "medium",
    ),
    r(
        "Denetçi müşteri baskısından etkilenmeden dürüst, tarafsız ve mesleki şüphecilikle karar verebilmiştir. Bağımsızlığın hangi boyutu tanımlanmaktadır?",
        "Esasta bağımsızlığın temel sonucu nedir?",
        "Esasta bağımsızlık",
        "Mesleki muhakemeyi zedeleyen etkiler olmadan sonuç oluşturabilmek",
        ["Şekilde bağımsızlık", "Yönetim bağımsızlığı", "Finansal raporlama bağımsızlığı", "İç kontrol bağımsızlığı"],
        ["Bütün müşteri ilişkilerinin açıklanıp mesleki muhakemenin yönetimin talimatına bırakılması", "Denetim ücretinin sıfırlanması ve bütün finansal ilişkilerin kamuya açıklanması", "Müşteri yönetiminin görüşü belirlemesine izin verilip bu durumun denetçi raporunda ayrıca açıklanması", "Denetçinin işletme çalışanı olması ve yönetimin ticari kararlarını uygulaması"],
        "Esasta bağımsızlık denetçinin sonuç oluştururken dürüstlük, tarafsızlık ve mesleki şüpheciliğini korumasıdır.",
        "Bu boyut denetçinin zihnî durumuna ve muhakemesinin uygunsuz etkilerden bağımsızlığına ilişkindir.",
        "Etik Kurallar par. 400.5(a)", "easy",
    ),
    r(
        "Denetçi fiilen tarafsız olduğunu düşünse de kamuya açık yakın ilişki, makul üçüncü tarafta bağımsızlığın zedelendiği algısı yaratmaktadır. Hangi boyut etkilenmiştir?",
        "Şekilde bağımsızlık neden gereklidir?",
        "Şekilde bağımsızlık",
        "Makul üçüncü tarafın dürüstlük, tarafsızlık veya şüpheciliğin zedelendiği sonucuna varmasını önlemek",
        ["Esasta bağımsızlık", "Mesleki yeterlik", "Sır saklama", "Denetim riski"],
        ["Denetim ücretini artırarak müşteriyle kurulan yakın ilişkinin bütün kullanıcılar tarafından bilinir hâle getirilmesini sağlamak", "Müşterinin bütün isteklerini yerine getirip denetçinin fiilen tarafsız olduğu yönündeki yönetim açıklamasına dayanmak", "Denetim kanıtını azaltıp yalnız denetim ekibinin bağımsızlık kanaatini çalışma dosyasına kaydetmek", "Yalnız düzenleyicinin kanaatini esas alıp diğer makul kullanıcıların algısını değerlendirme dışında bırakmak"],
        "Bağımsızlık yalnız denetçinin iç kanaatiyle değil, makul ve bilgi sahibi üçüncü taraf algısıyla da değerlendirilir.",
        "Şekilde bağımsızlık, güvence raporuna duyulan kamusal güveni korur.",
        "Etik Kurallar par. 400.5(b)", "easy",
    ),
    r(
        "Denetim ekibi üyesi, denetlenen işletmede önemli doğrudan finansal çıkar edinmiş ve çıkarı elinde tutarak denetime devam etmiştir. Uygun mudur?",
        "Denetim ekibi üyesinin denetim müşterisindeki doğrudan finansal çıkarı için temel yaklaşım nedir?",
        "Hayır; yasaklanan finansal çıkar elden çıkarılmalı veya kişi ekipten ayrılmalıdır",
        "Doğrudan finansal çıkar bulundurulamaz",
        ["Evet; çıkar dipnotta açıklanırsa yeterlidir", "Evet; oy hakkı kullanılmazsa tehdit yoktur", "Hayır; yalnız müşteri yönetimi çıkarı satın almalıdır", "Evet; çıkar denetim ücretinden küçükse her durumda serbesttir"],
        ["Çıkar yalnız yönetimin onayıyla tutulabilir", "Çıkar rapor tarihine kadar artırılabilir", "Çıkar denetim kanıtıyla mahsup edilir", "Çıkar sadece sözlü olarak açıklanır"],
        "Denetim ekibi ve yakın aile için müşteride doğrudan ya da önemli dolaylı finansal çıkar bağımsızlıkla bağdaşmaz.",
        "Yasaklanan çıkarın ortadan kaldırılması veya ilgili kişinin ekipten çıkarılması gerekir.",
        "Etik Kurallar Bölüm 510", "hard",
    ),
    r(
        "Denetim ekibi üyesi, denetim müşterisi bankadan olağan prosedür ve piyasa koşulları dışında önemli bir kredi almıştır. Bağımsızlık açısından nasıl değerlendirilir?",
        "Denetim müşterisi finansal kuruluştan alınan kredi hangi durumda bağımsızlık tehdidini artırır?",
        "Kişisel çıkar tehdidi doğar ve ilişki kabul edilebilir düzeye getirilmelidir",
        "Kredi olağan kredi prosedür ve koşullarına uygun olmadığında",
        ["Hiçbir tehdit doğmaz; kredi ile denetim ilgisizdir", "Yalnız yakınlık tehdidi doğar ve açıklama yeterlidir", "Kredi otomatik olarak denetim ücretine dönüştürülür", "Müşteri banka ise bütün krediler koşulsuz serbesttir"],
        ["Kredi olağan piyasa koşullarında ve standart süreçle verildiğinde", "Kredi başvurusu reddedildiğinde", "Kredi başka bir müşteriye kullandırıldığında", "Kredi finansal tablolarda muhasebeleştirildiğinde"],
        "Olağan koşullar dışındaki kredi, denetçinin müşteriye ekonomik bağımlılığı yoluyla kişisel çıkar tehdidi yaratır.",
        "Finansal kuruluşun normal kredi verme prosedür ve koşulları bağımsızlık değerlendirmesinde belirleyicidir.",
        "Etik Kurallar Bölüm 511", "hard",
    ),
    r(
        "Denetim ekibi üyesinin eşi, denetim müşterisinde finansal tabloların hazırlanmasını önemli ölçüde etkileyebilen yönetici konumundadır. Ekip üyesi denetime devam edebilir mi?",
        "Yakın aile ferdinin müşteride finansal raporlamayı etkileyen görevde bulunması öncelikle hangi bağımsızlık sorununu doğurur?",
        "Hayır; kişi denetim ekibinden çıkarılmalıdır",
        "Kişisel çıkar, yakınlık veya yıldırma tehditleri",
        ["Evet; eşin görevi denetimle hiçbir zaman ilişkili değildir", "Evet; yalnız sözlü açıklama yapılması yeterlidir", "Hayır; eş işten ayrılana kadar müşteri finansal tablo hazırlamaz", "Evet; denetçi görüş paragrafına aile bağını ekler"],
        ["Yalnız mesleki yeterlik tehdidi", "Sadece sır saklama tehdidi", "Hiçbir tehdit; aile ilişkileri dikkate alınmaz", "Yalnız müşteri savunuculuğu tehdidi"],
        "Yakın aile ferdinin müşteri finansal raporlamasını etkileyen görevi, ekip üyesinin bağımsızlığını kabul edilemez biçimde zedeler.",
        "Tehdidin türü ve ağırlığı göreve, yakınlığa ve kişinin ekipteki rolüne bağlıdır; bazı görevler açıkça yasaktır.",
        "Etik Kurallar Bölüm 521", "hard",
    ),
    r(
        "Müşteri yönetimi denetim sonucunu etkilemek amacıyla pahalı bir tatil teklif etmiştir. Denetçi hediyeyi kabul edip tehdidi dipnotta açıklayabilir mi?",
        "Hediye ve ağırlamanın denetçiyi uygunsuz biçimde etkileme amacı varsa hangi yaklaşım uygulanır?",
        "Hayır; uygunsuz etkileme amacı taşıyan teklif kabul edilmez",
        "Teklif reddedilir ve gerekli diğer karşılıklar değerlendirilir",
        ["Evet; dipnot açıklaması bütün tehdidi giderir", "Evet; müşteri gider yazarsa hediye serbesttir", "Hayır; hediye kabul edilip denetim ücreti azaltılır", "Evet; yalnız rapor tarihinden sonra kabul edilir"],
        ["Değeri ne olursa olsun kabul edilir", "Denetim görüşü karşılığında pazarlık yapılır", "Teklif ekip içinde paylaştırılarak tehdit azaltılır", "Hediye nakit değilse etik değerlendirme yapılmaz"],
        "Uygunsuz etkileme amacı veya bu yönde makul algı varsa teşvik kabul edilmez.",
        "Önemsiz değer değerlendirmesi, uygunsuz etkileme amacı bulunan bir teklifi meşru hâle getirmez.",
        "Etik Kurallar Bölüm 340 ve 420", "medium",
    ),
    r(
        "Denetim ücreti, müşterinin istediği olumlu görüşün verilmesi şartına bağlanmıştır. Böyle bir ücret düzenlemesi kabul edilebilir mi?",
        "Denetim sonucuna bağlı şarta bağlı ücret neden bağımsızlıkla bağdaşmaz?",
        "Hayır; denetim için şarta bağlı ücret yasaktır",
        "Sonuçta doğrudan mali çıkar yaratarak kişisel çıkar tehdidi oluşturur",
        ["Evet; sonuç gerçekleşirse ücret açıklanır", "Evet; ücret düşükse tehdit önemsizdir", "Hayır; yalnız müşteri ücret tutarını belirleyebilir", "Evet; üst yönetimden sorumlu olanlar sözlü onaylarsa"],
        ["Denetim kanıtının miktarını otomatik artırdığı için", "Müşteriyle yakınlık ilişkisini sona erdirdiği için", "Mesleki yeterliği tek başına kanıtladığı için", "Denetim riskini sıfıra indirdiği için"],
        "Görüş veya sonuçla bağlantılı ücret denetçinin ekonomik menfaatini mesleki sonucuna bağlar.",
        "Bu kişisel çıkar tehdidi önlemle kabul edilebilir düzeye indirilemeyeceğinden denetimde şarta bağlı ücret uygulanmaz.",
        "Etik Kurallar Bölüm 410", "hard",
    ),
    r(
        "Denetim şirketi müşterinin muhasebe kayıtlarını tutmuş, yönetim kararlarını almış ve ardından kendi oluşturduğu kayıtları denetlemiştir. Uygun mudur?",
        "Denetim müşterisine denetim dışı hizmet sunarken hangi sorumluluk üstlenilemez?",
        "Hayır; yönetim sorumluluğu ve kendi kendini denetleme tehdidi doğar",
        "Yönetim sorumluluğu",
        ["Evet; hizmet ve denetim aynı ekipçe yürütülmelidir", "Evet; müşteri ücreti ayrı faturalarsa yeterlidir", "Hayır; yalnız kayıtlar elektronikse hizmet yasaktır", "Evet; yönetim kararlarını denetçiye bırakabilir"],
        ["Teknik muhasebe eğitimi vermek", "Kamuya açık bilgi sağlamak", "Yönetimin hazırladığı veriyi denetlemek", "Standart hükümlerini açıklamak"],
        "Denetçi yönetim adına karar alamaz; kendi oluşturduğu kayıtları denetlemek ayrıca kendi kendini denetleme tehdidi yaratır.",
        "Denetim dışı hizmette müşteri yönetimi bütün muhakeme ve karar sorumluluğunu üstlenmelidir.",
        "Etik Kurallar Bölüm 600 ve 601", "hard",
    ),
    r(
        "Aynı kıdemli personelin müşteriyle uzun süre çalışması sonucunda yönetim açıklamalarına aşırı güven gelişmiştir. Denetim şirketi hiçbir değerlendirme yapmadan görevlendirmeyi sürdürmüştür. Uygun mudur?",
        "Personelin denetim müşterisiyle uzun süreli ilişkisi hangi tehditleri artırabilir?",
        "Hayır; yakınlık ve kişisel çıkar tehditleri değerlendirilmeli ve ele alınmalıdır",
        "Yakınlık ve kişisel çıkar tehditlerini",
        ["Evet; uzun çalışma her durumda bağımsızlığı güçlendirir", "Evet; kıdem arttıkça etik değerlendirme gereksizleşir", "Hayır; yalnız denetim ücreti düşürülmelidir", "Evet; müşteri memnunsa personel hiç değiştirilemez"],
        ["Yalnız sır saklama tehdidini", "Sadece mesleki yeterlik tehdidini", "Kendi kendini denetleme riskini her durumda ortadan kaldırır", "Hiçbir tehdidi; deneyim bütün riskleri giderir"],
        "Uzun ilişki aşırı yakınlık, sempati ve müşteriyi kaybetme kaygısı yaratabilir.",
        "Rollerin değiştirilmesi, uygun gözden geçirme veya gerekli rotasyon hükümleri tehdit değerlendirmesine göre uygulanır.",
        "Etik Kurallar Bölüm 540", "hard",
    ),
]


PREMISES = [
    {"stem":"Temel etik ilkeler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dürüstlük açık sözlü ve doğru olmayı gerektirir\n\nII. Tarafsızlık uygunsuz etkilerden kaçınmayı gerektirir\n\nIII. Mesleki yeterlik ve özen güncel bilgi ile titiz çalışmayı içerir","correct":"I, II ve III","why":"Üç ifade de Etik Kurallardaki ilgili temel ilkelerin özünü doğru açıklar.","ref":"Etik Kurallar Bölüm 110-113","difficulty":"easy"},
    {"stem":"Kavramsal çerçeve bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tehditler belirlenir\n\nII. Tehditler değerlendirilir\n\nIII. Kabul edilebilir düzeyde olmayan tehditler ele alınır","correct":"I, II ve III","why":"Belirleme, değerlendirme ve ele alma kavramsal çerçevenin üç zorunlu aşamasıdır.","ref":"Etik Kurallar Bölüm 120","difficulty":"easy"},
    {"stem":"Tehdit sınıfları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kişisel çıkar bir tehdit sınıfıdır\n\nII. Kendi kendini denetleme bir tehdit sınıfıdır\n\nIII. Müşteri memnuniyeti ayrı bir tehdit sınıfıdır","correct":"I ve II","why":"Kişisel çıkar ve kendi kendini denetleme beş tehdit sınıfındandır; müşteri memnuniyeti ayrı sınıf değildir.","ref":"Etik Kurallar par. 120.6","difficulty":"easy"},
    {"stem":"Bağımsızlık bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yalnız denetçinin kendi tarafsızlık kanaati yeterlidir\n\nII. Esasta bağımsızlık korunmalıdır\n\nIII. Şekilde bağımsızlık korunmalıdır","correct":"II ve III","why":"Bağımsızlık hem denetçinin zihnî durumunu hem de makul üçüncü tarafın görünüş değerlendirmesini kapsar.","ref":"Etik Kurallar par. 400.5","difficulty":"medium"},
    {"stem":"Kabul edilebilir düzeyde olmayan tehdide verilecek karşılıklar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tehdidi yaratan durum ortadan kaldırılabilir\n\nII. Tehdit sadece belgelenip değişiklik yapılmadan sürdürülebilir\n\nIII. Uygun önlemlerle tehdit kabul edilebilir düzeye indirilebilir","correct":"I ve III","why":"Belgeleme tek başına karşılık değildir; kaynak ortadan kaldırılır, önlem uygulanır veya faaliyet reddedilir/sona erdirilir.","ref":"Etik Kurallar par. 120.10","difficulty":"medium"},
    {"stem":"Denetim müşterisindeki finansal çıkarlar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ekip üyesinin önemli doğrudan çıkarı serbesttir\n\nII. Doğrudan çıkar kişisel çıkar tehdidi yaratır\n\nIII. Yasaklanan çıkar ortadan kaldırılmalı veya ilgili kişi ekipten çıkarılmalıdır","correct":"II ve III","why":"Denetim ekibinin müşterideki doğrudan çıkarı bağımsızlıkla bağdaşmaz; I yanlıştır.","ref":"Etik Kurallar Bölüm 510","difficulty":"hard"},
    {"stem":"Denetim dışı hizmetler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Denetçi müşteri adına yönetim kararı alamaz\n\nII. Kendi hazırladığı kayıtları denetlemek kendi kendini denetleme tehdidi yaratabilir\n\nIII. Ayrı fatura düzenlenmesi bütün bağımsızlık tehditlerini otomatik giderir","correct":"I ve II","why":"Yönetim sorumluluğu üstlenilemez ve kendi işini denetleme tehdidi değerlendirilir; ayrı fatura tek başına yeterli değildir.","ref":"Etik Kurallar Bölüm 600-601","difficulty":"hard"},
    {"stem":"Uzun ilişki ve hukuki ihtilaflar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Uzun ilişki yakınlık tehdidi yaratabilir\n\nII. Hukuki ihtilaf bağımsızlığı hiçbir koşulda etkilemez\n\nIII. Önemli ihtilaf kişisel çıkar ve yıldırma tehdidi yaratabilir","correct":"I ve III","why":"Uzun ilişki yakınlık, hukuki ihtilaf kişisel çıkar ve yıldırma tehdidi yaratabilir; II yanlıştır.","ref":"Etik Kurallar Bölüm 430 ve 540","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="bagimsizlik_ve_etik",
        label="Bağımsızlık ve Etik", slug="bagimsizlik_ve_etik", prefix="topic-bve",
        seed=2026071748,
        legislation_version="KGK TDS 2026 Seti; Bağımsız Denetçiler İçin Etik Kurallar (Bağımsızlık Standartları Dâhil), 11.08.2025 güncel metin (17.07.2026 kontrolü)",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
