#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Önemlilik ve Örnekleme, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Finansal tablodaki bir yanlışlığın, kullanıcıların ekonomik kararlarını etkilemesi makul ölçüde beklenmektedir. Bu yanlışlık nasıl değerlendirilir?",
        "BDS 320'ye göre bir yanlışlığı önemli kılan temel sonuç hangisidir?",
        "Önemli yanlışlık olarak değerlendirilir",
        "Kullanıcı kararlarını etkileyebilecek makul bir sonuç",
        ["Yalnız yönetim düzeltmeyi reddederse önemli sayılır", "Sadece nakit akışını etkilerse önemli sayılır", "Denetçi bulduğu anda kendiliğinden hile sayılır", "Tutarı ne olursa olsun bariz biçimde önemsiz sayılır"],
        ["Yanlışlığın yalnız dönem sonunda bulunması", "Yönetimin yanlışlığı sözlü olarak kabul etmesi", "İşlemin mutlaka nakit hareketi içermesi", "Yanlışlığın sadece vergi matrahını azaltması"],
        "Önemlilik, yanlışlığın kullanıcıların finansal tablolara dayanarak alacağı ekonomik kararlar üzerindeki makul etkisiyle ilişkilidir.",
        "Bir yanlışlık, tek başına veya diğerleriyle birlikte kullanıcı kararlarını etkileyebilecekse önemli kabul edilir.",
        "BDS 320 par. 2", "easy",
    ),
    r(
        "Tutarı genel önemliliğin altında olan bir ilişkili taraf açıklaması yönetimin çıkar çatışmasını gizlemektedir. Denetçi yalnız tutara bakarak önemsiz diyebilir mi?",
        "Önemlilik yargısını etkileyen unsurların doğru bileşimi hangisidir?",
        "Hayır; yanlışlığın niteliği ve koşulları da değerlendirilir",
        "Büyüklük, nitelik veya ikisinin bileşimi",
        ["Evet; önemlilik yalnız parasal büyüklükle ölçülür", "Evet; açıklama yanlışlıkları önemlilik dışında kalır", "Hayır; bütün ilişkili taraf işlemleri doğrudan hile sayılır", "Evet; genel önemliliğin altındaki her tutar önemsizdir"],
        ["Yalnız işlemin kaydedildiği yevmiye maddesi", "Sadece denetim ücretinin toplam tutarı", "Yalnız yanlışlığın bulunduğu takvim günü", "Sadece işletmenin çalışan sayısı"],
        "Niteliksel özellikler ve ortaya çıkış koşulları, düşük tutarlı bir yanlışlığı dahi önemli hâle getirebilir.",
        "Önemlilik mekanik bir tutar testi değildir; büyüklük, nitelik ve koşullar mesleki muhakemeyle birlikte ele alınır.",
        "BDS 320 par. 2 ve 6", "medium",
    ),
    r(
        "Bir yatırımcının bilgi ihtiyacı diğer bütün kullanıcılardan çok farklıdır. Denetçi önemliliği yalnız bu yatırımcının özel ihtiyacına göre belirlemiştir. Yaklaşım uygun mudur?",
        "Önemlilik belirlenirken kullanıcıların bilgi ihtiyacı hangi düzeyde ele alınır?",
        "Hayır; kullanıcı grubunun ortak ihtiyaçları esas alınır",
        "Kullanıcı grubunun ortak finansal bilgi ihtiyaçları",
        ["Evet; en büyük yatırımcının her özel talebi bağlayıcıdır", "Evet; yalnız işletme yönetiminin bilgi ihtiyacı esastır", "Hayır; hiçbir kullanıcı beklentisi dikkate alınamaz", "Evet; yalnız kredi verenin bireysel ihtiyacı kullanılır"],
        ["Her bireysel kullanıcının birbirinden farklı özel isteği", "Yalnız finans direktörünün raporlama tercihi", "Sadece denetim şirketinin bütçe beklentisi", "İşletmenin rakiplerinin stratejik bilgi ihtiyacı"],
        "İhtiyaçları oldukça farklı olabilen tek tek kullanıcıların özel etkileri yerine ortak bilgi ihtiyaçları değerlendirilir.",
        "Denetçinin yargısı, makul bilgi ve özen varsayımı altındaki kullanıcı grubunun ortak ihtiyaçlarına dayanır.",
        "BDS 320 par. 2 ve 4", "medium",
    ),
    r(
        "Genel önemlilik 500.000 TL'dir. Denetçi bu tutarın altındaki bütün yanlışlıkların her koşulda önemsiz olduğunu kabul etmiştir. Bu kabul doğru mudur?",
        "Planlama önemliliğinin altında kalan bir yanlışlık için hangi ifade doğrudur?",
        "Hayır; düşük tutar nitelik nedeniyle önemli olabilir",
        "Nitelik veya koşullar nedeniyle önemli olabilir",
        ["Evet; altındaki her yanlışlık otomatik olarak önemsizdir", "Evet; altındaki yanlışlıklar çalışma kâğıdına alınamaz", "Hayır; altındaki her yanlışlık otomatik olarak hiledir", "Evet; yalnız toplam tutar tam 500.000 TL olursa incelenir"],
        ["Her durumda çalışma dosyasından çıkarılır", "Yalnız yönetim isterse önemli kabul edilir", "Mutlaka bariz biçimde önemsiz sayılır", "Sadece sonraki döneme taşınır ve cari yıl değerlendirilmez"],
        "Planlama eşiği, altındaki bütün yanlışlıkların kayıtsız şartsız önemsiz sayılacağı katı bir sınır değildir.",
        "Mevzuata aykırılık veya ilişkili taraf açıklaması gibi niteliksel etkenler, daha düşük tutarlı yanlışlığı önemli kılabilir.",
        "BDS 320 par. 6", "medium",
    ),
    r(
        "Denetçi performans önemliliğini genel önemlilikle aynı tutarda belirleyerek tespit edilmemiş yanlışlıklar için hiç marj bırakmamıştır. Uygun mudur?",
        "Performans önemliliğinin genel önemlilikten düşük belirlenmesinin amacı nedir?",
        "Hayır; toplulaştırma riski için daha düşük belirlenir",
        "Toplulaştırma riskini uygun düşük düzeye indirmek",
        ["Evet; iki tutar her denetimde zorunlu olarak eşittir", "Evet; performans önemliliği genel önemlilikten yüksek olmalıdır", "Hayır; performans önemliliği yalnız rapordan sonra belirlenir", "Evet; tespit edilmemiş yanlışlıklar önemlilik hesabına girmez"],
        ["Denetim ücretini genel önemliliğin altına indirmek", "Bütün yanlışlıkları tek tek önemsiz ilan etmek", "Yönetimin düzeltme sorumluluğunu denetçiye devretmek", "Örnekleme dışı riski hiçbir prosedür uygulamadan sıfırlamak"],
        "Performans önemliliği, küçük ve tespit edilmemiş yanlışlıkların toplamının genel önemliliği aşması riskine karşı marj sağlar.",
        "Toplulaştırma riski, düzeltilmemiş ve tespit edilmemiş yanlışlıkların toplamının genel önemliliği aşması olasılığıdır.",
        "BDS 320 par. 9 ve 11; A13", "medium",
    ),
    r(
        "Genel denetim stratejisi hazırlanırken genel önemlilik belirlenmiş; kullanıcılar için hassas olan yönetici ücretleri için daha düşük eşik gerekip gerekmediği hiç değerlendirilmemiştir. Uygun mudur?",
        "Belirli işlem sınıfı, hesap bakiyesi veya açıklama için ayrı önemlilik ne zaman belirlenir?",
        "Hayır; hassas açıklama için daha düşük ayrı önemlilik gerekebilir",
        "Düşük yanlışlık kullanıcı kararını etkileyebiliyorsa",
        ["Evet; yalnız genel önemlilik belirlemek her durumda yeterlidir", "Evet; ayrı önemlilik yalnız nakit hesapları için kullanılır", "Hayır; yönetici ücretleri finansal tablo açıklaması değildir", "Evet; özel önemlilik genel önemlilikten yüksek olmalıdır"],
        ["Yalnız hesap bakiyesi genel önemliliği zaten aşmışsa", "Denetim ücreti yönetimce düşük bulunmuşsa", "İşlem sınıfındaki bütün kalemler tek tek incelenecekse", "Finansal tablo kullanıcıları bu açıklamayı hiç görmeyecekse"],
        "İlişkili taraflar, yönetici ücretleri veya yüksek belirsizlikli tahminler daha düşük özel önemlilik gerektirebilir.",
        "Özel önemlilik, genel eşiğin altındaki yanlışlıkların dahi kullanıcı kararını etkileyebileceği alanlar için belirlenir.",
        "BDS 320 par. 10 ve A11-A12", "hard",
    ),
    r(
        "Denetçi vergi öncesi 8.000.000 TL kârı kıyaslama noktası seçmiş ve mesleki muhakemeyle yüzde 5 uygulamıştır. Bu varsayımlarla genel önemlilik kaç TL'dir?",
        "BDS 320, önemlilik kıyaslama noktasına uygulanacak oranı nasıl belirler?",
        "400.000 TL",
        "Sabit oran yoktur; mesleki muhakeme kullanılır",
        ["40.000 TL", "160.000 TL", "800.000 TL", "1.600.000 TL"],
        ["Her işletme için zorunlu yüzde 1 oranını dayatır", "Bütün kâr amaçlı işletmeler için yüzde 10'u zorunlu kılar", "Oranı yalnız işletme yönetiminin seçmesini ister", "Kıyaslama noktası kullanılmasını tamamen yasaklar"],
        "Sorudaki muhakeme kabulüne göre 8.000.000 × %5 = 400.000 TL'dir; yüzde 5 standartça zorunlu bir oran değildir.",
        "Kıyaslama noktası ve oran işletmenin niteliği, kullanıcı odağı ve verinin oynaklığı gibi etkenlerle mesleki muhakeme kullanılarak seçilir.",
        "BDS 320 par. A4-A8", "medium",
    ),
    r(
        "Denetim sırasında büyük bir faaliyetin satıldığı ve gerçekleşen kârın planlama tahmininden ciddi biçimde farklılaştığı öğrenilmiştir. Denetçi başlangıç önemliliğini aynen koruyabilir mi?",
        "Denetim sırasında daha düşük önemlilik uygun hâle gelirse denetçinin sonraki adımı nedir?",
        "Hayır; önemlilik yeni bilgiye göre değiştirilir",
        "Performans önemliliği ile prosedürlerin uygunluğunu yeniden değerlendirmek",
        ["Evet; planlama tutarı denetim boyunca değiştirilemez", "Evet; değişiklik yalnız sonraki yıl dikkate alınır", "Hayır; denetim otomatik olarak sona erdirilir", "Evet; yalnız yönetim yazılı izin verirse tutar değişir"],
        ["Yalnız denetim ücretini aynı oranda azaltmak", "Uygulanmış bütün prosedürleri kanıtsız geçersiz saymak", "Önemlilik değişikliğini çalışma dosyasından çıkarmak", "Finansal tabloları doğrudan olumsuz görüşle raporlamak"],
        "Başlangıçta farklı bir tutara yol açacak yeni bilgi, önemlilik ve gerekirse özel önemlilik düzeylerinin değiştirilmesini gerektirir.",
        "Daha düşük önemlilik, performans önemliliğini ve prosedürlerin nitelik, zamanlama ve kapsamının yeterliliğini etkileyebilir.",
        "BDS 320 par. 12-13", "hard",
    ),
    r(
        "Bir satış faturası yanlış hesapta sınıflandırılmıştır. Yönetim bunun yalnız tutar hatası olmadığını ileri sürmektedir. BDS 450 bakımından yanlışlık kapsamına girer mi?",
        "BDS 450'de yanlışlık hangi alanlardaki farkları kapsar?",
        "Evet; sınıflandırma farkı da yanlışlıktır",
        "Tutar, sınıflandırma, sunum veya açıklamadaki farklar",
        ["Hayır; yalnız aritmetik tutar farkları yanlışlıktır", "Hayır; sınıflandırma yalnız vergi incelemesinin konusudur", "Evet; ancak sadece nakit hesaplarını etkilerse", "Hayır; yönetim açıklama yapınca yanlışlık ortadan kalkar"],
        ["Yalnız hesap makinesiyle yapılan aritmetik hatalar", "Sadece nakit tahsilat ile ödeme arasındaki farklar", "Yalnız hile olduğu mahkemece kesinleşen tutarlar", "Sadece vergi matrahını doğrudan değiştiren farklar"],
        "Yanlışlık; raporlanan ile çerçeveye göre olması gereken tutar, sınıflandırma, sunum veya açıklama arasındaki farktır.",
        "Eksik açıklama, yanlış sınıflandırma ve uygun olmayan muhasebe politikası uygulaması da yanlışlık oluşturabilir.",
        "BDS 450 par. 4 ve A1", "easy",
    ),
    r(
        "Denetçi yalnız genel önemliliği aşan yanlışlıkları listelemiş, daha küçük bütün yanlışlıkları 'önemsiz' diyerek atmıştır. Uygun mudur?",
        "'Bariz biçimde önemsiz' ifadesi 'önemli değil' ifadesiyle aynı anlama gelir mi?",
        "Hayır; bariz önemsiz dışındaki yanlışlıklar biriktirilir",
        "Hayır; bariz önemsiz, önemli değil kavramından daha dardır",
        ["Evet; yalnız genel önemliliği aşanlar biriktirilir", "Evet; küçük yanlışlıklar birbirleriyle hiçbir zaman toplanmaz", "Hayır; denetçi her kuruş farkı raporda ayrı görüşe dönüştürür", "Evet; yönetimin önemsiz dediği her kalem dosyadan çıkarılır"],
        ["Evet; iki ifade standartta tamamen eş anlamlıdır", "Evet; her ikisi yalnız yönetimce belirlenen eşiği anlatır", "Hayır; bariz önemsiz kalemler mutlaka önemli yanlışlıktır", "Evet; iki kavram da yalnız hile kaynaklı farkları kapsar"],
        "Biriktirme yükümlülüğünün istisnası genel önemliliğin altı değil, açıkça dikkate değmeyecek bariz önemsiz kalemlerdir.",
        "Kalemin bariz önemsiz olup olmadığı konusunda belirsizlik varsa kalem bu kategoriye alınamaz.",
        "BDS 450 par. 5 ve A2", "medium",
    ),
    r(
        "Biriktirilen yanlışlıklar toplamı önemliliğe yaklaşmış ve aynı süreçte başka yanlışlıklar olabileceğine işaret eden ortak özellikler görülmüştür. Denetçi ne yapmalıdır?",
        "Denetim stratejisi ve planının revizyonunu tetikleyebilecek durum hangisidir?",
        "Strateji ve planı revize edip etmemeye karar vermelidir",
        "Toplamın eşiğe yaklaşması veya ek yanlışlık ihtimali",
        ["Bütün yanlışlıkları artık bariz önemsiz saymalıdır", "Yalnız yönetimin sözlü açıklamasını alıp çalışmayı bitirmelidir", "Önemliliği yanlışlık toplamının üzerine mekanik olarak yükseltmelidir", "Raporu doğrudan olumlu görüşle tamamlamalıdır"],
        ["Denetim ekibinin çalışma saatinin bütçeyi aşması", "Yönetimin denetim ücretini zamanında ödemesi", "Finansal tabloların yazı tipinin değiştirilmesi", "İşletmenin reklam bütçesini azaltması"],
        "Toplamın eşiğe yaklaşması tespit edilmemiş yanlışlık marjını daraltır; ortak özellikler de başka yanlışlık ihtimalini gösterebilir.",
        "BDS 450 hem yanlışlıkların niteliği ve koşullarını hem de birikmiş toplamın önemliliğe yakınlığını plan revizyonu açısından ele alır.",
        "BDS 450 par. 6", "hard",
    ),
    r(
        "Denetçinin talebi üzerine yönetim alacak bakiyesini inceleyip bulunan yanlışlıkları düzeltmiştir. Denetçi düzeltmeyi görüp başka işlem yapmadan alanı kapatmıştır. Yeterli midir?",
        "Yönetim bir işlem sınıfını inceleyip yanlışlıkları düzelttiğinde denetçi ne yapar?",
        "Hayır; kalan yanlışlıklar için ilave prosedür uygular",
        "Kalan yanlışlığı araştıran ilave denetim prosedürleri uygular",
        ["Evet; yönetim düzeltmesi bütün kanıt ihtiyacını kaldırır", "Evet; düzeltmeden sonra aynı alanda prosedür uygulanamaz", "Hayır; bütün alacakları finansal tablodan çıkarır", "Evet; yalnız yönetim kurulu kararı alınırsa yeniden test eder"],
        ["Yalnız düzeltme nedeniyle denetim ücretini artırır", "İncelemeyi gelecek hesap dönemine erteler", "Yönetimin yaptığı düzeltmeyi kanıtsız olarak geri alır", "Alanı hiçbir değerlendirme yapmadan denetim kapsamından çıkarır"],
        "Yönetimin inceleme ve düzeltmesi, aynı alanda başka yanlışlık kalmadığını kendiliğinden kanıtlamaz.",
        "Denetçi kalan yanlışlık bulunup bulunmadığını uygun ilave prosedürlerle değerlendirir.",
        "BDS 450 par. 7", "medium",
    ),
    r(
        "Denetçi biriktirdiği yanlışlıkları rapor tarihine kadar yönetimden gizlemiş ve düzeltme istememiştir. Mevzuatla bildirim yasağı da yoktur. Uygun mudur?",
        "Biriktirilen yanlışlıkların yönetime bildirilmesinde doğru yaklaşım hangisidir?",
        "Hayır; yönetime zamanında bildirip düzeltme istemelidir",
        "Uygun kademeye zamanında bildirim ve düzeltme talebi",
        ["Evet; yanlışlıklar yalnız rapor yayımlandıktan sonra açıklanır", "Evet; denetçi düzeltme talep edemez", "Hayır; yalnız en küçük yanlışlık yönetimle paylaşılır", "Evet; bütün bildirimler yalnız sözleşme öncesinde yapılır"],
        ["Rapor yayımlandıktan sonra ilk kez bildirim yapmak", "Yanlışlıkları yalnız denetim ekibi içinde tutmak", "Yönetimden düzeltme yapmamasını talep etmek", "Bildirimi finansal tablo kullanıcılarından birine rastgele yapmak"],
        "Zamanında bildirim yönetimin nedenleri araştırmasına, düzeltme yapmasına ve kayıtları iyileştirmesine imkân verir.",
        "Mevzuatla yasaklanmadıkça denetçi biriktirilen yanlışlıkları uygun yönetim kademesine zamanında bildirir ve düzeltilmesini ister.",
        "BDS 450 par. 8", "easy",
    ),
    r(
        "Yönetim bildirilen önemli yanlışlığı düzeltmeyi reddetmiş, denetçi gerekçeyi öğrenmeden bu kararı etkisiz saymıştır. Yaklaşım uygun mudur?",
        "Yönetim düzeltmeyi reddederse denetçi bu reddi nasıl ele alır?",
        "Hayır; reddin gerekçesi genel değerlendirmeye alınır",
        "Yönetimin gerekçesi hakkında kanaat edinip önemli yanlışlık değerlendirmesine katar",
        ["Evet; yönetimin gerekçesi denetim açısından hiçbir önem taşımaz", "Evet; ret yanlışlığı otomatik olarak önemsiz yapar", "Hayır; denetçi finansal tabloları yönetim adına düzeltir", "Evet; ret her durumda denetimin hemen çekilmesini gerektirir"],
        ["Reddin yanlışlığı kendiliğinden ortadan kaldırdığını kabul eder", "Yönetimin gerekçesini çalışma dosyasına almadan yok sayar", "Ret üzerine önemliliği otomatik olarak iki katına çıkarır", "Bütün diğer düzeltilmiş yanlışlıkları tekrar finansal tabloya ekler"],
        "Reddin gerekçesi yönetimin finansal raporlama çerçevesini uygulama anlayışı ve taraflılığı hakkında bilgi sağlayabilir.",
        "Denetçi gerekçeyi anlar ve finansal tabloların bütün olarak önemli yanlışlık içerip içermediğine ilişkin sonucunda kullanır.",
        "BDS 450 par. 9 ve A13", "hard",
    ),
    r(
        "Planlamada tahminî kâra göre belirlenen önemlilik, dönem sonunda gerçekleşen kârın ciddi düşüşü nedeniyle yüksek kalmıştır. Denetçi düzeltilmemiş yanlışlıkları eski tutarla değerlendirebilir mi?",
        "Düzeltilmemiş yanlışlıkların etkisi değerlendirilmeden hemen önce ne doğrulanır?",
        "Hayır; önemlilik fiili sonuçlar kapsamında yeniden değerlendirilir",
        "Önemliliğin fiili sonuçlara göre geçerliliği",
        ["Evet; önemlilik ilk belirlendiği anda değiştirilemez", "Evet; fiili sonuçlar yalnız sonraki yıl kullanılır", "Hayır; bütün yanlışlıklar tutarına bakılmaksızın önemli sayılır", "Evet; yönetim eski tutarı onaylarsa yeniden değerlendirme gerekmez"],
        ["Denetim ücretinin yönetimce tam ödendiği", "Bütün yanlışlıkların hileden kaynaklandığı", "Örneklemdeki her kalemin yönetimce seçildiği", "Finansal tabloların aynı yazılımda hazırlandığı"],
        "Tahmin ile fiili sonuç arasındaki önemli fark, planlama önemliliğinin revizyonunu gerektirebilir.",
        "BDS 450, son değerlendirmeden önce önemliliğin fiili sonuçlar ışığında geçerliliğinin yeniden ele alınmasını ister.",
        "BDS 450 par. 10; A14-A15", "medium",
    ),
    r(
        "Cari dönemde küçük görünen yanlışlık, önceki dönemden taşınan düzeltilmemiş yanlışlıkla birlikte kullanıcı kararını etkileyebilecek düzeye ulaşmaktadır. Önceki dönem etkisi yok sayılabilir mi?",
        "Düzeltilmemiş yanlışlıkların önemliliği değerlendirilirken hangi boyutlar birlikte ele alınır?",
        "Hayır; önceki dönem yanlışlıklarının etkisi de incelenir",
        "Büyüklük, nitelik, koşullar ve önceki dönem etkisi",
        ["Evet; her dönem bütünüyle yalıtılmış değerlendirilir", "Evet; yalnız cari dönemin en büyük tek yanlışlığı ele alınır", "Hayır; önceki dönem kalemi otomatik hile sayılır", "Evet; geçmiş yanlışlıklar yalnız yönetim isterse dikkate alınır"],
        ["Yalnız yanlışlığın bulunduğu hesabın kod numarası", "Sadece denetim ekibinin kıdem dağılımı", "Yalnız yönetimin düzeltme için ayırdığı bütçe", "Sadece finansal tabloların hazırlanma süresi"],
        "Düzeltilmemiş yanlışlıklar tek başına ve toplu değerlendirilirken geçmiş dönem birikiminin cari tabloya etkisi de hesaba katılır.",
        "Miktar tek ölçüt değildir; nitelik, ortaya çıkış koşulları ve geçmiş dönem etkileri birlikte mesleki muhakemeye girer.",
        "BDS 450 par. 11", "hard",
    ),
    r(
        "Düzeltilmemiş yanlışlıklar üst yönetimden sorumlu olanlara bildirilmiş; ancak denetçi önemli kalemleri tek tek tanımlamamış ve düzeltme talep etmemiştir. Yeterli midir?",
        "Düzeltilmemiş yanlışlıklarla ilgili yazılı beyanda ne bulunur?",
        "Hayır; önemli kalemler ayrı tanımlanıp düzeltilmesi istenir",
        "Kalem özeti ile tekil ve toplu etkilerin önemsizliği kanaati",
        ["Evet; yalnız toplam tutarın söylenmesi her durumda yeterlidir", "Evet; üst yönetimden sorumlu olanlardan düzeltme istenemez", "Hayır; bütün kalemler denetçi tarafından muhasebeleştirilmelidir", "Evet; bildirim yalnız önceki dönem yanlışlıklarını kapsar"],
        ["Denetçinin bütün yanlışlıkları düzelttiğine ilişkin yönetim kanaati", "Yanlışlıkların hiçbirinin çalışma kâğıdına alınmadığı beyanı", "Yalnız denetim ücretinin makul bulunduğuna ilişkin açıklama", "Kalemlerin tamamının otomatik olarak hile sayıldığı beyanı"],
        "Üst yönetim iletişimi, düzeltilmemiş önemli yanlışlıkları ayrı tanımlar ve görüşe muhtemel etkileriyle birlikte düzeltme talebini içerir.",
        "Yönetim ve uygun hâllerde üst yönetimden sorumlu olanlar, düzeltilmemiş kalemlerin tek başına ve toplu etkisine ilişkin yazılı kanaat verir; özet eklenir.",
        "BDS 450 par. 12-14", "hard",
    ),
    r(
        "Denetçi 10.000 işlemden 200'ünü, her işleme seçilme şansı vererek test etmiş ve sonuçları anakitleye genellemeyi amaçlamıştır. Bu uygulama nedir?",
        "Denetim örneklemesinin temel amacı hangisidir?",
        "Denetim örneklemesi",
        "Örneklemden anakitle hakkında makul sonuç çıkarmak",
        ["Yüzde yüz inceleme", "Yalnız belirli kalem seçimi", "Analitik prosedür", "Yönetim sorgulaması"],
        ["Sadece seçilen 200 işlem hakkında rapor yazmak", "Anakitleyi incelemeden bütünü doğru kabul etmek", "Yönetimin örnek sonucunu değiştirmesine izin vermek", "Örnekleme riskini her koşulda tamamen ortadan kaldırmak"],
        "Anakitlenin yüzde 100'ünden azına prosedür uygulanmış, birimlere seçilme şansı verilmiş ve genelleme amaçlanmıştır.",
        "Örnekleme, test edilen kalemlerin ötesinde anakitle hakkında makul bir sonuca dayanak oluşturur.",
        "BDS 530 par. 4-5", "easy",
    ),
    r(
        "Örneklem kalemleri rastgele seçilmiş; ancak sonuçların değerlendirilmesinde olasılık teorisi kullanılmamıştır. Yaklaşım istatistiki örnekleme midir?",
        "İstatistiki örneklemenin birlikte taşıması gereken iki özellik hangisidir?",
        "Hayır; bu, istatistiki olmayan örneklemedir",
        "Rastgele seçim ve olasılık teorisiyle değerlendirme",
        ["Evet; rastgele seçim tek başına yeterlidir", "Evet; örneklem yüz kalemden büyükse istatistikidir", "Hayır; istatistiki örnekleme denetimde kullanılamaz", "Evet; yönetim örneklemi onayladıysa istatistikidir"],
        ["Büyük örneklem ve bütün kalemlerin yüksek tutarlı olması", "Gelişigüzel seçim ve yönetimin sonuçları onaylaması", "Sistematik seçim ve yüzde yüz inceleme yapılması", "Mesleki muhakeme kullanılmaması ve tek kalem seçilmesi"],
        "Rastgele seçim koşulunun tek başına bulunması yaklaşımı istatistiki hâle getirmez.",
        "İstatistiki örnekleme hem rastgele seçimi hem de örnekleme riskinin ölçümü dâhil olasılık teorisini gerektirir.",
        "BDS 530 par. 5", "medium",
    ),
    r(
        "Örnekleme dayanılarak kontroller gerçekte olduğundan daha etkin bulunmuştur. Bu sonuç hangi risk türü ve hangi etkiyle ilişkilidir?",
        "Örnekleme riski hangi durumu ifade eder?",
        "Örnekleme riski; denetim etkinliğini etkileyebilir",
        "Örneklem ile anakitle sonuçlarının farklılaşması",
        ["Örnekleme dışı risk; yalnız denetim verimliliğini etkiler", "Yapısal risk; her durumda görüşü olumlu etkiler", "Kontrol riski; örneklem büyüklüğünden bağımsızdır", "İşletme riski; yalnız yönetimin bütçesini etkiler"],
        ["Örneklem sonucunun anakitle sonucuyla her zaman aynı olması", "Yönetimin denetim ücretini zamanında ödememesi", "Denetçinin uygun prosedürü yanlış yorumlaması", "Anakitlenin finansal tablolarda açıklanmaması"],
        "Kontrolü gerçekte olduğundan etkin bulmak, uygun olmayan görüş riskine uzanabilen örnekleme kaynaklı hatalı sonuçtur.",
        "Örnekleme riski, seçilen alt kümeden varılan sonuçla anakitlenin tamamına uygulanacak prosedür sonucunun farklılaşmasıdır.",
        "BDS 530 par. 5", "hard",
    ),
    r(
        "Denetçi uygun olmayan bir prosedür seçmiş ve elde ettiği kanıtı yanlış yorumlamıştır. Bu hatalar örnekleme riskine mi girer?",
        "Örnekleme dışı riske örnek olan durum hangisidir?",
        "Hayır; bunlar örnekleme dışı risk örnekleridir",
        "Uygunsuz prosedür veya kanıtın yanlış yorumlanması",
        ["Evet; her denetçi hatası örnekleme riskidir", "Evet; yalnız örneklem büyütülerek tamamen giderilir", "Hayır; bu durumlar hiçbir denetim riski doğurmaz", "Evet; sadece istatistiki örneklemede görülür"],
        ["Örneklem sonucunun anakitle sonucundan farklı çıkması", "Seçilen örneklemin temsili olmaması", "Örnekleme riskinin kabul edilen seviyeyi aşması", "Örneklemde tesadüfen çok az sapma bulunması"],
        "Risk, örneklemin temsilinden değil denetçinin prosedür seçimi veya kanıt yorumundaki hatadan doğmaktadır.",
        "Örnekleme dışı risk, örnekleme riskinden başka bir nedenle hatalı denetim sonucuna ulaşılmasıdır.",
        "BDS 530 par. 5 ve A1", "easy",
    ),
    r(
        "Denetçi satışların tamlığını test etmek için eksik olduğu bilinen bir satış listesine dayanarak örneklem kurmuştur. Tasarım uygun mudur?",
        "Örneklem tasarlanırken hangi iki unsur öncelikle değerlendirilir?",
        "Hayır; amaca uygun tam anakitle hakkında kanıt elde edilmelidir",
        "Prosedürün amacı ve anakitlenin özellikleri",
        ["Evet; eksik anakitle seçimin doğruluğunu etkilemez", "Evet; yalnız örneklem sayısı yüksekse anakitle önemsizdir", "Hayır; satışlar üzerinde örnekleme kullanmak yasaktır", "Evet; yönetim listeyi imzaladığında tamlık kanıtlanır"],
        ["Denetim ücreti ve ekibin yıllık izin planı", "Yönetimin tercih ettiği cevap ve rapor tarihi", "Örneklerin dosya sırası ve yazı tipi", "İşletmenin reklam bütçesi ve çalışan sayısı"],
        "Eksik anakitleden temsili örneklem seçilse dahi tamlık yönetim beyanı hakkında güvenilir genelleme yapılamaz.",
        "Tasarımda prosedür amacı, sapma veya yanlışlığın tanımı, anakitlenin uygunluğu ve tamlığı birlikte ele alınır.",
        "BDS 530 par. 6 ve A4-A7", "hard",
    ),
    r(
        "Denetçi kabul etmek istediği örnekleme riskini düşürmüş, fakat örneklem büyüklüğünü de azaltmıştır. Bu yön doğru mudur?",
        "Kabul edilebilir örnekleme riski azaldığında gerekli örneklem büyüklüğü genel olarak nasıl değişir?",
        "Hayır; daha düşük risk için örneklem büyüklüğü artırılır",
        "Artar",
        ["Evet; risk azaldıkça örneklem de azalır", "Evet; risk ile örneklem arasında hiçbir ilişki yoktur", "Hayır; her durumda yüzde yüz inceleme zorunludur", "Evet; yalnız istatistiki olmayan örneklem küçülür"],
        ["Azalır", "Değişmeden kalmak zorundadır", "Önce sıfıra iner sonra artar", "Yalnız yönetim isterse değişir"],
        "Daha düşük kabul edilebilir örnekleme riski daha fazla kanıt, dolayısıyla genellikle daha büyük örneklem gerektirir.",
        "Örneklem büyüklüğü istatistiki formülle veya mesleki muhakemeyle belirlenebilir; risk azaldıkça gerekli büyüklük artar.",
        "BDS 530 par. 7 ve A10-A11", "easy",
    ),
    r(
        "Denetçi yalnız kolay erişilen ilk 50 faturayı seçmiş ve anakitlenin diğer birimlerine hiçbir seçilme şansı vermemiştir. Uygun mudur?",
        "Örneklem kalemlerinin seçiminde temel koşul hangisidir?",
        "Hayır; her örnekleme birimine seçilme şansı verilmelidir",
        "Her örnekleme birimine seçilme şansı verilmesi",
        ["Evet; ilk kalemler her zaman temsili kabul edilir", "Evet; kolaylık seçim yanlılığını ortadan kaldırır", "Hayır; denetçi yalnız en düşük tutarlı kalemleri seçmelidir", "Evet; liste sırası yönetimce belirlendiyse seçim geçerlidir"],
        ["Yalnız yüksek tutarlı kalemlerin seçilme şansına sahip olması", "Seçimin bütünüyle işletme yönetimine bırakılması", "Kalemlerin yalnız dönem başından seçilmesi", "Her kalemin aynı tutarda ve aynı tarihte olması"],
        "Kolay erişilen ardışık kalemler sistematik yanlılık taşıyabilir ve tüm birimlere seçilme şansı vermez.",
        "Seçim yanlılıktan uzak ve anakitlenin tipik özelliklerini temsil edecek biçimde yapılır.",
        "BDS 530 par. 8 ve A12-A13", "medium",
    ),
    r(
        "Seçilen iptal edilmiş çek prosedür amacına uygulanabilir değildir; denetçi uygun bir ikame kalem seçmiştir. Başka bir seçili kalemde ise belge kayıp ve hiçbir alternatif prosedür uygulanamamıştır. İkinci kalem nasıl ele alınır?",
        "Seçilen kaleme tasarlanan veya uygun alternatif prosedür uygulanamazsa sonuç nasıl sınıflandırılır?",
        "Kontrol testinde sapma, detay testinde yanlışlık",
        "Kontrol testinde sapma; detay testinde yanlışlık",
        ["Her iki testte de kanıtsız olarak doğru kabul edilir", "Kalem örneklemden sessizce çıkarılır ve yerine hiç seçim yapılmaz", "Yalnız yönetimin sözlü beyanıyla test edilmiş sayılır", "Her iki testte de otomatik anomali kabul edilir"],
        ["Her iki testte de kesinlikle doğru kalem", "Kontrol testinde yanlışlık; detay testinde sapma", "Her iki testte de örneklem dışı kalem", "Yalnız yönetim isterse sapma veya yanlışlık"],
        "Uygulanamaz kalem uygun ikameyle test edilebilir; fakat tasarlanan ve alternatif prosedürlerin ikisi de uygulanamazsa olumsuz sonuç varsayılır.",
        "BDS 530, kanıt elde edilemeyen seçili kalemi kontrol testinde sapma, detay testinde yanlışlık sayar.",
        "BDS 530 par. 9-11; A14-A16", "hard",
    ),
    r(
        "Detay testi örnekleminde bulunan yanlışlık anakitleye öngörülmemiş; tek bir sıra dışı kalem de hiçbir ek kanıt olmadan anomali sayılmıştır. Yaklaşım uygun mudur?",
        "Örneklem sonuçları anakitle hakkında makul dayanak sağlamıyorsa denetçinin uygun karşılığı hangisidir?",
        "Hayır; öngörü ve anomali için ek kanıt gerekir",
        "Ek kanıt, daha büyük örneklem veya uyarlanmış prosedür",
        ["Evet; örneklemdeki yanlışlık yalnız seçilen kalemi etkiler", "Evet; denetçi istediği her farkı kanıtsız anomali sayabilir", "Hayır; bulunan yanlışlık bütün anakitle tutarı kadar kaydedilir", "Evet; sonuç değerlendirmesi yalnız kontrol testlerinde yapılır"],
        ["Anakitleyi hiçbir ek kanıt olmadan doğru kabul etmek", "Bütün örneklem sonuçlarını çalışma dosyasından çıkarmak", "Yönetimden örnekleme riskini sıfırlayan sözlü beyan almak", "Kabul edilebilir yanlışlığı sonuçtan sonra sınırsız artırmak"],
        "Detay testi yanlışlıkları anakitleye öngörülür; anomali sonucuna ancak anakitleyi temsil etmediğine ilişkin yüksek kesinlik ve ek kanıtla varılır.",
        "Makul dayanak yoksa daha fazla yanlışlığın araştırılması istenebilir veya prosedürlerin nitelik, zamanlama ve kapsamı uyarlanabilir.",
        "BDS 530 par. 12-15; A17-A23", "hard",
    ),
]


PREMISES = [
    {"stem":"Önemlilik bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kullanıcıların ortak bilgi ihtiyaçları dikkate alınır\n\nII. Yanlışlığın niteliği önemlilik yargısını hiçbir koşulda etkilemez\n\nIII. Genel eşiğin altındaki bir yanlışlık niteliksel nedenle önemli olabilir","correct":"I ve III","why":"Ortak kullanıcı ihtiyaçları ve nitelik dikkate alınır; genel eşiğin altındaki bazı yanlışlıklar da önemli olabilir.","ref":"BDS 320 par. 2, 4 ve 6","difficulty":"medium"},
    {"stem":"Performans önemliliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Genel önemlilikle her durumda aynı tutarda belirlenir\n\nII. Toplulaştırma riskini azaltmayı amaçlar\n\nIII. Belirlenmesi mesleki muhakeme gerektirir","correct":"II ve III","why":"Performans önemliliği genel eşikten düşüktür, toplulaştırma riskine karşı marj sağlar ve mesleki muhakemeyle belirlenir.","ref":"BDS 320 par. 9 ve A13","difficulty":"medium"},
    {"stem":"Denetim sırasında önemlilik bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yeni bilgi önemliliğin değiştirilmesini gerektirebilir\n\nII. Daha düşük önemlilikte performans önemliliği yeniden ele alınabilir\n\nIII. Prosedürlerin nitelik, zamanlama ve kapsamının uygunluğu yeniden değerlendirilir","correct":"I, II ve III","why":"Yeni bilgi önemlilik tutarlarını, performans önemliliğini ve planlanmış ya da uygulanmış prosedürlerin yeterliliğini etkileyebilir.","ref":"BDS 320 par. 12-13","difficulty":"hard"},
    {"stem":"Belirlenen yanlışlıklar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bariz önemsiz olanlar dışındaki yanlışlıklar biriktirilir\n\nII. Birikmiş toplam önemliliğe yaklaşırsa plan revizyonu değerlendirilir\n\nIII. Yönetim düzeltince kalan yanlışlık için hiçbir prosedür uygulanmaz","correct":"I ve II","why":"Biriktirme ve gerekirse plan revizyonu gerekir; yönetimin düzeltmesinden sonra kalan yanlışlık bulunup bulunmadığı ek prosedürle sınanır.","ref":"BDS 450 par. 5-7","difficulty":"medium"},
    {"stem":"Düzeltilmemiş yanlışlıklar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Büyüklük ve nitelik birlikte değerlendirilir\n\nII. Önceki dönem yanlışlıklarının etkisi dikkate alınır\n\nIII. Önemli kalemler üst yönetimden sorumlu olanlara yalnız toplam hâlinde ve isimsiz bildirilir","correct":"I ve II","why":"Nihai değerlendirme miktar, nitelik, koşullar ve geçmiş dönem etkisini kapsar; önemli yanlışlıklar iletişimde münferit olarak tanımlanır.","ref":"BDS 450 par. 11-13","difficulty":"hard"},
    {"stem":"İstatistiki örnekleme bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Büyük örneklem tek başına yaklaşımı istatistiki yapar\n\nII. Örneklem kalemleri rastgele seçilir\n\nIII. Sonuçlar olasılık teorisi kullanılarak değerlendirilir","correct":"II ve III","why":"Rastgele seçim ile olasılık teorisi birlikte gerekir; örneklemin yalnız büyük olması sınıflandırma ölçütü değildir.","ref":"BDS 530 par. 5 ve A9","difficulty":"medium"},
    {"stem":"Örneklem büyüklüğü ve seçim bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kabul edilebilir risk azaldıkça gerekli örneklem büyür\n\nII. Yalnız yüksek tutarlı örnekleme birimlerine seçilme şansı verilir\n\nIII. Seçim anakitlenin tipik özelliklerini temsil edecek biçimde yanlılıktan uzak yapılır","correct":"I ve III","why":"Daha düşük risk daha büyük örneklem gerektirir; yalnız yüksek tutarlılara şans vermek yerine temsili ve yanlılıktan uzak seçim yapılır.","ref":"BDS 530 par. 7-8; A10-A13","difficulty":"medium"},
    {"stem":"Örneklemde bulunan yanlışlık ve sapmalar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Nitelik ve sebepleri araştırılır\n\nII. Detay testi yanlışlıkları anakitleye öngörülür\n\nIII. Anomali sonucu anakitleyi temsil etmediğine ilişkin güçlü kanıt gerektirir","correct":"I, II ve III","why":"BDS 530 neden analizi, detay testinde öngörü ve anomali için yüksek kesinlik sağlayan ilave kanıt ister.","ref":"BDS 530 par. 12-15","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="onemlilik_ve_ornekleme",
        label="Önemlilik ve Örnekleme", slug="onemlilik_ve_ornekleme", prefix="topic-oo",
        seed=2026071760,
        legislation_version="KGK TDS 2026 Seti; BDS 320, BDS 450 ve BDS 530, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
