#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Denetim Temelleri, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Denetçi, finansal tabloların bir bütün olarak hata veya hile kaynaklı önemli yanlışlık içerip içermediği hakkında yüksek düzeyde güvence elde etmeyi planlamaktadır. Hedeflenen güvence türü nedir?",
        "Finansal tablo denetiminde denetçinin birinci genel amacı aşağıdakilerden hangisidir?",
        "Makul güvence",
        "Önemli yanlışlıklar için makul güvence elde etmek",
        ["Mutlak güvence", "Sınırlı güvence", "Hiç güvence vermeyen derleme", "Yalnız yönetim güvencesi"],
        ["İşletmenin gelecekte zarar etmeyeceğini garanti etmek", "Bütün hata ve hileleri tutarına bakmadan bulmak", "Yönetimin iç kontrol sorumluluğunu devralmak", "Finansal tabloları işletme adına hazırlamak"],
        "BDS 200'e göre finansal tablo denetimi yüksek, fakat mutlak olmayan makul güvence sağlar.",
        "Amaç, finansal tabloların bütünü için hata veya hile kaynaklı önemli yanlışlık riskini kabul edilebilir düşük düzeye indirmektir.",
        "BDS 200 par. 5 ve 11", "easy",
    ),
    r(
        "Yönetim denetçiden finansal tablolarda hiçbir yanlışlık bulunmadığını kesin biçimde garanti etmesini istemiştir. Denetçi bu talebi kabul edebilir mi?",
        "Bağımsız denetimin mutlak güvence sağlayamamasının temel nedeni nedir?",
        "Hayır; denetim makul, mutlak olmayan güvence sağlar",
        "Denetim riski yapısal kısıtlar nedeniyle sıfırlanamaz",
        ["Evet; yeterli ücret ödenirse mutlak güvence verilir", "Evet; yönetim yazılı beyan sunarsa bütün risk kalkar", "Hayır; bağımsız denetim hiçbir güvence sağlamaz", "Evet; yalnız halka açık şirketlerde garanti mümkündür"],
        ["Denetçinin finansal raporlama çerçevesini seçememesi", "Bütün finansal bilgilerin kamuya açık olması", "Yönetimin her yanlışlığı önceden bildirmesi", "Örnekleme kullanımının standartlarca tamamen yasaklanması"],
        "Mesleki muhakeme, örnekleme, muhasebe tahminleri ve kanıtın ikna edici niteliği gibi kısıtlar mutlak güvenceyi engeller.",
        "Makul güvence, denetim riskinin kabul edilebilir düşük düzeye indirilmesidir; sıfır risk anlamına gelmez.",
        "BDS 200 par. 5, A45-A52", "medium",
    ),
    r(
        "Denetçi önemli yanlışlık riskini değerlendirmiş ve yeterli prosedürlerle tespit edememe riskini azaltmıştır. Bu bileşenlerin birleşimi hangi kavramı oluşturur?",
        "Denetim riski aşağıdakilerden hangisini ifade eder?",
        "Denetim riski",
        "Önemli yanlışlık varken uygun olmayan görüş verme riski",
        ["İş hayatı riski", "Kontrol ortamı", "Örnekleme aralığı", "Muhasebe tahmini"],
        ["İşletmenin ticari hedeflerine ulaşamaması riski", "Denetim ücretinin tahsil edilememesi riski", "Yönetimin bütçe hedefini aşması riski", "Finansal tablolar doğruyken işletmenin zarar etmesi riski"],
        "Denetim riski, önemli yanlışlık riski ile tespit edememe riskinin bir fonksiyonudur.",
        "Risk, önemli yanlışlık bulunan tablolara uygun olmayan denetim görüşü verilmesi ihtimalidir.",
        "BDS 200 par. 13 ve A34-A44", "medium",
    ),
    r(
        "Denetçi, bütün bakiyeleri tek tek incelemeden risk odaklı prosedürler ve örnekleme kullanmıştır. Bu durum tek başına standartlara aykırılık mıdır?",
        "Denetimin yapısal kısıtlamaları bakımından denetim kanıtının niteliği genellikle nasıldır?",
        "Hayır; her bakiyeyi incelemeden de yeterli ve uygun kanıt sağlanabilir",
        "Kesin kanıt olmaktan çok ikna edici niteliktedir",
        ["Evet; her işlem yüzde yüz incelenmelidir", "Evet; örnekleme yalnız vergi denetiminde kullanılabilir", "Hayır; hiçbir kanıt toplamadan görüş verilebilir", "Evet; risk değerlendirmesi kanıtın yerini alamaz"],
        ["Her durumda matematiksel olarak kesin niteliktedir", "Yalnız yönetimin sözlü açıklamalarından oluşur", "Sadece işletme dışından elde edilebilir", "Denetim görüşünden sonra toplanır"],
        "BDS'ler bütün işlemlerin incelenmesini değil, denetim riskini düşürecek yeterli ve uygun kanıtın elde edilmesini gerektirir.",
        "Denetim kanıtı çoğunlukla birikimli ve ikna edicidir; bu da makul güvence modelinin parçasıdır.",
        "BDS 200 par. A45-A52; BDS 500", "medium",
    ),
    r(
        "Denetçi yalnız küçük tutarlı ve kullanıcı kararlarını etkilemeyecek yanlışlıklar belirlemiştir. Denetim amacı bakımından her yanlışlık aynı ağırlıkta mıdır?",
        "Bir yanlışlığın önemli kabul edilmesinde temel ölçüt nedir?",
        "Hayır; denetim önemli yanlışlıklara odaklanır",
        "Kullanıcı kararlarını etkileme potansiyeli",
        ["Evet; bir kuruşluk fark bile görüşü zorunlu değiştirir", "Hayır; yalnız hile kaynaklı yanlışlıklar önemlidir", "Evet; sadece tutarına bakılmaksızın bütün farklar eşittir", "Hayır; yönetimin düzelttiği hiçbir hata kayda alınmaz"],
        ["Yalnız yanlışlığın hangi hesapta bulunduğu", "Sadece yönetimin yanlışlığı kabul edip etmemesi", "Denetim ücretinin toplam içindeki payı", "İşletmenin çalışan sayısı"],
        "Bağımsız denetim finansal tabloların bütünü açısından önemli yanlışlıklara odaklanır.",
        "Önemlilik hem tutar hem nitelik ve koşullar dikkate alınarak kullanıcı kararları üzerinden değerlendirilir.",
        "BDS 200 par. 6; BDS 320", "easy",
    ),
    r(
        "Yönetim karmaşık bir işlemin muhasebesini güçlü biçimde savunmuştur. Denetçi açıklamayı sorgulamadan kabul etmiş ve çelişkili kanıt aramamıştır. Hangi temel tutum zedelenmiştir?",
        "Mesleki şüphecilik aşağıdakilerden hangisini gerektirir?",
        "Mesleki şüphecilik",
        "Kanıtı sorgulayıcı bir zihinle değerlendirmek",
        ["Mesleki gizlilik", "Mutlak tarafsızlık beyanı", "Yönetim sorumluluğu", "Dış teyit zorunluluğu"],
        ["Yönetimin bütün açıklamalarını peşinen yanlış saymak", "Denetim prosedürlerini kanıt olmadan azaltmak", "Sadece geçmiş yıl sonuçlarına güvenmek", "Her koşulda suçlayıcı bir yaklaşım benimsemek"],
        "Denetçi yönetimin dürüst olduğunu geçmişte görmüş olsa da mesleki şüpheciliği sürdürür.",
        "Şüphecilik ne kör güven ne de peşin suçlamadır; kanıtın eleştirel değerlendirilmesidir.",
        "BDS 200 par. 15 ve A20-A24", "medium",
    ),
    r(
        "Denetçi, karmaşık tahmin için hangi uzmanlığın kullanılacağına ve elde edilen kanıtın yeterli olup olmadığına karar vermiştir. Hangi mesleki yetkinliği kullanmaktadır?",
        "Mesleki muhakeme denetimde hangi amaçla kullanılır?",
        "Mesleki muhakeme",
        "Denetimin şartlarına uygun bilinçli kararlar vermek",
        ["Yönetimin ticari muhakemesi", "Hukuki kesinlik", "Otomatik veri işleme", "Finansal raporlama sorumluluğu"],
        ["Standartların bütün hükümlerini isteğe bağlı kılmak", "Kanıt toplamadan görüş seçmek", "Yönetim kararlarını denetçi adına almak", "Denetim riskini sıfır kabul etmek"],
        "Planlama, önemlilik, risk, prosedür ve kanıt değerlendirmesi mesleki muhakeme gerektirir.",
        "Muhakeme ilgili eğitim, bilgi ve deneyimin standartlar ile etik çerçevesinde uygulanmasıdır.",
        "BDS 200 par. 16 ve A25-A29", "medium",
    ),
    r(
        "Denetçi çok sayıda belge toplamış, ancak belgeler yanlış finansal tablo iddiasıyla ilgilidir. Kanıtın hangi boyutu yetersizdir?",
        "Denetim kanıtında yeterlilik ve uygunluk sırasıyla neyi ifade eder?",
        "Denetim kanıtının uygunluk boyutu",
        "Kanıtın miktarı ile kalitesi",
        ["Yeterlilik; belge sayısı çok fazladır", "Önemlilik; bütün belgeler dış kaynaktandır", "Bağımsızlık; belgeler elektronik ortamdadır", "Muhakeme; kanıt yazılı biçimdedir"],
        ["Kanıtın maliyeti ile denetim ücretini", "Denetimin süresi ile ekip büyüklüğünü", "Yanlışlığın tutarı ile niteliğini", "Yönetim beyanı ile denetçi raporunu"],
        "Çok kanıt, ilgisiz veya güvenilir olmayan kanıtın kalite eksikliğini gidermez.",
        "Yeterlilik miktarı, uygunluk ise kanıtın ihtiyaca uygunluğu ve güvenilirliğiyle ilgili kaliteyi anlatır.",
        "BDS 200 par. 17; BDS 500", "easy",
    ),
    r(
        "Yönetim, finansal tabloları hazırlama ve gerekli iç kontrolü kurma sorumluluğunun denetçiye geçtiğini ileri sürmüştür. Bu görüş doğru mudur?",
        "BDS 200 ve BDS 210'un dayandığı yönetim ön kabulü hangi sorumlulukları içerir?",
        "Hayır; denetim yönetimin sorumluluklarını ortadan kaldırmaz",
        "Hazırlama, iç kontrol ve denetim erişimi",
        ["Evet; sözleşme imzalanınca bütün sorumluluk denetçiye geçer", "Evet; yalnız iç kontrol sorumluluğu denetçinindir", "Hayır; finansal tabloları üst yönetimden sorumlu olanlar denetler", "Evet; makul güvence yönetimi sorumsuz kılar"],
        ["Denetim görüşünü ve prosedürlerini yönetimin belirlemesi", "Denetim riskini sıfıra indirme garantisi", "Denetim çalışma kâğıtlarını işletmenin hazırlaması", "Denetçinin bağımsızlığını yönetimin üstlenmesi"],
        "Finansal tablolar ve iç kontrol yönetimin; görüş oluşturmak için denetim yapmak denetçinin sorumluluğudur.",
        "Yönetim ayrıca ilgili tüm bilgiye, ilave bilgilere ve gerekli görülen kişilere sınırsız erişim sağlar.",
        "BDS 200 par. 4 ve A2-A12; BDS 210 par. 6", "easy",
    ),
    r(
        "Denetçi, finansal tabloları kendisinin hazırladığını ve sonra aynı tablolar hakkında bağımsız görüş verdiğini raporunda belirtmiştir. Temel sorumluluk ayrımıyla uyumlu mudur?",
        "Yönetimin finansal tabloları hazırlama sorumluluğunu kabul etmesi, denetçinin yönetim beyanlarını başka kanıt aramadan yeterli saymasını sağlar mı?",
        "Hayır; hazırlama yönetimin, görüş denetçinin görevidir",
        "Hayır; yönetim beyanı tek başına yeterli denetim kanıtı değildir",
        ["Evet; denetçi her zaman tabloları da hazırlamalıdır", "Evet; yönetim yalnız imza atmakla sorumludur", "Hayır; görüşü üst yönetimden sorumlu olanlar verir", "Evet; denetçi hazırlarsa bağımsızlık otomatik güçlenir"],
        ["Evet; yönetim beyanı bütün diğer kanıtların yerini alır", "Evet; sorumluluk ön kabulü denetim prosedürlerini kaldırır", "Hayır; finansal tabloları denetçi yeniden hazırlamak zorundadır", "Evet; yalnız yönetişim organının sözlü onayı yeterlidir"],
        "Denetimin yürütülmesi yönetimin finansal tablo hazırlama sorumluluğunu devralmaz.",
        "Yönetim sorumluluğu, denetçinin yeterli ve uygun bağımsız kanıt elde etme yükümlülüğünü ortadan kaldırmaz.",
        "BDS 200 par. 4 ve 11", "easy",
    ),
    r(
        "Bir BDS denetimle ilgili olmasına rağmen denetçi, söz konusu standardın amacını ve bütün hükümlerini dikkate almadan yalnız genel deneyimine dayanmıştır. Yaklaşım uygun mudur?",
        "Denetçi BDS'lere uygunluk beyanında bulunabilmek için hangi koşulu karşılamalıdır?",
        "Hayır; denetimle ilgili bütün BDS'lere uyulmalıdır",
        "Denetimle ilgili tüm BDS hükümlerine uymak",
        ["Evet; deneyimli denetçi standartları uygulamayabilir", "Evet; yalnız BDS 200'e uyulması yeterlidir", "Hayır; BDS'ler yalnız kamu işletmelerine uygulanır", "Evet; yönetim onayı standardın yerini alır"],
        ["Standartların yalnız başlıklarını rapora eklemek", "Müşterinin seçtiği hükümlere uymak", "Sadece denetim sözleşmesine atıf yapmak", "Kanıt yetersiz olsa bile olumlu görüş vermek"],
        "BDS 200, denetçinin denetimle ilgili tüm standartların amaç ve hükümlerini anlamasını ve uygulamasını ister.",
        "Bütün ilgili hükümler yerine getirilmeden raporda denetimin BDS'lere uygun yürütüldüğü belirtilmez.",
        "BDS 200 par. 18-20", "medium",
    ),
    r(
        "İlgili bir BDS hükmünün uygulanması olağan dışı şartlarda hükmün amacına ulaşmayı engelleyecektir. Denetçi alternatif prosedürle aynı amaca ulaşmış ve gerekçesini belgelemiştir. Bu mümkün müdür?",
        "Denetçinin ilgili bir BDS hükmünden ayrılması hangi koşulda kabul edilebilir?",
        "Evet; alternatifle aynı amaca ulaşılır",
        "Amaca alternatif prosedürle ulaşılan istisnai durumda",
        ["Hayır; hiçbir koşulda alternatif prosedür kullanılamaz", "Evet; denetim ücretini azaltmak için her zaman", "Evet; yönetim yazılı izin verirse kanıtsız olarak", "Hayır; gerekçenin belgelenmesi yasaktır"],
        ["Denetçinin hükmü zaman alıcı bulması hâlinde", "Yönetimin standardı uygulamak istememesi durumunda", "Denetim riskinin değerlendirilmemiş olması hâlinde", "Alternatif prosedürün daha az kanıt sağlaması durumunda"],
        "BDS 200 ayrılmayı olağan bir tercih değil, hükmün amacına alternatif yolla ulaşılan istisnai durum olarak düzenler.",
        "Denetçi ayrılmanın nedenini, uygulanan alternatifi ve amaca nasıl ulaşıldığını çalışma kâğıtlarında açıklar.",
        "BDS 200 par. 23; BDS 230 par. 12", "hard",
    ),
    r(
        "Denetçi ilgili bir BDS'nin belirli amacına ulaşamayacağını belirlemiştir. Hiçbir değerlendirme yapmadan standart rapor düzenleyebilir mi?",
        "İlgili bir BDS amacına ulaşılamadığında denetçi öncelikle neyi değerlendirir?",
        "Hayır; genel amaçlara etkisi değerlendirilir",
        "Genel amaçlara ve denetim görüşüne etkisini",
        ["Evet; özel amaçların raporla ilgisi yoktur", "Evet; yönetim beyanı eksikliği her zaman giderir", "Hayır; denetim otomatik olarak yok hükmündedir", "Evet; yalnız ücret düşürülmesi gerekir"],
        ["Denetim ücretinin artırılıp artırılmayacağını", "İşletmenin bütçe hedefini", "Çalışan sayısının yeterli olup olmadığını", "Vergi matrahının değişip değişmediğini"],
        "Amaca ulaşılamaması, ek çalışma gereksinimi ile değiştirilmiş görüş veya çekilme gibi sonuçlar bakımından değerlendirilir.",
        "Değerlendirme, tek standardın amacından denetçinin BDS 200'deki genel amaçlarına uzanır.",
        "BDS 200 par. 21 ve 24", "hard",
    ),
    r(
        "Denetçi yalnız bir hesap bakiyesinin doğru olduğunu doğrulamış, fakat finansal tabloların bütünü hakkında görüş vermiştir. Genel denetim amacıyla uyumlu mudur?",
        "Bağımsız denetim görüşünün konusu kural olarak nedir?",
        "Hayır; bütün için yeterli ve uygun kanıt gerekir",
        "Finansal tabloların bütünü",
        ["Evet; tek önemli hesap bütün tabloların yerini alır", "Evet; yalnız bilanço toplamının doğrulanması yeterlidir", "Hayır; denetçi hiçbir zaman bütün hakkında görüş vermez", "Evet; yönetim diğer hesapları yazılı olarak doğrularsa"],
        ["Yalnız işletmenin gelecek yıl bütçesi", "Sadece yönetim kurulunun faaliyet raporu", "Denetim sözleşmesindeki ücret hesabı", "Her bir işlemin ticari başarısı"],
        "Denetçi finansal tabloların bir bütün olarak önemli yanlışlık içerip içermediğine ilişkin sonuç oluşturur.",
        "Tek tek kalemler denetim kanıtının parçalarıdır; raporun ana konusu bütün finansal tablolardır.",
        "BDS 200 par. 11; BDS 700", "medium",
    ),
    r(
        "Finansal tablolar önemli yanlışlık içermemektedir; ancak işletme dönem sonrasında ticari hedeflerine ulaşamamıştır. Bu durum tek başına denetimin başarısız olduğunu gösterir mi?",
        "Bağımsız denetim görüşü aşağıdakilerden hangisini garanti etmez?",
        "Hayır; denetim işletmenin gelecekteki başarısını garanti etmez",
        "İşletmenin gelecekteki ticari başarısını",
        ["Evet; olumlu görüş bütün ticari hedefleri garanti eder", "Hayır; denetim yalnız geçmiş nakit akışını doğrular", "Evet; makul güvence yatırım getirisini garanti eder", "Hayır; finansal tabloların doğruluğu denetimin konusu değildir"],
        ["Finansal tabloların önemli yanlışlık yönünden değerlendirilmesini", "Görüşün yeterli ve uygun kanıta dayanmasını", "Denetçinin mesleki şüphecilik kullanmasını", "Denetim riskinin azaltılmasını"],
        "Denetim görüşü finansal raporlamaya ilişkindir; işletmenin gelecekteki ekonomik başarısı için güvence değildir.",
        "Olumlu görüş, yatırımın güvenli veya yönetimin tüm kararlarının etkili olduğu anlamına gelmez.",
        "BDS 200 par. A1-A2", "easy",
    ),
    r(
        "Hile kaynaklı önemli yanlışlık riski, hata kaynaklı riske göre daha zor tespit edilebilmektedir. Bunun temel nedeni nedir?",
        "BDS 200 bakımından önemli yanlışlık hangi iki kaynaktan doğabilir?",
        "Kasıtlı gizleme ve kontrolleri aşma olasılığı",
        "Hata veya hileden",
        ["Hile her zaman küçük tutarlı olduğu için", "Hata yalnız yönetim tarafından yapıldığı için", "Hile denetim görüşünün kapsamı dışında olduğu için", "Hata hiçbir zaman kanıtla tespit edilemediği için"],
        ["Yalnız tahmin ve değerlemeden", "Sadece mevzuata aykırılıktan", "Yalnız iç kontrol eksikliğinden", "Sadece bilgisayar arızasından"],
        "Kasıtlı gizleme ve kontrollerin aşılması hileyi hataya göre daha zor saptanabilir kılar.",
        "Denetimin makul güvence amacı, finansal tabloların hem hata hem hile kaynaklı önemli yanlışlıklarını kapsar.",
        "BDS 200 par. 5 ve A53-A56; BDS 240", "medium",
    ),
    r(
        "Denetçi teknik olarak yeterli prosedürler uygulamış, ancak denetim boyunca geçerli etik hükümlere uymamıştır. Denetim BDS 200'e uygun sayılabilir mi?",
        "BDS 200 denetçinin hangi etik yükümlülüklere uymasını ister?",
        "Hayır; etik hükümlere uymak zorunludur",
        "Bağımsızlık dâhil ilgili etik hükümler",
        ["Evet; teknik kanıt etik ihlali her zaman giderir", "Evet; etik yalnız sözleşme öncesinde önemlidir", "Hayır; etik hükümler yalnız yönetime uygulanır", "Evet; müşteri ihlali onaylarsa denetim geçerlidir"],
        ["Yalnız işletmenin personel yönetmeliği", "Sadece vergi idaresinin iç talimatı", "Müşterinin belirlediği davranış kuralları", "Denetim ücretini artıran hükümler"],
        "Etik uygunluk ve bağımsızlık, denetim kanıtının ve görüşün güvenilirliği için temel ön koşuldur.",
        "BDS 200, denetimle ilgili etik hükümlerin tamamına, özellikle bağımsızlık hükümlerine uyulmasını gerektirir.",
        "BDS 200 par. 14 ve A16-A19", "easy",
    ),
    r(
        "Denetim kabul edilmeden önce işletmenin kullandığı finansal raporlama çerçevesinin kabul edilebilir olmadığı anlaşılmıştır. Mevzuat zorunluluğu da yoktur. Denetçi işi kabul etmeli midir?",
        "BDS 210'a göre denetimin ön şartlarından biri hangisidir?",
        "Hayır; kabul edilebilir çerçeve ön şarttır",
        "Kabul edilebilir finansal raporlama çerçevesi",
        ["Evet; denetçi sonradan kendi çerçevesini uygular", "Evet; yönetim hangi çerçeveyi seçerse seçsin kabul edilir", "Hayır; yalnız vergi beyannamesi hazırlanmalıdır", "Evet; olumlu görüş sözü verilirse sorun kalkar"],
        ["Denetim ücretinin peşin tahsil edilmesi", "Yönetimin bütün muhasebe tahminlerini kaldırması", "İşletmenin mutlaka halka açık olması", "Denetçinin finansal tabloları hazırlaması"],
        "Kabul edilebilir çerçeve, denetimin anlamlı bir ölçüt temelinde yürütülmesinin ön şartıdır.",
        "Denetçi çerçevenin kabul edilebilirliğini ve yönetimin sorumluluk ön kabulünü kabul edip etmediğini belirler.",
        "BDS 210 par. 6-8", "medium",
    ),
    r(
        "Yönetim, denetçiye kayıt ve belgelere erişim vereceğini ancak gerekli görülen çalışanlarla görüşmeye izin vermeyeceğini açıklamıştır. Denetimin ön şartları sağlanmış mıdır?",
        "Yönetimin denetim ön kabulü kapsamında denetçiye erişim sorumluluğu nedir?",
        "Hayır; denetçinin gerekli gördüğü kişilere sınırsız erişim de sağlanmalıdır",
        "Gerekli bilgi ve kişilere sınırsız erişim",
        ["Evet; yalnız defteri kebire erişim yeterlidir", "Evet; çalışan görüşmeleri hiçbir denetimde yapılmaz", "Hayır; denetçi tüm çalışanları işe almalıdır", "Evet; yönetim sözlü beyan verirse erişim gerekmez"],
        ["Yalnız yönetim kurulunun seçtiği belgelere erişmek", "Denetçiye sadece kamuya açıklanmış bilgileri vermek", "Çalışan erişimini denetim sonrasına ertelemek", "Denetim kanıtlarını denetçi adına hazırlamak"],
        "BDS 210 ön kabulü, yönetimin ilgili bilgi ve ilave bilgiyle birlikte gerekli kişilere sınırsız erişim sağlamasını içerir.",
        "Kişilere erişimin engellenmesi kanıt toplamayı sınırlar ve işin kabulünü etkileyebilir.",
        "BDS 210 par. 6(b)", "medium",
    ),
    r(
        "Yönetim, denetim başlamadan önce kapsamı öyle sınırlamıştır ki denetçinin görüş vermekten kaçınacağı öngörülmektedir. Mevzuat işi zorunlu kılmıyorsa denetçi ne yapmalıdır?",
        "Sözleşme öncesi kapsam sınırlaması görüş vermekten kaçınmaya yol açacaksa BDS 210'un yaklaşımı nedir?",
        "Denetim işini kabul etmemelidir",
        "Mevzuat zorunluluğu yoksa iş kabul edilmez",
        ["İşi kabul edip peşinen olumlu görüş vermelidir", "Kapsamı yönetimin istediği ölçüde azaltmalıdır", "İşi derleme hizmetine çevirip denetim görüşü vermelidir", "Yalnız denetim ücretini artırmalıdır"],
        ["İş koşulsuz kabul edilir", "Yönetim beyanı kanıt sayılarak sorun giderilir", "Denetçi sınırlamayı raporda hiç anmaz", "Sadece önemlilik sıfıra indirilir"],
        "Öngörülen sonuç görüş vermekten kaçınmaysa, mevzuat zorunluluğu dışında bu şartlarla denetim kabul edilmez.",
        "Kabul öncesi engel, denetçinin genel amaçlarına ulaşmasını baştan imkânsız kılmaktadır.",
        "BDS 210 par. 7", "hard",
    ),
    r(
        "Taraflar denetimin amacını, kapsamını ve sorumlulukları sözlü konuşmuş; yazılı sözleşme veya başka uygun yazılı anlaşma hazırlamamıştır. Yaklaşım uygun mudur?",
        "Denetim sözleşmesinin şartları hangi biçimde kayda geçirilir?",
        "Hayır; şartlar yazılı sözleşme veya uygun başka bir yazılı anlaşmayla kayda alınır",
        "Uygun bir yazılı anlaşmayla",
        ["Evet; tarafların sözlü mutabakatı her durumda yeterlidir", "Evet; yalnız denetçi çalışma kâğıdına not düşer", "Hayır; şartları sadece düzenleyici kurum belirler", "Evet; rapor tamamlanınca geriye dönük yazılabilir"],
        ["Yalnız yönetimin sözlü beyanında", "Denetçi raporunun görüş paragrafında", "İşletmenin reklam metninde", "Sadece ücret faturasının açıklamasında"],
        "Yazılı kayıt, denetimin amacı, kapsamı ve tarafların sorumlulukları hakkındaki yanlış anlamaları azaltır.",
        "BDS 210 sözleşme şartlarının yazılı olarak yönetim veya uygun hâllerde üst yönetimden sorumlu olanlarla kararlaştırılmasını ister.",
        "BDS 210 par. 9-10", "easy",
    ),
    r(
        "Denetim sözleşmesinde yalnız ücret ve teslim tarihi yer almakta; denetimin amacı, kapsamı ve taraf sorumlulukları bulunmamaktadır. Sözleşme BDS 210 bakımından yeterli midir?",
        "BDS 210'a göre denetim sözleşmesinde yer alan temel unsurlardan biri hangisidir?",
        "Hayır; temel denetim şartları yazılı olarak belirtilmelidir",
        "Denetimin amacı ve kapsamı ile denetçi ve yönetimin sorumlulukları",
        ["Evet; ücret ve tarih bütün unsurların yerini alır", "Evet; amaç yalnız rapor verildikten sonra belirlenir", "Hayır; sözleşmede ücret bulunması yasaktır", "Evet; sorumluluklar her işletmede yönetimce seçilir"],
        ["İşletmenin gelecek beş yıllık satış hedefi", "Denetçinin müşteriye sağlayacağı yatırım getirisi", "Yönetim kurulunun kişisel mal varlığı", "Bütün çalışanların bireysel performans notları"],
        "BDS 210; amaç, kapsam, sorumluluklar, raporlama çerçevesi ve beklenen rapor biçimi gibi unsurları arar.",
        "Ayrıca raporun şekil ve içeriğinin şartlara göre beklenenden farklılaşabileceği belirtilir.",
        "BDS 210 par. 10", "easy",
    ),
    r(
        "Aynı işletmenin tekrarlanan denetiminde ortaklık yapısı ve raporlama çerçevesi değişmiştir. Denetçi önceki sözleşmeyi hiç değerlendirmeden kullanabilir mi?",
        "Tekrarlanan denetimlerde denetçi sözleşme şartları için ne yapar?",
        "Hayır; şartların değiştirilmesi veya yeniden hatırlatılması gereğini değerlendirir",
        "Değişiklik veya yeniden hatırlatma gereğini değerlendirir",
        ["Evet; ilk sözleşme sonsuza kadar değişmeden geçerlidir", "Evet; yalnız ücret değişirse yeni değerlendirme yapılır", "Hayır; her yıl müşteri ilişkisi tamamen sonlandırılır", "Evet; raporlama çerçevesi sözleşmeyi etkilemez"],
        ["Önceki şartları otomatik olarak yok sayar", "Her yıl güvence düzeyini kendiliğinden düşürür", "Sözleşmeyi yalnız denetim sonrasında düzenler", "Yönetimin sözlü talimatını yazılı şartların yerine geçirir"],
        "Mülkiyet, yönetim, işin niteliği, çerçeve veya raporlama değişikliği şartların yenilenmesini gerektirebilir.",
        "BDS 210 her tekrarlanan denetimde yeni sözleşmeyi zorunlu kılmaz; yeniden düzenleme veya hatırlatma ihtiyacının değerlendirilmesini ister.",
        "BDS 210 par. 13-14", "medium",
    ),
    r(
        "Yönetim, yanlış anladığı denetim niteliğini gerekçe göstererek iş tamamlanmadan hizmeti daha düşük güvence sağlayan bir çalışmaya çevirmek istemektedir. Makul gerekçe yoksa denetçi kabul eder mi?",
        "Denetim sözleşmesinin daha düşük güvence sağlayan bir işe dönüştürülmesi hangi durumda kabul edilir?",
        "Hayır; makul gerekçe olmadan daha düşük güvenceye geçilmez",
        "Değişiklik için makul bir gerekçe bulunduğunda",
        ["Evet; yönetimin her talebi yeterli gerekçedir", "Evet; kanıt yetersizliği her zaman dönüştürme nedenidir", "Hayır; sözleşme hiçbir koşulda değiştirilemez", "Evet; görüş değişmesin diye hizmet türü değiştirilir"],
        ["Denetçi olumsuz sonuç beklediğinde", "Kanıt elde edememeyi gizlemek istendiğinde", "Yönetim ücret azaltmak istediğinde tek başına", "Rapor tarihini öne çekmek için"],
        "Koşullardaki gerçek değişim veya hizmetin niteliğine ilişkin haklı yanlış anlama makul olabilir; olumsuz sonuçtan kaçınma makul değildir.",
        "Denetçi, değişikliğin gerekçesini ve yeni şartları değerlendirir; gerekçe yoksa denetimi dönüştürmez.",
        "BDS 210 par. 14-17", "hard",
    ),
    r(
        "Denetçi, önemli muhakemeleri ve ulaşılan sonuçların dayanağını tecrübeli bir denetçinin anlayamayacağı kadar yüzeysel belgelemeyle bırakmıştır. BDS 230'a uygun mudur?",
        "Yeterli çalışma kâğıdı, denetimle önceden bağlantısı olmayan tecrübeli bir denetçinin hangi hususu anlamasını sağlar?",
        "Hayır; önemli hususlar, muhakemeler ve sonuç dayanakları anlaşılabilir olmalıdır",
        "Yapılan işi ve önemli muhakemeleri",
        ["Evet; yalnız nihai görüşün yazılması yeterlidir", "Evet; sözlü açıklama her zaman belgelemenin yerini alır", "Hayır; çalışma kâğıtları yönetim tarafından hazırlanmalıdır", "Evet; kanıtlar denetim bitince imha edilir"],
        ["İşletmenin gelecek dönem bütçe hedeflerini", "Denetim ücretinin pazarlık ayrıntılarını", "Her çalışanın kişisel özgeçmişini", "Yönetimin bütün ticari kararlarını"],
        "Çalışma kâğıtları yapılan işi, elde edilen kanıtı, sonuçları ve önemli mesleki muhakemeleri izlenebilir kılar.",
        "Belgeleme denetçinin sözlü açıklamasının yerine geçmez; açıklama mevcut belgeleri netleştirebilir.",
        "BDS 230 par. 2-3 ve 8", "medium",
    ),
    r(
        "Sorumlu denetçi kalite yönetimi için ekibin bütün muhakemelerini denetim şirketine devretmiş ve denetim düzeyinde sorumluluk almadığını belirtmiştir. Yaklaşım doğru mudur?",
        "BDS 220 (Revize) uyarınca denetim düzeyinde kalitenin yönetilmesi ve sağlanmasına ilişkin genel sorumluluk kimdedir?",
        "Hayır; denetim kalitesinden sorumlu denetçi sorumludur",
        "Denetim düzeyinde sorumlu denetçidedir",
        ["Evet; sorumluluk yalnız şirketin izleme birimindedir", "Evet; her ekip üyesi yalnız kendi işinden sorumludur", "Hayır; kalite yalnız yönetimin sorumluluğudur", "Evet; dış kalite incelemesi sorumluluğu kaldırır"],
        ["Denetlenen işletmenin yönetimindedir", "Yalnız denetimin kalitesini gözden geçiren kişidedir", "Finansal tabloları kullananlardadır", "Düzenleyici kurumun saha ekibindedir"],
        "Şirketin kalite yönetim sistemi denetimi destekler; ancak sorumlu denetçinin denetim düzeyindeki genel sorumluluğunu kaldırmaz.",
        "Sorumlu denetçi yeterli ve uygun katılım, yönlendirme, gözetim ve gözden geçirme yoluyla kaliteyi yönetir.",
        "BDS 220 (Revize) par. 13-16", "medium",
    ),
]


PREMISES = [
    {"stem":"Bağımsız denetimin genel amaçları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Finansal tabloların bütünü için makul güvence hedeflenir\n\nII. Hata ve hile kaynaklı önemli yanlışlıklar dikkate alınır\n\nIII. Ulaşılan sonuca uygun raporlama yapılır","correct":"I, II ve III","why":"BDS 200'ün makul güvence, önemli yanlışlık ve raporlama boyutlarının üçü de denetçinin genel amaçları içindedir.","ref":"BDS 200 par. 11","difficulty":"easy"},
    {"stem":"Denetçinin temel davranışları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mesleki şüphecilik sürdürülür\n\nII. Mesleki muhakeme kullanılır\n\nIII. Yeterli ve uygun kanıt elde edilir","correct":"I, II ve III","why":"BDS 200 bu üç yükümlülüğü denetimin planlanması ve yürütülmesinin temel unsurları olarak düzenler.","ref":"BDS 200 par. 15-17","difficulty":"easy"},
    {"stem":"Makul güvence bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yüksek bir güvence düzeyidir\n\nII. Denetim riskinin kabul edilebilir düşük düzeye indirilmesini gerektirir\n\nIII. Bütün yanlışlıkların bulunmasını kesin olarak garanti eder","correct":"I ve II","why":"Makul güvence yüksek fakat mutlak değildir; denetimin yapısal kısıtlamaları nedeniyle III yanlıştır.","ref":"BDS 200 par. 5 ve A45-A52","difficulty":"medium"},
    {"stem":"Denetim sorumlulukları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Finansal tabloları hazırlamak denetçinin asli görevidir\n\nII. Gerekli iç kontrolü oluşturmak yönetimin sorumluluğudur\n\nIII. Finansal tablolar hakkında görüş vermek denetçinin sorumluluğudur","correct":"II ve III","why":"Finansal tabloların hazırlanması ve iç kontrol yönetimin; görüş oluşturma ve raporlama denetçinin sorumluluğudur.","ref":"BDS 200 par. 4 ve 11","difficulty":"easy"},
    {"stem":"Denetimin ön şartları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kabul edilebilir finansal raporlama çerçevesi bulunur\n\nII. Denetçi gerekli kişilere erişebilmelidir\n\nIII. Yönetimin sorumluluk ön kabulünü benimsemesi aranmaz","correct":"I ve II","why":"BDS 210 kabul edilebilir çerçeveyi ve yönetimin bilgi, kişi erişimi dâhil sorumluluklarını kabul etmesini arar; III yanlıştır.","ref":"BDS 210 par. 6-8","difficulty":"medium"},
    {"stem":"Denetim sözleşmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Sözlü mutabakat her durumda yeterlidir\n\nII. Denetimin amacı ve kapsamı yazılı şartlarda yer alır\n\nIII. Denetçi ve yönetimin sorumlulukları belirtilir","correct":"II ve III","why":"BDS 210 yazılı sözleşme veya uygun yazılı anlaşma ve temel sorumluluk unsurlarını gerektirir.","ref":"BDS 210 par. 9-10","difficulty":"medium"},
    {"stem":"BDS'lere uygunluk bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Denetimle ilgili bütün BDS'ler dikkate alınır\n\nII. İstisnai ayrılmada alternatif prosedürle hükmün amacına ulaşılır\n\nIII. Yönetim izni, ilgili BDS hükümlerinin uygulanmaması için tek başına yeterlidir","correct":"I ve II","why":"İlgili standartlara uyulur; istisnai ayrılma amaca ulaşan alternatif ve belgeleme gerektirir. III yanlıştır.","ref":"BDS 200 par. 18-23","difficulty":"hard"},
    {"stem":"Denetimin belgelendirilmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Önemli muhakemeler ve sonuç dayanakları kaydedilir\n\nII. Sözlü açıklama her zaman çalışma kâğıdının yerini alır\n\nIII. Prosedürlerin niteliği, zamanlaması ve kapsamı anlaşılabilir olmalıdır","correct":"I ve III","why":"Çalışma kâğıtları yapılan işi ve önemli sonuçları izlenebilir kılar; sözlü açıklama tek başına yeterli değildir.","ref":"BDS 230 par. 8-9","difficulty":"medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="denetim_temelleri",
        label="Denetim Temelleri", slug="denetim_temelleri", prefix="topic-dte",
        seed=2026071747,
        legislation_version="KGK TDS 2026 Seti; BDS 200, BDS 210, BDS 220 (Revize), BDS 230 ve BDS 260 (17.07.2026 kontrolü)",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
