#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — KDV'de Teslim, Hizmet ve İndirim, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Türkiye'de ticari faaliyeti kapsamında mal satan işletmenin bu işlemi KDV karşısında nasıl değerlendirilir?",
        "Ticari, sınai, zirai veya serbest meslek faaliyeti çerçevesinde Türkiye'de yapılan teslim ve hizmetlerin KDV bakımından niteliği nedir?",
        "KDV'nin konusuna girer", "Katma değer vergisine tabidir",
        ["Yalnız damga vergisine tabidir", "Her durumda KDV'den istisnadır", "KDV dışında ücret sayılır", "Sadece ithalatta vergilenir"],
        ["Faaliyetin türüne bakılmaksızın istisnadır", "Yalnız kamu işletmelerinde vergilenir", "Kendiliğinden veraset vergisi doğurur", "Türkiye'de yapılsa da KDV dışıdır"],
        "Türkiye'de ticari faaliyet kapsamında yapılan mal teslimi KDV'nin konusuna girer.",
        "Kanun, Türkiye'de ticari, sınai, zirai ve serbest meslek faaliyeti kapsamında yapılan teslim ve hizmetleri vergilendirir.",
        "3065 sayılı KDVK m. 1/1", "easy",
    ),
    r(
        "Bir gerçek kişi yurt dışından kişisel kullanımı için mal ithal etmiştir. İthalatın ticari olmaması tek başına KDV'yi önler mi?",
        "Her türlü mal ve hizmet ithalatının KDV karşısındaki temel durumu hangisidir?",
        "Hayır; ithalat KDV'ye tabidir", "İthalat genel olarak KDV'ye tabidir",
        ["Evet; yalnız şirket ithalatı vergilenir", "Evet; kişisel ithalat daima istisnadır", "Yalnız ihracat vergisi doğar", "İthalat sadece damga vergisine tabidir"],
        ["Yalnız kamu sektörü ithalatı vergilenir", "Gerçek kişilerin ithalatı KDV dışıdır", "Sadece bedelsiz ithalat vergilenir", "İthalat hiçbir zaman KDV doğurmaz"],
        "İthalatın kamu veya özel sektörce, gerçek ya da tüzel kişi tarafından yapılması vergilemeyi tek başına değiştirmez.",
        "KDVK her türlü mal ve hizmet ithalatını verginin konusuna alır; ithalatçının statüsü belirleyici değildir.",
        "3065 sayılı KDVK m. 1/2", "easy",
    ),
    r(
        "Bir kamu kurumu kanunun gösterdiği gerek üzerine ticari nitelikte teslim yapmıştır. Kamu tüzel kişiliği işlemi kendiliğinden KDV dışına çıkarır mı?",
        "Vergiye tabi işlemi yapanın hukuki statüsü veya Türk tabiiyetinde bulunmaması KDV bakımından nasıl etki eder?",
        "Hayır; işlemin niteliği esas alınır", "Vergilendirmeye tek başına engel olmaz",
        ["Evet; kamu işlemleri koşulsuz istisnadır", "Evet; resmî gerek bütün vergileri kaldırır", "İşlem yalnız harca tabi olur", "KDV yerine ücret stopajı doğar"],
        ["İşlemi her durumda KDV dışına çıkarır", "Yalnız yabancıların işlemini istisna eder", "Mükellefin seçimine bağlı istisna yaratır", "Teslimi otomatik bağış sayar"],
        "Faaliyetin resmî gerek üzerine yapılması veya yapanın statüsü, vergiye tabi işlemin mahiyetini değiştirmez.",
        "KDV'de vergilendirilen işlemin niteliğidir; yapanın statüsü ya da tabiiyeti tek başına vergilemeyi önlemez.",
        "3065 sayılı KDVK m. 1", "medium",
    ),
    r(
        "Satıcı, mal üzerindeki tasarruf hakkını alıcıya devretmiştir. KDVK bakımından gerçekleşen işlem hangisidir?",
        "KDVK'da teslim kavramının temel ölçütü hangisidir?",
        "Mal teslimi gerçekleşmiştir", "Tasarruf hakkının alıcıya devri",
        ["Yalnız hizmet ifası gerçekleşmiştir", "Sadece mülkiyet vaadi verilmiştir", "Herhangi bir vergili işlem yoktur", "Yalnız finansman işlemi doğmuştur"],
        ["Malın bedelinin mutlaka peşin ödenmesi", "Tarafların aynı şehirde bulunması", "Sözleşmenin noterlikte yapılması", "Satıcının tüzel kişi olması"],
        "Teslim, mal üzerindeki tasarruf hakkının malik veya onun adına hareket edenlerce alıcıya devridir.",
        "Hukuki biçimden çok, mal üzerinde fiilen tasarruf edebilme yetkisinin alıcıya geçirilmesi teslimi belirler.",
        "3065 sayılı KDVK m. 2/1", "easy",
    ),
    r(
        "Satıcı, alıcının talimatıyla malı doğrudan alıcının gösterdiği üçüncü kişiye bırakmıştır. Teslim oluşmuş mudur?",
        "Malın alıcının gösterdiği yere veya kişiye tevdi edilmesi KDVK'da nasıl kabul edilir?",
        "Evet; alıcıya teslim hükmündedir", "Mal teslimi sayılır",
        ["Hayır; mal mutlaka alıcının eline verilmelidir", "Yalnız taşıma hizmeti sayılır", "Sadece emanet işlemi doğurur", "KDV bakımından hiç sonuç doğurmaz"],
        ["Teslim değil yalnız saklama sayılır", "Malın mülkiyetini satıcıya geri geçirir", "Sadece gümrük işlemi kabul edilir", "Her durumda vergiden istisnadır"],
        "Alıcının gösterdiği yere veya kişiye tevdi, alıcıya teslim hükmündedir.",
        "Teslim için malın bizzat alıcıya verilmesi şart değildir; alıcının talimatıyla gösterilen yere bırakılması yeterlidir.",
        "3065 sayılı KDVK m. 2/1", "medium",
    ),
    r(
        "Mal el değiştirmeden A'dan B'ye, B'den C'ye zincirleme sözleşmelerle tasarruf hakkı devredilmiş ve mal doğrudan C'ye gitmiştir. KDVK bakımından sonuç nedir?",
        "Malın fiziken ara alıcılara uğramadığı zincirleme akitlerde aradaki safhalar nasıl değerlendirilir?",
        "Her safha ayrı teslimdir", "Her safha bağımsız mal teslimi sayılır",
        ["Yalnız son safha teslimdir", "Hiçbir safha teslim değildir", "Tüm safhalar tek hizmettir", "Yalnız ilk safha vergilenir"],
        ["Sadece son alıcı yönünden teslim oluşur", "Ara safhalar bağış sayılır", "Bütün safhalar KDV dışıdır", "Yalnız nakliye vergilenir"],
        "Tasarruf hakkının zincirleme akitlerle devrinde, mal el değiştirmese bile her safha ayrı teslimdir.",
        "KDVK zincirleme satışların her birini ayrı vergili teslim olarak kabul eder.",
        "3065 sayılı KDVK m. 2/2", "hard",
    ),
    r(
        "Elektrik dağıtım şirketi abonesine elektrik sağlamıştır. Bu işlem KDVK'da hangi işlem türündedir?",
        "Su, elektrik, gaz, ısıtma ve soğutma biçimindeki dağıtımlar KDVK'ya göre nasıl nitelendirilir?",
        "Mal teslimidir", "Mal teslimi kabul edilir",
        ["Yalnız kira hizmetidir", "Menkul sermaye iradıdır", "KDV dışında bir bağıştır", "Sadece finansman hizmetidir"],
        ["Gayrimenkul kiralaması sayılır", "Vergisiz kamu hizmetidir", "Yalnız ücret ödemesidir", "Hiçbir teslim oluşturmaz"],
        "Elektrik ve benzeri enerji dağıtımları kanunda mal teslimi sayılmıştır.",
        "KDVK su, elektrik, gaz, ısıtma ve soğutma dağıtımlarını mal teslimi olarak niteler.",
        "3065 sayılı KDVK m. 2/3", "easy",
    ),
    r(
        "İki işletme mallarını bedel farkı olmaksızın karşılıklı değiştirmiştir. Trampa KDVK bakımından nasıl ele alınır?",
        "Trampa işleminde KDV bakımından kaç teslim bulunduğu kabul edilir?",
        "İki ayrı teslim vardır", "Karşılıklı iki mal teslimi oluşur",
        ["Tek bir teslim vardır", "Yalnız hizmet ifası vardır", "Teslim hiç gerçekleşmez", "Sadece bedel farkı vergilenir"],
        ["Hiç teslim bulunmaz", "Yalnız birinci mal teslim sayılır", "Tek bir finansman işlemi oluşur", "Sadece takas sözleşmesi damgalanır"],
        "Trampa, karşılıklı olarak iki ayrı teslim hükmündedir.",
        "Her taraf diğerine bir malın tasarruf hakkını devrettiği için iki ayrı teslim oluşur.",
        "3065 sayılı KDVK m. 2/5", "easy",
    ),
    r(
        "İşletme, ticari stokundaki vergiye tabi malı sahibinin kişisel kullanımı için işletmeden çekmiştir. KDVK bakımından sonuç hangisidir?",
        "Vergiye tabi malın işletme dışı amaçlarla işletmeden çekilmesi nasıl değerlendirilir?",
        "Teslim sayılan hâl oluşur", "Vergili teslim kabul edilir",
        ["Yalnız muhasebe içi aktarım olur", "Her durumda istisna uygulanır", "Sadece ücret ödemesi sayılır", "KDV yönünden sonuç doğmaz"],
        ["Teslim sayılmaz", "Yalnız bağış sözleşmesi olur", "KDV dışında tasfiye sayılır", "Sadece kurumlar vergisi doğurur"],
        "Vergiye tabi malın işletme dışı amaçlarla çekilmesi kanunen teslim sayılır.",
        "İşletmeden çekiş, malın nihai tüketime yönelmesi nedeniyle KDVK'da teslim sayılan hâllerdendir.",
        "3065 sayılı KDVK m. 3/a", "medium",
    ),
    r(
        "İşletme stokundaki vergiye tabi malları çalışanlarına bayram hediyesi olarak vermiştir. İşlem KDVK bakımından nedir?",
        "Vergiye tabi malların personele ücret, prim, ikramiye veya hediye adıyla verilmesi nasıl nitelendirilir?",
        "Teslim sayılır", "Kanunen mal teslimi kabul edilir",
        ["KDV dışında kalır", "Yalnız hizmet sayılır", "Her durumda ihracat istisnasıdır", "Sadece ücret stopajı doğurur"],
        ["Teslim oluşturmaz", "Yalnız iş hukuku ödemesidir", "Kendiliğinden bağış istisnasıdır", "Sadece damga vergisi doğurur"],
        "Vergiye tabi malların personele hediye veya benzeri adlarla verilmesi teslim sayılır.",
        "Mal işletme bünyesinden nihai kullanıma çıktığı için kanun işlemi teslim kabul eder.",
        "3065 sayılı KDVK m. 3/a", "easy",
    ),
    r(
        "Satış mülkiyeti muhafaza kaydıyla yapılmış ve malın zilyetliği alıcıya devredilmiştir. KDVK bakımından teslim ne zaman oluşur?",
        "Mülkiyeti muhafaza kaydıyla satışta hangi olay teslim sayılır?",
        "Zilyetliğin devrinde", "Mal zilyetliğinin alıcıya geçirilmesi",
        ["Son taksitten beş yıl sonra", "Mülkiyet kaydı kalkınca", "Satıcının bilanço gününde", "Hiçbir zaman"],
        ["Bedelin tamamının yıllar sonra ödenmesi", "Noterin ayrıca onay vermesi", "Satıcının faaliyetini bırakması", "Alıcının malı yeniden satması"],
        "Mülkiyeti muhafaza kaydı bulunsa da zilyetliğin devri teslim sayılır.",
        "KDVK, tasarruf imkânının alıcıya geçmesini esas alarak zilyetlik devrinde teslimi kabul eder.",
        "3065 sayılı KDVK m. 3/c", "medium",
    ),
    r(
        "Bir işletme müşterisinin makinesini ücret karşılığında onarmıştır. KDVK bakımından işlem türü hangisidir?",
        "Mal teslimi, teslim sayılan hâller ve mal ithalatı dışında kalan işlemler KDVK'da hangi başlıkta toplanır?",
        "Hizmet ifasıdır", "Hizmet olarak değerlendirilir",
        ["Mal ithalatıdır", "Teslim sayılan mal çekişidir", "Yalnız finansman işlemidir", "KDV dışında ücrettir"],
        ["Mutlaka mal teslimidir", "Yalnız menkul sermaye iradıdır", "Her durumda vergisiz bağıştır", "Sadece gümrük işlemidir"],
        "Onarma gibi bir şeyi yapmak veya işlemek biçimindeki edimler hizmettir.",
        "KDVK teslim ve ithalat dışında kalan yapma, işleme, onarma, kiralama gibi işlemleri hizmet sayar.",
        "3065 sayılı KDVK m. 4/1", "easy",
    ),
    r(
        "Danışmanlık hizmetinin bedeli para yerine bir bilgisayar teslim edilerek ödenmiştir. Karşılıklı edimler KDVK bakımından nasıl ele alınır?",
        "Bir hizmetin karşılığının mal teslimi veya başka hizmet olması hâlinde temel kural hangisidir?",
        "Her edim ayrı vergilendirilir", "Teslim ve hizmet ayrı ayrı değerlendirilir",
        ["Yalnız bilgisayar teslimi vergilenir", "Yalnız danışmanlık hizmeti vergilenir", "Karşılıklı edimler KDV dışı kalır", "Sadece bedel farkı vergilenir"],
        ["İki edim tek vergisiz işlem olur", "Sadece ilk edim dikkate alınır", "Karşılık ayni ise KDV doğmaz", "Her ikisi yalnız damga vergisine girer"],
        "Hizmet karşılığında mal veya hizmet alınması hâlinde her edim kendi niteliğine göre ayrı vergilenir.",
        "Parasal karşılık bulunmaması KDV'yi kaldırmaz; karşılıklı teslim ve hizmetler bağımsız işlemlerdir.",
        "3065 sayılı KDVK m. 4/2", "hard",
    ),
    r(
        "İşletme normalde ücretle sunduğu vergiye tabi hizmetten şirket ortağını bedelsiz yararlandırmıştır. KDVK bakımından sonuç nedir?",
        "Vergiye tabi bir hizmetten işletme sahibi, personel veya üçüncü kişinin karşılıksız yararlandırılması nasıl kabul edilir?",
        "Hizmet sayılan hâl oluşur", "Vergiye tabi hizmet kabul edilir",
        ["KDV yönünden hiçbir işlem oluşmaz", "Yalnız mal teslimi sayılır", "Her durumda sosyal yardım istisnasıdır", "Sadece ücret stopajı doğurur"],
        ["Hizmet sayılmaz", "Yalnız bağış belgesi doğurur", "Kendiliğinden ihracat sayılır", "Sadece kurum kazancını azaltır"],
        "Vergiye tabi hizmetten karşılıksız yararlandırma kanunen hizmet sayılır.",
        "Bedelsiz kullandırma, hizmetin nihai tüketimini oluşturduğu için KDVK m. 5 kapsamındadır.",
        "3065 sayılı KDVK m. 5", "medium",
    ),
    r(
        "Teslim anında Türkiye'de bulunan bir malın tasarruf hakkı alıcıya devredilmiştir. İşlem yeri bakımından sonuç hangisidir?",
        "Mal tesliminin Türkiye'de yapılmış sayılması için temel yer ölçütü nedir?",
        "Teslim Türkiye'de yapılmış sayılır", "Malın teslim anında Türkiye'de bulunması",
        ["Satıcının yabancı olması işlemi yurt dışına taşır", "Alıcının uyruğu işlem yerini belirler", "Ödeme dövizle ise işlem yurt dışındadır", "Sözleşme dili KDV yerini değiştirir"],
        ["Bedelin Türk lirasıyla ödenmesi", "Satıcının Türk vatandaşı olması", "Sözleşmenin Türkiye'de imzalanması", "Alıcının tüzel kişi olması"],
        "Mal tesliminde işlem yeri, malın teslim anında Türkiye'de bulunmasına göre belirlenir.",
        "KDVK m. 6 mal teslimi yönünden malın teslim anındaki fiziki konumunu esas alır.",
        "3065 sayılı KDVK m. 6/a", "easy",
    ),
    r(
        "Yabancı şirketin hizmeti yurt dışında hazırlanmış ancak hizmetten Türkiye'de faydalanılmıştır. Yer kuralı bakımından temel sonuç hangisidir?",
        "Bir hizmetin Türkiye'de yapılmış sayılması için hangi ölçütlerden biri yeterlidir?",
        "Hizmet Türkiye'de yapılmış sayılır", "Hizmetten Türkiye'de faydalanılması",
        ["Hizmet mutlaka KDV dışıdır", "Yalnız sağlayıcının uyruğu belirleyicidir", "Ödeme yeri tek başına işlemi yurt dışına taşır", "Sözleşmenin yabancı dilde olması yeterlidir"],
        ["Sağlayıcının Türk vatandaşı olması", "Bedelin mutlaka peşin ödenmesi", "Tarafların aynı ülkede kurulması", "Faturanın noter onaylı olması"],
        "Hizmetin Türkiye'de yapılması veya hizmetten Türkiye'de faydalanılması işlemi Türkiye'de yapılmış saydırır.",
        "Hizmet yurt dışında hazırlanmış olsa bile Türkiye'de faydalanma, KDV yer kuralını sağlayabilir.",
        "3065 sayılı KDVK m. 6/b", "hard",
    ),
    r(
        "Satıcı malı teslim etmiş, fatura da teslimden sonra düzenlenmiştir. Vergiyi doğuran olay hangi anda meydana gelir?",
        "Mal teslimi ve hizmet ifasında vergiyi doğuran olayın temel anı hangisidir?",
        "Malın teslim edildiği anda", "Teslimin veya hizmetin yapıldığı an",
        ["Bedelin tamamen tahsil edildiği anda", "Beyanname süresi bittiğinde", "Hesap dönemi kapandığında", "Alıcı malı yeniden sattığında"],
        ["Sözleşmenin görüşülmeye başlandığı an", "Ödemenin yıllar sonra tamamlandığı an", "Mükellefin faaliyetini bıraktığı an", "Vergi incelemesinin başladığı an"],
        "Genel kural olarak vergiyi doğuran olay malın teslimi veya hizmetin yapılmasıyla meydana gelir.",
        "Tahsilat zamanı değil, teslim veya hizmet ifasının gerçekleştiği an esas alınır.",
        "3065 sayılı KDVK m. 10/a", "easy",
    ),
    r(
        "Mal teslim edilmeden önce bedelin bir kısmı için fatura düzenlenmiş ve faturada miktar gösterilmiştir. Vergiyi doğuran olayın kapsamı nedir?",
        "Teslim veya hizmetten önce fatura düzenlenirse vergiyi doğuran olay hangi ölçüde meydana gelir?",
        "Faturada gösterilen miktarla sınırlı olarak", "Belgede yazılı miktar kadar",
        ["Teslimin tamamı için koşulsuz olarak", "Hiçbir tutar için meydana gelmez", "Yalnız tahsil edilen nakit kadar", "Beş yıl sonraki toplam bedel kadar"],
        ["İşin tahmini toplam bedeli kadar", "Sınırsız olarak bütün sözleşme için", "Yalnız maliyet bedeli kadar", "Belge tutarından bağımsız olarak"],
        "Teslimden önce fatura düzenlenmesi, belgede gösterilen miktarla sınırlı vergiyi doğuran olay yaratır.",
        "Ön fatura bütün sözleşme bedelini değil, faturada gösterilen kısmı vergilendirir.",
        "3065 sayılı KDVK m. 10/b", "medium",
    ),
    r(
        "Altı aylık projede hizmetin aylık kısımlar hâlinde tamamlanacağı kararlaştırılmıştır. Vergiyi doğuran olay nasıl oluşur?",
        "Kısım kısım teslim veya hizmette vergiyi doğuran olay hangi zamanda meydana gelir?",
        "Her kısmın tamamlandığı anda", "Her kısmın teslimi veya ifası sırasında",
        ["Yalnız bütün proje sona erince", "Sözleşme imzalanır imzalanmaz tamamı için", "Bedelin son taksiti ödenince", "Mükellef faaliyetini bırakınca"],
        ["Yalnız ilk kısımda bütün iş için", "Herhangi bir teslim olmadan", "Beşinci yılın sonunda", "Alıcının tercih ettiği tek dönemde"],
        "Kısım kısım yapılan işlerde her kısmın teslimi veya bir kısım hizmetin yapılması ayrı vergiyi doğuran olaydır.",
        "Dönemsel ifalarda vergileme, her bir kısmın gerçekleşmesine paralel yürür.",
        "3065 sayılı KDVK m. 10/c", "medium",
    ),
    r(
        "Mal konsinye olarak komisyoncuya gönderilmiş, ancak henüz nihai alıcıya teslim edilmemiştir. Vergiyi doğuran olay ne zaman meydana gelir?",
        "Komisyoncu veya konsinyasyon yoluyla satışta vergiyi doğuran olayın anı hangisidir?",
        "Malın nihai alıcıya tesliminde", "Malların alıcıya verildiği anda",
        ["Mal komisyoncuya ulaşır ulaşmaz", "Konsinye sözleşmesi imzalanınca", "Satıcı malı üretince", "Komisyoncu fiyat belirleyince"],
        ["Mal komisyoncu deposuna girince", "Komisyon sözleşmesi görüşülürken", "Satıcı siparişi alınca", "Alıcının kimliği bilinmeden önce"],
        "Konsinyasyon satışında vergiyi doğuran olay malın komisyoncuya değil, alıcıya teslimiyle meydana gelir.",
        "Komisyoncuya gönderme nihai teslim değildir; KDV olayı malın alıcıya verilmesinde oluşur.",
        "3065 sayılı KDVK m. 10/d", "hard",
    ),
    r(
        "Satıcı malı alıcıya göndermek üzere taşıyıcıya teslim etmiştir. Vergiyi doğuran olay bakımından hangi an esas alınır?",
        "Gönderilen malda nakliyeye başlanması veya malın taşıyıcıya verilmesi nasıl sonuç doğurur?",
        "Taşıyıcıya verildiği anda teslim oluşur", "Vergiyi doğuran mal teslimi gerçekleşir",
        ["Mal alıcı tarafından tüketilince", "Bedel tahsil edilince", "Garanti süresi dolunca", "Alıcı malı yeniden satınca"],
        ["Yalnız taşıma hizmeti doğar", "Teslim alıcının satışına kadar ertelenir", "KDV olayı hiçbir zaman oluşmaz", "Sadece irsaliye hükümsüz olur"],
        "Malın alıcıya gönderilmesinde nakliyeye başlanması veya taşıyıcıya tevdi teslim sayılır.",
        "Tasarruf sürecinin alıcı yönünde fiilen başlaması vergiyi doğuran olayı meydana getirir.",
        "3065 sayılı KDVK m. 2/1 ve 10/e", "medium",
    ),
    r(
        "Elektrik dağıtımında tüketim bedeli abone adına tahakkuk ettirilmiştir. Vergiyi doğuran olay ne zaman meydana gelir?",
        "Su, elektrik, gaz ve benzeri enerji dağıtımlarında KDV olayı hangi anda doğar?",
        "Bedelin tahakkuk ettirildiği anda", "Dağıtım bedelinin tahakkukunda",
        ["Abone ilk kez başvurduğunda", "Sayaç üretildiğinde", "Dağıtım şirketi kurulunca", "Bedel icra yoluyla tahsil edilince"],
        ["Abonelik sözleşmesi taslakken", "Enerji santrali tamamlanınca", "Fatura zamanaşımına uğrayınca", "Abone taşınmazı satınca"],
        "Enerji dağıtım ve kullanımlarında vergiyi doğuran olay bedelin tahakkuk ettirilmesiyle oluşur.",
        "Kanun sürekli dağıtım işlemlerinde tahakkuk anını özel vergiyi doğuran olay olarak belirler.",
        "3065 sayılı KDVK m. 10/g", "hard",
    ),
    r(
        "Gümrük vergisine tabi olmayan bir malın ithalatında gümrük beyannamesi tescil edilmiştir. KDV bakımından vergiyi doğuran olay hangisidir?",
        "Gümrük vergisine tabi olmayan ithalatta KDV'yi doğuran olay ne zaman meydana gelir?",
        "Gümrük beyannamesinin tescilinde", "İthalat beyannamesinin tescil edildiği anda",
        ["Mal yurt dışında üretilince", "Sipariş verildiğinde", "Döviz satın alındığında", "İthalatçı faaliyetini bırakınca"],
        ["Yabancı satıcı fiyat teklif edince", "Taşıma sözleşmesi kurulunca", "Mal yurt dışında depolanınca", "İthalatçı bilanço çıkarınca"],
        "Gümrük vergisine tabi olmayan ithalatta vergiyi doğuran olay gümrük beyannamesinin tescilidir.",
        "İthalatta vergiyi doğuran olay, gümrük yükümlülüğünün başlamasına veya beyanname tesciline bağlanmıştır.",
        "3065 sayılı KDVK m. 10/ı", "hard",
    ),
    r(
        "Türkiye'deki satıcı, malı yurt dışındaki müşteriye teslim etmiş ve mal Türkiye gümrük bölgesinden çıkmıştır. Diğer şartlar da sağlanmıştır. İşlemin niteliği nedir?",
        "Bir teslimin ihracat teslimi sayılmasında mal yönünden aranan temel koşul hangisidir?",
        "İhracat istisnası uygulanır", "Malın Türkiye gümrük bölgesinden çıkması",
        ["Yurt içi teslim olarak mutlaka vergilenir", "Yalnız alıcının yabancı olması yeterlidir ve başka koşul aranmaz", "İthalat işlemi sayılır", "Sadece damga vergisi istisnası doğar"],
        ["Malın Türkiye'de tüketilmesi", "Alıcının Türkiye'de yerleşik olması", "Malın satıcı deposunda kalması", "Bedelin yalnız nakit ödenmesi"],
        "Yurt dışındaki müşteriye yapılan ve Türkiye gümrük bölgesinden çıkan mal teslimi ihracat istisnasının temel koşullarını taşır.",
        "İhracat tesliminde alıcının yurt dışındaki müşteri olması yanında malın Türkiye gümrük bölgesinden çıkması gerekir.",
        "3065 sayılı KDVK m. 11/1-a ve 12/1", "medium",
    ),
    r(
        "Türkiye'deki danışmanlık şirketi yurt dışındaki müşteri için hizmet vermiş; hizmetten yalnız yurt dışında faydalanılmıştır. Diğer şartlar da sağlanmıştır. Sonuç nedir?",
        "Bir hizmetin hizmet ihracı kapsamında değerlendirilebilmesi için faydalanma nerede gerçekleşmelidir?",
        "Hizmet ihracı istisnası uygulanabilir", "Hizmetten yurt dışında faydalanılmalıdır",
        ["Hizmet mutlaka yurt içi işlem sayılır", "Müşterinin yabancı olması tek başına her koşulda yeterlidir", "İşlem mal ithalatı sayılır", "Yalnız kurumlar vergisi istisnası doğar"],
        ["Yalnız Türkiye'de faydalanılmalıdır", "Faydalanma yeri önem taşımaz", "Mutlaka satıcının işyerinde tüketilmelidir", "Hizmet alıcıya hiç sunulmamalıdır"],
        "Yurt dışındaki müşteri için yapılan ve yurt dışında faydalanılan hizmet, diğer koşullarla birlikte hizmet ihracı istisnasına girebilir.",
        "Hizmet ihracında hizmetin yurt dışındaki müşteri için yapılması ve hizmetten yurt dışında faydalanılması aranır.",
        "3065 sayılı KDVK m. 11/1-a ve 12/2", "hard",
    ),
    r(
        "Mükellef KDVK m. 11 kapsamındaki ihracat teslimi için girdiler yüklenmiş ve bu vergileri hesaplanan vergiden indirememiştir. Kanuni koşullarla sonuç ne olabilir?",
        "KDVK m. 32 kapsamındaki tam istisna işlemlere ait yüklenilen ve indirilemeyen KDV nasıl giderilir?",
        "İndirim yoluyla giderilemeyen kısım iade edilebilir", "Kanuni usulle iade konusu yapılabilir",
        ["Her durumda gider olarak yok edilir", "Mükellefin sermayesine eklenir", "Vergi ziyaı cezasına dönüşür", "Çalışan ücretine mahsup edilir"],
        ["İade hiçbir koşulda mümkün değildir", "Yalnız satış hasılatına eklenir", "Ortaklara kâr payı olarak dağıtılır", "Kendiliğinden gelir vergisine mahsup edilir"],
        "Tam istisna işlemlere ait yüklenilen KDV önce indirilir; indirimle giderilemeyen tutar kanuni koşullarla iade edilebilir.",
        "KDVK m. 32, sayılan istisnalara ilişkin yüklenilen ve indirilemeyen vergiyi iade mekanizmasına bağlar.",
        "3065 sayılı KDVK m. 32", "hard",
    ),
]


PREMISES = [
    {"stem":"KDV'nin konusu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Türkiye'de ticari faaliyet kapsamında yapılan teslimler KDV'ye tabidir\n\nII. Her türlü mal ve hizmet ithalatı genel olarak KDV'nin konusuna girer\n\nIII. İşlemi yapanın kamu tüzel kişisi olması tek başına vergilemeyi önlemez","correct":"I, II ve III","why":"Üç ifade de KDVK m. 1'deki konu ve statüden bağımsızlık kurallarına uygundur.","ref":"3065 sayılı KDVK m. 1","difficulty":"easy"},
    {"stem":"Mal teslimi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tasarruf hakkının devri teslimin temelidir\n\nII. Alıcının gösterdiği kişiye tevdi teslim hükmündedir\n\nIII. Trampa yalnız tek teslim sayılır","correct":"I ve II","why":"Tasarruf hakkı devri ve alıcının gösterdiği yere tevdi teslimdir; trampa iki ayrı teslimdir.","ref":"3065 sayılı KDVK m. 2","difficulty":"medium"},
    {"stem":"Teslim sayılan hâller bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Vergiye tabi malın işletme dışı amaçla çekilmesi teslim sayılır\n\nII. Personele vergiye tabi malın hediye edilmesi teslim sayılmaz\n\nIII. Mülkiyeti muhafaza kaydıyla satışta zilyetlik devri teslimdir","correct":"I ve III","why":"İşletmeden çekiş ve mülkiyeti muhafazada zilyetlik devri teslimdir; personele vergiye tabi mal verilmesi de teslim sayıldığından II yanlıştır.","ref":"3065 sayılı KDVK m. 3","difficulty":"medium"},
    {"stem":"Hizmet kavramı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Onarma ve kiralama hizmet değildir\n\nII. Karşılıksız yararlandırma hizmet sayılabilir\n\nIII. Hizmet karşılığı mal alınırsa her edim ayrı değerlendirilir","correct":"II ve III","why":"Onarma ve kiralama hizmettir; karşılıksız yararlandırma hizmet sayılabilir ve karşılıklı edimler ayrı değerlendirilir.","ref":"3065 sayılı KDVK m. 4-5","difficulty":"medium"},
    {"stem":"İşlemin Türkiye'de yapılması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Malın teslim anında Türkiye'de bulunması yer ölçütüdür\n\nII. Hizmetten faydalanılan yer hiçbir durumda dikkate alınmaz\n\nIII. Satıcının yabancı olması işlemi her durumda Türkiye dışına taşır","correct":"Yalnız I","why":"Malın teslim anındaki konumu esastır; hizmetten Türkiye'de faydalanma da yer ölçütüdür ve satıcının uyruğu tek başına belirleyici değildir.","ref":"3065 sayılı KDVK m. 6","difficulty":"medium"},
    {"stem":"Vergiyi doğuran olay bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Genel olarak teslim veya hizmet ifasında doğar\n\nII. Önceden düzenlenen faturada gösterilen miktar için doğabilir\n\nIII. Kısım kısım işlerde her kısmın ifası ayrı olay yaratır","correct":"I, II ve III","why":"Üç ifade de KDVK m. 10'daki genel ve özel vergiyi doğuran olay kurallarına uygundur.","ref":"3065 sayılı KDVK m. 10/a-c","difficulty":"hard"},
    {"stem":"Özel vergiyi doğuran olaylar bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Konsinyasyonda malın alıcıya teslimi esastır\n\nII. Enerji dağıtımında yalnız bedelin tahsili esastır\n\nIII. Gümrük vergisine tabi olmayan ithalatta beyanname tescili esastır","correct":"I ve III","why":"Konsinyasyonda nihai teslim, ithalatta beyanname tescili esastır; enerjide tahsil değil tahakkuk ölçüt alınır.","ref":"3065 sayılı KDVK m. 10/d, g ve ı","difficulty":"hard"},
    {"stem":"İstisna ve indirim ilişkisi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tam istisna işlemde indirilemeyen yüklenim kanuni koşullarla iade edilebilir\n\nII. İndirim hakkı tanınmayan istisna işleme ait KDV genel olarak indirilemez\n\nIII. Hizmet ihracında yurt dışında faydalanma koşulu aranmaz","correct":"I ve II","why":"Tam istisnada iade yolu vardır; kısmi istisnada indirim yasağı uygulanır; hizmet ihracında yurt dışında faydalanma aranır.","ref":"3065 sayılı KDVK m. 12, 30/a ve 32","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="katma_deger_vergisi",
        topic_id="kdv_teslim_ve_indirim",
        label="KDV'de Teslim, Hizmet ve İndirim",
        slug="kdv_teslim_ve_indirim",
        prefix="topic-kdv-ti",
        seed=170732,
        legislation_version="3065 sayılı Katma Değer Vergisi Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
