#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Meslek Hukuku — Çalışma Usulleri, 3×20."""
from topic_pack_builder import write_topic


SHORT = {
    "Meslek kütüğünde": "Odanın genel meslek kütüğünde",
    "Çalışanlar listesine": "Odanın çalışanlar listesine",
    "Otuz gün": "Alınmasından itibaren otuz gün",
    "Fiilen mesleki faaliyet yürütenleri göstermek": "Aktif meslek mensuplarını göstermek",
    "Ayrı şirketler ve ortaklıklar bölümüne": "Ayrı bir şirket-ortaklık bölümüne",
    "Evet; elektronik sistem üzerinden alınabilir": "Evet; elektronik başvuru mümkündür",
    "Eski odadan dosya getirtilip eksikler tamamlatılır": "Dosya getirtilir ve tamamlatılır",
    "Hayır; otuz gün içinde bildirilir": "Hayır; otuz günde bildirilir",
    "Başka faaliyetle iç içe olmayan bağımsız büro": "Diğer işlerden ayrı mesleki büro",
    "Hayır; Birlik Yönetim Kurulu şart belirleyebilir": "Hayır; şartları Birlik belirleyebilir",
    "Hayır; izin verilen unsurlarla sınırlıdır": "Hayır; izinli içerikle sınırlıdır",
    "Hayır; yönetmelikteki içerikle sınırlıdır": "Hayır; izinli içerikle sınırlıdır",
    "Yeni kimlik verilir, eskisi iptal edilir": "Eski kimlik iptal edilir",
    "Hayır; sürekli müşavirlikte sözleşme zorunludur": "Hayır; yazılı sözleşme zorunludur",
    "Defter, sürekli müşavirlik, denetim-rapor ve tasdik işleri": "Defter, müşavirlik, denetim ve tasdik",
    "Hayır; zorunlu sözleşme unsurları eksiktir": "Hayır; asgari unsurlar eksiktir",
    "Hayır; güvenilmez belge haklı fesih nedenidir": "Hayır; güvenilmez belge haklı nedendir",
    "Ücretin ödenmemesi veya belgenin güvenilmezliği": "Ödenmeyen ücret veya güvenilmez belge",
    "Hayır; bir ay içinde tutanakla iade edilmelidir": "Hayır; bir ayda tutanakla iade",
    "Bir ay içinde devir-teslim tutanağıyla": "Bir ayda tutanakla",
    "Evet; aynı unvandaki meslek mensupları kurabilir": "Evet; aynı unvanlılar kurabilir",
    "Hayır; tasdik ve defter tutma yapılamaz": "Hayır; bu iki hizmet verilemez",
    "Tasdik ile defter ve beyanname düzenleme": "Tasdik ve defter tutma işleri",
    "Üyelik mümkündür; ilgili şirkete mesleki hizmet veremez": "Üyelik var; mesleki hizmet yok",
}


def r(s, f, c, d, w, ref, difficulty="medium", fc=None, fd=None):
    c = SHORT.get(c, c)
    fc = SHORT.get(fc or c, fc or c)
    return {"scenario": s, "focus": f, "correct": c, "focus_correct": fc,
            "distractors": list(d), "focus_distractors": list(fd or d), "why": w,
            "focus_why": f"Çalışma usulünün odak sonucu şudur: {w}",
            "ref": ref, "difficulty": difficulty}


RULES = [
    r("Ruhsatlı olup odada kayıtlı ancak fiilen mesleki faaliyet yürütmeyen kişinin kaydı hangi ana sicilde bulunur?", "2026 düzeninde odaya kayıtlı her meslek mensubunun yer aldığı kayıt hangisidir?", "Meslek kütüğünde", ["Yalnız çalışanlar listesinde", "Ticaret sicili gazetesinde", "Stajyer yoklama defterinde", "Müşteri sözleşme listesinde"], "Meslek kütüğü, fiilen çalışıp çalışmadığına bakılmaksızın odaya kayıtlı her meslek mensubunu içerir.", "Çalışma Usulleri Yönetmeliği m. 11 (14.01.2026 değişikliği)", "easy"),
    r("Odaya kayıtlı SMMM fiilen bağımsız mesleki faaliyete başlamıştır. Hangi listeye ayrıca kaydolmalıdır?", "Çalışanlar listesinin ayırt edici işlevi nedir?", "Çalışanlar listesine", ["Yalnız aday meslek kütüğüne", "Ticaret sicilinin ihracat bölümüne", "Vergi mahkemesi siciline", "Müşteri personel listesine"], "Fiilen mesleki faaliyette bulunan meslek mensupları çalışanlar listesine yazılır.", "Çalışma Usulleri Yönetmeliği m. 11 (14.01.2026 değişikliği)", "easy", fc="Fiilen mesleki faaliyet yürütenleri göstermek"),
    r("Mesleki şirket çalışanlar listesine kaydedilecektir. Listede nereye yazılır?", "Ortaklık büroları ve mesleki şirketler çalışanlar listesinde nasıl izlenir?", "Ayrı şirketler ve ortaklıklar bölümüne", ["Meslek mensuplarının aile bölümüne", "Staj yoklama çizelgesine", "Disiplin cezaları cetveline", "Müşteri borçları bölümüne"], "Ortaklık büroları ve şirketler çalışanlar listesinin ayrı bir bölümüne kaydolur.", "Çalışma Usulleri Yönetmeliği m. 11", "easy"),
    r("Bağımsız büro açacak meslek mensubu çalışanlar listesine kayıt için hangi odaya başvurmalıdır?", "Çalışanlar listesi başvurusunda yetkili oda hangi ölçüte göre belirlenir?", "İşyerinin bağlı olduğu odaya", ["Doğum yerindeki odaya", "Müşterinin seçtiği herhangi bir odaya", "Yalnız TÜRMOB merkezine", "İlk öğrenim gördüğü ildeki odaya"], "Başvuru, mesleki işyerinin bağlı olduğu ilgili odaya yapılır.", "Çalışma Usulleri Yönetmeliği m. 11", "easy"),
    r("Meslek mensubu çalışanlar listesi başvurusunu e-Birlik benzeri elektronik sistem üzerinden dilekçeyle yapmıştır. Usule uygun mudur?", "2026 değişikliğine göre çalışanlar listesi başvuru dilekçesi nasıl alınabilir?", "Evet; elektronik sistem üzerinden alınabilir", ["Hayır; yalnız noter huzurunda verilir", "Sadece sözlü başvuru yapılır", "Yalnız vergi mahkemesine sunulur", "Elektronik başvuru kesinlikle yasaktır"], "2026 işlenmiş metin, başvuru dilekçesinin elektronik sistemler üzerinden alınmasına izin verir.", "Çalışma Usulleri Yönetmeliği m. 11 (14.01.2026 değişikliği)", "medium", fc="Elektronik sistemler üzerinden"),
    r("Başvuruda dört ay önce alınmış adli sicil belgesi sunulmuştur. Güncellik şartı bakımından yeterli midir?", "Çalışanlar listesi başvurusundaki adli sicil belgesinin azami yaşı nedir?", "Hayır; otuz günden eski olmamalıdır", ["Evet; beş yıl geçerlidir", "Belge için tarih şartı yoktur", "Yalnız on yıl önceki belge kabul edilir", "Adli sicil belgesi hiçbir zaman istenmez"], "Başvuruya, alınmasının üzerinden otuz gün geçmemiş ve arşiv bilgisi içeren adli sicil belgesi eklenir.", "Çalışma Usulleri Yönetmeliği m. 11", "medium", fc="Otuz gün"),
    r("YMM çalışanlar listesine başvururken yemin belgesini eklememiştir. Başvuru belgesi bakımından eksiklik var mıdır?", "YMM'ye özgü çalışanlar listesi başvuru belgesi hangisidir?", "Evet; yemin belgesini eklemelidir", ["Hayır; YMM yemini bulunmaz", "Yalnız müşterinin izin belgesi gerekir", "Sadece staj tezkiyesi eklenir", "Ticaret sicili belgesi yemin yerine geçer"], "YMM, başvurusuna yemin ettiğini gösteren yemin belgesini ekler.", "Çalışma Usulleri Yönetmeliği m. 11", "easy", fc="Yemin ettiğine dair belge"),
    r("Meslek mensubu ruhsat aldığı odadan başka bir odaya çalışanlar listesi için başvurmuştur. Dosya nasıl incelenir?", "Başka odada bulunan ruhsat dosyası bakımından uygulanacak işlem nedir?", "Eski odadan dosya getirtilip eksikler tamamlatılır", ["Dosya hiç incelenmeden yok edilir", "Yeni ruhsat sıfırdan sınavsız verilir", "Yalnız müşteri beyanı kabul edilir", "Başvuru her durumda reddedilir"], "Başka odaya başvuruda ruhsat dosyası getirtilip incelenir ve eksik belgeler tamamlatılır.", "Çalışma Usulleri Yönetmeliği m. 12", "medium", fc="Dosyanın getirtilmesi ve incelenmesi"),
    r("Ortaklık bürosu kuran meslek mensupları kuruluş belgesini iki ay sonra odaya vermiştir. Süreye uygun mudur?", "Ortaklık bürosu veya şirket belgeleri merkez ve şubenin bağlı olduğu odaya ne kadar sürede verilir?", "Hayır; bir ay içinde verilmelidir", ["Evet; beş yıl içinde yeterlidir", "Süre bulunmamaktadır", "Yalnız şirket kapanırken verilir", "Belge odaya hiçbir zaman verilmez"], "Kuruluş belgeleri ortaklarca merkez ve şubelerin bağlı olduğu odalara bir ay içinde sunulur.", "Çalışma Usulleri Yönetmeliği m. 13", "medium", fc="Bir ay içinde"),
    r("Meslek mensubu faaliyete başlamış ancak oda bilgisi dışında işyeri açmıştır. Temel yükümlülük nedir?", "Mesleki faaliyete başlamadan önce büro edinme bakımından kural hangisidir?", "Oda bilgisinde işyeri açmak", ["İşyeri açmadan sınırsız müşteri kabul etmek", "Büroyu odaya gizlemek", "Yalnız müşterinin evini kullanmak", "Ruhsatı başka kişiye kullandırmak"], "Meslek mensubu faaliyete başlamadan önce bağlı olduğu oda bilgisinde işyeri açar.", "Çalışma Usulleri Yönetmeliği m. 14", "easy"),
    r("İşyeri açılışı odaya kırk gün sonra bildirilmiştir. Güncel bildirim süresine uygun mudur?", "İşyeri açılış ve kapanışları odaya en geç ne zaman bildirilir?", "Hayır; otuz gün içinde bildirilir", ["Evet; bir yıl içinde bildirilir", "Bildirim için süre yoktur", "Sadece kapanış bildirilir", "Odaya bildirim yasaktır"], "İşyeri açılış ve kapanışları en geç otuz gün içinde odaya bildirilir.", "Çalışma Usulleri Yönetmeliği m. 14", "medium", fc="Otuz gün içinde"),
    r("Meslek mensubu ana bürosuna ek olarak yalnız iletişim amacıyla irtibat bürosu açmıştır. Mümkün müdür?", "Meslek mensubu, ortaklık bürosu veya şirket irtibat bürosu açabilir mi?", "Hayır; irtibat bürosu açılamaz", ["Evet; sınırsız irtibat bürosu açılır", "Yalnız müşteri izni yeterlidir", "Sadece başka odada açılabilir", "İrtibat bürosu zorunludur"], "Meslek mensupları, ortaklık büroları ve mesleki şirketler irtibat bürosu açamaz.", "Çalışma Usulleri Yönetmeliği m. 14", "easy"),
    r("Mesleki büro bir ticarethaneyle iç içe aynı mekânda faaliyet göstermektedir. Büro standardına uygun mudur?", "Mesleki işyerinin bağımsızlığı bakımından temel kural hangisidir?", "Hayır; büro bağımsız olmalıdır", ["Evet; her ticarethane içinde olabilir", "Yalnız ruhsatsız işlemler yapılmalıdır", "Büro müşterinin deposu olmalıdır", "İşyeri standardı bulunmamaktadır"], "Açılan işyeri bağımsız büro olmalı, başka serbest meslek faaliyeti veya ticarethane ile iç içe olmamalıdır.", "Çalışma Usulleri Yönetmeliği m. 14", "easy", fc="Başka faaliyetle iç içe olmayan bağımsız büro"),
    r("SMMM, ev-ofis kullanımının 2026 düzeninde hiçbir koşulda mümkün olmadığını söylemektedir. Bu mutlak ifade doğru mudur?", "2026 değişikliğinde ev-ofis veya paylaşımlı ofis için hangi makam şart belirleyebilir?", "Hayır; Birlik Yönetim Kurulu şart belirleyebilir", ["Evet; hiçbir istisna veya yetki yoktur", "Yalnız müşteri kuralları belirler", "Vergi mahkemesi her büroya izin verir", "Stajyer tek başına şart koyar"], "2026 değişikliği, kıdem, müşteri ve çalışan sayısı gibi ölçütlerle ev-ofis veya paylaşımlı ofis şartlarını belirleme yetkisini Birlik Yönetim Kuruluna verir.", "Çalışma Usulleri Yönetmeliği m. 14 (14.01.2026 değişikliği)", "hard", fc="Birlik Yönetim Kurulu"),
    r("Büro edinen meslek mensubu odaya kaydından dört ay sonra Büro Tescil Belgesi almak istemektedir. Süreye uygun mudur?", "Büro Tescil Belgesi odaya kayıttan itibaren ne kadar sürede alınır?", "Hayır; üç ay içinde alınmalıdır", ["Evet; beş yıl içinde alınır", "Belge almak isteğe bağlıdır", "Yalnız büro kapanınca alınır", "Süre on yıldır"], "Büro edinen meslek mensubu odaya kaydolduktan sonra üç ay içinde Büro Tescil Belgesi alır.", "Çalışma Usulleri Yönetmeliği m. 14", "medium", fc="Üç ay içinde"),
    r("Büro Tescil Belgesi üç yıldır vize edilmemiştir. Vize dönemi bakımından doğru uygulama nedir?", "Büro Tescil Belgesi hangi aralıkla vize ettirilir?", "İki yılda bir vize ettirilir", ["Her ay vize edilir", "Vize hiçbir zaman yapılmaz", "On yılda bir vize edilir", "Yalnız müşteri değişince vize edilir"], "Büro Tescil Belgesi iki yılda bir vize ettirilir; 2026 metni elektronik düzenleme ve vizeye de izin verir.", "Çalışma Usulleri Yönetmeliği m. 14", "medium"),
    r("Meslek mensubu tabela asmak istememektedir. Çalışma usulüne göre tabela zorunlu mudur?", "Mesleki büroda tabela asılmasının niteliği nedir?", "Hayır; tabela asılması isteğe bağlıdır", ["Evet; her cephede üç tabela zorunludur", "Yalnız ışıklı tabela zorunludur", "Tabela yerine müşteri adı yazılır", "Tabelada reklam yapmak zorunludur"], "Meslek mensubunun tabela asması ihtiyaridir; asılırsa yönetmelikteki içerik ve biçim kurallarına uyulur.", "Çalışma Usulleri Yönetmeliği m. 15", "easy", fc="İhtiyaridir"),
    r("Meslek mensubu tabelasında meslek unvanı dışında yanıltıcı yabancı ifadeler ve fotoğraflar kullanmıştır. Uygun mudur?", "Mesleki tabelada yönetmelikte izin verilmeyen ifade ve görsellere yer verilebilir mi?", "Hayır; izin verilen unsurlarla sınırlıdır", ["Evet; bütün reklam içerikleri serbesttir", "Yalnız müşteri fotoğrafı zorunludur", "Tabelada unvan kullanmak yasaktır", "Işıklı reklam her durumda zorunludur"], "Tabela; unvan, ad, iletişim ve izinli akademik/mesleki unsurlarla sınırlıdır; başka ifadeler ve görseller kullanılamaz.", "Çalışma Usulleri Yönetmeliği m. 15", "medium", fc="Hayır; yönetmelikteki içerikle sınırlıdır"),
    r("Meslek mensubu başka oda bölgesine nakledilmiş ancak eski kimlik belgesini kullanmayı sürdürmüştür. Doğru işlem nedir?", "İşyeri başka oda bölgesine nakledilince kimlik belgesi ne olur?", "Yeni kimlik verilir, eskisi iptal edilir", ["Eski kimlik süresiz kullanılır", "Kimlik müşteriye devredilir", "Ruhsat otomatik olarak yok olur", "Kimlik belgesi hiç düzenlenmez"], "Başka oda bölgesine nakil veya ad-soyad değişikliğinde yeni kimlik verilir ve eskisi iptal edilir.", "Çalışma Usulleri Yönetmeliği m. 16", "medium"),
    r("SMMM sürekli müşavirlik hizmetini yazılı sözleşme olmadan yürütmektedir. Usule uygun mudur?", "Hangi işlerde mesleki sözleşme zorunludur?", "Hayır; sürekli müşavirlikte sözleşme zorunludur", ["Evet; hiçbir mesleki işte sözleşme gerekmez", "Yalnız tek seferlik tanışmada zorunludur", "Sözleşme sadece staj için yapılır", "Müşteri istemezse bütün sözleşmeler yasaktır"], "Defter tutma, sürekli müşavirlik, inceleme-denetim-raporlama ve YMM tasdik işlerinde sözleşme zorunludur.", "Çalışma Usulleri Yönetmeliği m. 24", "medium", fc="Defter, sürekli müşavirlik, denetim-rapor ve tasdik işleri"),
    r("Mesleki sözleşmede işin kapsamı, ücret, süre ve taraf sorumlulukları gösterilmemiştir. Asgari içerik sağlanmış mıdır?", "Mesleki sözleşmenin asgari unsurlarından biri hangisidir?", "Hayır; zorunlu sözleşme unsurları eksiktir", ["Evet; boş sözleşme yeterlidir", "Yalnız meslek mensubunun adı yeterlidir", "Sözleşmede ücret yazılması yasaktır", "İşin kapsamı hiçbir zaman belirtilmez"], "Sözleşmede taraf bilgileri, amaç-kapsam, sorumluluklar, ücret-ödeme, yer, tarih ve süre bulunur.", "Çalışma Usulleri Yönetmeliği m. 25", "easy", fc="Amaç, kapsam, sorumluluk, ücret ve süre"),
    r("Müşteri sağlıksız ve güvenilmez belgeler vermesine rağmen meslek mensubunun sözleşmeyi feshedemeyeceğini ileri sürmüştür. Doğru mudur?", "Meslek mensubu bakımından haklı fesih nedenlerinden biri hangisidir?", "Hayır; güvenilmez belge haklı fesih nedenidir", ["Evet; sözleşme hiçbir zaman feshedilemez", "Yalnız müşterinin taşınması haklı nedendir", "Fesih için belgeler mutlaka yok edilmelidir", "Ücretin ödenmemesi önemsizdir"], "Ücretin ödenmemesi veya tevdi edilen belgelerin sağlıklı ve güvenilir olmaması meslek mensubu için haklı fesih nedenidir.", "Çalışma Usulleri Yönetmeliği m. 26", "medium", fc="Ücretin ödenmemesi veya belgenin güvenilmezliği"),
    r("Fesih sonrası defter ve belgeler iki ay elde tutulmuş ve tutanak düzenlenmemiştir. Usule uygun mudur?", "Fesihte defter ve belgelerin iade usulü hangisidir?", "Hayır; bir ay içinde tutanakla iade edilmelidir", ["Evet; süresiz saklanabilir", "Belgeler doğrudan imha edilir", "Yalnız rakibe teslim edilir", "Tutanak düzenlenmesi yasaktır"], "Fesihte alınmış defter ve belgeler bir ay içinde devir-teslim tutanağıyla sahibine iade edilir.", "Çalışma Usulleri Yönetmeliği m. 26", "medium", fc="Bir ay içinde devir-teslim tutanağıyla"),
    r("Aynı unvana sahip iki SMMM ortaklık bürosu kurmuştur. Unvan koşulu bakımından mümkün müdür?", "Ortaklık bürosu hangi unvan yapısıyla kurulabilir?", "Evet; aynı unvandaki meslek mensupları kurabilir", ["Hayır; ortaklık bürosu her durumda yasaktır", "Yalnız ruhsatsız kişiler kurabilir", "SMMM ile tacir ortak kurmak zorundadır", "Müşteriler ortaklık bürosuna ortak olur"], "Ortaklık bürosu aynı unvana sahip meslek mensupları arasında kurulabilir.", "Çalışma Usulleri Yönetmeliği m. 30/b", "easy", fc="Aynı unvana sahip meslek mensuplarınca"),
    r("SMMM ve YMM birlikte mesleki şirket kurmuş ve bu şirket üzerinden tasdik ile defter tutma hizmeti vermek istemiştir. Mümkün müdür?", "Karma unvanlı mesleki şirkette hangi iki hizmet verilemez?", "Hayır; tasdik ve defter tutma yapılamaz", ["Evet; bütün hizmetler sınırsız verilir", "Yalnız reklam hizmeti verilemez", "Sadece bilirkişilik yasaktır", "Yalnız eğitim hizmeti yasaktır"], "SMMM ve YMM'nin birlikte kurduğu mesleki şirkette tasdik hizmeti ile Kanun m. 2/A-a kapsamındaki defter-düzenleme işleri yapılamaz.", "Çalışma Usulleri Yönetmeliği m. 30/b (24.02.2025 değişikliği)", "hard", fc="Tasdik ile defter ve beyanname düzenleme"),
    r("SMMM anonim şirkette bağımsız yönetim kurulu üyesidir ve aynı şirkete mali müşavirlik hizmeti vermek istemektedir. Güncel kural nedir?", "2026 düzeninde bağımsız yönetim kurulu üyeliği hangi şartla ticari faaliyet sayılmaz?", "Üyelik mümkündür; ilgili şirkete mesleki hizmet veremez", ["Üyelik ve hizmet birlikte koşulsuz serbesttir", "Bağımsız üyelik her durumda tacirliktir", "Yalnız şirket çalışanı karar verir", "Üyelik SMMM ruhsatını kendiliğinden kaldırır"], "Bağımsız yönetim kurulu üyeliği ticari faaliyet sayılmaz; ancak meslek mensubu o şirkete ve bağlı şirketlerine Kanun m. 2 kapsamında hizmet veremez.", "Çalışma Usulleri Yönetmeliği m. 43 (14.01.2026 değişikliği)", "hard", fc="Şirkete mesleki hizmet vermeme şartıyla"),
]


PREMISES = [
    {"stem":"Meslek kütüğü ve çalışanlar listesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Meslek kütüğünde odaya kayıtlı her meslek mensubu yer alır\n\nII. Çalışanlar listesi fiilen mesleki faaliyet yürütenleri gösterir\n\nIII. Ortaklık ve şirketler ayrı bölümde izlenir","correct":"I, II ve III","why":"Üç ifade de 2026 tarihli kayıt ayrımını doğru açıklar.","ref":"Çalışma Usulleri Yönetmeliği m. 11","difficulty":"easy"},
    {"stem":"Çalışanlar listesi başvurusu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dilekçe elektronik sistemden alınabilir\n\nII. Adli sicil belgesi güncel olmalıdır\n\nIII. YMM'den yemin belgesi istenmez","correct":"I ve II","why":"Elektronik dilekçe ve güncel adli sicil mümkündür; YMM yemin belgesi sunar.","ref":"Çalışma Usulleri Yönetmeliği m. 11","difficulty":"medium"},
    {"stem":"Büro düzeni bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İşyeri oda bilgisinde açılır\n\nII. İrtibat bürosu açılamaz\n\nIII. Büro başka ticarethane ile iç içe olabilir","correct":"I ve II","why":"Büro oda bilgisinde ve bağımsız açılır; irtibat bürosu yasaktır.","ref":"Çalışma Usulleri Yönetmeliği m. 14","difficulty":"medium"},
    {"stem":"2026 büro düzeni bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Birlik Yönetim Kurulu ev-ofis şartı belirleyebilir\n\nII. Büro Tescil Belgesi elektronik düzenlenebilir\n\nIII. Belge iki yılda bir vize edilir","correct":"I, II ve III","why":"Üç ifade de güncel işlenmiş yönetmelik metnine uygundur.","ref":"Çalışma Usulleri Yönetmeliği m. 14","difficulty":"hard"},
    {"stem":"Mesleki sözleşme bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Defter tutmada sözleşme zorunludur\n\nII. Sürekli müşavirlikte sözleşme zorunludur\n\nIII. Tasdik işinde sözleşme yapılması yasaktır","correct":"I ve II","why":"Defter, sürekli müşavirlik, denetim-rapor ve tasdikte sözleşme zorunludur.","ref":"Çalışma Usulleri Yönetmeliği m. 24","difficulty":"medium"},
    {"stem":"Sözleşmenin feshi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Güvenilmez belge haklı fesih nedeni olabilir\n\nII. Defterler iki ay sonra tutanaksız iade edilir\n\nIII. Tazminat hakları genel hukuk kurallarına tabidir","correct":"I ve III","why":"Güvenilmez belge haklı neden olabilir ve tazminat genel hukuka tabidir; defterler bir ay içinde tutanakla iade edilir.","ref":"Çalışma Usulleri Yönetmeliği m. 26","difficulty":"hard"},
    {"stem":"Mesleki ortaklık bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ortaklık bürosu farklı unvan sahiplerince kurulur\n\nII. Karma unvanlı şirkette tasdik yapılamaz\n\nIII. Karma unvanlı şirkette defter tutma işi yapılamaz","correct":"II ve III","why":"Ortaklık bürosu aynı unvan sahiplerince kurulur; karma şirkette tasdik ve defter tutma işleri yapılamaz.","ref":"Çalışma Usulleri Yönetmeliği m. 30","difficulty":"hard"},
    {"stem":"2026 bağımsız yönetim kurulu üyeliği bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bağımsız üyelik ticari faaliyet sayılmaz\n\nII. Üye olunan şirkete mesleki hizmet verilebilir\n\nIII. Bağlı şirketlere hizmet sınırlaması yoktur","correct":"Yalnız I","why":"Bağımsız üyelik istisnadır; üye olunan ve bağlantılı şirketlere mesleki hizmet verilemez.","ref":"Çalışma Usulleri Yönetmeliği m. 43","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(lesson_id="meslek_hukuku", topic_id="calisma_usulleri",
                label="Çalışma Usulleri", slug="calisma_usulleri",
                prefix="topic-mh-cu", seed=170745,
                legislation_version="Çalışma Usul ve Esasları Yönetmeliği, 14.01.2026 değişikliği işlenmiş 17.07.2026 metni",
                rules=RULES, premises=PREMISES, wrong_banks={})
