#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Finansal Tablolar ve Analizi — Nakit Akış Analizi, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": distractors, "focus_distractors": focus_distractors,
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Bir işletmenin dönem içindeki nakit giriş ve çıkışları esas, yatırım ve finansman faaliyetleri itibarıyla raporlanmıştır. Hazırlanan temel tablo hangisidir?",
        "Nakit akış tablosunun başlıca amacı aşağıdakilerden hangisidir?",
        "Nakit akış tablosu",
        "Nakit değişimini üç faaliyet türüne göre açıklamak",
        ["Finansal durum tablosu", "Kâr veya zarar tablosu", "Özkaynak değişim tablosu", "Satışların maliyeti tablosu"],
        ["Tahakkuk esaslı dönem kârını tek başına ve bütün ayrıntılarıyla hesaplamak", "Bütün varlıkları gerçeğe uygun değere çevirmek", "Yalnız finansman borçlarının vadesini göstermek", "Gelecekteki nakdi kesin olarak tahmin etmek"],
        "TMS 7, dönem nakit akışlarını üç faaliyet sınıfında sunarak nakit ve nakit benzeri değişimini açıklar.",
        "Tablo, nakit yaratma ve kullanma biçimini; esas, yatırım ve finansman faaliyetleri ayrımında gösterir.",
        "TMS 7 par. 1, 6 ve amaç", "easy",
    ),
    r(
        "İşletme, edinildiğinde vadesine iki ay kalan, belirli tutarda nakde kolayca çevrilen ve değer değişim riski önemsiz bir yatırımı nakit benzeri saymıştır. Yaklaşım uygun mudur?",
        "Bir yatırımın nakit benzeri olabilmesi için aşağıdakilerden hangisi birlikte aranır?",
        "Evet; kısa vadeli, yüksek likit ve önemsiz değer değişim risklidir",
        "Kolay nakde dönüşüm, yüksek likidite ve önemsiz değer riski",
        ["Hayır; bütün kısa vadeli yatırımlar değer değişim riskine bakılmadan finansman faaliyeti sayılır", "Hayır; yalnız kasadaki para nakit benzeridir", "Evet; vadesi ne olursa olsun her menkul kıymet dahildir", "Evet; yüksek getiri sağlaması tek başına yeterlidir"],
        ["Uzun vadeli olması, nakde dönüşümünün belirsiz ve değer riskinin yüksek bulunması", "Yalnız özkaynağa dayalı araç niteliği taşıması", "Getirisinin piyasa ortalamasından yüksek olması", "İşletmenin bir yıldan uzun süre elde tutma amacı"],
        "TMS 7 tanımı bu üç niteliği birlikte arar; edinimden itibaren üç ay veya daha kısa vade genellikle kısa vadeye örnektir.",
        "Nakit benzerleri yatırım amacıyla değil, kısa vadeli nakit taahhütlerini karşılamak için tutulur.",
        "TMS 7 par. 6-7", "medium",
    ),
    r(
        "Vadesiz ve talep edildiğinde geri ödenen banka kredili mevduat hesabı işletmenin günlük nakit yönetiminin ayrılmaz parçasıdır; bakiye sıkça artıdan eksiye dönmektedir. Nakit tablosunda nasıl ele alınabilir?",
        "Bir banka nezdindeki borç bakiyesinin istisnaen nakit ve nakit benzerinin parçası sayılabilmesi için hangi özellik önemlidir?",
        "Nakit ve nakit benzerlerinin bir bileşeni olarak değerlendirilebilir",
        "Talep üzerine ödeme ve günlük nakit yönetimiyle bütünleşme",
        ["Her durumda yatırım faaliyeti olarak gösterilir", "Her durumda uzun vadeli finansman çıkışı olarak ve nakitten ayrı raporlanır", "Kâr veya zarar tablosundan mahsup edilir", "Nakit akış tablosuna hiçbir biçimde alınmaz"],
        ["Sabit beş yıllık vadeye, değişmez bakiyeye ve nakit yönetiminden ayrı kullanıma sahip olması", "Yalnız maddi duran varlık alımında kullanılması", "Faiz oranının bütün mevduatlardan yüksek olması", "Özkaynak aracı şeklinde ihraç edilmiş olması"],
        "TMS 7'nin dar istisnası, talep üzerine ödenen ve nakit yönetiminin ayrılmaz parçası olan kredili mevduat hesapları içindir.",
        "Olağan banka borçları finansman faaliyetidir; istisnada günlük nakit yönetimi niteliği belirleyicidir.",
        "TMS 7 par. 8", "hard",
    ),
    r(
        "Müşterilerden tahsilatlar, makine alımı ve banka kredisi kullanımı aynı dönemde gerçekleşmiştir. Nakit akış tablosunda sırasıyla hangi sınıflara girer?",
        "TMS 7'de dönem nakit akışlarının ana sınıfları hangileridir?",
        "Esas, yatırım ve finansman faaliyetleri",
        "Esas faaliyetler, yatırım faaliyetleri ve finansman faaliyetleri",
        ["Yatırım, esas ve finansman faaliyetleri", "Esas, finansman ve yatırım faaliyetleri", "Finansman, yatırım ve esas faaliyetler", "Yalnız esas ve yatırım faaliyetleri"],
        ["Cari varlık, duran varlık ve özkaynak değişimlerinin sınıflandırıldığı faaliyetler", "Gelir, gider ve kâr faaliyetleri", "Tahakkuk, değerleme ve raporlama faaliyetleri", "Üretim, satış ve vergi faaliyetleri"],
        "Müşteri tahsilatı ana hasılat faaliyeti, makine alımı uzun vadeli varlık yatırımı, kredi kullanımı finansman kaynağıdır.",
        "Bu üçlü sınıflama finansal yapının ve nakit yaratma biçiminin değerlendirilmesini sağlar.",
        "TMS 7 par. 6 ve 10", "easy",
    ),
    r(
        "İşletme müşterilerden tahsil ettiği ve tedarikçilere ödediği brüt nakit tutarlarını ayrı ayrı göstermiştir. Esas faaliyet nakit akışları hangi yöntemle sunulmuştur?",
        "Doğrudan yöntemin ayırt edici özelliği aşağıdakilerden hangisidir?",
        "Doğrudan yöntem",
        "Başlıca brüt nakit tahsilat ve ödeme sınıflarını açıklaması",
        ["Dolaylı yöntem", "Trend yöntemi", "Dikey yüzde yöntemi", "Tahakkuk düzeltme yöntemi"],
        ["Dönem kârını yalnız amortismanla düzeltip brüt nakit tahsilatlarını hiç göstermemesi", "Bütün nakit akışlarını net tek tutar göstermesi", "Yalnız bilanço kalemlerini yüzdelemesi", "Her dönemi sabit baz yıla oranlaması"],
        "Doğrudan yöntem, müşterilerden tahsilat ve tedarikçilere ödeme gibi brüt nakit sınıflarını sunar.",
        "TMS 7 doğrudan veya dolaylı yönteme izin verir ve doğrudan yöntemin kullanılmasını teşvik eder.",
        "TMS 7 par. 18-19", "easy",
    ),
    r(
        "Esas faaliyet nakit akışı dönem kârından başlanarak amortisman, işletme sermayesi değişimleri ve yatırım/finansman nitelikli sonuç kalemleriyle düzeltilmiştir. Hangi yöntem kullanılmıştır?",
        "Dolaylı yöntemde dönem kârı hangi tür etkiler için düzeltilir?",
        "Dolaylı yöntem",
        "Nakit dışı kalemler, tahakkuklar ve başka faaliyetlere ait sonuçlar",
        ["Doğrudan yöntem", "Fon kaynak-kullanım yöntemi", "Dikey analiz yöntemi", "Sabit baz endeksi yöntemi"],
        ["Yalnız sermaye artırımı, temettü ödemesi ve kredi anaparasının nakit hareketleri", "Sadece maddi duran varlıkların brüt tutarı", "Bütün gelir ve giderlerin toplam varlık payı", "Yalnız gelecek döneme ait bütçe varsayımları"],
        "Dolaylı yöntem, tahakkuk esaslı sonucu nakit esaslı faaliyet sonucuna dönüştüren düzeltmeler yapar.",
        "Amortisman gibi nakit dışı kalemler, işletme sermayesi değişimleri ve başka sınıfa ait sonuçlar düzeltilir.",
        "TMS 7 par. 18 ve 20", "medium",
    ),
    r(
        "İşletme 1.000 bin TL bedelli makineyi tamamı vadeli borçlanmayla, dönem içinde nakit ödemeden edinmiştir. İşlem nakit akış tablosunda gösterilir mi?",
        "Yatırım veya finansman niteliğinde olup nakit ve nakit benzeri kullanımını gerektirmeyen işlemler için doğru sunum nedir?",
        "Hayır; nakit dışı işlem tablodan çıkarılır ve başka yerde açıklanır",
        "Tabloya alınmaz; ilgili finansal tablo veya dipnotta açıklanır",
        ["Evet; yatırım çıkışı ve finansman girişi olarak iki kez gösterilir", "Evet; yalnız esas faaliyet çıkışı sayılır", "Hayır; işlem finansal tablolardan tümüyle silinir", "Evet; makinenin gerçeğe uygun değeri nakit sayılır"],
        ["Nakit girişi ve çıkışı yaratmış gibi esas ile yatırım faaliyetlerinde brüt gösterilir", "Yalnız dönem kârına eklenerek açıklama yapılmaz", "Her durumda nakit benzeri kabul edilir", "Finansman faaliyeti olmaktan çıkarılıp hasılat yazılır"],
        "Nakit kullanılmayan yatırım ve finansman işlemleri nakit akış tablosunun dışında tutulur, fakat kullanıcı için ayrıca açıklanır.",
        "Bu yaklaşım tabloyu gerçek nakit hareketleriyle sınırlar ve önemli nakit dışı işlemleri görünür tutar.",
        "TMS 7 par. 43-44", "medium",
    ),
    r(
        "İşletme olağan müşteri tahsilatlarını ve tedarikçi ödemelerini birbirinden mahsup ederek tek net tutar sunmuştur. TMS 7'nin genel sunum ilkesiyle uyumlu mudur?",
        "Esas, yatırım ve finansman faaliyetlerinden kaynaklanan önemli nakit giriş ve çıkışları kural olarak nasıl raporlanır?",
        "Hayır; net raporlama istisnaları dışında brüt sunum gerekir",
        "Önemli tahsilat ve ödemeler ayrı ve brüt gösterilir",
        ["Evet; bütün nakit hareketleri zorunlu olarak netleştirilir", "Evet; müşteri ve tedarikçi tutarları aynı kalemdir", "Hayır; yalnız tahsilatlar gösterilip ödemeler açıklanmaz", "Evet; netleştirme yalnız kârı artırdığı için uygundur"],
        ["Bütün faaliyetler tek bir net değişim tutarında birleştirilerek tahsilat ve ödeme bilgisi gizlenir", "Yalnız dönem sonunda bakiye kalırsa raporlanır", "Tahsilatlar kâr tablosunda, ödemeler bilançoda gösterilir", "Her nakit akışı baz yıl endeksine çevrilir"],
        "TMS 7 önemli nakit sınıflarının brüt sunumunu esas alır; müşteri adına akışlar ve hızlı devirli kısa vadeli kalemler gibi sınırlı istisnalar vardır.",
        "Brüt sunum nakdin kaynağı ve kullanımının ayrı değerlendirilmesini sağlar.",
        "TMS 7 par. 21-24", "hard",
    ),
    r(
        "Yabancı para tahsilatı, nakit akışının gerçekleştiği tarihteki kur yerine dönem sonu kuruyla çevrilmiştir. Yaklaşım kural olarak doğru mudur?",
        "Yabancı para cinsinden bir nakit akışı işletmenin ağırlıkla kullandığı para birimine hangi kurla çevrilir?",
        "Hayır; işlem tarihindeki kur kullanılmalıdır",
        "Nakit akışının gerçekleştiği tarihteki döviz kuru",
        ["Evet; bütün akışlarda yalnız kapanış kuru kullanılır", "Evet; baz yıl ortalama kuru zorunludur", "Hayır; yabancı para akışları tabloya alınmaz", "Evet; işletme istediği kuru açıklamasız seçebilir"],
        ["Her durumda dönem başı kuru", "Yalnız finansman sözleşmesindeki sabit kur", "Bir önceki raporlama döneminin kapanış kuru", "Nakit olmayan işlemlere uygulanan varsayımsal kur"],
        "Yabancı para nakit akışı işlem tarihindeki kurla çevrilir; uygun ortalama kur, gerçek kura makul yaklaşım sağlıyorsa kullanılabilir.",
        "Kur değişiminin eldeki nakit üzerindeki etkisi üç faaliyet sınıfından ayrı bir mutabakat kalemi olarak sunulur.",
        "TMS 7 par. 25-28", "medium",
    ),
    r(
        "Dönem kârı vergisi ödemesinin belirli bir kısmı doğrudan duran varlık satış kazancıyla ilişkilendirilebilmektedir. Bütün vergi ödemesi esas faaliyetlere yazılmalı mıdır?",
        "Gelir üzerinden alınan vergilere ilişkin nakit akışları hangi sınıfta gösterilir?",
        "Hayır; ilişkilendirilebilen kısım yatırım sınıfına alınabilir",
        "Özel ilişki yoksa esas faaliyetlerde",
        ["Evet; verginin niteliği ve ilişkilendirildiği işlem ne olursa olsun bütün ödeme esas faaliyette kalır", "Hayır; bütün vergi ödemeleri finansman faaliyetidir", "Evet; duran varlık satışında vergi nakit dışıdır", "Hayır; vergi ödemeleri hiçbir nakit tablosunda yer almaz"],
        ["Her durumda yatırım faaliyetlerinde", "Yalnız finansman faaliyetlerinde", "Vergi gideriyle eşit değilse tablo dışında", "Kâr veya zarar tablosunda gösterildiği için nakit sayılmaz"],
        "Vergi nakit akışları genellikle esas faaliyettir; belirli yatırım veya finansman işlemiyle özel olarak ilişkilendirilebilen kısım ilgili sınıfa alınabilir.",
        "TMS 7 sınıflandırmayı vergi giderinin muhasebeleştirilmesine değil, nakit akışının ilişkilendirilebildiği faaliyete bağlar.",
        "TMS 7 par. 35-36", "hard",
    ),
    r(
        "2026 raporunda finansal kuruluş olmayan işletme, ödenen faizi finansman; alınan faizi yatırım faaliyeti olarak sınıflandırmış ve politikayı dönemler boyunca tutarlı uygulamıştır. TMS 7'ye uygun mudur?",
        "2026'da yürürlükteki TMS 7'ye göre finansal kuruluş olmayan işletmelerde faiz ve temettü nakit akışlarının sınıflandırılmasında hangi ilke geçerlidir?",
        "Evet; açıklanan ve tutarlı uygulanan izinli bir seçimdir",
        "İzinli sınıf seçilir, ayrı açıklanır ve tutarlı uygulanır",
        ["Hayır; ödenen faiz yalnız esas faaliyette sınıflandırılabilir ve finansmana alınamaz", "Hayır; alınan faiz yalnız finansman faaliyeti olabilir", "Evet; her dönem açıklamasız farklı sınıf seçilebilir", "Hayır; faiz nakit akış tablosuna alınmaz"],
        ["Bütün faiz ve temettüler zorunlu olarak yatırım faaliyetidir", "Sınıflandırma her raporlama döneminde rastgele değiştirilir", "Nakit akışları yalnız giderin kâr tablosundaki adına göre belirlenir", "Faiz ve temettüler nakit dışı işlem sayılır"],
        "2026 TMS 7'de ödenen faiz esas veya finansman; alınan faiz ve temettüler esas veya yatırım olarak sınıflandırılabilir.",
        "Ödenen temettüler finansman veya esas faaliyet olabilir; her kalem ayrı açıklanır ve seçilen politika tutarlı uygulanır.",
        "TMS 7 par. 31-34; TFRS 18 öncesi 2026 hükümleri", "hard",
    ),
    r(
        "İşletme bir bağlı ortaklığın kontrolünü nakit bedelle edinmiştir. Ödenen nakit, edinilen işletmedeki nakit düşüldükten sonra hangi sınıfta gösterilir?",
        "Bağlı ortaklık veya başka bir işletme biriminin kontrolünün elde edilmesi ya da kaybedilmesine ilişkin toplam nakit akışları nasıl sunulur?",
        "Yatırım faaliyetlerinden nakit çıkışı",
        "Yatırım faaliyetlerinde, edinilen veya elden çıkarılan nakit düşülerek",
        ["Esas faaliyetlerden nakit çıkışı", "Finansman faaliyetlerinden nakit çıkışı", "Nakit dışı işlem", "Özkaynak değişimi olarak tablo dışında"],
        ["Net dönem kârıyla mahsup edilerek esas faaliyetlerde ve edinilen nakit eklenmeden", "Her zaman finansman faaliyetlerinde brüt olarak", "Satış hasılatına eklenerek", "Yalnız bilanço dipnotunda, nakit tablosu dışında"],
        "Kontrol değişikliği yatırımla ilgilidir; sunulan nakit akışı edinilen veya elden çıkarılan işletmenin nakdinden arındırılır.",
        "Bu işlemler ayrı gösterilerek yatırımın büyüklüğü ve nakit etkisi anlaşılır kılınır.",
        "TMS 7 par. 39-42", "hard",
    ),
    r(
        "Maddi duran varlık 900 bin TL nakit bedelle satılmıştır. Bu tahsilat hangi faaliyet sınıfındadır?",
        "Uzun vadeli varlıkların elden çıkarılmasından doğan nakit girişleri kural olarak hangi sınıfta yer alır?",
        "Yatırım faaliyetlerinden nakit girişi",
        "Yatırım faaliyetlerinde",
        ["Esas faaliyetlerden nakit girişi", "Finansman faaliyetlerinden nakit girişi", "Nakit benzerleri arasında aktarım", "Nakit dışı yeniden değerleme"],
        ["Esas faaliyetlerde satış hasılatı olarak", "Finansman faaliyetlerinde borçlanma olarak", "Nakit ve nakit benzerleri dışında bırakılarak", "Özkaynak değişim tablosunda tek başına"],
        "Uzun vadeli varlığın satış bedeli yatırım faaliyeti nakit girişidir; satış kârı ile nakit tahsilatı farklı büyüklüklerdir.",
        "Yatırım sınıfı, gelecekte gelir ve nakit yaratması beklenen kaynakların elden çıkarılmasını yansıtır.",
        "TMS 7 par. 16", "easy",
    ),
    r(
        "Üretimde kullanılacak makine için 1.200 bin TL nakit ödenmiştir. Nakit akış tablosundaki sınıflandırma nedir?",
        "Maddi ve maddi olmayan duran varlık edinimine ilişkin nakit ödemeleri hangi faaliyet kapsamındadır?",
        "Yatırım faaliyetlerinden nakit çıkışı",
        "Yatırım faaliyetleri",
        ["Esas faaliyetlerden nakit çıkışı", "Finansman faaliyetlerinden nakit çıkışı", "Nakit benzeri edinimi", "Nakit dışı işlem"],
        ["Esas faaliyetler", "Finansman faaliyetleri", "Yalnız özkaynak değişimleri", "Her durumda tablo dışı işlemler"],
        "Uzun vadeli üretim kapasitesi sağlayan varlık için yapılan nakit ödeme yatırım faaliyetidir.",
        "Aktifleştirilen geliştirme harcamaları gibi duran varlık oluşturan nakit ödemeleri de yatırım sınıfına girebilir.",
        "TMS 7 par. 16", "easy",
    ),
    r(
        "İşletme bankadan 2.000 bin TL kredi almış ve aynı yıl 500 bin TL anapara geri ödemiştir. Bu iki nakit akışı hangi sınıfta sunulur?",
        "Borçlanmadan sağlanan nakit ile borç anaparasının geri ödenmesi hangi faaliyetin kapsamındadır?",
        "Finansman faaliyetlerinde sırasıyla giriş ve çıkış",
        "Finansman faaliyetleri",
        ["Esas faaliyetlerde sırasıyla giriş ve çıkış", "Yatırım faaliyetlerinde iki ayrı çıkış", "İkisi de nakit dışı işlem", "Yalnız 1.500 bin TL esas faaliyet girişi"],
        ["Esas faaliyetler", "Yatırım faaliyetleri", "Nakit benzerleri arası transfer", "Kâr dağıtım faaliyeti"],
        "Kredi kullanımı ve anapara geri ödemesi işletmenin borç finansmanının büyüklüğünü değiştirir.",
        "Finansman faaliyetleri, işletmenin özkaynak ve borçlanma yapısındaki değişiklikleri doğuran nakit akışlarıdır.",
        "TMS 7 par. 6 ve 17", "easy",
    ),
    r(
        "İşletme yeni pay ihraç ederek 1.500 bin TL nakit sağlamış, ardından 200 bin TL kendi payını geri almıştır. İşlemler nasıl sınıflandırılır?",
        "Pay ihracı ve işletmenin kendi paylarını nakden geri alması hangi faaliyet grubunu etkiler?",
        "Finansman faaliyetlerinde giriş ve çıkış",
        "Finansman faaliyetlerini",
        ["Yatırım faaliyetlerinde giriş ve çıkış", "Esas faaliyetlerde iki ayrı ödeme", "Yalnız net 1.300 bin TL yatırım girişi", "Nakit dışı özkaynak işlemleri"],
        ["Yatırım faaliyetlerini", "Esas faaliyetleri", "Yalnız vergi faaliyetlerini", "Nakit benzerleri arasındaki transferleri"],
        "Pay ihracı özkaynak finansmanı sağlar; pay geri alımı özkaynak finansmanını azaltan nakit çıkışıdır.",
        "Sahiplerden kaynaklanan veya sahiplere dönen nakit, finansman yapısındaki değişimi gösterir.",
        "TMS 7 par. 17", "easy",
    ),
    r(
        "Finansal kuruluş olmayan işletme 2026'da ortaklarına nakit temettü ödemiş ve bunu finansman faaliyeti olarak tutarlı biçimde sınıflandırmıştır. Uygun mudur?",
        "2026'da yürürlükteki TMS 7'ye göre ödenen temettüler hangi sınıflarda sunulabilir?",
        "Evet; finansman faaliyeti izin verilen sınıflandırmadır",
        "Finansman faaliyeti veya tutarlı politika seçimiyle esas faaliyet",
        ["Hayır; yalnız yatırım faaliyeti olabilir", "Hayır; temettü nakit dışı işlemdir", "Evet; fakat yalnız duran varlık satışıyla mahsup edilirse", "Hayır; her durumda kâr tablosunda kalır"],
        ["Yalnız yatırım faaliyetinde ve esas faaliyetlere hiçbir koşulda alınmadan", "Yatırım veya vergi faaliyetinde", "Her durumda nakit benzeri transferi olarak", "Nakit akış tablosu dışında"],
        "Ödenen temettü finansman kaynağının maliyeti olarak finansmanda; dağıtım kapasitesini göstermek amacıyla esas faaliyetlerde sınıflandırılabilir.",
        "Seçim finansal tablo kullanıcılarına açıklanmalı ve dönemler arasında tutarlı uygulanmalıdır.",
        "TMS 7 par. 31 ve 34; 2026 hükümleri", "hard",
    ),
    r(
        "Müşterilerden 5.200 bin TL tahsil edilmiş, mal ve hizmet tedarikçilerine 3.100 bin TL ödenmiştir. Başka esas faaliyet akışı yoksa doğrudan yönteme göre net esas faaliyet nakdi kaçtır?",
        "Net esas faaliyet nakdi 2.100 bin TL ve tedarikçi ödemeleri 3.100 bin TL ise müşterilerden tahsilat kaç bin TL'dir?",
        "2.100 bin TL nakit girişi",
        "5.200 bin TL",
        ["2.100 bin TL nakit çıkışı", "3.100 bin TL nakit girişi", "5.200 bin TL nakit girişi", "8.300 bin TL nakit çıkışı"],
        ["1.000 bin TL", "2.100 bin TL", "3.100 bin TL", "6.200 bin TL"],
        "Net esas faaliyet nakdi 5.200 − 3.100 = 2.100 bin TL giriştir.",
        "Tahsilat, net giriş ile ödeme toplamıdır: 2.100 + 3.100 = 5.200 bin TL.",
        "TMS 7 par. 14 ve 18 - doğrudan yöntem", "easy",
    ),
    r(
        "Müşteri tahsilatları 4.800, tedarikçi ödemeleri 2.600, çalışan ödemeleri 900 ve vergi ödemeleri 300 bin TL'dir. Net esas faaliyet nakdi kaç bin TL'dir?",
        "Net esas faaliyet nakdi 1.000 bin TL; tahsilat 4.800, tedarikçi ve vergi ödemeleri toplamı 2.900 bin TL ise çalışanlara ödenen tutar kaç bin TL'dir?",
        "1.000 bin TL nakit girişi",
        "900 bin TL",
        ["200 bin TL nakit girişi", "1.300 bin TL nakit girişi", "2.000 bin TL nakit çıkışı", "8.600 bin TL nakit girişi"],
        ["300 bin TL", "1.000 bin TL", "1.900 bin TL", "2.900 bin TL"],
        "Net nakit 4.800 − 2.600 − 900 − 300 = 1.000 bin TL giriştir.",
        "Çalışan ödemesi 4.800 − 2.900 − 1.000 = 900 bin TL'dir.",
        "TMS 7 par. 14 ve 18 - esas faaliyet nakitleri", "medium",
    ),
    r(
        "Dolaylı yöntemde vergi sonrası kâr 1.200 bin TL'dir. Ticari alacaklar 250 bin TL artmış, diğer kalemler değişmemiştir. Alacak artışının esas faaliyet nakdine etkisi nedir?",
        "Yalnız ticari alacak artışı düzeltmesi dikkate alındığında 1.200 bin TL kârdan net esas faaliyet nakdi kaç bin TL olur?",
        "250 bin TL azaltıcı etki",
        "950 bin TL",
        ["250 bin TL artırıcı etki", "1.200 bin TL artırıcı etki", "1.450 bin TL azaltıcı etki", "Nakit üzerinde hiçbir etki yoktur"],
        ["250 bin TL", "1.200 bin TL", "1.450 bin TL", "2.650 bin TL"],
        "Alacak artışı, hasılatın henüz tahsil edilmemiş kısmını gösterdiğinden kârdan düşülür.",
        "Net faaliyet nakdi 1.200 − 250 = 950 bin TL'dir.",
        "TMS 7 par. 20 - işletme sermayesi düzeltmeleri", "medium",
    ),
    r(
        "Dolaylı yöntemde stoklar 180 bin TL artmış, ticari borçlar 120 bin TL artmıştır. İki değişimin net esas faaliyet nakdi etkisi nedir?",
        "Stok artışı 180 bin TL iken işletme sermayesi değişimlerinin toplam etkisi 60 bin TL nakit azalışıysa ticari borç artışı kaç bin TL'dir?",
        "60 bin TL azaltıcı etki",
        "120 bin TL",
        ["60 bin TL artırıcı etki", "120 bin TL azaltıcı etki", "180 bin TL artırıcı etki", "300 bin TL azaltıcı etki"],
        ["60 bin TL", "180 bin TL", "240 bin TL", "300 bin TL"],
        "Stok artışı 180 bin TL nakit kullanır, borç artışı 120 bin TL nakit korur; net etki −60 bin TL'dir.",
        "Borç artışı, 180 bin TL stok kullanımının 60 bin TL net azalışa inmesini sağlayan 120 bin TL'dir.",
        "TMS 7 par. 20 - işletme sermayesi", "medium",
    ),
    r(
        "Dolaylı yöntemde dönem kârı 900, amortisman gideri 160 bin TL'dir; başka düzeltme yoktur. Net esas faaliyet nakdi kaç bin TL'dir?",
        "Net esas faaliyet nakdi 1.060 ve dönem kârı 900 bin TL ise tek düzeltme olan amortisman gideri kaç bin TL'dir?",
        "1.060 bin TL",
        "160 bin TL",
        ["740 bin TL", "900 bin TL", "1.160 bin TL", "1.960 bin TL"],
        ["60 bin TL", "900 bin TL", "1.060 bin TL", "1.960 bin TL"],
        "Amortisman nakit çıkışı yaratmayan gider olduğundan kâra 160 bin TL eklenir: 1.060 bin TL.",
        "Nakit ile kâr arasındaki 160 bin TL fark, nakit dışı amortisman düzeltmesidir.",
        "TMS 7 par. 20 - nakit dışı kalemler", "easy",
    ),
    r(
        "Dolaylı yöntemde dönem kârına dahil 140 bin TL duran varlık satış kârı vardır. Satış tahsilatı yatırım faaliyetinde ayrıca gösterilmiştir. Satış kârı esas faaliyet hesabında ne yapılır?",
        "Dönem kârı 1.000 bin TL ve tek düzeltme 140 bin TL duran varlık satış kârıysa net esas faaliyet nakdi kaç bin TL'dir?",
        "Kârdan 140 bin TL düşülür",
        "860 bin TL",
        ["Kâra 140 bin TL eklenir", "Kârdan satış bedelinin tamamı iki kez düşülür", "Esas faaliyetlerde hiçbir düzeltme yapılmaz", "Satış kârı nakit benzeri sayılır"],
        ["140 bin TL", "1.000 bin TL", "1.140 bin TL", "1.860 bin TL"],
        "Satış kârı tahakkuk esaslı kârın içinde, tahsilat ise yatırım nakit akışındadır; mükerrerliği önlemek için kârdan çıkarılır.",
        "Net esas faaliyet nakdi 1.000 − 140 = 860 bin TL'dir.",
        "TMS 7 par. 20 - yatırım nitelikli sonuç düzeltmesi", "medium",
    ),
    r(
        "Dönem başı nakit 500, esas faaliyet girişi 900, yatırım çıkışı 700, finansman girişi 100 ve kur farkı etkisi 20 bin TL'dir. Dönem sonu nakit kaç bin TL'dir?",
        "Dönem sonu nakit 820, dönem başı 500; esas faaliyet girişi 900, yatırım çıkışı 700 bin TL ise finansman akışı ile kur etkisinin toplamı kaç bin TL'dir?",
        "820 bin TL",
        "120 bin TL net giriş",
        ["300 bin TL", "700 bin TL", "800 bin TL", "1.720 bin TL"],
        ["120 bin TL net çıkış", "200 bin TL net giriş", "320 bin TL net giriş", "1.020 bin TL net çıkış"],
        "Son bakiye 500 + 900 − 700 + 100 + 20 = 820 bin TL'dir.",
        "Toplam değişim 320 bin TL'dir; esas ve yatırımın neti 200 bin TL olduğundan kalan 120 bin TL giriş finansman ve kur etkisidir.",
        "TMS 7 par. 28 ve 45 - nakit mutabakatı", "medium",
    ),
    r(
        "İşletme üç dönem üst üste kâr açıklamasına rağmen esas faaliyetlerden sürekli nakit çıkışı raporlamıştır. Analizde hangi risk öne çıkar?",
        "Kâr ile esas faaliyet nakit akışının uzun süre ters yönde seyretmesi neden incelenmelidir?",
        "Kârın nakde dönüşümünde tahsilat veya işletme sermayesi sorunu olabilir",
        "Tahakkuk kalitesi ve sürdürülebilir nakit yaratma gücü hakkında uyarı verebilir",
        ["Kâr bulunduğu için tahsilat ve işletme sermayesi koşullarından bağımsız olarak nakit sorunu mümkün değildir", "Esas faaliyet nakdi yalnız yatırım başarısını ölçer", "Negatif nakit her durumda hızlı büyüme kanıtıdır", "Nakit akış tablosu kârla hiçbir ilişki taşımaz"],
        ["İki tutarın her dönemde eşit olması zorunlu olduğu ve bütün tahakkuklar nakit yarattığı için", "Yalnız vergi oranının değiştiğini kanıtladığı için", "Bütün alacakların tahsil edildiğini gösterdiği için", "Finansman nakdini kesin olarak sıfırladığı için"],
        "Sürekli kâr-nakit ayrışması alacak birikimi, stok artışı veya kârın tahakkuk niteliği gibi nedenler taşıyabilir.",
        "Nakit akış analizi kârlılığın nakit üretimine dönüşüp dönüşmediğini ve sürdürülebilirliğini sınar.",
        "TMS 7 par. 4-5; finansal tablo analizi", "hard",
    ),
    r(
        "Esas faaliyetlerden net nakit 1.500, maddi ve maddi olmayan duran varlık alımları 600 bin TL'dir. Basit serbest nakit akışı göstergesi kaç bin TL'dir?",
        "Basit serbest nakit akışı 900 bin TL ve duran varlık yatırımı 600 bin TL ise esas faaliyetlerden net nakit kaç bin TL'dir?",
        "900 bin TL",
        "1.500 bin TL",
        ["600 bin TL", "1.500 bin TL", "2.100 bin TL", "2.700 bin TL"],
        ["300 bin TL", "600 bin TL", "900 bin TL", "2.100 bin TL"],
        "Basit gösterge esas faaliyet nakdi eksi sermaye harcamasıdır: 1.500 − 600 = 900 bin TL.",
        "Esas faaliyet nakdi, serbest nakit ile yatırım harcamasının toplamıdır: 900 + 600 = 1.500 bin TL.",
        "Finansal tablo analizi - serbest nakit akışı göstergesi", "medium",
    ),
]


PREMISES = [
    {"stem":"Nakit akış tablosunun kapsamı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Nakit ve nakit benzerlerindeki değişimi açıklar\n\nII. Esas, yatırım ve finansman sınıflarını kullanır\n\nIII. Her raporlama döneminde finansal tabloların ayrılmaz parçasıdır","correct":"I, II ve III","why":"TMS 7, nakit değişimini üç faaliyet sınıfında ve her raporlama dönemi için sunmayı gerektirir.","ref":"TMS 7 par. 1, 6 ve 10","difficulty":"easy"},
    {"stem":"Nakit benzerleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yüksek likidite aranır\n\nII. Belirli tutarda nakde kolay dönüşebilmelidir\n\nIII. Değer değişim riski önemsiz olmalıdır","correct":"I, II ve III","why":"Üç ifade de TMS 7'nin nakit benzeri tanımının bileşenidir.","ref":"TMS 7 par. 6-7","difficulty":"easy"},
    {"stem":"Esas faaliyet nakit akışlarının sunumu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Doğrudan yöntem brüt tahsilat ve ödeme sınıflarını gösterir\n\nII. Dolaylı yöntem kârı nakit dışı ve tahakkuk kalemleriyle düzeltir\n\nIII. TMS 7 yalnız dolaylı yönteme izin verir","correct":"I ve II","why":"Her iki yönteme izin verilir; doğrudan yöntemin kullanımı teşvik edilir. III yanlıştır.","ref":"TMS 7 par. 18-20","difficulty":"medium"},
    {"stem":"Faaliyet sınıfları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Makine alımı esas faaliyettir\n\nII. Kredi anaparası alınması finansman girişidir\n\nIII. Maddi duran varlık satışı yatırım girişidir","correct":"II ve III","why":"Makine alımı yatırım çıkışıdır; kredi ve duran varlık satışı için II ve III doğrudur.","ref":"TMS 7 par. 16-17","difficulty":"medium"},
    {"stem":"Nakit dışı işlemler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Nakit kullanılmayan yatırım işlemi nakit akış tablosuna alınmaz\n\nII. Önemli nakit dışı işlem ayrıca açıklanır\n\nIII. Vadeli makine alımı nakit çıkışı yaratmış gibi gösterilir","correct":"I ve II","why":"Nakit dışı yatırım ve finansman işlemleri tablodan çıkarılır, ancak ilgili yerde açıklanır; III yanlıştır.","ref":"TMS 7 par. 43-44","difficulty":"medium"},
    {"stem":"2026 TMS 7 faiz ve temettü hükümleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Sınıflandırma her dönem açıklamasız değiştirilebilir\n\nII. Her faiz ve temettü nakit akışı ayrı açıklanır\n\nIII. Seçilen izinli sınıflandırma dönemler boyunca tutarlı uygulanır","correct":"II ve III","why":"TMS 7 ayrı açıklama ve tutarlılık ister; rastgele dönemsel değişime izin vermez.","ref":"TMS 7 par. 31-34; 2026 hükümleri","difficulty":"hard"},
    {"stem":"Dolaylı yöntem düzeltmeleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Amortisman gideri kâra geri eklenir\n\nII. Ticari alacak artışı esas faaliyet nakdini azaltır\n\nIII. Duran varlık satış kârı esas faaliyet hesabında aynen bırakılır","correct":"I ve II","why":"Amortisman nakit dışıdır, alacak artışı nakit kullanır; yatırım nitelikli satış kârı kârdan çıkarılır.","ref":"TMS 7 par. 20","difficulty":"medium"},
    {"stem":"Nakit akış analizinin yorumu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kâr ile faaliyet nakdi arasındaki sürekli ayrışma incelenir\n\nII. Pozitif kâr her durumda güçlü nakit üretimini kanıtlar\n\nIII. Faaliyet nakdi işletmenin kendi faaliyetleriyle nakit yaratma gücünü gösterir","correct":"I ve III","why":"Tahakkuk esaslı kâr nakit üretimine eşit değildir; süreklilik gösteren ayrışma ve faaliyet nakdinin niteliği incelenir.","ref":"TMS 7 par. 4-5; finansal tablo analizi","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="mali_tablolar_analizi", topic_id="nakit_akim_analizi",
        label="Nakit Akış Analizi", slug="nakit_akim_analizi", prefix="topic-naa",
        seed=2026071746,
        legislation_version="TMS 7 Nakit Akış Tablosu (2026 KGK seti); TFRS 18 01.01.2027 öncesi hükümler (17.07.2026 kontrolü)",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
