#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Vergilendirme Süreci, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Vergi kanunu, mal tesliminin gerçekleşmesini vergiye bağlamıştır. Vergi alacağı hangi anda doğar?",
        "Vergi alacağının doğumu bakımından VUK'un esas aldığı an hangisidir?",
        "Vergiyi doğuran olayın gerçekleştiği anda",
        "Vergiyi doğuran olay veya tamamlanan hukuki hâl",
        ["Verginin mükellefçe fiilen ödendiği anda", "Vergi inceleme raporunun yazıldığı anda", "Tahakkuk fişinin mükellefçe alındığı anda", "Vergi mahkemesi kararının kesinleştiği anda"],
        ["Vergi dairesinin tahsilat makbuzu düzenlediği an", "Mükellefin ödeme emrine karşı dava açtığı an", "İnceleme elemanının işe başladığı ilk gün", "Vergi cezasına ilişkin uzlaşmanın sağlandığı an"],
        "Vergi alacağı, kanunun vergiye bağladığı olayın gerçekleşmesiyle doğar; ödeme veya tarh daha sonraki aşamalardır.",
        "Hukuki durumun tamamlanması da vergiyi doğuran olay gibi vergi alacağının doğum anını belirleyebilir.",
        "213 sayılı VUK m. 19", "easy",
    ),
    r(
        "Vergiyi doğuran olay gerçekleşmiş ve Devlet yönünden vergi alacağı doğmuştur. Aynı ilişki mükellef yönünden neyi oluşturur?",
        "Vergi alacağının mükellef bakımından karşılığı hangisidir?",
        "Mükellef yönünden vergi borcunu oluşturur",
        "Vergi borcu",
        ["Yalnız muhasebe tahminini oluşturur", "Kendiliğinden vergi cezasını oluşturur", "Vergi incelemesini sona erdirir", "Dava açma hakkını ortadan kaldırır"],
        ["Vergi cezası", "Gecikme faizi", "Ödeme emri", "Yoklama fişi"],
        "Vergi alacağı kamu idaresi yönünden alacak, mükellef yönünden aynı tutarda vergi borcudur.",
        "VUK, vergi alacağının mükellef bakımından vergi borcunu teşkil ettiğini açıkça düzenler.",
        "213 sayılı VUK m. 19", "easy",
    ),
    r(
        "Vergi dairesi kanundaki matrah ve oranı kullanarak vergi alacağını miktar itibarıyla belirlemiştir. Hangi işlem yapılmıştır?",
        "Tarh işleminin ayırt edici unsuru hangisidir?",
        "Verginin tarh işlemi",
        "Vergi dairesince hesaplanıp miktar belirleme",
        ["Verginin tahakkuku", "Verginin tahsili", "Verginin tebliği", "Verginin terkini"],
        ["Vergi borcunun kanuna uygun biçimde ödenmesi", "Hüküm ifade eden yazının mükellefe bildirilmesi", "Verginin ödenmesi gereken aşamaya gelmesi", "Vergi borcunun süre sonunda zamanaşımına uğraması"],
        "Matrah ve oran üzerinden verginin hesaplanıp miktar itibarıyla belirlenmesi tarhtır.",
        "Tarh, vergi dairesinin vergi alacağını miktar olarak belirlediği idari işlemdir.",
        "213 sayılı VUK m. 20", "easy",
    ),
    r(
        "Vergilendirmeyi ilgilendiren ve hüküm ifade eden ihbarname yetkili makamca mükellefe yazıyla bildirilmiştir. Bu aşama hangisidir?",
        "VUK'a göre tebliğ kavramını doğru açıklayan seçenek hangisidir?",
        "Verginin tebliği",
        "Yetkili makamın yazılı vergilendirme bildirimi",
        ["Verginin tarhı", "Verginin tahsili", "Verginin tahakkuku", "Verginin hesaplanması"],
        ["Vergi borcunun banka hesabından ödenmesi", "Vergi matrahının mükellefçe hesaplanması", "Vergi alacağının oran üzerinden belirlenmesi", "Vergi borcunun kendiliğinden sona ermesi"],
        "Yetkili makamın hüküm ifade eden vergilendirme belgesini yazılı bildirmesi tebliğdir.",
        "Tebliğin konusu vergilendirmeyi ilgilendiren ve hüküm ifade eden hususlardır; muhatap mükellef veya ceza sorumlusu olabilir.",
        "213 sayılı VUK m. 21", "easy",
    ),
    r(
        "Tarh ve tebliğ edilen vergi artık ödenmesi gereken aşamaya gelmiştir. Bu durum hangi kavramla ifade edilir?",
        "Verginin tahakkuku hangi aşamayı anlatır?",
        "Verginin tahakkuku",
        "Tarh ve tebliğ sonrası verginin ödenebilir aşaması",
        ["Verginin tarhı", "Verginin tebliği", "Verginin tahsili", "Verginin terkini"],
        ["Vergi alacağının miktar olarak ilk kez hesaplanması", "Vergi borcunun kanuna uygun biçimde ödenmesi", "İhbarnamenin yetkili makamca yazıyla bildirilmesi", "Vergi borcunun düzeltme yoluyla tamamen kaldırılması"],
        "Ödeme henüz yapılmamış olsa da verginin ödenebilir aşamaya ulaşması tahakkuktur.",
        "Tahakkuk, tarh ve tebliğden sonra verginin ödenmesi gereken safhaya gelmesini ifade eder.",
        "213 sayılı VUK m. 22", "easy",
    ),
    r(
        "Mükellef tahakkuk eden vergi borcunu kanuna uygun biçimde vergi dairesine ödemiştir. Hangi aşama tamamlanmıştır?",
        "Verginin tahsili neyi ifade eder?",
        "Verginin tahsili",
        "Vergi borcunun kanuna uygun biçimde ödenmesi",
        ["Verginin tarhı", "Verginin tebliği", "Verginin tahakkuku", "Verginin doğumu"],
        ["Vergi alacağının matrah üzerinden hesaplanması", "İhbarnamenin yazıyla mükellefe bildirilmesi", "Verginin ödenmesi gereken aşamaya ulaşması", "Vergiyi doğuran olayın hukuken gerçekleşmesi"],
        "Kanuna uygun ödeme tahsildir; tarh ve tahakkuk ödeme öncesindeki idari aşamalardır.",
        "VUK tahsili, verginin kanuna uygun surette ödenmesi olarak tanımlar.",
        "213 sayılı VUK m. 23", "easy",
    ),
    r(
        "Mahiyeti gereği tahakkuku tahsile bağlı bir vergi fiilen tahsil edilmiştir. Tahakkuk ayrıca daha sonra mı gerçekleşir?",
        "Tahakkuku tahsile bağlı vergilerde tahsilin hukuki sonucu hangisidir?",
        "Hayır; bu vergilerde tahsil tahakkuku da içerir",
        "Bu vergilerde tahsil, tahakkuku da içine alır",
        ["Evet; tahakkuk yalnız dava süresi bitince gerçekleşir", "Evet; önce ayrı bir ikmal tarhiyatı yapılmalıdır", "Hayır; tahsil tahakkuku hiçbir biçimde etkilemez", "Evet; tahakkuk için takdir komisyonu kararı gerekir"],
        ["Tahsil tahakkuku ortadan kaldırır", "Tahakkuk tahsilden tamamen bağımsız kalır", "Tahsil yalnız tebliğ işleminin yerine geçer", "Tahsil yeni bir tarh işlemini zorunlu kılar"],
        "Bu vergi türlerinde ödeme, ayrıca beklenen bir tahakkuk aşaması olmaksızın tahakkuku da gerçekleştirir.",
        "VUK, mahiyeti gereği tahakkuku tahsile bağlı vergilerde tahsilin tahakkuku da kapsadığını belirtir.",
        "213 sayılı VUK m. 24", "medium",
    ),
    r(
        "Vergiyi doğuran olaydan sonra vergi dairesi tutarı belirlemiş, ihbarnameyi bildirmiş, vergi ödenebilir hâle gelmiş ve mükellef ödeme yapmıştır. Doğru sıra hangisidir?",
        "Vergilendirme sürecindeki dört temel idari aşamanın genel sırası hangisidir?",
        "Tarh, tebliğ, tahakkuk ve tahsil",
        "Tarh, tebliğ, tahakkuk ve tahsil",
        ["Tebliğ, tahsil, tarh ve tahakkuk", "Tahsil, tarh, tahakkuk ve tebliğ", "Tahakkuk, tarh, tahsil ve tebliğ", "Tarh, tahsil, tebliğ ve tahakkuk"],
        ["Tahakkuk, tebliğ, tarh ve tahsil", "Tebliğ, tarh, tahsil ve tahakkuk", "Tahsil, tahakkuk, tebliğ ve tarh", "Tarh, tahakkuk, tahsil ve tebliğ"],
        "Genel süreçte vergi önce tarh edilir, sonra tebliğle bildirilir, tahakkuk ederek ödenebilir hâle gelir ve tahsil edilir.",
        "Bu sıralama genel kuraldır; tahakkuku tahsile bağlı vergiler ve beyana dayalı tarh gibi özel usuller ayrıca düzenlenmiştir.",
        "213 sayılı VUK m. 20-24", "easy",
    ),
    r(
        "Mükellef beyan üzerinden alınan vergiye ilişkin beyannamesini vermiştir. Vergi hangi belgeyle tarh ve tahakkuk ettirilir?",
        "Beyan üzerinden alınan vergilerde temel tarh ve tahakkuk belgesi hangisidir?",
        "Tahakkuk fişi",
        "Tahakkuk fişi",
        ["Yoklama fişi", "Ödeme emri", "Uzlaşma tutanağı", "Takdir komisyonu kararı"],
        ["Vergi inceleme raporu", "İhtiyati haciz kararı", "Düzeltme fişi", "Teminat isteme yazısı"],
        "Beyana dayanan vergiler, beyannamenin alınması üzerine düzenlenen tahakkuk fişiyle tarh ve tahakkuk ettirilir.",
        "Vergi dairesi beyannameyi alınca tahakkuk fişi düzenler ve bu yolla vergi tahakkuk eder.",
        "213 sayılı VUK m. 25", "easy",
    ),
    r(
        "Vergi dairesi tahakkuk fişinin bir nüshasını beyannameyi mükellef adına teslim eden kişiye vermiştir. Bu nüsha başka hangi işlevi görür?",
        "Mükellefe verilen tahakkuk fişi nüshasının ek işlevi hangisidir?",
        "Beyannamenin makbuzu yerine geçer",
        "Beyanname makbuzu işlevi görür",
        ["Vergi inceleme raporunun yerini alır", "Dava dilekçesi olarak kabul edilir", "Ödeme emri hükmünde kullanılır", "Takdir komisyonu kararını oluşturur"],
        ["Vergi mahkemesi kararı sayılır", "Vergi borcunu kendiliğinden siler", "Yoklama fişi yerine düzenlenir", "Uzlaşma talebini başlatır"],
        "Tahakkuk fişinin mükellefe verilen nüshası aynı zamanda beyannamenin alındığını gösteren makbuzdur.",
        "Belge tahakkuku gösterirken aynı zamanda beyanname tesliminin makbuzu işlevini üstlenir.",
        "213 sayılı VUK m. 25", "easy",
    ),
    r(
        "Beyannameyi vergi dairesine teslim eden kişi düzenlenen tahakkuk fişini almadan ayrılmıştır. Verginin tahakkuku engellenir mi?",
        "Tahakkuk fişi nüshasının mükellefçe alınmamasının sonucu hangisidir?",
        "Hayır; fişin alınmaması tahakkuka engel olmaz",
        "Tahakkuku engellemez; nüsha mükellefe gönderilir",
        ["Evet; fiş alınmadan tahakkuk hiçbir zaman oluşmaz", "Evet; beyanname verilmemiş kabul edilir", "Hayır; vergi doğrudan terkin edilmiş sayılır", "Evet; yeni bir takdir komisyonu kararı gerekir"],
        ["Beyanname kendiliğinden hükümsüz olur", "Vergi borcu cezasız biçimde tamamen silinir", "Vergi yalnız ödeme emriyle yeniden tarh edilir", "Mükellef otomatik olarak uzlaşmış kabul edilir"],
        "Tahakkuk fişini fiziksel olarak almamak, beyan edilen matrah üzerinden tahakkuku ortadan kaldırmaz.",
        "Alınmayan nüsha kanundaki usule göre mükellefe gönderilir; tahakkuk geçerliliğini korur.",
        "213 sayılı VUK m. 27", "medium",
    ),
    r(
        "Beyanname elektronik ortamda gönderilmiş, tahakkuk fişi de elektronik düzenlenip yetkili kişiye iletilmiştir. Bu ileti neyin yerine geçer?",
        "Elektronik tahakkuk fişinin yetkili kişiye elektronik iletimi hangi sonucu doğurur?",
        "Tahakkuk fişinin elektronik tebliği sayılır",
        "Elektronik ileti tahakkuk fişinin tebliği sayılır",
        ["Yalnız beyannamenin taslak kaydı sayılır", "Vergi inceleme raporu yerine geçer", "Ödeme yapıldığına ilişkin makbuz sayılır", "Vergi mahkemesi kararı hükmünü doğurur"],
        ["Verginin tahsil edildiğini kesinleştirir", "Beyannameyi hiç verilmemiş hâle getirir", "Takdir komisyonu kararını oluşturur", "Vergi borcunu kendiliğinden terkin eder"],
        "Elektronik iletim, kâğıt nüshanın ayrıca tebliğine gerek bırakmadan tahakkuk fişinin tebliği sonucunu doğurur.",
        "VUK elektronik beyanda fişin elektronik düzenlenmesini ve yetkili kişiye iletimin tebliğ yerine geçmesini kabul eder.",
        "213 sayılı VUK m. 28", "medium",
    ),
    r(
        "Gelir İdaresi Başkanlığı, beyanname verme ve ödeme süresinin son gününü kanuni süreden itibaren kırk beş gün uzatmıştır. Yetki sınırına uygun mudur?",
        "Gelir İdaresi Başkanlığının beyan ve ödeme sürelerinin son gününü yeniden belirleme yetkisinin azami sınırı nedir?",
        "Hayır; uzatma kanuni süreden itibaren bir ayı geçemez",
        "Bir ay",
        ["Evet; Başkanlık süreyi sınırsız olarak uzatabilir", "Evet; azami sınır iki takvim ayıdır", "Hayır; Başkanlığın hiçbir süre belirleme yetkisi yoktur", "Evet; sınır yalnız beyan için üç aydır"],
        ["On beş gün", "İki ay", "Altı ay", "Bir takvim yılı"],
        "VUK'taki yetki bir aylık azami süreyle sınırlıdır; kırk beş günlük uzatma bu sınırı aşar.",
        "Başkanlık beyanname verme ve ödeme sürelerinin son gününü kanuni süreden itibaren en çok bir ay yeniden belirleyebilir.",
        "213 sayılı VUK mükerrer m. 28", "hard",
    ),
    r(
        "Daha önce tarh edilmiş vergiye ilişkin defter ve belgelerden tespit edilen ek matrah farkı üzerinden ilave vergi hesaplanmıştır. Tarh türü hangisidir?",
        "İkmalen vergi tarhının temel koşulu hangisidir?",
        "İkmalen vergi tarhı",
        "Önceki tarhtan sonra belgeyle belirlenen matrah farkı",
        ["Re'sen vergi tarhı", "İdarece vergi tarhı", "Beyana dayalı tarh", "Tahakkuku tahsile bağlı tarh"],
        ["Matrahın hiçbir kayıt veya ölçüyle belirlenememesi", "Mükellefin ilk kez süresinde beyanname vermesi", "Verginin kanuna uygun biçimde tahsil edilmesi", "Yalnız tebliğ evrakının muhataba ulaşmaması"],
        "Önceden bir tarh vardır ve sonradan belge ya da kanuni ölçülerle belirlenen fark bulunmuştur; bu ikmalen tarhtır.",
        "İkmalen tarh, daha önce tarh edilmiş vergiyle ilgili sonradan belirlenen matrah veya matrah farkına dayanır.",
        "213 sayılı VUK m. 29", "medium",
    ),
    r(
        "İlk tarhtan sonra ortaya çıkan fark yalnız soyut tahmine dayanmakta, defter, belge veya kanuni ölçüyle miktarı belirlenememektedir. İkmalen tarh yapılabilir mi?",
        "İkmalen tarh edilecek matrah farkının belirlenme dayanağı hangisidir?",
        "Hayır; fark kayıt veya kanuni ölçüyle belirlenir",
        "Defter, kayıt, belge veya kanuni ölçüler",
        ["Evet; hiçbir dayanak olmadan tahmin yeterlidir", "Evet; yalnız mükellefin sözlü kabulü zorunludur", "Hayır; ikmalen tarh yalnız ilk beyan sırasında yapılır", "Evet; sadece ödeme emrindeki tutar farkı yeterlidir"],
        ["Yalnız denetçinin kişisel kanaati", "Sadece mükellefin sektördeki itibarı", "Vergi dairesinin bütçe ihtiyacı", "Rastgele seçilmiş emsal işletme"],
        "İkmalen tarh için farkın nesnel defter, kayıt, belge veya kanuni ölçüye göre miktar olarak tespit edilebilmesi gerekir.",
        "Dayanaksız tahmin ikmalen tarhın yapısına uymaz; kanun belirlenebilir bir matrah farkı arar.",
        "213 sayılı VUK m. 29", "hard",
    ),
    r(
        "Mükellefin kayıtları vergi matrahını doğru ve kesin biçimde belirlemeye elverişli değildir. Takdir komisyonunca belirlenen matrah üzerinden hangi tarh yapılır?",
        "Re'sen vergi tarhının ayırt edici koşulu hangisidir?",
        "Re'sen vergi tarhı",
        "Matrahın kayıt veya ölçülerle belirlenememesi",
        ["İkmalen vergi tarhı", "İdarece vergi tarhı", "Beyana dayalı tarh", "Tahakkuku tahsile bağlı tarh"],
        ["Daha önceki tarhtan sonra belgeli bir matrah farkı bulunması", "Mükellefin kanuni süresinde eksiksiz beyanname vermesi", "Verginin ödenmesi gereken aşamaya gelmesi", "Vergi borcunun kanuna uygun biçimde ödenmesi"],
        "Matrahın kayıt ve ölçülerle belirlenememesi re'sen tarh sebebidir; matrah takdir veya inceleme raporuyla belirlenir.",
        "Re'sen tarh, matrahın tamamen veya kısmen olağan kanuni dayanaklarla tespit edilemediği hâllere yöneliktir.",
        "213 sayılı VUK m. 30", "medium",
    ),
    r(
        "Mükellef kanuni süre geçtiği hâlde vergi beyannamesini vermemiştir. VUK bakımından hangi tarh sebebi doğar?",
        "Kanuni süresinde beyanname verilmemesi hangi tarh usulüne neden olabilir?",
        "Süresinde beyan yoksa re'sen tarh sebebi doğar",
        "Re'sen vergi tarhı",
        ["Yalnız ikmalen tarh sebebi doğar", "Her durumda beyana dayalı tarh yapılır", "Vergi borcu kendiliğinden terkin edilir", "Sadece tahsil aşaması tamamlanmış sayılır"],
        ["İkmalen vergi tarhı", "Beyana dayalı olağan tarh", "Tahakkuku tahsile bağlı tarh", "Verginin kendiliğinden terkini"],
        "Kanuni sürenin geçmesine rağmen beyannamenin verilmemesi matrahın olağan yolla belirlenemediği kabul edilen re'sen tarh sebeplerindendir.",
        "VUK, süresinde beyanname verilmemesini re'sen tarh sebebi sayar.",
        "213 sayılı VUK m. 30/2-1", "easy",
    ),
    r(
        "Tutulması zorunlu defterler tasdik ettirilmemiş ve incelemeye ibraz edilmemiştir. Bu durum hangi sonuca yol açabilir?",
        "Zorunlu defterlerin tutulmaması, tasdik ettirilmemesi veya ibraz edilmemesi hangi kapsamda değerlendirilir?",
        "Re'sen tarh nedeni olabilir",
        "Matrah belirlenemediği için re'sen tarh hâli",
        ["Yalnız tahsil işlemini tamamlar", "Vergiyi kendiliğinden terkin eder", "Her durumda ikmalen tarhı zorunlu kılar", "Tebliğ işlemini hükümsüz bırakır"],
        ["Beyana dayalı tarhın eksiksiz tamamlanması", "Tahakkuk fişinin makbuz sayılması", "Verginin tahsil edilerek sona ermesi", "Dava süresinin hiç başlamaması"],
        "Zorunlu defterlerin bulunmaması veya incelemeye sunulmaması matrahın güvenilir biçimde belirlenmesini engelleyebilir.",
        "VUK bu defter eksikliklerini, matrahın olağan dayanaklarla belirlenemediği kabul edilen re'sen tarh hâlleri arasında sayar.",
        "213 sayılı VUK m. 30/2-3", "medium",
    ),
    r(
        "Defter ve belgeler şeklen mevcut olsa da gerçek durumu yansıtmadığına dair somut delil bulunmuştur. Re'sen tarh yönünden etkisi nedir?",
        "Defter veya beyannamenin gerçek durumu yansıtmadığına dair delil bulunması hangi sonucu doğurabilir?",
        "Re'sen tarh nedeni oluşturabilir",
        "Gerçeği yansıtmama delili re'sen tarha yol açabilir",
        ["Kayıtlar otomatik olarak eksiksiz kabul edilir", "Yalnız tahakkuk fişinin iptalini gerektirir", "Verginin tahsil edilmiş sayılmasını sağlar", "Sadece idarece tarh usulünü zorunlu kılar"],
        ["Her durumda olumlu vergi inceleme sonucu doğurur", "Vergi borcunun dava açılmadan silinmesini sağlar", "Yalnız tahsilat makbuzunun yeniden düzenlenmesini gerektirir", "Matrahın beyan edildiği şekliyle kesinleşmesini sağlar"],
        "Şekli varlık yeterli değildir; gerçek durumu yansıtmama delili, matrahın güvenilir belirlenemediğini gösterir.",
        "VUK zorunlu defterlerin veya beyannamelerin gerçeği yansıtmadığına ilişkin delili re'sen tarh sebepleri arasında düzenler.",
        "213 sayılı VUK m. 30/2-6", "hard",
    ),
    r(
        "Mükellef beyannamesini süresinden sonra, vergi incelemesine başlanmadan ve takdir komisyonuna sevk edilmeden kendiliğinden vermiştir. Tarh nasıl yapılır?",
        "İnceleme veya takdire sevkten önce kendiliğinden verilen geç beyanname için doğru işlem hangisidir?",
        "Beyan edilen matrah üzerinden re'sen tarh yapılır",
        "Geç beyan matrahından re'sen tarh; takdire sevk yok",
        ["Beyanname hiç verilmemiş sayılarak doğrudan terkin yapılır", "Her durumda takdir komisyonuna sevk edilir", "Yalnız ikmalen tarh yapılır ve ceza kesilmez", "Vergi tahsil edilmiş kabul edilerek dosya kapanır"],
        ["Beyannameyi yok sayıp vergiyi tahsil edilmiş kabul etmek", "Matrah farkı aramadan yalnız ikmalen tarh yapmak", "Mutlaka takdir komisyonunun yeni matrah belirlemesini beklemek", "Vergiyi kendiliğinden terkin ederek beyanı iade etmek"],
        "İnceleme başlamadan veya takdire sevkten önce verilen geç beyandaki matrah re'sen tarha esas olur; ayrıca takdire sevk edilmez.",
        "Kanun bu kolaylığı, inceleme başladıktan veya takdire sevkten sonra kendiliğinden verilen beyannamelere uygulamaz.",
        "213 sayılı VUK m. 30", "hard",
    ),
    r(
        "Aynı olayda hem re'sen tarh sebebi hem de belgelerle belirlenmiş ikmalen tarh farkı bulunmaktadır. İkmal tarhı re'sen takdir bitene kadar bekler mi?",
        "Re'sen ve ikmalen tarh sebepleri birlikteyse ikmal tarhiyatının zamanı nasıl belirlenir?",
        "Hayır; ikmal tarhı re'sen takdiri beklemez",
        "Re'sen takdir beklenmeden ikmal tarhı",
        ["Evet; ikmal tarhı her durumda beş yıl bekletilir", "Evet; iki tarh türü aynı olayda uygulanamaz", "Hayır; yalnız tahsil işlemi yapılıp iki tarh da kaldırılır", "Evet; önce verginin tamamen terkin edilmesi gerekir"],
        ["İkmal tarhiyatı hiçbir zaman yapılamaz", "İki tarhın da tahsil sonrasına bırakılması gerekir", "Yalnız mükellefin yazılı izniyle ikmal tarhı yapılır", "Re'sen tarh sebebi ikmal farkını kendiliğinden siler"],
        "Belgeye dayalı ikmal farkı, re'sen takdir sürecinin sonucu beklenmeden tarh edilebilir.",
        "Re'sen takdirde aynı fark dikkate alınmışsa daha önce tarh edilen vergi son hesaplamada indirilir.",
        "213 sayılı VUK m. 30", "hard",
    ),
    r(
        "Mükellef kanuni zamanda başvuru yükümlülüğünü yerine getirmediği için vergi zamanında tarh edilememiş; olay ikmalen ve re'sen tarh kapsamına da girmemektedir. Tarh türü hangisidir?",
        "İdarece tarhın ayırt edici koşulu hangisidir?",
        "Verginin idarece tarhı",
        "Yükümlülük ihlalinde kanuni matrahtan idarece tarh",
        ["Verginin ikmalen tarhı", "Verginin re'sen tarhı", "Beyana dayalı olağan tarh", "Tahakkuku tahsile bağlı tarh"],
        ["Önceki tarhtan sonra belgeli matrah farkı bulunması", "Matrahın kayıt ve belgelerle hiç belirlenememesi", "Mükellefin süresinde eksiksiz beyanname sunması", "Verginin kanuna uygun biçimde ödenmiş olması"],
        "İkmalen veya re'sen tarh dışında kalan başvuru ya da yükümlülük ihlali, kanuni matrah üzerinden idarece tarha yol açabilir.",
        "İdarece tarh, mükellefin zamanında başvurmaması veya yükümlülüğü yerine getirmemesi nedeniyle zamanında tarh edilemeyen vergiye yöneliktir.",
        "213 sayılı VUK mükerrer m. 30", "medium",
    ),
    r(
        "İdarece tarh edilecek vergi için görevli memurlar mükellefin durumunu yerinde tespit etmiş ve belge düzenlemiştir. Tarh hangi belgeye dayanır?",
        "İdarece tarhın doğrudan dayanak belgesi hangisidir?",
        "Yoklama fişi",
        "Yoklama fişi",
        ["Tahakkuk fişi", "Uzlaşma tutanağı", "Vergi mahkemesi kararı", "Ödeme emri"],
        ["Beyanname makbuzu", "İhtiyati haciz kararı", "Düzeltme dilekçesi", "Tahsilat makbuzu"],
        "VUK, idarece tarhın yoklama sonucu düzenlenen yoklama fişine dayanacağını belirtir.",
        "İdarece tarhta kanunen belli matrahın uygulanmasına ilişkin olgusal dayanak yoklama fişidir.",
        "213 sayılı VUK mükerrer m. 30 ve m. 131", "easy",
    ),
    r(
        "Re'sen takdir edilen matrah, mükellefin daha önce bildirdiği matraha eşittir. Ayrıca re'sen vergi tarh edilir mi?",
        "Re'sen takdir edilen matrah beyan edilen matrahı aşmıyorsa sonuç nedir?",
        "Hayır; ayrıca re'sen vergi tarh edilmez",
        "Beyan edilen matrah aşılmıyorsa re'sen tarh yapılmaz",
        ["Evet; bildirilen matrahın tamamı ikinci kez tarh edilir", "Evet; matrah farkı olmasa da iki kat vergi tarh edilir", "Hayır; önceki beyanname tamamen hükümsüz sayılır", "Evet; yalnız tahakkuk fişi alınmışsa yeniden tarh edilir"],
        ["Beyan edilen verginin tamamı ikinci kez tarh edilir", "Matrah farkı bulunmasa da ceza kadar vergi hesaplanır", "Önceki tarh kendiliğinden iki katına çıkarılır", "Bütün vergi borcu tahsil edilmeden terkin edilir"],
        "Re'sen takdir beyanı aşmıyorsa tarh edilecek yeni matrah farkı bulunmaz.",
        "Takdir edilen matrah daha yüksekse yalnız aradaki fark üzerinden re'sen vergi tarh edilir.",
        "213 sayılı VUK m. 33", "medium",
    ),
    r(
        "Vergi dairesi ikmalen tarh ettiği vergiyi yalnız telefonla bildirmiş, ihbarname düzenlememiştir. Usule uygun mudur?",
        "İkmalen ve re'sen tarh edilen vergiler hangi belgeyle ilgililere tebliğ edilir?",
        "Hayır; ikmalen tarh ihbarnameyle tebliğ edilir",
        "İhbarname",
        ["Evet; sözlü bildirim her durumda ihbarname yerine geçer", "Evet; yalnız tahsilat makbuzu gönderilmesi yeterlidir", "Hayır; ikmalen tarh hiçbir biçimde tebliğ edilmez", "Evet; sadece yoklama fişinin asılması yeterlidir"],
        ["Tahakkuk fişi", "Yoklama fişi", "Ödeme emri", "Beyanname makbuzu"],
        "İkmalen ve re'sen tarh edilen vergiler, muhatabın dava ve düzeltme haklarını da görebileceği ihbarnameyle bildirilir.",
        "VUK ikmalen ve re'sen tarh edilen verginin ihbarnameyle ilgililere tebliğini zorunlu tutar.",
        "213 sayılı VUK m. 34-35", "easy",
    ),
    r(
        "Vergilendirmeyle ilgili hüküm ifade eden belge için muhatabın bilinen adresi vardır; ancak idare doğrudan ilan yoluna gitmiştir. Genel tebliğ esasına uygun mudur?",
        "Bilinen adresi bulunan kişiye tahakkuk fişi dışındaki vergilendirme belgesi genel olarak nasıl tebliğ edilir?",
        "Hayır; bilinen adrese posta yoluyla tebliğ esastır",
        "Bilinen adrese taahhütlü posta",
        ["Evet; bilinen adres olsa da ilan her zaman ilk yoldur", "Evet; yalnız telefon mesajı tebliğ için yeterlidir", "Hayır; belge yalnız vergi dairesi panosuna asılır", "Evet; tebliğ hiçbir yazılı belge kullanılmadan yapılır"],
        ["Her durumda ilan yoluyla", "Yalnız sözlü telefon bildirimiyle", "Sadece belediye ilan panosuyla", "Mükellefin komşusuna bırakılarak"],
        "Bilinen adres varken genel kural posta yoluyla tebliğdir; ilan bilinen adres bulunmayan veya kanundaki şartların oluştuğu hâllerde kullanılır.",
        "Tahakkuk fişi dışındaki hüküm ifade eden belgeler bilinen adreslere posta yoluyla, bilinmeyen adreslerde ilanla tebliğ edilir.",
        "213 sayılı VUK m. 93", "medium",
    ),
]


PREMISES = [
    {"stem":"Vergilendirme aşamaları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tarh vergi alacağını miktar olarak belirler\n\nII. Tahakkuk verginin ödenmesi gereken aşamaya gelmesidir\n\nIII. Tahsil yalnız ihbarnamenin yazıyla bildirilmesidir","correct":"I ve II","why":"Tarh miktarı belirler, tahakkuk ödenebilir aşamayı anlatır; tahsil ise verginin kanuna uygun ödenmesidir.","ref":"213 sayılı VUK m. 20-23","difficulty":"easy"},
    {"stem":"Vergiyi doğuran olay bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Vergi alacağı ancak fiili ödeme anında doğar\n\nII. Vergi alacağı kanunun bağladığı olay gerçekleşince doğar\n\nIII. Vergi alacağı mükellef bakımından vergi borcudur","correct":"II ve III","why":"Vergi alacağı ödeme anında değil vergiyi doğuran olay veya hukuki durum tamamlandığında doğar ve mükellef için borç oluşturur.","ref":"213 sayılı VUK m. 19","difficulty":"medium"},
    {"stem":"Beyana dayanan tarh bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Vergi tahakkuk fişiyle tarh ve tahakkuk ettirilir\n\nII. Fiş nüshası beyanname makbuzu yerine geçer\n\nIII. Fişin alınmaması tahakkuku engellemez","correct":"I, II ve III","why":"Üç ifade de beyana dayalı tarhta tahakkuk fişi esasına uygundur.","ref":"213 sayılı VUK m. 25 ve 27","difficulty":"medium"},
    {"stem":"Elektronik beyan bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tahakkuk fişi elektronik düzenlenebilir\n\nII. Elektronik ileti tahakkuk fişinin tebliği yerine geçer\n\nIII. Elektronik iletim vergiyi fiilen tahsil edilmiş sayar","correct":"I ve II","why":"Elektronik fiş ve ileti tebliğ sonucunu doğurur; verginin fiilen ödendiği anlamına gelmez.","ref":"213 sayılı VUK m. 28","difficulty":"medium"},
    {"stem":"İkmalen tarh bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Daha önce bir vergi tarh edilmiş olmalıdır\n\nII. Matrah farkı yalnız soyut tahmine dayanabilir\n\nIII. Fark defter, kayıt, belge veya kanuni ölçüyle belirlenir","correct":"I ve III","why":"İkmalen tarh önceki tarhı ve nesnel biçimde belirlenen matrah farkını gerektirir; soyut tahmine dayanmaz.","ref":"213 sayılı VUK m. 29","difficulty":"medium"},
    {"stem":"Re'sen tarh bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Matrahın olağan kayıt ve ölçülerle belirlenememesi temel koşuldur\n\nII. Süresinde beyanname verilmemesi sebep olabilir\n\nIII. Zorunlu defterlerin ibraz edilmemesi sebep olabilir","correct":"I, II ve III","why":"Üç ifade de VUK'taki re'sen tarh tanımı ve sebepleriyle uyumludur.","ref":"213 sayılı VUK m. 30","difficulty":"hard"},
    {"stem":"İdarece tarh bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İkmalen ve re'sen tarh dışında kalan hâllere yönelir\n\nII. Mükellefin başvuru veya yükümlülük eksikliği nedeniyle zamanında tarh edilemeyen vergiyi kapsar\n\nIII. Yalnız tahakkuk fişine dayanır","correct":"I ve II","why":"İdarece tarh kanuni matrah ve yoklama fişine dayanır; tahakkuk fişi beyana dayanan tarhın belgesidir.","ref":"213 sayılı VUK mükerrer m. 30","difficulty":"hard"},
    {"stem":"Tebliğ esasları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bilinen adres varsa genel olarak posta yoluyla tebliğ edilir\n\nII. Bilinen adres varken ilan her durumda ilk yoldur\n\nIII. İlgilinin kabulüyle daire veya komisyonda tebliğ yapılabilir","correct":"I ve III","why":"Bilinen adreslerde posta genel esastır; ilgilinin kabulüyle daire veya komisyonda tebliğ de mümkündür. İlan her durumda ilk yol değildir.","ref":"213 sayılı VUK m. 93","difficulty":"medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="vergi_usul_kanunu", topic_id="vergilendirme_sureci",
        label="Vergilendirme Süreci", slug="vergilendirme_sureci", prefix="topic-vs",
        seed=2026071780,
        legislation_version="213 sayılı Vergi Usul Kanunu, Mevzuat Bilgi Sistemi güncel metni, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
