#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — KDV Mekanizması, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Mükellef vergiye tabi satışları nedeniyle müşterilerine KDV yansıtmıştır. Bu tutar mekanizmada nasıl adlandırılır?",
        "Vergiye tabi teslim ve hizmetler üzerinden satıcı tarafından hesaplanan vergi hangisidir?",
        "Satış üzerinden hesaplanan KDV",
        "Teslim ve hizmet üzerinden hesaplanan KDV",
        ["İndirilecek KDV", "Devreden KDV", "İade edilecek KDV", "Tecil edilen KDV"],
        ["Yüklenilen ancak indirilemeyen KDV", "Önceki dönemden devreden KDV", "İthalatta ertelenen vergi", "Gider yazılan vergi"],
        "Vergiye tabi işlem üzerinden müşteriye yansıtılan vergi hesaplanan KDV'dir.",
        "Hesaplanan KDV, satış ve hizmet işlemleri nedeniyle doğan çıktı vergisidir.",
        "3065 sayılı KDVK m. 29/1",
        "easy",
    ),
    r(
        "Mükellefin faaliyetiyle ilgili alış faturasında ayrıca gösterilen KDV, kanuni koşulları da taşımaktadır. Bu tutar nasıl adlandırılır?",
        "Faaliyete ilişkin alış ve ithalat nedeniyle yüklenilip hesaplanan vergiden düşülebilen KDV hangisidir?",
        "İndirilecek KDV",
        "İndirilecek KDV",
        ["Hesaplanan KDV", "Ödenecek KDV", "Devreden satış vergisi", "Vergi cezası"],
        ["Satış üzerinden hesaplanan KDV", "KKEG'ye ait indirilemeyen KDV", "Yersiz hesaplanan KDV", "Gecikme faizi"],
        "Faaliyetle ilgili alış belgesinde gösterilen ve indirim şartlarını taşıyan vergi indirilecek KDV'dir.",
        "İndirilecek KDV, mükellefin vergiye tabi faaliyeti için yüklendiği girdi vergisidir.",
        "3065 sayılı KDVK m. 29 ve 34",
        "easy",
    ),
    r(
        "Bir dönemde hesaplanan KDV 18.000 TL, indirilecek KDV 11.000 TL'dir. Başka unsur yoksa ödenecek KDV kaç TL'dir?",
        "Hesaplanan KDV 24.000 TL, indirilecek KDV 15.000 TL ise ödenecek vergi kaç TL'dir?",
        "7.000 TL",
        "9.000 TL",
        ["29.000 TL", "18.000 TL", "11.000 TL", "0 TL"],
        ["39.000 TL", "24.000 TL", "15.000 TL", "0 TL"],
        "Ödenecek KDV, hesaplanan vergiden indirilecek verginin çıkarılmasıyla 18.000 - 11.000 = 7.000 TL bulunur.",
        "Net ödenecek KDV 24.000 - 15.000 = 9.000 TL'dir.",
        "3065 sayılı KDVK m. 29/1",
        "easy",
    ),
    r(
        "Bir dönemde hesaplanan KDV 9.000 TL, indirilecek KDV 14.000 TL'dir. İade hakkı doğuran özel işlem yoktur. Sonuç hangisidir?",
        "Hesaplanan KDV 16.000 TL, indirilecek KDV 21.000 TL ise genel mekanizmada fark nasıl değerlendirilir?",
        "5.000 TL sonraki döneme devreder",
        "5.000 TL devreden KDV oluşur",
        ["5.000 TL ödenecek KDV çıkar", "23.000 TL ödenecek KDV çıkar", "14.000 TL vergi cezası doğar", "9.000 TL gider yazılır"],
        ["5.000 TL ödenecek KDV çıkar", "37.000 TL vergi borcu doğar", "21.000 TL hasılata eklenir", "16.000 TL ceza kesilir"],
        "İndirilecek verginin hesaplanan vergiyi aşan 5.000 TL'lik kısmı genel kural olarak sonraki döneme devreder.",
        "21.000 - 16.000 = 5.000 TL devreden KDV oluşur.",
        "3065 sayılı KDVK m. 29/2",
        "easy",
    ),
    r(
        "İndirilecek KDV hesaplanan KDV'yi aşmış, ancak işlem özel bir iade hakkına girmemiştir. Farkın genel sonucu hangisidir?",
        "KDVK m. 29/2'de indirilecek verginin hesaplanan vergiden fazla olması hâlinde temel kural hangisidir?",
        "Sonraki döneme devredilir",
        "Devredilir ve genel olarak iade edilmez",
        ["Aynı gün nakden iade edilir", "Kurum kazancına eklenir", "Vergi cezasına dönüşür", "Mükellefiyet sona erer"],
        ["Her durumda nakden iade edilir", "Satış hasılatı sayılır", "Vergi ziyaı cezası olur", "Ortaklara dağıtılır"],
        "Özel iade hükümleri saklı olmak üzere indirim fazlası sonraki döneme devreder ve genel olarak iade edilmez.",
        "KDV'nin temel zincir mekanizmasında fazla girdi vergisi gelecek döneme taşınır.",
        "3065 sayılı KDVK m. 29/2 ve 32",
        "medium",
    ),
    r(
        "Önceki dönemden devreden KDV 3.000 TL, cari dönem indirilecek KDV 7.000 TL ve hesaplanan KDV 12.000 TL'dir. Ödenecek KDV kaç TL'dir?",
        "Devreden KDV 4.000 TL, cari alış KDV'si 6.000 TL ve hesaplanan KDV 13.000 TL ise net ödenecek vergi kaç TL'dir?",
        "2.000 TL",
        "3.000 TL",
        ["22.000 TL", "12.000 TL", "10.000 TL", "0 TL"],
        ["23.000 TL", "13.000 TL", "10.000 TL", "0 TL"],
        "Toplam indirilecek KDV 3.000 + 7.000 = 10.000 TL; ödenecek KDV 12.000 - 10.000 = 2.000 TL'dir.",
        "Toplam indirim 4.000 + 6.000 = 10.000 TL; ödenecek vergi 13.000 - 10.000 = 3.000 TL'dir.",
        "3065 sayılı KDVK m. 29",
        "medium",
    ),
    r(
        "Mükellefin toplam alış KDV'si 10.000 TL'dir; bunun 6.000 TL'si indirim hakkı tanınan işlemlere, kalanı indirim hakkı tanınmayan işlemlere aittir. İndirilebilecek tutar kaç TL'dir?",
        "İndirim hakkı olan işleme 8.000 TL, olmayan işleme 5.000 TL KDV isabet ediyorsa indirilecek KDV kaç TL'dir?",
        "6.000 TL",
        "8.000 TL",
        ["10.000 TL", "4.000 TL", "16.000 TL", "0 TL"],
        ["13.000 TL", "5.000 TL", "3.000 TL", "0 TL"],
        "Kısmi indirimde yalnız indirim hakkı tanınan işlemlere isabet eden 6.000 TL dikkate alınır.",
        "İndirim hakkı tanınan işleme ait 8.000 TL indirilebilir; diğer kısım indirilemez.",
        "3065 sayılı KDVK m. 33",
        "medium",
    ),
    r(
        "Alış faturasında mal bedeli gösterilmiş ancak KDV ayrıca gösterilmemiştir; işlem ayrı gösterim zorunluluğundadır. İndirim koşulu bakımından eksik olan nedir?",
        "Yurt içi alış KDV'sinin indirilebilmesi için faturada hangi gösterim aranır?",
        "KDV'nin ayrıca gösterilmesi",
        "KDV'nin ayrıca gösterilmesi",
        ["Satıcının sermayesinin yazılması", "Alıcının çalışan sayısının belirtilmesi", "Malın piyasa değerinin yazılması", "Faturanın noter onaylı olması"],
        ["Satıcının kurum kazancının yazılması", "Alıcının banka bakiyesinin gösterilmesi", "Ortakların paylarının belirtilmesi", "Vergi dairesinin kaşesi"],
        "İndirim için KDV'nin fatura veya benzeri belgede ayrıca gösterilmesi gerekir.",
        "Belgede ayrı gösterim, indirilecek verginin tutar ve kaynağının doğrulanmasını sağlar.",
        "3065 sayılı KDVK m. 34/1",
        "easy",
    ),
    r(
        "KDV alış faturasında ayrıca gösterilmiş, ancak fatura kanuni defterlere hiç kaydedilmemiştir. İndirim bakımından sonuç hangisidir?",
        "Alış belgesindeki KDV'nin indirimi için ayrı gösterim yanında hangi kayıt şartı aranır?",
        "Kayıt yapılmadan indirim kullanılamaz",
        "Belgenin kanuni defterlere kaydedilmesi",
        ["Belge düzenlenince kayıt gereksizdir", "Sözlü beyan indirim için yeterlidir", "Yalnız ödeme yapılması yeterlidir", "Noter onayı kayıt yerine geçer"],
        ["Belgenin yalnız dosyada saklanması", "Satıcının kâr etmesi", "Alıcının sermaye artırması", "Ödemenin nakit yapılması"],
        "KDV'nin indirimi için belge kanuni defterlere kaydedilmiş olmalıdır.",
        "Ayrı gösterim ve kanuni defter kaydı indirim hakkının birlikte aranan belge koşullarıdır.",
        "3065 sayılı KDVK m. 34/1",
        "easy",
    ),
    r(
        "Bir alışa ait fatura, vergiyi doğuran olayın gerçekleştiği yılı izleyen takvim yılı içinde kanuni deftere kaydedilmiştir. Süre bakımından indirim mümkün müdür?",
        "KDV indirim hakkı, vergiyi doğuran olayın gerçekleştiği yılı izleyen hangi sınır aşılmadan kullanılabilir?",
        "Evet; kayıt döneminde kullanılabilir",
        "İzleyen takvim yılı sonuna kadar",
        ["Hayır; yalnız aynı gün kullanılabilir", "Hayır; yalnız fatura ayında kullanılabilir", "Evet; süresiz kullanılabilir", "Yalnız beş yıl sonra kullanılabilir"],
        ["Süresiz olarak", "Yalnız vergiyi doğuran olay günü", "Beşinci yılın sonuna kadar", "Mükellefin seçtiği herhangi bir yıl"],
        "Belge, olayın gerçekleştiği takvim yılını izleyen takvim yılı aşılmadan kaydedilmişse indirim kayıt döneminde kullanılabilir.",
        "KDVK m. 29/3 indirim hakkını, izleyen takvim yılını aşmama ve kayıt şartına bağlar.",
        "3065 sayılı KDVK m. 29/3",
        "hard",
    ),
    r(
        "Mükellef faaliyeti için ithal ettiği makine nedeniyle gümrükte KDV ödemiştir. Kanuni koşullar sağlanıyorsa bu KDV'nin durumu hangisidir?",
        "İthal olunan mal ve hizmetler dolayısıyla ödenen KDV mekanizmada nasıl değerlendirilir?",
        "İndirilecek KDV olabilir",
        "Hesaplanan KDV'den indirilebilir",
        ["Her durumda vergi cezasıdır", "Satış hasılatına eklenir", "Örtülü sermaye faizi sayılır", "Menkul sermaye iradı olur"],
        ["İthalat bedeline ikinci kez vergi olarak eklenir", "Kurumlar vergisi sayılır", "Yalnız gümrük cezasıdır", "Ücret stopajına mahsup edilir"],
        "Faaliyetle ilgili ithalat nedeniyle ödenen KDV, diğer indirim koşulları da varsa hesaplanan vergiden indirilebilir.",
        "KDVK m. 29 ithal olunan mal ve hizmetler için ödenen KDV'yi indirim kapsamına alır.",
        "3065 sayılı KDVK m. 29/1-b ve 34",
        "easy",
    ),
    r(
        "Vergi kesintisi yapmakla sorumlu tutulan mükellef, sorumlu sıfatıyla KDV'yi beyan etmiş ancak henüz ödememiştir. İndirim şartı bakımından eksik olan nedir?",
        "Sorumlu sıfatıyla yüklenilen KDV'nin indirilebilmesi için beyanın yanında hangi koşul aranır?",
        "Verginin ödenmesi",
        "Beyan edilen KDV'nin ödenmesi",
        ["Satıcının sermaye artırması", "Alıcının kâr dağıtması", "İşlemin noter onayı", "Verginin gider yazılması"],
        ["Kurum kazancının dağıtılması", "Faturanın yalnız arşivlenmesi", "Ortakların onayı", "Verginin cezaya çevrilmesi"],
        "Sorumlu sıfatıyla beyan edilen KDV'nin indirim konusu yapılması için verginin ödenmiş olması gerekir.",
        "KDVK m. 29/1-ç sorumlu sıfatıyla beyan ve ödeme koşullarını birlikte arar.",
        "3065 sayılı KDVK m. 29/1-ç",
        "hard",
    ),
    r(
        "Satıcı tarafından hesaplanıp beyan edilen KDV'yi içeren alacak VUK'a göre değersiz hâle gelmiş ve zarar yazılmıştır. Satıcı bu KDV'yi ne zaman indirim konusu yapabilir?",
        "Değersiz alacağa ilişkin hesaplanıp beyan edilen KDV için satıcıya tanınan mekanizma hangisidir?",
        "Alacağın zarar yazıldığı dönemde",
        "Zarar yazılan dönemde indirim",
        ["Faturanın düzenlendiği gün yeniden", "Alıcının kuruluş tarihinde", "Beş yıl sonra kendiliğinden", "Hiçbir dönemde"],
        ["Satışın hasılattan silinmemesi", "Verginin ikinci kez hesaplanması", "Alıcının sermayesine eklenmesi", "Yalnız ceza indirimi"],
        "Değersiz alacağa ilişkin hesaplanan ve beyan edilen KDV, alacağın zarar yazıldığı dönemde indirim konusu yapılabilir.",
        "Bu düzenleme tahsil edilemeyen bedel içindeki daha önce beyan edilmiş KDV'yi satıcı yönünden düzeltir.",
        "3065 sayılı KDVK m. 29/4",
        "hard",
    ),
    r(
        "Vergiye tabi işlem bulunmadığı hâlde faturada KDV gösteren kişi, gösterilen vergi için hangi yükümlülükle karşılaşır?",
        "KDV göstermeye hakkı olmadığı hâlde belgede KDV gösteren kişinin temel yükümlülüğü hangisidir?",
        "Gösterilen KDV'yi ödemek",
        "Gösterilen vergiyi ödemek",
        ["Vergiyi kendiliğinden yok saymak", "KDV'yi kurum kazancına çevirmek", "Yalnız faturayı iptal etmek", "Alıcıya ücret bordrosu vermek"],
        ["Vergiyi beyan dışı bırakmak", "Tutarı sermayeye eklemek", "Yalnız noter bildirimi yapmak", "KDV'yi gelir vergisine çevirmek"],
        "Belgede yersiz veya fazla KDV gösteren kişi bu vergiyi ödemekle yükümlüdür; düzeltme ve iade ayrı şartlara bağlıdır.",
        "Faturada gösterilen vergi, işlem vergisiz olsa bile Hazineye karşı ödeme yükümlülüğü doğurur.",
        "3065 sayılı KDVK m. 8/2",
        "medium",
    ),
    r(
        "Yurt dışındaki hizmet sağlayıcının Türkiye'de ikametgâhı, işyeri ve merkezi yoktur. Vergi alacağını güvenceye almak için alıcı sorumlu tutulmuştur. Kurum hangisidir?",
        "KDVK m. 9 kapsamında işlem tarafının verginin ödenmesinden sorumlu tutulmasının amacı hangisidir?",
        "KDV sorumluluğu",
        "Vergi alacağını güvenceye almak",
        ["Kurumlar vergisi muafiyeti", "Gelir vergisi istisnası", "Emlak vergisi bildirimi", "Damga vergisi iadesi"],
        ["Mükellefin ticari kârını artırmak", "Ortakların ücretini belirlemek", "Şirket sermayesini tamamlamak", "İşlemi KDV dışına çıkarmak"],
        "Türkiye'de yerleşik merkezi bulunmayan işlem tarafında alıcı vergi alacağını güvenceye almak için sorumlu tutulabilir.",
        "Vergi sorumluluğu, tahsil güvenliğini sağlamak üzere işlem tarafına beyan ve ödeme ödevi yükler.",
        "3065 sayılı KDVK m. 9/1",
        "medium",
    ),
    r(
        "Satıcı faturada ticari teamüle uygun 2.000 TL iskonto göstermiştir. KDV matrahı açısından iskonto nasıl değerlendirilir?",
        "Faturada gösterilen ve ticari teamüle uygun iskonto KDV matrahına dâhil midir?",
        "Matraha dâhil edilmez",
        "Hayır; matrah dışında kalır",
        ["Matraha iki kez eklenir", "Hesaplanan KDV sayılır", "İndirilecek KDV yapılır", "Vergi cezasına dönüşür"],
        ["Evet; her durumda matraha eklenir", "Yalnız kurum kazancına eklenir", "Devreden KDV sayılır", "Vergi sorumluluğu doğurur"],
        "Belgede gösterilen ve ticari teamüle uygun iskonto KDV matrahına dâhil değildir.",
        "İskontonun matrah dışında kalması için fatura veya benzeri belgede gösterilmesi ve teamüle uygun olması gerekir.",
        "3065 sayılı KDVK m. 25/a",
        "easy",
    ),
    r(
        "Bir işlemde mal bedeli ile bu bedel üzerinden hesaplanan KDV ayrı gösterilmiştir. Hesaplanan KDV kendi matrahına dâhil edilir mi?",
        "KDVK'ya göre hesaplanan katma değer vergisi matrahın bir unsuru mudur?",
        "Hayır; matraha dâhil değildir",
        "Matraha dâhil değildir",
        ["Evet; matraha tekrar eklenir", "Yalnız ithalatta matraha eklenir", "Devreden KDV sayılır", "Ticari iskonto kabul edilir"],
        ["Matrahın zorunlu unsurudur", "Yalnız ücrette matraha girer", "Örtülü sermaye sayılır", "Kur farkı olarak eklenir"],
        "Hesaplanan KDV, KDV matrahına dâhil olmayan unsurlardandır.",
        "Verginin kendi matrahına yeniden eklenmemesi vergi üzerinden vergi hesaplanmasını önler.",
        "3065 sayılı KDVK m. 25/b",
        "easy",
    ),
    r(
        "Satıcı, malı alıcının gösterdiği yere götürmek için taşıma ve yükleme bedelini alıcıdan ayrıca tahsil etmiştir. Bu bedeller matraha girer mi?",
        "Satıcının teslim yerine kadar yaptığı taşıma, yükleme ve boşaltma giderleri KDV matrahında nasıl değerlendirilir?",
        "Evet; matraha dâhildir",
        "Matraha dâhildir",
        ["Hayır; her durumda matrah dışıdır", "Yalnız indirilecek KDV sayılır", "Vergi cezasına dönüşür", "GMSİ olarak vergilenir"],
        ["Matrah dışında kalır", "İskonto sayılır", "Devreden KDV olur", "Yalnız kurum kazancına eklenir"],
        "Teslim yerine kadar satıcı tarafından yapılan taşıma, yükleme ve boşaltma giderleri matraha dâhildir.",
        "Bu yan edimler teslim bedelinin ekonomik tamamlayıcısı olarak KDV matrahına eklenir.",
        "3065 sayılı KDVK m. 24/a",
        "easy",
    ),
    r(
        "Vadeli satış nedeniyle faturada ayrıca vade farkı ve kur farkı hesaplanmıştır. Bu gelirlerin KDV matrahına etkisi hangisidir?",
        "Vade farkı, fiyat farkı, kur farkı ve faiz KDV matrahında nasıl değerlendirilir?",
        "Matraha dâhil edilir",
        "Matraha dâhildir",
        ["Ticari iskonto gibi çıkarılır", "Devreden KDV sayılır", "Vergi cezası kabul edilir", "Menkul sermaye iradı olur"],
        ["Matrah dışında tutulur", "Yalnız gelir vergisine tabidir", "İndirilecek KDV sayılır", "İşlem bedelinden düşülür"],
        "Vade, fiyat ve kur farkları ile faiz ve benzeri menfaatler KDV matrahına dâhildir.",
        "İşlem bedeline bağlı bu ek gelirler matrahı artırır.",
        "3065 sayılı KDVK m. 24/c",
        "medium",
    ),
    r(
        "Satılan malın bir kısmı sonraki dönemde iade edilmiş ve bedel azalmıştır. Satıcı ile alıcı KDV kayıtlarını hangi dönemde düzeltir?",
        "Mal iadesi veya işlemden vazgeçme nedeniyle matrah değişirse KDV düzeltmesi ne zaman yapılır?",
        "Değişikliğin gerçekleştiği dönemde",
        "Değişiklik döneminde",
        ["İlk faturanın yılından bağımsız beş yıl sonra", "Hiçbir zaman", "Yalnız işletme kapanınca", "Ortakların karar verdiği dönemde"],
        ["Yalnız ilk satış döneminde", "Süresiz ertelenerek", "Mükellefiyet bitince", "Kurum kazancı dağıtılınca"],
        "İade veya vazgeçmeyle değişen matrah ve indirim tutarları, değişikliğin meydana geldiği dönemde uygun yönde düzeltilir.",
        "KDVK m. 35 satıcı borcunu ve alıcı indirimini aynı ekonomik değişikliğe uyumlu hâle getirir.",
        "3065 sayılı KDVK m. 35",
        "medium",
    ),
    r(
        "KDV mükellefinin bir vergilendirme döneminde vergiye tabi işlemi bulunmamaktadır. Beyanname verme yükümlülüğü devam eder mi?",
        "Vergiye tabi işlemi olmayan KDV mükellefi dönem beyannamesi bakımından ne yapmalıdır?",
        "Evet; beyanname vermelidir",
        "Beyanname vermelidir",
        ["Hayır; mükellefiyet kendiliğinden biter", "Yalnız kurumlar beyannamesi verir", "Münferit beyanname verir", "Hiçbir bildirim yapmaz"],
        ["Mükellefiyetini silmelidir", "Yalnız ücret bordrosu verir", "Beyannameyi beş yıl erteler", "Sadece emlak bildirimi yapar"],
        "KDV mükellefi, ilgili dönemde vergiye tabi işlemi olmasa da beyanname vermek zorundadır.",
        "KDV beyan yükümlülüğü yalnız işlem bulunan dönemlerle sınırlı değildir.",
        "3065 sayılı KDVK m. 40/3",
        "easy",
    ),
    r(
        "KDVK m. 9 uyarınca vergi kesintisi yapmakla sorumlu tutulan kişi için vergilendirme dönemi nedir?",
        "Vergi kesintisi yapmakla sorumlu tutulanlarda KDV vergilendirme dönemi hangi zaman birimidir?",
        "Bir ay",
        "Aylık dönem",
        ["Bir gün", "Üç yıl", "Beş takvim yılı", "Mükellefin seçtiği dönem"],
        ["Bir takvim yılı", "Beş yıllık dönem", "İki hesap dönemi", "Süresiz dönem"],
        "Vergi kesintisi yapmakla sorumlu tutulanlarda vergilendirme dönemi bir aydır.",
        "Sorumlu sıfatıyla KDV beyanı aylık vergilendirme dönemine bağlanmıştır.",
        "3065 sayılı KDVK m. 39/2-b",
        "easy",
    ),
    r(
        "Faaliyeti binek otomobili kiralamak veya işletmek olmayan şirket, aldığı binek otomobilin KDV'sini indirmek istemektedir. Genel kural hangisidir?",
        "İşletmeye ait binek otomobili alış KDV'si hangi durumda genel indirim yasağının dışında kalır?",
        "İndirilemez",
        "Araç kiralama veya işletme faaliyetinde kullanıldığında",
        ["Her durumda tam indirilir", "Satış KDV'sine eklenir", "Devreden KDV'ye zorunlu eklenir", "Vergi cezası olarak ödenir"],
        ["Yöneticiye tahsis edildiğinde", "Ortağın özel kullanımında", "Faaliyetle ilgisiz tutulduğunda", "Yalnız sermayeye kaydedildiğinde"],
        "Binek otomobili kiralama veya işletme faaliyeti dışındaki işletmelerde alış KDV'si genel olarak indirilemez.",
        "İstisna, binek otomobillerin kiralanması veya çeşitli biçimlerde işletilmesi faaliyetinde kullanılan araçlara yöneliktir.",
        "3065 sayılı KDVK m. 30/b",
        "medium",
    ),
    r(
        "Stok malı deprem ve sel dışındaki olağan bir nedenle zayi olmuştur; kanundaki özel istisna yoktur. Bu mala ait KDV'nin durumu hangisidir?",
        "Zayi olan mallara ait KDV bakımından genel kural hangisidir?",
        "İndirilemez",
        "Hesaplanan KDV'den indirilemez",
        ["Her durumda indirilir", "Satış hasılatına eklenir", "Kurumlar vergisine mahsup edilir", "Ücret stopajına çevrilir"],
        ["Her zayi hâlinde tam indirilir", "Devreden KDV'ye koşulsuz eklenir", "Gelir vergisinden mahsup edilir", "İhracat istisnası sayılır"],
        "Kanundaki afet ve faydalı ömür istisnaları dışında zayi mallara ait KDV indirilemez.",
        "KDVK m. 30/c zayi mallar için genel indirim yasağı koyar ve belirli istisnalar düzenler.",
        "3065 sayılı KDVK m. 30/c",
        "medium",
    ),
    r(
        "Kurumlar vergisi bakımından KKEG olan bir harcama için KDV ödenmiştir; kanundaki özel istisna yoktur. KDV'nin durumu hangisidir?",
        "Gelir veya kurum kazancında indirimi kabul edilmeyen giderlere ait KDV için genel kural hangisidir?",
        "İndirilemez",
        "Hesaplanan KDV'den indirilemez",
        ["Her durumda indirilir", "Satış KDV'sine dönüşür", "Geçmiş yıl zararı sayılır", "İştirak istisnası olur"],
        ["İndirilecek KDV'ye koşulsuz eklenir", "Kurumlar vergisinden mahsup edilir", "Devreden zarara dönüşür", "İade hakkı doğurur"],
        "Kazancın tespitinde indirilemeyen giderlere ait KDV, özel hüküm yoksa KDV indirimine de konu olmaz.",
        "KDVK m. 30/d KKEG ile bağlantılı girdi vergisini genel olarak indirim dışında bırakır.",
        "3065 sayılı KDVK m. 30/d",
        "medium",
    ),
    r(
        "Mükellef hem indirim hakkı tanınan ihracat hem de indirim hakkı tanınmayan istisna işlem yapmaktadır. Ortak gider KDV'si nasıl ayrılır?",
        "İndirim hakkı tanınan ve tanınmayan işlemler birlikte yapılırsa ortak KDV'nin hangi kısmı indirilebilir?",
        "İndirim hakkı tanınan işleme düşen kısım",
        "İndirim hakkı olan işleme isabet eden kısım",
        ["Ortak KDV'nin tamamı", "Ortak KDV'nin hiçbir kısmı", "Yalnız satış KDV'si", "Mükellefin seçtiği rastgele kısım"],
        ["İndirim hakkı olmayan işleme düşen kısım", "KDV'nin tamamı", "Yalnız en yüksek tutarlı kısım", "Ortakların payına düşen kısım"],
        "Kısmi indirimde ortak KDV'nin yalnız indirim hakkı tanınan işlemlere isabet eden bölümü indirilebilir.",
        "Ortak girdiler, işlemlerin indirim hakkına göre ayrıştırılır.",
        "3065 sayılı KDVK m. 33",
        "hard",
    ),
]


PREMISES = [
    {"stem":"KDV'nin temel mahsup mekanizması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hesaplanan KDV satış işlemlerinden doğar\n\nII. İndirilecek KDV faaliyet girdileriyle ilgilidir\n\nIII. Ödenecek KDV temel olarak hesaplanan vergiden indirimlerin düşülmesiyle bulunur","correct":"I, II ve III","why":"Üç ifade de çıktı vergisi, girdi vergisi ve net ödeme ilişkisini açıklar.","ref":"3065 sayılı KDVK m. 29","difficulty":"easy"},
    {"stem":"Devreden KDV bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İndirim toplamı hesaplanan KDV'yi aşınca oluşabilir\n\nII. Genel kural olarak sonraki döneme taşınır\n\nIII. Her durumda aynı gün nakden iade edilir","correct":"I ve II","why":"İndirim fazlası devreder; iade yalnız kanundaki özel iade hakkı bulunan durumlarda mümkündür.","ref":"3065 sayılı KDVK m. 29/2 ve 32","difficulty":"medium"},
    {"stem":"KDV indiriminin belgelendirilmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KDV belgede ayrıca gösterilmelidir\n\nII. Sözlü açıklama her durumda yeterlidir\n\nIII. Belge kanuni deftere kaydedilmelidir","correct":"I ve III","why":"İndirim için ayrı gösterim ve kanuni defter kaydı birlikte aranır.","ref":"3065 sayılı KDVK m. 34","difficulty":"medium"},
    {"stem":"KDV matrahı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Hesaplanan KDV kendi matrahına dâhildir\n\nII. Teslim yerine kadar taşıma gideri matraha dâhildir\n\nIII. Faturadaki teamüle uygun iskonto matrah dışındadır","correct":"II ve III","why":"Hesaplanan KDV matrah dışı; taşıma gideri matraha dâhil; uygun fatura iskontosu matrah dışıdır.","ref":"3065 sayılı KDVK m. 24-25","difficulty":"medium"},
    {"stem":"İndirilemeyen KDV bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. KKEG'ye ait KDV genel olarak indirilemez\n\nII. Kanuni istisna dışındaki zayi mal KDV'si indirilemez\n\nIII. Her binek otomobil KDV'si koşulsuz indirilebilir","correct":"I ve II","why":"KKEG ve zayi mal KDV'sinde genel indirim yasağı vardır; binek araç istisnası faaliyet koşuluna bağlıdır.","ref":"3065 sayılı KDVK m. 30/b-d","difficulty":"medium"},
    {"stem":"KDV düzeltme ve sorumluluğu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mal iadesinde satıcı ve alıcı uygun düzeltme yapar\n\nII. Yersiz KDV gösteren kişi gösterdiği vergiyi öder\n\nIII. Sorumlu sıfatıyla beyan edilen KDV indiriminde ödeme koşulu aranır","correct":"I, II ve III","why":"Üç ifade m. 8, 29 ve 35'teki ödeme, indirim ve düzeltme hükümlerine uygundur.","ref":"3065 sayılı KDVK m. 8/2, 29/1-ç ve 35","difficulty":"hard"},
    {"stem":"KDV indirim süreci bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İthalatta ödenen faaliyet KDV'si indirilebilir\n\nII. İzleyen takvim yılı aşılmadan kayıt koşulu aranır\n\nIII. Fatura olmadan her alış KDV'si indirilebilir","correct":"I ve II","why":"İthal KDV indirim kapsamındadır; indirim süresi ve belge-kayıt şartı vardır.","ref":"3065 sayılı KDVK m. 29/1-b, 29/3 ve 34","difficulty":"hard"},
    {"stem":"Kısmi KDV indirimi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ortak girdi KDV'sinin tamamı her durumda indirilir\n\nII. İndirim hakkı olan işleme ait kısım indirilebilir\n\nIII. İndirim hakkı olmayan işleme ait kısım ayrıştırılır","correct":"II ve III","why":"Kısmi indirimde ortak KDV, işlemlerin indirim hakkına göre ayrıştırılır.","ref":"3065 sayılı KDVK m. 33","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="katma_deger_vergisi",
        topic_id="kdv_mekanizmasi",
        label="KDV Mekanizması",
        slug="kdv_mekanizmasi",
        prefix="topic-kdv-km",
        seed=170731,
        legislation_version="3065 sayılı Katma Değer Vergisi Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
