#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Beyan ve Kazanç Tespiti, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Mükellefin geliri için Kanunda özel bir tarh usulü öngörülmemiştir. Gelir vergisi hangi temel yöntemle tarh olunur?",
        "GVK'da aksine hüküm bulunmadıkça gelir vergisinin tarhını başlatan temel işlem hangisidir?",
        "Mükellef veya sorumlunun beyanı",
        "Mükellef veya vergi sorumlusunun beyanı",
        ["Vergi dairesinin sözlü tahmini", "İşverenin özel hukuk bildirimi", "Noterin tek taraflı değerlemesi", "Bankanın hesap kapatma işlemi"],
        ["Vergi mahkemesinin kesinleşmiş ceza kararı", "Belediyenin ruhsat işlemi", "Ticaret sicilinin tescili", "Bankanın kredi tahsisi"],
        "GVK m. 83 uyarınca, aksine hüküm yoksa gelir vergisi mükellefin veya vergi sorumlusunun beyanı üzerine tarh olunur.",
        "Gelir vergisinde temel tarh dayanağı mükellefin ya da sorumlunun beyanıdır.",
        "193 sayılı GVK m. 83",
        "easy",
    ),
    r(
        "Mükellef bir yılın gelirini, işveren ise kestiği vergileri, dar mükellef de belirli kazancını bildirecektir. Kullanılabilecek beyanname türleri hangileridir?",
        "GVK'da gelir vergisi beyanları hangi üç beyannameyle yapılır?",
        "Yıllık, muhtasar ve münferit",
        "Yıllık, muhtasar, münferit",
        ["Geçici, özel ve ek", "Aylık, üç aylık ve dönemsel", "Sözlü, yazılı ve elektronik", "Tarh, tahakkuk ve tahsil"],
        ["Bilanço, işletme ve serbest meslek", "Tarh, tebliğ ve tahakkuk", "Ücret, kira ve faiz", "Ticari, zirai ve mesleki"],
        "GVK m. 84 beyanları yıllık, muhtasar ve münferit beyanname olarak üçe ayırır.",
        "Kanundaki beyanname türleri yıllık, muhtasar ve münferit beyannamelerdir.",
        "193 sayılı GVK m. 84",
        "easy",
    ),
    r(
        "Gerçek kişi aynı takvim yılında farklı kaynaklardan elde ettiği beyana tabi gelirleri tek bildirimde toplamıştır. Bu bildirim hangisidir?",
        "Bir takvim yılındaki çeşitli kaynaklardan elde edilen gelirlerin toplanarak bildirilmesine özgü beyanname hangisidir?",
        "Yıllık beyanname",
        "Yıllık beyanname",
        ["Muhtasar beyanname", "Münferit beyanname", "Damga vergisi beyannamesi", "KDV beyannamesi"],
        ["Münferit beyanname", "Muhtasar beyanname", "Geçici vergi bildirimi", "Ücret bordrosu"],
        "Yıllık beyanname, bir takvim yılındaki farklı gelir kaynaklarının toplanıp vergi dairesine bildirilmesine yarar.",
        "Gelirin yılın yalnız bir bölümüne ait olması da bildirimin yıllık beyanname niteliğini değiştirmez.",
        "193 sayılı GVK m. 84/1",
        "easy",
    ),
    r(
        "Dar mükellef, yıllık beyannameye girmeyen ve tevkif edilmemiş bir kazanç elde etmiştir. Kullanılacak beyanname türü hangisidir?",
        "Dar mükellefin yıllık beyanla bildirmek zorunda olmadığı ve tevkif edilmemiş kazancı hangi beyannameye konu olur?",
        "Münferit beyanname",
        "Münferit beyanname",
        ["Muhtasar beyanname", "Yıllık ücret bordrosu", "KDV beyannamesi", "Emlak vergisi bildirimi"],
        ["Yıllık kurumlar beyannamesi", "Muhtasar beyanname", "Geçici vergi bildirimi", "Servet bildirimi"],
        "Münferit beyanname, dar mükellefin yıllık beyana girmeyen ve tevkif edilmemiş kazanç ve iratlarına özgüdür.",
        "Bu nitelikteki dar mükellef gelirleri münferit beyannameyle bildirilir.",
        "193 sayılı GVK m. 84/3 ve 101",
        "medium",
    ),
    r(
        "Mükellef, Kanunda ayrı tutulanlar dışındaki beyana tabi gelirlerini yıllık beyannamede bir araya getirmemiştir. Hangi ilkeye aykırıdır?",
        "Beyanı gereken gelirlerin yıllık beyannamede bir araya getirilmesi bakımından kural hangisidir?",
        "Gelirin toplanması ilkesine",
        "Toplanmaları zorunludur",
        ["Tahakkuk zamanaşımı ilkesine", "Vergi mahremiyeti ilkesine", "Belge düzeni ilkesine", "Tarhiyat sonrası uzlaşmaya"],
        ["Ayrı ayrı bildirilir", "Yalnız ücretler birleştirilir", "Toplama mükellefin seçimine bağlıdır", "Sadece kira gelirleri toplanır"],
        "GVK m. 85, beyanı gereken gelir unsurlarının yıllık beyannamede toplanmasını zorunlu kılar.",
        "Kanunda aksine hüküm bulunmadıkça beyana tabi kazanç ve iratlar yıllık beyannamede toplanır.",
        "193 sayılı GVK m. 85",
        "medium",
    ),
    r(
        "Bir tacir hesap dönemini zararla, bir serbest meslek erbabı ise hasılatsız kapatmıştır. Faaliyetleri sürmektedir. Beyan yükümlülüğü için doğru ifade hangisidir?",
        "Tacir ve serbest meslek erbabının faaliyetinden kazanç doğmaması yıllık beyanı nasıl etkiler?",
        "Yıllık beyanname vermeleri gerekir",
        "Beyan yükümlülüğü devam eder",
        ["Hiçbir bildirim yapmaları gerekmez", "Yalnız muhtasar beyanname verirler", "Münferit beyanname vermeleri gerekir", "Yalnız noter bildirimi yaparlar"],
        ["Kendiliğinden sona erdirir", "Beyannameyi belediyeye yönlendirir", "Yalnız ücret bordrosu gerektirir", "Mükellefiyeti kuruma dönüştürür"],
        "Tacir ve serbest meslek erbabı, faaliyetlerinden kazanç elde etmemiş olsalar dahi yıllık beyanname verir.",
        "Kazanç çıkmaması, devam eden ticari veya mesleki faaliyetin yıllık beyan yükümlülüğünü kaldırmaz.",
        "193 sayılı GVK m. 85",
        "medium",
    ),
    r(
        "İşletme büyüklüğü ölçülerini aşmayan ve gerçek usulde vergilendirilmeyen çiftçinin ürün bedelinden vergi kesilmiştir. Zirai kazanç için genel yöntem hangisidir?",
        "Gerçek usule tabi olmayan çiftçinin zirai kazancı kural olarak nasıl vergilendirilir?",
        "Hasılat üzerinden tevkifat",
        "Hasılat üzerinden tevkifat yoluyla",
        ["Bilanço esasına göre yıllık beyan", "Serbest meslek kazanç defteri", "Münferit beyanname", "Kurum kazancı hesabı"],
        ["Kurumlar vergisi beyannamesiyle", "Ücret bordrosu üzerinden", "Gayrimenkul kira beyanıyla", "Menkul kıymet değerlemesiyle"],
        "Gerçek usulde vergilendirilmeyen çiftçilerin zirai kazancı kural olarak hasılat üzerinden tevkifatla vergilendirilir.",
        "GVK m. 53, gerçek usul dışındaki çiftçiler için hasılat üzerinden vergi kesintisi esasını benimser.",
        "193 sayılı GVK m. 53",
        "medium",
    ),
    r(
        "Gerçek usule tabi çiftçi, zirai işletme hesabında dönemin hasılatı ile giderlerini karşılaştırmıştır. Kazanç hangi farktır?",
        "Zirai işletme hesabı esasına göre kazancın temel tespit biçimi hangisidir?",
        "Hasılat ile giderler arasındaki olumlu fark",
        "Hasılat ve gider farkı",
        ["Yalnız ürün satış bedellerinin toplamı", "İşletmenin kasa mevcudu", "Arazinin emlak vergisi değeri", "Çiftçinin kişisel servet artışı"],
        ["Yalnız ürün satışları", "Kişisel harcamaların hasılata eklenmesi", "Arazinin rayiç değerinin esas alınması", "Sadece nakit satışların dikkate alınması"],
        "Zirai işletme hesabında kazanç, tahsil veya tahakkuk eden hasılat ile ödenen veya borçlanılan giderlerin olumlu farkıdır.",
        "Zirai işletme hesabı, hasılat-gider karşılaştırmasına dayanır; dönem başı ve sonu ürün değerleri de düzeltilir.",
        "193 sayılı GVK m. 55",
        "hard",
    ),
    r(
        "Gerçek usulde vergilendirilmeyen çiftçinin zirai kazancı için yıllık beyanname verip vermeyeceği değerlendirilmektedir. Kural hangisidir?",
        "GVK m. 86'ya göre gerçek usulde vergilendirilmeyen zirai kazanç yıllık beyana nasıl yansır?",
        "Yıllık beyanname verilmez",
        "Yıllık beyana dâhil edilmez",
        ["Mutlaka beyan edilir", "Münferit beyannameye eklenir", "Kurumlar vergisi beyannamesi verilir", "Yalnız emlak bildirimi yapılır"],
        ["Beyana eklenir", "Kurum kazancı sayılarak bildirilir", "Serbest meslek geliriyle birleştirilir", "Münferit beyannameyle bildirilir"],
        "Gerçek usulde vergilendirilmeyen zirai kazanç için yıllık beyanname verilmez ve diğer beyana eklenmez.",
        "Bu zirai kazançlar GVK m. 86'da toplama yapılmayan gelirler arasında sayılır.",
        "193 sayılı GVK m. 86/1-a",
        "medium",
    ),
    r(
        "Dar mükellefin Türkiye'deki ücreti ve kira geliri tamamen tevkif edilmiştir. Başka geliri yoktur. Yıllık beyan bakımından kural hangisidir?",
        "Dar mükellefin Türkiye'de tamamı tevkif edilmiş ücret ve sermaye iratları yıllık beyana nasıl yansır?",
        "Yıllık beyanname verilmez",
        "Yıllık beyana dâhil edilmez",
        ["Tam mükellef gibi bütün gelirler bildirilir", "Mutlaka münferit beyanname verilir", "Yalnız ücret için yıllık beyan verilir", "Kurumlar vergisi beyannamesi gerekir"],
        ["Her durumda yıllık beyanda toplanır", "Yalnız muhtasar beyana eklenir", "Servet bildirimiyle beyan edilir", "Ticari kazanç olarak bildirilir"],
        "Dar mükellefin Türkiye'de tamamı tevkif edilmiş ücret, serbest meslek kazancı ve sermaye iratları yıllık beyana girmez.",
        "GVK m. 86/2, dar mükellefin tamamen tevkif edilmiş sayılı gelirlerini yıllık beyan dışında tutar.",
        "193 sayılı GVK m. 86/2",
        "hard",
    ),
    r(
        "Mükellefin bir gelir kaynağında oluşan zararı, aynı yıl başka kaynaktaki kazançtan düşülmüştür. Zarar diğer kazanç ve iratlardan doğmamıştır. İşlem nedir?",
        "Gelir kaynaklarının bir kısmındaki zararın diğer kaynak kazançlarına etkisi bakımından genel kural hangisidir?",
        "Zararın kazanca mahsubu",
        "Diğer kaynaklardan aynı yıl mahsup edilir",
        ["Vergi cezasının gider yazılması", "Kişisel harcamanın indirimi", "Sermaye kaybının ücretleştirilmesi", "Beyannamenin iptali"],
        ["Hiçbir biçimde dikkate alınmaz", "Yalnız emlak vergisinden düşülür", "Doğrudan vergi cezasına dönüşür", "Sadece muhtasar beyanda gösterilir"],
        "Diğer kazanç ve iratlardan doğan zararlar hariç, bir kaynaktaki zarar aynı yıl diğer kaynak kazançlarına mahsup edilebilir.",
        "GVK m. 88, gelir kaynaklarındaki zararların belirli sınırlarla diğer kaynaklara mahsubuna izin verir.",
        "193 sayılı GVK m. 88",
        "medium",
    ),
    r(
        "Cari yılda kapatılamayan faaliyet zararı sonraki yıllara devredilmiştir. En fazla hangi süre içinde mahsup edilebilir?",
        "GVK'da mahsup edilemeyen zarar bakiyesinin sonraki yıllara taşınma sınırı hangisidir?",
        "Arka arkaya beş yıl",
        "Birbirini izleyen beş yıl",
        ["Yalnız aynı ay", "Süresiz olarak", "Bir sonraki gün", "On takvim yılı"],
        ["Yalnız bir vergilendirme dönemi", "Sınırsız süre", "Her zaman geriye doğru", "Mükellefin seçtiği herhangi bir süre"],
        "Kapatılamayan zarar, izleyen yıllara taşınabilir; arka arkaya beş yıl içinde mahsup edilmeyen bakiye daha ileriye devredilemez.",
        "Zarar mahsubunun ileriye taşıma süresi birbirini izleyen beş yıldır.",
        "193 sayılı GVK m. 88",
        "medium",
    ),
    r(
        "Mükellef, gelir vergisi ile vergi cezasını yıllık gelirinden indirmek istemiştir. Sonuç hangisidir?",
        "Gelir vergisi ve vergi cezaları matrahın tespitinde nasıl değerlendirilir?",
        "İndirilemez",
        "Gelirden ve matrahtan indirilemez",
        ["Tamamı gider yazılır", "Yalnız ceza indirilebilir", "Yalnız gelir vergisi indirilebilir", "Ücret olarak dikkate alınır"],
        ["Ticari hasılattan her durumda düşülür", "Sermaye iradına eklenir", "Zirai ürün bedeli sayılır", "Yalnız muhtasar beyanda giderleşir"],
        "Gelir vergisi, şahsi vergiler, vergi cezaları ve para cezaları gelir unsurlarından ve matrahtan indirilemez.",
        "GVK m. 90 bu vergi, ceza ve fer'ilerin indirimini yasaklar.",
        "193 sayılı GVK m. 90",
        "easy",
    ),
    r(
        "Bilanço esasına tabi işletmenin dönem sonu öz sermayesi dönem başına göre artmıştır. Ticari kazanç tespitinin hareket noktası hangisidir?",
        "Bilanço esasında ticari kazanç hangi iki öz sermaye değeri arasındaki olumlu farka dayanır?",
        "Dönemsel öz sermaye farkı",
        "Hesap dönemi sonu ve başı öz sermayesi",
        ["Yalnız kasadaki nakit artışı", "Satış faturalarının brüt toplamı", "İşletme sahibinin kişisel serveti", "Banka kredilerinin toplamı"],
        ["Aylık ücret ile yıllık ücret", "Kira geliri ile faiz geliri", "Tahsilat ile vergi cezası", "Stok miktarı ile çalışan sayısı"],
        "Bilanço esasındaki ticari kazanç, dönem sonu ile dönem başı öz sermayesi arasındaki olumlu farktan hareketle bulunur.",
        "Öz sermayenin hesap dönemi sonu ve başındaki değerleri arasındaki olumlu fark bilanço esasının temelidir.",
        "193 sayılı GVK m. 38",
        "medium",
    ),
    r(
        "Bilanço esasındaki öz sermaye farkına işletme sahibinin dönem içi eklediği ve çektiği değerler için düzeltme yapılacaktır. Doğru işlem hangisidir?",
        "Bilanço esasındaki kazanç hesabında işletmeye eklenen ve işletmeden çekilen değerler nasıl düzeltilir?",
        "Eklenen indirilir, çekilen eklenir",
        "İlave indirilir, çekiş eklenir",
        ["Her ikisi de kazanca eklenir", "Her ikisi de kazançtan indirilir", "Eklenen eklenir, çekilen indirilir", "Hiçbiri dikkate alınmaz"],
        ["Her ikisi hasılat sayılır", "Her ikisi gider yazılır", "İlave değer eklenir, çekilen indirilir", "Yalnız çekilen değer yok sayılır"],
        "Sahibin işletmeye koyduğu değer öz sermaye artışından indirilir; işletmeden çektiği değer kazanç farkına eklenir.",
        "Dönem içi sermaye hareketleri gerçek faaliyet sonucunu bulmak için ters yönlü düzeltilir.",
        "193 sayılı GVK m. 38",
        "hard",
    ),
    r(
        "İşletme hesabına tabi tacir, hesap dönemindeki hasılatı ile giderleri karşılaştırmıştır. Ticari kazanç hangisidir?",
        "İşletme hesabı esasında ticari kazancın temel formülü hangisidir?",
        "Hasılat-gider farkı",
        "Hasılattan giderlerin çıkarılması",
        ["Yalnız tahsil edilen nakit", "Dönem sonu banka bakiyesi", "İşletmenin emlak değeri", "Sahibin kişisel serveti"],
        ["Öz sermayeye yalnız çekişlerin eklenmesi", "Kasa ile banka hesabının toplanması", "Kişisel harcamaların hasılata eklenmesi", "Yalnız stokların piyasa değerinin alınması"],
        "İşletme hesabında kazanç, bir hesap döneminde elde edilen hasılat ile giderler arasındaki olumlu farktır.",
        "Bu esasta tahsil ve tahakkuk eden hasılat ile ödenen ve borçlanılan giderler karşılaştırılır.",
        "193 sayılı GVK m. 39",
        "easy",
    ),
    r(
        "Emtia ticareti yapan işletmenin dönem sonu ve dönem başı stokları kazanç hesabına alınacaktır. Doğru uygulama hangisidir?",
        "İşletme hesabında dönem başı ve dönem sonu emtia değerleri hangi tarafa eklenir?",
        "Son stok hasılata, ilk stok gidere",
        "Dönem sonu hasılata, dönem başı giderlere",
        ["İki stok da hasılata", "İki stok da giderlere", "Son stok gidere, ilk stok hasılata", "Stoklar hiç dikkate alınmaz"],
        ["Her ikisi yalnız bilançoya", "Son stok giderlere, ilk stok hasılata", "Her ikisi kişisel servete", "Stokların ikisi de yok sayılır"],
        "Emtia ticaretinde dönem sonu stok değeri hasılata, dönem başı stok değeri giderlere eklenir.",
        "Stok düzeltmesi dönem içinde satılan emtianın maliyetini doğru döneme bağlar.",
        "193 sayılı GVK m. 39",
        "medium",
    ),
    r(
        "Tacir, kazancın elde edilmesi ve sürdürülmesi için yaptığı genel gideri indirmek istemektedir. Gider faaliyetle ilgili ve belgeli olduğuna göre kural hangisidir?",
        "Ticari kazancın elde edilmesi ve idamesi için yapılan genel giderler nasıl değerlendirilir?",
        "Safi kazancın tespitinde indirilebilir",
        "Hasılattan indirilebilir",
        ["Kişisel çekiş sayılır", "Her durumda kanunen kabul edilmeyen giderdir", "Menkul sermaye iradı sayılır", "Ücret olarak vergilendirilir"],
        ["İşletme sahibinin kişisel geliri sayılır", "Zirai hasılata eklenir", "Vergi cezasına dönüştürülür", "Yalnız servet bildiriminde gösterilir"],
        "Ticari kazancın elde edilmesi ve idamesi için yapılan genel giderler safi kazancın tespitinde indirilebilir.",
        "Faaliyetle illiyet bağı bulunan genel gider GVK m. 40 kapsamında hasılattan indirilebilir.",
        "193 sayılı GVK m. 40/1",
        "easy",
    ),
    r(
        "İşletme sahibi, eşinin kişisel harcamalarını ticari işletmenin gideri olarak kaydetmiştir. Vergisel sonuç hangisidir?",
        "Teşebbüs sahibi ile eş ve çocuklarının işletmeden çektiği değerler ticari kazançta nasıl değerlendirilir?",
        "Ticari kazançtan indirilemez",
        "İndirilemeyen kişisel çekiş sayılır",
        ["Genel gider olarak indirilir", "Amortisman konusu yapılır", "Ücret gideri sayılır", "Zirai kazanca aktarılır"],
        ["Faaliyet gideri olarak düşülür", "Menkul sermaye iradı sayılır", "Kira gideri olarak kabul edilir", "Vergi kredisine dönüştürülür"],
        "Teşebbüs sahibinin ve ailesinin kişisel harcamaları ticari kazancın elde edilmesiyle ilgili gider değildir ve indirilemez.",
        "İşletmeden çekilen para ve aynî değerler ile kişisel harcamalar GVK m. 41 kapsamında indirilemez.",
        "193 sayılı GVK m. 41/1-2",
        "easy",
    ),
    r(
        "İşverenin çalışana sağladığı para ve ayın toplamından kanundaki kesintiler düşülmüştür. Bulunan tutar nedir?",
        "Ücretin gerçek safi değeri hangi işlemle tespit edilir?",
        "Gerçek safi ücret",
        "Menfaatler eksi kanuni indirimler",
        ["Gayrisafi ticari kazanç", "Menkul sermaye iradı", "Zirai işletme hasılatı", "Kurum kazancı"],
        ["Yalnız nakit ücretin alınmasıyla", "İşverenin cirosunun bölünmesiyle", "Çalışanın servetinin ölçülmesiyle", "Kira gelirinin ücrete eklenmesiyle"],
        "Gerçek safi ücret, işverence sağlanan para, ayın ve menfaatlerden kanundaki indirimler çıkarılarak bulunur.",
        "GVK m. 63 ücretin gerçek safi değerini gayrisafi menfaatler ile kanuni indirimler arasındaki fark olarak tanımlar.",
        "193 sayılı GVK m. 63",
        "medium",
    ),
    r(
        "Serbest meslek erbabı hizmet bedelini tahakkuk ettirmiş ancak henüz tahsil etmemiştir. Kazanç tespitinde temel alınan yöntem hangisidir?",
        "Serbest meslek kazancında hasılatın elde edilmesi bakımından temel esas hangisidir?",
        "Tahsil esası",
        "Tahsil edilen hasılat esası",
        ["Tahakkuk esası", "Öz sermaye karşılaştırması", "Stok değerleme esası", "Emsal kira bedeli esası"],
        ["Yalnız fatura düzenleme esası", "Dönem sonu öz sermaye farkı", "Stokların piyasa değeri", "Kişisel servet artışı"],
        "Serbest meslek kazancı, hesap döneminde tahsil edilen menfaatlerden faaliyet giderlerinin çıkarılmasıyla tespit edilir.",
        "Henüz tahsil edilmeyen alacak, GVK m. 67'deki tahsil gerçekleşmedikçe kural olarak hasılat sayılmaz.",
        "193 sayılı GVK m. 67",
        "medium",
    ),
    r(
        "Mali müşavir, resmi harç için müşterisinden aldığı parayı tamamen ilgili kuruma yatırmıştır. Bu para mesleki kazanca eklenir mi?",
        "Müşteriden vergi, harç veya bilirkişilik gideri için alınıp tamamen o işe harcanan para nasıl değerlendirilir?",
        "Hayır; kazanç sayılmaz",
        "Serbest meslek kazancı sayılmaz",
        ["Evet; tamamı hasılattır", "Ücret geliri sayılır", "Menkul sermaye iradıdır", "Ticari mal satışıdır"],
        ["Her durumda mesleki hasılata eklenir", "Kira geliri olarak beyan edilir", "Zirai kazanç sayılır", "Değer artışı kazancına eklenir"],
        "Resmî ödemeler için müşteriden alınıp tamamen amacı doğrultusunda harcanan para serbest meslek kazancı sayılmaz.",
        "Genel gider karşılığı hasılata eklenebilirken, vergi ve harç için alınıp tümü o işe sarf edilen tutar kazanç değildir.",
        "193 sayılı GVK m. 67",
        "hard",
    ),
    r(
        "Kiraya veren, geçmiş yıl kirasını bu yıl tahsil etmiştir. GMSİ'de gayrisafi hasılat hangi dönemde dikkate alınır?",
        "Gayrimenkul sermaye iradında gayrisafi hasılatın elde edilmesinde temel esas hangisidir?",
        "Tahsil edildiği yılda",
        "Nakdî veya aynî tahsil",
        ["Sözleşmenin imzalandığı yılda", "Taşınmazın edinildiği yılda", "Kiracının işe başladığı yılda", "Tapunun düzenlendiği yılda"],
        ["Yalnız sözleşme tarihi", "Öz sermaye artışı", "Fatura tahakkuku", "Taşınmazın emlak değeri"],
        "GMSİ'de geçmiş yıllara ait kira tahsil edildiği yılın hasılatı sayılır; gelecek yıllara ait peşin kira ilgili yıllara dağıtılır.",
        "Gayrimenkul sermaye iradında gayrisafi hasılat, nakden veya aynen tahsil edilen kira bedelleridir.",
        "193 sayılı GVK m. 72",
        "medium",
    ),
    r(
        "Konut kira geliri sahibi, safi iradı belirlerken kanundaki koşullarla gerçek gider veya götürü gider yöntemlerinden birini seçecektir. Doğru ifade hangisidir?",
        "Gayrimenkul sermaye iradında safi iradın tespiti bakımından hangi iki gider yöntemi bulunur?",
        "İki gider yönteminden biri seçilebilir",
        "Gerçek veya götürü gider",
        ["Her iki yöntem aynı anda sınırsız kullanılır", "Hiçbir gider indirilemez", "Yalnız ticari bilanço yöntemi uygulanır", "Sadece ücret kesintisi yapılır"],
        ["Bilanço ve öz sermaye yöntemleri", "Tevkifat ve münferit beyan", "Stok ve amortisman yöntemleri", "Ücret ve serbest meslek yöntemleri"],
        "GVK m. 74, koşulları taşıyan mükellefe gerçek gider yerine götürü gider yöntemini seçme imkânı verir.",
        "Safi GMSİ gerçek gider yöntemiyle veya kanuni şartlar içinde götürü gider yöntemiyle tespit edilebilir.",
        "193 sayılı GVK m. 74",
        "medium",
    ),
    r(
        "Bir ödeme GVK m. 94 kapsamındadır ve alacaklı adına hesaba kaydedilmiştir; henüz nakit çıkışı olmamıştır. Tevkifat zamanı bakımından sonuç hangisidir?",
        "GVK'da tevkifat hangi ödeme biçimlerine uygulanır?",
        "Hesaben ödeme tevkifat doğurur",
        "Nakdî ve hesabî ödemelere",
        ["Nakit çıkmadığı için tevkifat yapılmaz", "Yalnız yıl sonunda tevkifat yapılır", "Alacak tahsil edilince ücret sayılır", "Ödeme kira geliri olmaktan çıkar"],
        ["Yalnız nakit ödemelere", "Yalnız aynî sermaye koymaya", "Sadece banka kredilerine", "Sadece mahkeme kararlarına"],
        "Tevkifat, nakden ödeme yanında alacaklıyı hak sahibi gösteren hesaben ödeme sırasında da yapılır.",
        "Hesaben ödeme, ödeyeni hak sahibine karşı borçlu gösteren kayıt ve işlemleri kapsar.",
        "193 sayılı GVK m. 94 ve 96",
        "hard",
    ),
    r(
        "Yıllık beyannamedeki gelire dâhil bir ödeme üzerinden daha önce gelir vergisi kesilmiştir. Kesilen vergi nasıl değerlendirilir?",
        "Beyan edilen gelire ilişkin kaynakta kesilmiş gelir vergisinin nihai hesapta işlevi hangisidir?",
        "Yıllık vergiden mahsup edilir",
        "Yıllık vergiden mahsup edilir",
        ["Gider olarak hasılattan düşülür", "Gelire yeniden eklenir", "Vergi cezasına dönüştürülür", "Sermaye kaybı sayılır"],
        ["Beyan edilen gelire ikinci kez eklenir", "Kişisel gider sayılır", "Zirai hasılat olarak yazılır", "Hiçbir biçimde dikkate alınmaz"],
        "Beyannameye dâhil kazanç ve iratlar üzerinden kesilmiş gelir vergisi, yıllık beyanname üzerinden hesaplanan vergiden mahsup edilir.",
        "Kaynakta kesilen vergi, beyana giren aynı gelir için yıllık vergi hesabında kredi işlevi görür.",
        "193 sayılı GVK m. 121",
        "medium",
    ),
]


PREMISES = [
    {"stem":"Gelir vergisi beyannameleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yıllık beyanname yıl gelirlerini toplar\n\nII. Muhtasar beyanname kesilen vergileri bildirir\n\nIII. Münferit beyanname belirli dar mükellef gelirleri içindir","correct":"I, II ve III","why":"Üç ifade de GVK m. 84'teki beyanname türlerinin işlevlerine uygundur.","ref":"193 sayılı GVK m. 84","difficulty":"easy"},
    {"stem":"Gelirin toplanması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Beyanı gereken gelirler yıllık beyannamede toplanır\n\nII. Kanundaki toplama dışı gelirler beyana eklenmez\n\nIII. Her gelir için zorunlu olarak ayrı yıllık beyanname verilir","correct":"I ve II","why":"Beyanı gereken gelirler tek yıllık beyanda toplanır; m. 86 gelirlerinden bazıları toplama dışıdır.","ref":"193 sayılı GVK m. 85-86","difficulty":"medium"},
    {"stem":"Ticari kazanç tespiti bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bilanço esası öz sermaye farkından hareket eder\n\nII. Kişisel harcamalar ticari gider olarak indirilebilir\n\nIII. İşletme hesabı hasılat-gider farkına dayanır","correct":"I ve III","why":"Bilanço öz sermaye, işletme hesabı hasılat-gider esaslıdır; kişisel harcama indirilemez.","ref":"193 sayılı GVK m. 38, 39 ve 41","difficulty":"medium"},
    {"stem":"Kazanç tespitinde tahsil esası bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Bilanço esasındaki ticari kazanç yalnız tahsilata dayanır\n\nII. Serbest meslek kazancında tahsil edilen hasılat esastır\n\nIII. Gayrimenkul sermaye iradında kira tahsilatı önem taşır","correct":"II ve III","why":"Serbest meslek ve GMSİ'de tahsil esası belirgindir; bilanço ticari kazancı öz sermaye ve tahakkuk sistemine dayanır.","ref":"193 sayılı GVK m. 38, 67 ve 72","difficulty":"hard"},
    {"stem":"Zarar mahsubu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Belirli kaynak zararları aynı yıl diğer kazançlardan indirilebilir\n\nII. Kalan zarar birbirini izleyen beş yıl taşınabilir\n\nIII. Her sermaye değer kaybı gelir zararı sayılır","correct":"I ve II","why":"GVK m. 88 kaynak zararlarının mahsubunu ve beş yıllık taşıma süresini düzenler; sermaye eksilmesi her zaman zarar değildir.","ref":"193 sayılı GVK m. 88","difficulty":"medium"},
    {"stem":"Beyan ve vergi kesintisi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tevkifat nakden ödemede uygulanabilir\n\nII. Tevkifat hesaben ödemede uygulanabilir\n\nIII. Beyana giren gelirden kesilen vergi yıllık vergiden mahsup edilebilir","correct":"I, II ve III","why":"GVK tevkifatı nakden ve hesaben ödemede öngörür; beyana giren gelir kesintisi yıllık vergiden mahsup edilir.","ref":"193 sayılı GVK m. 94, 96 ve 121","difficulty":"medium"},
    {"stem":"Giderlerin kazanç tespitine etkisi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Faaliyetin elde edilmesi için yapılan genel gider indirilebilir\n\nII. İşletme sahibinin kişisel harcaması indirilebilir\n\nIII. Gelir vergisi ve vergi cezası matrahtan indirilemez","correct":"I ve III","why":"Faaliyet gideri indirilebilir; kişisel harcamalar ile gelir vergisi ve cezalar indirilemez.","ref":"193 sayılı GVK m. 40, 41 ve 90","difficulty":"medium"},
    {"stem":"Zirai kazancın beyan ve tespiti bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gerçek usul dışındaki her çiftçi bilanço tutar\n\nII. Gerçek usul dışındaki zirai kazançta tevkifat esası uygulanır\n\nIII. Zirai işletme hesabında hasılat ve giderler karşılaştırılır","correct":"II ve III","why":"Gerçek usul dışındaki çiftçi kural olarak tevkifatla vergilenir; gerçek usulde zirai işletme hesabı hasılat-gider farkına dayanır.","ref":"193 sayılı GVK m. 53 ve 55","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="gelir_vergisi",
        topic_id="beyan_ve_tespit",
        label="Beyan ve Kazanç Tespiti",
        slug="beyan_ve_tespit",
        prefix="topic-gv-bt",
        seed=170728,
        legislation_version="193 sayılı Gelir Vergisi Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
