#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Vergi Uyuşmazlıkları, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Vergilendirme hesabındaki yanlışlık nedeniyle mükelleften haksız yere fazla vergi istenmiştir. VUK'a göre bu durum nedir?",
        "Vergi hatasının doğurduğu sonuç aşağıdakilerden hangisidir?",
        "Vergi hatası",
        "Haksız yere fazla veya eksik vergi istenmesi ya da alınması",
        ["Vergi incelemesi", "Uzlaşma tutanağı", "Mücbir sebep", "Yoklama işlemi"],
        ["Verginin doğru matrah üzerinden tahakkuk ettirilmesi", "Vergi beyan süresinin idarece uzatılması", "İş yerinin başka bir vergi dairesine nakledilmesi", "Yasal defterlerin yeniden tasdik ettirilmesi"],
        "Vergiyle ilgili hesap veya vergilendirme yanlışı yüzünden haksız fazla ya da eksik vergi istenmesi veya alınması vergi hatasıdır.",
        "Vergi hatası, hesabın veya vergilendirmenin yanlışlığı nedeniyle haksız vergi sonucunu doğurur.",
        "213 sayılı VUK m. 116",
        "easy",
    ),
    r(
        "Beyannamedeki matraha ait indirim rakamı eksik gösterildiği için vergi fazla hesaplanmıştır. Hata türü hangisidir?",
        "Matraha ait rakamların beyannamede eksik veya fazla gösterilmesi hangi hesap hatasıdır?",
        "Matrah hatası",
        "Matrah hatası",
        ["Verginin mükerrer olması", "Mükellefin şahsında hata", "Mevzuda hata", "Dönem hatası"],
        ["Vergi miktarında hata", "Mükellefiyette hata", "Mevzuda hata", "Dönem hatası"],
        "Matrah rakamının veya indirimin eksik ya da fazla gösterilmesi matrah hatasıdır.",
        "Beyanname, tahakkuk fişi veya ihbarnamedeki matrah ve indirim rakamlarının yanlışlığı matrah hatası sayılır.",
        "213 sayılı VUK m. 117/1",
        "easy",
    ),
    r(
        "Doğru matraha yanlış vergi oranı uygulanmıştır. VUK'a göre hangi hesap hatası oluşur?",
        "Mahsubun yapılmaması veya yanlış yapılması hangi hata grubundadır?",
        "Vergi miktarında hata",
        "Vergi miktarında hata",
        ["Matrah hatası", "Mükellefin şahsında hata", "Mevzuda hata", "Dönem hatası"],
        ["Matrah hatası", "Mükellefiyette hata", "Mevzuda hata", "Verginin mükerrer olması"],
        "Vergi oranı veya tarifenin yanlış uygulanması, vergi miktarında hata oluşturur.",
        "Mahsupların yapılmaması ya da yanlış yapılması vergi miktarında hata kapsamındadır.",
        "213 sayılı VUK m. 117/2",
        "easy",
    ),
    r(
        "Aynı vergi kanunu uygulanarak aynı dönem ve aynı matrah üzerinden ikinci kez vergi istenmiştir. Hata türü hangisidir?",
        "Verginin mükerrer olması için aşağıdakilerden hangisi aranır?",
        "Mükerrer vergi",
        "Aynı dönem ve matrahın yeniden vergilenmesi",
        ["Matrah hatası", "Mevzuda hata", "Mükellefiyette hata", "Dönem hatası"],
        ["Farklı vergilerin farklı dönemlerde alınması", "Aynı beyannamenin elektronik verilmesi", "Verginin süresinde bir kez ödenmesi", "Bir verginin iki taksitte ödenmesi"],
        "Aynı vergi, dönem ve matrah üzerinden birden fazla kez istenir veya alınırsa verginin mükerrerliği doğar.",
        "Mükerrerlik aynı vergi kanunu, aynı vergilendirme dönemi ve aynı matrah bağlantısını gerektirir.",
        "213 sayılı VUK m. 117/3",
        "medium",
    ),
    r(
        "Vergi asıl borçlu yerine aynı adlı başka bir kişiden istenmiştir. Vergilendirme hatası hangisidir?",
        "Mükellefin şahsında hatanın ayırt edici unsuru nedir?",
        "Şahısta hata",
        "Verginin yanlış kişiden istenmesi",
        ["Mükellefiyette hata", "Mevzuda hata", "Dönem hatası", "Matrah hatası"],
        ["Vergi dışı konudan vergi istenmesi", "Yanlış dönemin vergilendirilmesi", "Vergi hesabında toplama hatası", "Aynı matrahtan iki kez vergi alınması"],
        "Verginin gerçek borçlu yerine başka kişiye yöneltilmesi mükellefin şahsında hatadır.",
        "Şahısta hata, vergisel borcun yanlış kişiden aranmasıdır.",
        "213 sayılı VUK m. 118/1",
        "easy",
    ),
    r(
        "Açıkça vergiden muaf bir kişiden vergi istenmiştir. Hangi vergilendirme hatası oluşur?",
        "Açıkça vergiye tabi olmayan kişiden vergi alınması hangi hata türüdür?",
        "Mükellefiyette hata",
        "Mükellefiyette hata",
        ["Mükellefin şahsında hata", "Mevzuda hata", "Dönem hatası", "Verginin mükerrer olması"],
        ["Matrah hatası", "Vergi miktarında hata", "Dönem hatası", "Mükerrer vergi"],
        "Vergiye tabi olmayan veya muaf kişiden açıkça vergi istenmesi mükellefiyette hatadır.",
        "Kişinin mükellef olmaması ya da muaf bulunması hâlinde ondan vergi alınması mükellefiyet hatasıdır.",
        "213 sayılı VUK m. 118/2",
        "easy",
    ),
    r(
        "Kanunda açıkça istisna edilen bir işlem üzerinden vergi alınmıştır. Hata türü hangisidir?",
        "Verginin konusuna girmeyen gelir veya işlemden vergi istenmesi hangi hatadır?",
        "Mevzuda hata",
        "Mevzuda hata",
        ["Mükellefin şahsında hata", "Mükellefiyette hata", "Dönem hatası", "Matrah hatası"],
        ["Vergi miktarında hata", "Mükerrer vergi", "Matrah hatası", "Mükellefin şahsında hata"],
        "Vergi konusuna girmeyen veya istisna edilmiş işlem üzerinden vergi alınması mevzuda hatadır.",
        "Mevzuda hata, vergilendirilen gelir, servet, kıymet veya işlemin açıkça verginin konusuna girmemesidir.",
        "213 sayılı VUK m. 118/3",
        "easy",
    ),
    r(
        "2025 dönemi vergisi ihbarnamede 2026 dönemine ait gösterilmiştir. Vergilendirme hatası hangisidir?",
        "Verginin ait olduğu sürenin eksik veya fazla hesaplanması hangi hata türüdür?",
        "Dönem hatası",
        "Vergilendirme dönemi hatası",
        ["Mükellefin şahsında hata", "Mükellefiyette hata", "Mevzuda hata", "Matrah hatası"],
        ["Vergi mükellefinin şahsında hata", "Verginin mükerrer alınması", "Hesaplanan vergi miktarında hata", "Vergi matrahında hata"],
        "Aranan verginin ilgili olduğu dönemin yanlış gösterilmesi vergilendirme dönemi hatasıdır.",
        "Vergilendirme veya muafiyet süresinin yanlış belirlenmesi dönem hatası kapsamındadır.",
        "213 sayılı VUK m. 118/4",
        "medium",
    ),
    r(
        "Vergi hatası belirlenmiştir. Düzeltmeye kural olarak kim karar verir?",
        "Vergi hatasının teknik olarak düzeltilmesinde hangi belge esas alınır?",
        "Vergi dairesi müdürü",
        "Düzeltme fişi",
        ["Vergi mahkemesi kalemi", "Ticaret sicili müdürü", "Belediye encümeni", "Noter"],
        ["Tahakkuk fişi", "Yoklama fişi", "Ödeme emri", "Uzlaşma tutanağı"],
        "VUK'a göre vergi hatalarının düzeltilmesine ilgili vergi dairesi müdürü karar verir.",
        "Düzeltme işlemi düzeltme fişine dayanır; fazla vergi bu fişle terkin veya iade edilir.",
        "213 sayılı VUK m. 120",
        "easy",
    ),
    r(
        "Mükellefe iade hakkını gösteren düzeltme fişi tebliğ edilmiştir. Mükellef parayı almak için kaç yıl içinde başvurmalıdır?",
        "Düzeltme fişiyle mükellefe tebliğ edilmesi gereken bilgilerden biri hangisidir?",
        "Bir yıl",
        "Başvuru yeri ve süresi",
        ["On beş gün", "Otuz gün", "Beş yıl", "Süresiz"],
        ["Vergi memurunun kişisel adresi", "Mükellefin siyasi tercihi", "İşletmenin reklam bütçesi", "Mahkemenin duruşma salonu"],
        "Düzeltme fişi tebliğinden itibaren bir yıl içinde iade için başvurulmazsa geri alma hakkı düşer.",
        "Tebliğde iade tutarıyla başvurulacak muhasebe birimi ve başvuru süresi gösterilir.",
        "213 sayılı VUK m. 120",
        "medium",
    ),
    r(
        "İdare tereddüt bulunmayan açık ve kesin vergi hatasını kendiliğinden fark etmiştir. Mükellef talebi olmadan düzeltebilir mi?",
        "Mükellef aleyhine re'sen yapılan düzeltmeye karşı hangi hak korunur?",
        "Evet; re'sen düzeltme yapılabilir",
        "Vergi mahkemesinde dava açma hakkı",
        ["Hayır; mutlaka dava açılmalıdır", "Hayır; yalnız uzlaşmayla düzeltilir", "Evet; fakat hata hiç açıklanmaz", "Hayır; yalnız noter karar verebilir"],
        ["Hiçbir başvuru hakkı yoktur", "Yalnız ticaret siciline itiraz hakkı", "Sadece sözlü şikâyet hakkı", "Yalnız belediyeye başvuru hakkı"],
        "Tereddüt edilmeyen açık ve mutlak vergi hataları idarece re'sen düzeltilebilir.",
        "Kişinin aleyhine yapılan re'sen düzeltmeye karşı vergi mahkemesinde dava açma hakkı saklıdır.",
        "213 sayılı VUK m. 121",
        "medium",
    ),
    r(
        "Mükellef vergi işlemindeki hatanın düzeltilmesini istemektedir. Talep hangi usulle yapılır?",
        "Düzeltme talebinin taahhütlü postayla gönderilmesi mümkün müdür?",
        "Vergi dairesine yazılı başvuru",
        "Evet; taahhütlü postayla gönderilebilir",
        ["Yalnız sözlü telefonla istenir", "Doğrudan ticaret siciline verilir", "Sadece mahkemede ileri sürülür", "Noter kararıyla kendiliğinden yapılır"],
        ["Hayır; yalnız elden verilebilir", "Hayır; yalnız elektronik tebligatla yapılır", "Evet; fakat belediyeye gönderilir", "Hayır; posta hiçbir vergi işleminde kullanılamaz"],
        "Mükellef düzeltmeyi vergi dairesinden yazılı istemelidir; taahhütlü posta da kullanılabilir.",
        "VUK düzeltme başvurusunun taahhütlü postayla gönderilmesine açıkça izin verir.",
        "213 sayılı VUK m. 122",
        "easy",
    ),
    r(
        "Düzeltme mercii talebi yerinde görmemiştir. Sonuç mükellefe nasıl bildirilir?",
        "Düzeltme talebini inceleyen vergi dairesi servisi talebi nereye gönderir?",
        "Yazılı ret bildirimi",
        "Düzeltme merciine",
        ["Hiç bildirim yapılmaz", "Yalnız telefonla söylenir", "Ticaret sicilinde ilan edilir", "Müşteriye sözlü açıklanır"],
        ["Doğrudan ceza mahkemesine", "Belediye encümenine", "Noterler birliğine", "Ticaret odasına"],
        "Talep yerinde görülmezse ret sonucu düzeltmeyi isteyen kişiye yazılı tebliğ edilir.",
        "İlgili servis kendi görüşünü ekleyerek başvuruyu düzeltme merciine iletir.",
        "213 sayılı VUK m. 123",
        "easy",
    ),
    r(
        "Dava açma süresi geçtikten sonra yapılan düzeltme talebi reddedilmiştir. Genel bütçe vergisi için hangi idari yol kullanılabilir?",
        "Şikâyet yoluna başvurunun temel ön koşulu hangisidir?",
        "Bakanlığa şikâyet başvurusu",
        "Dava sonrası düzeltme talebinin reddi",
        ["Doğrudan ceza mahkemesine itiraz", "Ticaret siciline tescil", "Belediye encümenine uzlaşma", "Notere düzeltme talebi"],
        ["Verginin henüz tarh edilmemiş olması", "Dava süresinin hiç başlamamış olması", "Vergi dairesinin düzeltme talebini bütünüyle kabul etmesi", "Mükellefin vergiyi hiç öğrenmemesi"],
        "Dava süresi geçtikten sonra reddedilen düzeltme talebi için şikâyet yolu Hazine ve Maliye Bakanlığına başvurudur.",
        "Şikâyet, dava açma süresi geçtikten sonra yapılan ve reddedilen düzeltme isteminin devamı niteliğindedir.",
        "213 sayılı VUK m. 124",
        "medium",
    ),
    r(
        "Belediye vergisine ilişkin düzeltme talebi dava süresi geçtikten sonra reddedilmiştir. Şikâyet mercii hangisidir?",
        "İl özel idaresi vergisine ilişkin şikâyet başvurusu hangi makama yapılır?",
        "Belediye başkanlığı",
        "Valilik",
        ["Hazine ve Maliye Bakanlığı", "Vergi mahkemesi kalemi", "Ticaret sicili müdürlüğü", "Noter"],
        ["Belediye başkanlığı", "Hazine ve Maliye Bakanlığı", "Ticaret odası", "Defterdarlık muhasebe birimi"],
        "Belediye vergilerinde şikâyet başvurusu belediye başkanlığına yapılır.",
        "İl özel idare vergileri bakımından şikâyet mercii valiliktir.",
        "213 sayılı VUK m. 124",
        "easy",
    ),
    r(
        "Vergi işlemi yargı kararından geçmiş ve karar kesinleşmiştir; ancak belirlenen vergi hatası hakkında mahkeme ayrıca karar vermemiştir. Düzeltme mümkün müdür?",
        "Yargıdan geçmiş işlemde düzeltmenin yapılamayacağı durum hangisidir?",
        "Evet; hata karara bağlanmamışsa",
        "Aynı hatanın yargıda karara bağlanması",
        ["Hayır; kesinleşen işlem asla düzeltilemez", "Evet; mahkeme kararını idare kaldırır", "Hayır; yalnız ceza hataları düzeltilir", "Evet; zamanaşımı hiçbir zaman aranmaz"],
        ["Kararın kesinleşmiş olması", "Verginin tahsil edilmiş olması", "Mükellefin vergi dairesine yazılı düzeltme başvurusu yapması", "Hatanın hesap hatası olması"],
        "Yargıdan geçmiş işlemde de, ilgili hata hakkında yargı mercii karar vermemişse VUK usulüyle düzeltme yapılabilir.",
        "Mahkeme aynı vergi hatasını karara bağlamışsa idari düzeltme yoluyla bu karar etkisiz kılınamaz.",
        "213 sayılı VUK m. 125",
        "hard",
    ),
    r(
        "Tarh zamanaşımı dolduktan sonra vergi hatası bulunmuştur ve VUK m. 126'daki özel uzatma hâllerinden hiçbiri yoktur. Düzeltme yapılabilir mi?",
        "Zamanaşımının son yılında tarh ve tebliğ edilen vergide düzeltme süresi, hatanın yapıldığı tarihten itibaren en az ne kadardır?",
        "Hayır; süre dolmuştur",
        "Bir yıl",
        ["Evet; düzeltme süresizdir", "Evet; yalnız mükellef aleyhine yapılır", "Hayır; hata vergi ziyaına dönüşür", "Evet; yalnız sözlü taleple yapılır"],
        ["On beş gün", "Otuz gün", "İki yıl", "Beş yıl"],
        "Özel uzatma hâlleri dışında tarh zamanaşımı dolduktan sonra bulunan hata düzeltilemez.",
        "Son yılda tarh ve tebliğ edilen vergide düzeltme süresi hatanın yapıldığı tarihten başlayarak bir yıldan az olamaz.",
        "213 sayılı VUK m. 126",
        "hard",
    ),
    r(
        "Mükellef ikmalen tarh edilen vergi ile cezanın yarısını ödeyeceğini bildirerek cezada indirim istemektedir. Vergi dairesine başvuru süresi nedir?",
        "VUK m. 376 şartları sağlandığında vergi ziyaı, usulsüzlük ve özel usulsüzlük cezasının ne kadarı indirilir?",
        "Otuz gün",
        "Yarısı",
        ["On beş gün", "Kırk beş gün", "Üç ay", "Bir yıl"],
        ["Dörtte biri", "Üçte biri", "Tamamı", "Hiçbiri"],
        "Cezada indirim için ihbarnamenin tebliğinden itibaren otuz gün içinde başvurulup ödeme iradesi bildirilmelidir.",
        "Şartlar yerine getirildiğinde kapsamdaki cezanın yarısı indirilir.",
        "213 sayılı VUK m. 376",
        "medium",
    ),
    r(
        "Mükellef cezada indirim talep etmiş, ancak vergiyi ve kalan cezayı dava konusu yapmıştır. İndirimden yararlanabilir mi?",
        "Cezada indirim kapsamında ödeneceği bildirilen vergi ve cezanın süresinde ödenmemesi hangi sonucu doğurur?",
        "Hayır; indirim uygulanmaz",
        "İndirim hakkı kaybedilir",
        ["Evet; dava indirimi etkilemez", "Evet; ceza tamamen kalkar", "Hayır; vergi aslı da silinir", "Evet; yalnız faiz ödenir"],
        ["İndirim kesinleşir", "Ceza tamamen silinir", "Uzlaşma sağlanmış sayılır", "Dava kendiliğinden kabul edilir"],
        "M. 376'da ödeneceği bildirilen vergi veya cezanın dava konusu yapılması indirimden yararlanmayı engeller.",
        "Süresinde ödeme yapılmaması m. 376 indirim hakkını ortadan kaldırır.",
        "213 sayılı VUK m. 376",
        "medium",
    ),
    r(
        "2024 değişiklikleri sonrası mükellef, ikmalen tarh edilen verginin kendisini uzlaşmaya götürmek istemektedir. VUK Ek m. 1 bakımından mümkün müdür?",
        "Güncel VUK'a göre uzlaşmanın temel konusu hangisidir?",
        "Hayır; yalnız kapsamdaki cezalar uzlaşılır",
        "Kapsamdaki vergi cezaları",
        ["Evet; vergi aslı her durumda uzlaşılır", "Evet; yalnız verginin tamamı silinir", "Hayır; uzlaşma kurumu kaldırılmıştır", "Evet; yalnız beyana dayalı vergi uzlaşılır"],
        ["Her türlü verginin aslı", "Gecikme faizinin tamamı", "Mükellefin özel hukuk borçları", "Ceza mahkemesinin hapis kararı"],
        "7524 sayılı Kanun değişikliği sonrasında uzlaşma, vergi aslı yerine kanundaki kapsama giren cezalara yönelmiştir.",
        "Uzlaşma, ikmalen, re'sen veya idarece tarh edilen vergilere ilişkin vergi ziyaı cezaları ile şartları taşıyan usulsüzlük cezalarını kapsar.",
        "213 sayılı VUK Ek m. 1; 7524 sayılı Kanun m. 14",
        "hard",
    ),
    r(
        "Uzlaşma kapsamındaki ceza için ihbarname 5 Mayıs'ta tebliğ edilmiştir. Talep hangi sürede yapılmalıdır?",
        "Uzlaşma talebinin başlangıç tarihi hangi olaydır?",
        "Otuz gün",
        "Ceza ihbarnamesinin tebliği",
        ["On beş gün", "Kırk beş gün", "Üç ay", "Bir yıl"],
        ["Verginin tahsil edildiği gün", "Defterin tasdik tarihi", "İşletmenin kuruluş tarihi", "Mükellefin sözlü başvurusu"],
        "Uzlaşma talebi ceza ihbarnamesinin tebliğinden başlayarak otuz gün içinde yapılır.",
        "Uzlaşma başvuru süresi ilgili ihbarnamenin tebliğiyle işlemeye başlar.",
        "213 sayılı VUK Ek m. 1",
        "easy",
    ),
    r(
        "Mükellef ceza üzerinde uzlaşmış ve tutanak imzalanmıştır. Aynı ceza hakkında dava açabilir mi?",
        "Uzlaşma tutanağının hukuki niteliği hangisidir?",
        "Hayır; dava ve şikâyet yolu kapanır",
        "Kesindir ve hemen uygulanır",
        ["Evet; her zaman yeniden dava açabilir", "Evet; yalnız ceza mahkemesinde dava açar", "Hayır; ancak tutanak hiç uygulanmaz", "Evet; aynı konuda ikinci uzlaşma ister"],
        ["Yalnız tavsiye niteliğindedir", "Mükellef isterse tek taraflı değiştirir", "Mahkeme onayı olmadan yok hükmündedir", "Vergi dairesini hiçbir şekilde bağlamaz"],
        "Uzlaşma tutanağı kesindir; üzerinde uzlaşılan hususta dava açılamaz ve şikâyet yoluna gidilemez.",
        "Uzlaşma tutanağının gereği vergi dairesince gecikmeden yerine getirilir.",
        "213 sayılı VUK Ek m. 6",
        "medium",
    ),
    r(
        "Süresinde uzlaşma istenmiş ancak uzlaşma sağlanamamış; tutanak tebliğ edildiğinde genel dava süresinden sekiz gün kalmıştır. Dava için kullanılacak süre nedir?",
        "Uzlaşma sağlanamazsa ceza muhatabı hangi yola başvurabilir?",
        "On beş gün",
        "Yetkili vergi mahkemesinde dava",
        ["Kalan sekiz gün", "Otuz gün", "Üç ay", "Dava yolu tamamen kapanır"],
        ["Yalnız ceza mahkemesine başvuru", "Ticaret siciline itiraz", "Noter huzurunda ikinci uzlaşma", "Belediye encümeninde tahkim"],
        "Uzlaşma sağlanmadığında kalan dava süresi on beş günden azsa, tutanağın tebliğinden itibaren süre on beş güne tamamlanır.",
        "Uzlaşma gerçekleşmezse genel hükümler içinde yetkili vergi mahkemesinde dava açılabilir.",
        "213 sayılı VUK Ek m. 7",
        "hard",
    ),
    r(
        "Mükellef kendisine tarh edilen vergiye karşı dava açmak istemektedir. VUK'a göre dava açma yetkisi var mıdır?",
        "Kendisine vergi cezası kesilen kişi hangi yargı merciinde dava açabilir?",
        "Evet; vergi mahkemesinde dava açabilir",
        "Vergi mahkemesinde",
        ["Hayır; yalnız vergi dairesi dava açabilir", "Evet; yalnız ceza mahkemesinde", "Hayır; hiçbir yargı yolu yoktur", "Evet; yalnız ticaret mahkemesinde"],
        ["Asliye hukuk mahkemesinde", "Ceza mahkemesinde", "Ticaret mahkemesinde", "Sulh hukuk mahkemesinde"],
        "Mükellefler tarh edilen vergiye, ceza muhatapları da kesilen cezaya karşı vergi mahkemesinde dava açabilir.",
        "Vergi cezalarına karşı görevli ilk derece yargı mercii vergi mahkemesidir.",
        "213 sayılı VUK m. 377",
        "easy",
    ),
    r(
        "Mükellef, ihtirazi kayıt koymadan kendi beyan ettiği matrah üzerinden tarh edilen vergiye dava açmıştır. VUK'taki genel kural nedir?",
        "Vergi mahkemesinde dava açılabilmesi için tarh edilen vergi bakımından hangi aşama gerekir?",
        "Genel olarak dava açılamaz",
        "Tarhın tebliği",
        ["Her durumda dava açılabilir", "Dava yalnız noter onayıyla açılır", "Vergi kendiliğinden terkin edilir", "Yalnız ceza mahkemesi görevlidir"],
        ["Yalnız inceleme başlamış olması", "Defterin tasdik edilmiş olması", "İşletmenin kapanmış olması", "Uzlaşmanın mutlaka sağlanması"],
        "Mükellef kural olarak kendi beyan ettiği matraha ve bunun vergisine dava açamaz; vergi hatası ve ihtirazi kayıt gibi özel durumlar ayrıdır.",
        "Tarh edilen verginin dava konusu olabilmesi için işlemin tebliğ edilmesi gerekir.",
        "213 sayılı VUK m. 378",
        "medium",
    ),
    r(
        "Özel kanunda başka süre yoktur ve vergi ihbarnamesi mükellefe tebliğ edilmiştir. Vergi mahkemesinde genel dava açma süresi nedir?",
        "Vergi uyuşmazlığında dava açma süresi hangi günü izleyen günden başlar?",
        "Otuz gün",
        "Tebliğ günü",
        ["Yedi gün", "On beş gün", "Altmış gün", "Bir yıl"],
        ["Beyannamenin hazırlandığı gün", "Defterin tasdik edildiği gün", "İşletmenin kurulduğu gün", "Vergi memurunun göreve başladığı gün"],
        "İYUK'ta vergi mahkemeleri için özel kanunda aksine süre yoksa genel dava açma süresi otuz gündür.",
        "Tahakkuku tahsile bağlı olmayan vergilerde süre, işlemin tebliğini izleyen günden işlemeye başlar.",
        "2577 sayılı İYUK m. 7",
        "easy",
    ),
]


PREMISES = [
    {"stem":"Hesap hataları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Matrah rakamının yanlışlığı matrah hatasıdır\n\nII. Oranın yanlış uygulanması vergi miktarında hatadır\n\nIII. Aynı dönem ve matrahtan iki kez vergi alınması mükerrerliktir","correct":"I, II ve III","why":"Üç ifade de VUK m. 117'deki matrah, vergi miktarı ve mükerrerlik hata türlerine uygundur.","ref":"213 sayılı VUK m. 117","difficulty":"easy"},
    {"stem":"Vergilendirme hataları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Verginin başka kişiden istenmesi şahısta hatadır\n\nII. Muaf kişiden vergi istenmesi mevzuda hatadır\n\nIII. Yanlış dönemin vergilendirilmesi dönem hatasıdır","correct":"I ve III","why":"Verginin yanlış kişiden istenmesi şahısta, yanlış dönemde istenmesi dönemde hatadır; muaf kişiden vergi istenmesi mükellefiyette hatadır.","ref":"213 sayılı VUK m. 118","difficulty":"medium"},
    {"stem":"Düzeltme usulü bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Kararı ilgili vergi dairesi müdürü verir\n\nII. İşlem düzeltme fişine dayanır\n\nIII. Açık hata mükellef başvurusu olmadan düzeltilemez","correct":"I ve II","why":"Düzeltme müdür kararı ve düzeltme fişiyle yapılır; açık ve mutlak hata re'sen düzeltilebilir.","ref":"213 sayılı VUK m. 120-121","difficulty":"medium"},
    {"stem":"Şikâyet yolu bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Dava süresi dolmadan kabul edilen düzeltme talebini izler\n\nII. Genel bütçe vergisinde Bakanlığa başvurulur\n\nIII. Belediye vergisinde belediye başkanlığına başvurulur","correct":"II ve III","why":"Şikâyet yolu, dava süresi geçtikten sonra reddedilen düzeltme talebini izler; genel bütçe vergisinde Bakanlığa, belediye vergisinde belediye başkanlığına başvurulur.","ref":"213 sayılı VUK m. 124","difficulty":"medium"},
    {"stem":"Cezada indirim bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Başvuru ihbarnameden itibaren otuz gündür\n\nII. Şartlar sağlanırsa cezanın tamamı silinir\n\nIII. Vergi veya cezanın dava konusu yapılması indirimi engeller","correct":"I ve III","why":"Otuz günlük sürede başvuru gerekir ve dava açılması indirimi engeller; m. 376 cezanın tamamını değil yarısını indirir.","ref":"213 sayılı VUK m. 376","difficulty":"medium"},
    {"stem":"Uzlaşma bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Güncel düzenlemede vergi aslı uzlaşmanın konusu değildir\n\nII. Talep ihbarnamenin tebliğinden itibaren otuz gündür\n\nIII. İmzalanan uzlaşma tutanağı kesindir","correct":"I, II ve III","why":"7524 sonrası vergi aslı kapsamdan çıkarılmıştır; başvuru otuz gündür ve imzalı tutanak kesindir.","ref":"213 sayılı VUK Ek m. 1 ve 6","difficulty":"hard"},
    {"stem":"Vergi davası bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mükellef tarh edilen vergiye dava açabilir\n\nII. Ceza muhatabı kesilen cezaya dava açabilir\n\nIII. Mükellef kendi beyanına her durumda doğrudan dava açabilir","correct":"I ve II","why":"Mükellef ve ceza muhatabının dava hakkı vardır; kendi beyanına karşı dava yasağının hata ve ihtirazi kayıt gibi istisnaları bulunur.","ref":"213 sayılı VUK m. 377-378","difficulty":"medium"},
    {"stem":"Düzeltme zamanaşımı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tarh zamanaşımı sonrası hata her durumda düzeltilebilir\n\nII. Son yılda tarh ve tebliğde özel bir yıllık asgari süre vardır\n\nIII. VUK belirli hâllerde bir yıldan az olmayan özel süre öngörür","correct":"II ve III","why":"Düzeltme kural olarak tarh zamanaşımına bağlıdır; m. 126 bazı hâllerde bir yıldan az olmayan özel süre tanır.","ref":"213 sayılı VUK m. 126","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="vergi_hukuku",
        topic_id="vergi_uyusmazliklari",
        label="Vergi Uyuşmazlıkları",
        slug="vergi_uyusmazliklari",
        prefix="topic-vh-vu",
        seed=20260721,
        legislation_version="213 sayılı VUK ve 2577 sayılı İYUK, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
