#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Muhasebe Denetimi — Denetçi Raporu ve Görüşler, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Denetçi yeterli ve uygun kanıtı, düzeltilmemiş yanlışlıkları ve finansal tabloların sunumunu değerlendirmeden doğrudan olumlu görüş yazmıştır. Yaklaşım uygun mudur?",
        "Finansal tablolara ilişkin görüş oluşturulurken temel dayanak hangisidir?",
        "Hayır; görüş kanıt sonuçlarının değerlendirilmesine dayanır",
        "Yeterli kanıt, yanlışlık ve sunum değerlendirmeleri",
        ["Evet; yönetimin olumlu görüş talebi tek başına yeterlidir", "Evet; yalnız önceki yılın görüşü cari yılı belirler", "Hayır; görüş finansal tablo hazırlanmadan önce verilir", "Evet; denetim ücreti ödendiğinde kanıt değerlendirilmez"],
        ["Yalnız yönetimin finansal tabloları imzalamış olması", "Sadece önceki denetçinin raporundaki görüş türü", "Yalnız işletmenin dönem içinde kâr açıklamış olması", "Denetim sözleşmesindeki ücret ve ödeme takvimi"],
        "Görüş; kanıt yeterliliği, düzeltilmemiş yanlışlıklar ve raporlama çerçevesine uygunluğa ilişkin bütüncül sonuca dayanır.",
        "BDS 700, görüşün denetim kanıtlarından çıkarılan sonuçların değerlendirilmesine dayanmasını ister.",
        "BDS 700 par. 6 ve 10-15", "easy",
    ),
    r(
        "Finansal tablolar tüm önemli yönleriyle geçerli çerçeveye uygun hazırlanmış ve yeterli kanıt elde edilmiştir. Hangi görüş verilir?",
        "Olumlu görüş hangi durumda verilir?",
        "Olumlu görüş",
        "Tablolar tüm önemli yönleriyle geçerli çerçeveye uygunsa",
        ["Sınırlı olumlu görüş", "Olumsuz görüş", "Görüş vermekten kaçınma", "Dikkat çekilen hususlar görüşü"],
        ["Herhangi bir önemli ve yaygın yanlışlık bulunduğunda", "Yeterli ve uygun denetim kanıtı elde edilemediğinde", "Yönetim denetimin kapsamını önemli ölçüde sınırladığında", "Tabloların geçerli çerçeveye aykırı olduğu sonucuna varıldığında"],
        "Önemli yanlışlık yoksa ve tablolar geçerli raporlama çerçevesine uygun hazırlanmışsa olumlu görüş verilir.",
        "Olumlu görüş, finansal tabloların tüm önemli yönleriyle geçerli finansal raporlama çerçevesine uygunluğunu ifade eder.",
        "BDS 700 par. 16", "easy",
    ),
    r(
        "Denetçi raporu yalnız sözlü sunumla paylaşılmış ve raporda bağımsız denetçi olduğunu gösteren bir başlık kullanılmamıştır. Uygun mudur?",
        "BDS'lere uygun denetçi raporunun biçimi ve başlığı nasıldır?",
        "Hayır; yazılı rapor bağımsız denetçi başlığını taşımalıdır",
        "Yazılı ve başlıklı Bağımsız Denetçi Raporu",
        ["Evet; sözlü rapor yazılı raporla tamamen eşdeğerdir", "Evet; başlık yalnız yönetimin talebi varsa kullanılır", "Hayır; rapor yalnız elektronik tablo biçiminde düzenlenir", "Evet; herhangi bir başlık bağımsızlığı aynı ölçüde gösterir"],
        ["Sözlü sunum ve Yönetim Raporu başlığı", "Yazılı rapor ve Mali Müşavir Görüşü başlığı", "Sözlü rapor ve Finans Direktörü Raporu başlığı", "Yalnız e-posta konusu içinde Denetim ibaresi"],
        "Yazılılık ve açık bağımsız denetçi başlığı raporun niteliğini ve bağımsızlık iddiasını kullanıcıya gösterir.",
        "BDS 700 Türkiye uygulamasında rapor yazılı düzenlenir ve Bağımsız Denetçi Raporu başlığı açıkça yer alır.",
        "BDS 700 par. 20T-21", "easy",
    ),
    r(
        "Raporun ilk bölümünde uzun yönetim sorumlulukları açıklanmış, görüş ise raporun sonunda verilmiştir. Bu sıralama uygun mudur?",
        "Denetçi raporunun ilk bölümü hangi başlık altında hangi unsuru içerir?",
        "Hayır; ilk bölüm Görüş başlığı altında denetçi görüşünü içerir",
        "Görüş başlığı altında denetçi görüşü",
        ["Evet; görüşün raporun herhangi bir yerinde bulunması yeterlidir", "Evet; ilk bölüm mutlaka yönetimin sorumluluklarını içerir", "Hayır; ilk bölüm yalnız denetim ücretini açıklamalıdır", "Evet; görüş yalnız dipnotlara eklenerek verilebilir"],
        ["Yönetimin Sorumlulukları altında denetim ücreti", "Diğer Hususlar altında yönetimin beyanı", "Kilit Denetim Konuları altında ayrı bir görüş", "Ek Bilgiler altında finansal tablo hazırlama tarihi"],
        "Görüşün ilk bölümde sunulması, raporun temel sonucunu kullanıcının açık ve hızlı biçimde görmesini sağlar.",
        "Görüş bölümü işletmeyi, denetlenen tabloları, dönemleri ve ilgili dipnotları tanımlar.",
        "BDS 700 par. 23-24", "easy",
    ),
    r(
        "Raporda Görüş bölümünden sonra doğrudan imza yer almış; standartlara uygunluk, bağımsızlık ve kanıt yeterliliği açıklanmamıştır. Eksik bölüm hangisidir?",
        "Görüşün Dayanağı bölümünde hangi üç ana unsur açıklanır?",
        "Görüşün Dayanağı bölümü",
        "BDS uyumu, bağımsızlık ve kanıt yeterliliği",
        ["Yönetimin Yıllık Bütçesi bölümü", "Denetim Ücreti Dağılımı bölümü", "Gelecek Dönem Tahminleri bölümü", "Ortakların Kâr Payı bölümü"],
        ["Yönetimin kâr hedefi, vergi planı ve yatırım bütçesi", "Denetçinin ücreti, çalışma saati ve ekip izinleri", "İşletmenin satışları, reklamı ve pazar payı", "Yalnız önceki denetçinin adı, tarihi ve görüşü"],
        "Görüşün Dayanağı, görüşün mesleki ve kanıtsal temelini kullanıcıya açıklar.",
        "Bu bölüm Görüş bölümünün hemen ardından gelir; standartlara uygunluk, etik bağımsızlık ve kanıt yeterliliği bilgilerini içerir.",
        "BDS 700 par. 28", "medium",
    ),
    r(
        "Yönetim finansal tabloları hazırlama ve iç kontrol sorumluluğunu denetçiye devrettiğini raporda belirtmiştir. Bu ifade doğru mudur?",
        "Finansal tabloların hazırlanması ve ilgili iç kontrolden kim sorumludur?",
        "Hayır; sorumluluk yönetim ve üst yönetimden sorumlu olanlardadır",
        "Yönetim ve üst yönetimden sorumlu olanlar",
        ["Evet; bağımsız denetçi tabloların asli hazırlayıcısıdır", "Evet; denetim sözleşmesi bütün sorumluluğu denetçiye geçirir", "Hayır; sorumluluk yalnız finansal tablo kullanıcılarındadır", "Evet; iç kontrol sadece dış denetim şirketince kurulur"],
        ["Yalnız bağımsız denetçi", "Sadece işletmenin vergi dairesi", "Yalnız finansal tablo kullanıcıları", "Denetim şirketinin kalite gözden geçiren kişisi"],
        "Bağımsız denetim, yönetimin finansal raporlama ve gerekli iç kontrol sorumluluğunu devralmaz.",
        "Yönetim geçerli çerçeveye uygun tabloları ve gerekli iç kontrolü hazırlar; denetçi bunlar hakkında görüş oluşturur.",
        "BDS 700 par. 33-38", "medium",
    ),
    r(
        "Finansal tablolar 20 Mart'ta yönetimce hazırlanmış, yeterli kanıt 25 Mart'ta tamamlanmış; rapor 22 Mart tarihini taşımaktadır. Rapor tarihi uygun mudur?",
        "Denetçi raporu tarihi en erken hangi koşullar tamamlandığında belirlenebilir?",
        "Hayır; rapor tarihi kanıt tamamlanmadan önce olamaz",
        "Kanıt tamamlanıp tablo sorumluluğu alındığında",
        ["Evet; finansal tablo tarihinden sonraki herhangi bir gün seçilebilir", "Evet; yönetim istemişse kanıt tamamlanmadan tarih atılır", "Hayır; rapor her zaman finansal tablo tarihini taşımalıdır", "Evet; rapor tarihi yalnız sözleşme imza tarihine bağlıdır"],
        ["Denetim sözleşmesi imzalanır imzalanmaz", "İlk risk değerlendirme prosedürü uygulandığında", "Yönetim taslak bilanço hazırlamaya başladığında", "Denetim ücreti işletme tarafından tamamen ödendiğinde"],
        "Rapor tarihi, görüşe dayanak olacak yeterli ve uygun kanıt elde edilmeden önce olamaz.",
        "Finansal tablolar hazırlanmış olmalı, yetkili kişiler sorumluluk almalı ve görüşü destekleyen kanıt tamamlanmalıdır.",
        "BDS 700 par. 49", "medium",
    ),
    r(
        "Denetçi, üst yönetimden sorumlu olanlara hiç bildirmediği sıradan bir konuyu doğrudan kilit denetim konusu ilan etmiştir. Uygun mudur?",
        "Kilit denetim konuları hangi konu kümesinden seçilir?",
        "Hayır; kilit konu üst yönetime bildirilenlerden seçilir",
        "Üst yönetime bildirilen konular arasından",
        ["Evet; herhangi bir konu bildirim yapılmadan kilit konu seçilebilir", "Evet; yalnız yönetimin reklam için seçtiği konular kullanılır", "Hayır; kilit denetim konusu denetçi tarafından belirlenemez", "Evet; geçmiş yılların bütün konuları otomatik olarak kilit konudur"],
        ["İşletme çalışanlarının önerdiği bütün konulardan", "Finansal tablo kullanıcılarının oyladığı konulardan", "Yalnız önceki denetçinin raporundaki konulardan", "Yönetimin kamuya açıklamak istemediği tüm konulardan"],
        "Kilit denetim konusu, üst yönetim iletişimi içinden denetçinin cari dönem denetiminde en çok önem verdiği konudur.",
        "BDS 701, kilit konuları üst yönetimden sorumlu olanlara bildirilen konular arasından seçilen en önemli konular olarak tanımlar.",
        "BDS 701 par. 8", "easy",
    ),
    r(
        "Denetçi azami dikkat gerektiren alanları belirlerken yalnız parasal tutara bakmış; ciddi risk, yüksek tahmin belirsizliği ve önemli olayları dışlamıştır. Yaklaşım uygun mudur?",
        "Azami düzeyde dikkat gerektiren konular belirlenirken hangi alanlar özellikle dikkate alınır?",
        "Hayır; ciddi risk, önemli yargı ve olaylar da dikkate alınır",
        "Yüksek risk, önemli yönetim yargıları ve önemli işlemler",
        ["Evet; yalnız hesabın parasal büyüklüğü kilit konu belirler", "Evet; tahmin belirsizliği raporlama açısından önemsizdir", "Hayır; bütün finansal tablo hesapları kilit konu yapılmalıdır", "Evet; dönem içi önemli olaylar denetçi dikkatini etkilemez"],
        ["Yalnız denetim ücretinin yüksek olduğu çalışma alanları", "Sadece yönetimin raporda görmek istediği hesaplar", "Denetim ekibinin en az zaman ayırdığı rutin alanlar", "İşletmenin reklamlarında en sık kullandığı finansal veriler"],
        "Kilit konu seçimi, yüksek riskli ve önemli muhakeme gerektiren alanlarla önemli olayların denetime etkisine odaklanır.",
        "Denetçi azami dikkat alanları içinden cari dönem denetiminde en çok önem arz edenleri kilit konu belirler.",
        "BDS 701 par. 9-10", "medium",
    ),
    r(
        "Kilit Denetim Konuları bölümünde stok değerlemesi için ayrı bir olumlu görüş verilmiştir. Bu ifade uygun mudur?",
        "Kilit denetim konuları bir bütün olarak denetçi görüşüyle nasıl ilişkilidir?",
        "Hayır; kilit konular hakkında ayrı görüş verilmez",
        "Genel denetimde ele alınır; ayrı görüş verilmez",
        ["Evet; her kilit konu için bağımsız bir görüş zorunludur", "Evet; kilit konu bölümü genel görüşün yerine geçer", "Hayır; kilit konular denetim sırasında hiç ele alınmaz", "Evet; ayrı görüş yalnız stok ve hasılat için verilir"],
        ["Genel denetçi görüşünü tamamen ortadan kaldırır", "Her kilit konu için ikinci bir denetim raporu gerektirir", "Yalnız yönetimin görüşünü kullanıcıya aktarmak için kullanılır", "Olumlu görüş dışında görüş verilmesini her durumda engeller"],
        "Kilit konu açıklaması denetimde odaklanılan alanı anlatır; o alan için ayrı bir güvence sonucu oluşturmaz.",
        "Kilit konular bir bütün olarak finansal tabloların denetimi ve genel görüş bağlamında ele alınır.",
        "BDS 701 par. 11", "easy",
    ),
    r(
        "Rapor bir konuyu kilit denetim konusu olarak adlandırmış; ancak neden önemli olduğu ve denetimde nasıl ele alındığı açıklanmamıştır. Yeterli midir?",
        "Münferit kilit denetim konusu açıklamasının zorunlu iki içeriği hangisidir?",
        "Hayır; seçilme nedeni ve denetim yaklaşımı açıklanır",
        "Kilit konu seçilme nedeni ve denetimdeki yaklaşım",
        ["Evet; yalnız konu başlığının yazılması yeterlidir", "Evet; sadece yönetimin konuya ilişkin görüşü aktarılır", "Hayır; denetçinin ayrı olumlu görüş vermesi gerekir", "Evet; yalnız konuya ayrılan çalışma saati açıklanır"],
        ["Denetim ücreti ile ekipteki denetçi sayısı", "Yönetimin gelecek yıl bütçesi ile satış tahmini", "Konunun işletme reklamlarında nasıl sunulduğu", "Yalnız finansal tablo dipnotunun sayfa numarası"],
        "Kullanıcı, konunun niçin denetimde öne çıktığını ve denetçinin bu alana nasıl karşılık verdiğini anlamalıdır.",
        "Açıklama varsa ilgili finansal tablo dipnotuna atıf da içerir; ancak ayrı görüş oluşturmaz.",
        "BDS 701 par. 13", "medium",
    ),
    r(
        "Önemli ve yaygın yanlışlığa neden olan konu yalnız Kilit Denetim Konuları bölümünde anlatılmış, olumsuz görüş verilmemiştir. Uygun mudur?",
        "Olumlu görüş dışında görüşe neden olan konu Kilit Denetim Konuları bölümünde nasıl ele alınır?",
        "Hayır; KDK, olumlu görüş dışındaki görüşün yerine geçmez",
        "İlgili görüşün dayanağında raporlanır; kilit konu bölümünde bu bölüme atıf yapılır",
        ["Evet; kilit konu açıklaması her tür görüş değişikliğinin yerini alır", "Evet; önemli yanlışlık kilit konu yazılınca önemsizleşir", "Hayır; konu raporun hiçbir bölümünde açıklanamaz", "Evet; yalnız yönetim isterse görüş değiştirilir"],
        ["Yalnız kilit konu bölümünde ayrı olumlu görüş verilir", "Konu finansal tablo dipnotlarından ve rapordan çıkarılır", "Yönetimin sorumlulukları bölümünde önemsiz konu olarak sunulur", "Görüş bölümü değiştirilmeden yalnız rapor tarihine eklenir"],
        "Kilit konu bildirimi olumlu görüş dışı görüşün, gerekli açıklamaların veya işletmenin sürekliliği raporlamasının alternatifi değildir.",
        "Görüş değişikliğine yol açan konu ilgili dayanak bölümünde açıklanır; KDK bölümü gerekiyorsa oraya atıf yapar.",
        "BDS 701 par. 12 ve 15", "hard",
    ),
    r(
        "Kilit denetim konusu kamuya açıklanırsa ciddi zarar doğuracaktır; ancak bu zarar kamu yararından ağır basmamaktadır. Denetçi konuyu açıklamayabilir mi?",
        "Kilit denetim konusunun raporda açıklanmamasına izin veren durum hangisidir?",
        "Hayır; kamu yararı ağır basıyorsa konu açıklanır",
        "Mevzuat yasağı veya kamu yararını aşan zarar beklentisi",
        ["Evet; işletme yönetimi istemediğinde konu gizlenir", "Evet; denetim ücreti yüksekse açıklama yapılmaz", "Hayır; mevzuat yasağı olsa bile her konu açıklanır", "Evet; konu finansal tablolarda önemliyse daima gizlenir"],
        ["Yönetimin konuyu raporda görmek istememesi", "Konunun açıklamasının raporu bir sayfa uzatması", "Denetçinin konuya çok çalışma saati ayırmış olması", "İşletmenin konuyu reklamlarında kullanmayı planlamaması"],
        "Açıklamama istisnası dar yorumlanır; olumsuz sonuçların kamu yararını aşması makul biçimde beklenmelidir.",
        "Mevzuat yasağı dışında açıklamama, oldukça istisnai bir kamu yararı dengelemesine dayanır ve gerekçesi belgelenir.",
        "BDS 701 par. 14 ve 18", "hard",
    ),
    r(
        "Denetçi önemli yanlışlık olduğunu veya önemli yanlışlık olmadığı sonucuna yetecek kanıt elde edemediğini belirlemiştir. Her iki durumun ortak sonucu nedir?",
        "Olumlu görüş dışında görüş verilmesini tetikleyen iki temel koşul hangisidir?",
        "Olumlu görüş dışında bir görüş değerlendirilir",
        "Önemli yanlışlık veya kanıt yetersizliği",
        ["Her durumda olumlu görüş verilir", "Yalnız dikkat çekilen hususlar paragrafı eklenir", "Denetim raporu görüşsüz biçimde yayımlanır", "Kilit denetim konusu bulunmadığı açıklanır"],
        ["İşletmenin kâr etmesi veya zarar açıklaması", "Denetim ücretinin artması veya azalması", "Yönetimin raporu erken ya da geç istemesi", "Finansal tabloların kısa veya uzun olması"],
        "Önemli yanlışlık tespiti ile kanıt yetersizliği farklı kaynaklardır; ikisi de koşullarına göre olumlu görüş dışı sonuca yol açar.",
        "Görüş türü, sorunun kaynağı yanında etkilerin önemli ve yaygın olup olmadığına göre belirlenir.",
        "BDS 705 par. 6", "easy",
    ),
    r(
        "Yanlışlık yalnız tek bir hesabı aşan biçimde finansal tabloların önemli bölümünü etkilemekte ve kullanıcı anlayışı açısından temel oluşturmaktadır. Etki nasıl nitelenir?",
        "BDS 705 bakımından yaygın etki hangi durumlardan biriyle tanımlanır?",
        "Yaygın etki",
        "Sınırsızlık veya tabloların önemli bölümüne etki",
        ["Bariz önemsiz etki", "Yalnız niteliksiz etki", "Örnekleme dışı etki", "Sadece geçici etki"],
        ["Yalnız tek bir küçük hesabı önemsiz tutarda etkileme", "Finansal tabloların hiçbir unsurunu etkilememe", "Sadece denetim ücretinin hesaplanmasını değiştirme", "Yalnız raporun sayfa düzenini ve başlığını etkileme"],
        "Yaygınlık, yalnız tutarın büyüklüğünden değil etkinin finansal tablolara ne ölçüde yayıldığından ve kullanıcı anlayışındaki temel rolünden doğar.",
        "Etki sınırlı değilse, sınırlı olsa bile tabloların önemli bölümünü temsil ediyorsa veya açıklama kullanıcı anlayışı için temelse yaygın olabilir.",
        "BDS 705 par. 5", "medium",
    ),
    r(
        "Denetçi yeterli kanıt elde etmiş ve önemli fakat yaygın olmayan bir yanlışlık bulmuştur. Hangi görüş uygundur?",
        "Kanıt yetersizliğinin muhtemel etkisi önemli fakat yaygın değilse hangi görüş verilir?",
        "Sınırlı olumlu görüş",
        "Sınırlı olumlu görüş",
        ["Olumsuz görüş", "Görüş vermekten kaçınma", "Koşulsuz olumlu görüş", "Kilit denetim konusu görüşü"],
        ["Olumsuz görüş", "Görüş vermekten kaçınma", "Koşulsuz olumlu görüş", "Diğer hususlar görüşü"],
        "Önemli fakat yaygın olmayan tespit edilmiş yanlışlık sınırlı olumlu görüş gerektirir.",
        "Kanıt yetersizliğinde de muhtemel etki önemli fakat yaygın değilse sınırlı olumlu görüş verilir.",
        "BDS 705 par. 7", "easy",
    ),
    r(
        "Denetçi yeterli kanıtla hasılatın finansal tablolar genelinde önemli ve yaygın biçimde yanlış olduğunu belirlemiştir. Hangi görüş verilir?",
        "Olumsuz görüşün doğru koşul bileşimi hangisidir?",
        "Olumsuz görüş",
        "Yeterli kanıtla belirlenen önemli ve yaygın yanlışlık",
        ["Sınırlı olumlu görüş", "Görüş vermekten kaçınma", "Koşulsuz olumlu görüş", "Dikkat çekilen hususlar görüşü"],
        ["Kanıt yetersizliğinin önemli ve yaygın muhtemel etkisi", "Önemli olmayan ve yaygın olmayan bir sınıflandırma farkı", "Yeterli kanıtla önemli fakat yaygın olmayan yanlışlık", "Finansal tablolarda doğru açıklanmış önemli bir olay"],
        "Denetçi yanlışlığı kanıtla belirlemiş ve etki hem önemli hem yaygın olduğundan olumsuz görüş verir.",
        "Olumsuz görüşün kaynağı kanıt yetersizliği değil, belirlenmiş önemli ve yaygın yanlışlıktır.",
        "BDS 705 par. 8", "easy",
    ),
    r(
        "Yönetim kayıtları vermediği için kanıt elde edilememiş; tespit edilmemiş yanlışlıkların muhtemel etkisi önemli ve yaygın olabilir. Hangi görüş uygundur?",
        "Görüş vermekten kaçınmanın temel koşulu hangisidir?",
        "Görüş vermekten kaçınma",
        "Kanıt yokluğu ile önemli ve yaygın muhtemel etki",
        ["Olumsuz görüş", "Sınırlı olumlu görüş", "Koşulsuz olumlu görüş", "Dikkat çekilen hususlar görüşü"],
        ["Yeterli kanıtla belirlenmiş önemli ve yaygın yanlışlık", "Yeterli kanıtla önemli fakat yaygın olmayan yanlışlık", "Doğru açıklanmış önemli bir bilanço sonrası olay", "Önemsiz bir sınıflandırma farkının düzeltilmesi"],
        "Kanıt yokluğu nedeniyle etki kesin belirlenememiştir; muhtemel etki önemli ve yaygınsa görüş verilemez.",
        "Olumsuz görüş belirlenmiş yanlışlığa, kaçınma ise önemli ve yaygın olabilecek etki hakkında yeterli kanıt elde edilememesine dayanır.",
        "BDS 705 par. 9", "medium",
    ),
    r(
        "Birden fazla belirsizliğin tek tek kanıtı elde edilmiş; ancak etkileşimleri ve kümülatif etkileri nedeniyle bir bütün olarak görüş oluşturulamamaktadır. Ne yapılabilir?",
        "Birden fazla belirsizlikte istisnai olarak görüşten kaçınma hangi gerekçeye dayanabilir?",
        "Görüş vermekten kaçınılabilir",
        "Belirsizlik etkileşimi yüzünden görüş oluşturulamaması",
        ["Her durumda koşulsuz olumlu görüş verilir", "Yalnız dikkat çekilen hususlar paragrafı yeterlidir", "Bütün belirsizlikler otomatik önemsiz sayılır", "Her belirsizlik için ayrı olumlu görüş verilir"],
        ["Belirsizliklerin birbirinden tamamen bağımsız ve önemsiz olması", "Yönetimin raporun kısa olmasını istemesi", "Denetim ekibinin çalışma saatinin bütçeyi aşması", "Belirsizliklerin finansal tablolarla ilgisiz olması"],
        "İstisnai durumda kanıt tek tek mevcut olsa da belirsizliklerin birlikte etkisi güvenilir bir genel görüşü engelleyebilir.",
        "Kaçınma, belirsizliklerin muhtemel etkileşimi ve tablolar üzerindeki kümülatif etkileri nedeniyle görüş oluşturulamamasına dayanır.",
        "BDS 705 par. 10", "hard",
    ),
    r(
        "Önemli fakat yaygın olmayan yanlışlık nedeniyle rapor sınırlı olumlu görüş içerecektir. Görüş cümlesinde hangi yapı kullanılır?",
        "Olumlu görüş dışındaki raporda Görüşün Dayanağı başlığı nasıl uyarlanır?",
        "Yanlışlığın etkileri hariç tabloların uygunluğu belirtilir",
        "Dayanak başlığı verilen görüş türüne uyarlanır",
        ["Finansal tabloların hiçbir bölümüne ilişkin görüş verilmez", "Yanlışlığın bütün tablolarda önemsiz olduğu belirtilir", "Herhangi bir istisna ifadesi kullanılmadan olumlu görüş verilir", "Konu yalnız kilit denetim konusu olarak açıklanır"],
        ["Başlık her durumda yalnız Görüşün Dayanağı olarak kalır", "Başlık Yönetimin Dayanağı olarak değiştirilir", "Başlık yalnız Kilit Denetim Konuları yapılır", "Dayanak bölümü olumlu görüş dışında tamamen kaldırılır"],
        "Sınırlı olumlu görüş, dayanak bölümünde açıklanan hususun etkileri dışında kalan tablo sunumuna ilişkin sonuç verir.",
        "Dayanak bölümünün başlığı görüş türünü açıkça gösterir ve olumlu görüş dışı sonuca sebep olan hususu açıklar.",
        "BDS 705 par. 16-20", "medium",
    ),
    r(
        "Finansal tablolarda doğru ve yeterli açıklanmış büyük bir dava, kullanıcıların tabloları anlaması için temel önemdedir. Görüş değişikliği gerekmiyorsa hangi paragraf kullanılabilir?",
        "Dikkat Çekilen Hususlar paragrafı hangi tür hususa atıfta bulunur?",
        "Dikkat Çekilen Hususlar paragrafı",
        "Uygun açıklanmış ve tablo anlayışı için temel husus",
        ["Diğer Hususlar paragrafı", "Olumsuz Görüşün Dayanağı", "Görüş Vermekten Kaçınma bölümü", "Yönetimin Sorumlulukları bölümü"],
        ["Finansal tablolarda hiç sunulmayan denetimle ilgili bir husus", "Olumlu görüş dışı görüşe neden olan açıklanmamış yanlışlık", "Denetim ücreti ve sözleşme koşullarına ilişkin ayrıntılar", "Denetçinin işletme dışında verdiği diğer hizmetlerin listesi"],
        "Husus finansal tablolarda uygun açıklanmış, kullanıcı anlayışı için temel ve görüş değişikliğine neden olmamaktadır.",
        "Dikkat çekilen hususlar paragrafı ilgili dipnota atıf yapar ve denetçi görüşünün değişmediğini belirtir.",
        "BDS 706 par. 7-9", "medium",
    ),
    r(
        "Önceki dönem finansal tabloları başka denetçi tarafından denetlenmiştir ve bu bilgi cari tabloların içinde sunulmamaktadır. Kullanıcının denetimi anlaması için açıklama gerekiyorsa hangi paragraf uygundur?",
        "Diğer Hususlar paragrafı hangi tür bilgiye yöneliktir?",
        "Diğer Hususlar paragrafı",
        "Tablo dışı, denetim veya rapor anlayışıyla ilgili husus",
        ["Dikkat Çekilen Hususlar paragrafı", "Olumsuz Görüşün Dayanağı", "İşletmenin Sürekliliği bölümü", "Kilit konuya ilişkin ayrı görüş"],
        ["Finansal tablolarda uygun açıklanmış temel önemde bir husus", "Finansal tablolarda düzeltilmemiş önemli bir yanlışlık", "İşletmenin satış bütçesi ve yönetimin kâr hedefi", "Yalnız finansal tablo dipnotunda sunulan muhasebe politikası"],
        "Bilgi finansal tabloların içeriği değil, kullanıcının denetimi veya raporu anlamasıyla ilgilidir.",
        "Diğer Hususlar paragrafı, finansal tablolarda sunulan ya da açıklananlar dışındaki denetimle ilgili hususları kapsar.",
        "BDS 706 par. 7 ve 10-11", "easy",
    ),
    r(
        "Denetçi, önemli yanlışlığı düzeltmek yerine Dikkat Çekilen Hususlar paragrafı eklemiş ve bunun sınırlı olumlu görüşün yerini aldığını belirtmiştir. Uygun mudur?",
        "Dikkat Çekilen Hususlar paragrafı aşağıdakilerden hangisinin yerine geçmez?",
        "Hayır; dikkat paragrafı olumlu görüş dışındaki görüşün yerini alamaz",
        "Görüş değişikliği, açıklama veya süreklilik bildirimi",
        ["Evet; dikkat paragrafı bütün görüş değişikliklerinin alternatifidir", "Evet; önemli yanlışlık dipnota atıfla ortadan kalkar", "Hayır; dikkat paragrafı her zaman görüşten kaçınma yaratır", "Evet; yönetim isterse bütün yanlışlıklar dikkat paragrafına taşınır"],
        ["Yalnız rapor başlığının ve muhatabın belirtilmesi", "Denetçinin imzası ve görev yaptığı yer bilgisi", "Rapor tarihinin ve denetlenen dönemin açıklanması", "Görüş bölümünde işletmenin adının belirtilmesi"],
        "Dikkat paragrafı uygun açıklanmış hususa dikkat çeker; eksik açıklamayı veya gerekli görüş değişikliğini iyileştiremez.",
        "Denetçi böyle bir paragraf eklemeyi düşünüyorsa önerilen metni üst yönetimden sorumlu olanlara bildirir.",
        "BDS 706 par. 8-12", "hard",
    ),
    r(
        "İşletme tasfiye edilme niyetine rağmen finansal tablolarını işletmenin sürekliliği esasına göre hazırlamıştır. Denetçi bu esası uygun bulmamaktadır. Hangi görüş verilir?",
        "İşletmenin sürekliliği esasının kullanılması uygun değilse rapor sonucu nedir?",
        "Olumsuz görüş",
        "Olumsuz görüş",
        ["Olumlu görüş ve dikkat paragrafı", "Sınırlı olumlu görüş", "Görüş vermekten kaçınma", "Yalnız kilit denetim konusu"],
        ["Olumlu görüş", "Sınırlı olumlu görüş", "Görüş vermekten kaçınma", "Diğer Hususlar paragrafı"],
        "Uygun olmayan süreklilik esası finansal tabloların temel hazırlanma esasını bozduğu için olumsuz görüş gerektirir.",
        "Yönetim süreklilik esasını kullanmamalıyken kullanmışsa yeterli açıklama yapılması olumlu görüş sağlamaz.",
        "BDS 570 par. 21", "easy",
    ),
    r(
        "Sürekliliğe ilişkin önemli belirsizlik vardır; yönetimin süreklilik esasını kullanması uygun ve dipnot açıklaması yeterlidir. Raporlama nasıl olur?",
        "Yeterli açıklanmış süreklilik önemli belirsizliği görüşü nasıl etkiler?",
        "Olumlu görüş ve ayrı süreklilik belirsizliği bölümü",
        "Görüş değişmez; ayrı süreklilik bölümü eklenir",
        ["Doğrudan olumsuz görüş verilir", "Her durumda görüş vermekten kaçınılır", "Sadece Diğer Hususlar paragrafı kullanılır", "Belirsizlik raporda hiçbir biçimde açıklanmaz"],
        ["Her durumda olumsuz görüş gerektirir", "Otomatik olarak görüş vermekten kaçınma doğurur", "Yalnız Kilit Denetim Konuları bölümünde açıklanır", "Raporun bütün dayanak bölümlerini ortadan kaldırır"],
        "Esas uygun ve açıklama yeterliyse olumlu görüş korunur; ayrı bölüm dipnota dikkat çeker ve belirsizliğin görüşü değiştirmediğini söyler.",
        "Süreklilik önemli belirsizliği nitelikçe kilit konu olsa da KDK bölümünde değil, kendine özgü ayrı bölümde raporlanır.",
        "BDS 570 par. 22; BDS 701 par. 15", "hard",
    ),
    r(
        "İşletmenin sürekliliği esasının kullanılması uygundur; ancak mevcut önemli belirsizlik finansal tablolarda yeterince açıklanmamıştır. Denetçi ne yapar?",
        "Süreklilik önemli belirsizliği yetersiz açıklanmışsa hangi görüşler arasından seçim yapılır?",
        "BDS 705'e göre sınırlı olumlu veya olumsuz görüş verir",
        "Yaygınlığa göre sınırlı olumlu veya olumsuz görüş",
        ["Her durumda koşulsuz olumlu görüş verir", "Yalnız dikkat çekilen hususlar paragrafı ekler", "Açıklama eksikliğini kilit denetim konusu sayıp görüşü değiştirmez", "Finansal tabloların dışına sözlü bir uyarı eklemekle yetinir"],
        ["Olumlu görüş veya yalnız Diğer Hususlar paragrafı", "Görüş vermekten kaçınma veya olumlu görüş", "Yalnız Kilit Denetim Konuları bölümü", "Her durumda sadece olumsuz görüş"],
        "Açıklama eksikliği önemli yanlışlık oluşturur; yaygınlık sınırlı olumlu ile olumsuz görüş arasındaki seçimi belirler.",
        "Dayanak bölümünde önemli belirsizliğin var olduğu ve finansal tablolarda yeterince açıklanmadığı belirtilir.",
        "BDS 570 par. 23; BDS 705", "hard",
    ),
]


PREMISES = [
    {"stem":"Olumlu görüş bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tablolar tüm önemli yönleriyle geçerli çerçeveye uygundur\n\nII. Yeterli ve uygun denetim kanıtı değerlendirilir\n\nIII. Her önemli yanlışlık olumlu görüşle bağdaşır","correct":"I ve II","why":"Olumlu görüş uygunluk ve yeterli kanıt sonucuna dayanır; önemli yanlışlık olumlu görüş dışında sonuç doğurabilir.","ref":"BDS 700 par. 10-17","difficulty":"medium"},
    {"stem":"Denetçi raporunun şekli bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Rapor yazılı düzenlenir\n\nII. İlk bölüm Görüş başlığını taşır\n\nIII. Görüşün Dayanağı bölümü Görüş bölümünü izler","correct":"I, II ve III","why":"Yazılı raporda Görüş ilk bölümdür ve hemen ardından Görüşün Dayanağı gelir.","ref":"BDS 700 par. 20T, 23 ve 28","difficulty":"easy"},
    {"stem":"Kilit denetim konuları bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Üst yönetimden sorumlu olanlara bildirilen konular arasından seçilir\n\nII. Her kilit konu hakkında ayrı görüş verilir\n\nIII. Konunun denetimde nasıl ele alındığı açıklanır","correct":"I ve III","why":"Kilit konular üst yönetim iletişiminden seçilir ve denetim yaklaşımı açıklanır; ayrı görüş verilmez.","ref":"BDS 701 par. 8, 11 ve 13","difficulty":"medium"},
    {"stem":"Olumlu görüş dışındaki görüşler bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Önemli fakat yaygın olmayan yanlışlık sınırlı olumlu görüşe yol açabilir\n\nII. Belirlenmiş önemli ve yaygın yanlışlık olumsuz görüşe yol açar\n\nIII. Kanıt yetersizliğinin önemli ve yaygın muhtemel etkisi kaçınmaya yol açar","correct":"I, II ve III","why":"Üç ifade de sorunun kaynağı ile önem ve yaygınlık matrisine uygundur.","ref":"BDS 705 par. 7-9","difficulty":"hard"},
    {"stem":"Yaygın etki bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Mutlaka tek bir küçük hesapla sınırlıdır\n\nII. Finansal tabloların önemli bölümünü temsil edebilir\n\nIII. Açıklamalarda kullanıcı anlayışı açısından temel olabilir","correct":"II ve III","why":"Yaygın etki sınırlı değildir veya tabloların önemli bölümünü temsil eder; açıklamalarda kullanıcı anlayışı için temel olabilir.","ref":"BDS 705 par. 5","difficulty":"medium"},
    {"stem":"Dikkat Çekilen Hususlar paragrafı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Finansal tablolarda uygun açıklanmış bir hususa atıf yapar\n\nII. Olumlu görüş dışındaki görüşün yerine geçer\n\nIII. Görüşün değişmediğini belirtir","correct":"I ve III","why":"Paragraf uygun açıklanmış temel hususa dikkat çeker ve görüşü değiştirmez; gerekli görüş değişikliğinin yerine geçmez.","ref":"BDS 706 par. 8-9","difficulty":"medium"},
    {"stem":"Diğer Hususlar paragrafı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yalnız finansal tablolarda sunulan hususları kapsar\n\nII. Denetimin anlaşılmasıyla ilgili tablo dışı bir hususu kapsayabilir\n\nIII. Mevzuatla yasaklanmamış olması gerekir","correct":"II ve III","why":"Diğer Hususlar tablo dışında olup denetim, sorumluluklar veya raporun anlaşılmasıyla ilgili hususlara yönelir ve mevzuat yasağı bulunmamalıdır.","ref":"BDS 706 par. 7 ve 10","difficulty":"medium"},
    {"stem":"İşletmenin sürekliliği raporlaması bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Esasın kullanılması uygun değilse olumsuz görüş verilir\n\nII. Yeterli açıklanmış önemli belirsizlikte ayrı bölüm kullanılır\n\nIII. Yetersiz açıklama denetçi görüşünü hiçbir durumda değiştirmez","correct":"I ve II","why":"Esas uygun değilse olumsuz görüş verilir; yeterli açıklanmış önemli belirsizlik ayrı bölümde raporlanır. Yetersiz açıklama ise görüşü değiştirebilir.","ref":"BDS 570 par. 21-23","difficulty":"hard"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="denetim", topic_id="denetci_raporu",
        label="Denetçi Raporu ve Görüşler", slug="denetci_raporu", prefix="topic-dr",
        seed=2026071770,
        legislation_version="KGK TDS 2026 Seti; BDS 570, 700, 701, 705 ve 706, 17.07.2026 kontrolü",
        rules=RULES, premises=PREMISES, wrong_banks={},
    )
