#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Hukuk — Ticaret Şirketleri konu havuzu (3×20).

17.07.2026 tarihli güncel 6102 sayılı TTK metni esas alınmıştır. Sorular,
2026-1 resmî sınavındaki kısa kanun uygulaması ve öncül dengesini izler; resmî
soruların metnini veya seçeneklerini tekrar etmez.
"""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, distractors, why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario,
        "focus": focus,
        "correct": correct,
        "distractors": distractors,
        "focus_distractors": distractors[1:] + distractors[:1],
        "why": why,
        "focus_why": focus_why,
        "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Girişimciler, kuracakları yapıyı 6102 sayılı TTK anlamında bir ticaret şirketi olarak tescil ettirmek istemektedir. Aşağıdakilerden hangisi Kanunda sayılan ticaret şirketlerinden biridir?",
        "TTK m.124'te sınırlı olarak sayılan ticaret şirketi türlerinden biri aşağıdakilerden hangisidir?",
        "Kollektif şirket, Kanunda sayılan ticaret şirketi türlerinden biridir",
        ["Adi şirket, TTK'da ticaret şirketi olarak sayılan sermaye şirketidir", "Donatma iştiraki, bütün hâllerde ayrı tüzel kişiliğe sahip ticaret şirketidir", "İş ortaklığı, tescille kendiliğinden anonim şirket niteliği kazanır", "Acentelik, tarafların anlaşmasıyla ayrı bir ticaret şirketine dönüşür"],
        "TTK m.124/1 ticaret şirketlerini kollektif, komandit, anonim, limited ve kooperatif olarak sayar. Adi şirket bu sınırlı sayımın içinde değildir.",
        "Kollektif şirket Kanundaki beş ticaret şirketi türünden biridir; acentelik veya sözleşmesel iş ortaklığı bu hükümde şirket türü olarak yer almaz.",
        "6102 sayılı TTK m.124/1", "easy",
    ),
    r(
        "Bir uzman, şirket türlerini şahıs ve sermaye şirketleri olarak ayırırken kollektif şirketi sermaye şirketleri arasında göstermiştir. TTK m.124/2 bakımından doğru sınıflandırma hangisidir?",
        "Kollektif ve adi komandit şirketlerin TTK'daki ortak sınıflandırması aşağıdakilerden hangisidir?",
        "Kollektif ve komandit şirketler şahıs şirketi sayılır",
        ["Kollektif ve komandit şirketler sermaye şirketi sayılır", "Kollektif şirket sermaye, komandit şirket kooperatif sayılır", "Her iki şirket de adi şirket sayılır ve tüzel kişilik taşımaz", "Her iki şirket yalnız halka açık ortaklık olarak kurulabilir"],
        "TTK m.124/2, kollektif ile komandit şirketi şahıs şirketi olarak sınıflandırır. Sermaye şirketleri anonim, limited ve sermayesi paylara bölünmüş komandit şirkettir.",
        "Şahıs şirketleri grubunu kollektif ve adi komandit şirket oluşturur. Sorumluluk ve ortak kişiliğinin önemi bu sınıflandırmanın temel sonuçları arasındadır.",
        "6102 sayılı TTK m.124/2", "easy",
    ),
    r(
        "Tescil edilmiş bir limited şirketin ortaklarından ayrı hak sahibi olamayacağı ve borç üstlenemeyeceği ileri sürülmektedir. Ticaret şirketlerinin hukuki niteliği bakımından hangisi doğrudur?",
        "6102 sayılı TTK kapsamındaki ticaret şirketlerinin ortaklarından ayrı hukuki varlığı nasıl ifade edilir?",
        "Ticaret şirketleri tüzel kişiliğe sahiptir",
        ["Ticaret şirketleri yalnız ortakların adına işlem yapan tüzel kişiliği olmayan birliklerdir", "Ticaret şirketlerinin tüzel kişiliği sadece bütün ortaklar tacirse doğar", "Tüzel kişilik yalnız anonim şirketlere tanınmış istisnai bir niteliktir", "Şirket tüzel kişiliği ancak ilk kâr dağıtımından sonra kazanılır"],
        "TTK m.125/1 bütün ticaret şirketlerinin tüzel kişiliğe sahip olduğunu düzenler. Bu nedenle şirket, ortaklarından ayrı hak ve borç sahibi olabilir.",
        "Tüzel kişilik yalnız sermaye şirketlerine özgü değildir; Kanunda sayılan ticaret şirketlerinin ortak niteliğidir ve şirketi ortaklardan ayırır.",
        "6102 sayılı TTK m.125/1", "easy",
    ),
    r(
        "Bir ticaret şirketinin, işletme konusu dışında kaldığı ileri sürülen bir sözleşmeyle hak edinmesinin her durumda imkânsız olduğu savunulmuştur. Şirketin hak ehliyeti bakımından hangisi doğrudur?",
        "Ticaret şirketlerinin haklardan yararlanma ve borç üstlenme ehliyeti hangi genel çerçevede düzenlenmiştir?",
        "Kanuni istisnalar dışında TMK m.48 çerçevesinde hak edinip borç üstlenebilirler",
        ["Yalnız şirket sözleşmesinde tek tek sayılan hakları edinip borçları üstlenebilirler", "Sadece taşınır mal edinebilir, taşınmaz ve fikrî hak sahibi olamazlar", "Ortakların tamamının yazılı izni olmadan hiçbir borç üstlenemezler", "Hak ehliyeti yalnız ticaret sicili müdürünün işlem bazında vereceği izne bağlıdır"],
        "TTK m.125/2, ticaret şirketlerinin TMK m.48 çerçevesinde bütün haklardan yararlanıp borç üstlenebileceğini; kanuni istisnaların saklı olduğunu belirtir.",
        "Şirket ehliyeti eski ultra vires sınırlamasına indirgenmez. Kanuni istisnalar dışında tüzel kişilere tanınan genel hak ehliyeti geçerlidir.",
        "6102 sayılı TTK m.125/2", "medium",
    ),
    r(
        "Bir ortak, ticaret şirketine sermaye olarak devredilebilir ve nakden değerlendirilebilir bir fikrî mülkiyet hakkı koymayı taahhüt etmiştir. Genel hükümler bakımından hangisi doğrudur?",
        "Kanunda aksine özel bir hüküm bulunmadıkça ticaret şirketine sermaye olarak konulabilecek değerlerden biri hangisidir?",
        "Devredilebilir ekonomik değerli fikrî mülkiyet hakkı sermaye olabilir",
        ["Devri hukuken yasaklanmış kişiye sıkı sıkıya bağlı hak sermaye olabilir", "Ekonomik değeri bulunmayan kişisel tercih sermaye sayılır", "Üçüncü kişinin izni olmadan devredilemeyen aile hakkı sermaye sayılır", "Ortağın gelecekte edinmeyi umduğu belirsiz manevi değer sermaye olur"],
        "TTK m.127 fikrî mülkiyet haklarını ve devredilip nakden değerlendirilebilen değerleri, özel sınırlamalar saklı olmak üzere sermaye konusu kabul eder.",
        "Sermaye konusu olabilme bakımından devredilebilirlik ve ekonomik değer önemlidir. Kişiye sıkı sıkıya bağlı veya ekonomik değersiz haklar bu genel kurala uymaz.",
        "6102 sayılı TTK m.127/1", "medium",
    ),
    r(
        "Bir anonim şirket ortağı, sermaye borcunu yalnız kişisel emeğiyle yerine getirmek istemektedir. TTK'nın anonim şirkette ayni sermayeye ilişkin özel hükmü bakımından hangisi doğrudur?",
        "Anonim ve limited şirketlerde ayni sermaye bakımından kişisel emek ve ticari itibarın durumu aşağıdakilerden hangisidir?",
        "Kişisel emek ve ticari itibar sermaye şirketine ayni sermaye olamaz",
        ["Kişisel emek ve ticari itibar değer biçilmeksizin sınırsız sermaye sayılır", "Yalnız ticari itibar, hiçbir koşul aranmadan nakit sermaye yerine geçer", "Kişisel emek sadece halka açık anonim şirketlerde zorunlu sermayedir", "Her iki değer de tescille kendiliğinden para sermayesine dönüşür"],
        "TTK m.342/1 ve m.581/1, hizmet edimleri, kişisel emek ve ticari itibarı anonim ve limited şirkete ayni sermaye olarak konulamayacak değerler arasında sayar.",
        "TTK m.127'deki genel liste, şirket türüne özgü sınırlamalar saklı tutularak uygulanır. Sermaye şirketlerindeki özel hükümler kişisel emek ve itibarı dışlar.",
        "6102 sayılı TTK m.127/2, 342/1 ve 581/1", "medium",
    ),
    r(
        "Ortak, usulüne uygun düzenlenip imzalanan şirket sözleşmesinde belirli bir sermaye koymayı taahhüt etmiş; daha sonra şirketin henüz talepte bulunmadığını savunmuştur. Borcun doğumu bakımından hangisi doğrudur?",
        "Ortağın sermaye koyma borcu kime karşı ve hangi temel belgeye dayanarak doğar?",
        "Ortak, şirket sözleşmesindeki taahhüdü nedeniyle şirkete karşı borçlanır",
        ["Ortak yalnız diğer ortakların kişisel alacaklılarına karşı sermaye borçlusu olur", "Sermaye borcu şirket sözleşmesinden değil ilk kâr dağıtımından doğar", "Ortak yalnız ticaret sicili müdürüne karşı sermaye borçlusu sayılır", "Taahhüt imzalanmış olsa bile şirket hiçbir zaman ifa isteyemez"],
        "TTK m.128/1 uyarınca her ortak, usulüne uygun şirket sözleşmesiyle koymayı taahhüt ettiği sermayeden dolayı şirkete karşı borçludur.",
        "Sermaye koyma taahhüdünün alacaklısı şirkettir. Borcun kaynağı usulüne göre düzenlenip imzalanan şirket sözleşmesindeki taahhüttür.",
        "6102 sayılı TTK m.128/1", "easy",
    ),
    r(
        "Şirkete sermaye olarak konulacak taşınmaz sözleşmede bilirkişi değeriyle yer almış ve tapuya şerh verilmiştir. Ayni sermayenin kabulü bakımından hangisi doğrudur?",
        "Bir taşınmazın kuruluş aşamasında ayni sermaye olarak kabulü için TTK m.128/2'de aranan işlemlerden biri hangisidir?",
        "Taşınmazın bilirkişi değeriyle sözleşmede yer alması ve tapuya şerh verilmesi",
        ["Taşınmazın yalnız ortağın kişisel defterine kaydedilip şirkete sözlü bildirilmesi", "Taşınmazın değerleme yapılmadan şirketin internet sitesinde duyurulması", "Taşınmazın tapu bağlantısı kurulmadan yalnız fatura ile şirkete teslimi", "Taşınmazın sicile hiç işlenmeden ortağın kullanımında bırakılması"],
        "TTK m.128/2, taşınmazın bilirkişi değeriyle şirket sözleşmesinde yer almasını ve tapuya şerh verilmesini ayni sermayenin kabulü için düzenler.",
        "Taşınmaz sermayesinde sözlü taahhüt yeterli değildir. Bilirkişi değeri ve tapu şerhi, hakkın şirkete özgülenmesini ve üçüncü kişilere karşı korunmasını sağlar.",
        "6102 sayılı TTK m.128/2", "medium",
    ),
    r(
        "Ortak sermaye taahhüdünü zamanında yerine getirmemiş ve şirket zarara uğramıştır. Şirket hem ifayı hem gecikme zararını talep etmek istemektedir. Hangisi doğrudur?",
        "Sermaye koyma borcunun yerine getirilmemesi hâlinde şirketin sahip olduğu temel taleplerden biri hangisidir?",
        "Şirket ifayı dava edebilir; gecikme zararının tazmini için ihtar şarttır",
        ["Şirket yalnız ortağı üyelikten çıkarabilir, ifa veya tazminat isteyemez", "Şirket gecikme zararını ihtarsız isteyebilir fakat sermayenin ifasını dava edemez", "Şirket sermaye alacağını kendiliğinden bağışlanmış kabul etmek zorundadır", "Şirket yalnız ticaret sicilinden disiplin cezası verilmesini talep edebilir"],
        "TTK m.128/7 şirkete sermaye borcunun ifasını isteme ve dava etme hakkı verir. Gecikme zararının tazmini talebi bakımından ihtar koşulu aranır.",
        "Şirket sermaye borcunu takip edebilir ve gecikme zararını isteyebilir. Kanun, tazminat talebini ayrıca ihtar şartına bağlamıştır.",
        "6102 sayılı TTK m.128/7", "hard",
    ),
    r(
        "Ortağın taahhüt ettiği para sermaye zamanında ödenmemiştir. Şirket sözleşmesinde aksine hüküm bulunmadığına göre temerrüt faizinin başlangıcı nasıl belirlenir?",
        "Zamanında ifa edilmeyen para sermaye için, aksine sözleşme hükmü yoksa temerrüt faizi hangi andan itibaren işler?",
        "Para sermaye için şirketin tescili anından itibaren temerrüt faizi işler",
        ["Temerrüt faizi ancak ilk genel kurulun yapılmasından bir yıl sonra işler", "Faiz yalnız ortağın şirketten ayrıldığı tarihten itibaren işlemeye başlar", "Para sermayede temerrüt faizi hiçbir koşulda istenemez", "Faiz ancak şirket tasfiyeye girdiğinde geçmişe etkili olarak doğar"],
        "TTK m.129, zamanında ifa edilmeyen para sermayede aksine sözleşme hükmü yoksa şirketin tescili anından itibaren temerrüt faizi öngörür.",
        "Para sermaye borcundaki faiz başlangıcı, genel kural olarak şirketin tescil anıdır. Bu hak gecikme zararına ilişkin tazminat hakkını ortadan kaldırmaz.",
        "6102 sayılı TTK m.129", "medium",
    ),
    r(
        "Bir ortak, üçüncü kişiden olan alacağını şirkete sermaye olarak devretmiştir. Alacak henüz şirketçe tahsil edilememiştir. Ortağın sermaye borcu bakımından hangisi doğrudur?",
        "Alacağını sermaye olarak şirkete devreden ortak hangi anda sermaye koyma borcundan kurtulur?",
        "Devredilen alacak tahsil edilmedikçe ortağın sermaye borcu sona ermez",
        ["Alacağın varlığını sözlü bildirdiği anda ortak sermaye borcundan kurtulur", "Şirket alacağı tahsil etmese de devir vaadiyle borç kendiliğinden sona erer", "Ortak yalnız borçlunun adresini vererek sermaye borcunu tamamen ifa eder", "Alacağın vadesi geldiğinde tahsil sonucu aranmadan borç silinir"],
        "TTK m.130/1, alacağını sermaye olarak devreden ortağın ancak alacak şirketçe tahsil edildiğinde sermaye borcundan kurtulacağını düzenler.",
        "Alacağın şirkete devredilmiş olması tek başına tam ifa sonucu doğurmaz. Tahsil riski, Kanundaki düzenleme gereği sermaye koyan ortak üzerinde kalır.",
        "6102 sayılı TTK m.130/1", "medium",
    ),
    r(
        "Bir kollektif şirket ortağının kişisel alacaklısı, şirket devam ederken doğrudan şirket malvarlığındaki belirli bir makineyi haczettirmek istemektedir. TTK m.133 bakımından hangisi doğrudur?",
        "Şahıs şirketi devam ederken ortağın kişisel alacaklısı alacağını öncelikle hangi şirket kaynaklı değer üzerinden takip edebilir?",
        "Kişisel alacaklı, ortağa bilanço gereğince düşen kâr payına yönelebilir",
        ["Kişisel alacaklı şirketin dilediği taşınmazını doğrudan kendi adına tescil ettirebilir", "Alacaklı diğer ortakların bütün kişisel mallarını koşulsuz haczettirebilir", "Alacaklı şirket unvanını satarak borcu tek taraflı biçimde sona erdirebilir", "Alacaklı şirketin müşterilerinden olan tüm alacakları kendiliğinden devralır"],
        "TTK m.133/1'e göre şahıs şirketi devam ederken kişisel alacaklı, borçlu ortağa bilanço gereğince düşen kâr payından; fesihte tasfiye payından alacağını alabilir.",
        "Şirket malvarlığı ortağın kişisel malvarlığından ayrıdır. Kişisel alacaklı şirket sürerken doğrudan belirli şirket malına değil, borçlu ortağın kâr payına yönelir.",
        "6102 sayılı TTK m.133/1", "hard",
    ),
    r(
        "Üç tüzel kişi, ticari işletme işletmek amacıyla kollektif şirket kurmak istemektedir. Kollektif şirketin tanımı bakımından bu kuruluş mümkün müdür?",
        "Kollektif şirket ortaklarının kişi türü ve sorumluluğu bakımından doğru ifade hangisidir?",
        "Kollektif şirket gerçek kişiler arasında kurulur ve ortak sorumluluğu sınırlanmamıştır",
        ["Kollektif şirket yalnız tüzel kişiler arasında kurulur ve sorumluluk payla sınırlıdır", "Kollektif şirkette ortakların tamamı yalnız koydukları sermayeyle sorumludur", "Kollektif şirket tek bir kamu tüzel kişisi tarafından kurulabilen sermaye şirketidir", "Kollektif şirkette ortak kişiliği önemsizdir ve halka arz zorunludur"],
        "TTK m.211'e göre kollektif şirket, ticari işletmeyi unvan altında işletmek amacıyla gerçek kişiler arasında kurulur; ortakların şirket alacaklılarına karşı sorumluluğu sınırlanmamıştır.",
        "Kollektif şirkette ortaklar yalnız gerçek kişi olabilir. Bu şahıs şirketinde ortaklardan hiçbirinin dış sorumluluğu belirli sermaye tutarıyla sınırlandırılmış değildir.",
        "6102 sayılı TTK m.211", "easy",
    ),
    r(
        "Kollektif şirket kurucuları sözleşmeyi yalnız sözlü olarak yapmış ve hemen tescil istemiştir. Şirket sözleşmesinin şekli bakımından hangisi doğrudur?",
        "Kollektif şirket sözleşmesinin geçerli kuruluş şekli aşağıdakilerden hangisidir?",
        "Sözleşme yazılı; imzalar noter onaylı veya sicil görevlisi huzurunda olmalıdır",
        ["Sözleşmenin sözlü yapılması ve ortaklardan birinin tanıklığı her durumda yeterlidir", "Sözleşme yalnız vergi dairesinde sözlü beyanla kurulabilir", "Sözleşmenin geçerliliği ilk satış faturasının düzenlenmesine bağlıdır", "Sözleşme biçimsiz kurulabilir; tescil ve imza hiçbir zaman aranmaz"],
        "TTK m.212 kollektif şirket sözleşmesini yazılı şekle bağlar; imzaların noter onayı veya ticaret sicili müdürü ya da yardımcısı huzurunda atılması gerekir.",
        "Kollektif şirket sözleşmesinde yazılı metin tek başına yeterli değildir; imzalar için Kanunda gösterilen noter veya sicil huzuru usulü de yerine getirilmelidir.",
        "6102 sayılı TTK m.212", "medium",
    ),
    r(
        "Kollektif şirket kurucuları tescil yükümlülüğünü yerine getirmeden şirket unvanıyla üçüncü kişilerle işlemlere başlamıştır. Bu işlemlerden doğan sorumluluk bakımından hangisi doğrudur?",
        "Kollektif şirket tescil edilmeden şirket adına faaliyete başlanırsa ortakların üçüncü kişilere karşı sorumluluğu nasıl olur?",
        "Ortaklar üçüncü kişilere karşı müteselsilen sorumlu olur",
        ["Hiçbir ortak sorumlu olmaz; bütün işlemler yok hükmünde sayılır", "Yalnız en az sermaye koyan ortak sorumlu tutulabilir", "Sorumluluk sadece şirket tescil edildikten sonraki işlemlere yayılır", "Üçüncü kişiler yalnız ticaret sicili müdürlüğünden zarar isteyebilir"],
        "TTK m.216/1, tescil yükümlülüğü yerine getirilmeden şirket adına işlere başlanırsa ortakları bu işlerden üçüncü kişilere karşı müteselsilen sorumlu tutar.",
        "Tescil öncesi faaliyetin riski üçüncü kişiye yüklenmez. Kanun, işleme giren ortakların birlikte ve zincirleme sorumluluğunu kabul eder.",
        "6102 sayılı TTK m.216/1", "medium",
    ),
    r(
        "Bir şirkette bazı ortakların şirket alacaklılarına karşı sorumluluğu sınırlandırılmamış, diğer ortaklarınki belirli sermayeyle sınırlandırılmıştır. Bu yapı hangi şirket türünü tanımlar?",
        "Komandite ve komanditer ortakların birlikte bulunduğu şirket türü aşağıdakilerden hangisidir?",
        "Bu sorumluluk yapısı adi komandit şirketi tanımlar",
        ["Bu yapı bütün ortakları sınırlı sorumlu kollektif şirketi tanımlar", "Bu yapı ortak içermeyen tek kişilik anonim şirketi tanımlar", "Bu yapı tüzel kişiliği olmayan acentelik sözleşmesini tanımlar", "Bu yapı yalnız kamu idaresince kurulabilen kooperatifi tanımlar"],
        "TTK m.304/1 komandit şirketi, komandite ortakların sınırsız ve komanditer ortakların belirli sermayeyle sınırlı sorumlu olduğu şirket olarak tanımlar.",
        "Komandit şirketin ayırt edici yönü iki farklı sorumluluk grubudur: komandite ortak sınırsız, komanditer ortak koyduğu sermaye çevresinde sınırlı sorumludur.",
        "6102 sayılı TTK m.304/1-2", "easy",
    ),
    r(
        "Bir limited şirket, adi komandit şirkete komandite ortak olmak istemektedir. Ortakların kişi türüne ilişkin kural bakımından hangisi doğrudur?",
        "Adi komandit şirkette komandite ve komanditer ortakların gerçek veya tüzel kişi olabilmesi bakımından doğru ifade hangisidir?",
        "Komandite ortak gerçek kişi olmalı; tüzel kişi ancak komanditer olabilir",
        ["Komandite ortak yalnız tüzel kişi olabilir; gerçek kişiler komanditer olamaz", "Her iki ortak türü de yalnız kamu tüzel kişilerinden oluşabilir", "Komanditer ortak mutlaka gerçek kişi, komandite ortak mutlaka dernek olmalıdır", "Ortakların kişi türü bakımından Kanunda hiçbir ayrım yapılmamıştır"],
        "TTK m.304/3 komandite ortakların gerçek kişi olmasını zorunlu tutar. Tüzel kişiler adi komandit şirkette ancak komanditer ortak olabilir.",
        "Sınırsız sorumluluk taşıyan komandite sıfatı tüzel kişilere kapalıdır. Tüzel kişi katılımı, sorumluluğu sınırlı komanditer ortaklıkla mümkündür.",
        "6102 sayılı TTK m.304/3", "medium",
    ),
    r(
        "Komanditer ortak, sermaye taahhüdünü ticari itibarıyla yerine getirmek istemektedir. Komanditerin sermaye koyma borcu bakımından hangisi doğrudur?",
        "Adi komandit şirkette komanditer ortağın sermaye olarak koyamayacağı değerlerden biri hangisidir?",
        "Komanditer kişisel emeğini ve ticari itibarını sermaye olarak koyamaz",
        ["Komanditer devredilebilir taşınırını hiçbir durumda sermaye olarak koyamaz", "Komanditer nakit para koyarsa ortak sıfatını kendiliğinden kaybeder", "Komanditer ekonomik değer taşıyan alacağını sermaye yapamaz", "Komanditer devredilebilir fikrî hakkı hiçbir koşulda şirkete özgüleyemez"],
        "TTK m.307/2, komanditerin kişisel emeğini ve ticari itibarını sermaye olarak koymasını yasaklar. Diğer değerler genel ve özel kurallar çerçevesinde değerlendirilebilir.",
        "Komanditerin sorumluluk sınırının belirlenebilir olması gerekir. Bu nedenle kişisel emek ile ticari itibar komanditer sermayesi olarak kabul edilmez.",
        "6102 sayılı TTK m.307/2", "easy",
    ),
    r(
        "Şirket sözleşmesinin başlığında 'komandit' yazmasına rağmen hükümler sorumluluk ayrımını göstermemektedir. Şirket türünün belirlenmesi bakımından hangisi doğrudur?",
        "Bir şirketin komandit olup olmadığının belirlenmesinde esas alınacak ölçüt aşağıdakilerden hangisidir?",
        "Şirket türünde sözleşme hükümleri esastır; verilen ad tek başına yeterli değildir",
        ["Şirketin türünü yalnız kurucuların sözlü olarak kullandığı ad kesin biçimde belirler", "Şirket türü ilk faturada yazılan ibareye göre değiştirilemez biçimde doğar", "Ortakların sorumluluk hükümleri türün belirlenmesinde hiçbir önem taşımaz", "Şirket adı komandit ise sözleşmenin bütün hükümleri inceleme dışı kalır"],
        "TTK m.306/1, komandit niteliğin sözleşme hükümlerine göre belirlenmesini emreder; ortakların şirkete verdiği ad ve nitelik tek başına yeterli değildir.",
        "Şirket türü etikete değil hukuki yapıya, özellikle sözleşmedeki sorumluluk düzenine göre saptanır. Adlandırma içeriğe aykırılığı örtemez.",
        "6102 sayılı TTK m.306/1", "medium",
    ),
    r(
        "Sözleşme hükümleri incelendiğinde şirketin komandit olduğu açıkça saptanamamaktadır. TTK m.306/2 uyarınca şirket hangi türde kabul edilir?",
        "Bir şirketin adi komandit niteliği sözleşmeden açıkça belirlenemiyorsa uygulanacak kanuni karine hangisidir?",
        "Komandit nitelik açıkça saptanamıyorsa şirket kollektif sayılır",
        ["Belirsizlikte şirket anonim şirket sayılır ve pay ihraç etmiş kabul edilir", "Belirsizlik şirketi tüzel kişiliği olmayan acenteliğe dönüştürür", "Şirket kendiliğinden limited şirket olur ve ortak sayısı elliye çıkar", "Şirket hiçbir hukuki ilişki doğurmayan adi işlem sayılır"],
        "TTK m.306/2, şirketin komandit olduğunun açıkça saptanamaması hâlinde kollektif şirket sayılacağını düzenler.",
        "Komanditer sorumluluk sınırlaması açıkça kurulmamışsa belirsizlik sınırlı sorumluluk lehine yorumlanmaz; kollektif şirket sonucu doğar.",
        "6102 sayılı TTK m.306/2", "medium",
    ),
    r(
        "Anonim şirketin önemli bir borcu ödenmemiştir. Alacaklı, pay sahibinden taahhüt ettiği sermayeyi aşan şirket borcunun tamamını istemektedir. Hangisi doğrudur?",
        "Anonim şirkette şirket ve pay sahiplerinin borçlardan sorumluluğu bakımından doğru ifade hangisidir?",
        "Şirket malvarlığıyla; pay sahibi yalnız taahhüt ettiği sermaye payıyla şirkete karşı sorumludur",
        ["Pay sahipleri bütün şirket borçlarından alacaklılara karşı sınırsız ve müteselsil sorumludur", "Anonim şirket borçlarından yalnız yönetim kurulu başkanı kişisel malvarlığıyla sorumludur", "Şirket hiçbir borçtan sorumlu değildir; tüm borçlar çalışanlara geçer", "Pay sahibi sermaye borcunu ödese de şirketin her borcunu ayrıca ödemek zorundadır"],
        "TTK m.329 anonim şirketi borçlarından yalnız malvarlığıyla sorumlu şirket olarak tanımlar. Pay sahibi ise taahhüt ettiği sermaye payıyla ve şirkete karşı sorumludur.",
        "Anonim şirkette alacaklı kural olarak şirket malvarlığına yönelir. Pay sahibinin sermaye taahhüdü dışındaki şirket borcundan doğrudan sınırsız sorumluluğu yoktur.",
        "6102 sayılı TTK m.329", "medium",
    ),
    r(
        "Bir anonim şirketin esas sözleşmesi, yönetim kurulunun üç pay sahibi gerçek kişiden oluşmasını zorunlu tutmadığı hâlde tek bir tüzel kişiyi üye seçmiştir. TTK m.359 bakımından hangisi doğrudur?",
        "Anonim şirket yönetim kurulunun üye sayısı ve tüzel kişi üyelik bakımından kanuni yapısı nasıldır?",
        "Yönetim kurulu bir veya daha fazla gerçek ya da tüzel kişiden oluşabilir",
        ["Yönetim kurulu mutlaka en az beş pay sahibi gerçek kişiden oluşmalıdır", "Tüzel kişiler hiçbir durumda yönetim kurulu üyesi seçilemez", "Yönetim kurulu yalnız şirket çalışanlarından ve en az yedi kişiden oluşur", "Tek üyeli yönetim kurulu sadece halka açık şirketlerde mümkündür"],
        "TTK m.359/1, anonim şirket yönetim kurulunun esas sözleşmeyle atanmış veya genel kurulca seçilmiş bir ya da daha fazla kişiden oluşmasını ve tüzel kişinin üye olabilmesini kabul eder.",
        "Kanun tek üyeli yönetim kuruluna ve tüzel kişi üyeliğe izin verir. Tüzel kişi seçildiğinde onun adına hareket edecek gerçek kişi tescil ve ilan edilir.",
        "6102 sayılı TTK m.359/1-2", "medium",
    ),
    r(
        "Limited şirket ortağı, şirketin üçüncü kişiye olan sözleşme borcunun tamamından sırf ortak sıfatıyla kişisel olarak sorumlu tutulmuştur. TTK m.573 bakımından hangisi doğrudur?",
        "Limited şirket ortaklarının şirket borçları ve şirkete karşı yükümlülükleri bakımından temel kural hangisidir?",
        "Ortak şirket borcundan sorumlu değildir; sermaye, ek ödeme ve yan edim yükümlülüklerini yerine getirir",
        ["Ortak şirketin bütün borçlarından alacaklılara karşı sınırsız ve zincirleme sorumludur", "Ortağın tek yükümlülüğü şirket çalışanlarının ücretini kişisel malından ödemektir", "Ortak sermaye taahhüdünü yerine getirse de her şirket borcunu eşit payla üstlenir", "Limited şirkette şirket malvarlığı bulunmadığından borçların tamamı müdüre aittir"],
        "TTK m.573/2 ortakları şirket borçlarından sorumlu tutmaz; taahhüt edilen esas sermaye payı ile sözleşmede öngörülen ek ödeme ve yan edim yükümlülüklerini şirkete karşı düzenler.",
        "Limited şirketin borçlusu tüzel kişiliğin kendisidir. Ortağın temel borçları sermaye taahhüdü ve varsa şirket sözleşmesindeki ek ödeme ile yan edimlerdir.",
        "6102 sayılı TTK m.573/2", "medium",
    ),
    r(
        "Kurucular, yetmiş ortaklı bir limited şirketi tek sözleşmeyle kurmak istemektedir. Ortak sayısı bakımından bu plan nasıl değerlendirilir?",
        "Limited şirkette ortak sayısının kanuni üst sınırı aşağıdakilerden hangisidir?",
        "Limited şirkette ortak sayısı elliyi aşamaz",
        ["Limited şirkette ortak sayısı beşi aşamaz", "Limited şirkette en az elli bir ortak bulunması zorunludur", "Limited şirkette ortak sayısı için hiçbir üst sınır yoktur", "Limited şirket yalnız tek ortakla kurulabilir ve sonradan ortak alamaz"],
        "TTK m.574/1 limited şirkette ortak sayısının elliyi aşamayacağını emredici biçimde düzenler. Yetmiş ortaklı kuruluş bu sınıra uymaz.",
        "Limited şirket bir veya daha çok ortakla kurulabilir; ancak ortak sayısı ellinin üzerine çıkamaz. Tek ortaklı kuruluş da mümkündür.",
        "6102 sayılı TTK m.574/1", "easy",
    ),
    r(
        "Limited şirket esas sermaye payı yazılı bir sözleşmeyle devredilmiş, ancak taraf imzaları noterce onanmamış ve şirket sözleşmesinde aksi olmadığı hâlde genel kurul onayı da alınmamıştır. Hangisi doğrudur?",
        "Limited şirkette esas sermaye payının iradi devrinde kural olarak aranan şekil ve şirket içi onay hangisidir?",
        "Devir yazılı ve imzalar noter onaylı olmalı; kural olarak genel kurul da onay vermelidir",
        ["Devir yalnız sözlü beyanla yapılır ve hiçbir şirket organının onayı aranmaz", "Devir ticaret siciline telefonla bildirilince şekil eksikleri tamamen giderilir", "Pay devri ancak şirket tasfiyeye girdikten sonra ve mahkeme kararıyla yapılabilir", "Devir için yalnız müdürün e-postası yeterlidir; yazılı sözleşme kurulamaz"],
        "TTK m.595/1 pay devri ve devir borcunu doğuran işlemleri yazılı, imzaları noter onaylı şekle bağlar. Sözleşmede aksi yoksa m.595/2 gereği genel kurul onayıyla devir geçerli olur.",
        "Limited pay devrinde hem kanuni yazılı-noter onaylı şekil hem de kural olarak genel kurul onayı aranır. Şirket sözleşmesi onay kuralında farklı düzenleme yapabilir.",
        "6102 sayılı TTK m.595/1-2", "hard",
    ),
    r(
        "Limited şirket sözleşmesi yönetim ve temsili ortak olmayan bir üçüncü kişiye vermiş; hiçbir ortağa yönetim ve temsil yetkisi bırakmamıştır. TTK m.623 bakımından hangisi doğrudur?",
        "Limited şirketin yönetim ve temsilinin üçüncü kişilere bırakılması hâlinde ortaklardan biri bakımından korunması gereken asgari yetki nedir?",
        "En az bir ortağın şirketi yönetim hakkı ve temsil yetkisi bulunmalıdır",
        ["Bütün ortakların yönetim ve temsil yetkisinden tamamen yoksun bırakılması zorunludur", "Yalnız en yüksek sermayeli ortağın denetçi olması yeterlidir", "Her ortağın ayrı ayrı sınırsız temsil yetkisine sahip olması zorunludur", "Yönetim yalnız ticaret sicili müdürlüğünce dışarıdan atanan kişiye verilebilir"],
        "TTK m.623/1 yönetim ve temsilin müdür sıfatıyla ortaklara, tüm ortaklara veya üçüncü kişilere verilebilmesine izin verir; ancak en az bir ortak yönetim ve temsil yetkisine sahip olmalıdır.",
        "Profesyonel üçüncü kişi müdür mümkündür fakat ortakların tamamı yönetim ve temsilden dışlanamaz. Kanun en az bir ortak için her iki yetkiyi korur.",
        "6102 sayılı TTK m.623/1", "medium",
    ),
]


PREMISES = [
    {
        "stem": "Ticaret şirketlerinin genel yapısıyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ticaret şirketleri tüzel kişiliğe sahiptir.\n\nII. Kollektif ve komandit şirketler şahıs şirketidir.\n\nIII. Anonim ve limited şirketler sermaye şirketidir.",
        "correct": "I, II ve III",
        "why": "TTK m.124/2 şirketleri şahıs ve sermaye şirketleri olarak sınıflandırır; m.125/1 bütün ticaret şirketlerine tüzel kişilik tanır. Üç ifade de doğrudur.",
        "ref": "6102 sayılı TTK m.124/2 ve 125/1",
        "difficulty": "medium",
    },
    {
        "stem": "Sermaye koyma borcuyla ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ortak, sözleşmedeki taahhüdü nedeniyle şirkete karşı borçludur.\n\nII. Şirket sermaye borcunun ifasını dava edebilir.\n\nIII. Gecikme zararının tazmini için ihtar şartı aranır.",
        "correct": "I, II ve III",
        "why": "TTK m.128/1 sermaye borcunu şirkete karşı kurar; m.128/7 şirkete ifa ve dava hakkı verir, gecikme zararına ilişkin tazminat istemini ise ihtara bağlar.",
        "ref": "6102 sayılı TTK m.128/1 ve 128/7",
        "difficulty": "hard",
    },
    {
        "stem": "Kollektif şirketle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ortakları gerçek kişi olmalıdır.\n\nII. Ortakların şirket alacaklılarına karşı sorumluluğu sınırlanmamıştır.\n\nIII. Şirket yalnız tek ortakla kurulabilir.",
        "correct": "I ve II",
        "why": "TTK m.211 kollektif şirketi gerçek kişiler arasında kurulan ve ortak sorumluluğu sınırlanmayan şirket olarak tanımlar. Tanım birden çok gerçek kişiyi gerektirir; III yanlıştır.",
        "ref": "6102 sayılı TTK m.211",
        "difficulty": "easy",
    },
    {
        "stem": "Adi komandit şirketle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Komandite ortak gerçek kişi olmalıdır.\n\nII. Tüzel kişi komanditer ortak olabilir.\n\nIII. Komanditer kişisel emeğini sermaye olarak koyabilir.",
        "correct": "I ve II",
        "why": "TTK m.304/3 komanditeyi gerçek kişiyle sınırlar ve tüzel kişiye komanditerliği açar. TTK m.307/2 komanditerin kişisel emeğini ve ticari itibarını sermaye koymasını yasaklar.",
        "ref": "6102 sayılı TTK m.304/3 ve 307/2",
        "difficulty": "medium",
    },
    {
        "stem": "Anonim şirketle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Şirket borçlarından yalnız malvarlığıyla sorumludur.\n\nII. Pay sahipleri taahhüt ettikleri sermaye payıyla şirkete karşı sorumludur.\n\nIII. Yönetim kurulunun en az beş pay sahibi gerçek kişiden oluşması zorunludur.",
        "correct": "I ve II",
        "why": "I ve II TTK m.329'daki sorumluluk düzenini yansıtır. TTK m.359 yönetim kurulunun bir veya daha fazla gerçek ya da tüzel kişiden oluşmasına izin verdiğinden III yanlıştır.",
        "ref": "6102 sayılı TTK m.329 ve 359",
        "difficulty": "medium",
    },
    {
        "stem": "Limited şirket pay devriyle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Devir için tarafların sözlü anlaşması tek başına yeterlidir.\n\nII. Tarafların imzaları noterce onanmalıdır.\n\nIII. Şirket sözleşmesinde aksi yoksa genel kurul onayı gerekir.",
        "correct": "II ve III",
        "why": "TTK m.595/1-2 uyarınca imzaların noter onayı ve kural olarak genel kurul onayı gerekir; II ve III doğrudur. Sözlü anlaşma yeterli değildir, I yanlıştır.",
        "ref": "6102 sayılı TTK m.595/1-2",
        "difficulty": "hard",
    },
    {
        "stem": "Limited şirketin yönetimiyle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Yönetim ve temsil üçüncü kişiye verilebilir.\n\nII. Ortakların tamamı yönetim hakkı ve temsil yetkisinden yoksun bırakılmalıdır.\n\nIII. Tüzel kişi müdür olursa adına görevi yapacak gerçek kişiyi belirler.",
        "correct": "I ve III",
        "why": "TTK m.623 üçüncü kişi müdüre ve tüzel kişi müdüre izin verdiğinden I ve III doğrudur. En az bir ortağın yönetim hakkı ile temsil yetkisi bulunmalıdır; II yanlıştır.",
        "ref": "6102 sayılı TTK m.623/1-2",
        "difficulty": "hard",
    },
    {
        "stem": "Ticaret şirketlerinde sermaye olarak konulabilecek değerlerle ilgili aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Devredilebilir ve nakden değerlendirilebilir fikrî hak sermaye olabilir.\n\nII. Taşınır ve taşınmazlar genel olarak sermaye olabilir.\n\nIII. Devri hukuken yasak kişiye bağlı haklar her şirket türünde sermaye olabilir.",
        "correct": "I ve II",
        "why": "TTK m.127 devredilebilir ve ekonomik değer taşıyan fikrî haklarla taşınır ve taşınmazları genel olarak kabul eder. Devredilemeyen kişiye bağlı haklar bu nitelikleri taşımaz; III yanlıştır.",
        "ref": "6102 sayılı TTK m.127/1",
        "difficulty": "medium",
    },
]


WRONG_BANKS = {"unused": ["a", "b", "c", "d", "e", "f"]}


if __name__ == "__main__":
    write_topic(
        lesson_id="ticaret_hukuku",
        topic_id="ticaret_sirketleri",
        label="Ticaret Şirketleri",
        slug="ticaret_sirketleri",
        prefix="kh-tic-sir",
        seed=20260722,
        legislation_version="6102 sayılı TTK — 17.07.2026 güncel metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks=WRONG_BANKS,
    )
