#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SMMM Vergi Mevzuatı — Vergi Cezaları, 3×20."""
from topic_pack_builder import write_topic


def r(scenario, focus, correct, focus_correct, distractors, focus_distractors,
      why, focus_why, ref, difficulty="medium"):
    return {
        "scenario": scenario, "focus": focus,
        "correct": correct, "focus_correct": focus_correct,
        "distractors": list(distractors),
        "focus_distractors": list(focus_distractors),
        "why": why, "focus_why": focus_why, "ref": ref,
        "difficulty": difficulty,
    }


RULES = [
    r(
        "Mükellef vergi kanununun şekle ilişkin hükmüne aykırı davranmıştır. VUK'un ceza sistemi bakımından hangi yaptırım grupları gündeme gelebilir?",
        "VUK'ta vergi cezaları adı altında sayılan iki temel idari ceza türü hangileridir?",
        "Vergi cezaları ve diğer kanuni cezalar",
        "Vergi ziyaı ve usulsüzlük cezaları",
        ["Yalnız disiplin ve ruhsat yaptırımları", "Yalnız medeni tazminat sorumluluğu", "Sadece faaliyet izninin iptal edilmesi", "Yalnız meslekten çıkarma yaptırımı"],
        ["Hapis ve adli para cezaları", "Tazminat ve faiz cezaları", "Disiplin ve ruhsat cezaları", "İptal ve tam yargı cezaları"],
        "VUK, aykırı hareketleri vergi ziyaı cezası, usulsüzlük cezaları ve kanunda öngörülen diğer cezalarla karşılar.",
        "Vergi ziyaı cezası ve usulsüzlük cezaları VUK'un temel idari vergi cezası türleridir.",
        "213 sayılı VUK m. 331",
        "easy",
    ),
    r(
        "Vesayet altındaki kişinin vergisel işlerini yürüten vasi, bu kişi adına vergi kanununa aykırı davranmıştır. Vergi cezasının muhatabı kimdir?",
        "Velayet altındaki çocuk adına velinin vergi kanununa aykırı hareketinde ceza kimin adına kesilir?",
        "Vasi",
        "Veli",
        ["Vesayet altındaki kişi", "Vergi dairesi müdürü", "Sulh hukuk mahkemesi", "Kayyım olmayan akraba"],
        ["Çocuk", "Vergi sorumlusunun çalışanı", "Okul yönetimi", "Aile mahkemesi"],
        "Vesayet altındaki kişi, vasisinin kendisine izafeten yaptığı aykırı hareketten dolayı ceza muhatabı olmaz; ceza vasiye yönelir.",
        "Velinin çocuğa izafeten yaptığı vergi kanununa aykırı hareketin ceza muhatabı velidir.",
        "213 sayılı VUK m. 332",
        "easy",
    ),
    r(
        "Limited şirketin idaresi sırasında vergi kanununa aykırı işlem yapılmıştır. İdari vergi cezası kimin adına kesilir?",
        "Tüzel kişi bünyesinde VUK m. 359 kapsamındaki fiili bizzat işleyen kişi hakkında hapis cezası yönünden hangi esas uygulanır?",
        "Tüzel kişi adına",
        "Ceza fiili işleyen kişi hakkında hükmolunur",
        ["Her ortağa eşit olarak", "Yalnız şirket müdürünün eşine", "Ticaret sicili müdürlüğüne", "Şirketin bütün müşterilerine"],
        ["Hapis cezası tüzel kişi adına hükmolunur", "Ceza yalnız vergi dairesine uygulanır", "Fiili işleyen hiçbir şekilde sorumlu olmaz", "Ceza bütün ortaklara otomatik dağıtılır"],
        "Tüzel kişilerin idare ve tasfiyesindeki aykırılıklardan doğan idari vergi cezaları tüzel kişi adına kesilir.",
        "Kaçakçılık fiillerine ilişkin ceza, tüzel kişilik yerine fiili işleyen gerçek kişi hakkında hükmolunur.",
        "213 sayılı VUK m. 333",
        "medium",
    ),
    r(
        "Tek bir fiil hem KDV'nin hem gelir vergisinin ziyaa uğramasına neden olmuştur. Vergi ziyaı cezası nasıl uygulanır?",
        "Tek fiille farklı türden birkaç verginin ziyaa uğratılmasında temel ceza ilkesi hangisidir?",
        "Her vergi türü için ayrı ceza kesilir",
        "Her vergi bakımından ayrı ceza",
        ["Yalnız KDV için ceza kesilir", "Tek ve en düşük ceza kesilir", "Hiçbir vergi için ceza kesilmez", "Yalnız gelir vergisi için ceza kesilir"],
        ["Bütün vergiler için tek ceza", "Yalnız en yüksek vergi için ceza", "Yalnız en düşük vergi için ceza", "Vergilerin ortalaması kadar ceza"],
        "Tek fiil farklı vergi türlerinde ziya doğurmuşsa her vergi yönünden ayrı vergi ziyaı cezası kesilir.",
        "Farklı vergi türlerinin her biri için ziya ve ceza ayrı değerlendirilir.",
        "213 sayılı VUK m. 335",
        "medium",
    ),
    r(
        "Aynı fiil hem vergi ziyaı cezasını hem genel usulsüzlük cezasını gerektirmektedir. VUK'a göre hangi ceza kesilir?",
        "Tek fiilde vergi ziyaı ile genel usulsüzlüğün birleşmesinde uygulanan ilke hangisidir?",
        "Ağır olan ceza",
        "Yalnız ağır olan ceza",
        ["İki cezanın toplamı", "Yalnız usulsüzlük cezası", "Her iki cezanın yarısı", "Hiçbir ceza"],
        ["Her iki cezanın toplamı", "Daima vergi ziyaı cezası", "Daima usulsüzlük cezası", "İki cezanın aritmetik ortalaması"],
        "Tek fiilin vergi ziyaı ve genel usulsüzlük oluşturması hâlinde yalnız miktar bakımından ağır ceza kesilir.",
        "VUK m. 336, aynı fiilden doğan vergi ziyaı ve genel usulsüzlük cezalarında ağır olanın uygulanmasını öngörür.",
        "213 sayılı VUK m. 336",
        "medium",
    ),
    r(
        "Mükellef birbirinden bağımsız iki işlemle iki ayrı vergi ziyaına sebep olmuştur. Ceza nasıl belirlenir?",
        "Aynı takvim yılında aynı tür genel usulsüzlüğün birden fazla işlenmesinde, birinciden sonraki her fiil için hangi oran uygulanır?",
        "Her fiil için ayrı ceza kesilir",
        "İlk cezanın dörtte biri",
        ["Fiiller tek cezada birleştirilir", "Yalnız ikinci fiil cezalandırılır", "Yalnız ilk fiil cezalandırılır", "İki fiil de cezasız kalır"],
        ["Birinci cezanın tamamı", "Birinci cezanın yarısı", "Birinci cezanın iki katı", "Birinci cezanın üç katı"],
        "Ayrı ayrı işlenen vergi ziyaı veya usulsüzlük fiilleri için kural olarak ayrı ceza kesilir.",
        "VUK m. 352 kapsamındaki aynı tür genel usulsüzlük aynı takvim yılında yinelenirse birinciden sonrakilerin her biri için ilk cezanın dörtte biri kesilir.",
        "213 sayılı VUK m. 337",
        "hard",
    ),
    r(
        "Kesinleşen vergi ziyaı cezasından sonra kanundaki süre içinde yeniden vergi ziyaı cezası kesilmiştir. Tekerrür artırım oranı nedir?",
        "Kesinleşen usulsüzlük cezasından sonra kanundaki tekerrür süresinde yeniden usulsüzlük cezası kesilirse ceza hangi oranda artırılır?",
        "Yüzde elli",
        "Yüzde yirmi beş",
        ["Yüzde on", "Yüzde yirmi beş", "Yüzde yetmiş beş", "Yüzde yüz"],
        ["Yüzde on", "Yüzde elli", "Yüzde yetmiş beş", "Yüzde yüz"],
        "Vergi ziyaı cezasında tekerrür artırımı yüzde ellidir; artırım tutarı kanundaki üst sınırı aşamaz.",
        "Usulsüzlük cezasında tekerrür artırımı yüzde yirmi beştir.",
        "213 sayılı VUK m. 339",
        "medium",
    ),
    r(
        "Bir fiil hem VUK m. 359 kapsamında kaçakçılık suçu hem vergi ziyaı oluşturmuştur. Hapis cezası süreci idari vergi cezasını engeller mi?",
        "Kaçakçılık fiili için vergi ziyaı cezası kesilmesi, ceza soruşturması bakımından hangi sonucu doğurur?",
        "Hayır; yaptırımlar ayrıca uygulanır",
        "Ceza soruşturmasına engel olmaz",
        ["Evet; yalnız hapis cezası uygulanır", "Evet; yalnız vergi cezası uygulanır", "Evet; mükellef istediğini seçer", "Hayır; fakat iki ceza da yarıya iner"],
        ["Soruşturmayı kendiliğinden sona erdirir", "Kaçakçılık fiilini usulsüzlüğe dönüştürür", "Savcılığın görevini vergi dairesine geçirir", "Hapis cezasını idari para cezasına çevirir"],
        "Aynı fiil için idari vergi cezası ile kaçakçılık suçuna ilişkin ceza süreci birbirine engel değildir.",
        "Vergi ziyaı cezasının kesilmesi, m. 359 kapsamındaki suç yönünden takip yapılmasını ortadan kaldırmaz.",
        "213 sayılı VUK m. 340 ve 367",
        "medium",
    ),
    r(
        "Mükellefin ödevini eksik yerine getirmesi nedeniyle vergi zamanında eksik tahakkuk etmiştir. Bu sonuç hangi kavramı oluşturur?",
        "Vergi ziyaının temel unsuru aşağıdakilerden hangisidir?",
        "Vergi ziyaı",
        "Verginin zamanında tahakkuk etmemesi veya eksik tahakkuku",
        ["Genel tebliğ", "Vergi mahremiyeti", "Mücbir sebep", "Özel hesap dönemi"],
        ["Verginin süresinde ve eksiksiz tahakkuk ettirilmesi", "Yalnız muhasebe kârının azalması", "Mükellefin adresini zamanında bildirmesi", "İhtirazi kayıtla beyanname verilmesi"],
        "Vergisel ödevin geç veya eksik yerine getirilmesi yüzünden verginin zamanında tahakkuk etmemesi ya da eksik tahakkuku vergi ziyaıdır.",
        "Tahakkukun zamanında ve tam gerçekleşmemesi, vergi ziyaı tanımının merkezindeki sonuçtur.",
        "213 sayılı VUK m. 341",
        "easy",
    ),
    r(
        "Eksik tahakkuk eden vergi daha sonra tamamlanmıştır. Bu tamamlama, daha önce oluşan vergi ziyaı cezasını kendiliğinden ortadan kaldırır mı?",
        "Haksız vergi iadesinin sonradan geri alınması, vergi ziyaı cezasına nasıl etki eder?",
        "Hayır; cezaya engel olmaz",
        "Ceza uygulanmasına engel olmaz",
        ["Evet; ceza kendiliğinden düşer", "Evet; fiil usulsüzlüğe dönüşür", "Hayır; ceza iki katına çıkar", "Evet; yalnız faiz kalır"],
        ["Cezayı kendiliğinden kaldırır", "Fiili mücbir sebebe dönüştürür", "Cezayı daima yarıya indirir", "Zamanaşımını geçmiş saydırır"],
        "Verginin sonradan tahakkuk ettirilmesi veya tamamlanması, önceden oluşan vergi ziyaı için ceza uygulanmasını engellemez.",
        "Haksız iadenin geri alınması da vergi ziyaı cezasını kendiliğinden ortadan kaldırmaz.",
        "213 sayılı VUK m. 341",
        "medium",
    ),
    r(
        "Mükellef vergi ziyaına sebep olmuş, fiil VUK m. 359 kapsamına girmemiş ve başka bir özel oran da bulunmamaktadır. Temel ceza ne kadardır?",
        "VUK m. 344'te vergi ziyaı cezasının genel ölçüsü hangisidir?",
        "Ziyaa uğratılan verginin bir katı",
        "Verginin bir katı",
        ["Ziyaa uğratılan verginin yarısı", "Ziyaa uğratılan verginin iki katı", "Ziyaa uğratılan verginin üç katı", "Sabit bir usulsüzlük tutarı"],
        ["Verginin yüzde onu", "Verginin yarısı", "Verginin iki katı", "Verginin üç katı"],
        "Özel hâller dışında vergi ziyaı cezası, ziyaa uğratılan verginin bir katı tutarındadır.",
        "Genel ceza ölçüsü vergi kaybının bir katıdır; m. 359 ve diğer özel hükümler ayrıca değerlendirilir.",
        "213 sayılı VUK m. 344/1",
        "easy",
    ),
    r(
        "Vergi ziyaına VUK m. 359'da sayılan kaçakçılık fiiliyle sebebiyet verilmiştir. Vergi ziyaı cezası hangi kat üzerinden uygulanır?",
        "VUK m. 359 kapsamındaki fiile iştirak eden kişi için vergi ziyaı cezası kaç kat uygulanır?",
        "Üç kat",
        "Bir kat",
        ["Yarım kat", "Bir kat", "İki kat", "Dört kat"],
        ["Yarım kat", "İki kat", "Üç kat", "Dört kat"],
        "Vergi ziyaına m. 359 fiiliyle sebebiyet verilmesi hâlinde vergi ziyaı cezası üç kat uygulanır.",
        "Kaçakçılık fiiline iştirak eden kişi yönünden vergi ziyaı cezası bir kat uygulanır.",
        "213 sayılı VUK m. 344/2",
        "easy",
    ),
    r(
        "Beyanname kanuni süresinden sonra fakat vergi incelemesi başlamadan ve takdir komisyonuna sevkten önce kendiliğinden verilmiştir. Vergi ziyaı cezası hangi oranda uygulanır?",
        "İnceleme başladıktan sonra verilen geç beyanname, VUK m. 344'teki yüzde ellilik ceza oranından yararlanır mı?",
        "Genel cezanın yüzde ellisi oranında",
        "Hayır; yüzde ellilik oran uygulanmaz",
        ["Genel cezanın yüzde yirmisi oranında", "Genel cezanın tamamı kadar", "Genel cezanın iki katı oranında", "Ceza hiç kesilmeden"],
        ["Evet; inceleme tarihi sonucu değiştirmez", "Evet; ceza tamamen kaldırılır", "Hayır; ceza her durumda üç kat olur", "Evet; yalnız usulsüzlük cezası kesilir"],
        "İnceleme veya takdire sevkten önce kendiliğinden verilen geç beyannamede vergi ziyaı cezası yüzde elli oranında uygulanır.",
        "İnceleme başladıktan veya takdir komisyonuna sevkten sonra verilen geç beyanname bu indirimli oran kapsamı dışındadır.",
        "213 sayılı VUK m. 344/3",
        "medium",
    ),
    r(
        "Mükellefiyet tesis ettirmeden ve vergi dairesinin bilgisi dışında ticari faaliyette bulunularak vergi ziyaına sebep olunmuştur. Vergi ziyaı cezasına ne olur?",
        "Kayıt dışı faaliyete bağlı vergi ziyaında m. 344'te öngörülen ek artırım oranı nedir?",
        "Ceza yüzde elli artırılır",
        "Yüzde elli",
        ["Ceza kendiliğinden kaldırılır", "Ceza yalnız yüzde on artırılır", "Ceza daima yarıya indirilir", "Yalnız genel usulsüzlük uygulanır"],
        ["Yüzde on", "Yüzde yirmi beş", "Yüzde yetmiş beş", "Yüzde yüz"],
        "Mükellefiyet tesis ettirmeksizin idarenin bilgisi dışında yürütülen faaliyetle vergi ziyaı doğarsa hesaplanan vergi ziyaı cezası yüzde elli artırılır.",
        "2024'te eklenen hüküm, kayıt dışı faaliyete bağlı vergi ziyaı cezasına yüzde elli artırım getirir.",
        "213 sayılı VUK m. 344/4",
        "medium",
    ),
    r(
        "Mükellef vergi kanununun yalnız biçim ve usule ilişkin bir hükmüne uymamıştır. Vergi kaybı doğması şart değilse fiil nasıl adlandırılır?",
        "Usulsüzlüğün kanuni tanımı hangisidir?",
        "Usulsüzlük",
        "Şekil ve usul hükümlerine uymama",
        ["Vergi ziyaı", "Mücbir sebep", "Pişmanlık", "Yanılma"],
        ["Verginin eksik tahakkuk ettirilmesi", "Sahte belge düzenlenmesi", "Vergi borcunun zamanında ödenmesi", "Yetkili makamın yanlış izahat vermesi"],
        "Vergi kanunlarının şekle ve usule ilişkin hükümlerine uyulmaması usulsüzlüktür; ayrıca vergi ziyaı aranmaz.",
        "Usulsüzlük, vergi kanunlarının biçim ve usul hükümlerine aykırılığı ifade eder.",
        "213 sayılı VUK m. 351",
        "easy",
    ),
    r(
        "Tutulması zorunlu defterlerden biri hiç tutulmamıştır. VUK m. 352 bakımından fiilin derecesi nedir?",
        "Aşağıdakilerden hangisi birinci derece usulsüzlük örneğidir?",
        "Birinci derece usulsüzlük",
        "İşe başlamanın zamanında bildirilmemesi",
        ["İkinci derece usulsüzlük", "Vergi ziyaı oluşmadan cezasız fiil", "Yalnız özel usulsüzlük", "Mücbir sebep"],
        ["Adres değişikliğinin geç bildirilmesi", "Defter tasdikinin süreden sonra ilk ay içinde yapılması", "Bazı belgelerin doğruluğu bozmadan eksik olması", "Vergi karnesinin on beş gün gecikmesi"],
        "Tutulması zorunlu defterlerden herhangi birinin hiç tutulmaması birinci derece usulsüzlüktür.",
        "İşe başlamanın zamanında bildirilmemesi m. 352'de birinci derece usulsüzlük olarak sayılır.",
        "213 sayılı VUK m. 352/I",
        "easy",
    ),
    r(
        "Tasdiki zorunlu defter, kanuni sürenin bitiminden itibaren yirmi gün sonra tasdik ettirilmiştir. Fiil hangi derecededir?",
        "İşe başlama dışındaki vergi bildirimlerinin zamanında yapılmaması hangi usulsüzlük derecesindedir?",
        "İkinci derece usulsüzlük",
        "İkinci derece usulsüzlük",
        ["Birinci derece usulsüzlük", "Vergi ziyaı cezası", "Kaçakçılık suçu", "Cezayı kaldıran hâl"],
        ["Birinci derece usulsüzlük", "Kaçakçılık suçu", "Vergi ziyaı cezası", "Cezasız işlem"],
        "Tasdikin kanuni süreden sonra fakat bir ay içinde yaptırılması ikinci derece usulsüzlüktür; bir ay geçerse tasdik edilmemiş sayılır.",
        "İşe başlamayı bildirme hariç, vergi kanunlarındaki bildirimlerin geç yapılması ikinci derece usulsüzlüktür.",
        "213 sayılı VUK m. 352/II",
        "medium",
    ),
    r(
        "Düzenlenmesi zorunlu faturada gerçek bedelden farklı bir meblağ gösterilmiştir. Hangi ceza türü gündeme gelir?",
        "Elektronik düzenlenmesi gereken faturanın zorunlu hâl olmaksızın kâğıt düzenlenmesi hangi yaptırım kapsamındadır?",
        "Özel usulsüzlük cezası",
        "Özel usulsüzlük cezası",
        ["Yalnız birinci derece usulsüzlük", "Yalnız gecikme faizi", "Cezayı kaldıran yanılma", "Yalnız mücbir sebep"],
        ["Yalnız ikinci derece usulsüzlük", "Cezasız belge düzeni", "Yalnız vergi aslı", "Mücbir sebep indirimi"],
        "Fatura ve benzeri belgelerde gerçek tutardan farklı meblağ gösterilmesi m. 353 kapsamındaki özel usulsüzlük fiillerindendir.",
        "Elektronik belge zorunluluğuna aykırı biçimde kâğıt belge düzenlemek, kanuni istisna yoksa özel usulsüzlük cezasını gerektirir.",
        "213 sayılı VUK m. 353/1",
        "medium",
    ),
    r(
        "Fatura almak zorunda olan alıcıya fatura verilmemiştir. Alıcı, idare öğrenmeden ve düzenleme süresini izleyen beş iş günü içinde durumu bildirmiştir. Alıcıya ceza kesilir mi?",
        "Belgeyi almak zorunda olanın belgesiz işlemi cezasız bildirebilmesi için kanundaki süre nedir?",
        "Hayır; alıcıya ceza kesilmez",
        "Beş iş günü",
        ["Evet; ceza her durumda kesilir", "Evet; vergi ziyaı cezası üç kat kesilir", "Hayır; satıcıya da hiçbir ceza kesilmez", "Evet; yalnız gecikme faizi kesilir"],
        ["Belge tarihini izleyen bir gün", "Takvim yılının sonuna kadar", "Vergi incelemesi bitene kadar", "Ceza ihbarnamesinden sonra otuz gün"],
        "Belgeyi almak zorunda olan kişi, idare öğrenmeden önce beş iş günlük sürede bildirim yaparsa kendi adına özel usulsüzlük cezası kesilmez.",
        "Süre, belgenin düzenlenmesi gereken tarihi izleyen beş iş günüdür ve bildirim idarenin bilgisinden önce yapılmalıdır.",
        "213 sayılı VUK m. 353/1 ve 3",
        "hard",
    ),
    r(
        "Tek yoklamada aynı türden beş faturanın düzenlenmediği belirlenmiştir. Özel usulsüzlük cezası ve tespit sayısı nasıl değerlendirilir?",
        "Tek tespitte aynı türden birden fazla belgenin düzenlenmediği saptanırsa her belge yönünden temel ilke hangisidir?",
        "Her belgeye ceza; cetvel için tek tespit",
        "Her belge için ayrı ceza kesilir",
        ["Bütün belgeler için tek ceza ve beş tespit", "Yalnız ilk belge için ceza ve tek tespit", "Hiç ceza kesilmez ve tespit oluşmaz", "Her belgeye ceza ve her belge ayrı tespit"],
        ["Bütün belgeler tek cezada birleşir", "Yalnız ilk belge cezalandırılır", "Yalnız son belge cezalandırılır", "Belge sayısı cezada dikkate alınmaz"],
        "Her belge için ayrı ceza kesilir; ancak sonraki tespitlerde artan cetvel tutarını belirlemek bakımından bu yoklama tek tespit sayılır.",
        "Tek tespitteki belge çokluğu her belge için cezayı ortadan kaldırmaz; tespit basamağı yönünden tek olay kabul edilir.",
        "213 sayılı VUK m. 353/1-2",
        "hard",
    ),
    r(
        "Muhasebe standartları ve tek düzen hesap planına ilişkin zorunlu kurallara uyulmaması sonucu ayrıca vergi ziyaı da oluşmuştur. Özel usulsüzlük ile vergi ziyaı cezası birlikte uygulanabilir mi?",
        "VUK m. 353 kapsamındaki özel usulsüzlük sonucunda vergi ziyaı oluşursa m. 336'daki yalnız ağır cezayı uygulama kuralı geçerli midir?",
        "Evet; vergi ziyaı cezası ayrıca kesilir",
        "Hayır; m. 336 uygulanmaz",
        ["Hayır; yalnız özel usulsüzlük kesilir", "Hayır; yalnız vergi ziyaı cezası kesilir", "Evet; fakat iki ceza da yarıya iner", "Hayır; iki fiil de cezasız kalır"],
        ["Evet; yalnız ağır ceza kesilir", "Evet; cezalar aritmetik ortalamaya alınır", "Evet; yalnız usulsüzlük cezası kalır", "Hayır; vergi ziyaı cezası da kesilmez"],
        "M. 353 kapsamındaki özel usulsüzlük vergi ziyaına da yol açmışsa vergi ziyaı cezası ayrıca kesilir.",
        "Özel usulsüzlük ile vergi ziyaının birlikte gerçekleşmesinde m. 353 özel hükmü nedeniyle m. 336 uygulanmaz.",
        "213 sayılı VUK m. 353 son fıkra",
        "hard",
    ),
    r(
        "Belge gerçek bir işleme dayanmakta, ancak işlemin miktarını gerçeğe aykırı göstermektedir. VUK m. 359 bakımından belge nasıl nitelendirilir?",
        "Hiç gerçekleşmemiş bir işlem varmış gibi düzenlenen belge VUK m. 359'a göre nedir?",
        "Yanıltıcı belge",
        "Sahte belge",
        ["Sahte belge", "Perakende satış belgesi", "Gider pusulası", "Tahakkuk fişi"],
        ["Yanıltıcı belge", "Eksik şekilli fatura", "Gider pusulası", "Tahakkuk fişi"],
        "Gerçek bir işlem bulunmasına rağmen mahiyet veya miktarın gerçeğe aykırı yansıtıldığı belge muhteviyatı itibarıyla yanıltıcıdır.",
        "Gerçek bir işlem veya durum olmadığı hâlde varmış gibi düzenlenen belge sahte belgedir.",
        "213 sayılı VUK m. 359/a-b",
        "medium",
    ),
    r(
        "Vergi incelemesinde ceza gerektiren olay tespit edilmiştir. İdari vergi cezasını hangi vergi dairesi keser?",
        "Kesilen vergi cezası ilgiliye hangi belgeyle tebliğ edilir?",
        "Bağlı vergi dairesi",
        "Ceza ihbarnamesi",
        ["Herhangi bir belediye", "Ticaret sicili müdürlüğü", "Vergi mahkemesi", "Cumhuriyet başsavcılığı"],
        ["Tahakkuk fişi", "Yoklama fişi", "Ödeme makbuzu", "Uzlaşma tutanağı"],
        "Vergi cezasını, olayın ilgili olduğu vergi bakımından mükellefin bağlı bulunduğu vergi dairesi keser.",
        "İdari vergi cezaları ilgililere ceza ihbarnamesiyle tebliğ edilir.",
        "213 sayılı VUK m. 364-366",
        "easy",
    ),
    r(
        "Ceza ihbarnamesine karşı dava açılmamıştır. Vergi cezası hangi sürede ödenir?",
        "Yetkili makamın mükellefin kendisine yazıyla yanlış izahat vermesi hâlinde ceza ve gecikme faizi bakımından sonuç nedir?",
        "Bir ay içinde",
        "Ceza kesilmez ve gecikme faizi hesaplanmaz",
        ["Tebliğ günü içinde", "On beş gün içinde", "Üç ay içinde", "Hesap dönemi sonunda"],
        ["Ceza üç kat kesilir", "Yalnız gecikme faizi hesaplanır", "Ceza kesilir fakat vergi silinir", "Yalnız usulsüzlük cezası iki kat kesilir"],
        "Dava açılmayan ceza, dava açma süresinin sona erdiği tarihten başlayarak bir ay içinde ödenir.",
        "Yetkili makamın mükellefe yazılı yanlış izahatı nedeniyle vergi cezası kesilmez ve gecikme faizi hesaplanmaz.",
        "213 sayılı VUK m. 368-369",
        "medium",
    ),
    r(
        "Mükellef beyana dayanan vergideki aykırı fiilini, inceleme başlamadan ve önceden ihbar bulunmadan kendiliğinden bildirmiştir. Pişmanlıktan yararlanmak için eksik beyanını hangi sürede düzeltmelidir?",
        "VUK m. 371'deki pişmanlık hükümleri aşağıdaki vergilerden hangisine uygulanmaz?",
        "On beş gün",
        "Emlak vergisi",
        ["Beş iş günü", "Otuz gün", "Kırk beş gün", "Üç ay"],
        ["Gelir vergisi", "Kurumlar vergisi", "Katma değer vergisi", "Damga vergisi"],
        "Pişmanlıkta hiç verilmemiş beyanname on beş günde verilir; eksik veya yanlış beyan da haber verme tarihinden itibaren on beş günde düzeltilir.",
        "VUK m. 371'deki pişmanlık ve ıslah hükümleri emlak vergisi bakımından uygulanmaz.",
        "213 sayılı VUK m. 371",
        "medium",
    ),
    r(
        "Vergi cezası kesinleştikten sonra mükellef ölmüştür. Ceza mirasçılardan tahsil edilir mi?",
        "VUK'ta düzenlenen mücbir sebebin varlığı biliniyor veya ispatlanıyorsa vergi cezası bakımından sonuç nedir?",
        "Hayır; ölüm hâlinde vergi cezası düşer",
        "Vergi cezası kesilmez",
        ["Evet; mirasçılar her durumda öder", "Evet; ceza iki kat tahsil edilir", "Hayır; yalnız vergi aslı da düşer", "Evet; yalnız gecikme faiziyle tahsil edilir"],
        ["Ceza üç kat uygulanır", "Yalnız usulsüzlük cezası kesilir", "Ceza zamanaşımı uzatılır", "Ceza otomatik vergi ziyaına dönüşür"],
        "Vergi cezası şahsidir; mükellefin ölümüyle ceza düşer ve mirasçılara geçmez.",
        "Kanundaki mücbir sebep biliniyor veya kanıtlanıyorsa vergi cezası kesilmez.",
        "213 sayılı VUK m. 372-373",
        "easy",
    ),
]


PREMISES = [
    {"stem":"Ceza birleşmesi bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Tek fiille farklı vergiler ziyaa uğrarsa her vergi için ayrı ceza kesilir\n\nII. Tek fiilde vergi ziyaı ve genel usulsüzlük birleşirse yalnız ağır ceza kesilir\n\nIII. Ayrı fiiller her durumda tek cezada birleştirilir","correct":"I ve II","why":"Farklı vergilerin ziyaı ayrı cezalandırılır; tek fiilde vergi ziyaı ve genel usulsüzlükte ağır olan uygulanır. Ayrı fiiller kural olarak ayrı cezayı gerektirir.","ref":"213 sayılı VUK m. 335-337","difficulty":"hard"},
    {"stem":"Vergi ziyaı cezası bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Genel ceza ziyaa uğratılan verginin bir katıdır\n\nII. M. 359 fiiliyle oluşan ziya için ceza üç kattır\n\nIII. M. 359 fiiline iştirak eden için ceza bir kattır","correct":"I, II ve III","why":"Üç oran da VUK m. 344'teki genel, kaçakçılık fiili ve iştirak düzenine uygundur.","ref":"213 sayılı VUK m. 344","difficulty":"medium"},
    {"stem":"Genel usulsüzlük dereceleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Zorunlu defterin hiç tutulmaması birinci derecedir\n\nII. İşe başlamanın geç bildirilmesi ikinci derecedir\n\nIII. Diğer değişiklik bildirimlerinin geç yapılması ikinci derecedir","correct":"I ve III","why":"Defterin tutulmaması ve işe başlamanın geç bildirimi birinci derece; işe başlama dışındaki bildirim gecikmeleri ikinci derecedir.","ref":"213 sayılı VUK m. 352","difficulty":"medium"},
    {"stem":"Belge özel usulsüzlükleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gerçek tutardan farklı bedelli fatura özel usulsüzlük doğurur\n\nII. Zorunlu e-faturanın istisnasız kâğıt düzenlenmesi özel usulsüzlük doğurur\n\nIII. Aynı tespitteki çok sayıda belgenin tamamı tek belge sayılır","correct":"I ve II","why":"İlk iki fiil özel usulsüzlüktür. Aynı tespitte her belge için ayrı ceza kesilir; yalnız tespit basamağı tek sayılır.","ref":"213 sayılı VUK m. 353/1","difficulty":"hard"},
    {"stem":"Kaçakçılık ve vergi cezası bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Gerçek işlem miktarını yanlış gösteren belge yanıltıcı olabilir\n\nII. Gerçek olmayan işlem varmış gibi düzenlenen belge sahtedir\n\nIII. Hapis cezası vergi ziyaı cezasının ayrıca uygulanmasını engellemez","correct":"I, II ve III","why":"Belge tanımları ve idari vergi cezasıyla ceza yaptırımının bağımsızlığı VUK m. 359'da açıkça düzenlenmiştir.","ref":"213 sayılı VUK m. 359","difficulty":"medium"},
    {"stem":"Ceza işlemleri bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Cezayı bağlı vergi dairesi keser\n\nII. Ceza yalnız tahakkuk fişiyle bildirilir\n\nIII. Ceza ihbarnamesinde dava açma süresi gösterilir","correct":"I ve III","why":"Cezayı bağlı vergi dairesi keser ve ceza ihbarnamesiyle bildirir; ihbarnamede dava süresi de yer alır.","ref":"213 sayılı VUK m. 365-366","difficulty":"medium"},
    {"stem":"Pişmanlık ve izaha davet bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. İnceleme başladıktan sonra verilen dilekçe pişmanlık şartını sağlamaz\n\nII. Pişmanlıkta beyan ve ödeme için temel süre on beş gündür\n\nIII. İzaha davet edilen kişi davet konusu tespitle sınırlı olarak pişmanlıktan yararlanabilir","correct":"I ve II","why":"Pişmanlık dilekçesi inceleme veya takdire sevkten önce verilir ve on beş günlük beyan/ödeme şartları vardır. İzaha davet edilen, davet konusu tespitle sınırlı olarak pişmanlıktan yararlanamaz.","ref":"213 sayılı VUK m. 370-371","difficulty":"hard"},
    {"stem":"Cezanın kalkması ve zamanaşımı bakımından aşağıdaki ifadelerden hangileri doğrudur?\n\nI. Ölüm hâlinde vergi cezası düşer\n\nII. Mücbir sebep ispatlansa da ceza mutlaka kesilir\n\nIII. Genel usulsüzlük cezasında temel ceza kesme zamanaşımı iki yıldır","correct":"I ve III","why":"Ölüm cezayı düşürür, mücbir sebep ceza kesilmesini önler. Genel usulsüzlükte temel ceza kesme zamanaşımı iki yıldır.","ref":"213 sayılı VUK m. 372-374","difficulty":"medium"},
]


if __name__ == "__main__":
    write_topic(
        lesson_id="vergi_usul_kanunu",
        topic_id="vergi_cezalari",
        label="Vergi Cezaları",
        slug="vergi_cezalari",
        prefix="topic-vuk-vc",
        seed=20260719,
        legislation_version="213 sayılı Vergi Usul Kanunu, 17.07.2026 tarihinde yürürlükteki metin",
        rules=RULES,
        premises=PREMISES,
        wrong_banks={},
    )
